In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Yeast_chemical_inhibits_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_chemical_inhibits_biologicalprocess/Yeast_chemical_inhibits_biologicalprocess.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

# AgeXtend

In [4]:
AgeXtend = pd.read_csv(PROC_DIR + 'agextend_processed/AgeXtend_Yeast_ChemicalEntity_Inhibits_BiologicalProcess.csv')
AgeXtend.columns = AgeXtend.columns.str.lower()
AgeXtend = AgeXtend[~AgeXtend['head_detail_name'].isna()]

AgeXtend['kg_type'] = 'Aging'

print(f"AgeXtend: {len(AgeXtend):,} rows")
AgeXtend['head_id_is'] = 'Pubchem'
AgeXtend['tail_id_is'] = 'Quick_GO'
AgeXtend['kg_source'] = 'AgeXtend'

AgeXtend

AgeXtend: 6 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,tail_detail_name,relation_source,species,data_source,anti_aging_status,anti_aging_prob,kg_type,head_id_is,tail_id_is,kg_source
0,44422965,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2S,4S,5S)-2-[(3S,4S,5R,8R,9R,10R,13R,14R,17S)...",C[C@@]12CC[C@@H]([C@H]1CC[C@H]3[C@]2(CC[C@@H]4...,aging,AgeXtend,Saccharomyces cerevisiae,https://doi.org/10.3390/antiox11122373,1,0.911375,Aging,Pubchem,Quick_GO,AgeXtend
1,156588472,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"2-[(4R,5S,7R,8R,11S,12S,13R)-13,17,18-trihydro...",C1=C(C=C(C(=C1O)O)O)C(=O)OC[C@@H]2[C@@H]3C([C@...,aging,AgeXtend,Saccharomyces cerevisiae,https://doi.org/10.1016/j.mito.2018.07.003,1,0.896472,Aging,Pubchem,Quick_GO,AgeXtend
2,14018348,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"6,9,11-trihydroxy-10-methyl-6H-chromeno[3,4-b]...",CC1=C(C2=C(C=C1O)OC3=C(C2=O)C4=CC=CC=C4OC3O)O,aging,AgeXtend,Saccharomyces cerevisiae,https://doi.org/10.1016/j.mito.2018.07.003,1,0.917628,Aging,Pubchem,Quick_GO,AgeXtend
3,60201866,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(1R,9R,10S)-6-hydroxy-16-methyl-10-[(1E)-3-met...",CC1=C[C@@H]2C3=C(C=CC(=C3)O)O[C@]4(C1)[C@]2(C(...,aging,AgeXtend,Saccharomyces cerevisiae,https://doi.org/10.1155/2021/5469849,1,0.941336,Aging,Pubchem,Quick_GO,AgeXtend
4,15074,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,pyridine-4-carboxamide,C1=CN=CC=C1C(=O)N,aging,AgeXtend,Saccharomyces cerevisiae,https://doi.org/10.1101/2021.07.11.451986,1,0.631007,Aging,Pubchem,Quick_GO,AgeXtend
5,666825,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,6-(furan-2-ylmethylamino)-1H-pyrimidin-2-one,C1=COC(=C1)CNC2=CC=NC(=O)N2,aging,AgeXtend,Saccharomyces cerevisiae,https://doi.org/10.3390/antiox11050850,1,0.731969,Aging,Pubchem,Quick_GO,AgeXtend

# AgingAtlas

In [5]:
AgingAtlas = pd.read_csv(PROC_DIR + 'agingatlas/Yeast/Yeast_AgingAtlas_Chemical_Inhibit_BiologicalProcess_Geroprotectors.csv')
AgingAtlas.columns = AgingAtlas.columns.str.lower()
AgingAtlas = AgingAtlas[~AgingAtlas['head_detail_name'].isna()]

AgingAtlas['kg_type'] = 'Aging'
AgingAtlas['tail_type'] = 'BiologicalProcess'
print(f"AgingAtlas: {len(AgingAtlas):,} rows")
AgingAtlas['head_id_is'] = 'Pubchem'
AgingAtlas['tail_id_is'] = 'Quick_GO'
AgingAtlas['kg_source'] = 'AgingAtlas'
AgingAtlas

AgingAtlas: 10 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,pmid,rnaseq,data_type,tail_detail_name,kg_type,head_id_is,tail_id_is,kg_source
0,2519,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"1,3,7-trimethylpurine-2,6-dione",CN1C=NC2=C1C(=O)N(C(=O)N2C)C,Aging_Atlas_gerprotector,Saccharomyces cerevisiae,Caffeine,18513215,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
1,753,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"propane-1,2,3-triol",C(C(CO)O)O,Aging_Atlas_gerprotector,Saccharomyces cerevisiae,D-glycerol,12391171,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
2,5281614,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"2-(3,4-dihydroxyphenyl)-3,7-dihydroxychromen-4...",C1=CC(=C(C=C1C2=C(C(=O)C3=C(O2)C=C(C=C3)O)O)O)O,Aging_Atlas_gerprotector,Saccharomyces cerevisiae,Fisetin,15254550,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
3,162807,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2S,10S)-17,17-dimethyl-3,12,18-trioxapentacyc...",CC1(C=CC2=C(O1)C=CC3=C2OC[C@@]4([C@H]3OC5=C4C=...,Aging_Atlas_gerprotector,Saccharomyces cerevisiae,Glyceollin I,24399048,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
4,10621,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-5-hydroxy-2-(3-hydroxy-4-methoxyphenyl)-7...,C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC[C@@H]2[...,Aging_Atlas_gerprotector,Saccharomyces cerevisiae,Hesperidin,22484922,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
5,9903,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(4R)-4-[(3R,5R,8R,9S,10S,13R,14S,17R)-3-hydrox...",C[C@H](CCC(=O)O)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3...,Aging_Atlas_gerprotector,Saccharomyces cerevisiae,Lithocholic acid,20622262,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
6,6438394,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(E,2S,3R,4R)-2-amino-3,4-dihydroxy-2-(hydroxym...",CCCCCCC(=O)CCCCCC/C=C/C[C@H]([C@@H]([C@@](CO)(...,Aging_Atlas_gerprotector,Saccharomyces cerevisiae,Myriocin,23725375,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
7,169544354,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(6R)-2-methyl-6-[(1S,2S,4S,6R,8R,9S,12S,13R)-5...",CC1CC[C@@]2(C([C@H]3[C@@H](O2)C[C@@H]4[C@@]3(C...,Aging_Atlas_gerprotector,Saccharomyces cerevisiae,Nolinospiroside F,23439553,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
8,445154,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",C1=CC(=CC=C1/C=C/C2=CC(=CC(=C2)O)O)O,Aging_Atlas_gerprotector,Saccharomyces cerevisiae,Resveratrol,12939617,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
9,1102,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"N'-(3-aminopropyl)butane-1,4-diamine",C(CCNCCCN)CN,Aging_Atlas_gerprotector,Saccharomyces cerevisiae,Spermidine,19801973,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
    AgeXtend, AgingAtlas
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 16

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,44422965,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"(2S,4S,5S)-2-[(3S,4S,5R,8R,9R,10R,13R,14R,17S)...",aging,Saccharomyces cerevisiae
1,156588472,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"2-[(4R,5S,7R,8R,11S,12S,13R)-13,17,18-trihydro...",aging,Saccharomyces cerevisiae
2,14018348,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"6,9,11-trihydroxy-10-methyl-6H-chromeno[3,4-b]...",aging,Saccharomyces cerevisiae
3,60201866,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"(1R,9R,10S)-6-hydroxy-16-methyl-10-[(1E)-3-met...",aging,Saccharomyces cerevisiae
4,15074,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,pyridine-4-carboxamide,aging,Saccharomyces cerevisiae
5,666825,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,6-(furan-2-ylmethylamino)-1H-pyrimidin-2-one,aging,Saccharomyces cerevisiae
6,2519,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"1,3,7-trimethylpurine-2,6-dione",aging,Saccharomyces cerevisiae
7,753,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"propane-1,2,3-triol",aging,Saccharomyces cerevisiae
8,5281614,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"2-(3,4-dihydroxyphenyl)-3,7-dihydroxychromen-4...",aging,Saccharomyces cerevisiae
9,162807,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(2S,10S)-17,17-dimethyl-3,12,18-trioxapentacyc...",aging,Saccharomyces cerevisiae
10,10621,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,(2S)-5-hydroxy-2-(3-hydroxy-4-methoxyphenyl)-7...,aging,Saccharomyces cerevisiae
11,9903,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(4R)-4-[(3R,5R,8R,9S,10S,13R,14S,17R)-3-hydrox...",aging,Saccharomyces cerevisiae
12,6438394,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(E,2S,3R,4R)-2-amino-3,4-dihydroxy-2-(hydroxym...",aging,Saccharomyces cerevisiae
13,169544354,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(6R)-2-methyl-6-[(1S,2S,4S,6R,8R,9S,12S,13R)-5...",aging,Saccharomyces cerevisiae
14,445154,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",aging,Saccharomyces cerevisiae
15,1102,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"N'-(3-aminopropyl)butane-1,4-diamine",aging,Saccharomyces cerevisiae

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'ChemicalEntity_Inhibits_BiologicalProcess'}
head_type           : {'ChemicalEntity'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'AgingAtlas', 'AgeXtend'}
head_id_is          : {'Pubchem'}
tail_id_is          : {'Quick_GO'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 16 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            16                   0              16
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 16  |  After dedup: 16

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,753,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"propane-1,2,3-triol",aging,Saccharomyces cerevisiae
1,1102,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"N'-(3-aminopropyl)butane-1,4-diamine",aging,Saccharomyces cerevisiae
2,2519,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"1,3,7-trimethylpurine-2,6-dione",aging,Saccharomyces cerevisiae

In [11]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            16                   0              16
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'AgingAtlas', 'AgeXtend'} kg_source
AgingAtlas    10
AgeXtend       6
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    16
Name: count, dtype: int64

In [14]:
! mkdir Yeast_chemical_inhibits_biologicalprocess

mkdir: cannot create directory ‘Yeast_chemical_inhibits_biologicalprocess’: File exists

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 16 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_chemical_inhibits_biologicalprocess/Yeast_chemical_inhibits_biologicalprocess.csv

In [16]:
# OUT_PATH