In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast

In [3]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast

In [4]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Yeast_gene_inhibits_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_gene_inhibits_biologicalprocess/Yeast_gene_inhibits_biologicalprocess.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Yeast_gene_inhibits_biologicalprocess’: File exists

In [5]:
#

# Genage

In [6]:
Genage = pd.read_csv(PROC_DIR + 'genage/Yeast/Yeast_Gene_Inhibits_BiologicalProcess.csv')
Genage.columns = Genage.columns.str.lower()
Genage = Genage[~Genage['head_detail_name'].isna()]

Genage['kg_type'] = 'Aging'

print(f"Genage: {len(Genage):,} rows")
Genage['head_id_is'] = 'NCBI_ID'
Genage['tail_id_is'] = 'Quick_GO'
Genage['species'] = 'Saccharomyces cerevisiae'
Genage['kg_source'] = 'Genage'

Genage

Genage: 50 rows

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,relation_source,species,data_type,head_alt_name,kg_type,head_id_is,tail_id_is,kg_source
0,ATP2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,F1F0 ATP synthase subunit beta,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YJR121W,Aging,NCBI_ID,Quick_GO,Genage
1,DNA2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,bifunctional ATP-dependent DNA helicase/ssDNA ...,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YHR164C,Aging,NCBI_ID,Quick_GO,Genage
2,HAP4,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,transcription factor HAP4,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YKL109W,Aging,NCBI_ID,Quick_GO,Genage
3,SRS2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,DNA helicase SRS2,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YJL092W,Aging,NCBI_ID,Quick_GO,Genage
4,HST2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,histone deacetylase HST2,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YPL015C,Aging,NCBI_ID,Quick_GO,Genage
5,LAG2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Lag2p,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YOL025W,Aging,NCBI_ID,Quick_GO,Genage
6,LAT1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,dihydrolipoyllysine-residue acetyltransferase,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YNL071W,Aging,NCBI_ID,Quick_GO,Genage
7,MPT5,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Mpt5p,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YGL178W,Aging,NCBI_ID,Quick_GO,Genage
8,MXR1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,peptide-methionine-S-sulfoxide reductase,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YER042W,Aging,NCBI_ID,Quick_GO,Genage
9,NDE2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,NADH-ubiquinone reductase (H(+)-translocating)...,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YDL085W,Aging,NCBI_ID,Quick_GO,Genage
10,NPT1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,nicotinate phosphoribosyltransferase,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YOR209C,Aging,NCBI_ID,Quick_GO,Genage
11,PHB1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,prohibitin subunit PHB1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YGR132C,Aging,NCBI_ID,Quick_GO,Genage
12,PHB2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,prohibitin subunit PHB2,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YGR231C,Aging,NCBI_ID,Quick_GO,Genage
13,RAD27,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,multifunctional nuclease RAD27,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YKL113C,Aging,NCBI_ID,Quick_GO,Genage
14,SGS1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ATP-dependent DNA helicase SGS1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YMR190C,Aging,NCBI_ID,Quick_GO,Genage
15,SOD1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,superoxide dismutase SOD1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YJR104C,Aging,NCBI_ID,Quick_GO,Genage
16,SOD2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,superoxide dismutase SOD2,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YHR008C,Aging,NCBI_ID,Quick_GO,Genage
17,TLC1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,-,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YNCB0010W,Aging,NCBI_ID,Quick_GO,Genage
18,UMP1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Ump1p,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YBR173C,Aging,NCBI_ID,Quick_GO,Genage
19,PNC1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,nicotinamidase,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YGL037C,Aging,NCBI_ID,Quick_GO,Genage
20,CTR1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,high-affinity Cu transporter CTR1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YPR124W,Aging,NCBI_ID,Quick_GO,Genage
21,ISC1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,inositol phosphosphingolipid phospholipase,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YER019W,Aging,NCBI_ID,Quick_GO,Genage
22,RIF1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,DNA-binding protein RIF1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YBR275C,Aging,NCBI_ID,Quick_GO,Genage
23,PET9,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ADP/ATP carrier protein PET9,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YBL030C,Aging,NCBI_ID,Quick_GO,Genage
24,ACS2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,acetate--CoA ligase ACS2,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YLR153C,Aging,NCBI_ID,Quick_GO,Genage
25,BNA6,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,nicotinate-nucleotide diphosphorylase (carboxy...,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YFR047C,Aging,NCBI_ID,Quick_GO,Genage
26,AAT1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,aspartate transaminase AAT1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YKL106W,Aging,NCBI_ID,Quick_GO,Genage
27,AAT2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,aspartate transaminase AAT2,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YLR027C,Aging,NCBI_ID,Quick_GO,Genage
28,GUT2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,glycerol-3-phosphate dehydrogenase,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YIL155C,Aging,NCBI_ID,Quick_GO,Genage
29,MDH1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,malate dehydrogenase MDH1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YKL085W,Aging,NCBI_ID,Quick_GO,Genage
30,MDH2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,malate dehydrogenase MDH2,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YOL126C,Aging,NCBI_ID,Quick_GO,Genage
31,CTF4,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,chromatin-binding protein CTF4,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YPR135W,Aging,NCBI_ID,Quick_GO,Genage
32,YKL069W,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,L-methionine (R)-S-oxide reductase,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YKL069W,Aging,NCBI_ID,Quick_GO,Genage
33,BIR1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,survivin,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YJR089W,Aging,NCBI_ID,Quick_GO,Genage
34,NMA111,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Nma111p,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YNL123W,Aging,NCBI_ID,Quick_GO,Genage
35,BMH2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,14-3-3 family protein BMH2,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YDR099W,Aging,NCBI_ID,Quick_GO,Genage
36,YFH1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ferroxidase,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YDL120W,Aging,NCBI_ID,Quick_GO,Genage
37,TPO1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,polyamine transporter TPO1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YLL028W,Aging,NCBI_ID,Quick_GO,Genage
38,YOR1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ATP-binding cassette transporter YOR1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YGR281W,Aging,NCBI_ID,Quick_GO,Genage
39,PGA3,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,cytochrome-b5 reductase,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YML125C,Aging,NCBI_ID,Quick_GO,Genage
40,CDC13,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,telomere-binding protein CDC13,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YDL220C,Aging,NCBI_ID,Quick_GO,Genage
41,ZDS2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Zds2p,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YML109W,Aging,NCBI_ID,Quick_GO,Genage
42,NDT80,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,transcription factor NDT80,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YHR124W,Aging,NCBI_ID,Quick_GO,Genage
43,OSH6,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,oxysterol-binding protein OSH6,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YKR003W,Aging,NCBI_ID,Quick_GO,Genage
44,HCM1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Hcm1p,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YCR065W,Aging,NCBI_ID,Quick_GO,Genage
45,MCA1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Ca(2+)-dependent cysteine protease MCA1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YOR197W,Aging,NCBI_ID,Quick_GO,Genage
46,CDC26,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,anaphase promoting complex subunit CDC26,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YFR036W,Aging,NCBI_ID,Quick_GO,Genage
47,APC9,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,anaphase promoting complex subunit 9,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YLR102C,Aging,NCBI_ID,Quick_GO,Genage
48,TSA1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,thioredoxin peroxidase TSA1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YML028W,Aging,NCBI_ID,Quick_GO,Genage
49,PHO84,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,phosphate transporter PHO84,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YML123C,Aging,NCBI_ID,Quick_GO,Genage

# AgingBank

In [7]:
AgingBank = pd.read_csv(PROC_DIR + 'agingbank/yeast_AgingbankGene_inhibits_BioPro.csv')
AgingBank.columns = AgingBank.columns.str.lower()
AgingBank = AgingBank[~AgingBank['head_detail_name'].isna()]

AgingBank['tail_type'] = 'BiologicalProcess'
AgingBank['relation'] = 'Gene_Inhibits_BiologicalProcess'
print(f"AgingBank: {len(AgingBank):,} rows")
AgingBank['head_id_is'] = 'NCBI_ID'
AgingBank['tail_id_is'] = 'Quick_GO'
AgingBank['species'] = 'Saccharomyces cerevisiae'
AgingBank['kg_source'] = 'AgingBank'
AgingBank

AgingBank: 3 rows

,head,relation,tail,head_type,tail_type,kg_source,kg_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_type.1,species
0,FZO1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,mitofusin,aging,NCBI_ID,Quick_GO,Aging,Saccharomyces cerevisiae
1,GCN4,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,amino acid starvation-responsive transcription...,aging,NCBI_ID,Quick_GO,Aging,Saccharomyces cerevisiae
3,SSB2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Hsp70 family ATPase SSB2,aging,NCBI_ID,Quick_GO,Aging,Saccharomyces cerevisiae

# Consolidate into Unified Schem

In [8]:
# List all source DataFrames to include
source_dfs = [
    Genage, AgingBank
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 53

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,ATP2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,F1F0 ATP synthase subunit beta,obsolete aging,Saccharomyces cerevisiae
1,DNA2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,bifunctional ATP-dependent DNA helicase/ssDNA ...,obsolete aging,Saccharomyces cerevisiae
2,HAP4,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,transcription factor HAP4,obsolete aging,Saccharomyces cerevisiae
3,SRS2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,DNA helicase SRS2,obsolete aging,Saccharomyces cerevisiae
4,HST2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,histone deacetylase HST2,obsolete aging,Saccharomyces cerevisiae
5,LAG2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Lag2p,obsolete aging,Saccharomyces cerevisiae
6,LAT1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,dihydrolipoyllysine-residue acetyltransferase,obsolete aging,Saccharomyces cerevisiae
7,MPT5,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Mpt5p,obsolete aging,Saccharomyces cerevisiae
8,MXR1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,peptide-methionine-S-sulfoxide reductase,obsolete aging,Saccharomyces cerevisiae
9,NDE2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,NADH-ubiquinone reductase (H(+)-translocating)...,obsolete aging,Saccharomyces cerevisiae
10,NPT1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,nicotinate phosphoribosyltransferase,obsolete aging,Saccharomyces cerevisiae
11,PHB1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,prohibitin subunit PHB1,obsolete aging,Saccharomyces cerevisiae
12,PHB2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,prohibitin subunit PHB2,obsolete aging,Saccharomyces cerevisiae
13,RAD27,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,multifunctional nuclease RAD27,obsolete aging,Saccharomyces cerevisiae
14,SGS1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,ATP-dependent DNA helicase SGS1,obsolete aging,Saccharomyces cerevisiae
15,SOD1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,superoxide dismutase SOD1,obsolete aging,Saccharomyces cerevisiae
16,SOD2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,superoxide dismutase SOD2,obsolete aging,Saccharomyces cerevisiae
17,TLC1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,-,obsolete aging,Saccharomyces cerevisiae
18,UMP1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Ump1p,obsolete aging,Saccharomyces cerevisiae
19,PNC1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,nicotinamidase,obsolete aging,Saccharomyces cerevisiae
20,CTR1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,high-affinity Cu transporter CTR1,obsolete aging,Saccharomyces cerevisiae
21,ISC1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,inositol phosphosphingolipid phospholipase,obsolete aging,Saccharomyces cerevisiae
22,RIF1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,DNA-binding protein RIF1,obsolete aging,Saccharomyces cerevisiae
23,PET9,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,ADP/ATP carrier protein PET9,obsolete aging,Saccharomyces cerevisiae
24,ACS2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,acetate--CoA ligase ACS2,obsolete aging,Saccharomyces cerevisiae
25,BNA6,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,nicotinate-nucleotide diphosphorylase (carboxy...,obsolete aging,Saccharomyces cerevisiae
26,AAT1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,aspartate transaminase AAT1,obsolete aging,Saccharomyces cerevisiae
27,AAT2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,aspartate transaminase AAT2,obsolete aging,Saccharomyces cerevisiae
28,GUT2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,glycerol-3-phosphate dehydrogenase,obsolete aging,Saccharomyces cerevisiae
29,MDH1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,malate dehydrogenase MDH1,obsolete aging,Saccharomyces cerevisiae
30,MDH2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,malate dehydrogenase MDH2,obsolete aging,Saccharomyces cerevisiae
31,CTF4,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,chromatin-binding protein CTF4,obsolete aging,Saccharomyces cerevisiae
32,YKL069W,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,L-methionine (R)-S-oxide reductase,obsolete aging,Saccharomyces cerevisiae
33,BIR1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,survivin,obsolete aging,Saccharomyces cerevisiae
34,NMA111,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Nma111p,obsolete aging,Saccharomyces cerevisiae
35,BMH2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,14-3-3 family protein BMH2,obsolete aging,Saccharomyces cerevisiae
36,YFH1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,ferroxidase,obsolete aging,Saccharomyces cerevisiae
37,TPO1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,polyamine transporter TPO1,obsolete aging,Saccharomyces cerevisiae
38,YOR1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,ATP-binding cassette transporter YOR1,obsolete aging,Saccharomyces cerevisiae
39,PGA3,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,cytochrome-b5 reductase,obsolete aging,Saccharomyces cerevisiae
40,CDC13,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,telomere-binding protein CDC13,obsolete aging,Saccharomyces cerevisiae
41,ZDS2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Zds2p,obsolete aging,Saccharomyces cerevisiae
42,NDT80,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,transcription factor NDT80,obsolete aging,Saccharomyces cerevisiae
43,OSH6,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,oxysterol-binding protein OSH6,obsolete aging,Saccharomyces cerevisiae
44,HCM1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Hcm1p,obsolete aging,Saccharomyces cerevisiae
45,MCA1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Ca(2+)-dependent cysteine protease MCA1,obsolete aging,Saccharomyces cerevisiae
46,CDC26,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,anaphase promoting complex subunit CDC26,obsolete aging,Saccharomyces cerevisiae
47,APC9,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,anaphase promoting complex subunit 9,obsolete aging,Saccharomyces cerevisiae
48,TSA1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,thioredoxin peroxidase TSA1,obsolete aging,Saccharomyces cerevisiae
49,PHO84,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,phosphate transporter PHO84,obsolete aging,Saccharomyces cerevisiae
50,FZO1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,mitofusin,aging,Saccharomyces cerevisiae
51,GCN4,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,amino acid starvation-responsive transcription...,aging,Saccharomyces cerevisiae
52,SSB2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,Hsp70 family ATPase SSB2,aging,Saccharomyces cerevisiae

# Sanity Check — Distinct Values

In [9]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_Inhibits_BiologicalProcess'}
head_type           : {'Gene'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'AgingBank', 'Genage'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [10]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 53 remaining

# NaN Audit (pre-dedup)

In [11]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            53                   0              53
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [12]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 53  |  After dedup: 53

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,AAT1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,aspartate transaminase AAT1,obsolete aging,Saccharomyces cerevisiae
1,AAT2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,aspartate transaminase AAT2,obsolete aging,Saccharomyces cerevisiae
2,ACS2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,acetate--CoA ligase ACS2,obsolete aging,Saccharomyces cerevisiae

In [13]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            53                   0              53
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'AgingBank', 'Genage'} kg_source
Genage       50
AgingBank     3
Name: count, dtype: int64

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    53
Name: count, dtype: int64

In [16]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 53 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_gene_inhibits_biologicalprocess/Yeast_gene_inhibits_biologicalprocess.csv

In [17]:
# OUT_PATH

In [18]:
# !mkdir Yeast_gene_inhibits_biologicalprocess