In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'


# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

# POSITIVE ASSOCIATION

In [4]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Yeast_chemical_positiveassociated_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_chemical_positiveassociated_biologicalprocess/Yeast_chemical_positiveassociated_biologicalprocess.csv'

### Drugage

In [5]:
Drugage = pd.read_csv(PROC_DIR + 'drugage/drugage_final/Yeast_CE_Pos_BioPro_merged.csv')
Drugage.columns = Drugage.columns.str.lower()
Drugage = Drugage[~Drugage['head_detail_name'].isna()]

Drugage['kg_type'] = 'Aging'

print(f"Drugage: {len(Drugage):,} rows")
Drugage['head_id_is'] = 'Pubchem'
Drugage['tail_id_is'] = 'Quick_GO'
Drugage['relation'] = 'ChemicalEntity_PositivelyAssociatedWith_BiologicalProcess'
Drugage['kg_source'] = 'Drugage'
Drugage['tail_detail_name'] = 'aging'
Drugage

Drugage: 17 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,...,age_at_initiation,treatment_duration,avg_lifespan_change_percent,dosage,pubmed_id,kg_type,head_id_is,tail_id_is,kg_source,tail_detail_name
0,445154,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",C1=CC(=CC=C1/C=C/C2=CC(=CC(=C2)O)O)O,DrugAge,Saccharomyces cerevisiae,Resveratrol,...,NaN,NaN,70.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
1,5281614,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"2-(3,4-dihydroxyphenyl)-3,7-dihydroxychromen-4...",C1=CC(=C(C=C1C2=C(C(=O)C3=C(O2)C=C(C=C3)O)O)O)O,DrugAge,Saccharomyces cerevisiae,Fisetin,...,NaN,NaN,55.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
2,5281222,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(E)-1-(2,4-dihydroxyphenyl)-3-(3,4-dihydroxyph...",C1=CC(=C(C=C1/C=C/C(=O)C2=C(C=C(C=C2)O)O)O)O,DrugAge,Saccharomyces cerevisiae,Butein,...,NaN,NaN,31.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
3,9903,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(4R)-4-[(3R,5R,8R,9S,10S,13R,14S,17R)-3-hydrox...",C[C@H](CCC(=O)O)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3...,DrugAge,Saccharomyces cerevisiae,Lithocholic acid,...,NaN,NaN,100.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
4,6072,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"1-[2,4-dihydroxy-6-[(2S,3R,4S,5S,6R)-3,4,5-tri...",C1=CC(=CC=C1CCC(=O)C2=C(C=C(C=C2O[C@H]3[C@@H](...,DrugAge,Saccharomyces cerevisiae,Phloridzin,...,NaN,NaN,33.33,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
5,10621,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-5-hydroxy-2-(3-hydroxy-4-methoxyphenyl)-7...,C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC[C@@H]2[...,DrugAge,Saccharomyces cerevisiae,Hesperidin,...,NaN,NaN,4.60,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
6,169544354,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(6R)-2-methyl-6-[(1S,2S,4S,6R,8R,9S,12S,13R)-5...",CC1CC[C@@]2(C([C@H]3[C@@H](O2)C[C@@H]4[C@@]3(C...,DrugAge,Saccharomyces cerevisiae,Nolinospiroside F,...,NaN,NaN,22.60,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
7,91437,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(1R,6S)-3-hydroxy-4-methyl-7-oxabicyclo[4.1.0]...",CC1=C(C(=O)[C@H]2[C@@H](C1=O)O2)O,DrugAge,Saccharomyces cerevisiae,Terreic acid,...,NaN,NaN,15.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
8,446541,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,(E)-6-(4-hydroxy-6-methoxy-7-methyl-3-oxo-1H-2...,CC1=C2COC(=O)C2=C(C(=C1OC)C/C=C(\C)/CCC(=O)O)O,DrugAge,Saccharomyces cerevisiae,Mycophenolic acid,...,NaN,NaN,20.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
9,5281316,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"[(E,6R)-6-[(2S,8S,9R,10R,13R,14S,16R,17R)-2,16...",CC(=O)OC(C)(C)/C=C/C(=O)[C@@](C)([C@H]1[C@@H](...,DrugAge,Saccharomyces cerevisiae,Cucurbitacin B,...,NaN,NaN,38.13,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
10,936,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,pyridine-3-carboxamide,C1=CC(=CN=C1)C(=O)N,DrugAge,Saccharomyces cerevisiae,Nicotinamide,...,NaN,NaN,35.96,5 mM,27320176.0,Aging,Pubchem,Quick_GO,Drugage,aging
11,2519,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"1,3,7-trimethylpurine-2,6-dione",CN1C=NC2=C1C(=O)N(C(=O)N2C)C,DrugAge,Saccharomyces cerevisiae,Caffeine,...,NaN,NaN,86.00,0.2-0.4 mM,18513215.0,Aging,Pubchem,Quick_GO,Drugage,aging
12,1102,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"N'-(3-aminopropyl)butane-1,4-diamine",C(CCNCCCN)CN,DrugAge,Saccharomyces cerevisiae,Spermidine,...,NaN,NaN,233.00,4 mM,19801973.0,Aging,Pubchem,Quick_GO,Drugage,aging
13,162807,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2S,10S)-17,17-dimethyl-3,12,18-trioxapentacyc...",CC1(C=CC2=C(O1)C=CC3=C2OC[C@@]4([C@H]3OC5=C4C=...,DrugAge,Saccharomyces cerevisiae,Glyceollin I,...,NaN,NaN,40.00,12.5 nM,24399048.0,Aging,Pubchem,Quick_GO,Drugage,aging
14,1493,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"2,4-dinitrophenol",C1=CC(=C(C=C1[N+](=O)[O-])[N+](=O)[O-])O,DrugAge,Saccharomyces cerevisiae,"2,4-dinitrophenol",...,NaN,NaN,14.71,10 nM,15383542.0,Aging,Pubchem,Quick_GO,Drugage,aging
15,439224,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-(3-aminopropanoylamino)-3-(1H-imidazol-...,C1=C(NC=N1)C[C@@H](C(=O)O)NC(=O)CCN,DrugAge,Saccharomyces cerevisiae,Carnosine,...,NaN,NaN,25.00,20 mM,27040824.0,Aging,Pubchem,Quick_GO,Drugage,aging
16,15103,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-amino-4-methylselanylbutanoic acid,C[Se]CCC(C(=O)O)N,DrugAge,Saccharomyces cerevisiae,Selenomethionine,...,NaN,NaN,30.00,0.00061%,33783357.0,Aging,Pubchem,Quick_GO,Drugage,aging

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
    Drugage
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 17

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,445154,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",aging,Saccharomyces cerevisiae
1,5281614,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"2-(3,4-dihydroxyphenyl)-3,7-dihydroxychromen-4...",aging,Saccharomyces cerevisiae
2,5281222,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(E)-1-(2,4-dihydroxyphenyl)-3-(3,4-dihydroxyph...",aging,Saccharomyces cerevisiae
3,9903,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(4R)-4-[(3R,5R,8R,9S,10S,13R,14S,17R)-3-hydrox...",aging,Saccharomyces cerevisiae
4,6072,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"1-[2,4-dihydroxy-6-[(2S,3R,4S,5S,6R)-3,4,5-tri...",aging,Saccharomyces cerevisiae
5,10621,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,(2S)-5-hydroxy-2-(3-hydroxy-4-methoxyphenyl)-7...,aging,Saccharomyces cerevisiae
6,169544354,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(6R)-2-methyl-6-[(1S,2S,4S,6R,8R,9S,12S,13R)-5...",aging,Saccharomyces cerevisiae
7,91437,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(1R,6S)-3-hydroxy-4-methyl-7-oxabicyclo[4.1.0]...",aging,Saccharomyces cerevisiae
8,446541,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,(E)-6-(4-hydroxy-6-methoxy-7-methyl-3-oxo-1H-2...,aging,Saccharomyces cerevisiae
9,5281316,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"[(E,6R)-6-[(2S,8S,9R,10R,13R,14S,16R,17R)-2,16...",aging,Saccharomyces cerevisiae
10,936,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,pyridine-3-carboxamide,aging,Saccharomyces cerevisiae
11,2519,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"1,3,7-trimethylpurine-2,6-dione",aging,Saccharomyces cerevisiae
12,1102,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"N'-(3-aminopropyl)butane-1,4-diamine",aging,Saccharomyces cerevisiae
13,162807,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2S,10S)-17,17-dimethyl-3,12,18-trioxapentacyc...",aging,Saccharomyces cerevisiae
14,1493,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"2,4-dinitrophenol",aging,Saccharomyces cerevisiae
15,439224,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,(2S)-2-(3-aminopropanoylamino)-3-(1H-imidazol-...,aging,Saccharomyces cerevisiae
16,15103,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-amino-4-methylselanylbutanoic acid,aging,Saccharomyces cerevisiae

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'ChemicalEntity_PositivelyAssociatedWith_BiologicalProcess'}
head_type           : {'ChemicalEntity'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'Drugage'}
head_id_is          : {'Pubchem'}
tail_id_is          : {'Quick_GO'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 17 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            17                   0              17
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 17  |  After dedup: 17

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,936,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,pyridine-3-carboxamide,aging,Saccharomyces cerevisiae
1,1102,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"N'-(3-aminopropyl)butane-1,4-diamine",aging,Saccharomyces cerevisiae
2,1493,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"2,4-dinitrophenol",aging,Saccharomyces cerevisiae

In [11]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            17                   0              17
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Drugage'} kg_source
Drugage    17
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    17
Name: count, dtype: int64

In [14]:
! mkdir Yeast_chemical_positiveassociated_biologicalprocess

mkdir: cannot create directory ‘Yeast_chemical_positiveassociated_biologicalprocess’: File exists

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 17 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_chemical_positiveassociated_biologicalprocess/Yeast_chemical_positiveassociated_biologicalprocess.csv

In [16]:
# OUT_PATH

# NEGATIVE ASSOCIATION

In [17]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Yeast_chemical_negativeassociated_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_chemical_negativeassociated_biologicalprocess/Yeast_chemical_negativeassociated_biologicalprocess.csv'

In [18]:
Drugage = pd.read_csv(PROC_DIR + 'drugage/drugage_final/Yeast_CE_Neg_BioPro_merged.csv')
Drugage.columns = Drugage.columns.str.lower()
Drugage = Drugage[~Drugage['head_detail_name'].isna()]

Drugage['kg_type'] = 'Aging'

print(f"Drugage: {len(Drugage):,} rows")
Drugage['head_id_is'] = 'Pubchem'
Drugage['tail_id_is'] = 'Quick_GO'
Drugage['relation'] = 'ChemicalEntity_NegativelyAssociatedWith_BiologicalProcess'
Drugage['kg_source'] = 'Drugage'
Drugage['tail_detail_name'] = 'aging'
Drugage

Drugage: 1 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,...,age_at_initiation,treatment_duration,avg_lifespan_change_percent,dosage,pubmed_id,kg_type,head_id_is,tail_id_is,kg_source,tail_detail_name
0,445154,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",C1=CC(=CC=C1/C=C/C2=CC(=CC(=C2)O)O)O,DrugAge,Saccharomyces cerevisiae,Resveratrol,...,NaN,NaN,-34.8,100 µM,28412652.0,Aging,Pubchem,Quick_GO,Drugage,aging

In [19]:
# List all source DataFrames to include
source_dfs = [
    Drugage
    
]
aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 1

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,445154,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",aging,Saccharomyces cerevisiae

In [20]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             1                   0               1
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [21]:
# ! mkdir Yeast_chemical_negativeassociated_biologicalprocess

In [22]:
final_df.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df):,} rows → {OUT_PATH}")

Saved 1 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_chemical_negativeassociated_biologicalprocess/Yeast_chemical_negativeassociated_biologicalprocess.csv

# NOT ASSOCIATION

In [23]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Yeast_chemical_notassociated_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_chemical_notassociated_biologicalprocess/Yeast_chemical_notassociated_biologicalprocess.csv'

In [24]:
Drugage = pd.read_csv(PROC_DIR + 'drugage/drugage_final/Yeast_CE_Not_BioPro_merged.csv')
Drugage.columns = Drugage.columns.str.lower()
Drugage = Drugage[~Drugage['head_detail_name'].isna()]

Drugage['kg_type'] = 'Aging'

print(f"Drugage: {len(Drugage):,} rows")
Drugage['head_id_is'] = 'Pubchem'
Drugage['tail_id_is'] = 'Quick_GO'
Drugage['relation'] = 'ChemicalEntity_NotAssociatedWith_BiologicalProcess'
Drugage['kg_source'] = 'Drugage'
Drugage['tail_detail_name'] = 'aging'
Drugage

Drugage: 7 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,...,age_at_initiation,treatment_duration,avg_lifespan_change_percent,dosage,pubmed_id,kg_type,head_id_is,tail_id_is,kg_source,tail_detail_name
0,439213,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"(3R,4R,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)N)O)O)O,DrugAge,Saccharomyces cerevisiae,D-glucosamine,...,NaN,NaN,0.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
1,439924,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"1-[(2R,3R,4S,5R)-3,4-dihydroxy-5-(hydroxymethy...",C1=CC(=C[N+](=C1)[C@H]2[C@@H]([C@@H]([C@H](O2)...,DrugAge,Saccharomyces cerevisiae,Nicotinamide riboside,...,NaN,NaN,20.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
2,10917,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,(3R)-3-hydroxy-4-(trimethylazaniumyl)butanoate,C[N+](C)(C)C[C@@H](CC(=O)[O-])O,DrugAge,Saccharomyces cerevisiae,L-Carnitine,...,NaN,NaN,21.40,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
3,162807,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2S,10S)-17,17-dimethyl-3,12,18-trioxapentacyc...",CC1(C=CC2=C(O1)C=CC3=C2OC[C@@]4([C@H]3OC5=C4C=...,DrugAge,Saccharomyces cerevisiae,Glyceollin I,...,NaN,NaN,NaN,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
4,135398634,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"2-amino-1,7-dihydropurin-6-one",C1=NC2=C(N1)C(=O)NC(=N2)N,DrugAge,Saccharomyces cerevisiae,Guanine,...,NaN,NaN,-2.99,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
5,445154,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",C1=CC(=CC=C1/C=C/C2=CC(=CC(=C2)O)O)O,DrugAge,Saccharomyces cerevisiae,Resveratrol,...,NaN,NaN,0.00,100 mg/ml,15684413.0,Aging,Pubchem,Quick_GO,Drugage,aging
6,6072,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"1-[2,4-dihydroxy-6-[(2S,3R,4S,5S,6R)-3,4,5-tri...",C1=CC(=CC=C1CCC(=O)C2=C(C=C(C=C2O[C@H]3[C@@H](...,DrugAge,Saccharomyces cerevisiae,Phloridzin,...,NaN,NaN,5.79,1 μM,21597195.0,Aging,Pubchem,Quick_GO,Drugage,aging

In [25]:
# List all source DataFrames to include
source_dfs = [
    Drugage
    
]
aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 7

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,439213,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(3R,4R,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",aging,Saccharomyces cerevisiae
1,439924,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"1-[(2R,3R,4S,5R)-3,4-dihydroxy-5-(hydroxymethy...",aging,Saccharomyces cerevisiae
2,10917,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,(3R)-3-hydroxy-4-(trimethylazaniumyl)butanoate,aging,Saccharomyces cerevisiae
3,162807,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2S,10S)-17,17-dimethyl-3,12,18-trioxapentacyc...",aging,Saccharomyces cerevisiae
4,135398634,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"2-amino-1,7-dihydropurin-6-one",aging,Saccharomyces cerevisiae
5,445154,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",aging,Saccharomyces cerevisiae
6,6072,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"1-[2,4-dihydroxy-6-[(2S,3R,4S,5S,6R)-3,4,5-tri...",aging,Saccharomyces cerevisiae

In [26]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             7                   0               7
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [27]:
! mkdir Yeast_chemical_notassociated_biologicalprocess

mkdir: cannot create directory ‘Yeast_chemical_notassociated_biologicalprocess’: File exists

In [28]:
final_df.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df):,} rows → {OUT_PATH}")

Saved 7 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_chemical_notassociated_biologicalprocess/Yeast_chemical_notassociated_biologicalprocess.csv