In [6]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [7]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast

In [23]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'
DB_DIR     = BASE_DIR + 'data_collection/'
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Yeast_chemical_gene
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_chemical_gene/Yeast_chemical_gene.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Yeast_chemical_gene’: File exists

In [24]:
# PubChem compound table: CID → IUPAC name and SMILES
Pubchem = pd.read_pickle(DB_DIR + 'databases_for_mapping/pubchem/combined_df.pkl')
Pubchem_IUPAC_CID_Dict = dict(zip(Pubchem['PUBCHEM_COMPOUND_CID'], Pubchem['PUBCHEM_IUPAC_NAME']))
Pubchem_CID_Smile_Dict = dict(zip(Pubchem['PUBCHEM_COMPOUND_CID'], Pubchem['PUBCHEM_SMILES']))
del Pubchem

print(f"PubChem IUPAC dict: {len(Pubchem_IUPAC_CID_Dict):,} entries")

PubChem IUPAC dict: 119,177,440 entries

In [10]:
Yeast = pd.read_csv(
    f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Saccharomyces_cerevisiae.gene_info',
    sep='\t',
    
)
Yeast["LocusTag"] = Yeast["LocusTag"].str.replace("Dmel_", "", regex=False)

Yeast_symbol2Locus_dict = dict(zip(Yeast['Symbol'], Yeast['LocusTag']))
Yeast
Yeast_symbol2Locus_dict

{'NEWENTRY': '-',
 'atp6': 'ACI60_gp06',
 'ACI60_gt03': 'ACI60_gt03',
 'ACI60_gt04': 'ACI60_gt04',
 'ACI60_gr01': 'ACI60_gr01',
 'ACI60_gt21': 'ACI60_gt21',
 'ACI60_gt24': 'ACI60_gt24',
 'atp9': 'ACI60_gp04',
 'atp8': 'ACI60_gp07',
 'ACI60_gr02': 'ACI60_gr02',
 'ACI60_gt02': 'ACI60_gt02',
 'cox1': 'ACI60_gp08',
 'cytb': 'ACI60_gp05',
 'rps3': 'ACI60_gp03',
 'ACI60_gt05': 'ACI60_gt05',
 'ACI60_gt06': 'ACI60_gt06',
 'ACI60_gt07': 'ACI60_gt07',
 'ACI60_gt08': 'ACI60_gt08',
 'ACI60_gt09': 'ACI60_gt09',
 'ACI60_gt10': 'ACI60_gt10',
 'ACI60_gt11': 'ACI60_gt11',
 'ACI60_gt12': 'ACI60_gt12',
 'ACI60_gt13': 'ACI60_gt13',
 'ACI60_gt14': 'ACI60_gt14',
 'ACI60_gt15': 'ACI60_gt15',
 'ACI60_gt16': 'ACI60_gt16',
 'ACI60_gt17': 'ACI60_gt17',
 'ACI60_gt18': 'ACI60_gt18',
 'ACI60_gt19': 'ACI60_gt19',
 'ACI60_gt20': 'ACI60_gt20',
 'cox2': 'ACI60_gp02',
 'ACI60_gt22': 'ACI60_gt22',
 'ACI60_gt23': 'ACI60_gt23',
 'cox3': 'ACI60_gp01',
 'ACI60_gs01': 'ACI60_gs01',
 'ACI60_gt01': 'ACI60_gt01',
 'YCL075W': 'YCL075W',
 'YCL074W': 'YCL074W',
 'GEX1': 'YCL073C',
 'VBA3': 'YCL069W',
 'YCL068C': 'YCL068C',
 'HMLALPHA2': 'YCL067C',
 'HMLALPHA1': 'YCL066W',
 'CHA1': 'YCL064C',
 'VAC17': 'YCL063W',
 'MRC1': 'YCL061C',
 'KRR1': 'YCL059C',
 'FYV5': 'YCL058C',
 'MIC10': 'YCL057C-A',
 'PRD1': 'YCL057W',
 'PEX34': 'YCL056C',
 'KAR4': 'YCL055W',
 'SPB1': 'YCL054W',
 'PBN1': 'YCL052C',
 'LRE1': 'YCL051W',
 'APA1': 'YCL050C',
 'YCL049C': 'YCL049C',
 'SPS22': 'YCL048W',
 'POF1': 'YCL047C',
 'EMC1': 'YCL045C',
 'MGR1': 'YCL044C',
 'PDI1': 'YCL043C',
 'YCL042W': 'YCL042W',
 'GLK1': 'YCL040W',
 'GID7': 'YCL039W',
 'ATG22': 'YCL038C',
 'SRO9': 'YCL037C',
 'GFD2': 'YCL036W',
 'GRX1': 'YCL035C',
 'LSB5': 'YCL034W',
 'MXR2': 'YCL033C',
 'STE50': 'YCL032W',
 'RRP7': 'YCL031C',
 'HIS4': 'YCL030C',
 'BIK1': 'YCL029C',
 'RNQ1': 'YCL028W',
 'FUS1': 'YCL027W',
 'HBN1': 'YCL026C-B',
 'FRM2': 'YCL026C-A',
 'AGP1': 'YCL025C',
 'KCC4': 'YCL024W',
 'YNCC0001C': 'YNCC0001C',
 'YCL021W-A': 'YCL021W-A',
 'YCL020W': 'YCL020W',
 'YCL019W': 'YCL019W',
 'SUP53': 'YNCC0002W',
 'LEU2': 'YCL018W',
 'NFS1': 'YCL017C',
 'DCC1': 'YCL016C',
 'BUD3': 'YCL014W',
 'GBP2': 'YCL011C',
 'SGF29': 'YCL010C',
 'ILV6': 'YCL009C',
 'STP22': 'YCL008C',
 'LDB16': 'YCL005W',
 'PGS1': 'YCL004W',
 'YCL002C': 'YCL002C',
 'RER1': 'YCL001W',
 'YCL001W-A': 'YCL001W-A',
 'YCL001W-B': 'YCL001W-B',
 'YCR001W': 'YCR001W',
 'CDC10': 'YCR002C',
 'MRPL32': 'YCR003W',
 'YCP4': 'YCR004C',
 'CIT2': 'YCR005C',
 'YCR006C': 'YCR006C',
 'SUF2': 'YNCC0004C',
 'DFP3': 'YCR007C',
 'YNCC0005W': 'YNCC0005W',
 'SAT4': 'YCR008W',
 'RVS161': 'YCR009C',
 'ADY2': 'YCR010C',
 'ADP1': 'YCR011C',
 'PGK1': 'YCR012W',
 'POL4': 'YCR014C',
 'CTO1': 'YCR015C',
 'SUF16': 'YNCC0007C',
 'RBP95': 'YCR016W',
 'CWH43': 'YCR017C',
 'SRD1': 'YCR018C',
 'YNCC0008W': 'YNCC0008W',
 'YNCC0009C': 'YNCC0009C',
 'MAK32': 'YCR019W',
 'PET18': 'YCR020C',
 'MAK31': 'YCR020C-A',
 'HTL1': 'YCR020W-B',
 'HSP30': 'YCR021C',
 'YCR022C': 'YCR022C',
 'YCR023C': 'YCR023C',
 'SLM5': 'YCR024C',
 'PMP1': 'YCR024C-A',
 'YCR025C': 'YCR025C',
 'NPP1': 'YCR026C',
 'RHB1': 'YCR027C',
 'YNCC0010C': 'YNCC0010C',
 'FEN2': 'YCR028C',
 'RIM1': 'YCR028C-A',
 'SYP1': 'YCR030C',
 'RPS14A': 'YCR031C',
 'BPH1': 'YCR032W',
 'SNT1': 'YCR033W',
 'ELO2': 'YCR034W',
 'RRP43': 'YCR035C',
 'RBK1': 'YCR036W',
 'PHO87': 'YCR037C',
 'BUD5': 'YCR038C',
 'MATALPHA2': 'YCR039C',
 'MATALPHA1': 'YCR040W',
 'YCR041W': 'YCR041W',
 'TAF2': 'YCR042C',
 'YCR043C': 'YCR043C',
 'PER1': 'YCR044C',
 'RRT12': 'YCR045C',
 'IMG1': 'YCR046C',
 'BUD23': 'YCR047C',
 'ARE1': 'YCR048W',
 'YCR050C': 'YCR050C',
 'YCR051W': 'YCR051W',
 'RSC6': 'YCR052W',
 'THR4': 'YCR053W',
 'CTR86': 'YCR054C',
 'PWP2': 'YCR057C',
 'YIH1': 'YCR059C',
 'TAH1': 'YCR060W',
 'TVS1': 'YCR061W',
 'SUP61': 'YNCC0013W',
 'BUD31': 'YCR063W',
 'HCM1': 'YCR065W',
 'RAD18': 'YCR066W',
 'SED4': 'YCR067C',
 'ATG15': 'YCR068W',
 'CPR4': 'YCR069W',
 'IMG2': 'YCR071C',
 'RSA4': 'YCR072C',
 'SSK22': 'YCR073C',
 'SOL2': 'YCR073W-A',
 'ERS1': 'YCR075C',
 'FUB1': 'YCR076C',
 'PAT1': 'YCR077C',
 'PTC6': 'YCR079W',
 'SRB8': 'YCR081W',
 'AHC2': 'YCR082W',
 'TRX3': 'YCR083W',
 'TUP1': 'YCR084C',
 'YCR085W': 'YCR085W',
 'CSM1': 'YCR086W',
 'YCR087C-A': 'YCR087C-A',
 'ABP1': 'YCR088W',
 'FIG2': 'YCR089W',
 'YCR090C': 'YCR090C',
 'KIN82': 'YCR091W',
 'MSH3': 'YCR092C',
 'CDC39': 'YCR093W',
 'CDC50': 'YCR094W',
 'OCA4': 'YCR095C',
 'HMRA2': 'YCR096C',
 'HMRA1': 'YCR097W',
 'YNCC0014W': 'YNCC0014W',
 'GIT1': 'YCR098C',
 'YCR099C': 'YCR099C',
 'EMA35': 'YCR100C',
 'YCR101C': 'YCR101C',
 'YCR102C': 'YCR102C',
 'PAU3': 'YCR104W',
 'ADH7': 'YCR105W',
 'RDS1': 'YCR106W',
 'AAD3': 'YCR107W',
 'YFL068W': 'YFL068W',
 'YFL067W': 'YFL067W',
 'YFL066C': 'YFL066C',
 'YFL065C': 'YFL065C',
 'YFL064C': 'YFL064C',
 'COS4': 'YFL062W',
 'DDI3': 'YFL061W',
 'SNO3': 'YFL060C',
 'SNZ3': 'YFL059W',
 'THI5': 'YFL058W',
 'AAD6': 'YFL056C',
 'AGP3': 'YFL055W',
 'AQY3': 'YFL054C',
 'DAK2': 'YFL053W',
 'ZNF1': 'YFL052W',
 'YFL051C': 'YFL051C',
 'ALR2': 'YFL050C',
 'SWP82': 'YFL049W',
 'EMP47': 'YFL048C',
 'RGD2': 'YFL047W',
 'FMP32': 'YFL046W',
 'SEC53': 'YFL045C',
 'OTU1': 'YFL044C',
 'LAM5': 'YFL042C',
 'FET5': 'YFL041W',
 'YFL040W': 'YFL040W',
 'ACT1': 'YFL039C',
 'YPT1': 'YFL038C',
 'TUB2': 'YFL037W',
 'RPO41': 'YFL036W',
 'MOB2': 'YFL034C-B',
 'RPL22B': 'YFL034C-A',
 'MIL1': 'YFL034W',
 'RIM15': 'YFL033C',
 'HAC1': 'YFL031W',
 'AGX1': 'YFL030W',
 'CAK1': 'YFL029C',
 'CAF16': 'YFL028C',
 'GYP8': 'YFL027C',
 'STE2': 'YFL026W',
 'BST1': 'YFL025C',
 'EPL1': 'YFL024C',
 'BUD27': 'YFL023W',
 'FRS2': 'YFL022C',
 'GAT1': 'YFL021W',
 'PAU5': 'YFL020C',
 'YFL019C': 'YFL019C',
 'SUF9': 'YNCF0002W',
 'LPD1': 'YFL018C',
 'SMX2': 'YFL017W-A',
 'GNA1': 'YFL017C',
 'MDJ1': 'YFL016C',
 'YFL015C': 'YFL015C',
 'HSP12': 'YFL014W',
 'IES1': 'YFL013C',
 'YFL012W': 'YFL012W',
 'HXT10': 'YFL011W',
 'AUA1': 'YFL010W-A',
 'WWM1': 'YFL010C',
 'CDC4': 'YFL009W',
 'SMC1': 'YFL008W',
 'BLM10': 'YFL007W',
 'SEC4': 'YFL005W',
 'VTC2': 'YFL004W',
 'MSH4': 'YFL003C',
 'YNCF0004C': 'YNCF0004C',
 'YFL002W-B': 'YFL002W-B',
 'YFL002W-A': 'YFL002W-A',
 'SPB4': 'YFL002C',
 'DEG1': 'YFL001W',
 'LOC1': 'YFR001W',
 'NIC96': 'YFR002W',
 'YPI1': 'YFR003C',
 'RPN11': 'YFR004W',
 'SAD1': 'YFR005C',
 'YFR006W': 'YFR006W',
 'YNCF0005C': 'YNCF0005C',
 'YFH7': 'YFR007W',
 'FAR7': 'YFR008W',
 'SUF20': 'YNCF0006W',
 'GCN20': 'YFR009W',
 'UBP6': 'YFR010W',
 'MIC19': 'YFR011C',
 'SUP11': 'YNCF0007W',
 'DCV1': 'YFR012W',
 'YFR012W-A': 'YFR012W-A',
 'IOC3': 'YFR013W',
 'CMK1': 'YFR014C',
 'GSY1': 'YFR015C',
 'AIP5': 'YFR016C',
 'YNCF0008C': 'YNCF0008C',
 'IGD1': 'YFR017C',
 'YFR018C': 'YFR018C',
 'FAB1': 'YFR019W',
 'YNCF0009C': 'YNCF0009C',
 'CSS2': 'YFR020W',
 'ATG18': 'YFR021W',
 'ROG3': 'YFR022W',
 'PES4': 'YFR023W',
 'LSB3': 'YFR024C-A',
 'HIS2': 'YFR025C',
 'YNCF0011C': 'YNCF0011C',
 'ULI1': 'YFR026C',
 'ECO1': 'YFR027W',
 'CDC14': 'YFR028C',
 'SUP6': 'YNCF0012C',
 'PTR3': 'YFR029W',
 'MET10': 'YFR030W',
 'SMC2': 'YFR031C',
 'RPL2A': 'YFR031C-A',
 'RRT5': 'YFR032C',
 'RPL29': 'YFR032C-A',
 'QCR6': 'YFR033C',
 'PHO4': 'YFR034C',
 'YFR035C': 'YFR035C',
 'YNCF0014C': 'YNCF0014C',
 'CDC26': 'YFR036W',
 'RSC8': 'YFR037C',
 'IRC5': 'YFR038W',
 'OSW7': 'YFR039C',
 'SAP155': 'YFR040W',
 'ERJ5': 'YFR041C',
 'KEG1': 'YFR042W',
 'IRC6': 'YFR043C',
 'DUG1': 'YFR044C',
 'MRX20': 'YFR045W',
 'CNN1': 'YFR046C',
 'BNA6': 'YFR047C',
 'RMD8': 'YFR048W',
 'KGD4': 'YFR049W',
 'PRE4': 'YFR050C',
 'RET2': 'YFR051C',
 'RPN12': 'YFR052W',
 'HXK1': 'YFR053C',
 'YFR054C': 'YFR054C',
 'IRC7': 'YFR055W',
 'YFR057W': 'YFR057W',
 'VPS13': 'YLL040C',
 'UBI4': 'YLL039C',
 'ENT4': 'YLL038C',
 'PRP19': 'YLL036C',
 'GRC3': 'YLL035W',
 'RIX7': 'YLL034C',
 'IRC19': 'YLL033W',
 'YLL032C': 'YLL032C',
 'GPI13': 'YLL031C',
 'RRT7': 'YLL030C',
 'FRA1': 'YLL029W',
 'TPO1': 'YLL028W',
 'ISA1': 'YLL027W',
 'HSP104': 'YLL026W',
 'YNCL0001W': 'YNCL0001W',
 'PAU17': 'YLL025W',
 'SSA2': 'YLL024C',
 'POM33': 'YLL023C',
 'HIF1': 'YLL022C',
 'SPA2': 'YLL021W',
 'KNS1': 'YLL019C',
 'COX19': 'YLL018C-A',
 'DPS1': 'YLL018C',
 'SDC25': 'YLL016W',
 'BPT1': 'YLL015W',
 'EMC6': 'YLL014W',
 'PUF3': 'YLL013C',
 'YEH1': 'YLL012W',
 'SOF1': 'YLL011W',
 'PSR1': 'YLL010C',
 'COX17': 'YLL009C',
 'DRS1': 'YLL008W',
 'LMO1': 'YLL007C',
 'MMM1': 'YLL006W',
 'SPO75': 'YLL005C',
 'ORC3': 'YLL004W',
 'SFI1': 'YLL003W',
 'RTT109': 'YLL002W',
 'YLL067C': 'YLL067C',
 'YLL066C': 'YLL066C',
 'PAU18': 'YLL064C',
 'AYT1': 'YLL063C',
 'MHT1': 'YLL062C',
 'MMP1': 'YLL061W',
 'GTT2': 'YLL060C',
 'HSU1': 'YLL058W',
 'JLP1': 'YLL057C',
 'YLL056C': 'YLL056C',
 'YCT1': 'YLL055W',
 'YLL054C': 'YLL054C',
 'YLL053C': 'YLL053C',
 'AQY2': 'YLL052C',
 'FRE6': 'YLL051C',
 'COF1': 'YLL050C',
 'LDB18': 'YLL049W',
 'YBT1': 'YLL048C',
 'RNP1': 'YLL046C',
 'RPL8B': 'YLL045C',
 'FPS1': 'YLL043W',
 'ATG10': 'YLL042C',
 'SDH2': 'YLL041C',
 'DNM1': 'YLL001W',
 'YLR001C': 'YLR001C',
 'NOC3': 'YLR002C',
 'CMS1': 'YLR003C',
 'THI73': 'YLR004C',
 'SSL1': 'YLR005W',
 'SSK1': 'YLR006C',
 'NSE1': 'YLR007W',
 'PAM18': 'YLR008C',
 'RLP24': 'YLR009W',
 'TEN1': 'YLR010C',
 'YNCL0002C': 'YNCL0002C',
 'LOT6': 'YLR011W',
 'YLR012C': 'YLR012C',
 'GAT3': 'YLR013W',
 'PPR1': 'YLR014C',
 'BRE2': 'YLR015W',
 'PML1': 'YLR016C',
 'MEU1': 'YLR017W',
 'POM34': 'YLR018C',
 'PSR2': 'YLR019W',
 'YEH2': 'YLR020C',
 'IRC25': 'YLR021W',
 'SDO1': 'YLR022C',
 'IZH3': 'YLR023C',
 'UBR2': 'YLR024C',
 'SNF7': 'YLR025W',
 'SED5': 'YLR026C',
 'AAT2': 'YLR027C',
 'ADE16': 'YLR028C',
 'RPL15A': 'YLR029C',
 'YLR030W': 'YLR030W',
 'YLR031W': 'YLR031W',
 'RAD5': 'YLR032W',
 'RSC58': 'YLR033W',
 'SMF3': 'YLR034C',
 'MLH2': 'YLR035C',
 'YNCL0004C': 'YNCL0004C',
 'YLR035C-A': 'YLR035C-A',
 'YLR036C': 'YLR036C',
 'PAU23': 'YLR037C',
 'COX12': 'YLR038C',
 'RIC1': 'YLR039C',
 'AFB1': 'YLR040C',
 'NFG1': 'YLR042C',
 'TRX1': 'YLR043C',
 'PDC1': 'YLR044C',
 'STU2': 'YLR045C',
 'YLR046C': 'YLR046C',
 'FRE8': 'YLR047C',
 'RPS0B': 'YLR048W',
 'MLO50': 'YLR049C',
 'EMA19': 'YLR050C',
 'FCF2': 'YLR051C',
 'IES3': 'YLR052W',
 'NRS1': 'YLR053C',
 'OSW2': 'YLR054C',
 'SPT8': 'YLR055C',
 'ERG3': 'YLR056W',
 'MNL2': 'YLR057W',
 'SHM2': 'YLR058C',
 'REX2': 'YLR059C',
 'FRS1': 'YLR060W',
 'RPL22A': 'YLR061W',
 'BMT6': 'YLR063W',
 'PER33': 'YLR064W',
 'SND2': 'YLR065C',
 'SPC3': 'YLR066W',
 'PET309': 'YLR067C',
 'FYV7': 'YLR068W',
 'MEF1': 'YLR069C',
 'XYL2': 'YLR070C',
 'RGR1': 'YLR071C',
 'LAM6': 'YLR072W',
 'RFU1': 'YLR073C',
 'BUD20': 'YLR074C',
 'RPL10': 'YLR075W',
 'FMP25': 'YLR077W',
 'BOS1': 'YLR078C',
 'SIC1': 'YLR079W',
 'EMP46': 'YLR080W',
 'GAL2': 'YLR081W',
 'SRL2': 'YLR082C',
 'EMP70': 'YLR083C',
 'RAX2': 'YLR084C',
 'ARP6': 'YLR085C',
 'SMC4': 'YLR086W',
 'CSF1': 'YLR087C',
 'GAA1': 'YLR088W',
 'ALT1': 'YLR089C',
 'XDJ1': 'YLR090W',
 'GEP5': 'YLR091W',
 'SUL2': 'YLR092W',
 'NYV1': 'YLR093C',
 'GIS3': 'YLR094C',
 'IOC2': 'YLR095C',
 'KIN2': 'YLR096W',
 'HRT3': 'YLR097C',
 'CHA4': 'YLR098C',
 'ICT1': 'YLR099C',
 'MIM2': 'YLR099W-A',
 'ERG27': 'YLR100W',
 'APC9': 'YLR102C',
 'CDC45': 'YLR103C',
 'LCL2': 'YLR104W',
 'SEN2': 'YLR105C',
 'REA1': 'YLR106C',
 'REX3': 'YLR107W',
 'YLR108C': 'YLR108C',
 'AHP1': 'YLR109W',
 'CCW12': 'YLR110C',
 'YLR111W': 'YLR111W',
 'YLR112W': 'YLR112W',
 'HOG1': 'YLR113W',
 'YNCL0007W': 'YNCL0007W',
 'AVL9': 'YLR114C',
 'CFT2': 'YLR115W',
 'MSL5': 'YLR116W',
 'CLF1': 'YLR117C',
 'TML25': 'YLR118C',
 'SRN2': 'YLR119W',
 'YPS1': 'YLR120C',
 'YPS3': 'YLR121C',
 'YLR122C': 'YLR122C',
 'YLR125W': 'YLR125W',
 'YLR126C': 'YLR126C',
 'APC2': 'YLR127C',
 'DCN1': 'YLR128W',
 'DIP2': 'YLR129W',
 'ZRT2': 'YLR130C',
 'ACE2': 'YLR131C',
 'USB1': 'YLR132C',
 'CKI1': 'YLR133W',
 'PDC5': 'YLR134W',
 'SLX4': 'YLR135W',
 'TIS11': 'YLR136C',
 'RKM5': 'YLR137W',
 'NHA1': 'YLR138W',
 'SLS1': 'YLR139C',
 'RRN5': 'YLR141W',
 'PUT1': 'YLR142W',
 'YNCL0008W': 'YNCL0008W',
 'DPH6': 'YLR143W',
 'ACF2': 'YLR144C',
 'RMP1': 'YLR145W',
 'SPE4': 'YLR146C',
 'SMD3': 'YLR147C',
 'PEP3': 'YLR148W',
 'GID11': 'YLR149C',
 'STM1': 'YLR150W',
 'PCD1': 'YLR151C',
 'YLR152C': 'YLR152C',
 'ACS2': 'YLR153C',
 'RNH203': 'YLR154C',
 'YNCL0009C': 'YNCL0009C',
 'TAR1': 'YLR154W-C',
 'ASP3-1': 'YLR155C',
 'YLR156W': 'YLR156W',
 'ASP3-2': 'YLR157C',
 'YLR157C-B': 'YLR157C-B',
 'YLR157C-A': 'YLR157C-A',
 'ASP3-3': 'YLR158C',
 'YLR159W': 'YLR159W',
 'ASP3-4': 'YLR160C',
 'YLR161W': 'YLR161W',
 'YLR162W': 'YLR162W',
 'MAS1': 'YLR163C',
 'SHH4': 'YLR164W',
 'PUS5': 'YLR165C',
 'SEC10': 'YLR166C',
 'RPS31': 'YLR167W',
 'UPS2': 'YLR168C',
 'APS1': 'YLR170C',
 'DPH5': 'YLR172C',
 'TAG1': 'YLR173W',
 'IDP2': 'YLR174W',
 'CBF5': 'YLR175W',
 'RFX1': 'YLR176C',
 'YLR177W': 'YLR177W',
 'TFS1': 'YLR178C',
 'YLR179C': 'YLR179C',
 'SAM1': 'YLR180W',
 'VTA1': 'YLR181C',
 'SWI6': 'YLR182W',
 'TOS4': 'YLR183C',
 'RPL37A': 'YLR185W',
 'EMG1': 'YLR186W',
 'SKG3': 'YLR187W',
 'MDL1': 'YLR188W',
 'ATG26': 'YLR189C',
 'MMR1': 'YLR190W',
 'PEX13': 'YLR191W',
 'HCR1': 'YLR192C',
 'UPS1': 'YLR193C',
 'NCW2': 'YLR194C',
 'NMT1': 'YLR195C',
 'PWP1': 'YLR196W',
 'NOP56': 'YLR197W',
 'PBA1': 'YLR199C',
 'YKE2': 'YLR200W',
 'COQ9': 'YLR201C',
 'MSS51': 'YLR203C',
 'QRI5': 'YLR204W',
 'HMX1': 'YLR205C',
 'ENT2': 'YLR206W',
 'HRD3': 'YLR207W',
 'SEC13': 'YLR208W',
 'PNP1': 'YLR209C',
 'CLB4': 'YLR210W',
 'ATG38': 'YLR211C',
 'TUB4': 'YLR212C',
 'CRR1': 'YLR213C',
 'FRE1': 'YLR214W',
 'CDC123': 'YLR215C',
 'CPR6': 'YLR216C',
 'COA4': 'YLR218C',
 'MSC3': 'YLR219W',
 'CCC1': 'YLR220W',
 'RSA3': 'YLR221C',
 'UTP13': 'YLR222C',
 'IFH1': 'YLR223C',
 'UCC1': 'YLR224W',
 'YLR225C': 'YLR225C',
 'BUR2': 'YLR226W',
 'ADY4': 'YLR227C',
 'YNCL0032C': 'YNCL0032C',
 'YLR227W-A': 'YLR227W-A',
 'YLR227W-B': 'YLR227W-B',
 'ECM22': 'YLR228C',
 'CDC42': 'YLR229C',
 'YNCL0033C': 'YNCL0033C',
 'BNA5': 'YLR231C',
 'EST1': 'YLR233C',
 'TOP3': 'YLR234W',
 'YLR236C': 'YLR236C',
 'THI7': 'YLR237W',
 'FAR10': 'YLR238W',
 'LIP2': 'YLR239C',
 'VPS34': 'YLR240W',
 'CSC1': 'YLR241W',
 'ARV1': 'YLR242C',
 'GPN3': 'YLR243W',
 'MAP1': 'YLR244C',
 'CDD1': 'YLR245C',
 'ERF2': 'YLR246W',
 'YNCL0034W': 'YNCL0034W',
 'IRC20': 'YLR247C',
 'RCK2': 'YLR248W',
 'YEF3': 'YLR249W',
 'SSP120': 'YLR250W',
 'SYM1': 'YLR251W',
 'CQD2': 'YLR253W',
 'NDL1': 'YLR254C',
 'YLR255C': 'YLR255C',
 'HAP1': 'YLR256W',
 'YLR256W-A': 'YLR256W-A',
 'YNCL0035C': 'YNCL0035C',
 'YLR257W': 'YLR257W',
 'GSY2': 'YLR258W',
 'HSP60': 'YLR259C',
 'LCB5': 'YLR260W',
 'VPS63': 'YLR261C',
 'YPT6': 'YLR262C',
 'TMA7': 'YLR262C-A',
 'RED1': 'YLR263W',
 'RPS28B': 'YLR264W',
 'NEJ1': 'YLR265C',
 'PDR8': 'YLR266C',
 'BOP2': 'YLR267W',
 'SEC22': 'YLR268W',
 'DCS1': 'YLR270W',
 'CMG1': 'YLR271W',
 'YCS4': 'YLR272C',
 'YNCL0036C': 'YNCL0036C',
 'PIG1': 'YLR273C',
 'MCM5': 'YLR274W',
 'SMD2': 'YLR275W',
 'DBP9': 'YLR276C',
 'YSH1': 'YLR277C',
 'YLR278C': 'YLR278C',
 'RSO55': 'YLR281C',
 'PUT7': 'YLR283W',
 'ECI1': 'YLR284C',
 'NNT1': 'YLR285W',
 'CTS1': 'YLR286C',
 'YLR287C': 'YLR287C',
 'RPS30A': 'YLR287C-A',
 'MEC3': 'YLR288C',
 'GUF1': 'YLR289W',
 'COQ11': 'YLR290C',
 'GCD7': 'YLR291C',
 'SEC72': 'YLR292C',
 'GSP1': 'YLR293C',
 'ATP14': 'YLR295C',
 'YLR296W': 'YLR296W',
 'YLR297W': 'YLR297W',
 'YHC1': 'YLR298C',
 'ECM38': 'YLR299W',
 'EXG1': 'YLR300W',
 'HRI1': 'YLR301W',
 'YNCL0037W': 'YNCL0037W',
 'MET17': 'YLR303W',
 'YLR302C': 'YLR302C',
 'YNCL0038W': 'YNCL0038W',
 'ACO1': 'YLR304C',
 'STT4': 'YLR305C',
 'UBC12': 'YLR306W',
 'CDA1': 'YLR307W',
 'CDA2': 'YLR308W',
 'IMH1': 'YLR309C',
 'CDC25': 'YLR310C',
 'ATG39': 'YLR312C',
 'MRPL15': 'YLR312W-A',
 'SPH1': 'YLR313C',
 'CDC3': 'YLR314C',
 'NKP2': 'YLR315W',
 'TAD3': 'YLR316C',
 'EST2': 'YLR318W',
 'BUD6': 'YLR319C',
 'MMS22': 'YLR320W',
 'SFH1': 'YLR321C',
 'CWC24': 'YLR323C',
 'PEX30': 'YLR324W',
 'RPL38': 'YLR325C',
 'YLR326W': 'YLR326W',
 'TMA10': 'YLR327C',
 'YNCL0039W': 'YNCL0039W',
 'NMA1': 'YLR328W',
 'REC102': 'YLR329W',
 'CHS5': 'YLR330W',
 'MID2': 'YLR332W',
 'JIP3': 'YLR331C',
 'YNCL0040W': 'YNCL0040W',
 'RPS25B': 'YLR333C',
 'YNCL0044W': 'YNCL0044W',
 'NUP2': 'YLR335W',
 'SGD1': 'YLR336C',
 'VRP1': 'YLR337C',
 'RPP0': 'YLR340W',
 'SPO77': 'YLR341W',
 'FKS1': 'YLR342W',
 'GAS2': 'YLR343W',
 'TRR4': 'YNCL0045W',
 'RPL26A': 'YLR344W',
 'YLR345W': 'YLR345W',
 'CIS1': 'YLR346C',
 'KAP95': 'YLR347C',
 'DIC1': 'YLR348C',
 'ORM2': 'YLR350W',
 'NIT3': 'YLR351C',
 'LUG1': 'YLR352W',
 'BUD8': 'YLR353W',
 'TAL1': 'YLR354C',
 'ILV5': 'YLR355C',
 'ATG33': 'YLR356W',
 'RSC2': 'YLR357W',
 'YLR358C': 'YLR358C',
 'ADE13': 'YLR359W',
 'VPS38': 'YLR360W',
 'DCR2': 'YLR361C',
 'STE11': 'YLR362W',
 'NMD4': 'YLR363C',
 'YLR363W-A': 'YLR363W-A',
 'GRX8': 'YLR364W',
 'YLR365W': 'YLR365W',
 'RPS22B': 'YLR367W',
 'MDM30': 'YLR368W',
 'SSQ1': 'YLR369W',
 'ARC18': 'YLR370C',
 'ROM2': 'YLR371W',
 'ELO3': 'YLR372W',
 'VID22': 'YLR373C',
 'STP3': 'YLR375W',
 'PSY3': 'YLR376C',
 'FBP1': 'YLR377C',
 'YNCL0047W': 'YNCL0047W',
 'SEC61': 'YLR378C',
 'CSR1': 'YLR380W',
 'CTF3': 'YLR381W',
 'NAM2': 'YLR382C',
 'SMC6': 'YLR383W',
 'IKI3': 'YLR384C',
 'SWC7': 'YLR385C',
 'VAC14': 'YLR386W',
 'REH1': 'YLR387C',
 'RPS29A': 'YLR388W',
 'STE23': 'YLR389C',
 'ECM19': 'YLR390W',
 'CCW14': 'YLR390W-A',
 'ART10': 'YLR392C',
 'ATP10': 'YLR393W',
 'CST9': 'YLR394W',
 'COX8': 'YLR395C',
 'VPS33': 'YLR396C',
 'AFG2': 'YLR397C',
 'SKI2': 'YLR398C',
 'BDF1': 'YLR399C',
 'DUS3': 'YLR401C',
 'SFP1': 'YLR403W',
 'SEI1': 'YLR404W',
 'DUS4': 'YLR405W',
 'RPL31B': 'YLR406C',
 'GAG1': 'YLR407W',
 'BLS1': 'YLR408C',
 'UTP21': 'YLR409C',
 'VIP1': 'YLR410W',
 'YLR410W-A': 'YLR410W-A',
 'YLR410W-B': 'YLR410W-B',
 'CTR3': 'YLR411W',
 'BER1': 'YLR412W',
 'INA1': 'YLR413W',
 'PUN1': 'YLR414C',
 'YLR415C': 'YLR415C',
 'VPS36': 'YLR417W',
 'CDC73': 'YLR418C',
 'YLR419W': 'YLR419W',
 'YNCL0049C': 'YNCL0049C',
 'URA4': 'YLR420W',
 'RPN13': 'YLR421C',
 'DCK1': 'YLR422W',
 'ATG17': 'YLR423C',
 'SPP382': 'YLR424W',
 'YNCL0050C': 'YNCL0050C',
 'TUS1': 'YLR425W',
 'TDA5': 'YLR426W',
 'MAG2': 'YLR427W',
 'CRN1': 'YLR429W',
 'SEN1': 'YLR430W',
 'ATG23': 'YLR431C',
 'IMD3': 'YLR432W',
 'CNA1': 'YLR433C',
 'TSR2': 'YLR435W',
 'ECM30': 'YLR436C',
 'DIF1': 'YLR437C',
 'CAR2': 'YLR438W',
 'LSM3': 'YLR438C-A',
 'MRPL4': 'YLR439W',
 'SEC39': 'YLR440C',
 'RPS1A': 'YLR441C',
 'SIR3': 'YLR442C',
 'ECM7': 'YLR443W',
 'GMC2': 'YLR445W',
 'NGK1': 'YLR446W',
 'VMA6': 'YLR447C',
 'RPL6B': 'YLR448W',
 'FPR4': 'YLR449W',
 'HMG2': 'YLR450W',
 'LEU3': 'YLR451W',
 'SST2': 'YLR452C',
 'RIF2': 'YLR453C',
 'FMP27': 'YLR454W',
 'YNCL0051C': 'YNCL0051C',
 'PDP3': 'YLR455W',
 'YLR456W': 'YLR456W',
 'NBP1': 'YLR457C',
 'GAB1': 'YLR459W',
 'YLR460C': 'YLR460C',
 'PAU4': 'YLR461W',
 'YLR462W': 'YLR462W',
 'YLR464W': 'YLR464W',
 'YRF1-4': 'YLR466W',
 'YRF1-5': 'YLR467W',
 'CDC24': 'YAL041W',
 'CLN3': 'YAL040C',
 'CYC3': 'YAL039C',
 'CDC19': 'YAL038W',
 'YAL037W': 'YAL037W',
 'RBG1': 'YAL036C',
 'FUN12': 'YAL035W',
 'MTW1': 'YAL034W-A',
 'FUN19': 'YAL034C',
 'POP5': 'YAL033W',
 'PRP45': 'YAL032C',
 'GIP4': 'YAL031C',
 'SNC1': 'YAL030W',
 'MYO4': 'YAL029C',
 'FRT2': 'YAL028W',
 'SAW1': 'YAL027W',
 'DRS2': 'YAL026C',
 'MAK16': 'YAL025C',
 'LTE1': 'YAL024C',
 'PMT2': 'YAL023C',
 'FUN26': 'YAL022C',
 'CCR4': 'YAL021C',
 'ATS1': 'YAL020C',
 'FUN30': 'YAL019W',
 'LDS1': 'YAL018C',
 'PSK1': 'YAL017W',
 'TPD3': 'YAL016W',
 'NTG1': 'YAL015C',
 'SYN8': 'YAL014C',
 'DEP1': 'YAL013W',
 'CYS3': 'YAL012W',
 'SWC3': 'YAL011W',
 'MDM10': 'YAL010C',
 'SPO7': 'YAL009W',
 'FUN14': 'YAL008W',
 'ERP2': 'YAL007C',
 'TRN1': 'YNCA0002W',
 'PAU8': 'YAL068C',
 'SEO1': 'YAL067C',
 'YAL065C': 'YAL065C',
 'YAL064W-B': 'YAL064W-B',
 'TDA8': 'YAL064C-A',
 'YAL064W': 'YAL064W',
 'FLO9': 'YAL063C',
 'GDH3': 'YAL062W',
 'BDH2': 'YAL061W',
 'BDH1': 'YAL060W',
 'ECM1': 'YAL059W',
 'CNE1': 'YAL058W',
 'GPB2': 'YAL056W',
 'PEX22': 'YAL055W',
 'ACS1': 'YAL054C',
 'FLC2': 'YAL053W',
 'OAF1': 'YAL051W',
 'AIM2': 'YAL049C',
 'GEM1': 'YAL048C',
 'SPC72': 'YAL047C',
 'BOL3': 'YAL046C',
 'BOL1': 'YAL044W-A',
 'GCV3': 'YAL044C',
 'PTA1': 'YAL043C',
 'ERV46': 'YAL042W',
 'SSA1': 'YAL005C',
 'EFB1': 'YAL003W',
 'VPS8': 'YAL002W',
 'TFC3': 'YAL001C',
 'NUP60': 'YAR002W',
 'ERP1': 'YAR002C-A',
 'SWD1': 'YAR003W',
 'RFA1': 'YAR007C',
 'SEN34': 'YAR008W',
 'YAR009C': 'YAR009C',
 'YAR010C': 'YAR010C',

# stitch

In [13]:

stitch = pd.read_csv(PROC_DIR + 'stitch/stitch_YEAST_CHEMICALENTITY_GENE.csv')

stitch.columns = stitch.columns.str.lower()
stitch['tail'] = stitch['tail'].map(Yeast_symbol2Locus_dict).fillna(stitch['tail'])
stitch['kg_type'] = 'Generalised'
stitch['kg_source'] = 'stitch'
stitch['species'] = 'S.cerevisae'
stitch['tail_id_is'] = 'NCBI_ID'

print(f"stitch: {len(stitch):,} rows")
stitch

stitch: 2,052,652 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species,kg_type
0,1,ChemicalEntity_Gene,YAL005C,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,Hsp70 family ATPase SSA1,S.cerevisae,Generalised
1,1,ChemicalEntity_Gene,YAL019W,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,DNA-dependent ATPase FUN30,S.cerevisae,Generalised
2,1,ChemicalEntity_Gene,YAL021C,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,CCR4-NOT core exoribonuclease subunit CCR4,S.cerevisae,Generalised
3,1,ChemicalEntity_Gene,YAL058W,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,calnexin,S.cerevisae,Generalised
4,1,ChemicalEntity_Gene,YAR035W,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,carnitine O-acetyltransferase YAT1,S.cerevisae,Generalised
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2052647,9999811,ChemicalEntity_Gene,YBR160W,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,"3-[[5-[4-(2,3-dihydro-1,4-benzodioxin-6-ylamin...",cyclin-dependent serine/threonine-protein kina...,S.cerevisae,Generalised
2052648,9999811,ChemicalEntity_Gene,YFL029C,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,"3-[[5-[4-(2,3-dihydro-1,4-benzodioxin-6-ylamin...",cyclin-dependent protein kinase-activating kin...,S.cerevisae,Generalised
2052649,9999811,ChemicalEntity_Gene,YPL031C,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,"3-[[5-[4-(2,3-dihydro-1,4-benzodioxin-6-ylamin...",cyclin-dependent serine/threonine-protein kina...,S.cerevisae,Generalised
2052650,9999913,ChemicalEntity_Gene,YCR048W,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,"N-[5-(methanesulfonamido)-4,6-dimethyl-1-propy...",sterol acyltransferase,S.cerevisae,Generalised
2052651,9999913,ChemicalEntity_Gene,YNR019W,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,"N-[5-(methanesulfonamido)-4,6-dimethyl-1-propy...",sterol acyltransferase,S.cerevisae,Generalised

# Consolidate into Unified Schem

In [14]:
# List all source DataFrames to include
source_dfs = [
    stitch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 2,052,652

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,1,ChemicalEntity_Gene,YAL005C,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,Hsp70 family ATPase SSA1,S.cerevisae
1,1,ChemicalEntity_Gene,YAL019W,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,DNA-dependent ATPase FUN30,S.cerevisae
2,1,ChemicalEntity_Gene,YAL021C,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,CCR4-NOT core exoribonuclease subunit CCR4,S.cerevisae
3,1,ChemicalEntity_Gene,YAL058W,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,calnexin,S.cerevisae
4,1,ChemicalEntity_Gene,YAR035W,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,carnitine O-acetyltransferase YAT1,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2052647,9999811,ChemicalEntity_Gene,YBR160W,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,"3-[[5-[4-(2,3-dihydro-1,4-benzodioxin-6-ylamin...",cyclin-dependent serine/threonine-protein kina...,S.cerevisae
2052648,9999811,ChemicalEntity_Gene,YFL029C,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,"3-[[5-[4-(2,3-dihydro-1,4-benzodioxin-6-ylamin...",cyclin-dependent protein kinase-activating kin...,S.cerevisae
2052649,9999811,ChemicalEntity_Gene,YPL031C,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,"3-[[5-[4-(2,3-dihydro-1,4-benzodioxin-6-ylamin...",cyclin-dependent serine/threonine-protein kina...,S.cerevisae
2052650,9999913,ChemicalEntity_Gene,YCR048W,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,"N-[5-(methanesulfonamido)-4,6-dimethyl-1-propy...",sterol acyltransferase,S.cerevisae
2052651,9999913,ChemicalEntity_Gene,YNR019W,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,"N-[5-(methanesulfonamido)-4,6-dimethyl-1-propy...",sterol acyltransferase,S.cerevisae

# Sanity Check — Distinct Values

In [15]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [16]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 2,052,652 remaining

# NaN Audit (pre-dedup)

In [17]:
true_nan   = final_df.isna().sum()
genDR_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type       2052652            2052652         4105304
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name      16031              16031           32062
tail_detail_name          0                  0               0
species                   0                  0               0

# Deduplication

In [18]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 2,052,652  |  After dedup: 2,052,652

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name
0,1,ChemicalEntity_Gene,YAL005C,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,Hsp70 family ATPase SSA1
1,1,ChemicalEntity_Gene,YAL019W,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,DNA-dependent ATPase FUN30
2,1,ChemicalEntity_Gene,YAL021C,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,CCR4-NOT core exoribonuclease subunit CCR4

In [26]:
# 1. Use .loc to target rows where 'head_detail_name' is NaN
# 2. Map the 'CID' (or relevant key column) against your dictionary
# 3. Assign it back to the 'head_detail_name' column

mask = final_df_dedup['head_detail_name'].isna()

final_df_dedup.loc[mask, 'head_detail_name'] = final_df_dedup.loc[mask, 'head_detail_name'].map(Pubchem_IUPAC_CID_Dict)
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name
0,1,ChemicalEntity_Gene,YAL005C,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,Hsp70 family ATPase SSA1
1,1,ChemicalEntity_Gene,YAL019W,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,DNA-dependent ATPase FUN30
2,1,ChemicalEntity_Gene,YAL021C,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,CCR4-NOT core exoribonuclease subunit CCR4
3,1,ChemicalEntity_Gene,YAL058W,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,calnexin
4,1,ChemicalEntity_Gene,YAR035W,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,carnitine O-acetyltransferase YAT1
...,...,...,...,...,...,...,...,...,...,...,...,...
2052647,91758423,ChemicalEntity_Gene,YEL024W,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,"(2R,3R,4R,5R)-2-[(1S,2S,4S,6R)-4-amino-3-[(2R,...",ubiquinol--cytochrome-c reductase catalytic su...
2052648,91758423,ChemicalEntity_Gene,YGR152C,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,"(2R,3R,4R,5R)-2-[(1S,2S,4S,6R)-4-amino-3-[(2R,...",Ras family GTPase RSR1
2052649,91758423,ChemicalEntity_Gene,YNL098C,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,"(2R,3R,4R,5R)-2-[(1S,2S,4S,6R)-4-amino-3-[(2R,...",Ras family GTPase RAS2
2052650,91758423,ChemicalEntity_Gene,YNL131W,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,"(2R,3R,4R,5R)-2-[(1S,2S,4S,6R)-4-amino-3-[(2R,...",Tom22p
2052651,91758423,ChemicalEntity_Gene,YOR101W,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,"(2R,3R,4R,5R)-2-[(1S,2S,4S,6R)-4-amino-3-[(2R,...",Ras family GTPase RAS1

In [27]:
true_nan   = final_df_dedup.isna().sum()
genDR_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type       2052652            2052652         4105304
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name      16031              16031           32062
tail_detail_name          0                  0               0

In [29]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'stitch'} kg_source
stitch    2052652
Name: count, dtype: int64

In [30]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    2052652
Name: count, dtype: int64

In [ ]:
# final_df_dedup[final_df_dedup['head_detail_name'].isna()]

In [31]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 2,052,652 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_chemical_gene/Yeast_chemical_gene.csv