In [19]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [20]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast

In [21]:
! pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast

In [22]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Yeast_gene_promotes_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_gene_promotes_biologicalprocess/Yeast_gene_promotes_biologicalprocess.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Yeast_gene_promotes_biologicalprocess’: File exists

In [23]:
#

# Genage

In [24]:
Genage = pd.read_csv(PROC_DIR + 'genage/Yeast/Yeast_Gene_Promotes_BiologicalProcess.csv')
Genage.columns = Genage.columns.str.lower()
Genage = Genage[~Genage['head_detail_name'].isna()]

Genage['kg_type'] = 'Aging'
Genage['relation'] = 'Gene_Promotes_BiologicalProcess'
print(f"Genage: {len(Genage):,} rows")
Genage['head_id_is'] = 'NCBI_ID'
Genage['tail_id_is'] = 'Quick_GO'
Genage['species'] = 'Saccharomyces cerevisiae'
Genage['kg_source'] = 'Genage'

Genage

Genage: 347 rows

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,relation_source,species,data_type,head_alt_name,kg_type,head_id_is,tail_id_is,kg_source
0,AGP1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,amino acid transporter AGP1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YCL025C,Aging,NCBI_ID,Quick_GO,Genage
1,BRE5,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Bre5p,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YNR051C,Aging,NCBI_ID,Quick_GO,Genage
2,CDC25,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Ras family guanine nucleotide exchange factor ...,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YLR310C,Aging,NCBI_ID,Quick_GO,Genage
3,CDC6,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AAA family ATPase CDC6,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YJL194W,Aging,NCBI_ID,Quick_GO,Genage
4,CLN3,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,cyclin CLN3,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YAL040C,Aging,NCBI_ID,Quick_GO,Genage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,YUR1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,mannosyltransferase YUR1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YJL139C,Aging,NCBI_ID,Quick_GO,Genage
343,SGF11,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,SAGA histone acetyltransferase complex subunit...,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YPL047W,Aging,NCBI_ID,Quick_GO,Genage
344,NAT4,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,N-terminal L-serine N(alpha)-acetyltransferase...,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YMR069W,Aging,NCBI_ID,Quick_GO,Genage
345,CAN1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,arginine permease CAN1,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YEL063C,Aging,NCBI_ID,Quick_GO,Genage
346,RPO31,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,DNA-directed RNA polymerase III core subunit R...,obsolete aging,GeneAge,Saccharomyces cerevisiae,Causative,YOR116C,Aging,NCBI_ID,Quick_GO,Genage

# AgingBank

In [25]:
AgingBank = pd.read_csv(PROC_DIR + 'agingbank/yeast_AgingbankGene_promotes_BioPro.csv')
AgingBank.columns = AgingBank.columns.str.lower()
AgingBank = AgingBank[~AgingBank['head_detail_name'].isna()]

AgingBank['kg_type'] = 'Aging'
AgingBank['relation'] = 'Gene_Promotes_BiologicalProcess'
AgingBank['tail_type'] = 'BiologicalProcess'
print(f"AgingBank: {len(AgingBank):,} rows")
AgingBank['head_id_is'] = 'NCBI_ID'
AgingBank['tail_id_is'] = 'Quick_GO'
AgingBank['species'] = 'Saccharomyces cerevisiae'
AgingBank['kg_source'] = 'AgingBank'
AgingBank

AgingBank: 5 rows

,head,relation,tail,head_type,tail_type,kg_source,kg_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_type.1,species
0,ASF1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,nucleosome assembly factor ASF1,aging,NCBI_ID,Quick_GO,Aging,Saccharomyces cerevisiae
1,SEC27,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,coatomer subunit beta',aging,NCBI_ID,Quick_GO,Aging,Saccharomyces cerevisiae
2,SEC63,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,protein-transporting protein SEC63,aging,NCBI_ID,Quick_GO,Aging,Saccharomyces cerevisiae
3,TRP5,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,tryptophan synthase TRP5,aging,NCBI_ID,Quick_GO,Aging,Saccharomyces cerevisiae
4,ATP2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,F1F0 ATP synthase subunit beta,aging,NCBI_ID,Quick_GO,Aging,Saccharomyces cerevisiae

# Consolidate into Unified Schem

In [26]:
# List all source DataFrames to include
source_dfs = [
    Genage, AgingBank
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 352

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,AGP1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,amino acid transporter AGP1,obsolete aging,Saccharomyces cerevisiae
1,BRE5,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Bre5p,obsolete aging,Saccharomyces cerevisiae
2,CDC25,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Ras family guanine nucleotide exchange factor ...,obsolete aging,Saccharomyces cerevisiae
3,CDC6,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,AAA family ATPase CDC6,obsolete aging,Saccharomyces cerevisiae
4,CLN3,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,cyclin CLN3,obsolete aging,Saccharomyces cerevisiae
...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,ASF1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,nucleosome assembly factor ASF1,aging,Saccharomyces cerevisiae
348,SEC27,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,coatomer subunit beta',aging,Saccharomyces cerevisiae
349,SEC63,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,protein-transporting protein SEC63,aging,Saccharomyces cerevisiae
350,TRP5,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,tryptophan synthase TRP5,aging,Saccharomyces cerevisiae
351,ATP2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,F1F0 ATP synthase subunit beta,aging,Saccharomyces cerevisiae

# Sanity Check — Distinct Values

In [27]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_Promotes_BiologicalProcess'}
head_type           : {'Gene'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'Genage', 'AgingBank'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [28]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 352 remaining

# NaN Audit (pre-dedup)

In [29]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           352                   0             352
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [30]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 352  |  After dedup: 352

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,AAC3,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,ADP/ATP carrier protein AAC3,obsolete aging,Saccharomyces cerevisiae
1,AAH1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,adenine deaminase,obsolete aging,Saccharomyces cerevisiae
2,ABP1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Abp1p,obsolete aging,Saccharomyces cerevisiae

In [31]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           352                   0             352
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [32]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Genage', 'AgingBank'} kg_source
Genage       347
AgingBank      5
Name: count, dtype: int64

In [33]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    352
Name: count, dtype: int64

In [34]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 352 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Yeast/Yeast_gene_promotes_biologicalprocess/Yeast_gene_promotes_biologicalprocess.csv

In [35]:
# OUT_PATH

In [36]:
# ! mkdir Droso_gene_promotes_biologicalprocess