In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_mirna_gene/Zebrafish_mirna_gene.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

In [5]:
# Zebrafish = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Danio_rerio.gene_info',
#     sep='\t',
    
# )
# # Zebrafish["LocusTag"] = Zebrafish["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Zebrafish_symbol2Locus_dict = dict(zip(Zebrafish['Symbol'], Zebrafish['LocusTag']))
# # Zebrafish
# # Zebrafish_symbol2Locus_dict
# Zebrafish

# mirna

In [6]:
mirna = pd.read_csv(PROC_DIR + 'mirTARbase/drer/miRTarBase_Mirna_Gene.csv')

mirna.columns = mirna.columns.str.lower()
mirna = mirna[~mirna['head'].isna()]
mirna = mirna.rename(columns={'headtype': 'head_type', 'tailtype': 'tail_type'})

mirna['kg_type'] = 'Generalised'
mirna['kg_source'] = 'miRTarBase'
mirna['species'] = 'D.rerio'
mirna['tail_id_is'] = 'NCBI_ID'
mirna['head_id_is'] = 'miRTarBase_ID'
print(f"mirna: {len(mirna):,} rows")
mirna

mirna: 208 rows

,head,relation,tail,head_type,tail_type,kg_source,head_detail_name,tail_detail_name,species,kg_type,tail_id_is,head_id_is
0,dre-miR-196b,Mirna_Gene,hoxb8a,Mirna,Gene,miRTarBase,dre-miR-196b,homeobox B8a,D.rerio,Generalised,NCBI_ID,miRTarBase_ID
1,dre-miR-126a-3p,Mirna_Gene,spred1,Mirna,Gene,miRTarBase,dre-miR-126a-3p,sprouty related EVH1 domain containing 1,D.rerio,Generalised,NCBI_ID,miRTarBase_ID
2,dre-miR-126a-3p,Mirna_Gene,pik3r2,Mirna,Gene,miRTarBase,dre-miR-126a-3p,"phosphoinositide-3-kinase, regulatory subunit ...",D.rerio,Generalised,NCBI_ID,miRTarBase_ID
3,dre-miR-214,Mirna_Gene,disp2,Mirna,Gene,miRTarBase,dre-miR-214,dispatched RND transporter family member 2,D.rerio,Generalised,NCBI_ID,miRTarBase_ID
4,dre-miR-214,Mirna_Gene,disp2,Mirna,Gene,miRTarBase,dre-miR-214,dispatched RND transporter family member 2,D.rerio,Generalised,NCBI_ID,miRTarBase_ID
...,...,...,...,...,...,...,...,...,...,...,...,...
203,dre-miR-140-5p,Mirna_Gene,prkaa2,Mirna,Gene,miRTarBase,dre-miR-140-5p,"protein kinase, AMP-activated, alpha 2 catalyt...",D.rerio,Generalised,NCBI_ID,miRTarBase_ID
204,dre-miR-126a-3p,Mirna_Gene,cxcl12a,Mirna,Gene,miRTarBase,dre-miR-126a-3p,chemokine (C-X-C motif) ligand 12a (stromal ce...,D.rerio,Generalised,NCBI_ID,miRTarBase_ID
205,dre-miR-126a-3p,Mirna_Gene,cxcl12a,Mirna,Gene,miRTarBase,dre-miR-126a-3p,chemokine (C-X-C motif) ligand 12a (stromal ce...,D.rerio,Generalised,NCBI_ID,miRTarBase_ID
206,dre-miR-202-5p,Mirna_Gene,cdc42se1,Mirna,Gene,miRTarBase,dre-miR-202-5p,CDC42 small effector 1,D.rerio,Generalised,NCBI_ID,miRTarBase_ID
207,dre-miR-146a,Mirna_Gene,traf6,Mirna,Gene,miRTarBase,dre-miR-146a,TNF receptor-associated factor 6,D.rerio,Generalised,NCBI_ID,miRTarBase_ID

In [7]:
mirna[mirna['head_detail_name'].isna()]

Empty DataFrame
Columns: [head, relation, tail, head_type, tail_type, kg_source, head_detail_name, tail_detail_name, species, kg_type, tail_id_is, head_id_is]
Index: []

# Consolidate into Unified Schem

In [8]:
# List all source DataFrames to include
source_dfs = [
     mirna
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 208

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,dre-miR-196b,Mirna_Gene,hoxb8a,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dre-miR-196b,homeobox B8a,D.rerio
1,dre-miR-126a-3p,Mirna_Gene,spred1,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dre-miR-126a-3p,sprouty related EVH1 domain containing 1,D.rerio
2,dre-miR-126a-3p,Mirna_Gene,pik3r2,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dre-miR-126a-3p,"phosphoinositide-3-kinase, regulatory subunit ...",D.rerio
3,dre-miR-214,Mirna_Gene,disp2,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dre-miR-214,dispatched RND transporter family member 2,D.rerio
4,dre-miR-214,Mirna_Gene,disp2,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dre-miR-214,dispatched RND transporter family member 2,D.rerio
...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,dre-miR-140-5p,Mirna_Gene,prkaa2,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dre-miR-140-5p,"protein kinase, AMP-activated, alpha 2 catalyt...",D.rerio
204,dre-miR-126a-3p,Mirna_Gene,cxcl12a,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dre-miR-126a-3p,chemokine (C-X-C motif) ligand 12a (stromal ce...,D.rerio
205,dre-miR-126a-3p,Mirna_Gene,cxcl12a,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dre-miR-126a-3p,chemokine (C-X-C motif) ligand 12a (stromal ce...,D.rerio
206,dre-miR-202-5p,Mirna_Gene,cdc42se1,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dre-miR-202-5p,CDC42 small effector 1,D.rerio
207,dre-miR-146a,Mirna_Gene,traf6,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dre-miR-146a,TNF receptor-associated factor 6,D.rerio

# Sanity Check — Distinct Values

In [9]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Mirna_Gene'}
head_type           : {'Mirna'}
tail_type           : {'Gene'}
relation_type       : {None}
kg_source           : {'miRTarBase'}
head_id_is          : {'miRTarBase_ID'}
tail_id_is          : {'NCBI_ID'}

In [10]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 208 remaining

# NaN Audit (pre-dedup)

In [11]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           208                   0             208
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [12]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 208  |  After dedup: 113

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,dre-let-7a,Mirna_Gene,ascl1a,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dre-let-7a,achaete-scute family bHLH transcription factor 1a,D.rerio
1,dre-let-7a,Mirna_Gene,hspd1,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dre-let-7a,heat shock 60 protein 1,D.rerio
2,dre-let-7a,Mirna_Gene,myca,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dre-let-7a,"MYC proto-oncogene, bHLH transcription factor a",D.rerio

In [13]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           113                   0             113
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'miRTarBase'} kg_source
miRTarBase    113
Name: count, dtype: int64

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    113
Name: count, dtype: int64

In [16]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 113 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_mirna_gene/Zebrafish_mirna_gene.csv

In [17]:
# OUT_PATH