In [2]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [3]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish

In [4]:
# Monarch/Monarch_final/Zebrafish/GENE_GENE_Zebrafish_Zebrafish.csv
# string/drer/string_Zebra_GENE_GENE.csv

In [5]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_gene_biologicalprocess/Zebrafish_gene_biologicalprocess.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [6]:
#

In [7]:
# Zebrafish = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Danio_rerio.gene_info',
#     sep='\t',
    
# )
# # Zebrafish["LocusTag"] = Zebrafish["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Zebrafish_symbol2Locus_dict = dict(zip(Zebrafish['Symbol'], Zebrafish['LocusTag']))
# # Zebrafish
# # Zebrafish_symbol2Locus_dict
# Zebrafish

# Monarch

In [12]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Zebrafish/Gene_Zebra_BiologicalProcess.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'

monarch['species'] = 'D.rerio'
print(f"monarch: {len(monarch):,} rows")
monarch = monarch[~monarch['head'].str.contains(':')]
monarch

monarch: 90,208 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,pbx1a,Gene_BiologicalProcess,GO:0001654,Gene,actively_involved_in,BiologicalProcess,infores:go-central,pre-B-cell leukemia homeobox 1a,eye development,Danio rerio,NaN,NCBI,Quick_GO,pbx1a,D.rerio,Generalised,Monarch_KG
2,pou3f2b,Gene_BiologicalProcess,GO:0006357,Gene,actively_involved_in,BiologicalProcess,infores:go-central,POU class 3 homeobox 2b,regulation of transcription by RNA polymerase II,Danio rerio,NaN,NCBI,Quick_GO,pou3f2b,D.rerio,Generalised,Monarch_KG
3,flvcr1,Gene_BiologicalProcess,GO:0030218,Gene,actively_involved_in,BiologicalProcess,infores:go-central,FLVCR choline and heme transporter 1,erythrocyte differentiation,Danio rerio,NaN,NCBI,Quick_GO,flvcr1,D.rerio,Generalised,Monarch_KG
4,cpdb,Gene_BiologicalProcess,GO:0006518,Gene,actively_involved_in,BiologicalProcess,infores:go-central,"carboxypeptidase D, b",peptide metabolic process,Danio rerio,NaN,NCBI,Quick_GO,cpdb,D.rerio,Generalised,Monarch_KG
5,emx2,Gene_BiologicalProcess,GO:0007420,Gene,actively_involved_in,BiologicalProcess,infores:go-central,empty spiracles homeobox 2,brain development,Danio rerio,NaN,NCBI,Quick_GO,emx2,D.rerio,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91903,c9,Gene_BiologicalProcess,GO:0006955,Gene,acts_upstream_of_or_within,BiologicalProcess,infores:zfin,complement component 9,immune response,Danio rerio,NaN,NCBI,Quick_GO,c9,D.rerio,Generalised,Monarch_KG
91904,c9,Gene_BiologicalProcess,GO:0006958,Gene,acts_upstream_of_or_within,BiologicalProcess,infores:zfin,complement component 9,"complement activation, classical pathway",Danio rerio,NaN,NCBI,Quick_GO,c9,D.rerio,Generalised,Monarch_KG
91906,rgrb,Gene_BiologicalProcess,GO:0007186,Gene,acts_upstream_of_or_within,BiologicalProcess,infores:zfin,retinal G protein coupled receptor b,G protein-coupled receptor signaling pathway,Danio rerio,NaN,NCBI,Quick_GO,rgrb,D.rerio,Generalised,Monarch_KG
91907,rgrb,Gene_BiologicalProcess,GO:0007186,Gene,acts_upstream_of_or_within,BiologicalProcess,infores:zfin,retinal G protein coupled receptor b,G protein-coupled receptor signaling pathway,Danio rerio,NaN,NCBI,Quick_GO,rgrb,D.rerio,Generalised,Monarch_KG
91908,rgrb,Gene_BiologicalProcess,GO:0007601,Gene,acts_upstream_of_or_within,BiologicalProcess,infores:zfin,retinal G protein coupled receptor b,visual perception,Danio rerio,NaN,NCBI,Quick_GO,rgrb,D.rerio,Generalised,Monarch_KG

In [13]:
monarch[monarch['head_detail_name'].isna()]

Empty DataFrame
Columns: [head, relation, tail, head_type, relation_type, tail_type, relation_source, head_detail_name, tail_detail_name, head_taxon_name, tail_taxon_name, head_id_is, tail_id_is, head_name, species, kg_type, kg_source]
Index: []

In [14]:
# for i, df in enumerate(aligned):
#     dup_cols = df.columns[df.columns.duplicated()]
    
#     if len(dup_cols) > 0:
#         print(f"DF {i} duplicate columns:")
#         print(dup_cols)

# Consolidate into Unified Schem

In [18]:
# List all source DataFrames to include
source_dfs = [
     monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 86,213

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,pbx1a,Gene_BiologicalProcess,GO:0001654,Gene,actively_involved_in,BiologicalProcess,Monarch_KG,Generalised,NCBI,Quick_GO,pre-B-cell leukemia homeobox 1a,eye development,D.rerio
1,pou3f2b,Gene_BiologicalProcess,GO:0006357,Gene,actively_involved_in,BiologicalProcess,Monarch_KG,Generalised,NCBI,Quick_GO,POU class 3 homeobox 2b,regulation of transcription by RNA polymerase II,D.rerio
2,flvcr1,Gene_BiologicalProcess,GO:0030218,Gene,actively_involved_in,BiologicalProcess,Monarch_KG,Generalised,NCBI,Quick_GO,FLVCR choline and heme transporter 1,erythrocyte differentiation,D.rerio
3,cpdb,Gene_BiologicalProcess,GO:0006518,Gene,actively_involved_in,BiologicalProcess,Monarch_KG,Generalised,NCBI,Quick_GO,"carboxypeptidase D, b",peptide metabolic process,D.rerio
4,emx2,Gene_BiologicalProcess,GO:0007420,Gene,actively_involved_in,BiologicalProcess,Monarch_KG,Generalised,NCBI,Quick_GO,empty spiracles homeobox 2,brain development,D.rerio
...,...,...,...,...,...,...,...,...,...,...,...,...,...
86208,c9,Gene_BiologicalProcess,GO:0006955,Gene,acts_upstream_of_or_within,BiologicalProcess,Monarch_KG,Generalised,NCBI,Quick_GO,complement component 9,immune response,D.rerio
86209,c9,Gene_BiologicalProcess,GO:0006958,Gene,acts_upstream_of_or_within,BiologicalProcess,Monarch_KG,Generalised,NCBI,Quick_GO,complement component 9,"complement activation, classical pathway",D.rerio
86210,rgrb,Gene_BiologicalProcess,GO:0007186,Gene,acts_upstream_of_or_within,BiologicalProcess,Monarch_KG,Generalised,NCBI,Quick_GO,retinal G protein coupled receptor b,G protein-coupled receptor signaling pathway,D.rerio
86211,rgrb,Gene_BiologicalProcess,GO:0007186,Gene,acts_upstream_of_or_within,BiologicalProcess,Monarch_KG,Generalised,NCBI,Quick_GO,retinal G protein coupled receptor b,G protein-coupled receptor signaling pathway,D.rerio
86212,rgrb,Gene_BiologicalProcess,GO:0007601,Gene,acts_upstream_of_or_within,BiologicalProcess,Monarch_KG,Generalised,NCBI,Quick_GO,retinal G protein coupled receptor b,visual perception,D.rerio

# Sanity Check — Distinct Values

In [19]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_BiologicalProcess'}
head_type           : {'Gene'}
tail_type           : {'BiologicalProcess'}
relation_type       : {'acts_upstream_of_or_within', 'acts_upstream_of_or_within_positive_effect', 'acts_upstream_of', 'acts_upstream_of_positive_effect', 'actively_involved_in', 'acts_upstream_of_or_within_negative_effect', 'acts_upstream_of_negative_effect'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'NCBI'}
tail_id_is          : {'Quick_GO'}

In [20]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 86,213 remaining

# NaN Audit (pre-dedup)

In [21]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [22]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 86,213  |  After dedup: 61,729

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,ATP6,Gene_BiologicalProcess,GO:0006754,Gene,acts_upstream_of_or_within,BiologicalProcess,Monarch_KG,Generalised,NCBI,Quick_GO,ATP synthase F0 subunit 6,ATP biosynthetic process,D.rerio
1,ATP6,Gene_BiologicalProcess,GO:0006811,Gene,acts_upstream_of_or_within,BiologicalProcess,Monarch_KG,Generalised,NCBI,Quick_GO,ATP synthase F0 subunit 6,monoatomic ion transport,D.rerio
2,ATP6,Gene_BiologicalProcess,GO:0015986,Gene,actively_involved_in,BiologicalProcess,Monarch_KG,Generalised,NCBI,Quick_GO,ATP synthase F0 subunit 6,proton motive force-driven ATP synthesis,D.rerio

In [23]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [24]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    61729
Name: count, dtype: int64

In [25]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    61729
Name: count, dtype: int64

In [26]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 61,729 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_gene_biologicalprocess/Zebrafish_gene_biologicalprocess.csv

In [27]:
# OUT_PATH