In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_gene_anatomy/Zebrafish_gene_anatomy.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

# Monarch

In [5]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Zebrafish/Gene_Zebra_Anatomy.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'
monarch['species'] = 'D.rerio'
monarch['relation'] = 'Gene_AnatomicalEntity'
print(f"monarch: {len(monarch):,} rows")
monarch = monarch[~monarch['head'].str.contains(':')]
monarch

monarch: 521,207 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,myb,Gene_AnatomicalEntity,ZFA:0000033,Gene,expressed_in,AnatomicalEntity,infores:zfin,v-myb avian myeloblastosis viral oncogene homolog,intermediate cell mass of mesoderm,Danio rerio,NaN,NCBI,ZFIN_ID,myb,D.rerio,Generalised,Monarch_KG
1,ptpn12,Gene_AnatomicalEntity,ZFA:0000079,Gene,expressed_in,AnatomicalEntity,infores:zfin,protein tyrosine phosphatase non-receptor type 12,telencephalon,Danio rerio,NaN,NCBI,ZFIN_ID,ptpn12,D.rerio,Generalised,Monarch_KG
2,fgf24,Gene_AnatomicalEntity,ZFA:0001453,Gene,expressed_in,AnatomicalEntity,infores:zfin,fibroblast growth factor 24,pectoral fin field,Danio rerio,NaN,NCBI,ZFIN_ID,fgf24,D.rerio,Generalised,Monarch_KG
3,gata5,Gene_AnatomicalEntity,ZFA:0000038,Gene,expressed_in,AnatomicalEntity,infores:zfin,GATA binding protein 5,margin,Danio rerio,NaN,NCBI,ZFIN_ID,gata5,D.rerio,Generalised,Monarch_KG
4,exo1,Gene_AnatomicalEntity,ZFA:0000098,Gene,expressed_in,AnatomicalEntity,infores:zfin,exonuclease 1,proliferative region,Danio rerio,NaN,NCBI,ZFIN_ID,exo1,D.rerio,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528404,ackr4a,Gene_AnatomicalEntity,ZFA:0001094,Gene,expressed_in,AnatomicalEntity,infores:zfin,atypical chemokine receptor 4a,whole organism,Danio rerio,NaN,NCBI,ZFIN_ID,ackr4a,D.rerio,Generalised,Monarch_KG
528406,kcnk5b,Gene_AnatomicalEntity,ZFA:0001093,Gene,expressed_in,AnatomicalEntity,infores:zfin,"potassium channel, subfamily K, member 5b",unspecified,Danio rerio,NaN,NCBI,ZFIN_ID,kcnk5b,D.rerio,Generalised,Monarch_KG
528407,pik3r4,Gene_AnatomicalEntity,ZFA:0001094,Gene,expressed_in,AnatomicalEntity,infores:zfin,"phosphoinositide-3-kinase, regulatory subunit 4",whole organism,Danio rerio,NaN,NCBI,ZFIN_ID,pik3r4,D.rerio,Generalised,Monarch_KG
528408,ywhaqb,Gene_AnatomicalEntity,ZFA:0001093,Gene,expressed_in,AnatomicalEntity,infores:zfin,tyrosine 3-monooxygenase/tryptophan 5-monooxyg...,unspecified,Danio rerio,NaN,NCBI,ZFIN_ID,ywhaqb,D.rerio,Generalised,Monarch_KG
528409,pde4dip,Gene_AnatomicalEntity,ZFA:0001093,Gene,expressed_in,AnatomicalEntity,infores:zfin,phosphodiesterase 4D interacting protein,unspecified,Danio rerio,NaN,NCBI,ZFIN_ID,pde4dip,D.rerio,Generalised,Monarch_KG

In [6]:
monarch[monarch['head_detail_name'].isna()]

Empty DataFrame
Columns: [head, relation, tail, head_type, relation_type, tail_type, relation_source, head_detail_name, tail_detail_name, head_taxon_name, tail_taxon_name, head_id_is, tail_id_is, head_name, species, kg_type, kg_source]
Index: []

# Consolidate into Unified Schem

In [7]:
# List all source DataFrames to include
source_dfs = [
     monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 490,952

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,myb,Gene_AnatomicalEntity,ZFA:0000033,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,v-myb avian myeloblastosis viral oncogene homolog,intermediate cell mass of mesoderm,D.rerio
1,ptpn12,Gene_AnatomicalEntity,ZFA:0000079,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,protein tyrosine phosphatase non-receptor type 12,telencephalon,D.rerio
2,fgf24,Gene_AnatomicalEntity,ZFA:0001453,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,fibroblast growth factor 24,pectoral fin field,D.rerio
3,gata5,Gene_AnatomicalEntity,ZFA:0000038,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,GATA binding protein 5,margin,D.rerio
4,exo1,Gene_AnatomicalEntity,ZFA:0000098,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,exonuclease 1,proliferative region,D.rerio
...,...,...,...,...,...,...,...,...,...,...,...,...,...
490947,ackr4a,Gene_AnatomicalEntity,ZFA:0001094,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,atypical chemokine receptor 4a,whole organism,D.rerio
490948,kcnk5b,Gene_AnatomicalEntity,ZFA:0001093,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,"potassium channel, subfamily K, member 5b",unspecified,D.rerio
490949,pik3r4,Gene_AnatomicalEntity,ZFA:0001094,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,"phosphoinositide-3-kinase, regulatory subunit 4",whole organism,D.rerio
490950,ywhaqb,Gene_AnatomicalEntity,ZFA:0001093,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,tyrosine 3-monooxygenase/tryptophan 5-monooxyg...,unspecified,D.rerio
490951,pde4dip,Gene_AnatomicalEntity,ZFA:0001093,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,phosphodiesterase 4D interacting protein,unspecified,D.rerio

# Sanity Check — Distinct Values

In [8]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_AnatomicalEntity'}
head_type           : {'Gene'}
tail_type           : {'AnatomicalEntity'}
relation_type       : {'expressed_in'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'NCBI'}
tail_id_is          : {'ZFIN_ID'}

In [9]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 490,952 remaining

# NaN Audit (pre-dedup)

In [10]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [11]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 490,952  |  After dedup: 104,609

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,ATP6,Gene_AnatomicalEntity,ZFA:0000123,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,ATP synthase F0 subunit 6,liver,D.rerio
1,ATP6,Gene_AnatomicalEntity,ZFA:0000303,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,ATP synthase F0 subunit 6,female organism,D.rerio
2,ATP6,Gene_AnatomicalEntity,ZFA:0001094,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,ATP synthase F0 subunit 6,whole organism,D.rerio

In [12]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    104609
Name: count, dtype: int64

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    104609
Name: count, dtype: int64

In [15]:
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,ATP6,Gene_AnatomicalEntity,ZFA:0000123,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,ATP synthase F0 subunit 6,liver,D.rerio
1,ATP6,Gene_AnatomicalEntity,ZFA:0000303,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,ATP synthase F0 subunit 6,female organism,D.rerio
2,ATP6,Gene_AnatomicalEntity,ZFA:0001094,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,ATP synthase F0 subunit 6,whole organism,D.rerio
3,ATP6,Gene_AnatomicalEntity,ZFA:0005145,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,ATP synthase F0 subunit 6,muscle,D.rerio
4,ATP8,Gene_AnatomicalEntity,ZFA:0000003,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,ATP synthase F0 subunit 8,adaxial cell,D.rerio
...,...,...,...,...,...,...,...,...,...,...,...,...,...
104604,zwi,Gene_AnatomicalEntity,ZFA:0000823,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,zwilling,rhombomere 5,D.rerio
104605,zwi,Gene_AnatomicalEntity,ZFA:0000948,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,zwilling,rhombomere 3,D.rerio
104606,zwi,Gene_AnatomicalEntity,ZFA:0001479,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,zwilling,lateral line nerve,D.rerio
104607,zyg11,Gene_AnatomicalEntity,ZFA:0000303,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,"zyg-11 family member, cell cycle regulator",female organism,D.rerio
104608,zyg11,Gene_AnatomicalEntity,ZFA:0001094,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI,ZFIN_ID,"zyg-11 family member, cell cycle regulator",whole organism,D.rerio

In [16]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 104,609 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_gene_anatomy/Zebrafish_gene_anatomy.csv

In [18]:
# OUT_PATH