In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_chemical_gene/Zebrafish_chemical_gene.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [18]:
#

In [5]:
# Zebrafish = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Danio_rerio.gene_info',
#     sep='\t',
    
# )
# # Zebrafish["LocusTag"] = Zebrafish["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Zebrafish_symbol2Locus_dict = dict(zip(Zebrafish['Symbol'], Zebrafish['LocusTag']))
# # Zebrafish
# # Zebrafish_symbol2Locus_dict
# Zebrafish

# stitch

In [6]:
stitch = pd.read_csv(PROC_DIR + 'stitch/stitch_ZEBRA_CHEMICALENTITY_GENE.csv')

stitch.columns = stitch.columns.str.lower()
stitch = stitch[~stitch['head_detail_name'].isna()]
stitch['kg_type'] = 'Generalised'
stitch['kg_source'] = 'stitch'
stitch['species'] = 'D.rerio'
print(f"stitch: {len(stitch):,} rows")
stitch

stitch: 16,666,058 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species,kg_type
0,1,ChemicalEntity_Gene,ACADSB,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,acyl-CoA dehydrogenase short/branched chain [S...,D.rerio,Generalised
1,1,ChemicalEntity_Gene,ACY1,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,aminoacylase 1 [Source:HGNC Symbol;Acc:HGNC:177],D.rerio,Generalised
2,1,ChemicalEntity_Gene,BPTF,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,bromodomain PHD finger transcription factor [S...,D.rerio,Generalised
3,1,ChemicalEntity_Gene,BRPF3,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,bromodomain and PHD finger containing 3 [Sourc...,D.rerio,Generalised
4,1,ChemicalEntity_Gene,CDY2B,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,chromodomain Y-linked 2B [Source:HGNC Symbol;A...,D.rerio,Generalised
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16699402,9999994,ChemicalEntity_Gene,nlgn2b,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,neuroligin 2b [Source:ZFIN;Acc:ZDB-GENE-090918-3],D.rerio,Generalised
16699403,9999994,ChemicalEntity_Gene,nlgn3b,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,neuroligin 3b [Source:ZFIN;Acc:ZDB-GENE-060526...,D.rerio,Generalised
16699404,9999994,ChemicalEntity_Gene,nlgn4xa,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,neuroligin 4 X-linked a [Source:ZFIN;Acc:ZDB-G...,D.rerio,Generalised
16699405,9999994,ChemicalEntity_Gene,nlgn4xb,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,neuroligin 4 X-linked b [Source:ZFIN;Acc:ZDB-G...,D.rerio,Generalised
16699406,9999994,ChemicalEntity_Gene,tg,ChemicalEntity,NaN,Gene,stitch,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,thyroglobulin [Source:ZFIN;Acc:ZDB-GENE-030519-1],D.rerio,Generalised

In [7]:
stitch[stitch['head_detail_name'].isna()]

Empty DataFrame
Columns: [head, relation, tail, head_type, relation_type, tail_type, kg_source, head_id_is, tail_id_is, head_detail_name, tail_detail_name, species, kg_type]
Index: []

# Consolidate into Unified Schem

In [8]:
# List all source DataFrames to include
source_dfs = [
     stitch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 16,666,058

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,1,ChemicalEntity_Gene,ACADSB,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,acyl-CoA dehydrogenase short/branched chain [S...,D.rerio
1,1,ChemicalEntity_Gene,ACY1,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,aminoacylase 1 [Source:HGNC Symbol;Acc:HGNC:177],D.rerio
2,1,ChemicalEntity_Gene,BPTF,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,bromodomain PHD finger transcription factor [S...,D.rerio
3,1,ChemicalEntity_Gene,BRPF3,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,bromodomain and PHD finger containing 3 [Sourc...,D.rerio
4,1,ChemicalEntity_Gene,CDY2B,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,chromodomain Y-linked 2B [Source:HGNC Symbol;A...,D.rerio
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16666053,9999994,ChemicalEntity_Gene,nlgn2b,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,neuroligin 2b [Source:ZFIN;Acc:ZDB-GENE-090918-3],D.rerio
16666054,9999994,ChemicalEntity_Gene,nlgn3b,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,neuroligin 3b [Source:ZFIN;Acc:ZDB-GENE-060526...,D.rerio
16666055,9999994,ChemicalEntity_Gene,nlgn4xa,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,neuroligin 4 X-linked a [Source:ZFIN;Acc:ZDB-G...,D.rerio
16666056,9999994,ChemicalEntity_Gene,nlgn4xb,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,neuroligin 4 X-linked b [Source:ZFIN;Acc:ZDB-G...,D.rerio
16666057,9999994,ChemicalEntity_Gene,tg,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,thyroglobulin [Source:ZFIN;Acc:ZDB-GENE-030519-1],D.rerio

# Sanity Check — Distinct Values

In [17]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'ChemicalEntity_Gene'}
head_type           : {'ChemicalEntity'}
tail_type           : {'Gene'}

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [10]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 16,666,058 remaining

# NaN Audit (pre-dedup)

In [11]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type      16666058            16666058        33332116
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [12]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 16,666,058  |  After dedup: 16,666,058

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name
0,1,ChemicalEntity_Gene,ACADSB,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,acyl-CoA dehydrogenase short/branched chain [S...
1,1,ChemicalEntity_Gene,ACY1,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,aminoacylase 1 [Source:HGNC Symbol;Acc:HGNC:177]
2,1,ChemicalEntity_Gene,BPTF,ChemicalEntity,NaN,Gene,stitch,Generalised,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,bromodomain PHD finger transcription factor [S...

In [21]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type      16666058            16666058        33332116
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [22]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'stitch'} kg_source
stitch    16666058
Name: count, dtype: int64

In [23]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    16666058
Name: count, dtype: int64

In [24]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 16,666,058 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_chemical_gene/Zebrafish_chemical_gene.csv

In [19]:
# OUT_PATH