In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_phenotype_cellularcomponent/Zebrafish_phenotype_cellularcomponent.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

In [5]:
# Zebrafish = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Danio_rerio.gene_info',
#     sep='\t',
    
# )
# # Zebrafish["LocusTag"] = Zebrafish["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Zebrafish_symbol2Locus_dict = dict(zip(Zebrafish['Symbol'], Zebrafish['LocusTag']))
# # Zebrafish
# # Zebrafish_symbol2Locus_dict
# Zebrafish

# monarch

In [6]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Zebrafish/Zebra_Phenotype_CellularComponent.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
# monarch = monarch.rename(columns={'headtype': 'head_type', 'tailtype': 'tail_type'})

monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'
monarch['species'] = 'D.rerio'
print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 5,378 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,species,kg_type,kg_source
0,ZP:0019682,Phenotype_CellularComponent,GO:0030424,Phenotype,related_to,CellularComponent,infores:upheno,axon commissure of the tract of the commissure...,axon,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
1,ZP:0019700,Phenotype_CellularComponent,GO:0044297,Phenotype,related_to,CellularComponent,infores:upheno,"cell body photoreceptor cell mislocalised, abn...",cell body,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
2,ZP:0019701,Phenotype_CellularComponent,GO:0060091,Phenotype,related_to,CellularComponent,infores:upheno,"kinocilium hair cell disorganized, abnormal",kinocilium,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
3,ZP:0019702,Phenotype_CellularComponent,GO:0005929,Phenotype,related_to,CellularComponent,infores:upheno,"cilium olfactory pit swollen, abnormal",cilium,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
4,ZP:0019703,Phenotype_CellularComponent,GO:0060091,Phenotype,related_to,CellularComponent,infores:upheno,"kinocilium hair cell decreased length, abnormal",kinocilium,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5373,ZP:0019604,Phenotype_CellularComponent,GO:0045495,Phenotype,related_to,CellularComponent,infores:upheno,pole plasm oocyte stage I increased distributi...,pole plasm,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
5374,ZP:0019605,Phenotype_CellularComponent,GO:0031514,Phenotype,related_to,CellularComponent,infores:upheno,motile cilium Kupffer's vesicle increased leng...,motile cilium,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
5375,ZP:0019607,Phenotype_CellularComponent,GO:0005892,Phenotype,related_to,CellularComponent,infores:upheno,acetylcholine-gated channel complex myotome di...,acetylcholine-gated channel complex,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
5376,ZP:0019608,Phenotype_CellularComponent,GO:0005892,Phenotype,related_to,CellularComponent,infores:upheno,acetylcholine-gated channel complex myotome mi...,acetylcholine-gated channel complex,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
5377,ZP:0019611,Phenotype_CellularComponent,GO:0045178,Phenotype,related_to,CellularComponent,infores:upheno,basal part of cell otic epithelium decreased a...,basal part of cell,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG

In [7]:
monarch[monarch['head_detail_name'].isna()]

Empty DataFrame
Columns: [head, relation, tail, head_type, relation_type, tail_type, relation_source, head_detail_name, tail_detail_name, head_taxon_name, tail_taxon_name, head_id_is, tail_id_is, species, kg_type, kg_source]
Index: []

# Consolidate into Unified Schem

In [8]:
# List all source DataFrames to include
source_dfs = [
     monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 5,378

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,ZP:0019682,Phenotype_CellularComponent,GO:0030424,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,axon commissure of the tract of the commissure...,axon,D.rerio
1,ZP:0019700,Phenotype_CellularComponent,GO:0044297,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,"cell body photoreceptor cell mislocalised, abn...",cell body,D.rerio
2,ZP:0019701,Phenotype_CellularComponent,GO:0060091,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,"kinocilium hair cell disorganized, abnormal",kinocilium,D.rerio
3,ZP:0019702,Phenotype_CellularComponent,GO:0005929,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,"cilium olfactory pit swollen, abnormal",cilium,D.rerio
4,ZP:0019703,Phenotype_CellularComponent,GO:0060091,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,"kinocilium hair cell decreased length, abnormal",kinocilium,D.rerio
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5373,ZP:0019604,Phenotype_CellularComponent,GO:0045495,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,pole plasm oocyte stage I increased distributi...,pole plasm,D.rerio
5374,ZP:0019605,Phenotype_CellularComponent,GO:0031514,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,motile cilium Kupffer's vesicle increased leng...,motile cilium,D.rerio
5375,ZP:0019607,Phenotype_CellularComponent,GO:0005892,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,acetylcholine-gated channel complex myotome di...,acetylcholine-gated channel complex,D.rerio
5376,ZP:0019608,Phenotype_CellularComponent,GO:0005892,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,acetylcholine-gated channel complex myotome mi...,acetylcholine-gated channel complex,D.rerio
5377,ZP:0019611,Phenotype_CellularComponent,GO:0045178,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,basal part of cell otic epithelium decreased a...,basal part of cell,D.rerio

# Sanity Check — Distinct Values

In [9]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Phenotype_CellularComponent'}
head_type           : {'Phenotype'}
tail_type           : {'CellularComponent'}
relation_type       : {'related_to'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'ZFIN_ID'}
tail_id_is          : {'Quick_GO'}

In [10]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 5,378 remaining

# NaN Audit (pre-dedup)

In [11]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [12]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 5,378  |  After dedup: 5,378

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,ZP:0000089,Phenotype_CellularComponent,GO:0030424,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,"axon olfactory receptor cell decreased length,...",axon,D.rerio
1,ZP:0000090,Phenotype_CellularComponent,GO:0030424,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,"axon olfactory receptor cell disorganized, abn...",axon,D.rerio
2,ZP:0000216,Phenotype_CellularComponent,GO:0030424,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,"axon Mauthner neuron mislocalised, abnormal",axon,D.rerio

In [13]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    5378
Name: count, dtype: int64

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    5378
Name: count, dtype: int64

In [16]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 5,378 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_phenotype_cellularcomponent/Zebrafish_phenotype_cellularcomponent.csv

In [17]:
# OUT_PATH