In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_gene_pathway/Zebrafish_gene_pathway.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

In [19]:
# Zebrafish = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Danio_rerio.gene_info',
#     sep='\t',
    
# )
# # Zebrafish["LocusTag"] = Zebrafish["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Zebrafish_symbol2Locus_dict = dict(zip(Zebrafish['Symbol'], Zebrafish['LocusTag']))
# # Zebrafish
# # Zebrafish_symbol2Locus_dict
# Zebrafish

# Monarch

In [6]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Zebrafish/Zebra_Gene_Pathway.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'

monarch['species'] = 'D.rerio'
print(f"monarch: {len(monarch):,} rows")
monarch = monarch[~monarch['head'].str.contains(':')]
monarch

monarch: 10,394 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,parvaa,Gene_Pathway,R-HSA-446343,Gene,participates_in,Pathway,infores:reactome,"parvin, alpha a",Localization of the PINCH-ILK-PARVIN complex t...,Danio rerio,Homo sapiens,NCBI,Reactome,parvaa,D.rerio,Generalised,Monarch_KG
1,parvaa,Gene_Pathway,R-HSA-446388,Gene,participates_in,Pathway,infores:reactome,"parvin, alpha a",Regulation of cytoskeletal remodeling and cell...,Danio rerio,Homo sapiens,NCBI,Reactome,parvaa,D.rerio,Generalised,Monarch_KG
2,oxct1a,Gene_Pathway,R-HSA-77108,Gene,participates_in,Pathway,infores:reactome,3-oxoacid CoA transferase 1a,Utilization of Ketone Bodies,Danio rerio,Homo sapiens,NCBI,Reactome,oxct1a,D.rerio,Generalised,Monarch_KG
3,ctdp1,Gene_Pathway,R-HSA-6796648,Gene,participates_in,Pathway,infores:reactome,"CTD (carboxy-terminal domain, RNA polymerase I...",TP53 Regulates Transcription of DNA Repair Genes,Danio rerio,Homo sapiens,NCBI,Reactome,ctdp1,D.rerio,Generalised,Monarch_KG
4,sumo2b,Gene_Pathway,R-HSA-196791,Gene,participates_in,Pathway,infores:reactome,small ubiquitin like modifier 2b,Vitamin D (calciferol) metabolism,Danio rerio,Homo sapiens,NCBI,Reactome,sumo2b,D.rerio,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10393,tyrp1b,Gene_Pathway,R-HSA-5662702,Gene,participates_in,Pathway,infores:reactome,tyrosinase-related protein 1b,Melanin biosynthesis,Danio rerio,Homo sapiens,NCBI,Reactome,tyrp1b,D.rerio,Generalised,Monarch_KG
10394,rab30,Gene_Pathway,R-HSA-8873719,Gene,participates_in,Pathway,infores:reactome,"RAB30, member RAS oncogene family",RAB geranylgeranylation,Danio rerio,Homo sapiens,NCBI,Reactome,rab30,D.rerio,Generalised,Monarch_KG
10395,ikbke,Gene_Pathway,R-HSA-9860927,Gene,participates_in,Pathway,infores:reactome,inhibitor of nuclear factor kappa B kinase sub...,"Turbulent (oscillatory, disturbed) flow shear ...",Danio rerio,Homo sapiens,NCBI,Reactome,ikbke,D.rerio,Generalised,Monarch_KG
10396,rac3a,Gene_Pathway,R-HSA-4086400,Gene,participates_in,Pathway,infores:reactome,Rac family small GTPase 3a,PCP/CE pathway,Danio rerio,Homo sapiens,NCBI,Reactome,rac3a,D.rerio,Generalised,Monarch_KG
10397,rac3a,Gene_Pathway,R-HSA-9013423,Gene,participates_in,Pathway,infores:reactome,Rac family small GTPase 3a,RAC3 GTPase cycle,Danio rerio,Homo sapiens,NCBI,Reactome,rac3a,D.rerio,Generalised,Monarch_KG

In [7]:
monarch[monarch['head_detail_name'].isna()]

Empty DataFrame
Columns: [head, relation, tail, head_type, relation_type, tail_type, relation_source, head_detail_name, tail_detail_name, head_taxon_name, tail_taxon_name, head_id_is, tail_id_is, head_name, species, kg_type, kg_source]
Index: []

# Consolidate into Unified Schem

In [8]:
# List all source DataFrames to include
source_dfs = [
     monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 9,877

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,parvaa,Gene_Pathway,R-HSA-446343,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI,Reactome,"parvin, alpha a",Localization of the PINCH-ILK-PARVIN complex t...,D.rerio
1,parvaa,Gene_Pathway,R-HSA-446388,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI,Reactome,"parvin, alpha a",Regulation of cytoskeletal remodeling and cell...,D.rerio
2,oxct1a,Gene_Pathway,R-HSA-77108,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI,Reactome,3-oxoacid CoA transferase 1a,Utilization of Ketone Bodies,D.rerio
3,ctdp1,Gene_Pathway,R-HSA-6796648,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI,Reactome,"CTD (carboxy-terminal domain, RNA polymerase I...",TP53 Regulates Transcription of DNA Repair Genes,D.rerio
4,sumo2b,Gene_Pathway,R-HSA-196791,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI,Reactome,small ubiquitin like modifier 2b,Vitamin D (calciferol) metabolism,D.rerio
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9872,tyrp1b,Gene_Pathway,R-HSA-5662702,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI,Reactome,tyrosinase-related protein 1b,Melanin biosynthesis,D.rerio
9873,rab30,Gene_Pathway,R-HSA-8873719,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI,Reactome,"RAB30, member RAS oncogene family",RAB geranylgeranylation,D.rerio
9874,ikbke,Gene_Pathway,R-HSA-9860927,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI,Reactome,inhibitor of nuclear factor kappa B kinase sub...,"Turbulent (oscillatory, disturbed) flow shear ...",D.rerio
9875,rac3a,Gene_Pathway,R-HSA-4086400,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI,Reactome,Rac family small GTPase 3a,PCP/CE pathway,D.rerio
9876,rac3a,Gene_Pathway,R-HSA-9013423,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI,Reactome,Rac family small GTPase 3a,RAC3 GTPase cycle,D.rerio

# Sanity Check — Distinct Values

In [9]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_Pathway'}
head_type           : {'Gene'}
tail_type           : {'Pathway'}
relation_type       : {'participates_in'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'NCBI'}
tail_id_is          : {'Reactome'}

In [10]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 9,877 remaining

# NaN Audit (pre-dedup)

In [11]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [12]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 9,877  |  After dedup: 9,877

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,aaas,Gene_Pathway,R-HSA-8980692,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI,Reactome,"achalasia, adrenocortical insufficiency, alacr...",RHOA GTPase cycle,D.rerio
1,aacs,Gene_Pathway,R-HSA-77111,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI,Reactome,acetoacetyl-CoA synthetase,Synthesis of Ketone Bodies,D.rerio
2,aamp,Gene_Pathway,R-HSA-168638,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI,Reactome,"angio-associated, migratory cell protein",NOD1/2 Signaling Pathway,D.rerio

In [13]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    9877
Name: count, dtype: int64

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    9877
Name: count, dtype: int64

In [18]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 9,877 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_gene_pathway/Zebrafish_gene_pathway.csv

In [17]:
# OUT_PATH