In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_phenotype_molecularfunction/Zebrafish_phenotype_molecularfunction.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

In [5]:
# Zebrafish = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Danio_rerio.gene_info',
#     sep='\t',
    
# )
# # Zebrafish["LocusTag"] = Zebrafish["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Zebrafish_symbol2Locus_dict = dict(zip(Zebrafish['Symbol'], Zebrafish['LocusTag']))
# # Zebrafish
# # Zebrafish_symbol2Locus_dict
# Zebrafish

# monarch

In [7]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Zebrafish/Zebra_PhenotypicFeature_MolecularFunction.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
# monarch = monarch.rename(columns={'headtype': 'head_type', 'tailtype': 'tail_type'})

monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'
monarch['species'] = 'D.rerio'
print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 455 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,species,kg_type,kg_source
0,ZP:0019874,Phenotype_MolecularFunction,GO:0004708,Phenotype,related_to,MolecularFunction,infores:upheno,"MAP kinase kinase activity process quality, ab...",MAP kinase kinase activity,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
1,ZP:0019951,Phenotype_MolecularFunction,GO:0072320,Phenotype,related_to,MolecularFunction,infores:upheno,volume-sensitive chloride channel activity dec...,volume-sensitive chloride channel activity,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
2,ZP:0020011,Phenotype_MolecularFunction,GO:0097153,Phenotype,related_to,MolecularFunction,infores:upheno,cysteine-type endopeptidase activity involved ...,obsolete cysteine-type endopeptidase activity ...,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
3,ZP:0020439,Phenotype_MolecularFunction,GO:0008475,Phenotype,related_to,MolecularFunction,infores:upheno,procollagen-lysine 5-dioxygenase activity disr...,procollagen-lysine 5-dioxygenase activity,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
4,ZP:0021430,Phenotype_MolecularFunction,GO:0008086,Phenotype,related_to,MolecularFunction,infores:upheno,light-activated voltage-gated calcium channel ...,light-activated voltage-gated calcium channel ...,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,ZP:0019079,Phenotype_MolecularFunction,GO:0004800,Phenotype,related_to,MolecularFunction,infores:upheno,"thyroxine 5'-deiodinase activity disrupted, ab...",thyroxine 5'-deiodinase activity,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
451,ZP:0019080,Phenotype_MolecularFunction,GO:0004800,Phenotype,related_to,MolecularFunction,infores:upheno,thyroxine 5'-deiodinase activity decreased pro...,thyroxine 5'-deiodinase activity,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
452,ZP:0019486,Phenotype_MolecularFunction,GO:0004348,Phenotype,related_to,MolecularFunction,infores:upheno,glucosylceramidase activity decreased process ...,glucosylceramidase activity,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
453,ZP:0019568,Phenotype_MolecularFunction,GO:0016772,Phenotype,related_to,MolecularFunction,infores:upheno,"transferase activity, transferring phosphorus-...","transferase activity, transferring phosphorus-...",Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG
454,ZP:0019572,Phenotype_MolecularFunction,GO:0015926,Phenotype,related_to,MolecularFunction,infores:upheno,glucosidase activity decreased process quality...,glucosidase activity,Danio rerio,NaN,ZFIN_ID,Quick_GO,D.rerio,Generalised,Monarch_KG

In [8]:
monarch[monarch['head_detail_name'].isna()]

Empty DataFrame
Columns: [head, relation, tail, head_type, relation_type, tail_type, relation_source, head_detail_name, tail_detail_name, head_taxon_name, tail_taxon_name, head_id_is, tail_id_is, species, kg_type, kg_source]
Index: []

# Consolidate into Unified Schem

In [9]:
# List all source DataFrames to include
source_dfs = [
     monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 455

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,ZP:0019874,Phenotype_MolecularFunction,GO:0004708,Phenotype,related_to,MolecularFunction,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,"MAP kinase kinase activity process quality, ab...",MAP kinase kinase activity,D.rerio
1,ZP:0019951,Phenotype_MolecularFunction,GO:0072320,Phenotype,related_to,MolecularFunction,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,volume-sensitive chloride channel activity dec...,volume-sensitive chloride channel activity,D.rerio
2,ZP:0020011,Phenotype_MolecularFunction,GO:0097153,Phenotype,related_to,MolecularFunction,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,cysteine-type endopeptidase activity involved ...,obsolete cysteine-type endopeptidase activity ...,D.rerio
3,ZP:0020439,Phenotype_MolecularFunction,GO:0008475,Phenotype,related_to,MolecularFunction,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,procollagen-lysine 5-dioxygenase activity disr...,procollagen-lysine 5-dioxygenase activity,D.rerio
4,ZP:0021430,Phenotype_MolecularFunction,GO:0008086,Phenotype,related_to,MolecularFunction,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,light-activated voltage-gated calcium channel ...,light-activated voltage-gated calcium channel ...,D.rerio
...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,ZP:0019079,Phenotype_MolecularFunction,GO:0004800,Phenotype,related_to,MolecularFunction,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,"thyroxine 5'-deiodinase activity disrupted, ab...",thyroxine 5'-deiodinase activity,D.rerio
451,ZP:0019080,Phenotype_MolecularFunction,GO:0004800,Phenotype,related_to,MolecularFunction,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,thyroxine 5'-deiodinase activity decreased pro...,thyroxine 5'-deiodinase activity,D.rerio
452,ZP:0019486,Phenotype_MolecularFunction,GO:0004348,Phenotype,related_to,MolecularFunction,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,glucosylceramidase activity decreased process ...,glucosylceramidase activity,D.rerio
453,ZP:0019568,Phenotype_MolecularFunction,GO:0016772,Phenotype,related_to,MolecularFunction,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,"transferase activity, transferring phosphorus-...","transferase activity, transferring phosphorus-...",D.rerio
454,ZP:0019572,Phenotype_MolecularFunction,GO:0015926,Phenotype,related_to,MolecularFunction,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,glucosidase activity decreased process quality...,glucosidase activity,D.rerio

# Sanity Check — Distinct Values

In [10]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Phenotype_MolecularFunction'}
head_type           : {'Phenotype'}
tail_type           : {'MolecularFunction'}
relation_type       : {'related_to'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'ZFIN_ID'}
tail_id_is          : {'Quick_GO'}

In [11]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 455 remaining

# NaN Audit (pre-dedup)

In [12]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [13]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 455  |  After dedup: 455

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name
0,ZP:0000092,Phenotype_MolecularFunction,GO:0004853,Phenotype,related_to,MolecularFunction,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,uroporphyrinogen decarboxylase activity decrea...,uroporphyrinogen decarboxylase activity
1,ZP:0000690,Phenotype_MolecularFunction,GO:0005179,Phenotype,related_to,MolecularFunction,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,"hormone activity decreased occurrence, abnormal",hormone activity
2,ZP:0000830,Phenotype_MolecularFunction,GO:0005248,Phenotype,related_to,MolecularFunction,Monarch_KG,Generalised,ZFIN_ID,Quick_GO,voltage-gated sodium channel activity amplitud...,voltage-gated sodium channel activity

In [14]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    455
Name: count, dtype: int64

In [16]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    455
Name: count, dtype: int64

In [18]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 455 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_phenotype_molecularfunction/Zebrafish_phenotype_molecularfunction.csv

In [19]:
# OUT_PATH