In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_anatomy_anatomy/Zebrafish_anatomy_anatomy.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

In [5]:
# Zebrafish = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Danio_rerio.gene_info',
#     sep='\t',
    
# )
# # Zebrafish["LocusTag"] = Zebrafish["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Zebrafish_symbol2Locus_dict = dict(zip(Zebrafish['Symbol'], Zebrafish['LocusTag']))
# # Zebrafish
# # Zebrafish_symbol2Locus_dict
# Zebrafish

# monarch

In [6]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Zebrafish/Zebra_AnatomicalEntity_AnatomicalEntity.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
# monarch = monarch.rename(columns={'headtype': 'head_type', 'tailtype': 'tail_type'})

monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'
monarch['species'] = 'D.rerio'
monarch['relation'] = 'AnatomicalEntity_AnatomicalEntity'
monarch['head_type'] = 'AnatomicalEntity'
monarch['tail_type'] = 'AnatomicalEntity'
print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 5,951 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,species,kg_type,kg_source
0,ZFA:0000000,AnatomicalEntity_AnatomicalEntity,ZFA:0001105,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:zfa,Brachet's cleft,embryonic structure,Danio rerio,Danio rerio,ZFIN_ID,ZFIN_ID,D.rerio,Generalised,Monarch_KG
1,ZFA:0000001,AnatomicalEntity_AnatomicalEntity,ZFA:0001105,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:zfa,Kupffer's vesicle,embryonic structure,Danio rerio,Danio rerio,ZFIN_ID,ZFIN_ID,D.rerio,Generalised,Monarch_KG
2,ZFA:0000001,AnatomicalEntity_AnatomicalEntity,ZFA:0000077,AnatomicalEntity,related_to,AnatomicalEntity,infores:zfa,Kupffer's vesicle,tail bud,Danio rerio,Danio rerio,ZFIN_ID,ZFIN_ID,D.rerio,Generalised,Monarch_KG
3,ZFA:0000001,AnatomicalEntity_AnatomicalEntity,ZFA:0000023,AnatomicalEntity,related_to,AnatomicalEntity,infores:zfa,Kupffer's vesicle,forerunner cell group,Danio rerio,Danio rerio,ZFIN_ID,ZFIN_ID,D.rerio,Generalised,Monarch_KG
4,ZFA:0000003,AnatomicalEntity_AnatomicalEntity,ZFA:0009000,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:zfa,adaxial cell,cell,Danio rerio,Danio rerio,ZFIN_ID,ZFIN_ID,D.rerio,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5946,ZFA:0009401,AnatomicalEntity_AnatomicalEntity,ZFA:0000035,AnatomicalEntity,related_to,AnatomicalEntity,infores:zfa,lens fiber cell,lens,Danio rerio,Danio rerio,ZFIN_ID,ZFIN_ID,D.rerio,Generalised,Monarch_KG
5947,ZFA:0009402,AnatomicalEntity_AnatomicalEntity,ZFA:0009000,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:zfa,heart valve cell,cell,Danio rerio,Danio rerio,ZFIN_ID,ZFIN_ID,D.rerio,Generalised,Monarch_KG
5948,ZFA:0009402,AnatomicalEntity_AnatomicalEntity,ZFA:0005065,AnatomicalEntity,related_to,AnatomicalEntity,infores:zfa,heart valve cell,heart valve,Danio rerio,Danio rerio,ZFIN_ID,ZFIN_ID,D.rerio,Generalised,Monarch_KG
5949,ZFA:0009403,AnatomicalEntity_AnatomicalEntity,ZFA:0009402,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:zfa,heart valve interstitial cell,heart valve cell,Danio rerio,Danio rerio,ZFIN_ID,ZFIN_ID,D.rerio,Generalised,Monarch_KG
5950,ZFA:0009404,AnatomicalEntity_AnatomicalEntity,ZFA:0009402,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:zfa,heart valve endothelial cell,heart valve cell,Danio rerio,Danio rerio,ZFIN_ID,ZFIN_ID,D.rerio,Generalised,Monarch_KG

In [7]:
monarch[monarch['head_detail_name'].isna()]

Empty DataFrame
Columns: [head, relation, tail, head_type, relation_type, tail_type, relation_source, head_detail_name, tail_detail_name, head_taxon_name, tail_taxon_name, head_id_is, tail_id_is, species, kg_type, kg_source]
Index: []

# Consolidate into Unified Schem

In [8]:
# List all source DataFrames to include
source_dfs = [
     monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 5,951

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,ZFA:0000000,AnatomicalEntity_AnatomicalEntity,ZFA:0001105,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,ZFIN_ID,ZFIN_ID,Brachet's cleft,embryonic structure,D.rerio
1,ZFA:0000001,AnatomicalEntity_AnatomicalEntity,ZFA:0001105,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,ZFIN_ID,ZFIN_ID,Kupffer's vesicle,embryonic structure,D.rerio
2,ZFA:0000001,AnatomicalEntity_AnatomicalEntity,ZFA:0000077,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,ZFIN_ID,ZFIN_ID,Kupffer's vesicle,tail bud,D.rerio
3,ZFA:0000001,AnatomicalEntity_AnatomicalEntity,ZFA:0000023,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,ZFIN_ID,ZFIN_ID,Kupffer's vesicle,forerunner cell group,D.rerio
4,ZFA:0000003,AnatomicalEntity_AnatomicalEntity,ZFA:0009000,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,ZFIN_ID,ZFIN_ID,adaxial cell,cell,D.rerio
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5946,ZFA:0009401,AnatomicalEntity_AnatomicalEntity,ZFA:0000035,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,ZFIN_ID,ZFIN_ID,lens fiber cell,lens,D.rerio
5947,ZFA:0009402,AnatomicalEntity_AnatomicalEntity,ZFA:0009000,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,ZFIN_ID,ZFIN_ID,heart valve cell,cell,D.rerio
5948,ZFA:0009402,AnatomicalEntity_AnatomicalEntity,ZFA:0005065,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,ZFIN_ID,ZFIN_ID,heart valve cell,heart valve,D.rerio
5949,ZFA:0009403,AnatomicalEntity_AnatomicalEntity,ZFA:0009402,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,ZFIN_ID,ZFIN_ID,heart valve interstitial cell,heart valve cell,D.rerio
5950,ZFA:0009404,AnatomicalEntity_AnatomicalEntity,ZFA:0009402,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,ZFIN_ID,ZFIN_ID,heart valve endothelial cell,heart valve cell,D.rerio

# Sanity Check — Distinct Values

In [9]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'AnatomicalEntity_AnatomicalEntity'}
head_type           : {'AnatomicalEntity'}
tail_type           : {'AnatomicalEntity'}
relation_type       : {'related_to', 'subclass_of'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'ZFIN_ID'}
tail_id_is          : {'ZFIN_ID'}

In [10]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 5,951 remaining

# NaN Audit (pre-dedup)

In [11]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [12]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 5,951  |  After dedup: 5,950

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,ZFA:0000000,AnatomicalEntity_AnatomicalEntity,ZFA:0001105,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,ZFIN_ID,ZFIN_ID,Brachet's cleft,embryonic structure,D.rerio
1,ZFA:0000001,AnatomicalEntity_AnatomicalEntity,ZFA:0000023,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,ZFIN_ID,ZFIN_ID,Kupffer's vesicle,forerunner cell group,D.rerio
2,ZFA:0000001,AnatomicalEntity_AnatomicalEntity,ZFA:0000077,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,ZFIN_ID,ZFIN_ID,Kupffer's vesicle,tail bud,D.rerio

In [13]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    5950
Name: count, dtype: int64

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    5950
Name: count, dtype: int64

In [16]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 5,950 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_anatomy_anatomy/Zebrafish_anatomy_anatomy.csv

In [17]:
# OUT_PATH