In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [22]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish

In [20]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_chemical_protein/Zebrafish_chemical_protein.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

In [5]:
# Zebrafish = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Danio_rerio.gene_info',
#     sep='\t',
    
# )
# # Zebrafish["LocusTag"] = Zebrafish["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Zebrafish_symbol2Locus_dict = dict(zip(Zebrafish['Symbol'], Zebrafish['LocusTag']))
# # Zebrafish
# # Zebrafish_symbol2Locus_dict
# Zebrafish

# bindingdb

In [7]:
bindingdb = pd.read_csv(PROC_DIR + 'bindingdb/Chemical_Protein_Zebra_BindingDB.csv')

bindingdb.columns = bindingdb.columns.str.lower()
bindingdb = bindingdb[~bindingdb['head_detail_name'].isna()]
bindingdb['kg_type'] = 'Generalised'
bindingdb['kg_source'] = 'Binding_DB'
bindingdb['species'] = 'D.rerio'
print(f"bindingdb: {len(bindingdb):,} rows")
bindingdb

bindingdb: 32 rows

,head,relation,tail,head_type,tail_type,kg_source,species,head_detail_name,head_smile_name,tail_detail_name,head_id_is,tail_id_is,kg_type
0,71575543,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",C1=CC(=CC(=C1)NC(=O)NC2=CC=C(C=C2)OC3=NC=NC4=C...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
1,71575213,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",C1=CC(=CC=C1C(F)(F)F)NC(=O)NC2=CC=C(C=C2)OC3=N...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
2,71575641,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,1-[2-chloro-4-(trifluoromethyl)phenyl]-3-[4-(1...,C1=CC(=CC=C1NC(=O)NC2=C(C=C(C=C2)C(F)(F)F)Cl)O...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
3,71575640,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-[3,5-bis(trifluoromethyl)phenyl]-3-[4-(1H-py...",C1=CC(=CC=C1NC(=O)NC2=CC(=CC(=C2)C(F)(F)F)C(F)...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
4,71575546,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",C1=CC(=CC(=C1)OC(F)(F)F)NC(=O)NC2=CC=C(C=C2)OC...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
5,71575545,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(3-fluorophenyl)-3-[4-(1H-pyrazolo[3,4-d]pyr...",C1=CC(=CC(=C1)F)NC(=O)NC2=CC=C(C=C2)OC3=NC=NC4...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
6,71575544,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(3-propan-2-ylphenyl)-3-[4-(1H-pyrazolo[3,4-...",CC(C)C1=CC(=CC=C1)NC(=O)NC2=CC=C(C=C2)OC3=NC=N...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
7,71575542,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,1-(4-morpholin-4-ylphenyl)-3-[4-(1H-pyrazolo[3...,C1COCCN1C2=CC=C(C=C2)NC(=O)NC3=CC=C(C=C3)OC4=N...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
8,71575541,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(4-fluorophenyl)-3-[4-(1H-pyrazolo[3,4-d]pyr...",C1=CC(=CC=C1NC(=O)NC2=CC=C(C=C2)F)OC3=NC=NC4=C...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
9,71716376,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(cyclohexylmethyl)-3-[4-(1H-pyrazolo[3,4-d]p...",C1CCC(CC1)CNC(=O)NC2=CC=C(C=C2)OC3=NC=NC4=C3C=NN4,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
10,71720643,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-cyclohexyl-3-[4-(1H-pyrazolo[3,4-d]pyrimidin...",C1CCC(CC1)NC(=O)NC2=CC=C(C=C2)OC3=NC=NC4=C3C=NN4,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
11,71718823,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(1-phenylethyl)-3-[4-(1H-pyrazolo[3,4-d]pyri...",CC(C1=CC=CC=C1)NC(=O)NC2=CC=C(C=C2)OC3=NC=NC4=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
12,71720012,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",C1=CC(=CN=C1)NC(=O)NC2=CC=C(C=C2)OC3=NC=NC4=C3...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
13,71575438,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-phenyl-3-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-y...",C1=CC=C(C=C1)NC(=O)NC2=CC=C(C=C2)OC3=NC=NC4=C3...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
14,71575437,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"2-(4-bromophenyl)-N-[4-(1H-pyrazolo[3,4-d]pyri...",C1=CC(=CC=C1CC(=O)NC2=CC=C(C=C2)OC3=NC=NC4=C3C...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
15,71575436,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"4-bromo-N-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-yl...",C1=CC(=CC=C1C(=O)NC2=CC=C(C=C2)OC3=NC=NC4=C3C=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
16,71575327,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"4-bromo-N-[3-(1H-pyrazolo[3,4-d]pyrimidin-4-yl...",C1=CC(=CC(=C1)OC2=NC=NC3=C2C=NN3)NC(=O)C4=CC=C...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
17,71575326,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"N-[3-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",C1=CC(=CC(=C1)OC2=NC=NC3=C2C=NN3)NC(=O)C4=CC=C...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
18,71575325,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"2-(4-bromophenyl)-N-[3-(1H-pyrazolo[3,4-d]pyri...",C1=CC(=CC(=C1)OC2=NC=NC3=C2C=NN3)NC(=O)CC4=CC=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
19,71575324,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"N-[3-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",C1=CC(=CC(=C1)OC2=NC=NC3=C2C=NN3)NC(=O)CC4=CC=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
20,71575323,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(4-bromophenyl)-3-[3-(1H-pyrazolo[3,4-d]pyri...",C1=CC(=CC(=C1)OC2=NC=NC3=C2C=NN3)NC(=O)NC4=CC=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
21,71575322,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-[3-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",C1=CC(=CC(=C1)OC2=NC=NC3=C2C=NN3)NC(=O)NC4=CC=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
22,71575215,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-[4-(1-methylpyrazolo[3,4-d]pyrimidin-4-yl)ox...",CN1C2=C(C=N1)C(=NC=N2)OC3=CC=C(C=C3)NC(=O)NC4=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
23,71575214,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(3-methoxyphenyl)-3-[4-(1-methylpyrazolo[3,4...",CN1C2=C(C=N1)C(=NC=N2)OC3=CC=C(C=C3)NC(=O)NC4=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
24,71575212,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(2,3-dimethylphenyl)-3-[4-(1H-pyrazolo[3,4-d...",CC1=C(C(=CC=C1)NC(=O)NC2=CC=C(C=C2)OC3=NC=NC4=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
25,71575211,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(4-bromophenyl)-3-[4-(1H-pyrazolo[3,4-d]pyri...",C1=CC(=CC=C1NC(=O)NC2=CC=C(C=C2)Br)OC3=NC=NC4=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
26,71575210,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(3-methoxyphenyl)-3-[4-(1H-pyrazolo[3,4-d]py...",COC1=CC=CC(=C1)NC(=O)NC2=CC=C(C=C2)OC3=NC=NC4=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
27,71575116,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(1-phenylethyl)-3-[4-(1H-pyrazolo[3,4-d]pyri...",CC(C1=CC=CC=C1)NC(=O)NC2=CC=C(C=C2)NC3=NC=NC4=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
28,71575115,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-ylamino)ph...",C1=CC(=CC=C1C(F)(F)F)NC(=O)NC2=CC=C(C=C2)NC3=N...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
29,71575114,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(2,3-dimethylphenyl)-3-[4-(1H-pyrazolo[3,4-d...",CC1=C(C(=CC=C1)NC(=O)NC2=CC=C(C=C2)NC3=NC=NC4=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
30,71575113,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(4-bromophenyl)-3-[4-(1H-pyrazolo[3,4-d]pyri...",C1=CC(=CC=C1NC2=NC=NC3=C2C=NN3)NC(=O)NC4=CC=C(...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised
31,71575112,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,Protein,Binding_DB,D.rerio,"1-(3-methoxyphenyl)-3-[4-(1H-pyrazolo[3,4-d]py...",COC1=CC=CC(=C1)NC(=O)NC2=CC=C(C=C2)NC3=NC=NC4=...,Vascular endothelial growth factor receptor 2 ...,Pubchem,Uniprot_ID,Generalised

In [8]:
bindingdb[bindingdb['head_detail_name'].isna()]

Empty DataFrame
Columns: [head, relation, tail, head_type, tail_type, kg_source, species, head_detail_name, head_smile_name, tail_detail_name, head_id_is, tail_id_is, kg_type]
Index: []

# Consolidate into Unified Schem

In [9]:
# List all source DataFrames to include
source_dfs = [
     bindingdb
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 32

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,71575543,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",Vascular endothelial growth factor receptor 2 ...,D.rerio
1,71575213,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",Vascular endothelial growth factor receptor 2 ...,D.rerio
2,71575641,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,1-[2-chloro-4-(trifluoromethyl)phenyl]-3-[4-(1...,Vascular endothelial growth factor receptor 2 ...,D.rerio
3,71575640,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-[3,5-bis(trifluoromethyl)phenyl]-3-[4-(1H-py...",Vascular endothelial growth factor receptor 2 ...,D.rerio
4,71575546,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",Vascular endothelial growth factor receptor 2 ...,D.rerio
5,71575545,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(3-fluorophenyl)-3-[4-(1H-pyrazolo[3,4-d]pyr...",Vascular endothelial growth factor receptor 2 ...,D.rerio
6,71575544,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(3-propan-2-ylphenyl)-3-[4-(1H-pyrazolo[3,4-...",Vascular endothelial growth factor receptor 2 ...,D.rerio
7,71575542,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,1-(4-morpholin-4-ylphenyl)-3-[4-(1H-pyrazolo[3...,Vascular endothelial growth factor receptor 2 ...,D.rerio
8,71575541,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(4-fluorophenyl)-3-[4-(1H-pyrazolo[3,4-d]pyr...",Vascular endothelial growth factor receptor 2 ...,D.rerio
9,71716376,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(cyclohexylmethyl)-3-[4-(1H-pyrazolo[3,4-d]p...",Vascular endothelial growth factor receptor 2 ...,D.rerio
10,71720643,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-cyclohexyl-3-[4-(1H-pyrazolo[3,4-d]pyrimidin...",Vascular endothelial growth factor receptor 2 ...,D.rerio
11,71718823,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(1-phenylethyl)-3-[4-(1H-pyrazolo[3,4-d]pyri...",Vascular endothelial growth factor receptor 2 ...,D.rerio
12,71720012,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",Vascular endothelial growth factor receptor 2 ...,D.rerio
13,71575438,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-phenyl-3-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-y...",Vascular endothelial growth factor receptor 2 ...,D.rerio
14,71575437,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"2-(4-bromophenyl)-N-[4-(1H-pyrazolo[3,4-d]pyri...",Vascular endothelial growth factor receptor 2 ...,D.rerio
15,71575436,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"4-bromo-N-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-yl...",Vascular endothelial growth factor receptor 2 ...,D.rerio
16,71575327,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"4-bromo-N-[3-(1H-pyrazolo[3,4-d]pyrimidin-4-yl...",Vascular endothelial growth factor receptor 2 ...,D.rerio
17,71575326,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"N-[3-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",Vascular endothelial growth factor receptor 2 ...,D.rerio
18,71575325,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"2-(4-bromophenyl)-N-[3-(1H-pyrazolo[3,4-d]pyri...",Vascular endothelial growth factor receptor 2 ...,D.rerio
19,71575324,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"N-[3-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",Vascular endothelial growth factor receptor 2 ...,D.rerio
20,71575323,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(4-bromophenyl)-3-[3-(1H-pyrazolo[3,4-d]pyri...",Vascular endothelial growth factor receptor 2 ...,D.rerio
21,71575322,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-[3-(1H-pyrazolo[3,4-d]pyrimidin-4-yloxy)phen...",Vascular endothelial growth factor receptor 2 ...,D.rerio
22,71575215,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-[4-(1-methylpyrazolo[3,4-d]pyrimidin-4-yl)ox...",Vascular endothelial growth factor receptor 2 ...,D.rerio
23,71575214,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(3-methoxyphenyl)-3-[4-(1-methylpyrazolo[3,4...",Vascular endothelial growth factor receptor 2 ...,D.rerio
24,71575212,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(2,3-dimethylphenyl)-3-[4-(1H-pyrazolo[3,4-d...",Vascular endothelial growth factor receptor 2 ...,D.rerio
25,71575211,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(4-bromophenyl)-3-[4-(1H-pyrazolo[3,4-d]pyri...",Vascular endothelial growth factor receptor 2 ...,D.rerio
26,71575210,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(3-methoxyphenyl)-3-[4-(1H-pyrazolo[3,4-d]py...",Vascular endothelial growth factor receptor 2 ...,D.rerio
27,71575116,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(1-phenylethyl)-3-[4-(1H-pyrazolo[3,4-d]pyri...",Vascular endothelial growth factor receptor 2 ...,D.rerio
28,71575115,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-[4-(1H-pyrazolo[3,4-d]pyrimidin-4-ylamino)ph...",Vascular endothelial growth factor receptor 2 ...,D.rerio
29,71575114,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(2,3-dimethylphenyl)-3-[4-(1H-pyrazolo[3,4-d...",Vascular endothelial growth factor receptor 2 ...,D.rerio
30,71575113,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(4-bromophenyl)-3-[4-(1H-pyrazolo[3,4-d]pyri...",Vascular endothelial growth factor receptor 2 ...,D.rerio
31,71575112,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(3-methoxyphenyl)-3-[4-(1H-pyrazolo[3,4-d]py...",Vascular endothelial growth factor receptor 2 ...,D.rerio

# Sanity Check — Distinct Values

In [10]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'ChemicalEntity_Protein'}
head_type           : {'ChemicalEntity'}
tail_type           : {'Protein'}
relation_type       : {None}
kg_source           : {'Binding_DB'}
head_id_is          : {'Pubchem'}
tail_id_is          : {'Uniprot_ID'}

In [11]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 32 remaining

# NaN Audit (pre-dedup)

In [12]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            32                   0              32
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [13]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 32  |  After dedup: 32

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,71575112,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(3-methoxyphenyl)-3-[4-(1H-pyrazolo[3,4-d]py...",Vascular endothelial growth factor receptor 2 ...,D.rerio
1,71575113,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(4-bromophenyl)-3-[4-(1H-pyrazolo[3,4-d]pyri...",Vascular endothelial growth factor receptor 2 ...,D.rerio
2,71575114,ChemicalEntity_Protein,Q5GIT4,ChemicalEntity,None,Protein,Binding_DB,Generalised,Pubchem,Uniprot_ID,"1-(2,3-dimethylphenyl)-3-[4-(1H-pyrazolo[3,4-d...",Vascular endothelial growth factor receptor 2 ...,D.rerio

In [14]:
final_df_dedup['species'] = 'D.rerio'

In [15]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            32                   0              32
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [16]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Binding_DB'} kg_source
Binding_DB    32
Name: count, dtype: int64

In [17]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    32
Name: count, dtype: int64

In [21]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 32 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_chemical_protein/Zebrafish_chemical_protein.csv

In [19]:
# OUT_PATH