In [17]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [18]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish

In [19]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_gene_molecularfunction/Zebrafish_gene_molecularfunction.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [20]:
#

In [21]:
# Zebrafish = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Danio_rerio.gene_info',
#     sep='\t',
    
# )
# # Zebrafish["LocusTag"] = Zebrafish["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Zebrafish_symbol2Locus_dict = dict(zip(Zebrafish['Symbol'], Zebrafish['LocusTag']))
# # Zebrafish
# # Zebrafish_symbol2Locus_dict
# Zebrafish

# Monarch

In [22]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Zebrafish/Gene_Zebra_MolecularFunction.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'

monarch['species'] = 'D.rerio'
print(f"monarch: {len(monarch):,} rows")
monarch = monarch[~monarch['head'].str.contains(':')]
monarch

monarch: 87,351 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,dnm2a,Gene_MolecularFunction,GO:0003924,Gene,enables,MolecularFunction,infores:go-central,dynamin 2a,GTPase activity,Danio rerio,NaN,NCBI,Quick_GO,dnm2a,D.rerio,Generalised,Monarch_KG
1,triobpa,Gene_MolecularFunction,GO:0051015,Gene,enables,MolecularFunction,infores:go-central,TRIO and F-actin binding protein a,actin filament binding,Danio rerio,NaN,NCBI,Quick_GO,triobpa,D.rerio,Generalised,Monarch_KG
2,creb3l3l,Gene_MolecularFunction,GO:0000981,Gene,enables,MolecularFunction,infores:go-central,cAMP responsive element binding protein 3-like...,"DNA-binding transcription factor activity, RNA...",Danio rerio,NaN,NCBI,Quick_GO,creb3l3l,D.rerio,Generalised,Monarch_KG
4,gbx1,Gene_MolecularFunction,GO:0000977,Gene,enables,MolecularFunction,infores:go-central,gastrulation brain homeobox 1,RNA polymerase II transcription regulatory reg...,Danio rerio,NaN,NCBI,Quick_GO,gbx1,D.rerio,Generalised,Monarch_KG
5,thrap3a,Gene_MolecularFunction,GO:0003712,Gene,enables,MolecularFunction,infores:go-central,thyroid hormone receptor associated protein 3a,transcription coregulator activity,Danio rerio,NaN,NCBI,Quick_GO,thrap3a,D.rerio,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87992,ppm1aa,Gene_MolecularFunction,GO:0004722,Gene,enables,MolecularFunction,infores:zfin,"protein phosphatase, Mg2+/Mn2+ dependent, 1Aa",protein serine/threonine phosphatase activity,Danio rerio,NaN,NCBI,Quick_GO,ppm1aa,D.rerio,Generalised,Monarch_KG
87993,tbxas1,Gene_MolecularFunction,GO:0004796,Gene,enables,MolecularFunction,infores:zfin,thromboxane A synthase 1 (platelet),thromboxane-A synthase activity,Danio rerio,NaN,NCBI,Quick_GO,tbxas1,D.rerio,Generalised,Monarch_KG
87994,crot,Gene_MolecularFunction,GO:0008458,Gene,enables,MolecularFunction,infores:zfin,carnitine O-octanoyltransferase,carnitine O-octanoyltransferase activity,Danio rerio,NaN,NCBI,Quick_GO,crot,D.rerio,Generalised,Monarch_KG
87995,echdc1,Gene_MolecularFunction,GO:0004492,Gene,enables,MolecularFunction,infores:zfin,enoyl CoA hydratase domain containing 1,methyl/ethyl malonyl-CoA decarboxylase activity,Danio rerio,NaN,NCBI,Quick_GO,echdc1,D.rerio,Generalised,Monarch_KG
87996,ssh1b,Gene_MolecularFunction,GO:0017018,Gene,enables,MolecularFunction,infores:zfin,slingshot protein phosphatase 1b,myosin phosphatase activity,Danio rerio,NaN,NCBI,Quick_GO,ssh1b,D.rerio,Generalised,Monarch_KG

In [23]:
monarch[monarch['head_detail_name'].isna()]

Empty DataFrame
Columns: [head, relation, tail, head_type, relation_type, tail_type, relation_source, head_detail_name, tail_detail_name, head_taxon_name, tail_taxon_name, head_id_is, tail_id_is, head_name, species, kg_type, kg_source]
Index: []

# Consolidate into Unified Schem

In [24]:
# List all source DataFrames to include
source_dfs = [
     monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 80,883

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,dnm2a,Gene_MolecularFunction,GO:0003924,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI,Quick_GO,dynamin 2a,GTPase activity,D.rerio
1,triobpa,Gene_MolecularFunction,GO:0051015,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI,Quick_GO,TRIO and F-actin binding protein a,actin filament binding,D.rerio
2,creb3l3l,Gene_MolecularFunction,GO:0000981,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI,Quick_GO,cAMP responsive element binding protein 3-like...,"DNA-binding transcription factor activity, RNA...",D.rerio
3,gbx1,Gene_MolecularFunction,GO:0000977,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI,Quick_GO,gastrulation brain homeobox 1,RNA polymerase II transcription regulatory reg...,D.rerio
4,thrap3a,Gene_MolecularFunction,GO:0003712,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI,Quick_GO,thyroid hormone receptor associated protein 3a,transcription coregulator activity,D.rerio
...,...,...,...,...,...,...,...,...,...,...,...,...,...
80878,ppm1aa,Gene_MolecularFunction,GO:0004722,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI,Quick_GO,"protein phosphatase, Mg2+/Mn2+ dependent, 1Aa",protein serine/threonine phosphatase activity,D.rerio
80879,tbxas1,Gene_MolecularFunction,GO:0004796,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI,Quick_GO,thromboxane A synthase 1 (platelet),thromboxane-A synthase activity,D.rerio
80880,crot,Gene_MolecularFunction,GO:0008458,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI,Quick_GO,carnitine O-octanoyltransferase,carnitine O-octanoyltransferase activity,D.rerio
80881,echdc1,Gene_MolecularFunction,GO:0004492,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI,Quick_GO,enoyl CoA hydratase domain containing 1,methyl/ethyl malonyl-CoA decarboxylase activity,D.rerio
80882,ssh1b,Gene_MolecularFunction,GO:0017018,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI,Quick_GO,slingshot protein phosphatase 1b,myosin phosphatase activity,D.rerio

# Sanity Check — Distinct Values

In [25]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_MolecularFunction'}
head_type           : {'Gene'}
tail_type           : {'MolecularFunction'}
relation_type       : {'contributes_to', 'enables'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'NCBI'}
tail_id_is          : {'Quick_GO'}

In [26]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 80,883 remaining

# NaN Audit (pre-dedup)

In [27]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [28]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 80,883  |  After dedup: 50,075

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,42sp43,Gene_MolecularFunction,GO:0046872,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI,Quick_GO,P43 5S RNA-binding protein,metal ion binding,D.rerio
1,ATP6,Gene_MolecularFunction,GO:0015078,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI,Quick_GO,ATP synthase F0 subunit 6,proton transmembrane transporter activity,D.rerio
2,ATP6,Gene_MolecularFunction,GO:0046933,Gene,contributes_to,MolecularFunction,Monarch_KG,Generalised,NCBI,Quick_GO,ATP synthase F0 subunit 6,"proton-transporting ATP synthase activity, rot...",D.rerio

In [29]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [30]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    50075
Name: count, dtype: int64

In [31]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    50075
Name: count, dtype: int64

In [32]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 50,075 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_gene_molecularfunction/Zebrafish_gene_molecularfunction.csv

In [33]:
# OUT_PATH