In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_gene_cellularcomponent/Zebrafish_gene_cellularcomponent.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [5]:
#

In [6]:
# Zebrafish = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Danio_rerio.gene_info',
#     sep='\t',
    
# )
# # Zebrafish["LocusTag"] = Zebrafish["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Zebrafish_symbol2Locus_dict = dict(zip(Zebrafish['Symbol'], Zebrafish['LocusTag']))
# # Zebrafish
# # Zebrafish_symbol2Locus_dict
# Zebrafish

# Monarch

In [4]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Zebrafish/Gene_Zebra_CellularComponent.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'

monarch['species'] = 'D.rerio'
print(f"monarch: {len(monarch):,} rows")
monarch = monarch[~monarch['head'].str.contains(':')]
monarch

monarch: 66,826 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,plxnd1,Gene_CellularComponent,GO:0002116,Gene,part_of,CellularComponent,infores:go-central,plexin D1,semaphorin receptor complex,Danio rerio,NaN,NCBI,Quick_GO,plxnd1,D.rerio,Generalised,Monarch_KG
1,unc119b,Gene_CellularComponent,GO:0005929,Gene,is_active_in,CellularComponent,infores:go-central,unc-119 lipid binding chaperone B,cilium,Danio rerio,NaN,NCBI,Quick_GO,unc119b,D.rerio,Generalised,Monarch_KG
2,scarb2a,Gene_CellularComponent,GO:0005886,Gene,is_active_in,CellularComponent,infores:go-central,"scavenger receptor class B, member 2a",plasma membrane,Danio rerio,NaN,NCBI,Quick_GO,scarb2a,D.rerio,Generalised,Monarch_KG
3,exd2,Gene_CellularComponent,GO:0005737,Gene,is_active_in,CellularComponent,infores:go-central,exonuclease 3'-5' domain containing 2,cytoplasm,Danio rerio,NaN,NCBI,Quick_GO,exd2,D.rerio,Generalised,Monarch_KG
5,ptger2b,Gene_CellularComponent,GO:0005886,Gene,is_active_in,CellularComponent,infores:go-central,prostaglandin E receptor 2b (subtype EP2),plasma membrane,Danio rerio,NaN,NCBI,Quick_GO,ptger2b,D.rerio,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67364,tor1l1,Gene_CellularComponent,GO:0042995,Gene,located_in,CellularComponent,infores:zfin,torsin family 1 like 1,cell projection,Danio rerio,NaN,NCBI,Quick_GO,tor1l1,D.rerio,Generalised,Monarch_KG
67365,cenpq,Gene_CellularComponent,GO:0000775,Gene,located_in,CellularComponent,infores:zfin,centromere protein Q,"chromosome, centromeric region",Danio rerio,NaN,NCBI,Quick_GO,cenpq,D.rerio,Generalised,Monarch_KG
67366,cenpq,Gene_CellularComponent,GO:0005694,Gene,located_in,CellularComponent,infores:zfin,centromere protein Q,chromosome,Danio rerio,NaN,NCBI,Quick_GO,cenpq,D.rerio,Generalised,Monarch_KG
67367,cenpq,Gene_CellularComponent,GO:0005634,Gene,located_in,CellularComponent,infores:zfin,centromere protein Q,nucleus,Danio rerio,NaN,NCBI,Quick_GO,cenpq,D.rerio,Generalised,Monarch_KG
67368,tgm8,Gene_CellularComponent,GO:0005886,Gene,located_in,CellularComponent,infores:zfin,transglutaminase 8,plasma membrane,Danio rerio,NaN,NCBI,Quick_GO,tgm8,D.rerio,Generalised,Monarch_KG

In [5]:
monarch[monarch['head_detail_name'].isna()]

Empty DataFrame
Columns: [head, relation, tail, head_type, relation_type, tail_type, relation_source, head_detail_name, tail_detail_name, head_taxon_name, tail_taxon_name, head_id_is, tail_id_is, head_name, species, kg_type, kg_source]
Index: []

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
     monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 62,407

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,plxnd1,Gene_CellularComponent,GO:0002116,Gene,part_of,CellularComponent,Monarch_KG,Generalised,NCBI,Quick_GO,plexin D1,semaphorin receptor complex,D.rerio
1,unc119b,Gene_CellularComponent,GO:0005929,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI,Quick_GO,unc-119 lipid binding chaperone B,cilium,D.rerio
2,scarb2a,Gene_CellularComponent,GO:0005886,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI,Quick_GO,"scavenger receptor class B, member 2a",plasma membrane,D.rerio
3,exd2,Gene_CellularComponent,GO:0005737,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI,Quick_GO,exonuclease 3'-5' domain containing 2,cytoplasm,D.rerio
4,ptger2b,Gene_CellularComponent,GO:0005886,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI,Quick_GO,prostaglandin E receptor 2b (subtype EP2),plasma membrane,D.rerio
...,...,...,...,...,...,...,...,...,...,...,...,...,...
62402,tor1l1,Gene_CellularComponent,GO:0042995,Gene,located_in,CellularComponent,Monarch_KG,Generalised,NCBI,Quick_GO,torsin family 1 like 1,cell projection,D.rerio
62403,cenpq,Gene_CellularComponent,GO:0000775,Gene,located_in,CellularComponent,Monarch_KG,Generalised,NCBI,Quick_GO,centromere protein Q,"chromosome, centromeric region",D.rerio
62404,cenpq,Gene_CellularComponent,GO:0005694,Gene,located_in,CellularComponent,Monarch_KG,Generalised,NCBI,Quick_GO,centromere protein Q,chromosome,D.rerio
62405,cenpq,Gene_CellularComponent,GO:0005634,Gene,located_in,CellularComponent,Monarch_KG,Generalised,NCBI,Quick_GO,centromere protein Q,nucleus,D.rerio
62406,tgm8,Gene_CellularComponent,GO:0005886,Gene,located_in,CellularComponent,Monarch_KG,Generalised,NCBI,Quick_GO,transglutaminase 8,plasma membrane,D.rerio

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_CellularComponent'}
head_type           : {'Gene'}
tail_type           : {'CellularComponent'}
relation_type       : {'is_active_in', 'located_in', 'colocalizes_with', 'part_of'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'NCBI'}
tail_id_is          : {'Quick_GO'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 62,407 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 62,407  |  After dedup: 43,025

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,42sp43,Gene_CellularComponent,GO:0005634,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI,Quick_GO,P43 5S RNA-binding protein,nucleus,D.rerio
1,ATP6,Gene_CellularComponent,GO:0005739,Gene,located_in,CellularComponent,Monarch_KG,Generalised,NCBI,Quick_GO,ATP synthase F0 subunit 6,mitochondrion,D.rerio
2,ATP6,Gene_CellularComponent,GO:0005743,Gene,located_in,CellularComponent,Monarch_KG,Generalised,NCBI,Quick_GO,ATP synthase F0 subunit 6,mitochondrial inner membrane,D.rerio

In [11]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    43025
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    43025
Name: count, dtype: int64

In [14]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 43,025 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Zebrafish/Zebrafish_gene_cellularcomponent/Zebrafish_gene_cellularcomponent.csv

In [15]:
# OUT_PATH