In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Celegans_phenotype_chemical
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_phenotype_chemical/Celegans_phenotype_chemical.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Celegans_phenotype_chemical’: File exists

# Monarch

In [4]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Celegans/Cele_Phenotype_ChemicalEntity.csv')
monarch.columns = monarch.columns.str.lower()
monarch['kg_type'] = 'Generalised'
monarch['species'] = 'C.elegans'

monarch['kg_source'] = 'Monarch_KG'
#

print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 11 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,tail_iupac_name,species,kg_type,kg_source
0,WBPhenotype:0000507,Phenotype_ChemicalEntity,187,Phenotype,related_to,ChemicalEntity,infores:upheno,acetylcholine levels variant,acetylcholine,Caenorhabditis elegans,NaN,WormBasePhenotype,PubChem,2-acetyloxyethyl(trimethyl)azanium,C.elegans,Generalised,Monarch_KG
1,WBPhenotype:0000552,Phenotype_ChemicalEntity,119,Phenotype,related_to,ChemicalEntity,infores:upheno,GABA levels variant,gamma-aminobutyric acid,Caenorhabditis elegans,NaN,WormBasePhenotype,PubChem,4-aminobutanoic acid,C.elegans,Generalised,Monarch_KG
2,WBPhenotype:0001574,Phenotype_ChemicalEntity,5957,Phenotype,related_to,ChemicalEntity,infores:upheno,ATP levels variant,ATP,Caenorhabditis elegans,NaN,WormBasePhenotype,PubChem,"[[(2R,3S,4R,5R)-5-(6-aminopurin-9-yl)-3,4-dihy...",C.elegans,Generalised,Monarch_KG
3,WBPhenotype:0001575,Phenotype_ChemicalEntity,5957,Phenotype,related_to,ChemicalEntity,infores:upheno,ATP levels reduced,ATP,Caenorhabditis elegans,NaN,WormBasePhenotype,PubChem,"[[(2R,3S,4R,5R)-5-(6-aminopurin-9-yl)-3,4-dihy...",C.elegans,Generalised,Monarch_KG
4,WBPhenotype:0001899,Phenotype_ChemicalEntity,124886,Phenotype,related_to,ChemicalEntity,infores:upheno,glutathione levels variant,glutathione,Caenorhabditis elegans,NaN,WormBasePhenotype,PubChem,(2S)-2-amino-5-[[(2R)-1-(carboxymethylamino)-1...,C.elegans,Generalised,Monarch_KG
5,WBPhenotype:0002264,Phenotype_ChemicalEntity,5957,Phenotype,related_to,ChemicalEntity,infores:upheno,ATP levels increased,ATP,Caenorhabditis elegans,NaN,WormBasePhenotype,PubChem,"[[(2R,3S,4R,5R)-5-(6-aminopurin-9-yl)-3,4-dihy...",C.elegans,Generalised,Monarch_KG
6,WBPhenotype:0002350,Phenotype_ChemicalEntity,784,Phenotype,related_to,ChemicalEntity,infores:upheno,hydrogen peroxide levels increased,hydrogen peroxide,Caenorhabditis elegans,NaN,WormBasePhenotype,PubChem,hydrogen peroxide,C.elegans,Generalised,Monarch_KG
7,WBPhenotype:0002351,Phenotype_ChemicalEntity,784,Phenotype,related_to,ChemicalEntity,infores:upheno,hydrogen peroxide levels reduced,hydrogen peroxide,Caenorhabditis elegans,NaN,WormBasePhenotype,PubChem,hydrogen peroxide,C.elegans,Generalised,Monarch_KG
8,WBPhenotype:0002617,Phenotype_ChemicalEntity,271,Phenotype,related_to,ChemicalEntity,infores:upheno,cytosolic calcium levels increased,calcium(2+),Caenorhabditis elegans,NaN,WormBasePhenotype,PubChem,calcium(2+),C.elegans,Generalised,Monarch_KG
9,WBPhenotype:0002618,Phenotype_ChemicalEntity,271,Phenotype,related_to,ChemicalEntity,infores:upheno,cytosolic calcium levels decreased,calcium(2+),Caenorhabditis elegans,NaN,WormBasePhenotype,PubChem,calcium(2+),C.elegans,Generalised,Monarch_KG
10,WBPhenotype:0002637,Phenotype_ChemicalEntity,23925,Phenotype,related_to,ChemicalEntity,infores:upheno,iron levels decreased,iron atom,Caenorhabditis elegans,NaN,WormBasePhenotype,PubChem,iron,C.elegans,Generalised,Monarch_KG

In [5]:
#

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
    monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 11

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,WBPhenotype:0000507,Phenotype_ChemicalEntity,187,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,acetylcholine levels variant,acetylcholine,C.elegans
1,WBPhenotype:0000552,Phenotype_ChemicalEntity,119,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,GABA levels variant,gamma-aminobutyric acid,C.elegans
2,WBPhenotype:0001574,Phenotype_ChemicalEntity,5957,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,ATP levels variant,ATP,C.elegans
3,WBPhenotype:0001575,Phenotype_ChemicalEntity,5957,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,ATP levels reduced,ATP,C.elegans
4,WBPhenotype:0001899,Phenotype_ChemicalEntity,124886,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,glutathione levels variant,glutathione,C.elegans
5,WBPhenotype:0002264,Phenotype_ChemicalEntity,5957,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,ATP levels increased,ATP,C.elegans
6,WBPhenotype:0002350,Phenotype_ChemicalEntity,784,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,hydrogen peroxide levels increased,hydrogen peroxide,C.elegans
7,WBPhenotype:0002351,Phenotype_ChemicalEntity,784,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,hydrogen peroxide levels reduced,hydrogen peroxide,C.elegans
8,WBPhenotype:0002617,Phenotype_ChemicalEntity,271,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,cytosolic calcium levels increased,calcium(2+),C.elegans
9,WBPhenotype:0002618,Phenotype_ChemicalEntity,271,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,cytosolic calcium levels decreased,calcium(2+),C.elegans
10,WBPhenotype:0002637,Phenotype_ChemicalEntity,23925,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,iron levels decreased,iron atom,C.elegans

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Phenotype_ChemicalEntity'}
head_type           : {'Phenotype'}
tail_type           : {'ChemicalEntity'}
relation_type       : {'related_to'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'WormBasePhenotype'}
tail_id_is          : {'PubChem'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 11 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 11  |  After dedup: 11

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,WBPhenotype:0000507,Phenotype_ChemicalEntity,187,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,acetylcholine levels variant,acetylcholine,C.elegans
1,WBPhenotype:0000552,Phenotype_ChemicalEntity,119,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,GABA levels variant,gamma-aminobutyric acid,C.elegans
2,WBPhenotype:0001574,Phenotype_ChemicalEntity,5957,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,WormBasePhenotype,PubChem,ATP levels variant,ATP,C.elegans

In [11]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    11
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    11
Name: count, dtype: int64

In [14]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 11 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_phenotype_chemical/Celegans_phenotype_chemical.csv

In [15]:
#