In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────

!mkdir Celegans_anatomy_anatomy
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_anatomy_anatomy/Celegans_anatomy_anatomy.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Celegans_anatomy_anatomy’: File exists

# Monarch

In [4]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Celegans/Cele_AnatomicalEntity_AnatomicalEntity.csv')
monarch.columns = monarch.columns.str.lower()
monarch['kg_type'] = 'Generalised'
monarch['species'] = 'C.elegans'
monarch['relation'] = 'AnatomicalEntity_AnatomicalEntity'
monarch['head_type'] = 'AnatomicalEntity'
monarch['tail_type'] = 'AnatomicalEntity'

monarch['kg_source'] = 'Monarch_KG'

print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 15,092 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,species,kg_type,kg_source
0,WBbt:0000101,AnatomicalEntity_AnatomicalEntity,WBbt:0000100,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:wbbt,Lineage,C. elegans anatomical entity,Caenorhabditis elegans,Caenorhabditis elegans,WormBase,WormBase,C.elegans,Generalised,Monarch_KG
1,WBbt:0000102,AnatomicalEntity_AnatomicalEntity,WBbt:0000101,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:wbbt,P0 nucleus,Lineage,Caenorhabditis elegans,Caenorhabditis elegans,WormBase,WormBase,C.elegans,Generalised,Monarch_KG
2,WBbt:0000102,AnatomicalEntity_AnatomicalEntity,WBbt:0006803,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:wbbt,P0 nucleus,Nucleus,Caenorhabditis elegans,Caenorhabditis elegans,WormBase,WormBase,C.elegans,Generalised,Monarch_KG
3,WBbt:0000102,AnatomicalEntity_AnatomicalEntity,WBbt:0004422,AnatomicalEntity,related_to,AnatomicalEntity,infores:wbbt,P0 nucleus,P0,Caenorhabditis elegans,Caenorhabditis elegans,WormBase,WormBase,C.elegans,Generalised,Monarch_KG
4,WBbt:0001001,AnatomicalEntity_AnatomicalEntity,WBbt:0006803,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:wbbt,AB nucleus,Nucleus,Caenorhabditis elegans,Caenorhabditis elegans,WormBase,WormBase,C.elegans,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15087,WBbt:0008638,AnatomicalEntity_AnatomicalEntity,WBbt:0004148,AnatomicalEntity,related_to,AnatomicalEntity,infores:wbbt,Z4.appaaap nucleus hermaphrodite,Z4.appaaap hermaphrodite,Caenorhabditis elegans,Caenorhabditis elegans,WormBase,WormBase,C.elegans,Generalised,Monarch_KG
15088,WBbt:0008639,AnatomicalEntity_AnatomicalEntity,WBbt:0003565,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:wbbt,Z4.appaaaa nucleus hermaphrodite,Z4.appaaaa nucleus,Caenorhabditis elegans,Caenorhabditis elegans,WormBase,WormBase,C.elegans,Generalised,Monarch_KG
15089,WBbt:0008639,AnatomicalEntity_AnatomicalEntity,WBbt:0004150,AnatomicalEntity,related_to,AnatomicalEntity,infores:wbbt,Z4.appaaaa nucleus hermaphrodite,Z4.appaaaa hermaphrodite,Caenorhabditis elegans,Caenorhabditis elegans,WormBase,WormBase,C.elegans,Generalised,Monarch_KG
15090,WBbt:0008640,AnatomicalEntity_AnatomicalEntity,WBbt:0003565,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:wbbt,Z4.appaaaa nucleus male,Z4.appaaaa nucleus,Caenorhabditis elegans,Caenorhabditis elegans,WormBase,WormBase,C.elegans,Generalised,Monarch_KG
15091,WBbt:0008640,AnatomicalEntity_AnatomicalEntity,WBbt:0005032,AnatomicalEntity,related_to,AnatomicalEntity,infores:wbbt,Z4.appaaaa nucleus male,Z4.appaaaa male,Caenorhabditis elegans,Caenorhabditis elegans,WormBase,WormBase,C.elegans,Generalised,Monarch_KG

In [5]:
#

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
    monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 15,092

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,WBbt:0000101,AnatomicalEntity_AnatomicalEntity,WBbt:0000100,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBase,Lineage,C. elegans anatomical entity,C.elegans
1,WBbt:0000102,AnatomicalEntity_AnatomicalEntity,WBbt:0000101,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBase,P0 nucleus,Lineage,C.elegans
2,WBbt:0000102,AnatomicalEntity_AnatomicalEntity,WBbt:0006803,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBase,P0 nucleus,Nucleus,C.elegans
3,WBbt:0000102,AnatomicalEntity_AnatomicalEntity,WBbt:0004422,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBase,P0 nucleus,P0,C.elegans
4,WBbt:0001001,AnatomicalEntity_AnatomicalEntity,WBbt:0006803,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBase,AB nucleus,Nucleus,C.elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15087,WBbt:0008638,AnatomicalEntity_AnatomicalEntity,WBbt:0004148,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBase,Z4.appaaap nucleus hermaphrodite,Z4.appaaap hermaphrodite,C.elegans
15088,WBbt:0008639,AnatomicalEntity_AnatomicalEntity,WBbt:0003565,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBase,Z4.appaaaa nucleus hermaphrodite,Z4.appaaaa nucleus,C.elegans
15089,WBbt:0008639,AnatomicalEntity_AnatomicalEntity,WBbt:0004150,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBase,Z4.appaaaa nucleus hermaphrodite,Z4.appaaaa hermaphrodite,C.elegans
15090,WBbt:0008640,AnatomicalEntity_AnatomicalEntity,WBbt:0003565,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBase,Z4.appaaaa nucleus male,Z4.appaaaa nucleus,C.elegans
15091,WBbt:0008640,AnatomicalEntity_AnatomicalEntity,WBbt:0005032,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBase,Z4.appaaaa nucleus male,Z4.appaaaa male,C.elegans

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'AnatomicalEntity_AnatomicalEntity'}
head_type           : {'AnatomicalEntity'}
tail_type           : {'AnatomicalEntity'}
relation_type       : {'subclass_of', 'related_to'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'WormBase'}
tail_id_is          : {'WormBase'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 15,092 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 15,092  |  After dedup: 15,092

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,WBbt:0000101,AnatomicalEntity_AnatomicalEntity,WBbt:0000100,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBase,Lineage,C. elegans anatomical entity,C.elegans
1,WBbt:0000102,AnatomicalEntity_AnatomicalEntity,WBbt:0000101,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBase,P0 nucleus,Lineage,C.elegans
2,WBbt:0000102,AnatomicalEntity_AnatomicalEntity,WBbt:0004422,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBase,P0 nucleus,P0,C.elegans

In [11]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    15092
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    15092
Name: count, dtype: int64

In [14]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 15,092 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_anatomy_anatomy/Celegans_anatomy_anatomy.csv