In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

!mkdir Celegans_chemical_noeffect_biologicalprocess
# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_chemical_noeffect_biologicalprocess/Celegans_chemical_noeffect_biologicalprocess.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Celegans_chemical_noeffect_biologicalprocess’: File exists

# AgeXtend

In [4]:
AgeXtend = pd.read_csv(PROC_DIR + 'agextend_processed/AgeXtend_Cele_ChemicalEntity_NoEffect_BiologicalProcess.csv')
AgeXtend.columns = AgeXtend.columns.str.lower()
AgeXtend = AgeXtend[~AgeXtend['head_detail_name'].isna()]

AgeXtend['kg_type'] = 'Aging'

print(f"AgeXtend: {len(AgeXtend):,} rows")
AgeXtend['head_id_is'] = 'Pubchem'
AgeXtend['tail_id_is'] = 'Quick_GO'
AgeXtend['species'] = 'Caenorhabditis elegans'
AgeXtend['kg_source'] = 'AgeXtend'

AgeXtend

AgeXtend: 10 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,tail_detail_name,relation_source,species,data_source,anti_aging_status,anti_aging_prob,kg_type,head_id_is,tail_id_is,kg_source
0,8514,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,hexasodium;8-[[4-methyl-3-[[3-[[3-[[2-methyl-5...,CC1=C(C=C(C=C1)C(=O)NC2=C3C(=CC(=CC3=C(C=C2)S(...,aging,AgeXtend,Caenorhabditis elegans,PMID: 24134630,0,0.372763,Aging,Pubchem,Quick_GO,AgeXtend
1,107759,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"N,N'-bis[6-[(2-methoxyphenyl)methylamino]hexyl...",COC1=CC=CC=C1CNCCCCCCNCCCCCCCCNCCCCCCNCC2=CC=C...,aging,AgeXtend,Caenorhabditis elegans,PMID: 24134630,0,0.415464,Aging,Pubchem,Quick_GO,AgeXtend
2,135484644,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,trisodium;[2-[(4-carboxyphenyl)diazenyl]-4-for...,CC1=C(C(=C(C(=N1)N=NC2=CC=C(C=C2)C(=O)O)COP(=O...,aging,AgeXtend,Caenorhabditis elegans,PMID: 24134630,1,0.668222,Aging,Pubchem,Quick_GO,AgeXtend
3,426756,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"azanide;cyclobutane-1,1-dicarboxylic acid;plat...",C1CC(C1)(C(=O)O)C(=O)O.[NH2-].[NH2-].[Pt+2],aging,AgeXtend,Caenorhabditis elegans,PMID: 24134630,0,0.211349,Aging,Pubchem,Quick_GO,AgeXtend
4,11236,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,aminourea;hydrochloride,C(=O)(N)NN.Cl,aging,AgeXtend,Caenorhabditis elegans,PMID: 24134630,0,0.133482,Aging,Pubchem,Quick_GO,AgeXtend
5,443297,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,hydroxylamine;hydrochloride,NO.Cl,aging,AgeXtend,Caenorhabditis elegans,PMID: 24134630,0,0.281992,Aging,Pubchem,Quick_GO,AgeXtend
6,4353,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,N-bromoacetamide,CC(=O)NBr,aging,AgeXtend,Caenorhabditis elegans,PMID: 24134630,1,0.873322,Aging,Pubchem,Quick_GO,AgeXtend
7,3385,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"5-fluoro-1H-pyrimidine-2,4-dione",C1=C(C(=O)NC(=O)N1)F,aging,AgeXtend,Caenorhabditis elegans,PMID: 24134630,0,0.238939,Aging,Pubchem,Quick_GO,AgeXtend
8,3194,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"2-phenyl-1,2-benzoselenazol-3-one",C1=CC=C(C=C1)N2C(=O)C3=CC=CC=C3[Se]2,aging,AgeXtend,Caenorhabditis elegans,PMID: 24134630,1,0.908062,Aging,Pubchem,Quick_GO,AgeXtend
9,156790054,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,N-[(2-hydroxyphenyl)methyl]-2-(8-methoxy-6-oxo...,COC1=CC2=C(C=C1)C3=C(C=C(C=C3)OCC(=O)NCC4=CC=C...,aging,AgeXtend,Caenorhabditis elegans,https://doi.org/10.1016/j.tetlet.2023.154389,1,0.841166,Aging,Pubchem,Quick_GO,AgeXtend

# Consolidate into Unified Schem

In [5]:
# List all source DataFrames to include
source_dfs = [
    AgeXtend, 
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 10

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,8514,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,hexasodium;8-[[4-methyl-3-[[3-[[3-[[2-methyl-5...,aging,Caenorhabditis elegans
1,107759,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"N,N'-bis[6-[(2-methoxyphenyl)methylamino]hexyl...",aging,Caenorhabditis elegans
2,135484644,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,trisodium;[2-[(4-carboxyphenyl)diazenyl]-4-for...,aging,Caenorhabditis elegans
3,426756,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"azanide;cyclobutane-1,1-dicarboxylic acid;plat...",aging,Caenorhabditis elegans
4,11236,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,aminourea;hydrochloride,aging,Caenorhabditis elegans
5,443297,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,hydroxylamine;hydrochloride,aging,Caenorhabditis elegans
6,4353,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,N-bromoacetamide,aging,Caenorhabditis elegans
7,3385,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"5-fluoro-1H-pyrimidine-2,4-dione",aging,Caenorhabditis elegans
8,3194,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"2-phenyl-1,2-benzoselenazol-3-one",aging,Caenorhabditis elegans
9,156790054,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,N-[(2-hydroxyphenyl)methyl]-2-(8-methoxy-6-oxo...,aging,Caenorhabditis elegans

# Sanity Check — Distinct Values

In [6]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'ChemicalEntity_NoEffect_BiologicalProcess'}
head_type           : {'ChemicalEntity'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'AgeXtend'}
head_id_is          : {'Pubchem'}
tail_id_is          : {'Quick_GO'}

In [7]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 10 remaining

# NaN Audit (pre-dedup)

In [8]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            10                   0              10
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [9]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 10  |  After dedup: 10

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,3194,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"2-phenyl-1,2-benzoselenazol-3-one",aging,Caenorhabditis elegans
1,3385,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"5-fluoro-1H-pyrimidine-2,4-dione",aging,Caenorhabditis elegans
2,4353,ChemicalEntity_NoEffect_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,N-bromoacetamide,aging,Caenorhabditis elegans

In [10]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            10                   0              10
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [11]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'AgeXtend'} kg_source
AgeXtend    10
Name: count, dtype: int64

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    10
Name: count, dtype: int64

In [13]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 10 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_chemical_noeffect_biologicalprocess/Celegans_chemical_noeffect_biologicalprocess.csv

In [14]:
# Celegans_chemical_noeffect_biologicalprocess