In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

In [3]:
! pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

In [4]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Celegans_gene_promotes_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_gene_promotes_biologicalprocess/Celegans_gene_promotes_biologicalprocess.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Celegans_gene_promotes_biologicalprocess’: File exists

In [5]:
#

In [6]:
# Mouse = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Mus_musculus.gene_info',
#     sep='\t',
    
# )
# # Mouse["LocusTag"] = Mouse["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Mouse_symbol2Locus_dict = dict(zip(Mouse['Symbol'], Mouse['LocusTag']))
# # Mouse
# # Mouse_symbol2Locus_dict
# Mouse

# Genage

In [7]:
Genage = pd.read_csv(PROC_DIR + 'genage/Cele/Cele_Gene_Promotes_BiologicalProcess.csv')
Genage.columns = Genage.columns.str.lower()
Genage = Genage[~Genage['head_detail_name'].isna()]

Genage['kg_type'] = 'Aging'
Genage['relation'] = 'Gene_Promotes_BiologicalProcess'
print(f"Genage: {len(Genage):,} rows")
Genage['head_id_is'] = 'NCBI_ID'
Genage['tail_id_is'] = 'Quick_GO'
Genage['species'] = 'Caenorhabditis elegans'
Genage['kg_source'] = 'Genage'

Genage

Genage: 557 rows

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,relation_source,species,data_type,head_alt_name,kg_type,head_id_is,tail_id_is,kg_source
0,aat-8,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Amino acid transporter,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,aat-8,Aging,NCBI_ID,Quick_GO,Genage
1,acl-11,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Phospholipid/glycerol acyltransferase domain-c...,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,acl-11,Aging,NCBI_ID,Quick_GO,Genage
2,aco-2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"putative aconitate hydratase, mitochondrial",obsolete aging,GeneAge,Caenorhabditis elegans,Causative,aco-2,Aging,NCBI_ID,Quick_GO,Genage
3,age-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Phosphatidylinositol 3-kinase age-1,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,age-1,Aging,NCBI_ID,Quick_GO,Genage
4,akt-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Serine/threonine-protein kinase akt-1,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,akt-1,Aging,NCBI_ID,Quick_GO,Genage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552,unc-36,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,VWFA domain-containing protein;Voltage-depende...,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,unc-36,Aging,NCBI_ID,Quick_GO,Genage
553,ergo-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Piwi domain-containing protein;Piwi-like prote...,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,ergo-1,Aging,NCBI_ID,Quick_GO,Genage
554,dot-1.1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"Histone-lysine N-methyltransferase, H3 lysine-...",obsolete aging,GeneAge,Caenorhabditis elegans,Causative,dot-1.1,Aging,NCBI_ID,Quick_GO,Genage
555,cyk-3,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Ubiquitin carboxyl-terminal hydrolase cyk-3,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,cyk-3,Aging,NCBI_ID,Quick_GO,Genage
556,rpc-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,DNA-directed RNA polymerase subunit,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,rpc-1,Aging,NCBI_ID,Quick_GO,Genage

# AgingBank

In [8]:
AgingBank = pd.read_csv(PROC_DIR + 'agingbank/Celegans_AgingbankGene_promotes_BioPro.csv')
AgingBank.columns = AgingBank.columns.str.lower()
AgingBank = AgingBank[~AgingBank['head_detail_name'].isna()]

AgingBank['kg_type'] = 'Aging'
AgingBank['relation'] = 'Gene_Promotes_BiologicalProcess'
AgingBank['tail_type'] = 'BiologicalProcess'
print(f"AgingBank: {len(AgingBank):,} rows")
AgingBank['head_id_is'] = 'NCBI_ID'
AgingBank['tail_id_is'] = 'Quick_GO'
AgingBank['species'] = 'Caenorhabditis elegans'
AgingBank['kg_source'] = 'AgingBank'
AgingBank

AgingBank: 21 rows

,head,relation,tail,head_type,tail_type,kg_source,kg_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_type.1,species
0,clk-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"5-demethoxyubiquinone hydroxylase, mitochondrial",aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
1,DAF-16,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Forkhead box protein O,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
2,mir-241,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,ncRNA,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
3,miR-71,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,miscRNA,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
4,miR-83,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,ncRNA,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
5,mir-84,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,ncRNA,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
6,DAF-16,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Forkhead box protein O,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
7,DAF-18,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"Phosphatidylinositol 3,4,5-trisphosphate 3-pho...",aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
8,DAF-16,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Forkhead box protein O,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
9,pcm-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Protein-L-isoaspartate O-methyltransferase,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
10,ATFS-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Stress activated transcription factor atfs-1,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
11,DAF-16,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Forkhead box protein O,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
12,DAF-16,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Forkhead box protein O,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
13,DCT-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,NIP3 homolog,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
14,ELT-2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Transcription factor elt-2,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
15,HEL-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Spliceosome RNA helicase DDX39B homolog,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
16,HLH-30,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Helix-loop-helix protein 30,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
17,ins-6,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,putative insulin-like peptide beta-type 5,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
18,MML-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,BHLH domain-containing protein;Protein WBSCR14...,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
19,MXL-2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Max-like protein homolog 2,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
20,PQM-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Zinc finger transcription factor pqm-1,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans

# Consolidate into Unified Schem

In [9]:
# List all source DataFrames to include
source_dfs = [
    Genage, AgingBank
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 578

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,aat-8,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Amino acid transporter,obsolete aging,Caenorhabditis elegans
1,acl-11,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Phospholipid/glycerol acyltransferase domain-c...,obsolete aging,Caenorhabditis elegans
2,aco-2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,"putative aconitate hydratase, mitochondrial",obsolete aging,Caenorhabditis elegans
3,age-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Phosphatidylinositol 3-kinase age-1,obsolete aging,Caenorhabditis elegans
4,akt-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Serine/threonine-protein kinase akt-1,obsolete aging,Caenorhabditis elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
573,HLH-30,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,Helix-loop-helix protein 30,aging,Caenorhabditis elegans
574,ins-6,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,putative insulin-like peptide beta-type 5,aging,Caenorhabditis elegans
575,MML-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,BHLH domain-containing protein;Protein WBSCR14...,aging,Caenorhabditis elegans
576,MXL-2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,Max-like protein homolog 2,aging,Caenorhabditis elegans
577,PQM-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,Zinc finger transcription factor pqm-1,aging,Caenorhabditis elegans

# Sanity Check — Distinct Values

In [10]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_Promotes_BiologicalProcess'}
head_type           : {'Gene'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'Genage', 'AgingBank'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [11]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 578 remaining

# NaN Audit (pre-dedup)

In [12]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           578                   0             578
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [13]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 578  |  After dedup: 571

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,ATFS-1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,Stress activated transcription factor atfs-1,aging,Caenorhabditis elegans
1,B0024.4,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,CUB_2 domain-containing protein,obsolete aging,Caenorhabditis elegans
2,B0250.5,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,"putative 3-hydroxyisobutyrate dehydrogenase, m...",obsolete aging,Caenorhabditis elegans

In [14]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           571                   0             571
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Genage', 'AgingBank::Genage', 'AgingBank'} kg_source
Genage               554
AgingBank             16
AgingBank::Genage      1
Name: count, dtype: int64

In [16]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    571
Name: count, dtype: int64

In [17]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 571 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_gene_promotes_biologicalprocess/Celegans_gene_promotes_biologicalprocess.csv

In [18]:
# OUT_PATH