In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Celegans_gene_inhibits_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_gene_inhibits_biologicalprocess/Celegans_gene_inhibits_biologicalprocess.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Celegans_gene_inhibits_biologicalprocess’: File exists

In [4]:
#

# Genage

In [5]:
Genage = pd.read_csv(PROC_DIR + 'genage/Cele/Cele_Gene_Inhibits_BiologicalProcess.csv')
Genage.columns = Genage.columns.str.lower()
Genage = Genage[~Genage['head_detail_name'].isna()]

Genage['kg_type'] = 'Aging'

print(f"Genage: {len(Genage):,} rows")
Genage['head_id_is'] = 'NCBI_ID'
Genage['tail_id_is'] = 'Quick_GO'
Genage['species'] = 'Caenorhabditis elegans'
Genage['kg_source'] = 'Genage'

Genage

Genage: 278 rows

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,relation_source,species,data_type,head_alt_name,kg_type,head_id_is,tail_id_is,kg_source
0,aak-2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,5'-AMP-activated protein kinase catalytic subu...,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,aak-2,Aging,NCBI_ID,Quick_GO,Genage
1,abu-11,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Activated in Blocked Unfolded protein response,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,abu-11,Aging,NCBI_ID,Quick_GO,Genage
2,ain-1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ALG-1 INteracting protein,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,ain-1,Aging,NCBI_ID,Quick_GO,Genage
3,alg-2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Protein argonaute-2,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,alg-2,Aging,NCBI_ID,Quick_GO,Genage
4,arl-8,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ADP-ribosylation factor-like protein 8B,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,arl-8,Aging,NCBI_ID,Quick_GO,Genage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,mml-1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,BHLH domain-containing protein;Protein WBSCR14...,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,mml-1,Aging,NCBI_ID,Quick_GO,Genage
274,mir-124,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ncRNA,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,mir-124,Aging,NCBI_ID,Quick_GO,Genage
275,mir-71,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,miscRNA,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,mir-71,Aging,NCBI_ID,Quick_GO,Genage
276,mir-246,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ncRNA,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,mir-246,Aging,NCBI_ID,Quick_GO,Genage
277,mir-238,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ncRNA,obsolete aging,GeneAge,Caenorhabditis elegans,Causative,mir-238,Aging,NCBI_ID,Quick_GO,Genage

# AgingBank

In [6]:
AgingBank = pd.read_csv(PROC_DIR + 'agingbank/Celegans_AgingbankGene_inhibits_BioPro.csv')
AgingBank.columns = AgingBank.columns.str.lower()
AgingBank = AgingBank[~AgingBank['head_detail_name'].isna()]


AgingBank['tail_type'] = 'BiologicalProcess'
AgingBank['relation'] = 'Gene_Inhibits_BiologicalProcess'

print(f"AgingBank: {len(AgingBank):,} rows")
AgingBank['head_id_is'] = 'NCBI_ID'
AgingBank['tail_id_is'] = 'Quick_GO'
AgingBank['species'] = 'Caenorhabditis elegans'
AgingBank['kg_source'] = 'AgingBank'
AgingBank

AgingBank: 64 rows

,head,relation,tail,head_type,tail_type,kg_source,kg_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_type.1,species
0,cbp-1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Protein cbp-1,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
1,DAF-16,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Forkhead box protein O,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
2,DAF-16,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Forkhead box protein O,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
3,DAF-16,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Forkhead box protein O,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
4,DAF-16,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Forkhead box protein O,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,SACY-1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,RNA helicase,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
60,SKN-1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,BZIP domain-containing protein;Protein skinhead-1,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
61,SKN-1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,BZIP domain-containing protein;Protein skinhead-1,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
62,SPT-4,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Transcription elongation factor SPT4,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans
63,UNC-104,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Kinesin-like protein unc-104,aging,NCBI_ID,Quick_GO,Aging,Caenorhabditis elegans

# Consolidate into Unified Schem

In [7]:
# List all source DataFrames to include
source_dfs = [
    Genage, AgingBank
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 342

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,aak-2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,5'-AMP-activated protein kinase catalytic subu...,obsolete aging,Caenorhabditis elegans
1,abu-11,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Activated in Blocked Unfolded protein response,obsolete aging,Caenorhabditis elegans
2,ain-1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,ALG-1 INteracting protein,obsolete aging,Caenorhabditis elegans
3,alg-2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Protein argonaute-2,obsolete aging,Caenorhabditis elegans
4,arl-8,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,ADP-ribosylation factor-like protein 8B,obsolete aging,Caenorhabditis elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,SACY-1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,RNA helicase,aging,Caenorhabditis elegans
338,SKN-1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,BZIP domain-containing protein;Protein skinhead-1,aging,Caenorhabditis elegans
339,SKN-1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,BZIP domain-containing protein;Protein skinhead-1,aging,Caenorhabditis elegans
340,SPT-4,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,Transcription elongation factor SPT4,aging,Caenorhabditis elegans
341,UNC-104,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,Kinesin-like protein unc-104,aging,Caenorhabditis elegans

# Sanity Check — Distinct Values

In [8]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_Inhibits_BiologicalProcess'}
head_type           : {'Gene'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'Genage', 'AgingBank'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [9]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 342 remaining

# NaN Audit (pre-dedup)

In [10]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           342                   0             342
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [11]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 342  |  After dedup: 305

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,AGE-1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,Phosphatidylinositol 3-kinase age-1,aging,Caenorhabditis elegans
1,C14A4.9,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,C6 domain-containing protein,obsolete aging,Caenorhabditis elegans
2,C26B9.3,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Uncharacterized protein,obsolete aging,Caenorhabditis elegans

In [12]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           305                   0             305
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Genage', 'AgingBank', 'AgingBank::Genage'} kg_source
Genage               272
AgingBank             27
AgingBank::Genage      6
Name: count, dtype: int64

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    305
Name: count, dtype: int64

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 305 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_gene_inhibits_biologicalprocess/Celegans_gene_inhibits_biologicalprocess.csv

In [16]:
# OUT_PATH

In [17]:
# !mkdir Celegans_gene_inhibits_biologicalprocess