In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

In [3]:
# Gene → CellularComponent
# Monarch/Monarch_final/Celegans/Gene_Cele_CellularComponent.csv

In [4]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Celegans_gene_MolecularFunction
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_gene_MolecularFunction/Celegans_gene_MolecularFunction.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Celegans_gene_MolecularFunction’: File exists

In [5]:
# cele = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Caenorhabditis_elegans.gene_info',
#     sep='\t',
    
# )
# cele["LocusTag"] = cele["LocusTag"].str.replace("CELE_", "", regex=False)

# cele_symbol2Locus_dict = dict(zip(cele['Symbol'], cele['LocusTag']))
# cele
# # cele_symbol2Locus_dict

In [6]:
PROC_DIR#+Monarch/Monarch_final/Celegans
!ls /storage/Arushi/090526_EvoAge/kg_formation/processed_data/Monarch/Monarch_final/Celegans

Cele_AnatomicalEntity_AnatomicalEntity.csv    Gene_Cele_Anatomy.csv
Cele_Gene_Pathway.csv			      Gene_Cele_BiologicalProcess.csv
Cele_Phenotype_CellularComponent.csv	      Gene_Cele_CellularComponent.csv
Cele_Phenotype_ChemicalEntity.csv	      Gene_Cele_MolecularFunction.csv
Cele_PhenotypicFeature_BiologicalProcess.csv  Gene_Cele_Phenotype.csv
Cele_PhenotypicFeature_MolecularFunction.csv  GENE_GENE_Cele_Cele.csv

# Monarch

In [7]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Celegans/Gene_Cele_MolecularFunction.csv')
monarch.columns = monarch.columns.str.lower()
monarch['kg_type'] = 'Generalised'
monarch['species'] = 'C.elegans'

monarch['kg_source'] = 'Monarch_KG'


print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 39,781 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,Y75B8A.14,Gene_MolecularFunction,GO:0005515,Gene,enables,MolecularFunction,infores:intact,GPN-loop GTPase 3,protein binding,Caenorhabditis elegans,NaN,WormBase,Quick_GO,gex-4,C.elegans,Generalised,Monarch_KG
1,Y75B8A.14,Gene_MolecularFunction,GO:0005515,Gene,enables,MolecularFunction,infores:intact,GPN-loop GTPase 3,protein binding,Caenorhabditis elegans,NaN,WormBase,Quick_GO,gex-4,C.elegans,Generalised,Monarch_KG
2,Y75B8A.14,Gene_MolecularFunction,GO:0005525,Gene,enables,MolecularFunction,infores:uniprot,GPN-loop GTPase 3,GTP binding,Caenorhabditis elegans,NaN,WormBase,Quick_GO,gex-4,C.elegans,Generalised,Monarch_KG
3,Y75B8A.14,Gene_MolecularFunction,GO:0016787,Gene,enables,MolecularFunction,infores:uniprot,GPN-loop GTPase 3,hydrolase activity,Caenorhabditis elegans,NaN,WormBase,Quick_GO,gex-4,C.elegans,Generalised,Monarch_KG
4,Y75B8A.17,Gene_MolecularFunction,GO:0005515,Gene,enables,MolecularFunction,infores:uniprot,Geminin homolog,protein binding,Caenorhabditis elegans,NaN,WormBase,Quick_GO,gmn-1,C.elegans,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39776,Y75B8A.6,Gene_MolecularFunction,GO:0008270,Gene,enables,MolecularFunction,infores:interpro,CXXC-type domain-containing protein,zinc ion binding,Caenorhabditis elegans,NaN,WormBase,Quick_GO,Y75B8A.6,C.elegans,Generalised,Monarch_KG
39777,Y75B8A.6,Gene_MolecularFunction,GO:0017056,Gene,enables,MolecularFunction,infores:interpro,CXXC-type domain-containing protein,structural constituent of nuclear pore,Caenorhabditis elegans,NaN,WormBase,Quick_GO,Y75B8A.6,C.elegans,Generalised,Monarch_KG
39778,Y75B8A.6,Gene_MolecularFunction,GO:0046872,Gene,enables,MolecularFunction,infores:uniprot,CXXC-type domain-containing protein,metal ion binding,Caenorhabditis elegans,NaN,WormBase,Quick_GO,Y75B8A.6,C.elegans,Generalised,Monarch_KG
39779,Y75B8A.10,Gene_MolecularFunction,GO:0046872,Gene,enables,MolecularFunction,infores:uniprot,RING-type domain-containing protein,metal ion binding,Caenorhabditis elegans,NaN,WormBase,Quick_GO,Y75B8A.10,C.elegans,Generalised,Monarch_KG
39780,Y75B8A.11,Gene_MolecularFunction,GO:0071855,Gene,enables,MolecularFunction,infores:uniprot,LURY-1-2,neuropeptide receptor binding,Caenorhabditis elegans,NaN,WormBase,Quick_GO,lury-1,C.elegans,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [8]:
# List all source DataFrames to include
source_dfs = [
     monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 39,781

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Y75B8A.14,Gene_MolecularFunction,GO:0005515,Gene,enables,MolecularFunction,Monarch_KG,Generalised,WormBase,Quick_GO,GPN-loop GTPase 3,protein binding,C.elegans
1,Y75B8A.14,Gene_MolecularFunction,GO:0005515,Gene,enables,MolecularFunction,Monarch_KG,Generalised,WormBase,Quick_GO,GPN-loop GTPase 3,protein binding,C.elegans
2,Y75B8A.14,Gene_MolecularFunction,GO:0005525,Gene,enables,MolecularFunction,Monarch_KG,Generalised,WormBase,Quick_GO,GPN-loop GTPase 3,GTP binding,C.elegans
3,Y75B8A.14,Gene_MolecularFunction,GO:0016787,Gene,enables,MolecularFunction,Monarch_KG,Generalised,WormBase,Quick_GO,GPN-loop GTPase 3,hydrolase activity,C.elegans
4,Y75B8A.17,Gene_MolecularFunction,GO:0005515,Gene,enables,MolecularFunction,Monarch_KG,Generalised,WormBase,Quick_GO,Geminin homolog,protein binding,C.elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39776,Y75B8A.6,Gene_MolecularFunction,GO:0008270,Gene,enables,MolecularFunction,Monarch_KG,Generalised,WormBase,Quick_GO,CXXC-type domain-containing protein,zinc ion binding,C.elegans
39777,Y75B8A.6,Gene_MolecularFunction,GO:0017056,Gene,enables,MolecularFunction,Monarch_KG,Generalised,WormBase,Quick_GO,CXXC-type domain-containing protein,structural constituent of nuclear pore,C.elegans
39778,Y75B8A.6,Gene_MolecularFunction,GO:0046872,Gene,enables,MolecularFunction,Monarch_KG,Generalised,WormBase,Quick_GO,CXXC-type domain-containing protein,metal ion binding,C.elegans
39779,Y75B8A.10,Gene_MolecularFunction,GO:0046872,Gene,enables,MolecularFunction,Monarch_KG,Generalised,WormBase,Quick_GO,RING-type domain-containing protein,metal ion binding,C.elegans
39780,Y75B8A.11,Gene_MolecularFunction,GO:0071855,Gene,enables,MolecularFunction,Monarch_KG,Generalised,WormBase,Quick_GO,LURY-1-2,neuropeptide receptor binding,C.elegans

# Sanity Check — Distinct Values

In [9]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_MolecularFunction'}
head_type           : {'Gene'}
tail_type           : {'MolecularFunction'}
relation_type       : {'contributes_to', 'enables'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'WormBase'}
tail_id_is          : {'Quick_GO'}

In [10]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 39,781 remaining

# NaN Audit (pre-dedup)

In [11]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                     63                  63             126
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name         63                  63             126
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [12]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 39,781  |  After dedup: 27,235

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,2RSSE.1,Gene_MolecularFunction,GO:0005096,Gene,enables,MolecularFunction,Monarch_KG,Generalised,WormBase,Quick_GO,Rho-GAP domain-containing protein,GTPase activator activity,C.elegans
1,3R5.1,Gene_MolecularFunction,GO:0003677,Gene,enables,MolecularFunction,Monarch_KG,Generalised,WormBase,Quick_GO,Protection of telomeres protein 1 ssDNA-bindin...,DNA binding,C.elegans
2,3R5.1,Gene_MolecularFunction,GO:0043047,Gene,enables,MolecularFunction,Monarch_KG,Generalised,WormBase,Quick_GO,Protection of telomeres protein 1 ssDNA-bindin...,single-stranded telomeric DNA binding,C.elegans

In [13]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    27235
Name: count, dtype: int64

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    27235
Name: count, dtype: int64

In [16]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 27,235 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_gene_MolecularFunction/Celegans_gene_MolecularFunction.csv

In [17]:
#