In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

In [3]:
# phenotype → CellularComponent
# Monarch/Monarch_final/Celegans/Cele_Phenotype_CellularComponent.csv

In [4]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Celegans_phenotype_CellularComponent
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_phenotype_CellularComponent/Celegans_phenotype_CellularComponent.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Celegans_phenotype_CellularComponent’: File exists

In [5]:
# cele = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Caenorhabditis_elegans.gene_info',
#     sep='\t',
    
# )
# cele["LocusTag"] = cele["LocusTag"].str.replace("CELE_", "", regex=False)

# cele_symbol2Locus_dict = dict(zip(cele['Symbol'], cele['LocusTag']))
# cele
# # cele_symbol2Locus_dict

# Monarch

In [6]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Celegans/Cele_Phenotype_CellularComponent.csv')
monarch.columns = monarch.columns.str.lower()
monarch['kg_type'] = 'Generalised'
monarch['species'] = 'C.elegans'

monarch['kg_source'] = 'Monarch_KG'


print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 76 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,species,kg_type,kg_source
0,WBPhenotype:0000103,Phenotype_CellularComponent,GO:0044840,Phenotype,related_to,CellularComponent,infores:upheno,gut granule development variant,gut granule,Caenorhabditis elegans,NaN,WormBasePhenotype,Quick_GO,C.elegans,Generalised,Monarch_KG
1,WBPhenotype:0000161,Phenotype_CellularComponent,GO:0005634,Phenotype,related_to,CellularComponent,infores:upheno,nuclear rotation variant,nucleus,Caenorhabditis elegans,NaN,WormBasePhenotype,Quick_GO,C.elegans,Generalised,Monarch_KG
2,WBPhenotype:0000180,Phenotype_CellularComponent,GO:0030424,Phenotype,related_to,CellularComponent,infores:upheno,axon morphology variant,axon,Caenorhabditis elegans,NaN,WormBasePhenotype,Quick_GO,C.elegans,Generalised,Monarch_KG
3,WBPhenotype:0000181,Phenotype_CellularComponent,GO:0030424,Phenotype,related_to,CellularComponent,infores:upheno,axon trajectory variant,axon,Caenorhabditis elegans,NaN,WormBasePhenotype,Quick_GO,C.elegans,Generalised,Monarch_KG
4,WBPhenotype:0000200,Phenotype_CellularComponent,GO:0031012,Phenotype,related_to,CellularComponent,infores:upheno,pericellular component development variant,extracellular matrix,Caenorhabditis elegans,NaN,WormBasePhenotype,Quick_GO,C.elegans,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,WBPhenotype:0002519,Phenotype_CellularComponent,GO:0030424,Phenotype,related_to,CellularComponent,infores:upheno,axon length reduced,axon,Caenorhabditis elegans,NaN,WormBasePhenotype,Quick_GO,C.elegans,Generalised,Monarch_KG
72,WBPhenotype:0002591,Phenotype_CellularComponent,GO:0030425,Phenotype,related_to,CellularComponent,infores:upheno,dendrite length reduced,dendrite,Caenorhabditis elegans,NaN,WormBasePhenotype,Quick_GO,C.elegans,Generalised,Monarch_KG
73,WBPhenotype:0002617,Phenotype_CellularComponent,GO:0005829,Phenotype,related_to,CellularComponent,infores:upheno,cytosolic calcium levels increased,cytosol,Caenorhabditis elegans,NaN,WormBasePhenotype,Quick_GO,C.elegans,Generalised,Monarch_KG
74,WBPhenotype:0002618,Phenotype_CellularComponent,GO:0005829,Phenotype,related_to,CellularComponent,infores:upheno,cytosolic calcium levels decreased,cytosol,Caenorhabditis elegans,NaN,WormBasePhenotype,Quick_GO,C.elegans,Generalised,Monarch_KG
75,WBPhenotype:0002647,Phenotype_CellularComponent,GO:0030425,Phenotype,related_to,CellularComponent,infores:upheno,dendrite morphology variant,dendrite,Caenorhabditis elegans,NaN,WormBasePhenotype,Quick_GO,C.elegans,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [7]:
# List all source DataFrames to include
source_dfs = [
     monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 76

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,WBPhenotype:0000103,Phenotype_CellularComponent,GO:0044840,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,WormBasePhenotype,Quick_GO,gut granule development variant,gut granule,C.elegans
1,WBPhenotype:0000161,Phenotype_CellularComponent,GO:0005634,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,WormBasePhenotype,Quick_GO,nuclear rotation variant,nucleus,C.elegans
2,WBPhenotype:0000180,Phenotype_CellularComponent,GO:0030424,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,WormBasePhenotype,Quick_GO,axon morphology variant,axon,C.elegans
3,WBPhenotype:0000181,Phenotype_CellularComponent,GO:0030424,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,WormBasePhenotype,Quick_GO,axon trajectory variant,axon,C.elegans
4,WBPhenotype:0000200,Phenotype_CellularComponent,GO:0031012,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,WormBasePhenotype,Quick_GO,pericellular component development variant,extracellular matrix,C.elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,WBPhenotype:0002519,Phenotype_CellularComponent,GO:0030424,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,WormBasePhenotype,Quick_GO,axon length reduced,axon,C.elegans
72,WBPhenotype:0002591,Phenotype_CellularComponent,GO:0030425,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,WormBasePhenotype,Quick_GO,dendrite length reduced,dendrite,C.elegans
73,WBPhenotype:0002617,Phenotype_CellularComponent,GO:0005829,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,WormBasePhenotype,Quick_GO,cytosolic calcium levels increased,cytosol,C.elegans
74,WBPhenotype:0002618,Phenotype_CellularComponent,GO:0005829,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,WormBasePhenotype,Quick_GO,cytosolic calcium levels decreased,cytosol,C.elegans
75,WBPhenotype:0002647,Phenotype_CellularComponent,GO:0030425,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,WormBasePhenotype,Quick_GO,dendrite morphology variant,dendrite,C.elegans

# Sanity Check — Distinct Values

In [8]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Phenotype_CellularComponent'}
head_type           : {'Phenotype'}
tail_type           : {'CellularComponent'}
relation_type       : {'related_to'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'WormBasePhenotype'}
tail_id_is          : {'Quick_GO'}

In [9]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 76 remaining

# NaN Audit (pre-dedup)

In [10]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [11]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 76  |  After dedup: 76

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,WBPhenotype:0000103,Phenotype_CellularComponent,GO:0044840,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,WormBasePhenotype,Quick_GO,gut granule development variant,gut granule,C.elegans
1,WBPhenotype:0000161,Phenotype_CellularComponent,GO:0005634,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,WormBasePhenotype,Quick_GO,nuclear rotation variant,nucleus,C.elegans
2,WBPhenotype:0000180,Phenotype_CellularComponent,GO:0030424,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,WormBasePhenotype,Quick_GO,axon morphology variant,axon,C.elegans

In [12]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    76
Name: count, dtype: int64

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    76
Name: count, dtype: int64

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 76 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_phenotype_CellularComponent/Celegans_phenotype_CellularComponent.csv

In [16]:
#