In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Celegans_chemical_protein
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_chemical_protein/Celegans_chemical_protein.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Celegans_chemical_protein’: File exists

# BindingDB

In [4]:
bindingDB = pd.read_csv(PROC_DIR + 'bindingdb/Chemical_Protein_Cele_BindingDB.csv')
bindingDB.columns = bindingDB.columns.str.lower()
bindingDB['kg_type'] = 'Generalised'
bindingDB['species'] = 'C.elegans'

# print(f"bindingDB: {len(bindingDB):,} rows")
bindingDB

,head,relation,tail,head_type,tail_type,kg_source,species,head_detail_name,head_smile_name,tail_detail_name,head_id_is,tail_id_is,kg_type
0,2408764,ChemicalEntity_Protein,P06582,ChemicalEntity,Protein,BindingDB,C.elegans,"2-[4-(1,3-benzothiazol-2-ylsulfanylmethyl)phen...",C1=CC=C2C(=C1)N=C(S2)SCC3=CC=C(C=C3)C4=NN=CO4,Heat shock protein hsp-16.2 {ECO:0000305},Pubchem,Uniprot_ID,Generalised
1,2168035,ChemicalEntity_Protein,P06582,ChemicalEntity,Protein,BindingDB,C.elegans,"N-[4-(5-chlorothiophen-2-yl)-1,3-thiazol-2-yl]...",C1=CSC(=C1)C(=O)NC2=NC(=CS2)C3=CC=C(S3)Cl,Heat shock protein hsp-16.2 {ECO:0000305},Pubchem,Uniprot_ID,Generalised
2,746912,ChemicalEntity_Protein,P06582,ChemicalEntity,Protein,BindingDB,C.elegans,"4-methoxy-N-(4-thiophen-2-yl-1,3-thiazol-2-yl)...",COC1=CC=C(C=C1)C(=O)NC2=NC(=CS2)C3=CC=CS3,Heat shock protein hsp-16.2 {ECO:0000305},Pubchem,Uniprot_ID,Generalised
3,5343237,ChemicalEntity_Protein,P34707,ChemicalEntity,Protein,BindingDB,C.elegans,[(Z)-[amino(pyridin-3-yl)methylidene]amino] 3-...,C1=CC(=CC(=C1)Cl)C(=O)O/N=C(/C2=CN=CC=C2)\N,Protein skinhead-1,Pubchem,Uniprot_ID,Generalised
4,646210,ChemicalEntity_Protein,P34707,ChemicalEntity,Protein,BindingDB,C.elegans,"2-benzylsulfanyl-5-thiophen-2-yl-1,3,4-oxadiazole",C1=CC=C(C=C1)CSC2=NN=C(O2)C3=CC=CS3,Protein skinhead-1,Pubchem,Uniprot_ID,Generalised
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,49795158,ChemicalEntity_Protein,P34707,ChemicalEntity,Protein,BindingDB,C.elegans,methyl 3-[[3-methyl-2-oxo-5-(trifluoromethoxy)...,CC1(C2=C(C=CC(=C2)OC(F)(F)F)NC1=O)CC3=CC(=CC=C...,Protein skinhead-1,Pubchem,Uniprot_ID,Generalised
295,51360602,ChemicalEntity_Protein,P34707,ChemicalEntity,Protein,BindingDB,C.elegans,6-bromo-2-(4-methylphenyl)-3-[[2-(trifluoromet...,CC1=CC=C(C=C1)C2=C(N3C=C(C=CC3=N2)Br)CC4=CC=CC...,Protein skinhead-1,Pubchem,Uniprot_ID,Generalised
296,51361065,ChemicalEntity_Protein,P34707,ChemicalEntity,Protein,BindingDB,C.elegans,6-chloro-8-fluoro-2-phenylquinoline,C1=CC=C(C=C1)C2=NC3=C(C=C(C=C3C=C2)Cl)F,Protein skinhead-1,Pubchem,Uniprot_ID,Generalised
297,51361255,ChemicalEntity_Protein,P34707,ChemicalEntity,Protein,BindingDB,C.elegans,6-chloro-2-(4-fluorophenyl)-3-(thiophen-3-ylme...,C1=CC(=CC=C1C2=C(N3C=C(C=CC3=N2)Cl)CC4=CSC=C4)F,Protein skinhead-1,Pubchem,Uniprot_ID,Generalised
298,51361280,ChemicalEntity_Protein,P34707,ChemicalEntity,Protein,BindingDB,C.elegans,6-bromo-2-(3-chlorophenyl)-3-(thiophen-3-ylmet...,C1=CC(=CC(=C1)Cl)C2=C(N3C=C(C=CC3=N2)Br)CC4=CS...,Protein skinhead-1,Pubchem,Uniprot_ID,Generalised

In [5]:
#

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
    bindingDB
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 299

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,2408764,ChemicalEntity_Protein,P06582,ChemicalEntity,None,Protein,BindingDB,Generalised,Pubchem,Uniprot_ID,"2-[4-(1,3-benzothiazol-2-ylsulfanylmethyl)phen...",Heat shock protein hsp-16.2 {ECO:0000305},C.elegans
1,2168035,ChemicalEntity_Protein,P06582,ChemicalEntity,None,Protein,BindingDB,Generalised,Pubchem,Uniprot_ID,"N-[4-(5-chlorothiophen-2-yl)-1,3-thiazol-2-yl]...",Heat shock protein hsp-16.2 {ECO:0000305},C.elegans
2,746912,ChemicalEntity_Protein,P06582,ChemicalEntity,None,Protein,BindingDB,Generalised,Pubchem,Uniprot_ID,"4-methoxy-N-(4-thiophen-2-yl-1,3-thiazol-2-yl)...",Heat shock protein hsp-16.2 {ECO:0000305},C.elegans
3,5343237,ChemicalEntity_Protein,P34707,ChemicalEntity,None,Protein,BindingDB,Generalised,Pubchem,Uniprot_ID,[(Z)-[amino(pyridin-3-yl)methylidene]amino] 3-...,Protein skinhead-1,C.elegans
4,646210,ChemicalEntity_Protein,P34707,ChemicalEntity,None,Protein,BindingDB,Generalised,Pubchem,Uniprot_ID,"2-benzylsulfanyl-5-thiophen-2-yl-1,3,4-oxadiazole",Protein skinhead-1,C.elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,49795158,ChemicalEntity_Protein,P34707,ChemicalEntity,None,Protein,BindingDB,Generalised,Pubchem,Uniprot_ID,methyl 3-[[3-methyl-2-oxo-5-(trifluoromethoxy)...,Protein skinhead-1,C.elegans
295,51360602,ChemicalEntity_Protein,P34707,ChemicalEntity,None,Protein,BindingDB,Generalised,Pubchem,Uniprot_ID,6-bromo-2-(4-methylphenyl)-3-[[2-(trifluoromet...,Protein skinhead-1,C.elegans
296,51361065,ChemicalEntity_Protein,P34707,ChemicalEntity,None,Protein,BindingDB,Generalised,Pubchem,Uniprot_ID,6-chloro-8-fluoro-2-phenylquinoline,Protein skinhead-1,C.elegans
297,51361255,ChemicalEntity_Protein,P34707,ChemicalEntity,None,Protein,BindingDB,Generalised,Pubchem,Uniprot_ID,6-chloro-2-(4-fluorophenyl)-3-(thiophen-3-ylme...,Protein skinhead-1,C.elegans
298,51361280,ChemicalEntity_Protein,P34707,ChemicalEntity,None,Protein,BindingDB,Generalised,Pubchem,Uniprot_ID,6-bromo-2-(3-chlorophenyl)-3-(thiophen-3-ylmet...,Protein skinhead-1,C.elegans

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'ChemicalEntity_Protein'}
head_type           : {'ChemicalEntity'}
tail_type           : {'Protein'}
relation_type       : {None}
kg_source           : {'BindingDB'}
head_id_is          : {'Pubchem'}
tail_id_is          : {'Uniprot_ID'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 299 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           299                   0             299
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 299  |  After dedup: 299

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,3197,ChemicalEntity_Protein,P34707,ChemicalEntity,None,Protein,BindingDB,Generalised,Pubchem,Uniprot_ID,"N-[2,4,12,15,17,25-hexamethyl-27-methylsulfany...",Protein skinhead-1,C.elegans
1,11293,ChemicalEntity_Protein,P06582,ChemicalEntity,None,Protein,BindingDB,Generalised,Pubchem,Uniprot_ID,"4-[(4-aminophenyl)-(4-iminocyclohexa-2,5-dien-...",Heat shock protein hsp-16.2 {ECO:0000305},C.elegans
2,13271,ChemicalEntity_Protein,P06582,ChemicalEntity,None,Protein,BindingDB,Generalised,Pubchem,Uniprot_ID,4-nitro-N-phenylaniline,Heat shock protein hsp-16.2 {ECO:0000305},C.elegans

In [11]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           299                   0             299
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'BindingDB'} kg_source
BindingDB    299
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    299
Name: count, dtype: int64

In [14]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 299 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_chemical_protein/Celegans_chemical_protein.csv

In [15]:
OUT_PATH

'/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_chemical_protein/Celegans_chemical_protein.csv'

In [16]:
#