In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Celegans_gene_pathway
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_gene_pathway/Celegans_gene_pathway.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

# Monarch

In [4]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Celegans/Cele_Gene_Pathway.csv')
monarch.columns = monarch.columns.str.lower()
monarch['kg_type'] = 'Generalised'
monarch['species'] = 'C.elegans'

monarch['kg_source'] = 'Monarch_KG'


print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 12,698 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,K03H1.13,Gene_Pathway,R-HSA-6787639,Gene,participates_in,Pathway,infores:reactome,L-fucokinase domain-containing protein,GDP-fucose biosynthesis,Caenorhabditis elegans,Homo sapiens,WormBase,Reactome,K03H1.13,C.elegans,Generalised,Monarch_KG
1,W01A8.8,Gene_Pathway,R-HSA-381426,Gene,participates_in,Pathway,infores:reactome,DUF19 domain-containing protein,Regulation of Insulin-like Growth Factor (IGF)...,Caenorhabditis elegans,Homo sapiens,WormBase,Reactome,W01A8.8,C.elegans,Generalised,Monarch_KG
2,W01A8.8,Gene_Pathway,R-HSA-8957275,Gene,participates_in,Pathway,infores:reactome,DUF19 domain-containing protein,Post-translational protein phosphorylation,Caenorhabditis elegans,Homo sapiens,WormBase,Reactome,W01A8.8,C.elegans,Generalised,Monarch_KG
3,Y37A1B.17,Gene_Pathway,R-HSA-193648,Gene,participates_in,Pathway,infores:reactome,SH3 domain-containing GRB2-like protein;SH3 do...,NRAGE signals death through JNK,Caenorhabditis elegans,Homo sapiens,WormBase,Reactome,dnbp-1,C.elegans,Generalised,Monarch_KG
4,Y37A1B.17,Gene_Pathway,R-HSA-416482,Gene,participates_in,Pathway,infores:reactome,SH3 domain-containing GRB2-like protein;SH3 do...,G alpha (12/13) signalling events,Caenorhabditis elegans,Homo sapiens,WormBase,Reactome,dnbp-1,C.elegans,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12693,Y59A8B.25,Gene_Pathway,R-HSA-6811440,Gene,participates_in,Pathway,infores:reactome,DUF727 domain-containing protein,Retrograde transport at the Trans-Golgi-Network,Caenorhabditis elegans,Homo sapiens,WormBase,Reactome,Y59A8B.25,C.elegans,Generalised,Monarch_KG
12694,ZK863.9,Gene_Pathway,R-HSA-1236978,Gene,participates_in,Pathway,infores:reactome,C-type lectin domain-containing protein,Cross-presentation of soluble exogenous antige...,Caenorhabditis elegans,Homo sapiens,WormBase,Reactome,clec-224,C.elegans,Generalised,Monarch_KG
12695,ZK863.9,Gene_Pathway,R-HSA-446203,Gene,participates_in,Pathway,infores:reactome,C-type lectin domain-containing protein,Asparagine N-linked glycosylation,Caenorhabditis elegans,Homo sapiens,WormBase,Reactome,clec-224,C.elegans,Generalised,Monarch_KG
12696,ZK863.9,Gene_Pathway,R-HSA-5621480,Gene,participates_in,Pathway,infores:reactome,C-type lectin domain-containing protein,Dectin-2 family,Caenorhabditis elegans,Homo sapiens,WormBase,Reactome,clec-224,C.elegans,Generalised,Monarch_KG
12697,ZK863.9,Gene_Pathway,R-HSA-6798695,Gene,participates_in,Pathway,infores:reactome,C-type lectin domain-containing protein,Neutrophil degranulation,Caenorhabditis elegans,Homo sapiens,WormBase,Reactome,clec-224,C.elegans,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [5]:
# List all source DataFrames to include
source_dfs = [
     monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 12,698

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,K03H1.13,Gene_Pathway,R-HSA-6787639,Gene,participates_in,Pathway,Monarch_KG,Generalised,WormBase,Reactome,L-fucokinase domain-containing protein,GDP-fucose biosynthesis,C.elegans
1,W01A8.8,Gene_Pathway,R-HSA-381426,Gene,participates_in,Pathway,Monarch_KG,Generalised,WormBase,Reactome,DUF19 domain-containing protein,Regulation of Insulin-like Growth Factor (IGF)...,C.elegans
2,W01A8.8,Gene_Pathway,R-HSA-8957275,Gene,participates_in,Pathway,Monarch_KG,Generalised,WormBase,Reactome,DUF19 domain-containing protein,Post-translational protein phosphorylation,C.elegans
3,Y37A1B.17,Gene_Pathway,R-HSA-193648,Gene,participates_in,Pathway,Monarch_KG,Generalised,WormBase,Reactome,SH3 domain-containing GRB2-like protein;SH3 do...,NRAGE signals death through JNK,C.elegans
4,Y37A1B.17,Gene_Pathway,R-HSA-416482,Gene,participates_in,Pathway,Monarch_KG,Generalised,WormBase,Reactome,SH3 domain-containing GRB2-like protein;SH3 do...,G alpha (12/13) signalling events,C.elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12693,Y59A8B.25,Gene_Pathway,R-HSA-6811440,Gene,participates_in,Pathway,Monarch_KG,Generalised,WormBase,Reactome,DUF727 domain-containing protein,Retrograde transport at the Trans-Golgi-Network,C.elegans
12694,ZK863.9,Gene_Pathway,R-HSA-1236978,Gene,participates_in,Pathway,Monarch_KG,Generalised,WormBase,Reactome,C-type lectin domain-containing protein,Cross-presentation of soluble exogenous antige...,C.elegans
12695,ZK863.9,Gene_Pathway,R-HSA-446203,Gene,participates_in,Pathway,Monarch_KG,Generalised,WormBase,Reactome,C-type lectin domain-containing protein,Asparagine N-linked glycosylation,C.elegans
12696,ZK863.9,Gene_Pathway,R-HSA-5621480,Gene,participates_in,Pathway,Monarch_KG,Generalised,WormBase,Reactome,C-type lectin domain-containing protein,Dectin-2 family,C.elegans
12697,ZK863.9,Gene_Pathway,R-HSA-6798695,Gene,participates_in,Pathway,Monarch_KG,Generalised,WormBase,Reactome,C-type lectin domain-containing protein,Neutrophil degranulation,C.elegans

# Sanity Check — Distinct Values

In [6]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_Pathway'}
head_type           : {'Gene'}
tail_type           : {'Pathway'}
relation_type       : {'participates_in'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'WormBase'}
tail_id_is          : {'Reactome'}

In [7]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 12,698 remaining

# NaN Audit (pre-dedup)

In [8]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [9]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 12,698  |  After dedup: 12,698

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,2RSSE.1,Gene_Pathway,R-HSA-8980692,Gene,participates_in,Pathway,Monarch_KG,Generalised,WormBase,Reactome,Rho-GAP domain-containing protein,RHOA GTPase cycle,C.elegans
1,2RSSE.1,Gene_Pathway,R-HSA-9013148,Gene,participates_in,Pathway,Monarch_KG,Generalised,WormBase,Reactome,Rho-GAP domain-containing protein,CDC42 GTPase cycle,C.elegans
2,2RSSE.1,Gene_Pathway,R-HSA-9013149,Gene,participates_in,Pathway,Monarch_KG,Generalised,WormBase,Reactome,Rho-GAP domain-containing protein,RAC1 GTPase cycle,C.elegans

In [10]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [11]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    12698
Name: count, dtype: int64

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    12698
Name: count, dtype: int64

In [13]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 12,698 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_gene_pathway/Celegans_gene_pathway.csv

In [14]:
#