In [16]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [17]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

# Databases Having Gene Phenotype relation of celegans

In [18]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Celegans_protein_tissue
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_protein_tissue/Celegans_protein_tissue.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Celegans_protein_tissue’: File exists

In [19]:
# cele = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Caenorhabditis_elegans.gene_info',
#     sep='\t',
    
# )
# cele["LocusTag"] = cele["LocusTag"].str.replace("CELE_", "", regex=False)

# cele_symbol2Locus_dict = dict(zip(cele['Symbol'], cele['LocusTag']))
# cele
# # cele_symbol2Locus_dict

# AgeAnnOMO

In [20]:
AgeAnnoMO = pd.read_csv(PROC_DIR + 'ageanno_processed_mo/AgeAnnoMO_Celegans_Protein_Tissue.csv')
AgeAnnoMO.columns = AgeAnnoMO.columns.str.lower()
AgeAnnoMO['kg_type'] = 'Aging'
AgeAnnoMO['relation'] = 'Protein_Tissue'

AgeAnnoMO['species'] = 'Caenorhabditis elegans'
AgeAnnoMO['kg_source'] = 'AgeAnnoMO'

print(f"AgeAnnoMO: {len(AgeAnnoMO):,} rows")
AgeAnnoMO

AgeAnnoMO: 778 rows

,head,relation,tail,head_type,tail_type,head_id_is,tail_id_is,relation_source,species,tail_detail_name,head_detail_name,kg_type,kg_source
0,A3QM97,Protein_Tissue,BTO:0001489,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Caenorhabditis elegans,whole body,Metal transporter cnnm-1 {ECO:0000305},Aging,AgeAnnoMO
1,A3QMD7,Protein_Tissue,BTO:0001489,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Caenorhabditis elegans,whole body,ING family member lsy-13 {ECO:0000303|PubMed:2...,Aging,AgeAnnoMO
2,A7LPI2,Protein_Tissue,BTO:0001489,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Caenorhabditis elegans,whole body,Liprin-beta homolog {ECO:0000312|WormBase:T21H...,Aging,AgeAnnoMO
3,A8WHT1,Protein_Tissue,BTO:0001489,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Caenorhabditis elegans,whole body,tRNA (guanine(37)-N1)-methyltransferase {ECO:0...,Aging,AgeAnnoMO
4,B2D6K7,Protein_Tissue,BTO:0001489,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Caenorhabditis elegans,whole body,Ataxin-2 homolog {ECO:0000305},Aging,AgeAnnoMO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
773,Q9XWS0,Protein_Tissue,BTO:0001489,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Caenorhabditis elegans,whole body,Spindle and kinetochore-associated protein 1 {...,Aging,AgeAnnoMO
774,Q9XXN3,Protein_Tissue,BTO:0001489,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Caenorhabditis elegans,whole body,Nuclear envelope phosphatase-regulatory subuni...,Aging,AgeAnnoMO
775,Q9Y0V2,Protein_Tissue,BTO:0001489,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Caenorhabditis elegans,whole body,Mitochondrial import inner membrane translocas...,Aging,AgeAnnoMO
776,Q9Y0V6,Protein_Tissue,BTO:0001489,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Caenorhabditis elegans,whole body,Mitochondrial import inner membrane translocas...,Aging,AgeAnnoMO
777,Q9Y194,Protein_Tissue,BTO:0001489,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Caenorhabditis elegans,whole body,Sphingosine-1-phosphate lyase,Aging,AgeAnnoMO

In [21]:
#

# Consolidate into Unified Schem

In [22]:
# List all source DataFrames to include
source_dfs = [
    AgeAnnoMO
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 778

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,A3QM97,Protein_Tissue,BTO:0001489,Protein,None,Tissue,AgeAnnoMO,Aging,Uniprot,BTO_ID,Metal transporter cnnm-1 {ECO:0000305},whole body,Caenorhabditis elegans
1,A3QMD7,Protein_Tissue,BTO:0001489,Protein,None,Tissue,AgeAnnoMO,Aging,Uniprot,BTO_ID,ING family member lsy-13 {ECO:0000303|PubMed:2...,whole body,Caenorhabditis elegans
2,A7LPI2,Protein_Tissue,BTO:0001489,Protein,None,Tissue,AgeAnnoMO,Aging,Uniprot,BTO_ID,Liprin-beta homolog {ECO:0000312|WormBase:T21H...,whole body,Caenorhabditis elegans
3,A8WHT1,Protein_Tissue,BTO:0001489,Protein,None,Tissue,AgeAnnoMO,Aging,Uniprot,BTO_ID,tRNA (guanine(37)-N1)-methyltransferase {ECO:0...,whole body,Caenorhabditis elegans
4,B2D6K7,Protein_Tissue,BTO:0001489,Protein,None,Tissue,AgeAnnoMO,Aging,Uniprot,BTO_ID,Ataxin-2 homolog {ECO:0000305},whole body,Caenorhabditis elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
773,Q9XWS0,Protein_Tissue,BTO:0001489,Protein,None,Tissue,AgeAnnoMO,Aging,Uniprot,BTO_ID,Spindle and kinetochore-associated protein 1 {...,whole body,Caenorhabditis elegans
774,Q9XXN3,Protein_Tissue,BTO:0001489,Protein,None,Tissue,AgeAnnoMO,Aging,Uniprot,BTO_ID,Nuclear envelope phosphatase-regulatory subuni...,whole body,Caenorhabditis elegans
775,Q9Y0V2,Protein_Tissue,BTO:0001489,Protein,None,Tissue,AgeAnnoMO,Aging,Uniprot,BTO_ID,Mitochondrial import inner membrane translocas...,whole body,Caenorhabditis elegans
776,Q9Y0V6,Protein_Tissue,BTO:0001489,Protein,None,Tissue,AgeAnnoMO,Aging,Uniprot,BTO_ID,Mitochondrial import inner membrane translocas...,whole body,Caenorhabditis elegans
777,Q9Y194,Protein_Tissue,BTO:0001489,Protein,None,Tissue,AgeAnnoMO,Aging,Uniprot,BTO_ID,Sphingosine-1-phosphate lyase,whole body,Caenorhabditis elegans

# Sanity Check — Distinct Values

In [23]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Protein_Tissue'}
head_type           : {'Protein'}
tail_type           : {'Tissue'}
relation_type       : {None}
kg_source           : {'AgeAnnoMO'}
head_id_is          : {'Uniprot'}
tail_id_is          : {'BTO_ID'}

In [24]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 778 remaining

# NaN Audit (pre-dedup)

In [25]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           778                   0             778
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [26]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 778  |  After dedup: 778

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,A3QM97,Protein_Tissue,BTO:0001489,Protein,None,Tissue,AgeAnnoMO,Aging,Uniprot,BTO_ID,Metal transporter cnnm-1 {ECO:0000305},whole body,Caenorhabditis elegans
1,A3QMD7,Protein_Tissue,BTO:0001489,Protein,None,Tissue,AgeAnnoMO,Aging,Uniprot,BTO_ID,ING family member lsy-13 {ECO:0000303|PubMed:2...,whole body,Caenorhabditis elegans
2,A7LPI2,Protein_Tissue,BTO:0001489,Protein,None,Tissue,AgeAnnoMO,Aging,Uniprot,BTO_ID,Liprin-beta homolog {ECO:0000312|WormBase:T21H...,whole body,Caenorhabditis elegans

In [27]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           778                   0             778
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [28]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'AgeAnnoMO'} kg_source
AgeAnnoMO    778
Name: count, dtype: int64

In [29]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    778
Name: count, dtype: int64

In [30]:
! mkdir Celegans_protein_tissue

mkdir: cannot create directory ‘Celegans_protein_tissue’: File exists

In [31]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 778 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_protein_tissue/Celegans_protein_tissue.csv

In [17]:
#