In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

In [3]:
# Gene → Anatomy
# Monarch/Monarch_final/Celegans/Gene_Cele_Anatomy.csv

In [4]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Celegans_gene_Anatomy
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_gene_Anatomy/Celegans_gene_Anatomy.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Celegans_gene_Anatomy’: File exists

In [5]:
!ls /storage/Arushi/090526_EvoAge/kg_formation/processed_data/Monarch/Monarch_final/Celegans/

Cele_AnatomicalEntity_AnatomicalEntity.csv    Gene_Cele_Anatomy.csv
Cele_Gene_Pathway.csv			      Gene_Cele_BiologicalProcess.csv
Cele_Phenotype_CellularComponent.csv	      Gene_Cele_CellularComponent.csv
Cele_Phenotype_ChemicalEntity.csv	      Gene_Cele_MolecularFunction.csv
Cele_PhenotypicFeature_BiologicalProcess.csv  Gene_Cele_Phenotype.csv
Cele_PhenotypicFeature_MolecularFunction.csv  GENE_GENE_Cele_Cele.csv

# Monarch

In [6]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Celegans/Gene_Cele_Anatomy.csv')
monarch.columns = monarch.columns.str.lower()
monarch['kg_type'] = 'Generalised'
monarch['species'] = 'C.elegans'
monarch['relation'] = 'Gene_AnatomicalEntity'
monarch['tail_type'] = 'AnatomicalEntity'

monarch['kg_source'] = 'Monarch_KG'


print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 105,006 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,infores:wormbase,RING-box protein 1,C. elegans anatomical entity,Caenorhabditis elegans,NaN,WormBase,WormBaseAnatomy,rbx-1,C.elegans,Generalised,Monarch_KG
1,ZK287.5,Gene_AnatomicalEntity,WBbt:0005784,Gene,expressed_in,AnatomicalEntity,infores:wormbase,RING-box protein 1,germ line,Caenorhabditis elegans,NaN,WormBase,WormBaseAnatomy,rbx-1,C.elegans,Generalised,Monarch_KG
2,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,infores:wormbase,RING-box protein 1,C. elegans anatomical entity,Caenorhabditis elegans,NaN,WormBase,WormBaseAnatomy,rbx-1,C.elegans,Generalised,Monarch_KG
3,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,infores:wormbase,RING-box protein 1,C. elegans anatomical entity,Caenorhabditis elegans,NaN,WormBase,WormBaseAnatomy,rbx-1,C.elegans,Generalised,Monarch_KG
4,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,infores:wormbase,RING-box protein 1,C. elegans anatomical entity,Caenorhabditis elegans,NaN,WormBase,WormBaseAnatomy,rbx-1,C.elegans,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105001,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,infores:wormbase,RING-box protein 1,C. elegans anatomical entity,Caenorhabditis elegans,NaN,WormBase,WormBaseAnatomy,rbx-1,C.elegans,Generalised,Monarch_KG
105002,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,infores:wormbase,RING-box protein 1,C. elegans anatomical entity,Caenorhabditis elegans,NaN,WormBase,WormBaseAnatomy,rbx-1,C.elegans,Generalised,Monarch_KG
105003,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,infores:wormbase,RING-box protein 1,C. elegans anatomical entity,Caenorhabditis elegans,NaN,WormBase,WormBaseAnatomy,rbx-1,C.elegans,Generalised,Monarch_KG
105004,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,infores:wormbase,RING-box protein 1,C. elegans anatomical entity,Caenorhabditis elegans,NaN,WormBase,WormBaseAnatomy,rbx-1,C.elegans,Generalised,Monarch_KG
105005,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,infores:wormbase,RING-box protein 1,C. elegans anatomical entity,Caenorhabditis elegans,NaN,WormBase,WormBaseAnatomy,rbx-1,C.elegans,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [7]:
# List all source DataFrames to include
source_dfs = [
     monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 105,006

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBaseAnatomy,RING-box protein 1,C. elegans anatomical entity,C.elegans
1,ZK287.5,Gene_AnatomicalEntity,WBbt:0005784,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBaseAnatomy,RING-box protein 1,germ line,C.elegans
2,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBaseAnatomy,RING-box protein 1,C. elegans anatomical entity,C.elegans
3,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBaseAnatomy,RING-box protein 1,C. elegans anatomical entity,C.elegans
4,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBaseAnatomy,RING-box protein 1,C. elegans anatomical entity,C.elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
105001,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBaseAnatomy,RING-box protein 1,C. elegans anatomical entity,C.elegans
105002,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBaseAnatomy,RING-box protein 1,C. elegans anatomical entity,C.elegans
105003,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBaseAnatomy,RING-box protein 1,C. elegans anatomical entity,C.elegans
105004,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBaseAnatomy,RING-box protein 1,C. elegans anatomical entity,C.elegans
105005,ZK287.5,Gene_AnatomicalEntity,WBbt:0000100,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBaseAnatomy,RING-box protein 1,C. elegans anatomical entity,C.elegans

# Sanity Check — Distinct Values

In [8]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_AnatomicalEntity'}
head_type           : {'Gene'}
tail_type           : {'AnatomicalEntity'}
relation_type       : {'expressed_in'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'WormBase'}
tail_id_is          : {'WormBaseAnatomy'}

In [9]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 105,006 remaining

# NaN Audit (pre-dedup)

In [10]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                    505                 505            1010
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name        505                 505            1010
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [11]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 105,006  |  After dedup: 65,039

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,4R79.1,Gene_AnatomicalEntity,WBbt:0003708,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBaseAnatomy,Metalloendopeptidase;Zinc metalloproteinase nas-6,mc2,C.elegans
1,4R79.1,Gene_AnatomicalEntity,WBbt:0003724,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBaseAnatomy,Metalloendopeptidase;Zinc metalloproteinase nas-6,pm6,C.elegans
2,4R79.1,Gene_AnatomicalEntity,WBbt:0003742,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,WormBase,WormBaseAnatomy,Metalloendopeptidase;Zinc metalloproteinase nas-6,pm2,C.elegans

In [12]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    65039
Name: count, dtype: int64

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    65039
Name: count, dtype: int64

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 65,039 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_gene_Anatomy/Celegans_gene_Anatomy.csv

In [16]:
#