In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

In [3]:
# Gene → CellularComponent
# Monarch/Monarch_final/Celegans/Gene_Cele_CellularComponent.csv

In [4]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Celegans_gene_CellularComponent
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_gene_CellularComponent/Celegans_gene_CellularComponent.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Celegans_gene_CellularComponent’: File exists

In [5]:
# cele = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Caenorhabditis_elegans.gene_info',
#     sep='\t',
    
# )
# cele["LocusTag"] = cele["LocusTag"].str.replace("CELE_", "", regex=False)

# cele_symbol2Locus_dict = dict(zip(cele['Symbol'], cele['LocusTag']))
# cele
# # cele_symbol2Locus_dict

# Monarch

In [6]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Celegans/Gene_Cele_CellularComponent.csv')
monarch.columns = monarch.columns.str.lower()
monarch['kg_type'] = 'Generalised'
monarch['species'] = 'C.elegans'

monarch['kg_source'] = 'Monarch_KG'


print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 40,938 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,Y75B8A.16,Gene_CellularComponent,GO:0016020,Gene,located_in,CellularComponent,infores:interpro,Golgi pH regulator,membrane,Caenorhabditis elegans,NaN,WormBase,Quick_GO,gphr-1,C.elegans,Generalised,Monarch_KG
1,Y75B8A.16,Gene_CellularComponent,GO:0016020,Gene,located_in,CellularComponent,infores:uniprot,Golgi pH regulator,membrane,Caenorhabditis elegans,NaN,WormBase,Quick_GO,gphr-1,C.elegans,Generalised,Monarch_KG
2,Y75B8A.16,Gene_CellularComponent,GO:0016020,Gene,located_in,CellularComponent,infores:uniprot,Golgi pH regulator,membrane,Caenorhabditis elegans,NaN,WormBase,Quick_GO,gphr-1,C.elegans,Generalised,Monarch_KG
3,Y75B8A.17,Gene_CellularComponent,GO:0005634,Gene,located_in,CellularComponent,infores:uniprot,Geminin homolog,nucleus,Caenorhabditis elegans,NaN,WormBase,Quick_GO,gmn-1,C.elegans,Generalised,Monarch_KG
4,Y75B8A.17,Gene_CellularComponent,GO:0005634,Gene,located_in,CellularComponent,infores:uniprot,Geminin homolog,nucleus,Caenorhabditis elegans,NaN,WormBase,Quick_GO,gmn-1,C.elegans,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40933,Y75B8A.7,Gene_CellularComponent,GO:0034457,Gene,part_of,CellularComponent,infores:interpro,U3 small nucleolar ribonucleoprotein MPP10,Mpp10 complex,Caenorhabditis elegans,NaN,WormBase,Quick_GO,Y75B8A.7,C.elegans,Generalised,Monarch_KG
40934,Y75B8A.7,Gene_CellularComponent,GO:0034457,Gene,part_of,CellularComponent,infores:uniprot,U3 small nucleolar ribonucleoprotein MPP10,Mpp10 complex,Caenorhabditis elegans,NaN,WormBase,Quick_GO,Y75B8A.7,C.elegans,Generalised,Monarch_KG
40935,Y75B8A.7,Gene_CellularComponent,GO:1990904,Gene,part_of,CellularComponent,infores:uniprot,U3 small nucleolar ribonucleoprotein MPP10,ribonucleoprotein complex,Caenorhabditis elegans,NaN,WormBase,Quick_GO,Y75B8A.7,C.elegans,Generalised,Monarch_KG
40936,Y75B8A.11,Gene_CellularComponent,GO:0005576,Gene,located_in,CellularComponent,infores:uniprot,LURY-1-2,extracellular region,Caenorhabditis elegans,NaN,WormBase,Quick_GO,lury-1,C.elegans,Generalised,Monarch_KG
40937,Y75B8A.11,Gene_CellularComponent,GO:0005576,Gene,located_in,CellularComponent,infores:uniprot,LURY-1-2,extracellular region,Caenorhabditis elegans,NaN,WormBase,Quick_GO,lury-1,C.elegans,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [7]:
# List all source DataFrames to include
source_dfs = [
     monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 40,938

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Y75B8A.16,Gene_CellularComponent,GO:0016020,Gene,located_in,CellularComponent,Monarch_KG,Generalised,WormBase,Quick_GO,Golgi pH regulator,membrane,C.elegans
1,Y75B8A.16,Gene_CellularComponent,GO:0016020,Gene,located_in,CellularComponent,Monarch_KG,Generalised,WormBase,Quick_GO,Golgi pH regulator,membrane,C.elegans
2,Y75B8A.16,Gene_CellularComponent,GO:0016020,Gene,located_in,CellularComponent,Monarch_KG,Generalised,WormBase,Quick_GO,Golgi pH regulator,membrane,C.elegans
3,Y75B8A.17,Gene_CellularComponent,GO:0005634,Gene,located_in,CellularComponent,Monarch_KG,Generalised,WormBase,Quick_GO,Geminin homolog,nucleus,C.elegans
4,Y75B8A.17,Gene_CellularComponent,GO:0005634,Gene,located_in,CellularComponent,Monarch_KG,Generalised,WormBase,Quick_GO,Geminin homolog,nucleus,C.elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40933,Y75B8A.7,Gene_CellularComponent,GO:0034457,Gene,part_of,CellularComponent,Monarch_KG,Generalised,WormBase,Quick_GO,U3 small nucleolar ribonucleoprotein MPP10,Mpp10 complex,C.elegans
40934,Y75B8A.7,Gene_CellularComponent,GO:0034457,Gene,part_of,CellularComponent,Monarch_KG,Generalised,WormBase,Quick_GO,U3 small nucleolar ribonucleoprotein MPP10,Mpp10 complex,C.elegans
40935,Y75B8A.7,Gene_CellularComponent,GO:1990904,Gene,part_of,CellularComponent,Monarch_KG,Generalised,WormBase,Quick_GO,U3 small nucleolar ribonucleoprotein MPP10,ribonucleoprotein complex,C.elegans
40936,Y75B8A.11,Gene_CellularComponent,GO:0005576,Gene,located_in,CellularComponent,Monarch_KG,Generalised,WormBase,Quick_GO,LURY-1-2,extracellular region,C.elegans
40937,Y75B8A.11,Gene_CellularComponent,GO:0005576,Gene,located_in,CellularComponent,Monarch_KG,Generalised,WormBase,Quick_GO,LURY-1-2,extracellular region,C.elegans

# Sanity Check — Distinct Values

In [8]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_CellularComponent'}
head_type           : {'Gene'}
tail_type           : {'CellularComponent'}
relation_type       : {'part_of', 'colocalizes_with', 'located_in', 'is_active_in'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'WormBase'}
tail_id_is          : {'Quick_GO'}

In [9]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 40,938 remaining

# NaN Audit (pre-dedup)

In [10]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                     82                  82             164
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name         82                  82             164
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [11]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 40,938  |  After dedup: 27,064

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,3R5.1,Gene_CellularComponent,GO:0000781,Gene,located_in,CellularComponent,Monarch_KG,Generalised,WormBase,Quick_GO,Protection of telomeres protein 1 ssDNA-bindin...,"chromosome, telomeric region",C.elegans
1,3R5.1,Gene_CellularComponent,GO:0005634,Gene,located_in,CellularComponent,Monarch_KG,Generalised,WormBase,Quick_GO,Protection of telomeres protein 1 ssDNA-bindin...,nucleus,C.elegans
2,4R79.1,Gene_CellularComponent,GO:0005576,Gene,located_in,CellularComponent,Monarch_KG,Generalised,WormBase,Quick_GO,Metalloendopeptidase;Zinc metalloproteinase nas-6,extracellular region,C.elegans

In [12]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    27064
Name: count, dtype: int64

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    27064
Name: count, dtype: int64

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 27,064 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_gene_CellularComponent/Celegans_gene_CellularComponent.csv

In [16]:
#