In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'


# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

# POSITIVE ASSOCIATION

In [4]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Celegans_chemical_positiveassociated_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_chemical_positiveassociated_biologicalprocess/Celegans_chemical_positiveassociated_biologicalprocess.csv'

mkdir: cannot create directory ‘Celegans_chemical_positiveassociated_biologicalprocess’: File exists

### Drugage

In [5]:
Drugage = pd.read_csv(PROC_DIR + 'drugage/drugage_final/Cele_CE_Pos_BioPro_merged.csv')
Drugage.columns = Drugage.columns.str.lower()
Drugage = Drugage[~Drugage['head_detail_name'].isna()]

Drugage['kg_type'] = 'Aging'

print(f"Drugage: {len(Drugage):,} rows")
Drugage['head_id_is'] = 'Pubchem'
Drugage['tail_id_is'] = 'Quick_GO'
Drugage['relation'] = 'ChemicalEntity_PositivelyAssociatedWith_BiologicalProcess'
Drugage['kg_source'] = 'Drugage'
Drugage['tail_detail_name'] = 'aging'
Drugage

Drugage: 360 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,...,age_at_initiation,treatment_duration,avg_lifespan_change_percent,dosage,pubmed_id,kg_type,head_id_is,tail_id_is,kg_source,tail_detail_name
0,14985,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",CC1=C(C2=C(CC[C@@](O2)(C)CCC[C@H](C)CCC[C@H](C...,DrugAge,Caenorhabditis elegans,Vitamin E,...,NaN,NaN,23.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
1,3973,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-morpholin-4-yl-8-phenylchromen-4-one,C1COCCN1C2=CC(=O)C3=C(O2)C(=CC=C3)C4=CC=CC=C4,DrugAge,Caenorhabditis elegans,LY-294002,...,NaN,NaN,25.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
2,9929901,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"2-methyl-2-[(3E,7E)-4,8,12-trimethyltrideca-3,...",CC(=CCC/C(=C/CC/C(=C/CCC1(CCC2=C(O1)C=CC(=C2)O...,DrugAge,Caenorhabditis elegans,Tocotrienol,...,NaN,NaN,19.80,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
3,171249,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,manganese(3+);2-[2-[(2-oxidophenyl)methylidene...,C1=CC=C(C(=C1)C=NCCN=CC2=CC=CC=C2[O-])[O-].[Cl...,DrugAge,Caenorhabditis elegans,EUK-8,...,NaN,NaN,33.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
4,9823233,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,manganese(3+);2-methoxy-6-[2-[(3-methoxy-2-oxi...,COC1=CC=CC(=C1[O-])C=NCCN=CC2=C(C(=CC=C2)OC)[O...,DrugAge,Caenorhabditis elegans,EUK-134,...,NaN,NaN,54.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,5281855,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"6,7,13,14-tetrahydroxy-2,9-dioxatetracyclo[6.6...",C1=C2C3=C(C(=C1O)O)OC(=O)C4=CC(=C(C(=C43)OC2=O...,DrugAge,Caenorhabditis elegans,Ellagic acid,...,NaN,NaN,8.99,50 µM,21805983.0,Aging,Pubchem,Quick_GO,Drugage,aging
358,3830,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,N-(furan-2-ylmethyl)-7H-purin-6-amine,C1=COC(=C1)CNC2=NC=NC3=C2NC=N3,DrugAge,Caenorhabditis elegans,Kinetin,...,NaN,NaN,21.00,200 µM,29255944.0,Aging,Pubchem,Quick_GO,Drugage,aging
359,9964771,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,4-[(7H-purin-6-ylamino)methyl]phenol,C1=CC(=CC=C1CNC2=NC=NC3=C2NC=N3)O,DrugAge,Caenorhabditis elegans,para-topolin,...,NaN,NaN,8.00,100 µM,29255944.0,Aging,Pubchem,Quick_GO,Drugage,aging
360,51,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-oxopentanedioic acid,C(CC(=O)O)C(=O)C(=O)O,DrugAge,Caenorhabditis elegans,alpha-ketoglutaric acid,...,NaN,NaN,56.25,8 mM,31820364.0,Aging,Pubchem,Quick_GO,Drugage,aging
361,55245,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(8S,11R,13S,14S,17S)-11-[4-(dimethylamino)phen...",CC#C[C@@]1(CC[C@@H]2[C@@]1(C[C@@H](C3=C4CCC(=O...,DrugAge,Caenorhabditis elegans,Mifepristone,...,NaN,NaN,15.00,400 μg/mL,32648907.0,Aging,Pubchem,Quick_GO,Drugage,aging

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
    Drugage
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 360

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,14985,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",aging,Caenorhabditis elegans
1,3973,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-morpholin-4-yl-8-phenylchromen-4-one,aging,Caenorhabditis elegans
2,9929901,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"2-methyl-2-[(3E,7E)-4,8,12-trimethyltrideca-3,...",aging,Caenorhabditis elegans
3,171249,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,manganese(3+);2-[2-[(2-oxidophenyl)methylidene...,aging,Caenorhabditis elegans
4,9823233,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,manganese(3+);2-methoxy-6-[2-[(3-methoxy-2-oxi...,aging,Caenorhabditis elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,5281855,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"6,7,13,14-tetrahydroxy-2,9-dioxatetracyclo[6.6...",aging,Caenorhabditis elegans
356,3830,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,N-(furan-2-ylmethyl)-7H-purin-6-amine,aging,Caenorhabditis elegans
357,9964771,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,4-[(7H-purin-6-ylamino)methyl]phenol,aging,Caenorhabditis elegans
358,51,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-oxopentanedioic acid,aging,Caenorhabditis elegans
359,55245,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(8S,11R,13S,14S,17S)-11-[4-(dimethylamino)phen...",aging,Caenorhabditis elegans

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'ChemicalEntity_PositivelyAssociatedWith_BiologicalProcess'}
head_type           : {'ChemicalEntity'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'Drugage'}
head_id_is          : {'Pubchem'}
tail_id_is          : {'Quick_GO'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 360 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           360                   0             360
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 360  |  After dedup: 360

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,51,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-oxopentanedioic acid,aging,Caenorhabditis elegans
1,72,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"3,4-dihydroxybenzoic acid",aging,Caenorhabditis elegans
2,176,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,acetic acid,aging,Caenorhabditis elegans

In [11]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           360                   0             360
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Drugage'} kg_source
Drugage    360
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    360
Name: count, dtype: int64

In [14]:
! mkdir Celegans_chemical_positiveassociated_biologicalprocess

mkdir: cannot create directory ‘Celegans_chemical_positiveassociated_biologicalprocess’: File exists

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 360 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_chemical_positiveassociated_biologicalprocess/Celegans_chemical_positiveassociated_biologicalprocess.csv

In [16]:
# OUT_PATH

# NEGATIVE ASSOCIATION

In [17]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Celegans_chemical_negativeassociated_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_chemical_negativeassociated_biologicalprocess/Celegans_chemical_negativeassociated_biologicalprocess.csv'

mkdir: cannot create directory ‘Celegans_chemical_negativeassociated_biologicalprocess’: File exists

In [18]:
Drugage = pd.read_csv(PROC_DIR + 'drugage/drugage_final/Cele_CE_Neg_BioPro_merged.csv')
Drugage.columns = Drugage.columns.str.lower()
Drugage = Drugage[~Drugage['head_detail_name'].isna()]

Drugage['kg_type'] = 'Aging'

print(f"Drugage: {len(Drugage):,} rows")
Drugage['head_id_is'] = 'Pubchem'
Drugage['tail_id_is'] = 'Quick_GO'
Drugage['relation'] = 'ChemicalEntity_NegativelyAssociatedWith_BiologicalProcess'
Drugage['kg_source'] = 'Drugage'
Drugage['tail_detail_name'] = 'aging'
Drugage

Drugage: 97 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,...,age_at_initiation,treatment_duration,avg_lifespan_change_percent,dosage,pubmed_id,kg_type,head_id_is,tail_id_is,kg_source,tail_detail_name
0,5790,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"5-fluoro-1-[(2R,4S,5R)-4-hydroxy-5-(hydroxymet...",C1[C@@H]([C@H](O[C@H]1N2C=C(C(=O)NC2=O)F)CO)O,DrugAge,Caenorhabditis elegans,Floxuridine,...,NaN,NaN,-18.66,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
1,5793,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(3R,4S,5S,6R)-6-(hydroxymethyl)oxane-2,3,4,5-t...",C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)O,DrugAge,Caenorhabditis elegans,Glucose,...,NaN,NaN,-7.75,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
2,753,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"propane-1,2,3-triol",C(C(CO)O)O,DrugAge,Caenorhabditis elegans,Glycerol,...,NaN,NaN,-24.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
3,162243,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(4R)-4-[(5S,8R,9S,10S,13R,14S,17R)-10,13-dimet...",C[C@H](CCCN(C)C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3...,DrugAge,Caenorhabditis elegans,25-Azacoprostane,...,NaN,NaN,-34.80,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
4,446284,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(5Z,8Z,11Z,14Z,17Z)-icosa-5,8,11,14,17-pentaen...",CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CCCC(=O)O,DrugAge,Caenorhabditis elegans,Eicosapentaenoic acid,...,NaN,NaN,-20.37,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,123596,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,methanesulfonic acid;4-[(4-methylpiperazin-1-y...,CC1=C(C=C(C=C1)NC(=O)C2=CC=C(C=C2)CN3CCN(CC3)C...,DrugAge,Caenorhabditis elegans,Imatinib mesylate,...,NaN,NaN,-58.91,1000 µM,32010883.0,Aging,Pubchem,Quick_GO,Drugage,aging
93,2230,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"methyl 1-methyl-3,6-dihydro-2H-pyridine-5-carb...",CN1CCC=C(C1)C(=O)OC,DrugAge,Caenorhabditis elegans,Arecoline,...,NaN,NaN,-63.50,0.2 mM,32854519.0,Aging,Pubchem,Quick_GO,Drugage,aging
95,12035,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,(2R)-2-acetamido-3-sulfanylpropanoic acid,CC(=O)N[C@@H](CS)C(=O)O,DrugAge,Caenorhabditis elegans,N-Acetyl Cysteine,...,NaN,NaN,-10.70,5 mM,34267196.0,Aging,Pubchem,Quick_GO,Drugage,aging
96,124886,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-amino-5-[[(2R)-1-(carboxymethylamino)-1...,C(CC(=O)N[C@@H](CS)C(=O)NCC(=O)O)[C@@H](C(=O)O)N,DrugAge,Caenorhabditis elegans,Glutathione,...,NaN,NaN,-13.90,5 mM,34267196.0,Aging,Pubchem,Quick_GO,Drugage,aging
97,5353800,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(3E)-3-(dimethylcarbamoylimino)-1,1-dimethylurea",CN(C)C(=O)/N=N/C(=O)N(C)C,DrugAge,Caenorhabditis elegans,Diamide,...,NaN,NaN,-24.88,5 mM,34267196.0,Aging,Pubchem,Quick_GO,Drugage,aging

In [19]:
# List all source DataFrames to include
source_dfs = [
    Drugage
    
]
aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 97

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,5790,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"5-fluoro-1-[(2R,4S,5R)-4-hydroxy-5-(hydroxymet...",aging,Caenorhabditis elegans
1,5793,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(3R,4S,5S,6R)-6-(hydroxymethyl)oxane-2,3,4,5-t...",aging,Caenorhabditis elegans
2,753,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"propane-1,2,3-triol",aging,Caenorhabditis elegans
3,162243,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(4R)-4-[(5S,8R,9S,10S,13R,14S,17R)-10,13-dimet...",aging,Caenorhabditis elegans
4,446284,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(5Z,8Z,11Z,14Z,17Z)-icosa-5,8,11,14,17-pentaen...",aging,Caenorhabditis elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,123596,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,methanesulfonic acid;4-[(4-methylpiperazin-1-y...,aging,Caenorhabditis elegans
93,2230,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"methyl 1-methyl-3,6-dihydro-2H-pyridine-5-carb...",aging,Caenorhabditis elegans
94,12035,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,(2R)-2-acetamido-3-sulfanylpropanoic acid,aging,Caenorhabditis elegans
95,124886,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,(2S)-2-amino-5-[[(2R)-1-(carboxymethylamino)-1...,aging,Caenorhabditis elegans
96,5353800,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(3E)-3-(dimethylcarbamoylimino)-1,1-dimethylurea",aging,Caenorhabditis elegans

In [20]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            97                   0              97
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [21]:
! mkdir Celegans_chemical_negativeassociated_biologicalprocess

mkdir: cannot create directory ‘Celegans_chemical_negativeassociated_biologicalprocess’: File exists

In [22]:
final_df.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df):,} rows → {OUT_PATH}")

Saved 97 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_chemical_negativeassociated_biologicalprocess/Celegans_chemical_negativeassociated_biologicalprocess.csv

# NOT ASSOCIATION

In [23]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Celegans_chemical_notassociated_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_chemical_notassociated_biologicalprocess/Celegans_chemical_notassociated_biologicalprocess.csv'

mkdir: cannot create directory ‘Celegans_chemical_notassociated_biologicalprocess’: File exists

In [24]:
Drugage = pd.read_csv(PROC_DIR + 'drugage/drugage_final/Cele_CE_Not_BioPro_merged.csv')
Drugage.columns = Drugage.columns.str.lower()
Drugage = Drugage[~Drugage['head_detail_name'].isna()]

Drugage['kg_type'] = 'Aging'

print(f"Drugage: {len(Drugage):,} rows")
Drugage['head_id_is'] = 'Pubchem'
Drugage['tail_id_is'] = 'Quick_GO'
Drugage['relation'] = 'ChemicalEntity_NotAssociatedWith_BiologicalProcess'
Drugage['kg_source'] = 'Drugage'
Drugage['tail_detail_name'] = 'aging'
Drugage

Drugage: 198 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,...,age_at_initiation,treatment_duration,avg_lifespan_change_percent,dosage,pubmed_id,kg_type,head_id_is,tail_id_is,kg_source,tail_detail_name
0,65064,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"[(2R,3R)-5,7-dihydroxy-2-(3,4,5-trihydroxyphen...",C1[C@H]([C@H](OC2=CC(=CC(=C21)O)O)C3=CC(=C(C(=...,DrugAge,Caenorhabditis elegans,Epigallocatechin-3-gallate,...,NaN,NaN,4.80,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
1,6223,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"(1R,7S,8S,11R)-7-hydroxy-11-(hydroxymethyl)-15...",CN1C(=O)[C@]23CC4=CC=C[C@@H]([C@H]4N2C(=O)[C@]...,DrugAge,Caenorhabditis elegans,Gliotoxin,...,NaN,NaN,0.90,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
2,124886,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-amino-5-[[(2R)-1-(carboxymethylamino)-1...,C(CC(=O)N[C@@H](CS)C(=O)NCC(=O)O)[C@@H](C(=O)O)N,DrugAge,Caenorhabditis elegans,Glutathione,...,NaN,NaN,NaN,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
3,5780,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R,3R,4R,5S)-hexane-1,2,3,4,5,6-hexol",C([C@H]([C@H]([C@@H]([C@H](CO)O)O)O)O)O,DrugAge,Caenorhabditis elegans,Sorbitol,...,NaN,NaN,-2.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
4,5988,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R,3R,4S,5S,6R)-2-[(2S,3S,4S,5R)-3,4-dihydrox...",C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@]2([C...,DrugAge,Caenorhabditis elegans,Sucrose,...,NaN,NaN,-4.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,2230,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"methyl 1-methyl-3,6-dihydro-2H-pyridine-5-carb...",CN1CCC=C(C1)C(=O)OC,DrugAge,Caenorhabditis elegans,Arecoline,...,NaN,NaN,-15.95,0.2 mM,32854519.0,Aging,Pubchem,Quick_GO,Drugage,aging
195,2973,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,N-[5-[[4-[5-[acetyl(hydroxy)amino]pentylamino]...,CC(=O)N(CCCCCNC(=O)CCC(=O)N(CCCCCNC(=O)CCC(=O)...,DrugAge,Caenorhabditis elegans,Deferoxamine,...,NaN,NaN,-4.45,100 µM,22445852.0,Aging,Pubchem,Quick_GO,Drugage,aging
196,5353800,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"(3E)-3-(dimethylcarbamoylimino)-1,1-dimethylurea",CN(C)C(=O)/N=N/C(=O)N(C)C,DrugAge,Caenorhabditis elegans,Diamide,...,NaN,NaN,1.74,2.5 mM,34267196.0,Aging,Pubchem,Quick_GO,Drugage,aging
197,13975035,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"2-phenyl-2-sulfanylidene-3H-1,3,2lambda5-benzo...",C1=CC=C(C=C1)P2(=S)NC3=CC=CC=C3O2,DrugAge,Caenorhabditis elegans,FW1256,...,NaN,NaN,0.55,10 µM,32566245.0,Aging,Pubchem,Quick_GO,Drugage,aging
198,55245,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"(8S,11R,13S,14S,17S)-11-[4-(dimethylamino)phen...",CC#C[C@@]1(CC[C@@H]2[C@@]1(C[C@@H](C3=C4CCC(=O...,DrugAge,Caenorhabditis elegans,Mifepristone,...,NaN,NaN,-9.00,400 μg/mL,32648907.0,Aging,Pubchem,Quick_GO,Drugage,aging

In [25]:
# List all source DataFrames to include
source_dfs = [
    Drugage
    
]
aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 198

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,65064,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"[(2R,3R)-5,7-dihydroxy-2-(3,4,5-trihydroxyphen...",aging,Caenorhabditis elegans
1,6223,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(1R,7S,8S,11R)-7-hydroxy-11-(hydroxymethyl)-15...",aging,Caenorhabditis elegans
2,124886,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,(2S)-2-amino-5-[[(2R)-1-(carboxymethylamino)-1...,aging,Caenorhabditis elegans
3,5780,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2R,3R,4R,5S)-hexane-1,2,3,4,5,6-hexol",aging,Caenorhabditis elegans
4,5988,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2R,3R,4S,5S,6R)-2-[(2S,3S,4S,5R)-3,4-dihydrox...",aging,Caenorhabditis elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,2230,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"methyl 1-methyl-3,6-dihydro-2H-pyridine-5-carb...",aging,Caenorhabditis elegans
194,2973,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,N-[5-[[4-[5-[acetyl(hydroxy)amino]pentylamino]...,aging,Caenorhabditis elegans
195,5353800,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(3E)-3-(dimethylcarbamoylimino)-1,1-dimethylurea",aging,Caenorhabditis elegans
196,13975035,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"2-phenyl-2-sulfanylidene-3H-1,3,2lambda5-benzo...",aging,Caenorhabditis elegans
197,55245,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(8S,11R,13S,14S,17S)-11-[4-(dimethylamino)phen...",aging,Caenorhabditis elegans

In [26]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           198                   0             198
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [27]:
! mkdir Celegans_chemical_notassociated_biologicalprocess

mkdir: cannot create directory ‘Celegans_chemical_notassociated_biologicalprocess’: File exists

In [28]:
OUT_PATH

'/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_chemical_notassociated_biologicalprocess/Celegans_chemical_notassociated_biologicalprocess.csv'

In [29]:
final_df.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df):,} rows → {OUT_PATH}")

Saved 198 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Celegans/Celegans_chemical_notassociated_biologicalprocess/Celegans_chemical_notassociated_biologicalprocess.csv