In [1]:
import pandas as pd
import numpy as np
import re

In [3]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/data_processing/species_specific_data_source/Mouse

# Mappings

In [2]:
your_path_here = '/storage/Arushi/090526_EvoAge/kg_formation/data_collection/'

In [ ]:
Pubchem = pd.read_pickle(f'{your_path_here}databases_for_mapping/pubchem/combined_df.pkl')

In [23]:
## Gprofiler_protein to gene

GPRO = pd.read_csv(f'{your_path_here}stitch/mmus/gProfiler_mmusculus_4-9-2025_11-29-22 PM.csv')
GPRO = GPRO[~GPRO['converted_alias'].isna()]
GPRO
protein_to_gene_dict = dict(zip(GPRO['initial_alias'], GPRO['name']))
protein_to_gene_dict
gene_to_description_dict = dict(zip(GPRO['name'], GPRO['description']))
gene_to_description_dict
GPRO

,initial_alias,converted_alias,name,description,namespace
0,ENSMUSP00000112926,ENSMUSG00000066880,Zfp617,zinc finger protein 617 [Source:MGI Symbol;Acc...,ENSP
1,ENSMUSP00000000348,ENSMUSG00000000339,Rtca,RNA 3'-terminal phosphate cyclase [Source:MGI ...,ENSP
2,ENSMUSP00000045327,ENSMUSG00000067299,Crygd,"crystallin, gamma D [Source:MGI Symbol;Acc:MGI...",ENSP
4,ENSMUSP00000034904,ENSMUSG00000032349,Elovl5,ELOVL fatty acid elongase 5 [Source:MGI Symbol...,ENSP
5,ENSMUSP00000135826,ENSMUSG00000093575,Gm20695,predicted gene 20695 [Source:MGI Symbol;Acc:MG...,ENSP
...,...,...,...,...,...
20124,ENSMUSP00000051282,ENSMUSG00000046854,Pip5kl1,phosphatidylinositol-4-phosphate 5-kinase-like...,ENSP
20125,ENSMUSP00000077535,ENSMUSG00000058063,Trim31,tripartite motif-containing 31 [Source:MGI Sym...,ENSP
20126,ENSMUSP00000069017,ENSMUSG00000054836,Elp6,elongator acetyltransferase complex subunit 6 ...,ENSP
20127,ENSMUSP00000054125,ENSMUSG00000048230,Fbxo43,F-box protein 43 [Source:MGI Symbol;Acc:MGI:19...,ENSP
20128,ENSMUSP00000079926,ENSMUSG00000025949,Pikfyve,"phosphoinositide kinase, FYVE type zinc finger...",ENSP

In [27]:
## Pubchem_2_name 

Pubchem = pd.read_pickle(f'{your_path_here}databases_for_mapping/pubchem/combined_df.pkl')

Pubchem_CID_Smile_Dict  = dict(zip(Pubchem['PUBCHEM_COMPOUND_CID'], Pubchem['PUBCHEM_SMILES']))
Pubchem_CID_Smile_Dict

pubchem_cid_to_iupac  = dict(zip(Pubchem['PUBCHEM_COMPOUND_CID'], Pubchem['PUBCHEM_IUPAC_NAME']))

# del Pubchem

In [5]:
# del Pubchem
# del Pubchem_CID_Smile_Dict
# del Pubchem_IUPAC_CID_Dict

In [11]:
NCBI_mouse_gene = pd.read_csv(f'{your_path_here}databases_for_mapping/ncbi/Mus_musculus.gene_info',sep = '\t')
NCBI_mouse_gene

# Extract ENSMUSG pattern using regex and save in new column
NCBI_mouse_gene['ENSMBL'] = NCBI_mouse_gene['dbXrefs'].str.extract(r'(ENSMUSG\d+)', expand=False)
NCBI_mouse_gene

NCBI_mouse_gene_Locus_2_GeneSymd_ict = dict(zip(NCBI_mouse_gene['ENSMBL'], NCBI_mouse_gene['Symbol']))
NCBI_mouse_gene_Locus_2_GeneSymd_ict
NCBI_mouse_Locustag_Descrip_dict = dict(zip(NCBI_mouse_gene['LocusTag'], NCBI_mouse_gene['description']))
NCBI_mouse_Locustag_Descrip_dict

,#tax_id,GeneID,Symbol,LocusTag,Synonyms,dbXrefs,chromosome,map_location,description,type_of_gene,Symbol_from_nomenclature_authority,Full_name_from_nomenclature_authority,Nomenclature_status,Other_designations,Modification_date,Feature_type
0,10090,11287,Pzp,-,A1m|A2m|MAM,MGI:MGI:87854|Ensembl:ENSMUSG00000030359|Allia...,6,6 F3|6 63.02 cM,"PZP, alpha-2-macroglobulin like",protein-coding,Pzp,"PZP, alpha-2-macroglobulin like",O,pregnancy zone protein|alpha 1 macroglobulin|a...,20250308,-
1,10090,11298,Aanat,-,AA-NAT|Nat-2|Nat4|Snat,MGI:MGI:1328365|Ensembl:ENSMUSG00000020804|All...,11,11 81.43 cM|11 E2,arylalkylamine N-acetyltransferase,protein-coding,Aanat,arylalkylamine N-acetyltransferase,O,serotonin N-acetyltransferase|aralkylamine N-a...,20250308,-
2,10090,11302,Aatk,-,AATYK|aatyk1|mKIAA0641,MGI:MGI:1197518|Ensembl:ENSMUSG00000025375|All...,11,11 E2|11 83.96 cM,apoptosis-associated tyrosine kinase,protein-coding,Aatk,apoptosis-associated tyrosine kinase,O,serine/threonine-protein kinase LMTK1|apoptosi...,20250308,-
3,10090,11303,Abca1,-,ABC-1|Abc1,MGI:MGI:99607|Ensembl:ENSMUSG00000015243|Allia...,4,4 B2|4 28.57 cM,"ATP-binding cassette, sub-family A member 1",protein-coding,Abca1,"ATP-binding cassette, sub-family A member 1",O,phospholipid-transporting ATPase ABCA1|ATP-bin...,20250308,-
4,10090,11304,Abca4,-,Abc10|Abcr|D430003I15Rik|RmP,MGI:MGI:109424|Ensembl:ENSMUSG00000028125|Alli...,3,3 G1|3 52.94 cM,"ATP-binding cassette, sub-family A member 4",protein-coding,Abca4,"ATP-binding cassette, sub-family A member 4",O,retinal-specific phospholipid-transporting ATP...,20250308,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112364,57486,3337213,ND3,-,-,-,MT,-,NADH dehydrogenase subunit 3,protein-coding,-,-,-,-,20230818,-
112365,57486,3337214,ND1,-,-,-,MT,-,NADH dehydrogenase subunit 1,protein-coding,-,-,-,-,20230818,-
112366,57486,3337215,ND6,-,-,-,MT,-,NADH dehydrogenase subunit 6,protein-coding,-,-,-,-,20230818,-
112367,57486,3337216,ATP8,-,-,-,MT,-,ATP synthase F0 subunit 8,protein-coding,-,-,-,-,20230818,-
112368,57486,3337217,ND2,-,-,-,MT,-,NADH dehydrogenase subunit 2,protein-coding,-,-,-,-,20230818,-

# Mouse

# Chemical Gene

In [28]:
# mouse_chemical_protein_path =  f'{your_path_here}stitch/mouse/10090.protein_chemical.links.detailed.v5.0.tsv'

chem_gene_df =pd.read_csv(f'{your_path_here}stitch/mmus/10090.protein_chemical.links.detailed.v5.0.tsv', sep = '\t')
chem_gene_df

chem_gene_df = chem_gene_df.rename(columns={'chemical':'Head', 'protein':'Tail'})
chem_gene_df['Tail'] = chem_gene_df['Tail'].str.replace('10090.', '', regex=False)

# Cele_C_P = Cele_C_P.drop(columns={'head_smile', 'Tail_SEQ'})

# =============================================================================
# Clean chemical IDs — strip STITCH prefixes and leading zeros
# =============================================================================

def clean_chemical_id(chem_id):
    """Remove STITCH-specific prefixes and leading zeros from chemical IDs."""
    return chem_id.lstrip('CIDs').lstrip('CIDm').lstrip('0')

# Note: DataFrame.applymap() is deprecated in newer pandas — should use .map() instead
chem_gene_df[['Head']] = chem_gene_df[['Head']].applymap(clean_chemical_id)

# Add KG metadata
chem_gene_df['relation'] = 'ChemicalEntity_Gene'
chem_gene_df['head_type'] = 'ChemicalEntity'
chem_gene_df['tail_type'] = 'Gene'
chem_gene_df['relation_type'] = np.nan
chem_gene_df['kg_source'] = 'STITCH'

# Map Ensembl Protein IDs to gene symbols using gProfiler
chem_gene_df['tail'] = chem_gene_df['Tail'].map(protein_to_gene_dict)

print(f"Chemical IDs cleaned, protein IDs mapped to gene symbols")
print(f"Mapped genes: {chem_gene_df['tail'].notna().sum():,}")
print(f"Unmapped (NaN): {chem_gene_df['tail'].isna().sum():,}")
chem_gene_df

/tmp/ipykernel_1702666/724579688.py:20: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  chem_gene_df[['Head']] = chem_gene_df[['Head']].applymap(clean_chemical_id)

Chemical IDs cleaned, protein IDs mapped to gene symbols
Mapped genes: 38,224,741
Unmapped (NaN): 891,511

,Head,Tail,experimental,prediction,database,textmining,combined_score,relation,head_type,tail_type,relation_type,kg_source,tail
0,91758680,ENSMUSP00000053638,0,0,0,253,253,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Aplnr
1,91758408,ENSMUSP00000001179,0,0,0,195,195,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Pcnt
2,91758408,ENSMUSP00000005488,0,0,0,156,156,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Casp14
3,91758408,ENSMUSP00000006618,0,0,0,162,162,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Arhgef19
4,91758408,ENSMUSP00000007012,0,0,0,170,170,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Sod2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39116247,1,ENSMUSP00000135826,0,0,789,0,789,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Gm20695
39116248,1,ENSMUSP00000136352,0,0,0,408,408,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,NaN
39116249,1,ENSMUSP00000136589,0,0,0,162,162,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Pbld1
39116250,1,ENSMUSP00000136633,0,0,0,162,162,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,NaN
39116251,1,ENSMUSP00000137387,0,0,0,408,408,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,NaN

In [29]:
# =============================================================================
# Map descriptions and filter unmapped entries
# =============================================================================

# Drop original 'Tail' column (Ensembl ID) — replaced by 'tail' (gene symbol)
# Note: DataFrame.drop() with inplace=True is planned for deprecation in future pandas
chem_gene_df.drop('Tail', axis=1, inplace=True)

# Map gene descriptions from gProfiler
chem_gene_df['tail_detail_name'] = chem_gene_df['tail'].map(gene_to_description_dict)

# Map chemical IUPAC names from PubChem
chem_gene_df['head_detail_name'] = chem_gene_df['Head'].map(pubchem_cid_to_iupac)

# Filter out entries with unmapped genes or descriptions
before_count = len(chem_gene_df)
chem_gene_df = chem_gene_df[~chem_gene_df['tail'].isna()]
chem_gene_df = chem_gene_df[~chem_gene_df['tail_detail_name'].isna()]
chem_gene_df = chem_gene_df[~chem_gene_df['head_detail_name'].isna()]
after_count = len(chem_gene_df)

print(f"Before filtering: {before_count:,}")
print(f"After filtering: {after_count:,}")
print(f"Removed: {before_count - after_count:,} triples with unmapped entities")
chem_gene_df

Before filtering: 39,116,252
After filtering: 37,026,061
Removed: 2,090,191 triples with unmapped entities

,Head,experimental,prediction,database,textmining,combined_score,relation,head_type,tail_type,relation_type,kg_source,tail,tail_detail_name,head_detail_name
0,91758680,0,0,0,253,253,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Aplnr,apelin receptor [Source:MGI Symbol;Acc:MGI:134...,"azane;2-hydroxypropane-1,2,3-tricarboxylate;ir..."
1,91758408,0,0,0,195,195,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Pcnt,pericentrin (kendrin) [Source:MGI Symbol;Acc:M...,N-[2-[[5-chloro-2-(oxan-4-ylamino)pyrimidin-4-...
2,91758408,0,0,0,156,156,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Casp14,caspase 14 [Source:MGI Symbol;Acc:MGI:1335092],N-[2-[[5-chloro-2-(oxan-4-ylamino)pyrimidin-4-...
3,91758408,0,0,0,162,162,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Arhgef19,Rho guanine nucleotide exchange factor 19 [Sou...,N-[2-[[5-chloro-2-(oxan-4-ylamino)pyrimidin-4-...
4,91758408,0,0,0,170,170,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Sod2,"superoxide dismutase 2, mitochondrial [Source:...",N-[2-[[5-chloro-2-(oxan-4-ylamino)pyrimidin-4-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39116241,1,0,0,730,0,730,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Lpcat2b,lysophosphatidylcholine acyltransferase 2B [So...,3-acetyloxy-4-(trimethylazaniumyl)butanoate
39116243,1,0,0,469,182,553,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Eci2,enoyl-Coenzyme A delta isomerase 2 [Source:MGI...,3-acetyloxy-4-(trimethylazaniumyl)butanoate
39116245,1,0,0,408,0,408,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Baz1a,bromodomain adjacent to zinc finger domain 1A ...,3-acetyloxy-4-(trimethylazaniumyl)butanoate
39116247,1,0,0,789,0,789,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Gm20695,predicted gene 20695 [Source:MGI Symbol;Acc:MG...,3-acetyloxy-4-(trimethylazaniumyl)butanoate
39116249,1,0,0,0,162,162,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Pbld1,phenazine biosynthesis-like protein domain con...,3-acetyloxy-4-(trimethylazaniumyl)butanoate

In [30]:
# =============================================================================
# Standardize columns and add remaining metadata
# =============================================================================

chem_gene_df.columns = chem_gene_df.columns.str.lower()
chem_gene_df['species'] = 'M.musculus'
chem_gene_df['head_id_is'] = 'Pubchem'
chem_gene_df['tail_id_is'] = 'NCBI_ID'
chem_gene_df['relation'] = 'ChemicalEntity_Gene'

# Remove duplicate columns (if any from mixed-case renaming)
cols = pd.Series(chem_gene_df.columns)
duplicates = cols[cols.duplicated()].unique()
for dup in duplicates:
    first_index = cols[cols == dup].index[0]
    chem_gene_df.drop(chem_gene_df.columns[first_index], axis=1, inplace=True)

# Handle duplicate 'tail' columns if present
tail_indices = [i for i, col in enumerate(chem_gene_df.columns) if col == 'tail']
if len(tail_indices) > 1:
    chem_gene_df.drop(chem_gene_df.columns[tail_indices[0]], axis=1, inplace=True)

print(f"Final columns: {list(chem_gene_df.columns)}")
print(f"Triples: {len(chem_gene_df):,}")

Final columns: ['head', 'experimental', 'prediction', 'database', 'textmining', 'combined_score', 'relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'tail', 'tail_detail_name', 'head_detail_name', 'species', 'head_id_is', 'tail_id_is']
Triples: 37,026,061

In [34]:
final_df = chem_gene_df

In [35]:
set(final_df['species']), set(final_df['relation']),set(final_df['head_type']),set(final_df['tail_type']),set(final_df['kg_source']),set(final_df['head_id_is']),set(final_df['tail_id_is'])

({'M.musculus'},
 {'ChemicalEntity_Gene'},
 {'ChemicalEntity'},
 {'Gene'},
 {'STITCH'},
 {'Pubchem'},
 {'NCBI_ID'})

In [36]:
final_df

,head,experimental,prediction,database,textmining,combined_score,relation,head_type,tail_type,relation_type,kg_source,tail,tail_detail_name,head_detail_name,species,head_id_is,tail_id_is
0,91758680,0,0,0,253,253,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Aplnr,apelin receptor [Source:MGI Symbol;Acc:MGI:134...,"azane;2-hydroxypropane-1,2,3-tricarboxylate;ir...",M.musculus,Pubchem,NCBI_ID
1,91758408,0,0,0,195,195,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Pcnt,pericentrin (kendrin) [Source:MGI Symbol;Acc:M...,N-[2-[[5-chloro-2-(oxan-4-ylamino)pyrimidin-4-...,M.musculus,Pubchem,NCBI_ID
2,91758408,0,0,0,156,156,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Casp14,caspase 14 [Source:MGI Symbol;Acc:MGI:1335092],N-[2-[[5-chloro-2-(oxan-4-ylamino)pyrimidin-4-...,M.musculus,Pubchem,NCBI_ID
3,91758408,0,0,0,162,162,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Arhgef19,Rho guanine nucleotide exchange factor 19 [Sou...,N-[2-[[5-chloro-2-(oxan-4-ylamino)pyrimidin-4-...,M.musculus,Pubchem,NCBI_ID
4,91758408,0,0,0,170,170,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Sod2,"superoxide dismutase 2, mitochondrial [Source:...",N-[2-[[5-chloro-2-(oxan-4-ylamino)pyrimidin-4-...,M.musculus,Pubchem,NCBI_ID
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39116241,1,0,0,730,0,730,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Lpcat2b,lysophosphatidylcholine acyltransferase 2B [So...,3-acetyloxy-4-(trimethylazaniumyl)butanoate,M.musculus,Pubchem,NCBI_ID
39116243,1,0,0,469,182,553,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Eci2,enoyl-Coenzyme A delta isomerase 2 [Source:MGI...,3-acetyloxy-4-(trimethylazaniumyl)butanoate,M.musculus,Pubchem,NCBI_ID
39116245,1,0,0,408,0,408,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Baz1a,bromodomain adjacent to zinc finger domain 1A ...,3-acetyloxy-4-(trimethylazaniumyl)butanoate,M.musculus,Pubchem,NCBI_ID
39116247,1,0,0,789,0,789,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Gm20695,predicted gene 20695 [Source:MGI Symbol;Acc:MG...,3-acetyloxy-4-(trimethylazaniumyl)butanoate,M.musculus,Pubchem,NCBI_ID
39116249,1,0,0,0,162,162,ChemicalEntity_Gene,ChemicalEntity,Gene,NaN,STITCH,Pbld1,phenazine biosynthesis-like protein domain con...,3-acetyloxy-4-(trimethylazaniumyl)butanoate,M.musculus,Pubchem,NCBI_ID

In [37]:
# =============================================================================
# Deduplicate by grouping on (head, relation, tail)
# =============================================================================

group_cols = ['head', 'relation', 'tail']

def merge_sources(x):
    """Merge multiple kg_source values with '::' separator."""
    return '::'.join(sorted(set(x.dropna().astype(str))))

chem_gene_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type': 'first',
    'relation_type': 'first',
    'tail_type': 'first',
    'kg_source': merge_sources,
    'head_id_is': 'first',
    'tail_id_is': 'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Triples before deduplication: {len(final_df):,}")
print(f"Triples after deduplication: {len(chem_gene_dedup):,}")
print(f"Duplicates removed: {len(chem_gene_df) - len(chem_gene_dedup):,}")
chem_gene_dedup.head()

Triples before deduplication: 37,026,061
Triples after deduplication: 21,357,298
Duplicates removed: 15,668,763

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,1,ChemicalEntity_Gene,Aanat,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,arylalkylamine N-acetyltransferase [Source:MGI...,M.musculus
1,1,ChemicalEntity_Gene,Acaa1a,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,acetyl-Coenzyme A acyltransferase 1A [Source:M...,M.musculus
2,1,ChemicalEntity_Gene,Acaa1b,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,acetyl-Coenzyme A acyltransferase 1B [Source:M...,M.musculus
3,1,ChemicalEntity_Gene,Acaa2,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,acetyl-CoA acyltransferase 2 [Source:MGI Symbo...,M.musculus
4,1,ChemicalEntity_Gene,Acadm,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,"acyl-Coenzyme A dehydrogenase, medium chain [S...",M.musculus

In [38]:

chem_gene_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,1,ChemicalEntity_Gene,Aanat,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,arylalkylamine N-acetyltransferase [Source:MGI...,M.musculus
1,1,ChemicalEntity_Gene,Acaa1a,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,acetyl-Coenzyme A acyltransferase 1A [Source:M...,M.musculus
2,1,ChemicalEntity_Gene,Acaa1b,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,acetyl-Coenzyme A acyltransferase 1B [Source:M...,M.musculus
3,1,ChemicalEntity_Gene,Acaa2,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,acetyl-CoA acyltransferase 2 [Source:MGI Symbo...,M.musculus
4,1,ChemicalEntity_Gene,Acadm,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-acetyloxy-4-(trimethylazaniumyl)butanoate,"acyl-Coenzyme A dehydrogenase, medium chain [S...",M.musculus
...,...,...,...,...,...,...,...,...,...,...,...,...
21357293,9999994,ChemicalEntity_Gene,Ces4a,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,carboxylesterase 4A [Source:MGI Symbol;Acc:MGI...,M.musculus
21357294,9999994,ChemicalEntity_Gene,Nlgn1,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,neuroligin 1 [Source:MGI Symbol;Acc:MGI:2179435],M.musculus
21357295,9999994,ChemicalEntity_Gene,Nlgn2,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,neuroligin 2 [Source:MGI Symbol;Acc:MGI:2681835],M.musculus
21357296,9999994,ChemicalEntity_Gene,Nlgn3,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,neuroligin 3 [Source:MGI Symbol;Acc:MGI:2444609],M.musculus
21357297,9999994,ChemicalEntity_Gene,Tg,ChemicalEntity,NaN,Gene,STITCH,Pubchem,NCBI_ID,3-[1-[(3-chlorophenyl)methyl]piperidin-4-yl]-1...,thyroglobulin [Source:MGI Symbol;Acc:MGI:98733],M.musculus

In [40]:
# =============================================================================
# Data quality validation
# =============================================================================

true_nan_count = chem_gene_dedup.isna().sum()
string_nan_count = chem_gene_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

nan_summary = pd.DataFrame({
    'NaN_count': true_nan_count,
    "'NAN'_string_count": string_nan_count,
    'Total_NaN_like': true_nan_count + string_nan_count
})

nan_summary

NaN validation summary:

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type      21357298            21357298        42714596
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [43]:
chem_gene_dedup.to_csv('/storage/Arushi/090526_EvoAge/kg_formation/processed_data/stitch/stitch_MOUSE_CHEMICALENTITY_GENE.csv',index = None)