# ANATOMY ↔ GENE Relation-Wise Merge

Merges ANATOMY–GENE triples from multiple KG sources (DRKG, PrimeKG, Hetionet, TARKG),
aligns to a common schema, deduplicates by `(head, relation, tail)`, and saves the result.

## 0. Configuration

In [16]:
import os
import pandas as pd
import numpy as np

# ── Base directories ──────────────────────────────────────────────────────────
BASE_DIR  = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR  = BASE_DIR + 'processed_data/'
PROC_DIR  = BASE_DIR + 'processed_data/'


# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH  = BASE_DIR + 'processed_data_relation_wise_merge/generalised/ANATOMY_BIOLOGICALPROCESS/ALL_ANATOMY_BIOLOGICALPROCESS.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

## 1. Build Lookup Dictionaries

In [17]:
UBERON = pd.read_csv(f'{BASE_DIR}data_collection/databases_for_mapping/uberon/Uberon_ID_Name_non_dup.csv')
UBERON_dict = dict(zip(UBERON['UBERON ID'], UBERON['Name']))
# UBERON_dict

In [18]:
# MESH mapping to map tail (GO_ID) to name
go_db = pd.read_csv(f'{BASE_DIR}data_collection/databases_for_mapping/MESH/MESH_GO_ID_NAME.csv')
GO_dict = dict(zip(go_db['id'], go_db['name']))
del go_db

## 2. Load Individual KG Sources

### 2a. Monarch

In [19]:
Monarch_Anatomy_cellularComp = pd.read_csv(f'{BASE_DIR}processed_data/Monarch/Human/Human_AnatomicalEntity_BiologicalProcess_Monarch.csv')
Monarch_Anatomy_cellularComp.columns = Monarch_Anatomy_cellularComp.columns.str.lower()
Monarch_Anatomy_cellularComp['head_detail_name'] = Monarch_Anatomy_cellularComp['head'].map(UBERON_dict)
Monarch_Anatomy_cellularComp['tail_detail_name'] = Monarch_Anatomy_cellularComp['tail'].map(GO_dict)

print(f"DRKG:     {len(Monarch_Anatomy_cellularComp):,} rows | columns: {list(Monarch_Anatomy_cellularComp.columns)}")
Monarch_Anatomy_cellularComp['kg_type'] = 'Generalised'
Monarch_Anatomy_cellularComp['species'] = 'Homo sapiens'
Monarch_Anatomy_cellularComp['kg_source'] = 'Monarch_KG'

Monarch_Anatomy_cellularComp

DRKG:     321 rows | columns: ['head', 'tail', 'relation_type', 'relation_source', 'kgsource', 'head_name', 'head_type', 'head_id_is', 'head_taxon', 'head_taxon_label', 'tail_name', 'tail_type', 'tail_id_is', 'tail_taxon', 'tail_taxon_label', 'head_taxon_name', 'tail_taxon_name', 'head_type_clean', 'tail_type_clean', 'relation', 'species_species', 'head_detail_name', 'tail_detail_name']

,head,tail,relation_type,relation_source,kgsource,head_name,head_type,head_id_is,head_taxon,head_taxon_label,...,tail_taxon_name,head_type_clean,tail_type_clean,relation,species_species,head_detail_name,tail_detail_name,kg_type,species,kg_source
0,UBERON:0000004,GO:0007608,related_to,infores:uberon,MonarchKG,nose,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,BiologicalProcess,AnatomicalEntity_BiologicalProcess,NaN,nose,sensory perception of smell,Generalised,Homo sapiens,Monarch_KG
1,UBERON:0000005,GO:0007606,related_to,infores:uberon,MonarchKG,chemosensory organ,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,BiologicalProcess,AnatomicalEntity_BiologicalProcess,NaN,chemosensory organ,sensory perception of chemical stimulus,Generalised,Homo sapiens,Monarch_KG
2,UBERON:0000007,GO:0007276,related_to,infores:uberon,MonarchKG,pituitary gland,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,BiologicalProcess,AnatomicalEntity_BiologicalProcess,NaN,pituitary gland,gamete generation,Generalised,Homo sapiens,Monarch_KG
3,UBERON:0000016,GO:0030073,related_to,infores:uberon,MonarchKG,endocrine pancreas,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,BiologicalProcess,AnatomicalEntity_BiologicalProcess,NaN,endocrine pancreas,insulin secretion,Generalised,Homo sapiens,Monarch_KG
4,UBERON:0000016,GO:0070091,related_to,infores:uberon,MonarchKG,endocrine pancreas,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,BiologicalProcess,AnatomicalEntity_BiologicalProcess,NaN,endocrine pancreas,glucagon secretion,Generalised,Homo sapiens,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,UBERON:4000146,GO:0001958,related_to,infores:uberon,MonarchKG,transient cartilaginous element,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,BiologicalProcess,AnatomicalEntity_BiologicalProcess,NaN,transient cartilaginous element,endochondral ossification,Generalised,Homo sapiens,Monarch_KG
317,UBERON:6001722,GO:0046879,related_to,infores:uberon,MonarchKG,insect ring gland,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,BiologicalProcess,AnatomicalEntity_BiologicalProcess,NaN,insect ring gland,hormone secretion,Generalised,Homo sapiens,Monarch_KG
318,UBERON:6005805,GO:0050908,related_to,infores:uberon,MonarchKG,insect Bolwig organ,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,BiologicalProcess,AnatomicalEntity_BiologicalProcess,NaN,insect Bolwig organ,detection of light stimulus involved in visual...,Generalised,Homo sapiens,Monarch_KG
319,UBERON:8440011,GO:0007601,related_to,infores:uberon,MonarchKG,cortical visual area,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,BiologicalProcess,AnatomicalEntity_BiologicalProcess,NaN,cortical visual area,visual perception,Generalised,Homo sapiens,Monarch_KG
320,UBERON:8450002,GO:0046903,related_to,infores:uberon,MonarchKG,excretory system,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,BiologicalProcess,AnatomicalEntity_BiologicalProcess,NaN,excretory system,secretion,Generalised,Homo sapiens,Monarch_KG

In [20]:
Monarch_Anatomy_cellularComp[Monarch_Anatomy_cellularComp['head_detail_name'].isna()]

Empty DataFrame
Columns: [head, tail, relation_type, relation_source, kgsource, head_name, head_type, head_id_is, head_taxon, head_taxon_label, tail_name, tail_type, tail_id_is, tail_taxon, tail_taxon_label, head_taxon_name, tail_taxon_name, head_type_clean, tail_type_clean, relation, species_species, head_detail_name, tail_detail_name, kg_type, species, kg_source]
Index: []

[0 rows x 26 columns]

In [21]:
Monarch_Anatomy_cellularComp[Monarch_Anatomy_cellularComp['tail_detail_name'].isna()]

Empty DataFrame
Columns: [head, tail, relation_type, relation_source, kgsource, head_name, head_type, head_id_is, head_taxon, head_taxon_label, tail_name, tail_type, tail_id_is, tail_taxon, tail_taxon_label, head_taxon_name, tail_taxon_name, head_type_clean, tail_type_clean, relation, species_species, head_detail_name, tail_detail_name, kg_type, species, kg_source]
Index: []

[0 rows x 26 columns]

## 3. Align Schemas and Concatenate

In [22]:
source_dfs = [
    Monarch_Anatomy_cellularComp,
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df['species'] = 'Homo sapiens'
final_df

Consolidated rows: 321

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,UBERON:0000004,AnatomicalEntity_BiologicalProcess,GO:0007608,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,nose,sensory perception of smell,Generalised,Homo sapiens
1,UBERON:0000005,AnatomicalEntity_BiologicalProcess,GO:0007606,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,chemosensory organ,sensory perception of chemical stimulus,Generalised,Homo sapiens
2,UBERON:0000007,AnatomicalEntity_BiologicalProcess,GO:0007276,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,pituitary gland,gamete generation,Generalised,Homo sapiens
3,UBERON:0000016,AnatomicalEntity_BiologicalProcess,GO:0030073,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,endocrine pancreas,insulin secretion,Generalised,Homo sapiens
4,UBERON:0000016,AnatomicalEntity_BiologicalProcess,GO:0070091,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,endocrine pancreas,glucagon secretion,Generalised,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,UBERON:4000146,AnatomicalEntity_BiologicalProcess,GO:0001958,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,transient cartilaginous element,endochondral ossification,Generalised,Homo sapiens
317,UBERON:6001722,AnatomicalEntity_BiologicalProcess,GO:0046879,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,insect ring gland,hormone secretion,Generalised,Homo sapiens
318,UBERON:6005805,AnatomicalEntity_BiologicalProcess,GO:0050908,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,insect Bolwig organ,detection of light stimulus involved in visual...,Generalised,Homo sapiens
319,UBERON:8440011,AnatomicalEntity_BiologicalProcess,GO:0007601,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,cortical visual area,visual perception,Generalised,Homo sapiens
320,UBERON:8450002,AnatomicalEntity_BiologicalProcess,GO:0046903,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,excretory system,secretion,Generalised,Homo sapiens

## 4. QC — NaN Check Before Name Repair

In [23]:
def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(final_df)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

## 6. Deduplicate and Add Schema Columns

Group by `(head, relation, tail)` and collapse duplicate `kg_source` values with `::` separator.

In [24]:
GROUP_COLS = ['head', 'relation', 'tail']

def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

final_df_dedup = final_df.groupby(GROUP_COLS, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'kg_type': merge_sources,
    'species': 'first',
})

# Enforce final column order
final_df_dedup = final_df_dedup[REQUIRED_COLS]

print(f"After deduplication: {len(final_df_dedup):,} rows")
final_df_dedup.head()

After deduplication: 321 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,UBERON:0000004,AnatomicalEntity_BiologicalProcess,GO:0007608,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,nose,sensory perception of smell,Generalised,Homo sapiens
1,UBERON:0000005,AnatomicalEntity_BiologicalProcess,GO:0007606,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,chemosensory organ,sensory perception of chemical stimulus,Generalised,Homo sapiens
2,UBERON:0000007,AnatomicalEntity_BiologicalProcess,GO:0007276,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,pituitary gland,gamete generation,Generalised,Homo sapiens
3,UBERON:0000016,AnatomicalEntity_BiologicalProcess,GO:0030073,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,endocrine pancreas,insulin secretion,Generalised,Homo sapiens
4,UBERON:0000016,AnatomicalEntity_BiologicalProcess,GO:0070091,AnatomicalEntity,related_to,BiologicalProcess,Monarch_KG,UBERON,GO,endocrine pancreas,glucagon secretion,Generalised,Homo sapiens

In [25]:
print("\nkg_source values present:", set(final_df_dedup['kg_source']))

kg_source values present: {'Monarch_KG'}

In [26]:
print("\nkg_type values present:", set(final_df_dedup['kg_type']))

kg_type values present: {'Generalised'}

## 7. QC — NaN Check After Deduplication

In [27]:
nan_summary(final_df_dedup)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

In [28]:
final_df_dedup['head_species'] = 'Homo sapiens'
final_df_dedup['tail_species'] = 'Homo sapiens'

## 8. Save Output

In [29]:
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 321 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/ANATOMY_BIOLOGICALPROCESS/ALL_ANATOMY_BIOLOGICALPROCESS.csv

In [31]:
#