# Phenotype ↔ Phenotype Relation-Wise Merge

Merges Phenotype–Phenotype triples from PrimeKG, GPKG, and TARKG;
deduplicates by `(head, relation, tail)`; and saves the result.

## 0. Configuration

In [1]:

import os
import pandas as pd
import numpy as np

BASE_DIR  = '/storage/Arushi/090526_EvoAge/kg_formation/'
DB_DIR     = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR  = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/PHENOTYPE_PHENOTYPE/ALL_PHENOTYPE_PHENOTYPE.csv'

# ── Required output schema ────────────────────────────────────────────────────

REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

## 1. Load KG Sources

### 1a. PrimeKG

In [2]:
PrimeKG_Phenotype_Phenotype = pd.read_csv(PROC_DIR + 'PrimeKG/PrimeKG_Phenotype_Phenotype.csv')
PrimeKG_Phenotype_Phenotype.columns = PrimeKG_Phenotype_Phenotype.columns.str.lower()
print(f"PrimeKG: {len(PrimeKG_Phenotype_Phenotype):,} rows | columns: {list(PrimeKG_Phenotype_Phenotype.columns)}")
PrimeKG_Phenotype_Phenotype['kg_type'] = 'Generalised'
PrimeKG_Phenotype_Phenotype['kg_source'] = 'PrimeKG'
PrimeKG_Phenotype_Phenotype['species'] = 'Homo species'
PrimeKG_Phenotype_Phenotype.head(2)

PrimeKG: 18,736 rows | columns: ['head', 'relation', 'tail', 'head_type', 'relation_type', 'tail_type', 'kg_source', 'head_id_is', 'tail_id_is', 'head_detail_name', 'tail_detail_name']

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,HP:0000002,Phenotype_Phenotype,HP:0001507,Phenotype,parent-child,Phenotype,PrimeKG,HPO_ID,HPO_ID,Abnormality of body height,Growth abnormality,Generalised,Homo species
1,HP:0000003,Phenotype_Phenotype,HP:0000107,Phenotype,parent-child,Phenotype,PrimeKG,HPO_ID,HPO_ID,Multicystic kidney dysplasia,Renal cyst,Generalised,Homo species

### 1b. GPKG

In [3]:
GPKG_Phenotype_Phenotype = pd.read_csv(PROC_DIR + 'GPKG/Phenotype_Phenotype_GPKG.csv')
GPKG_Phenotype_Phenotype.columns = GPKG_Phenotype_Phenotype.columns.str.lower()
GPKG_Phenotype_Phenotype.rename(columns={'head_name': 'head_detail_name', 'tail_name': 'tail_detail_name'}, inplace=True)
print(f"GPKG:    {len(GPKG_Phenotype_Phenotype):,} rows | columns: {list(GPKG_Phenotype_Phenotype.columns)}")
GPKG_Phenotype_Phenotype['kg_type'] = 'Generalised'
GPKG_Phenotype_Phenotype['kg_source'] = 'GPKG'
GPKG_Phenotype_Phenotype['species'] = 'Homo species'

GPKG_Phenotype_Phenotype.head(2)

GPKG:    16,000 rows | columns: ['head', 'relation', 'tail', 'head_type', 'relation_type', 'tail_type', 'kg_source', 'head_detail_name', 'head_id_is', 'tail_detail_name', 'tail_id_is']

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_detail_name,head_id_is,tail_detail_name,tail_id_is,kg_type,species
0,HP:0001373,Phenotype_Phenotype,HP:0012095,Phenotype,resembles,Phenotype,GPKG,Joint dislocation,HPO_ID,Multiple joint dislocation,HPO_ID,Generalised,Homo species
1,HP:0002536,Phenotype_Phenotype,HP:0009879,Phenotype,resembles,Phenotype,GPKG,Abnormal cortical gyration,HPO_ID,Simplified gyral pattern,HPO_ID,Generalised,Homo species

### 1c. TARKG

In [4]:
TARKG_Phenotype_Phenotype = pd.read_csv(PROC_DIR + 'TARKG/Phenotype_Phenotype.csv')
TARKG_Phenotype_Phenotype.columns = TARKG_Phenotype_Phenotype.columns.str.lower()
print(f"TARKG:   {len(TARKG_Phenotype_Phenotype):,} rows | columns: {list(TARKG_Phenotype_Phenotype.columns)}")
GPKG_Phenotype_Phenotype['kg_type'] = 'Generalised'
GPKG_Phenotype_Phenotype['kg_source'] = 'TARKG'
GPKG_Phenotype_Phenotype['species'] = 'Homo species'
TARKG_Phenotype_Phenotype.head(2)

TARKG:   18,416 rows | columns: ['head', 'relation', 'tail', 'head_type', 'relation_type', 'tail_type', 'kg_source', 'head_detail_name', 'tail_detail_name', 'head_id_is', 'tail_id_is', 'kg_index', 'kg', 'change']

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_index,kg,change
0,HP:0002859,Phenotype_Phenotype,HP:0030448,Phenotype,IS_A,Phenotype,TARKG,Rhabdomyosarcoma,Soft tissue sarcoma,HPO_ID,HPO_ID,OpenBioLink-4762814,OpenBioLink,0
1,HP:0010614,Phenotype_Phenotype,HP:0030448,Phenotype,IS_A,Phenotype,TARKG,Fibroma,Soft tissue sarcoma,HPO_ID,HPO_ID,OpenBioLink-4770128,OpenBioLink,0

### 1d. pheknowlator

In [5]:
pheknowlator_Phenotype_Phenotype = pd.read_csv(PROC_DIR + 'pheknowlator/Phenotype_Phenotype.csv')
pheknowlator_Phenotype_Phenotype.columns = pheknowlator_Phenotype_Phenotype.columns.str.lower()
print(f"pheknowlator:   {len(pheknowlator_Phenotype_Phenotype):,} rows | columns: {list(pheknowlator_Phenotype_Phenotype.columns)}")
pheknowlator_Phenotype_Phenotype['kg_type'] = 'Generalised'
pheknowlator_Phenotype_Phenotype['kg_source'] = 'pheknowlator'
pheknowlator_Phenotype_Phenotype['species'] = 'Homo species'
pheknowlator_Phenotype_Phenotype.head(2)

pheknowlator:   27,321 rows | columns: ['head', 'relation', 'tail', 'head_type', 'tail_type', 'head_detail_name', 'tail_detail_name', 'head_id_is', 'tail_id_is', 'kg_source']

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_source,kg_type,species
0,HP:0011353,Phenotype_Phenotype,HP:0011353,Phenotype,Phenotype,Arterial intimal fibrosis,Arterial intimal fibrosis,HPO_ID,HPO_ID,pheknowlator,Generalised,Homo species
1,HP:0009327,Phenotype_Phenotype,HP:0009334,Phenotype,Phenotype,Ivory epiphysis of the middle phalanx of the 3...,Abnormality of the epiphysis of the middle pha...,HPO_ID,HPO_ID,pheknowlator,Generalised,Homo species

## 2. Check and Fix Duplicate Columns

In [6]:
SOURCE_DFS = [
    ('PrimeKG_Phenotype_Phenotype', PrimeKG_Phenotype_Phenotype),
    ('GPKG_Phenotype_Phenotype',    GPKG_Phenotype_Phenotype),
    ('TARKG_Phenotype_Phenotype',   TARKG_Phenotype_Phenotype),
    ('pheknowlator_Phenotype_Phenotype', pheknowlator_Phenotype_Phenotype),
]

for name, df in SOURCE_DFS:
    dupes = df.columns[df.columns.duplicated(keep=False)].unique().tolist()
    if dupes:
        print(f"\n[{name}] duplicate columns: {dupes}")
        for col in dupes:
            for i, (_, s) in enumerate(df.loc[:, df.columns == col].items()):
                print(f"  '{col}' occurrence {i} → sample: {s.dropna().head(3).tolist()}")
    else:
        print(f"[{name}] ✓ no duplicates")

[PrimeKG_Phenotype_Phenotype] ✓ no duplicates
[GPKG_Phenotype_Phenotype] ✓ no duplicates
[TARKG_Phenotype_Phenotype] ✓ no duplicates
[pheknowlator_Phenotype_Phenotype] ✓ no duplicates

In [7]:
# # Edit keep='first'/'last' per DataFrame based on inspection above
# PrimeKG_Phenotype_Phenotype = PrimeKG_Phenotype_Phenotype.loc[:, ~PrimeKG_Phenotype_Phenotype.columns.duplicated(keep='first')]
# GPKG_Phenotype_Phenotype    = GPKG_Phenotype_Phenotype.loc[:,    ~GPKG_Phenotype_Phenotype.columns.duplicated(keep='first')]
# TARKG_Phenotype_Phenotype   = TARKG_Phenotype_Phenotype.loc[:,   ~TARKG_Phenotype_Phenotype.columns.duplicated(keep='first')]

# for name, df in SOURCE_DFS:
#     remaining = df.columns[df.columns.duplicated()].tolist()
#     print(f"[{name}] {'✓ clean' if not remaining else '✗ still has dupes: ' + str(remaining)}")

## 3. Align Schemas and Concatenate

In [8]:
CONCAT_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

df_list = []
for name, df in SOURCE_DFS:
    tmp = df.copy()
    for col in CONCAT_COLS:
        if col not in tmp.columns:
            tmp[col] = pd.NA
    df_list.append(tmp[CONCAT_COLS])

final_df = pd.concat(df_list, ignore_index=True)
print(f"Combined: {len(final_df):,} rows")
final_df.head(2)

Combined: 80,473 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,HP:0000002,Phenotype_Phenotype,HP:0001507,Phenotype,parent-child,Phenotype,PrimeKG,HPO_ID,HPO_ID,Abnormality of body height,Growth abnormality,Generalised,Homo species
1,HP:0000003,Phenotype_Phenotype,HP:0000107,Phenotype,parent-child,Phenotype,PrimeKG,HPO_ID,HPO_ID,Multicystic kidney dysplasia,Renal cyst,Generalised,Homo species

## 4. Standardise Fixed-Value Columns

In [9]:
final_df['head_type'] = 'Phenotype'
final_df['tail_type'] = 'Phenotype'
final_df['relation']  = 'Phenotype_Phenotype'
final_df['head_id_is'] = 'HPO'
final_df['tail_id_is'] = 'HPO'

print("Unique relation:",   set(final_df['relation']))
print("Unique head_type:",  set(final_df['head_type']))
print("Unique tail_type:",  set(final_df['tail_type']))
print("Unique kg_source:",  set(final_df['kg_source']))

Unique relation: {'Phenotype_Phenotype'}
Unique head_type: {'Phenotype'}
Unique tail_type: {'Phenotype'}
Unique kg_source: {'TARKG', 'pheknowlator', 'PrimeKG'}

## 5. Deduplicate and Add Schema Columns

Group by `(head, relation, tail)` and collapse `kg_source` with `::` separator.

In [11]:
GROUP_COLS = ['head', 'relation', 'tail']

def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

print(f"Before deduplication: {len(final_df):,} rows")
final_df_dedup = final_df.groupby(GROUP_COLS, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':         merge_sources,
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'kg_type': merge_sources,
    'species': 'first',
    
})


final_df_dedup = final_df_dedup[REQUIRED_COLS]

print(f"After deduplication: {len(final_df_dedup):,} rows")
final_df_dedup.head()

Before deduplication: 80,473 rows
After deduplication: 43,393 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,HP:0000002,Phenotype_Phenotype,HP:0000002,Phenotype,None,Phenotype,pheknowlator,HPO,HPO,Abnormality of body height,Abnormality of body height,generalised,Human
1,HP:0000002,Phenotype_Phenotype,HP:0000098,Phenotype,resembles,Phenotype,TARKG,HPO,HPO,Abnormality of body height,Tall stature,generalised,Human
2,HP:0000002,Phenotype_Phenotype,HP:0001507,Phenotype,parent-child,Phenotype,PrimeKG::TARKG::pheknowlator,HPO,HPO,Abnormality of body height,Growth abnormality,generalised,Human
3,HP:0000002,Phenotype_Phenotype,HP:0004322,Phenotype,resembles,Phenotype,TARKG,HPO,HPO,Abnormality of body height,Short stature,generalised,Human
4,HP:0000003,Phenotype_Phenotype,HP:0000003,Phenotype,None,Phenotype,pheknowlator,HPO,HPO,Multicystic kidney dysplasia,Multicystic kidney dysplasia,generalised,Human

## 6. QC — NaN Check

In [12]:
def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(final_df_dedup)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type          8991                   0            8991
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

## 7. Save Output

In [5]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 43,393 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/PHENOTYPE_PHENOTYPE/ALL_PHENOTYPE_PHENOTYPE.csv

In [6]:
# final_df_dedup = pd.read_csv('/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/PHENOTYPE_PHENOTYPE/ALL_PHENOTYPE_PHENOTYPE.csv')
# final_df_dedup['kg_type']= "Generalised"
# final_df_dedup