In [4]:
import os
import pandas as pd
import numpy as np

In [2]:
# ── Base directories ──────────────────────────────────────────────────────────
BASE_DIR   = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR   = BASE_DIR + 'processed_data/'
DB_DIR     = BASE_DIR + 'data_collection/databases_for_mapping/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/CHEMICAL_INHIBITS_BIOLOGICALPROCESS/ALL_CHEMICAL_INHIBITS_BIOLOGICALPROCESS_Human.parquet'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

In [3]:
# AgeXtend
AgeXtend_Human_Chem_Inhibits_BioPro_1 = pd.read_csv(PROC_DIR + 'agextend_processed/AgeXtend_Human_ChemicalEntity_Inhibits_BiologicalProcess.csv')
AgeXtend_Human_Chem_Inhibits_BioPro_1.columns = AgeXtend_Human_Chem_Inhibits_BioPro_1.columns.str.lower()
AgeXtend_Human_Chem_Inhibits_BioPro_1.rename(columns={'relation_source': 'kg_source'}, inplace=True)
AgeXtend_Human_Chem_Inhibits_BioPro_1['kg_type'] = 'Aging'
AgeXtend_Human_Chem_Inhibits_BioPro_1['kg_source'] = 'AgeXtend'
AgeXtend_Human_Chem_Inhibits_BioPro_1['species'] = 'Homo sapiens'
AgeXtend_Human_Chem_Inhibits_BioPro_1

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,tail_detail_name,kg_source,species,data_source,anti_aging_status,anti_aging_prob,kg_type
0,73544,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R,3S,4S,5R)-2,5-bis(hydroxymethyl)oxolane-3,...",C([C@@H]1[C@H]([C@@H]([C@H](O1)CO)O)O)O,aging,AgeXtend,Homo sapiens,https://doi.org/10.1186/s13062-024-00455-4,1,0.909696,Aging
1,163659,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2S,3S)-2-[(2S,4R,5R,6R)-4-[(2S,4R,5S,6R)-4-[(...",C[C@@H]1[C@H]([C@@H](C[C@@H](O1)O[C@@H]2C[C@@H...,aging,AgeXtend,Homo sapiens,https://doi.org/10.1186/s13062-024-00455-4,1,0.915105,Aging
2,138402875,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,2-oxidoacetate;platinum(2+),C(C(=O)[O-])[O-].[Pt+2],aging,AgeXtend,Homo sapiens,https://doi.org/10.1186/s13062-024-00455-4,1,0.856031,Aging
3,135565785,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,2-amino-N-[7-methoxy-8-(3-morpholin-4-ylpropox...,COC1=C(C=CC2=C3NCCN3C(=NC(=O)C4=CN=C(N=C4)N)N=...,aging,AgeXtend,Homo sapiens,https://doi.org/10.1186/s13062-024-00455-4,1,0.773343,Aging
4,10496,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"4,7-dioxadispiro[4.0.46.25]dodeca-1,9-diene-3,...",C1CC2(C13C=CC(=O)O3)C=CC(=O)O2,aging,AgeXtend,Homo sapiens,https://doi.org/10.1016/j.archger.2023.105255,1,0.788277,Aging
5,155802404,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,2-[[(5R)-3-(carboxymethylimino)-5-hydroxy-5-(h...,COC1=C(C[C@@](CC1=NCC(=O)O)(CO)O)NC(CO)C(=O)O,aging,AgeXtend,Homo sapiens,https://doi.org/10.3390/md12105174,0,0.276886,Aging
6,14444485,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,2-[[5-hydroxy-5-(hydroxymethyl)-2-methoxy-3-ox...,COC1=C(CC(CC1=O)(CO)O)NCC(=O)O,aging,AgeXtend,Homo sapiens,https://doi.org/10.3390/md12105174,0,0.446332,Aging
7,5281544,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"methyl (4S,5E,6S)-4-[2-[2-(3,4-dihydroxyphenyl...",C/C=C/1\[C@@H](C(=CO[C@H]1O[C@H]2[C@@H]([C@H](...,aging,AgeXtend,Homo sapiens,https://doi.org/10.1089/rej.2006.0513,1,0.910744,Aging
8,5320315,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"5,7-dihydroxy-6-methoxy-2-phenylchromen-4-one",COC1=C(C2=C(C=C1O)OC(=CC2=O)C3=CC=CC=C3)O,aging,AgeXtend,Homo sapiens,https://doi.org/10.1016/j.biopha.2023.116110,1,0.912800,Aging
9,5281227,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"2,4,4-trimethyl-3-[(1E,3E,5E,7E,9E,11E,13E,15E...",CC1=C(C(CCC1=O)(C)C)/C=C/C(=C/C=C/C(=C/C=C/C=C...,aging,AgeXtend,Homo sapiens,https://www.sciencedirect.com/science/article/...,1,0.869158,Aging
10,222284,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(3S,8S,9S,10R,13R,14S,17R)-17-[(2R,5R)-5-ethyl...",CC[C@H](CC[C@@H](C)[C@H]1CC[C@@H]2[C@@]1(CC[C@...,aging,AgeXtend,Homo sapiens,https://doi.org/10.1590/0001-3765201920181088,1,0.903926,Aging
11,13387679,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"3-(3-formyl-2,4-dihydroxy-6-methylphenoxy)carb...",CC1=CC(=C(C(=C1OC(=O)C2=C(C(=C(C=C2C)OC)C(=O)O...,aging,AgeXtend,Homo sapiens,https://doi.org/10.1590/0001-3765201920181088,1,0.871494,Aging
12,22311,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,1-methyl-4-prop-1-en-2-ylcyclohexene,CC1=CCC(CC1)C(=C)C,aging,AgeXtend,Homo sapiens,https://doi.org/10.1002/tox.23646,1,0.819916,Aging
13,5351619,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2S)-3-(2-sulfanylidene-1,3-dihydroimidazol-4-...",C[N+](C)(C)[C@@H](CC1=CNC(=S)N1)C(=O)[O-],aging,AgeXtend,Homo sapiens,https://www.sciencedirect.com/science/article/...,0,0.231059,Aging
14,139584912,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(E,4S)-4-[[(2Z,4E)-hexa-2,4-dienoyl]amino]-2-m...",C/C=C/C=C\C(=O)N[C@@H](C)/C=C(\C)/C(=O)N,aging,AgeXtend,Homo sapiens,https://pubmed.ncbi.nlm.nih.gov/32927886/,1,0.837722,Aging

In [4]:
# AgeXtend ALL
AgeXtend_Human_Chem_Inhibits_BioPro_2 = pd.read_csv(PROC_DIR + 'agextend_processed/CHEM_BioP_Hallmarks/All_Chemical_Inhibits_BioPro(Hallmarks).csv')
AgeXtend_Human_Chem_Inhibits_BioPro_2.columns = AgeXtend_Human_Chem_Inhibits_BioPro_2.columns.str.lower()
AgeXtend_Human_Chem_Inhibits_BioPro_2.rename(columns={'relation_source': 'kg_source'}, inplace=True)
AgeXtend_Human_Chem_Inhibits_BioPro_2['kg_type'] = 'Aging'
AgeXtend_Human_Chem_Inhibits_BioPro_2['kg_source'] = 'AgeXtend'
AgeXtend_Human_Chem_Inhibits_BioPro_2['species'] = 'Homo sapiens'
AgeXtend_Human_Chem_Inhibits_BioPro_2

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,tail_detail_name,kg_source,species,data_source,anti_aging_status,anti_aging_prob,head_id_is,tail_id_is,source,name/title/synonyms,kg_type
0,5319022,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(3Z)-3-butylidene-4,5-dihydro-2-benzofuran-1-one",CCC/C=C\1/C2=C(C=CCC2)C(=O)O1,obsolete aging,AgeXtend,Homo sapiens,https://doi.org/10.1016/j.phymed.2023.155216,1.0,0.914950,NaN,NaN,NaN,NaN,Aging
1,5280443,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"5,7-dihydroxy-2-(4-hydroxyphenyl)chromen-4-one",C1=CC(=CC=C1C2=CC(=O)C3=C(C=C(C=C3O2)O)O)O,obsolete aging,AgeXtend,Homo sapiens,https://doi.org/10.1016/j.mad.2023.111889,1.0,0.920326,NaN,NaN,NaN,NaN,Aging
2,6072,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"1-[2,4-dihydroxy-6-[(2S,3R,4S,5S,6R)-3,4,5-tri...",C1=CC(=CC=C1CCC(=O)C2=C(C=C(C=C2O[C@H]3[C@@H](...,obsolete aging,AgeXtend,Homo sapiens,https://doi.org/10.1016/j.exger.2022.111769,1.0,0.904648,NaN,NaN,NaN,NaN,Aging
3,73554535,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R,6R)-6-[(7S,10S,13R,14R,15S,17R)-7,15-dihyd...",C[C@H](CC(=O)C[C@@H](C)C(=O)O)[C@H]1C[C@@H]([C...,obsolete aging,AgeXtend,Homo sapiens,https://doi.org/10.1111/acel.13686,1.0,0.824924,NaN,NaN,NaN,NaN,Aging
4,4034,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,1-[(4-chlorophenyl)-phenylmethyl]-4-[(3-methyl...,CC1=CC(=CC=C1)CN2CCN(CC2)C(C3=CC=CC=C3)C4=CC=C...,obsolete aging,AgeXtend,Homo sapiens,https://doi.org/10.1007/s11357-023-01011-0,1.0,0.928011,NaN,NaN,NaN,NaN,Aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6823,16666638,ChemicalEntity_Inhibits_BiologicalProcess,GO:1111113,ChemicalEntity,BiologicalProcess,2-ethoxy-5-[(Z)-prop-1-enyl]phenol,CCOC1=C(C=C(C=C1)/C=C\C)O,epigenetic alterations,AgeXtend,Homo sapiens,NaN,NaN,NaN,Pubchem,Quick_GO,Tox21-ActiveAntagonist-HDAC,NaN,Aging
6824,23661981,ChemicalEntity_Inhibits_BiologicalProcess,GO:1111113,ChemicalEntity,BiologicalProcess,"sodium;9,10-dioxoanthracene-2-sulfonate",C1=CC=C2C(=C1)C(=O)C3=C(C2=O)C=C(C=C3)S(=O)(=O...,epigenetic alterations,AgeXtend,Homo sapiens,NaN,NaN,NaN,Pubchem,Quick_GO,Tox21-ActiveAntagonist-HDAC,NaN,Aging
6825,23677829,ChemicalEntity_Inhibits_BiologicalProcess,GO:1111113,ChemicalEntity,BiologicalProcess,sodium;2-[1-methyl-5-(4-methylbenzoyl)pyrrol-2...,CC1=CC=C(C=C1)C(=O)C2=CC=C(N2C)CC(=O)[O-].O.O....,epigenetic alterations,AgeXtend,Homo sapiens,NaN,NaN,NaN,Pubchem,Quick_GO,Tox21-ActiveAntagonist-HDAC,NaN,Aging
6826,57351929,ChemicalEntity_Inhibits_BiologicalProcess,GO:1111113,ChemicalEntity,BiologicalProcess,"sodium;4-[2-[5-[(2,4-dimethylphenyl)hydrazinyl...",CC1=CC(=C(C=C1)NN=C2C(=O)C=CC(=NNC3=CC=C(C=C3)...,epigenetic alterations,AgeXtend,Homo sapiens,NaN,NaN,NaN,Pubchem,Quick_GO,Tox21-ActiveAntagonist-HDAC,NaN,Aging
6827,60196270,ChemicalEntity_Inhibits_BiologicalProcess,GO:1111113,ChemicalEntity,BiologicalProcess,"(2R,3S,4R,5S)-6-(methylamino)hexane-1,2,3,4,5-...",CC1=C(C=CC=C1NC2=C(C=CC=N2)C(=O)O)C(F)(F)F.CNC...,epigenetic alterations,AgeXtend,Homo sapiens,NaN,NaN,NaN,Pubchem,Quick_GO,Tox21-ActiveAntagonist-HDAC,NaN,Aging

In [5]:
# set(AgeXtend_Human_Chem_Inhibits_BioPro_2['relation'])

In [6]:
# AgingAtlas
AgingAtlas_Human_Chem_Inhibits_BioPro_1 = pd.read_csv(PROC_DIR + 'agingatlas/Human/AgingAtlas_Human_Chemical_Inhibit_BiologicalProcess_Geroprotectors.csv')
AgingAtlas_Human_Chem_Inhibits_BioPro_1.columns = AgingAtlas_Human_Chem_Inhibits_BioPro_1.columns.str.lower()
AgingAtlas_Human_Chem_Inhibits_BioPro_1.rename(columns={'relation_source': 'kg_source'}, inplace=True)
AgingAtlas_Human_Chem_Inhibits_BioPro_1['kg_type'] = 'Aging'
AgingAtlas_Human_Chem_Inhibits_BioPro_1['kg_source'] = 'AgingAtlas'
AgingAtlas_Human_Chem_Inhibits_BioPro_1['species'] = 'Homo sapiens'
AgingAtlas_Human_Chem_Inhibits_BioPro_1

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,kg_source,species,head_alt_name,pmid,rnaseq,data_type,tail_detail_name,kg_type
0,17751002,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(3S,4R,5S)-3,4,5,6-tetrahydroxyhexanal",C(C=O)[C@@H]([C@H]([C@H](CO)O)O)O,AgingAtlas,Homo sapiens,2-deoxy-D-glucose,21604001,Not Available,Causative,aging,Aging
1,439224,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-(3-aminopropanoylamino)-3-(1H-imidazol-...,C1=C(NC=N1)C[C@@H](C(=O)O)NC(=O)CCN,AgingAtlas,Homo sapiens,L-carnosine,8187813,Not Available,Causative,aging,Aging
2,24757913,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"S-[(E)-4-[(5R,8S,11S)-5-methyl-6,9,13-trioxo-8...",CCCCCCCC(=O)SCC/C=C/[C@@H]1CC(=O)NCC2=NC(=CS2)...,AgingAtlas,Homo sapiens,Largazole,23564418,Not Available,Causative,aging,Aging
3,4091,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"3-(diaminomethylidene)-1,1-dimethylguanidine",CN(C)C(=N)N=C(N)N,AgingAtlas,Homo sapiens,Metformin,31559522,Not Available,Causative,aging,Aging
4,6099,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,[7-(dimethylamino)phenothiazin-3-ylidene]-dime...,CN(C)C1=CC2=C(C=C1)N=C3C=CC(=[N+](C)C)C=C3S2.[...,AgingAtlas,Homo sapiens,Methylene blue,28559565,Not Available,Causative,aging,Aging
5,24978538,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"4-[4-[[2-(4-chlorophenyl)-5,5-dimethylcyclohex...",CC1(CCC(=C(C1)CN2CCN(CC2)C3=CC=C(C=C3)C(=O)NS(...,AgingAtlas,Homo sapiens,Navitoclax,29669575,Not Available,Causative,aging,Aging
6,5280343,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"2-(3,4-dihydroxyphenyl)-3,5,7-trihydroxychrome...",C1=CC(=C(C=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O)O)O,AgingAtlas,Homo sapiens,Quercetin,30069858,view,Causative,aging,Aging
7,444795,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2E,4E,6E,8E)-3,7-dimethyl-9-(2,6,6-trimethylc...",CC1=C(C(CCC1)(C)C)/C=C/C(=C/C=C/C(=C/C(=O)O)/C)/C,AgingAtlas,Homo sapiens,Retinoic acid,14654966,Not Available,Causative,aging,Aging
8,5350,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,1-isothiocyanato-4-methylsulfinylbutane,CS(=O)CCCCN=C=S,AgingAtlas,Homo sapiens,Sulforaphane,30595796,Not Available,Causative,aging,Aging
9,54670067,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2-[(1S)-1,2-dihydroxyethyl]-3,4-dihydroxy...",C([C@@H]([C@@H]1C(=C(C(=O)O1)O)O)O)O,AgingAtlas,Homo sapiens,Vitamin C,27271327,view,Causative,aging,Aging

In [7]:
SOURCE_DFS = [
    ('AgeXtend_Human_Chem_Inhibits_BioPro_1', AgeXtend_Human_Chem_Inhibits_BioPro_1),
    ('AgeXtend_Human_Chem_Inhibits_BioPro_2', AgeXtend_Human_Chem_Inhibits_BioPro_2),
    ('AgingAtlas_Human_Chem_Inhibits_BioPro_1', AgingAtlas_Human_Chem_Inhibits_BioPro_1),
]

for name, df in SOURCE_DFS:
    dupes = df.columns[df.columns.duplicated(keep=False)].unique().tolist()
    if dupes:
        print(f'\n[{name}] duplicate columns: {dupes}')
        for col in dupes:
            for i, (_, s) in enumerate(df.loc[:, df.columns == col].items()):
                print(f"  '{col}' occurrence {i} → sample: {s.dropna().head(3).tolist()}")
    else:
        print(f'[{name}] ✓ no duplicates')

[AgeXtend_Human_Chem_Inhibits_BioPro_1] ✓ no duplicates
[AgeXtend_Human_Chem_Inhibits_BioPro_2] ✓ no duplicates
[AgingAtlas_Human_Chem_Inhibits_BioPro_1] ✓ no duplicates

In [8]:
CONCAT_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

df_list = []
for name, df in SOURCE_DFS:
    tmp = df.loc[:, ~df.columns.duplicated()].copy()
    for col in CONCAT_COLS:
        if col not in tmp.columns:
            tmp[col] = pd.NA
    df_list.append(tmp[CONCAT_COLS])

final_df = pd.concat(df_list, ignore_index=True)
print(f'Combined: {len(final_df):,} rows')
final_df

Combined: 6,853 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,73544,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,NaN,BiologicalProcess,AgeXtend,NaN,NaN,"(2R,3S,4S,5R)-2,5-bis(hydroxymethyl)oxolane-3,...",aging,Aging,Homo sapiens
1,163659,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,NaN,BiologicalProcess,AgeXtend,NaN,NaN,"(2S,3S)-2-[(2S,4R,5R,6R)-4-[(2S,4R,5S,6R)-4-[(...",aging,Aging,Homo sapiens
2,138402875,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,NaN,BiologicalProcess,AgeXtend,NaN,NaN,2-oxidoacetate;platinum(2+),aging,Aging,Homo sapiens
3,135565785,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,NaN,BiologicalProcess,AgeXtend,NaN,NaN,2-amino-N-[7-methoxy-8-(3-morpholin-4-ylpropox...,aging,Aging,Homo sapiens
4,10496,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,NaN,BiologicalProcess,AgeXtend,NaN,NaN,"4,7-dioxadispiro[4.0.46.25]dodeca-1,9-diene-3,...",aging,Aging,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6848,24978538,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,NaN,BiologicalProcess,AgingAtlas,NaN,NaN,"4-[4-[[2-(4-chlorophenyl)-5,5-dimethylcyclohex...",aging,Aging,Homo sapiens
6849,5280343,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,NaN,BiologicalProcess,AgingAtlas,NaN,NaN,"2-(3,4-dihydroxyphenyl)-3,5,7-trihydroxychrome...",aging,Aging,Homo sapiens
6850,444795,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,NaN,BiologicalProcess,AgingAtlas,NaN,NaN,"(2E,4E,6E,8E)-3,7-dimethyl-9-(2,6,6-trimethylc...",aging,Aging,Homo sapiens
6851,5350,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,NaN,BiologicalProcess,AgingAtlas,NaN,NaN,1-isothiocyanato-4-methylsulfinylbutane,aging,Aging,Homo sapiens
6852,54670067,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,NaN,BiologicalProcess,AgingAtlas,NaN,NaN,"(2R)-2-[(1S)-1,2-dihydroxyethyl]-3,4-dihydroxy...",aging,Aging,Homo sapiens

In [9]:
GROUP_COLS = ['head', 'relation', 'tail']

def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

final_df_dedup = final_df.groupby(GROUP_COLS, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':         merge_sources,
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'kg_type': merge_sources,
    'species': 'first',
})
print(f'After deduplication: {len(final_df_dedup):,} rows')
final_df_dedup = final_df_dedup[REQUIRED_COLS]
final_df_dedup.head()

After deduplication: 6,838 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,237,ChemicalEntity_Inhibits_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"4-N-(6-chloro-2-methoxyacridin-9-yl)-1-N,1-N-d...",deregulated nutrient sensing,Aging,Homo sapiens
1,402,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,None,None,sulfane,obsolete aging,Aging,Homo sapiens
2,403,ChemicalEntity_Inhibits_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,4-aminophenol,epigenetic alterations,Aging,Homo sapiens
3,980,ChemicalEntity_Inhibits_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,4-nitrophenol,epigenetic alterations,Aging,Homo sapiens
4,1318,ChemicalEntity_Inhibits_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"1,10-phenanthroline",epigenetic alterations,Aging,Homo sapiens

In [10]:
def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(final_df_dedup)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type          6838                   0            6838
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is               79                   0              79
tail_id_is               79                   0              79
head_detail_name          2                   0               2
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

In [11]:
final_df_dedup['head_id_is'] = 'Pubchem'
final_df_dedup['tail_id_is'] = 'Quick_GO'
nan_summary(final_df_dedup)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type          6838                   0            6838
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          2                   0               2
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

In [12]:
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
final_df_dedup.to_parquet(OUT_PATH, index=False)
print(f'Saved {len(final_df_dedup):,} rows → {OUT_PATH}')

Saved 6,838 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/CHEMICAL_INHIBITS_BIOLOGICALPROCESS/ALL_CHEMICAL_INHIBITS_BIOLOGICALPROCESS_Human.parquet

In [5]:
f = pd.read_parquet('/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/CHEMICAL_INHIBITS_BIOLOGICALPROCESS/ALL_CHEMICAL_INHIBITS_BIOLOGICALPROCESS_Human.parquet')
f

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species,head_species
0,237,ChemicalEntity_Inhibits_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"4-N-(6-chloro-2-methoxyacridin-9-yl)-1-N,1-N-d...",deregulated nutrient sensing,Aging,Homo sapiens,Homo sapiens
1,402,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,sulfane,obsolete aging,Aging,Homo sapiens,Homo sapiens
2,403,ChemicalEntity_Inhibits_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,4-aminophenol,epigenetic alterations,Aging,Homo sapiens,Homo sapiens
3,980,ChemicalEntity_Inhibits_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,4-nitrophenol,epigenetic alterations,Aging,Homo sapiens,Homo sapiens
4,1318,ChemicalEntity_Inhibits_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"1,10-phenanthroline",epigenetic alterations,Aging,Homo sapiens,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6833,156588472,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"2-[(4R,5S,7R,8R,11S,12S,13R)-13,17,18-trihydro...",obsolete aging,Aging,Homo sapiens,Homo sapiens
6834,162642741,ChemicalEntity_Inhibits_BiologicalProcess,GO:0090398,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"[(2R,3S,4S,5R,6S)-3,4,5-triacetyloxy-6-[4-[[1-...",cellular senescence,Aging,Homo sapiens,Homo sapiens
6835,168265116,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"(2S,3R,4S,5S,6R)-2-[[(2S,4S,5S,10S)-5-hydroxy-...",obsolete aging,Aging,Homo sapiens,Homo sapiens
6836,168312228,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,3-[3-[N-[(4-bromophenyl)methoxy]-C-methylcarbo...,obsolete aging,Aging,Homo sapiens,Homo sapiens
6837,169553329,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"methyl (2R,6R)-2-methyl-4-oxo-6-[(10S,13R,14R,...",obsolete aging,Aging,Homo sapiens,Homo sapiens

In [6]:
set(f['kg_type'])

{'Aging'}