In [1]:
import os
import pandas as pd
import numpy as np

BASE_DIR   = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR   = BASE_DIR + 'processed_data/'
DB_DIR     = BASE_DIR + 'data_collection/databases_for_mapping/'

OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/PMID_CHEMICAL/ALL_PMID_CHEMICAL.parquet'

REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

## 2. Load KG Sources

#### CKG

In [3]:
CKG = pd.read_csv(PROC_DIR + 'CKG/File_43_PMID_CHEMICAL_CKG.csv')
CKG

,Head,Relation,Tail,Head_type,Tail_type,KG_Source,Tail_ID_IS,Tail_detail_name,Head_ID_IS
0,PMID:20398344,MENTIONED_IN_PUBLICATION,7045767,PMID,Drug,CKG,Pubchem,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,PubmedID
1,PMID:19399243,MENTIONED_IN_PUBLICATION,7045767,PMID,Drug,CKG,Pubchem,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,PubmedID
2,PMID:19783937,MENTIONED_IN_PUBLICATION,7045767,PMID,Drug,CKG,Pubchem,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,PubmedID
3,PMID:18555826,MENTIONED_IN_PUBLICATION,7045767,PMID,Drug,CKG,Pubchem,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,PubmedID
4,PMID:19300586,MENTIONED_IN_PUBLICATION,7045767,PMID,Drug,CKG,Pubchem,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,PubmedID
...,...,...,...,...,...,...,...,...,...
42809921,PMID:37652915,MENTIONED_IN_PUBLICATION,17754356,PMID,Drug,CKG,Pubchem,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",PubmedID
42809922,PMID:41260918,MENTIONED_IN_PUBLICATION,17754356,PMID,Drug,CKG,Pubchem,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",PubmedID
42809923,PMID:21980712,MENTIONED_IN_PUBLICATION,17754356,PMID,Drug,CKG,Pubchem,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",PubmedID
42809924,PMID:21701441,MENTIONED_IN_PUBLICATION,17754356,PMID,Drug,CKG,Pubchem,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",PubmedID
42809925,PMID:2055987,MENTIONED_IN_PUBLICATION,17754356,PMID,Drug,CKG,Pubchem,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",PubmedID

In [4]:
CKG.columns = CKG.columns.str.lower()
CKG['head_detail_name'] = ''
CKG['relation'] = 'PMID_ChemicalEntity'
CKG['tail_type'] = 'ChemicalEntity'
CKG['kg_type'] = 'Generalised'
CKG['kg_source'] = 'CKG'
CKG['species'] = 'Homo species'
CKG

,head,relation,tail,head_type,tail_type,kg_source,tail_id_is,tail_detail_name,head_id_is,head_detail_name,kg_type,species
0,PMID:20398344,PMID_ChemicalEntity,7045767,PMID,ChemicalEntity,CKG,Pubchem,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,PubmedID,,Generalised,Homo species
1,PMID:19399243,PMID_ChemicalEntity,7045767,PMID,ChemicalEntity,CKG,Pubchem,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,PubmedID,,Generalised,Homo species
2,PMID:19783937,PMID_ChemicalEntity,7045767,PMID,ChemicalEntity,CKG,Pubchem,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,PubmedID,,Generalised,Homo species
3,PMID:18555826,PMID_ChemicalEntity,7045767,PMID,ChemicalEntity,CKG,Pubchem,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,PubmedID,,Generalised,Homo species
4,PMID:19300586,PMID_ChemicalEntity,7045767,PMID,ChemicalEntity,CKG,Pubchem,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,PubmedID,,Generalised,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...
42809921,PMID:37652915,PMID_ChemicalEntity,17754356,PMID,ChemicalEntity,CKG,Pubchem,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",PubmedID,,Generalised,Homo species
42809922,PMID:41260918,PMID_ChemicalEntity,17754356,PMID,ChemicalEntity,CKG,Pubchem,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",PubmedID,,Generalised,Homo species
42809923,PMID:21980712,PMID_ChemicalEntity,17754356,PMID,ChemicalEntity,CKG,Pubchem,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",PubmedID,,Generalised,Homo species
42809924,PMID:21701441,PMID_ChemicalEntity,17754356,PMID,ChemicalEntity,CKG,Pubchem,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",PubmedID,,Generalised,Homo species
42809925,PMID:2055987,PMID_ChemicalEntity,17754356,PMID,ChemicalEntity,CKG,Pubchem,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",PubmedID,,Generalised,Homo species

In [5]:
SOURCE_DFS = [
              ('CKG', CKG)
             ]
for name, df in SOURCE_DFS:
    dupes = df.columns[df.columns.duplicated(keep=False)].unique().tolist()
    print(f"[{name}] {'duplicate columns: ' + str(dupes) if dupes else '✓ no duplicates'}")

[CKG] ✓ no duplicates

In [6]:
CONCAT_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name','kg_type', 'species'
]

df_list = []
for name, df in SOURCE_DFS:
    tmp = df.loc[:, ~df.columns.duplicated()].copy()
    for col in CONCAT_COLS:
        if col not in tmp.columns:
            tmp[col] = pd.NA
    df_list.append(tmp[CONCAT_COLS])

final_df = pd.concat(df_list, ignore_index=True)
print(f"Combined: {len(final_df):,} rows")
final_df

Combined: 42,809,926 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,PMID:20398344,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
1,PMID:19399243,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
2,PMID:19783937,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
3,PMID:18555826,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
4,PMID:19300586,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42809921,PMID:37652915,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species
42809922,PMID:41260918,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species
42809923,PMID:21980712,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species
42809924,PMID:21701441,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species
42809925,PMID:2055987,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species

In [7]:
final_df = final_df[~final_df['tail_detail_name'].isna()]
final_df

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,PMID:20398344,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
1,PMID:19399243,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
2,PMID:19783937,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
3,PMID:18555826,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
4,PMID:19300586,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42809921,PMID:37652915,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species
42809922,PMID:41260918,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species
42809923,PMID:21980712,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species
42809924,PMID:21701441,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species
42809925,PMID:2055987,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species

In [8]:
import pandas as pd
import numpy as np

# Vectorized hash using numpy — avoids Python string ops entirely
keys = (
    pd.util.hash_array(final_df['head'].to_numpy()) ^
    pd.util.hash_array(final_df['relation'].to_numpy()) * 2654435761 ^
    pd.util.hash_array(final_df['tail'].to_numpy()) * 40503
)

# Keep first occurrence of each hash
mask = ~pd.Series(keys).duplicated(keep='first').to_numpy()
final_df = final_df.iloc[mask].reset_index(drop=True)

print(f"After dedup: {len(final_df):,} rows")
final_df

After dedup: 42,795,681 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,PMID:20398344,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
1,PMID:19399243,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
2,PMID:19783937,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
3,PMID:18555826,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
4,PMID:19300586,PMID_ChemicalEntity,7045767,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Generalised,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42795676,PMID:37652915,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species
42795677,PMID:41260918,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species
42795678,PMID:21980712,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species
42795679,PMID:21701441,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species
42795680,PMID:2055987,PMID_ChemicalEntity,17754356,PMID,<NA>,ChemicalEntity,CKG,PubmedID,Pubchem,,"(1S,2S,5R,7S,9S,10S,14R,15S,19S)-15-[(2R,5S,6R...",Generalised,Homo species

In [9]:
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
final_df.to_parquet(OUT_PATH, index=False)
print(f"Saved {len(final_df):,} rows → {OUT_PATH}")

Saved 42,795,681 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/PMID_CHEMICAL/ALL_PMID_CHEMICAL.parquet

In [10]:
#