In [1]:
import os
import re
import pandas as pd
import numpy as np

In [2]:
# ── Base directories ──────────────────────────────────────────────────────────
BASE_DIR   = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR   = BASE_DIR + 'processed_data/'
DB_DIR     = BASE_DIR + 'data_collection/databases_for_mapping/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/GENE_INHIBITS_BIOLOGICALPROCESS/ALL_GENE_INHIBITS_BIOLOGICALPROCESS.parquet'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

# Cellage

In [3]:
# CellAge
CellAge_Human_Gene_Inhibits_BioPro_1 = pd.read_csv(PROC_DIR + 'cellage/CellAge_Gene_Inhibits_BioPro_human.csv')
CellAge_Human_Gene_Inhibits_BioPro_1.columns = CellAge_Human_Gene_Inhibits_BioPro_1.columns.str.lower()
CellAge_Human_Gene_Inhibits_BioPro_1.rename(columns={'Relation_Source': 'kg_source'}, inplace=True)
CellAge_Human_Gene_Inhibits_BioPro_1['kg_type'] = 'Aging'
CellAge_Human_Gene_Inhibits_BioPro_1['species'] = 'Homo species'
CellAge_Human_Gene_Inhibits_BioPro_1['kg_source'] = 'CellAge'
CellAge_Human_Gene_Inhibits_BioPro_1

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,relation_source,species,head_id_is,tail_id_is,data_type,cancer cell,kg_type,kg_source
0,ABCC6,Gene_Inhibits_BiologicalProcess,GO:0090398,Gene,BiologicalProcess,ATP binding cassette subfamily C member 6,cellular senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,Yes,Aging,CellAge
1,ACER2,Gene_Inhibits_BiologicalProcess,GO:0090399,Gene,BiologicalProcess,alkaline ceramidase 2,replicative senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,Yes,Aging,CellAge
2,ACER2,Gene_Inhibits_BiologicalProcess,GO:0090400,Gene,BiologicalProcess,alkaline ceramidase 2,stress-induced premature senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,Yes,Aging,CellAge
3,ACLY,Gene_Inhibits_BiologicalProcess,GO:0090398,Gene,BiologicalProcess,ATP citrate lyase,cellular senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,No,Aging,CellAge
4,AGO2,Gene_Inhibits_BiologicalProcess,GO:0090402,Gene,BiologicalProcess,argonaute RISC catalytic component 2,oncogene-induced cell senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,No,Aging,CellAge
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,ZMPSTE24,Gene_Inhibits_BiologicalProcess,GO:0090399,Gene,BiologicalProcess,zinc metallopeptidase STE24,replicative senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,No,Aging,CellAge
506,ZMYND11,Gene_Inhibits_BiologicalProcess,GO:0090398,Gene,BiologicalProcess,zinc finger MYND-type containing 11,cellular senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,No,Aging,CellAge
507,ZNF148,Gene_Inhibits_BiologicalProcess,GO:0090398,Gene,BiologicalProcess,zinc finger protein 148,cellular senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,Yes,Aging,CellAge
508,ZNF207,Gene_Inhibits_BiologicalProcess,GO:0090398,Gene,BiologicalProcess,zinc finger protein 207,cellular senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,Yes,Aging,CellAge
509,ZNF217,Gene_Inhibits_BiologicalProcess,GO:0090399,Gene,BiologicalProcess,zinc finger protein 217,replicative senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,No,Aging,CellAge

###  aging bank

In [4]:

agingbank_geneInhibit_BiologicalProcess = pd.read_csv(PROC_DIR + 'agingbank/Human_AgingbankGene_inhibits_BioPro.csv')
agingbank_geneInhibit_BiologicalProcess.columns = agingbank_geneInhibit_BiologicalProcess.columns.str.lower()
agingbank_geneInhibit_BiologicalProcess.rename(columns={'Relation_Source': 'kg_source'}, inplace=True)
agingbank_geneInhibit_BiologicalProcess['kg_type'] = 'Aging'
agingbank_geneInhibit_BiologicalProcess['species'] = 'Homo species'
agingbank_geneInhibit_BiologicalProcess['relation'] = 'Gene_Inhibits_BiologicalProcess'

agingbank_geneInhibit_BiologicalProcess['kg_source'] = 'AgingBank'
agingbank_geneInhibit_BiologicalProcess

,head,relation,tail,head_type,tail_type,kg_source,kg_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_type.1,species
0,CFHR1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,complement factor H related 1,aging,NCBI_ID,Quick_GO,Aging,Homo species
1,CFHR3,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,complement factor H related 3,aging,NCBI_ID,Quick_GO,Aging,Homo species
2,EZH2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,enhancer of zeste 2 polycomb repressive comple...,aging,NCBI_ID,Quick_GO,Aging,Homo species
3,AEG-1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,metadherin,aging,NCBI_ID,Quick_GO,Aging,Homo species
4,AKT1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,AKT serine/threonine kinase 1,aging,NCBI_ID,Quick_GO,Aging,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,PANDA,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,promoter of CDKN1A antisense DNA damage activa...,aging,NCBI_ID,Quick_GO,Aging,Homo species
167,REST,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,RE1 silencing transcription factor,aging,NCBI_ID,Quick_GO,Aging,Homo species
168,SAFA,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,heterogeneous nuclear ribonucleoprotein U,aging,NCBI_ID,Quick_GO,Aging,Homo species
169,SP1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Sp1 transcription factor,aging,NCBI_ID,Quick_GO,Aging,Homo species
170,ZEB1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,zinc finger E-box binding homeobox 1,aging,NCBI_ID,Quick_GO,Aging,Homo species

In [5]:

agingbank_2_geneInhibit_BiologicalProcess = pd.read_csv(PROC_DIR + 'agingbank/Human_AgingbankGene_inhibits_BioPro_file2.csv')
agingbank_2_geneInhibit_BiologicalProcess.columns = agingbank_2_geneInhibit_BiologicalProcess.columns.str.lower()
agingbank_2_geneInhibit_BiologicalProcess.rename(columns={'Relation_Source': 'kg_source'}, inplace=True)
agingbank_2_geneInhibit_BiologicalProcess['kg_type'] = 'Aging'
agingbank_2_geneInhibit_BiologicalProcess['species'] = 'Homo species'
agingbank_2_geneInhibit_BiologicalProcess['relation'] = 'Gene_Inhibits_BiologicalProcess'

agingbank_2_geneInhibit_BiologicalProcess['kg_source'] = 'AgingBank'

agingbank_2_geneInhibit_BiologicalProcess

,head,relation,tail,head_type,tail_type,kg_source,kg_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_type.1,species
0,p16,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,H3 histone pseudogene 10,aging,NCBI_ID,Quick_GO,Aging,Homo species
1,SYCP2L,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,synaptonemal complex protein 2 like,aging,NCBI_ID,Quick_GO,Aging,Homo species
2,AEG-1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,metadherin,aging,NCBI_ID,Quick_GO,Aging,Homo species
3,BIS,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,BAG cochaperone 3,aging,NCBI_ID,Quick_GO,Aging,Homo species
4,CDC73,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,cell division cycle 73,aging,NCBI_ID,Quick_GO,Aging,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,SIRT1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,sirtuin 1,aging,NCBI_ID,Quick_GO,Aging,Homo species
88,SIRT1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,sirtuin 1,aging,NCBI_ID,Quick_GO,Aging,Homo species
89,SIRT1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,sirtuin 1,aging,NCBI_ID,Quick_GO,Aging,Homo species
90,SIRT6,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,sirtuin 6,aging,NCBI_ID,Quick_GO,Aging,Homo species
91,MEG3,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,maternally expressed 3,aging,NCBI_ID,Quick_GO,Aging,Homo species

In [11]:
#

In [6]:
SOURCE_DFS = [
    ('CellAge_Human_Gene_Inhibits_BioPro_1',    CellAge_Human_Gene_Inhibits_BioPro_1),
    ('agingbank_2_geneInhibit_BiologicalProcess',    agingbank_2_geneInhibit_BiologicalProcess),
    ('agingbank_geneInhibit_BiologicalProcess',    agingbank_geneInhibit_BiologicalProcess),
    
]

for name, df in SOURCE_DFS:
    dupes = df.columns[df.columns.duplicated(keep=False)].unique().tolist()
    if dupes:
        print(f"\n[{name}] duplicate columns: {dupes}")
        for col in dupes:
            for i, (_, s) in enumerate(df.loc[:, df.columns == col].items()):
                print(f"  '{col}' occurrence {i} → sample: {s.dropna().head(3).tolist()}")
    else:
        print(f"[{name}] ✓ no duplicates")

[CellAge_Human_Gene_Inhibits_BioPro_1] ✓ no duplicates
[agingbank_2_geneInhibit_BiologicalProcess] ✓ no duplicates
[agingbank_geneInhibit_BiologicalProcess] ✓ no duplicates

In [7]:
CONCAT_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name','kg_type', 'species'
]

df_list = []
for name, df in SOURCE_DFS:
    tmp = df.loc[:, ~df.columns.duplicated()].copy()
    for col in CONCAT_COLS:
        if col not in tmp.columns:
            tmp[col] = pd.NA
    df_list.append(tmp[CONCAT_COLS])

final_df = pd.concat(df_list, ignore_index=True)
print(f"Combined: {len(final_df):,} rows")
final_df

Combined: 773 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,ABCC6,Gene_Inhibits_BiologicalProcess,GO:0090398,Gene,NaN,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,ATP binding cassette subfamily C member 6,cellular senescence,Aging,Homo species
1,ACER2,Gene_Inhibits_BiologicalProcess,GO:0090399,Gene,NaN,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,alkaline ceramidase 2,replicative senescence,Aging,Homo species
2,ACER2,Gene_Inhibits_BiologicalProcess,GO:0090400,Gene,NaN,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,alkaline ceramidase 2,stress-induced premature senescence,Aging,Homo species
3,ACLY,Gene_Inhibits_BiologicalProcess,GO:0090398,Gene,NaN,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,ATP citrate lyase,cellular senescence,Aging,Homo species
4,AGO2,Gene_Inhibits_BiologicalProcess,GO:0090402,Gene,NaN,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,argonaute RISC catalytic component 2,oncogene-induced cell senescence,Aging,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
768,PANDA,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,NaN,BiologicalProcess,AgingBank,NCBI_ID,Quick_GO,promoter of CDKN1A antisense DNA damage activa...,aging,Aging,Homo species
769,REST,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,NaN,BiologicalProcess,AgingBank,NCBI_ID,Quick_GO,RE1 silencing transcription factor,aging,Aging,Homo species
770,SAFA,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,NaN,BiologicalProcess,AgingBank,NCBI_ID,Quick_GO,heterogeneous nuclear ribonucleoprotein U,aging,Aging,Homo species
771,SP1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,NaN,BiologicalProcess,AgingBank,NCBI_ID,Quick_GO,Sp1 transcription factor,aging,Aging,Homo species
772,ZEB1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,NaN,BiologicalProcess,AgingBank,NCBI_ID,Quick_GO,zinc finger E-box binding homeobox 1,aging,Aging,Homo species

In [8]:
GROUP_COLS = ['head', 'relation', 'tail']

def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

final_df_dedup = final_df.groupby(GROUP_COLS, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':         merge_sources,
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'kg_type': merge_sources,
    'species': 'first',
})
print(f"After deduplication: {len(final_df_dedup):,} rows")
final_df_dedup = final_df_dedup[REQUIRED_COLS]
final_df_dedup.head()

After deduplication: 639 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,ABCC6,Gene_Inhibits_BiologicalProcess,GO:0090398,Gene,None,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,ATP binding cassette subfamily C member 6,cellular senescence,Aging,Homo species
1,ACE,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,NCBI_ID,Quick_GO,angiotensin I converting enzyme,aging,Aging,Homo species
2,ACER2,Gene_Inhibits_BiologicalProcess,GO:0090399,Gene,None,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,alkaline ceramidase 2,replicative senescence,Aging,Homo species
3,ACER2,Gene_Inhibits_BiologicalProcess,GO:0090400,Gene,None,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,alkaline ceramidase 2,stress-induced premature senescence,Aging,Homo species
4,ACLY,Gene_Inhibits_BiologicalProcess,GO:0090398,Gene,None,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,ATP citrate lyase,cellular senescence,Aging,Homo species

In [9]:
def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(final_df_dedup)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           639                   0             639
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

In [10]:
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
final_df_dedup.to_parquet(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 639 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/GENE_INHIBITS_BIOLOGICALPROCESS/ALL_GENE_INHIBITS_BIOLOGICALPROCESS.parquet