In [ ]:
import os
import pandas as pd
import numpy as np

In [ ]:
# ── Base directories ──────────────────────────────────────────────────────────
BASE_DIR   = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR   = BASE_DIR + 'processed_data/'
DB_DIR     = BASE_DIR + 'data_collection/databases_for_mapping/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/CHEMICAL_PROMOTES_BIOLOGICALPROCESS/ALL_CHEMICAL_PROMOTES_BIOLOGICALPROCESS_Human.parquet'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

In [27]:
Pubchem = pd.read_pickle(DB_DIR + 'pubchem/combined_df.pkl')
Pubchem_IUPAC_CID_Dict  = dict(zip(Pubchem['PUBCHEM_COMPOUND_CID'], Pubchem['PUBCHEM_IUPAC_NAME']))
del Pubchem

NameError: name 'MAPPING_DIR' is not defined

In [28]:

GO = pd.read_csv(DB_DIR + 'MESH/MESH_GO_ID_NAME.csv')
GO_dict = dict(zip(GO['id'], GO['name']))
del GO

In [18]:
# AgeAnnoMO
Agextend = pd.read_csv(PROC_DIR + 'agextend_processed/CHEM_BioP_Hallmarks/All_Chemical_Promotes_BioPro(Hallmarks).csv')
Agextend.columns = Agextend.columns.str.lower()
Agextend.rename(columns={'relation_source': 'kg_source'}, inplace=True)
Agextend['kg_type'] = 'Aging'
Agextend['species'] = 'Homo sapiens'
Agextend

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,tail_detail_name,kg_source,species,head_id_is,tail_id_is,name/title/synonyms,source,kg_type
0,31703,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,BiologicalProcess,"(7S,9S)-7-[(2R,4S,5S,6S)-4-amino-5-hydroxy-6-m...",C[C@H]1[C@H]([C@H](C[C@@H](O1)O[C@H]2C[C@@](CC...,cellular senescence,AgeXtend,Homo sapiens,Pubchem,Quick_GO,Doxorubicin/Doxorubicin/doxorubicin,https://doi.org/10.1016/j.jjcc.2019.05.002,Aging
1,10297043,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,BiologicalProcess,6-[4-[(4-ethylpiperazin-1-yl)methyl]phenyl]-N-...,CCN1CCN(CC1)CC2=CC=C(C=C2)C3=CC4=C(N3)N=CN=C4N...,cellular senescence,AgeXtend,Homo sapiens,Pubchem,Quick_GO,AEE788/(R)-6-(4-((4-Ethylpiperazin-1-yl)methyl...,https://doi.org/10.1016/j.celrep.2017.09.085,Aging
2,24771867,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,BiologicalProcess,4-[[9-chloro-7-(2-fluoro-6-methoxyphenyl)-5H-p...,COC1=C(C(=CC=C1)F)C2=NCC3=CN=C(N=C3C4=C2C=C(C=...,cellular senescence,AgeXtend,Homo sapiens,Pubchem,Quick_GO,Alisertib/Alisertib/Alisertib,https://doi.org/10.1016/j.celrep.2017.09.085,Aging
3,24856041,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,BiologicalProcess,N-[4-[3-(2-aminopyrimidin-4-yl)pyridin-2-yl]ox...,CC1=CSC(=C1)C2=NN=C(C3=CC=CC=C32)NC4=CC=C(C=C4...,cellular senescence,AgeXtend,Homo sapiens,Pubchem,Quick_GO,AMG 900/N-(4-(3-(2-aminopyrimidin-4-yl)pyridin...,https://doi.org/10.1016/j.celrep.2017.09.085,Aging
4,135398495,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,BiologicalProcess,1-cyclopropyl-3-[5-[6-(morpholin-4-ylmethyl)-1...,C1CC1NC(=O)NC2=C(NN=C2)C3=NC4=C(N3)C=C(C=C4)CN...,cellular senescence,AgeXtend,Homo sapiens,Pubchem,Quick_GO,AT9283/1-Cyclopropyl-3-(3-(5-(morpholinomethyl...,https://doi.org/10.1016/j.celrep.2017.09.085,Aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47331,60750,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,BiologicalProcess,"4-amino-1-[(2R,4R,5R)-3,3-difluoro-4-hydroxy-5...",C1=CN(C(=O)N=C1N)[C@H]2C([C@@H]([C@H](O2)CO)O)...,telomere attrition,AgeXtend,Homo sapiens,Pubchem,Quick_GO,NaN,https://doi.org/10.3390/cancers12071901,Aging
47332,9802860,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,BiologicalProcess,"(1S,3S,6S,10R,12R,13R,16S,19S)-16-methoxy-3,10...",C[C@@H]1CCC[C@H]2C=C([C@H](C[C@@]23[C@H]4[C@](...,telomere attrition,AgeXtend,Homo sapiens,Pubchem,Quick_GO,NaN,https://doi.org/10.3390/cancers12071901,Aging
47333,23205,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,BiologicalProcess,"(3aR,5R,5aR,8aR,9S,9aS)-9-hydroxy-5,8a-dimethy...",C[C@@H]1C[C@@H]2[C@H]([C@@H]([C@]3([C@H]1C=CC3...,telomere attrition,AgeXtend,Homo sapiens,Pubchem,Quick_GO,NaN,https://doi.org/10.3390/cancers12071901,Aging
47334,135499583,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,BiologicalProcess,"[[(1S,4R)-4-(2-amino-6-oxo-1H-purin-9-yl)cyclo...",C1[C@@H](C=C[C@@H]1N2C=NC3=C2N=C(NC3=O)N)COP(=...,telomere attrition,AgeXtend,Homo sapiens,Pubchem,Quick_GO,NaN,https://doi.org/10.3390/cancers12071901,Aging
47335,135430795,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,BiologicalProcess,"[[(2S,5R)-5-(2-amino-6-oxo-1H-purin-9-yl)oxola...",C1C[C@@H](O[C@@H]1COP(=O)(O)OP(=O)(O)OP(=O)(O)...,telomere attrition,AgeXtend,Homo sapiens,Pubchem,Quick_GO,NaN,https://doi.org/10.3390/cancers12071901,Aging

In [19]:
SOURCE_DFS = [
    ('Agextend', Agextend),
]

for name, df in SOURCE_DFS:
    dupes = df.columns[df.columns.duplicated(keep=False)].unique().tolist()
    if dupes:
        print(f'\n[{name}] duplicate columns: {dupes}')
        for col in dupes:
            for i, (_, s) in enumerate(df.loc[:, df.columns == col].items()):
                print(f"  '{col}' occurrence {i} → sample: {s.dropna().head(3).tolist()}")
    else:
        print(f'[{name}] ✓ no duplicates')

[Agextend] ✓ no duplicates

In [20]:
CONCAT_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

df_list = []
for name, df in SOURCE_DFS:
    tmp = df.loc[:, ~df.columns.duplicated()].copy()
    for col in CONCAT_COLS:
        if col not in tmp.columns:
            tmp[col] = pd.NA
    df_list.append(tmp[CONCAT_COLS])

final_df = pd.concat(df_list, ignore_index=True)
print(f'Combined: {len(final_df):,} rows')
final_df

Combined: 47,336 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,31703,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"(7S,9S)-7-[(2R,4S,5S,6S)-4-amino-5-hydroxy-6-m...",cellular senescence,Aging,Homo sapiens
1,10297043,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,6-[4-[(4-ethylpiperazin-1-yl)methyl]phenyl]-N-...,cellular senescence,Aging,Homo sapiens
2,24771867,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,4-[[9-chloro-7-(2-fluoro-6-methoxyphenyl)-5H-p...,cellular senescence,Aging,Homo sapiens
3,24856041,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,N-[4-[3-(2-aminopyrimidin-4-yl)pyridin-2-yl]ox...,cellular senescence,Aging,Homo sapiens
4,135398495,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,1-cyclopropyl-3-[5-[6-(morpholin-4-ylmethyl)-1...,cellular senescence,Aging,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47331,60750,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"4-amino-1-[(2R,4R,5R)-3,3-difluoro-4-hydroxy-5...",telomere attrition,Aging,Homo sapiens
47332,9802860,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"(1S,3S,6S,10R,12R,13R,16S,19S)-16-methoxy-3,10...",telomere attrition,Aging,Homo sapiens
47333,23205,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"(3aR,5R,5aR,8aR,9S,9aS)-9-hydroxy-5,8a-dimethy...",telomere attrition,Aging,Homo sapiens
47334,135499583,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"[[(1S,4R)-4-(2-amino-6-oxo-1H-purin-9-yl)cyclo...",telomere attrition,Aging,Homo sapiens
47335,135430795,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"[[(2S,5R)-5-(2-amino-6-oxo-1H-purin-9-yl)oxola...",telomere attrition,Aging,Homo sapiens

In [21]:
GROUP_COLS = ['head', 'relation', 'tail']

def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

final_df_dedup = final_df.groupby(GROUP_COLS, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':         merge_sources,
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'kg_type': merge_sources,
    'species': 'first',
})
print(f'After deduplication: {len(final_df_dedup):,} rows')
final_df_dedup = final_df_dedup[REQUIRED_COLS]
final_df_dedup.head()

After deduplication: 47,336 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,6,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"1-chloro-2,4-dinitrobenzene",genomic instability,Aging,Homo sapiens
1,86,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,2-amino-3-hydroxybenzoic acid,epigenetic alterations,Aging,Homo sapiens
2,109,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,2-amino-3-sulfinopropanoic acid,epigenetic alterations,Aging,Homo sapiens
3,190,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,7H-purin-6-amine,genomic instability,Aging,Homo sapiens
4,237,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"4-N-(6-chloro-2-methoxyacridin-9-yl)-1-N,1-N-d...",epigenetic alterations,Aging,Homo sapiens

In [22]:
def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(final_df_dedup)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type         47336                   0           47336
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name         51                   0              51
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

In [24]:
final_df_dedup[final_df_dedup['head_detail_name'].isna()]

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
686,10038,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
687,10039,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
3752,263463,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
5388,652954,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
6652,666049,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
6682,666291,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
24272,3404071,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
27950,4889893,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
27988,4898241,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
31180,6079422,ChemicalEntity_Promotes_BiologicalProcess,GO:1111114,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,loss of proteostasis,Aging,Homo sapiens
31470,6323490,ChemicalEntity_Promotes_BiologicalProcess,GO:1111116,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,mitochondrial dysfunction,Aging,Homo sapiens
31480,6327657,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
31481,6327657,ChemicalEntity_Promotes_BiologicalProcess,GO:1111118,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,altered intercellular communication,Aging,Homo sapiens
32382,6604952,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
35575,9959619,ChemicalEntity_Promotes_BiologicalProcess,GO:1111116,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,mitochondrial dysfunction,Aging,Homo sapiens
40282,16682734,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
40294,16682999,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
41606,23682559,ChemicalEntity_Promotes_BiologicalProcess,GO:1111116,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,mitochondrial dysfunction,Aging,Homo sapiens
43201,24868291,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
43202,24868294,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
43898,25074892,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
44097,38988738,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
44102,40424356,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
44141,44135675,ChemicalEntity_Promotes_BiologicalProcess,GO:1111116,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,mitochondrial dysfunction,Aging,Homo sapiens
44696,53779545,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
44782,54682935,ChemicalEntity_Promotes_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,epigenetic alterations,Aging,Homo sapiens
45083,90478862,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45088,91800127,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45098,92254928,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45100,92279974,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45104,92288874,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45106,92289845,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45129,121488551,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45130,121488579,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45131,121488769,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45132,121489075,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45133,121489703,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45134,121490877,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45136,121491979,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45137,121492292,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45139,121492917,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45140,121492995,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45141,121493222,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45143,121596462,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45144,121596550,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45145,121596554,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45146,121596623,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45147,121596684,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45148,122173822,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45355,131634424,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens
45356,131634926,ChemicalEntity_Promotes_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,None,genomic instability,Aging,Homo sapiens

In [29]:
head_ids = pd.to_numeric(final_df['head'], errors='coerce')
mask = final_df['head_detail_name'].isna()
final_df.loc[mask, 'head_detail_name'] = head_ids[mask].map(Pubchem_IUPAC_CID_Dict)
final_df

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,31703,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"(7S,9S)-7-[(2R,4S,5S,6S)-4-amino-5-hydroxy-6-m...",cellular senescence,Aging,Homo sapiens
1,10297043,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,6-[4-[(4-ethylpiperazin-1-yl)methyl]phenyl]-N-...,cellular senescence,Aging,Homo sapiens
2,24771867,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,4-[[9-chloro-7-(2-fluoro-6-methoxyphenyl)-5H-p...,cellular senescence,Aging,Homo sapiens
3,24856041,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,N-[4-[3-(2-aminopyrimidin-4-yl)pyridin-2-yl]ox...,cellular senescence,Aging,Homo sapiens
4,135398495,ChemicalEntity_Promotes_BiologicalProcess,GO:0090398,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,1-cyclopropyl-3-[5-[6-(morpholin-4-ylmethyl)-1...,cellular senescence,Aging,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47331,60750,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"4-amino-1-[(2R,4R,5R)-3,3-difluoro-4-hydroxy-5...",telomere attrition,Aging,Homo sapiens
47332,9802860,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"(1S,3S,6S,10R,12R,13R,16S,19S)-16-methoxy-3,10...",telomere attrition,Aging,Homo sapiens
47333,23205,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"(3aR,5R,5aR,8aR,9S,9aS)-9-hydroxy-5,8a-dimethy...",telomere attrition,Aging,Homo sapiens
47334,135499583,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"[[(1S,4R)-4-(2-amino-6-oxo-1H-purin-9-yl)cyclo...",telomere attrition,Aging,Homo sapiens
47335,135430795,ChemicalEntity_Promotes_BiologicalProcess,GO:1111112,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"[[(2S,5R)-5-(2-amino-6-oxo-1H-purin-9-yl)oxola...",telomere attrition,Aging,Homo sapiens

In [30]:
nan_summary(final_df_dedup)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type         47336                   0           47336
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name         51                   0              51
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

In [32]:
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
final_df_dedup.to_parquet(OUT_PATH, index=False)
print(f'Saved {len(final_df_dedup):,} rows → {OUT_PATH}')

Saved 47,336 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/CHEMICAL_PROMOTES_BIOLOGICALPROCESS/ALL_CHEMICAL_PROMOTES_BIOLOGICALPROCESS_Human.parquet

In [31]:
#