# Gene → BiologicalProcess Relation Pipeline

Builds a unified, deduplicated edge table for the **Gene–BiologicalProcess** relation.

**Output schema:** `head | relation | tail | head_type | relation_type | tail_type | kg_source | kg_type | head_id_is | tail_id_is | head_detail_name | tail_detail_name`

---
**Sources included:**
- ageanno_processed_mo (AgeAnnoMO_Human_Gene_BiologicalProcess.csv - Native Aging)
- agingatlas (Human/Human_Gene_BiologicalProcess.csv - Native Aging)
- agingbank (4 files - Native Aging)
- cellage (2 files - Native Aging)
- digitalagingatlas (6 files - Native Aging)
- DRKG (DRKG_Gene_Biological_Process.csv - Native Generalised)
- genage (Human/Human_Gene_BiologicalProcess.csv - Native Aging)
- GPKG (Gene_BiologicalProcess_GPKG.csv - Native Generalised)
- Hetionet (Gene_BiologicalProcess_Hetionet.csv - Native Generalised)
- Monarch (Human/Gene_Human_BiologicalProcess_MONARCH.csv - Native Generalised)
- TARKG (Gene_BiologicalProcess_TARKG.csv - Native Generalised)

**Base paths:**
- KG data: `/storage/Arushi/090526_EvoAge/kg_formation/`
- Processed KG files: `/storage/Arushi/090526_EvoAge/kg_formation/processed_data/`

## 0 · Imports & Base Paths

In [1]:
import pandas as pd
import os

BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR     = BASE_DIR + 'processed_data/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/GENE_BIOLOGICALPROCESS/ALL_GENE_BIOLOGICALPROCESS.csv'

REQUIRED_COLS = [
    'head', 'relation', 'tail', 'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type', 'head_id_is', 'tail_id_is', 'head_detail_name', 'tail_detail_name','species'
]

## 1 · Mapping DBs

In [15]:
# MESH mapping to map tail (GO_ID) to name
go_db = pd.read_csv(MAPPING_DIR + 'MESH/MESH_GO_ID_NAME.csv')
GO_dict = dict(zip(go_db['id'], go_db['name']))
del go_db

# NCBI mapping to resolve gene synonyms and descriptions
ncbi = pd.read_csv(MAPPING_DIR + 'ncbi/Homo_sapiens.gene_info', sep='\t')
NCBI_sym2desc_dict = dict(zip(ncbi['Symbol'],  ncbi['description']))
NCBI_syn2sym_dict = {}
for synonyms, symbol in zip(ncbi['Synonyms'], ncbi['Symbol']):
    for syn in str(synonyms).split('|'):
        NCBI_syn2sym_dict[syn.strip()] = symbol
del ncbi
NCBI_sym2desc_dict

{'A1BG': 'alpha-1-B glycoprotein',
 'A2M': 'alpha-2-macroglobulin',
 'A2MP1': 'alpha-2-macroglobulin pseudogene 1',
 'NAT1': 'N-acetyltransferase 1',
 'NAT2': 'N-acetyltransferase 2',
 'NATP': 'N-acetyltransferase pseudogene',
 'SERPINA3': 'serpin family A member 3',
 'AADAC': 'arylacetamide deacetylase',
 'AAMP': 'angio associated migratory cell protein',
 'AANAT': 'aralkylamine N-acetyltransferase',
 'AARS1': 'alanyl-tRNA synthetase 1',
 'AAVS1': 'adeno-associated virus integration site 1',
 'ABAT': '4-aminobutyrate aminotransferase',
 'ABCA1': 'ATP binding cassette subfamily A member 1',
 'ABCA2': 'ATP binding cassette subfamily A member 2',
 'ABCA3': 'ATP binding cassette subfamily A member 3',
 'ABCB7': 'ATP binding cassette subfamily B member 7',
 'ABCF1': 'ATP binding cassette subfamily F member 1',
 'ABCA4': 'ATP binding cassette subfamily A member 4',
 'ABL1': 'ABL proto-oncogene 1, non-receptor tyrosine kinase',
 'AOC1': 'amine oxidase copper containing 1',
 'ABL2': 'ABL proto-oncogene 2, non-receptor tyrosine kinase',
 'ABO': 'ABO, alpha 1-3-N-acetylgalactosaminyltransferase and alpha 1-3-galactosyltransferase',
 'ABR': 'ABR activator of RhoGEF and GTPase',
 'ACAA1': 'acetyl-CoA acyltransferase 1',
 'ACACA': 'acetyl-CoA carboxylase alpha',
 'ACACB': 'acetyl-CoA carboxylase beta',
 'ACADL': 'acyl-CoA dehydrogenase long chain',
 'ACADM': 'acyl-CoA dehydrogenase medium chain',
 'ACADS': 'acyl-CoA dehydrogenase short chain',
 'ACADSB': 'acyl-CoA dehydrogenase short/branched chain',
 'ACADVL': 'acyl-CoA dehydrogenase very long chain',
 'ACAT1': 'acetyl-CoA acetyltransferase 1',
 'ACAT2': 'acetyl-CoA acetyltransferase 2',
 'ASIC2': 'acid sensing ion channel subunit 2',
 'ASIC1': 'acid sensing ion channel subunit 1',
 'ACHE': 'acetylcholinesterase (Yt blood group)',
 'ACLY': 'ATP citrate lyase',
 'ACO1': 'aconitase 1',
 'ACR': 'acrosin',
 'ACO2': 'aconitase 2',
 'ACOX1': 'acyl-CoA oxidase 1',
 'ACP1': 'acid phosphatase 1',
 'ACP2': 'acid phosphatase 2, lysosomal',
 'ACP5': 'acid phosphatase 5, tartrate resistant',
 'ACP3': 'acid phosphatase 3',
 'ACRV1': 'acrosomal vesicle protein 1',
 'ACTA1': 'actin alpha 1, skeletal muscle',
 'ACTA2': 'actin alpha 2, smooth muscle',
 'ACTB': 'actin beta',
 'ACTBP2': 'ACTB pseudogene 2',
 'ACTBP3': 'ACTB pseudogene 3',
 'ACTBP4': 'ACTB pseudogene 4',
 'ACTBP6': 'ACTB pseudogene 6',
 'ACTBP7': 'ACTB pseudogene 7',
 'ACTBP8': 'ACTB pseudogene 8',
 'ACTBP9': 'ACTB pseudogene 9',
 'ACTC1': 'actin alpha cardiac muscle 1',
 'ACTG1': 'actin gamma 1',
 'ACTG2': 'actin gamma 2, smooth muscle',
 'ACTG1P1': 'actin gamma 1 pseudogene 1',
 'ACTG1P2': 'actin gamma 1 pseudogene 2',
 'ACTG1P3': 'actin gamma 1 pseudogene 3',
 'ACTG1P6': 'actin gamma 1 pseudogene 6',
 'ACTG1P7': 'actin gamma 1 pseudogene 7',
 'ACTG1P8': 'actin gamma 1 pseudogene 8',
 'ACTN4': 'actinin alpha 4',
 'ACTG1P9': 'actin gamma 1 pseudogene 9',
 'ACTG1P10': 'actin gamma 1 pseudogene 10',
 'ACTL6A': 'actin like 6A',
 'ACTN1': 'actinin alpha 1',
 'ACTN2': 'actinin alpha 2',
 'ACTN3': 'actinin alpha 3',
 'ACVR1': 'activin A receptor type 1',
 'ACVR1B': 'activin A receptor type 1B',
 'ACVR2A': 'activin A receptor type 2A',
 'ACVR2B': 'activin A receptor type 2B',
 'ACVRL1': 'activin A receptor like type 1',
 'ACY1': 'aminoacylase 1',
 'ACYP1': 'acylphosphatase 1',
 'ACYP2': 'acylphosphatase 2',
 'ADA': 'adenosine deaminase',
 'ADAM8': 'ADAM metallopeptidase domain 8',
 'ADAM10': 'ADAM metallopeptidase domain 10',
 'ADAR': 'adenosine deaminase RNA specific',
 'ADARB1': 'adenosine deaminase RNA specific B1',
 'ADARB2': 'adenosine deaminase RNA specific B2 (inactive)',
 'ADCP1': 'adenosine deaminase complexing protein 1',
 'ADCY1': 'adenylate cyclase 1',
 'ADCY2': 'adenylate cyclase 2',
 'ADCY3': 'adenylate cyclase 3',
 'ADCY5': 'adenylate cyclase 5',
 'ADCY6': 'adenylate cyclase 6',
 'ADCY7': 'adenylate cyclase 7',
 'ADCY8': 'adenylate cyclase 8',
 'ADCY9': 'adenylate cyclase 9',
 'ADCYAP1': 'adenylate cyclase activating polypeptide 1',
 'ADCYAP1R1': 'ADCYAP receptor type I',
 'ADD1': 'adducin 1',
 'ADD2': 'adducin 2',
 'ADD3': 'adducin 3',
 'ADFN': 'albinism-deafness syndrome',
 'PLIN2': 'perilipin 2',
 'ADH1A': 'alcohol dehydrogenase 1A (class I), alpha polypeptide',
 'ADH1B': 'alcohol dehydrogenase 1B (class I), beta polypeptide',
 'ADH1C': 'alcohol dehydrogenase 1C (class I), gamma polypeptide',
 'ADH4': 'alcohol dehydrogenase 4 (class II), pi polypeptide',
 'ADH5': 'alcohol dehydrogenase 5 (class III), chi polypeptide',
 'ADH6': 'alcohol dehydrogenase 6 (class V)',
 'ADH7': 'alcohol dehydrogenase 7 (class IV), mu or sigma polypeptide',
 'ADK': 'adenosine kinase',
 'ADM': 'adrenomedullin',
 'ADORA1': 'adenosine A1 receptor',
 'ADORA2A': 'adenosine A2a receptor',
 'ADORA2B': 'adenosine A2b receptor',
 'ADORA2BP1': 'adenosine A2b receptor pseudogene 1',
 'ADORA3': 'adenosine A3 receptor',
 'ADPRH': 'ADP-ribosylarginine hydrolase',
 'PARP1': 'poly(ADP-ribose) polymerase 1',
 'PARP4': 'poly(ADP-ribose) polymerase family member 4',
 'PARP1P1': 'poly(ADP-ribose) polymerase 1 pseudogene 1',
 'PARP1P2': 'poly(ADP-ribose) polymerase 1 pseudogene 2',
 'ADRA1D': 'adrenoceptor alpha 1D',
 'ADRA1B': 'adrenoceptor alpha 1B',
 'ADRA1A': 'adrenoceptor alpha 1A',
 'ADRA2A': 'adrenoceptor alpha 2A',
 'ADRA2B': 'adrenoceptor alpha 2B',
 'ADRA2C': 'adrenoceptor alpha 2C',
 'ADRB1': 'adrenoceptor beta 1',
 'ADRB2': 'adrenoceptor beta 2',
 'ADRB3': 'adrenoceptor beta 3',
 'GRK2': 'G protein-coupled receptor kinase 2',
 'GRK3': 'G protein-coupled receptor kinase 3',
 'ADSL': 'adenylosuccinate lyase',
 'ADSS2': 'adenylosuccinate synthase 2',
 'AP2A1': 'adaptor related protein complex 2 subunit alpha 1',
 'AP2A2': 'adaptor related protein complex 2 subunit alpha 2',
 'AP1B1': 'adaptor related protein complex 1 subunit beta 1',
 'AP2B1': 'adaptor related protein complex 2 subunit beta 1',
 'AP1G1': 'adaptor related protein complex 1 subunit gamma 1',
 'AEBP1': 'AE binding protein 1',
 'TLE5': 'TLE family member 5, transcriptional modulator',
 'CRISP1': 'cysteine rich secretory protein 1',
 'AF8T': 'AF8 temperature sensitivity complementing',
 'AFA': 'ankyloblepharon filiforme adnatum',
 'AFG3L1P': 'AFG3 like matrix AAA peptidase subunit 1, pseudogene',
 'AFM': 'afamin',
 'AFP': 'alpha fetoprotein',
 'AGA': 'aspartylglucosaminidase',
 'ACAN': 'aggrecan',
 'AGER': 'advanced glycosylation end-product specific receptor',
 'AGL': 'amylo-alpha-1,6-glucosidase and 4-alpha-glucanotransferase',
 'AGRP': 'agouti related neuropeptide',
 'JAG1': 'jagged canonical Notch ligand 1',
 'AGT': 'angiotensinogen',
 'AGTR1': 'angiotensin II receptor type 1',
 'AGTR2': 'angiotensin II receptor type 2',
 'APLNR': 'apelin receptor',
 'AGXT': 'alanine--glyoxylate aminotransferase',
 'NR0B1': 'nuclear receptor subfamily 0 group B member 1',
 'AHCY': 'adenosylhomocysteinase',
 'AIC': 'Aicardi syndrome',
 'AHR': 'aryl hydrocarbon receptor',
 'AHSG': 'alpha 2-HS glycoprotein',
 'AIF1': 'allograft inflammatory factor 1',
 'AIH3': 'amelogenesis imperfecta 3, hypomaturation or hypoplastic type',
 'CRYBG1': 'crystallin beta-gamma domain containing 1',
 'AK1': 'adenylate kinase 1',
 'AK2': 'adenylate kinase 2',
 'AK4': 'adenylate kinase 4',
 'AK4P1': 'adenylate kinase 4 pseudogene 1',
 'AKT1': 'AKT serine/threonine kinase 1',
 'AKT2': 'AKT serine/threonine kinase 2',
 'ALAD': 'aminolevulinate dehydratase',
 'ALAS1': "5'-aminolevulinate synthase 1",
 'ALAS2': "5'-aminolevulinate synthase 2",
 'ALB': 'albumin',
 'ALCAM': 'activated leukocyte cell adhesion molecule',
 'ABCD1': 'ATP binding cassette subfamily D member 1',
 'ALDH1A1': 'aldehyde dehydrogenase 1 family member A1',
 'ALDH2': 'aldehyde dehydrogenase 2 family member',
 'ALDH3A1': 'aldehyde dehydrogenase 3 family member A1',
 'ALDH1B1': 'aldehyde dehydrogenase 1 family member B1',
 'ALDH1A3': 'aldehyde dehydrogenase 1 family member A3',
 'ALDH3B1': 'aldehyde dehydrogenase 3 family member B1',
 'ALDH3B2': 'aldehyde dehydrogenase 3 family member B2',
 'ALDH9A1': 'aldehyde dehydrogenase 9 family member A1',
 'ALDH3A2': 'aldehyde dehydrogenase 3 family member A2',
 'ABCD2': 'ATP binding cassette subfamily D member 2',
 'ALDOA': 'aldolase, fructose-bisphosphate A',
 'ALDOAP2': 'ALDOA pseudogene 2',
 'ALDOB': 'aldolase, fructose-bisphosphate B',
 'ALDOC': 'aldolase, fructose-bisphosphate C',
 'AKR1B1': 'aldo-keto reductase family 1 member B',
 'AKR1B1P2': 'aldo-keto reductase family 1 member B1 pseudogene 2',
 'ALK': 'ALK receptor tyrosine kinase',
 'ALOX12': 'arachidonate 12-lipoxygenase, 12S type',
 'ALOX5': 'arachidonate 5-lipoxygenase',
 'ALOX5AP': 'arachidonate 5-lipoxygenase activating protein',
 'ALOX12B': 'arachidonate 12-lipoxygenase, 12R type',
 'ALOX12P1': 'arachidonate 12-lipoxygenase pseudogene 1',
 'ALOX12P2': 'arachidonate 12-lipoxygenase pseudogene 2',
 'ALOX15': 'arachidonate 15-lipoxygenase',
 'ALOX15B': 'arachidonate 15-lipoxygenase type B',
 'ALPI': 'alkaline phosphatase, intestinal',
 'ALPL': 'alkaline phosphatase, biomineralization associated',
 'ALPP': 'alkaline phosphatase, placental',
 'ALPG': 'alkaline phosphatase, germ cell',
 'ALS3': 'amyotrophic lateral sclerosis 3 (autosomal dominant)',
 'ALX3': 'ALX homeobox 3',
 'AMBN': 'ameloblastin',
 'AMBP': 'alpha-1-microglobulin/bikunin precursor',
 'AMD1': 'adenosylmethionine decarboxylase 1',
 'AMD1P2': 'adenosylmethionine decarboxylase 1 pseudogene 2',
 'AMELX': 'amelogenin X-linked',
 'AMELY': 'amelogenin Y-linked',
 'AMFR': 'autocrine motility factor receptor',
 'AMH': 'anti-Mullerian hormone',
 'AMHR2': 'anti-Mullerian hormone receptor type 2',
 'AMPD1': 'adenosine monophosphate deaminase 1',
 'AMPD2': 'adenosine monophosphate deaminase 2',
 'AMPD3': 'adenosine monophosphate deaminase 3',
 'AMPH': 'amphiphysin',
 'BIN1': 'bridging integrator 1',
 'AMT': 'aminomethyltransferase',
 'AMY1A': 'amylase alpha 1A',
 'AMY1B': 'amylase alpha 1B',
 'AMY1C': 'amylase alpha 1C',
 'AMY2A': 'amylase alpha 2A',
 'AMY2B': 'amylase alpha 2B',
 'AMYP1': 'amylase alpha pseudogene 1',
 'ANCR': 'Angelman syndrome chromosome region',
 'ANG': 'angiogenin',
 'ANGPT1': 'angiopoietin 1',
 'ANGPT2': 'angiopoietin 2',
 'ANK1': 'ankyrin 1',
 'ANK2': 'ankyrin 2',
 'ANK3': 'ankyrin 3',
 'ANPEP': 'alanyl aminopeptidase, membrane',
 'SLC25A4': 'solute carrier family 25 member 4',
 'SLC25A5': 'solute carrier family 25 member 5',
 'SLC25A6': 'solute carrier family 25 member 6',
 'ANXA1': 'annexin A1',
 'ANXA2': 'annexin A2',
 'ANXA2P1': 'annexin A2 pseudogene 1',
 'ANXA2P2': 'annexin A2 pseudogene 2',
 'ANXA2P3': 'annexin A2 pseudogene 3',
 'ANXA3': 'annexin A3',
 'ANXA4': 'annexin A4',
 'ANXA5': 'annexin A5',
 'ANXA6': 'annexin A6',
 'ANXA7': 'annexin A7',
 'ANXA11': 'annexin A11',
 'ANXA13': 'annexin A13',
 'AOAH': 'acyloxyacyl hydrolase',
 'AOC2': 'amine oxidase copper containing 2',
 'AOX1': 'aldehyde oxidase 1',
 'APAF1': 'apoptotic peptidase activating factor 1',
 'NUDT2': 'nudix hydrolase 2',
 'APOF': 'apolipoprotein F',
 'APBA1': 'amyloid beta precursor protein binding family A member 1',
 'APBA2': 'amyloid beta precursor protein binding family A member 2',
 'APBB1': 'amyloid beta precursor protein binding family B member 1',
 'APBB2': 'amyloid beta precursor protein binding family B member 2',
 'APC': 'APC regulator of WNT signaling pathway',
 'APCS': 'amyloid P component, serum',
 'AIRE': 'autoimmune regulator',
 'APEH': 'acylaminoacyl-peptide hydrolase',
 'APEX1': 'apurinic/apyrimidinic endodeoxyribonuclease 1',
 'BIRC2': 'baculoviral IAP repeat containing 2',
 'BIRC3': 'baculoviral IAP repeat containing 3',
 'XIAP': 'X-linked inhibitor of apoptosis',
 'BIRC5': 'baculoviral IAP repeat containing 5',
 'APLP1': 'amyloid beta precursor like protein 1',
 'APLP2': 'amyloid beta precursor like protein 2',
 'APOA1': 'apolipoprotein A1',
 'APOA2': 'apolipoprotein A2',
 'APOA4': 'apolipoprotein A4',
 'APOB': 'apolipoprotein B',
 'APOBEC1': 'apolipoprotein B mRNA editing enzyme catalytic subunit 1',
 'APOC1': 'apolipoprotein C1',
 'APOC1P1': 'apolipoprotein C1 pseudogene 1',
 'AQP8': 'aquaporin 8',
 'APOC2': 'apolipoprotein C2',
 'APOC3': 'apolipoprotein C3',
 'APOC4': 'apolipoprotein C4',
 'APOD': 'apolipoprotein D',
 'APOE': 'apolipoprotein E',
 'APOH': 'apolipoprotein H',
 'APP': 'amyloid beta precursor protein',
 'APRT': 'adenine phosphoribosyltransferase',
 'KLK3': 'kallikrein related peptidase 3',
 'FAS': 'Fas cell surface death receptor',
 'FASLG': 'Fas ligand',
 'SHROOM2': 'shroom family member 2',
 'AQP1': 'aquaporin 1 (Colton blood group)',
 'AQP2': 'aquaporin 2',
 'AQP3': 'aquaporin 3 (Gill blood group)',
 'AQP4': 'aquaporin 4',
 'AQP5': 'aquaporin 5',
 'AQP6': 'aquaporin 6',
 'AQP7': 'aquaporin 7',
 'AQP9': 'aquaporin 9',
 'AR': 'androgen receptor',
 'ABCC6': 'ATP binding cassette subfamily C member 6',
 'ARAF': 'A-Raf proto-oncogene, serine/threonine kinase',
 'ARCN1': 'archain 1',
 'TRIM23': 'tripartite motif containing 23',
 'AREG': 'amphiregulin',
 'ARF1': 'ARF GTPase 1',
 'ARF3': 'ARF GTPase 3',
 'ARF4': 'ARF GTPase 4',
 'ARL4D': 'ARF like GTPase 4D',
 'ARF4P1': 'ARF GTPase 4 pseudogene 1',
 'ARF5': 'ARF GTPase 5',
 'ARF6': 'ARF GTPase 6',
 'ARG1': 'arginase 1',
 'ARG2': 'arginase 2',
 'RHOA': 'ras homolog family member A',
 'RHOB': 'ras homolog family member B',
 'RHOC': 'ras homolog family member C',
 'RND3': 'Rho family GTPase 3',
 'RHOG': 'ras homolog family member G',
 'ARHGAP1': 'Rho GTPase activating protein 1',
 'ARHGAP4': 'Rho GTPase activating protein 4',
 'ARHGAP5': 'Rho GTPase activating protein 5',
 'ARHGAP6': 'Rho GTPase activating protein 6',
 'ARHGDIA': 'Rho GDP dissociation inhibitor alpha',
 'ARHGDIB': 'Rho GDP dissociation inhibitor beta',
 'ARHGDIG': 'Rho GDP dissociation inhibitor gamma',
 'RHOH': 'ras homolog family member H',
 'ARL1': 'ARF like GTPase 1',
 'PHOX2A': 'paired like homeobox 2A',
 'ARL2': 'ARF like GTPase 2',
 'ARL3': 'ARF like GTPase 3',
 'ARNT': 'aryl hydrocarbon receptor nuclear translocator',
 'BMAL1': 'basic helix-loop-helix ARNT like 1',
 'ARR3': 'arrestin 3',
 'ARRB1': 'arrestin beta 1',
 'ARRB2': 'arrestin beta 2',
 'ARSA': 'arylsulfatase A',
 'ARSB': 'arylsulfatase B',
 'STS': 'steroid sulfatase',
 'ARSC2': 'arylsulfatase C, isozyme F',
 'ARSD': 'arylsulfatase D',
 'ARSL': 'arylsulfatase L',
 'ARSF': 'arylsulfatase F',
 'ART1': 'ADP-ribosyltransferase 1',
 'ART2P': 'ADP-ribosyltransferase 2, pseudogene',
 'ART3': 'ADP-ribosyltransferase 3 (inactive)',
 'ART4': 'ADP-ribosyltransferase 4 (inactive) (Dombrock blood group)',
 'ARVCF': 'ARVCF delta catenin family member',
 'ARVD3': 'arrhythmogenic right ventricular dysplasia 3',
 'ARVD4': 'arrhythmogenic right ventricular dysplasia 4',
 'ASAH1': 'N-acylsphingosine amidohydrolase 1',
 'ASCL1': 'achaete-scute family bHLH transcription factor 1',
 'ASCL2': 'achaete-scute family bHLH transcription factor 2',
 'ASD1': 'atrial septal defect 1',
 'ASGR1': 'asialoglycoprotein receptor 1',
 'ASGR2': 'asialoglycoprotein receptor 2',
 'ASIP': 'agouti signaling protein',
 'ASL': 'argininosuccinate lyase',
 'ASLP1': 'argininosuccinate lyase pseudogene 1',
 'ASMT': 'acetylserotonin O-methyltransferase',
 'GET3': 'guided entry of tail-anchored proteins factor 3, ATPase',
 'ASNS': 'asparagine synthetase (glutamine-hydrolyzing)',
 'ASNSP2': 'ASNS pseudogene 2',
 'ASPA': 'aspartoacylase',
 'ASPH': 'aspartate beta-hydroxylase',
 'ASS1': 'argininosuccinate synthase 1',
 'ASS1P2': 'argininosuccinate synthetase 1 pseudogene 2',
 'ASS1P4': 'argininosuccinate synthetase 1 pseudogene 4',
 'ASS1P5': 'argininosuccinate synthetase 1 pseudogene 5',
 'ASS1P6': 'argininosuccinate synthetase 1 pseudogene 6',
 'ASS1P8': 'argininosuccinate synthetase 1 pseudogene 8',
 'ASS1P9': 'argininosuccinate synthetase 1 pseudogene 9',
 'ASS1P10': 'argininosuccinate synthetase 1 pseudogene 10',
 'ASS1P14': 'argininosuccinate synthetase 1 pseudogene 14',
 'ASTN1': 'astrotactin 1',
 'SERPINC1': 'serpin family C member 1',
 'ZFHX3': 'zinc finger homeobox 3',
 'ATD': 'asphixiating thoracic dystrophy (chondroectodermal dysplasia-like syndrome)',
 'ATF1': 'activating transcription factor 1',
 'ATF3': 'activating transcription factor 3',
 'ATF4': 'activating transcription factor 4',
 'ATF4P1': 'activating transcription factor 4 pseudogene 1',
 'ATHS': 'atherosclerosis susceptibility (lipoprotein associated)',
 'ATIC': '5-aminoimidazole-4-carboxamide ribonucleotide formyltransferase/IMP cyclohydrolase',
 'ATM': 'ATM serine/threonine kinase',
 'RERE': 'arginine-glutamic acid dipeptide repeats',
 'ATOH1': 'atonal bHLH transcription factor 1',
 'ATOX1': 'antioxidant 1 copper chaperone',
 'ATP1A1': 'ATPase Na+/K+ transporting subunit alpha 1',
 'ATP1A2': 'ATPase Na+/K+ transporting subunit alpha 2',
 'ATP1A3': 'ATPase Na+/K+ transporting subunit alpha 3',
 'ATP12A': 'ATPase H+/K+ transporting non-gastric alpha2 subunit',
 'ATP1A4': 'ATPase Na+/K+ transporting subunit alpha 4',
 'ATP1B1': 'ATPase Na+/K+ transporting subunit beta 1',
 'ATP1B2': 'ATPase Na+/K+ transporting subunit beta 2',
 'ATP1B3': 'ATPase Na+/K+ transporting subunit beta 3',
 'ATP1B3P1': 'ATPase Na+/K+ transporting subunit beta 3 pseudogene 1',
 'ATP1B1P1': 'ATPase Na+/K+ transporting subunit beta 1 pseudogene 1',
 'FXYD2': 'FXYD domain containing ion transport regulator 2',
 'ATP2A1': 'ATPase sarcoplasmic/endoplasmic reticulum Ca2+ transporting 1',
 'ATP2A2': 'ATPase sarcoplasmic/endoplasmic reticulum Ca2+ transporting 2',
 'ATP2A3': 'ATPase sarcoplasmic/endoplasmic reticulum Ca2+ transporting 3',
 'ATP2B1': 'ATPase plasma membrane Ca2+ transporting 1',
 'ATP2B2': 'ATPase plasma membrane Ca2+ transporting 2',
 'ATP2B3': 'ATPase plasma membrane Ca2+ transporting 3',
 'ATP2B4': 'ATPase plasma membrane Ca2+ transporting 4',
 'ATP4A': 'ATPase H+/K+ transporting subunit alpha',
 'ATP4B': 'ATPase H+/K+ transporting subunit beta',
 'ATP5F1A': 'ATP synthase F1 subunit alpha',
 'ALDH7A1': 'aldehyde dehydrogenase 7 family member A1',
 'ATP5F1AP2': 'ATP synthase F1 subunit alpha pseudogene 2',
 'ATP5F1B': 'ATP synthase F1 subunit beta',
 'ATP5F1BP1': 'ATP synthase F1 subunit beta pseudogene 1',
 'ATP5F1C': 'ATP synthase F1 subunit gamma',
 'ATP5F1D': 'ATP synthase F1 subunit delta',
 'ATP5F1E': 'ATP synthase F1 subunit epsilon',
 'ATP5PB': 'ATP synthase peripheral stalk-membrane subunit b',
 'ATP5MC1': 'ATP synthase membrane subunit c locus 1',
 'ATP5MC2': 'ATP synthase membrane subunit c locus 2',
 'ATP5MC3': 'ATP synthase membrane subunit c locus 3',
 'ATP5MC2P1': 'ATP5MC2 pseudogene 1',
 'ATP5ME': 'ATP synthase membrane subunit e',
 'ATP5PF': 'ATP synthase peripheral stalk subunit F6',
 'ATP6V1A': 'ATPase H+ transporting V1 subunit A',
 'ATP6V1B1': 'ATPase H+ transporting V1 subunit B1',
 'ATP6V1B2': 'ATPase H+ transporting V1 subunit B2',
 'ATP6V0C': 'ATPase H+ transporting V0 subunit c',
 'ATP6V1C1': 'ATPase H+ transporting V1 subunit C1',
 'ATP6V1E1': 'ATPase H+ transporting V1 subunit E1',
 'ATP6V0B': 'ATPase H+ transporting V0 subunit b',
 'ATP6V1G2': 'ATPase H+ transporting V1 subunit G2',
 'ATP6V0A1': 'ATPase H+ transporting V0 subunit a1',
 'ATP6AP1': 'ATPase H+ transporting accessory protein 1',
 'ATP7A': 'ATPase copper transporting alpha',
 'ATP5PO': 'ATP synthase peripheral stalk subunit OSCP',
 'ATP7B': 'ATPase copper transporting beta',
 'ALDH7A1P1': 'aldehyde dehydrogenase 7 family member A1 pseudogene 1',
 'ALDH7A1P2': 'aldehyde dehydrogenase 7 family member A1 pseudogene 2',
 'ALDH7A1P3': 'aldehyde dehydrogenase 7 family member A1 pseudogene 3',
 'ALDH7A1P4': 'aldehyde dehydrogenase 7 family member A1 pseudogene 4',
 'ATR': 'ATR serine/threonine kinase',
 'ATRX': 'ATRX chromatin remodeler',
 'KIF1A': 'kinesin family member 1A',
 'AUH': 'AU RNA binding methylglutaconyl-CoA hydratase',
 'AUP1': 'AUP1 lipid droplet regulating VLDL assembly factor',
 'AVP': 'arginine vasopressin',
 'AVPR1A': 'arginine vasopressin receptor 1A',
 'AVPR1B': 'arginine vasopressin receptor 1B',
 'AVPR2': 'arginine vasopressin receptor 2',
 'AXL': 'AXL receptor tyrosine kinase',

## 2 · Load Source Files

# # 1. ageanno_processed_mo (AgeAnnoMO_Human_Gene_BiologicalProcess.csv)

In [3]:
ageanno_path = PROC_DIR + 'ageanno_processed_mo/AgeAnnoMO_Human_Gene_BiologicalProcess.csv'
if os.path.exists(ageanno_path):
    AgeAnno = pd.read_csv(ageanno_path)
    AgeAnno.columns = AgeAnno.columns.str.lower()
    if 'kgsource' in AgeAnno.columns:
        AgeAnno = AgeAnno.rename(columns={'kgsource': 'kg_source'})
    if 'head_name' in AgeAnno.columns:
        AgeAnno = AgeAnno.rename(columns={'head_name': 'head_detail_name'})
    if 'tail_name' in AgeAnno.columns:
        AgeAnno = AgeAnno.rename(columns={'tail_name': 'tail_detail_name'})
    AgeAnno['head_id_is'] = 'NCBI_ID'
    AgeAnno['tail_id_is'] = 'Quick_GO'
    AgeAnno['relation'] = 'Gene_BiologicalProcess'
    AgeAnno['head_type'] = 'Gene'
    AgeAnno['tail_type'] = 'BiologicalProcess'
    AgeAnno['kg_source'] = 'AgeAnnoMO'
    AgeAnno['kg_type'] = 'Aging'
    if 'tail_detail_name' not in AgeAnno.columns:
        AgeAnno['tail_detail_name'] = AgeAnno['tail'].map(GO_dict)
    else:
        AgeAnno['tail_detail_name'] = AgeAnno['tail_detail_name'].fillna(AgeAnno['tail'].map(GO_dict))
    print(f"AgeAnno: {len(AgeAnno):,} rows")
else:
    print("Warning: ageanno_processed_mo path not found")
    AgeAnno = pd.DataFrame(columns=REQUIRED_COLS)
AgeAnno['species'] = 'Homo sapiens'
AgeAnno['kg_type'] = 'Aging'
AgeAnno

AgeAnno: 1,556 rows

,head,relation,tail,head_type,tail_type,relation_source,species,tail_detail_name,head_detail_name,head_id_is,tail_id_is,kg_source,kg_type
0,EIF1,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,eukaryotic translation initiation factor 1,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
1,SELPLG,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,selectin P ligand,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
2,LINC01592,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,long intergenic non-protein coding RNA 1592,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
3,PDE3A,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,phosphodiesterase 3A,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
4,OSBPL3,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,oxysterol binding protein like 3,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1551,DUSP5,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,dual specificity phosphatase 5,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
1552,SMIM21,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,small integral membrane protein 21,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
1553,SLC35A1,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,solute carrier family 35 member A1,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
1554,CLGN,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,calmegin,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
1555,MIR4523,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,microRNA 4523,NCBI_ID,Quick_GO,AgeAnnoMO,Aging

# 2. agingatlas (Human/Human_Gene_BiologicalProcess.csv)

In [4]:
agingatlas_path = PROC_DIR + 'agingatlas/Human/Human_Gene_BiologicalProcess.csv'
if os.path.exists(agingatlas_path):
    AgingAtlas = pd.read_csv(agingatlas_path)
    AgingAtlas.columns = AgingAtlas.columns.str.lower()
    if 'kgsource' in AgingAtlas.columns:
        AgingAtlas = AgingAtlas.rename(columns={'kgsource': 'kg_source'})
    if 'head_name' in AgingAtlas.columns:
        AgingAtlas = AgingAtlas.rename(columns={'head_name': 'head_detail_name'})
    if 'tail_name' in AgingAtlas.columns:
        AgingAtlas = AgingAtlas.rename(columns={'tail_name': 'tail_detail_name'})
    if 'relation_source' in AgingAtlas.columns:
        AgingAtlas = AgingAtlas.rename(columns={'relation_source': 'kg_source'})
    AgingAtlas['head_id_is'] = 'NCBI_ID'
    AgingAtlas['tail_id_is'] = 'Quick_GO'
    AgingAtlas['relation'] = 'Gene_BiologicalProcess'
    AgingAtlas['head_type'] = 'Gene'
    AgingAtlas['tail_type'] = 'BiologicalProcess'
    AgingAtlas['kg_source'] = 'AgingAtlas'
    if 'tail_detail_name' not in AgingAtlas.columns:
        AgingAtlas['tail_detail_name'] = AgingAtlas['tail'].map(GO_dict)
    else:
        AgingAtlas['tail_detail_name'] = AgingAtlas['tail_detail_name'].fillna(AgingAtlas['tail'].map(GO_dict))
    print(f"AgingAtlas: {len(AgingAtlas):,} rows")
else:
    print("Warning: agingatlas path not found")
    AgingAtlas = pd.DataFrame(columns=REQUIRED_COLS)
AgingAtlas['species'] = 'Homo sapiens'
AgingAtlas['kg_type'] = 'Aging'
AgingAtlas

AgingAtlas: 503 rows

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_source,species,symbol,gene_set,kegg_id,kegg_name,literature_name,literature_link,data_type,kg_type
0,IL2RB,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Interleukin 2 Receptor Subunit Beta,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,IL2RB,others,hsa04060,Cytokine-cytokine receptor interaction,Defective CD8 Signaling Pathways Delay Rejecti...,10.1097/TP.0000000000000886,Associative,Aging
1,PSAT1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Phosphoserine Aminotransferase 1,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,PSAT1,others,hsa00260 hsa00260,"Glycine, serine and threonine metabolism",Serine Metabolism Controls Dental Pulp Stem Ce...,10.1177/0022034520958374,Associative,Aging
2,A2M,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,alpha-2-macroglobulin,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,A2M,others,unknown,Unknown,Alpha-2 Macroglobulin Is Genetically Associate...,10.1038/1243,Associative,Aging
3,AARS1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Alanyl-TRNA Synthetase 1,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,AARS1,loss of proteostasis,hsa00970,Aminoacyl-tRNA biosynthesis,Altered Sensory Neuron Development in CMT2D Mi...,10.3389/fncel.2020.00232,Associative,Aging
4,ABL1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"ABL proto-oncogene 1, non-receptor tyrosine ki...",aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,ABL1,genomic instability,hsa04110,Cell cycle,p73 Is Regulated by Tyrosine Kinase c-Abl in t...,10.1038/21704,Associative,Aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,XRCC5,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,X-ray repair complementing defective repair in...,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,XRCC5,telomere attrition,unknown,Unknown,Human Ku70/80 Associates Physically With Telom...,10.1074/jbc.M208542200,Associative,Aging
499,XRCC6,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,X-ray repair complementing defective repair in...,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,XRCC6,others,unknown,Unknown,Human Ku70/80 associates physically with telom...,10.1074/jbc.M208542200,Associative,Aging
500,YWHAZ,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,tyrosine 3-monooxygenase/tryptophan 5-monooxyg...,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,YWHAZ,stem cell exhaustion,hsa04110,Cell cycle,Proteomic Analysis Identifies That 14-3-3zeta ...,10.1073/pnas.0406499101,Associative,Aging
501,ZAP70,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Zeta Chain Of T Cell Receptor Associated Prote...,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,ZAP70,NF-?B related gene,hsa04064,NF-kappa B signaling pathway,Otud7b facilitates T cell activation and infla...,10.1084/jem.20151426,Associative,Aging
502,ZMPSTE24,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc metallopeptidase STE24,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,ZMPSTE24,genomic instability,unknown,Unknown,Loss of ZMPSTE24 (FACE-1) Causes Autosomal Rec...,10.1093/hmg/ddi159,Associative,Aging

### 3 GenAge

In [5]:
genage_path = PROC_DIR + 'genage/Human/Human_Gene_BiologicalProcess.csv'
genage = pd.read_csv(genage_path)
genage['species'] = 'Homo sapiens'
genage['kg_type'] = 'Aging'
genage

,head,relation,tail,head_type,tail_type,kg_source,head_id_is,tail_id_is,relation_type,head_detail_name,tail_detail_name,species,kg_type
0,GHR,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,growth hormone receptor,aging,Homo sapiens,Aging
1,GHRH,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,growth hormone releasing hormone,aging,Homo sapiens,Aging
2,SHC1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,SHC adaptor protein 1,aging,Homo sapiens,Aging
3,POU1F1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,POU class 1 homeobox 1,aging,Homo sapiens,Aging
4,PROP1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,PROP paired-like homeobox 1,aging,Homo sapiens,Aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,TRAP1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,TNF receptor associated protein 1,aging,Homo sapiens,Aging
298,TRPV1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,transient receptor potential cation channel su...,aging,Homo sapiens,Aging
299,NFE2L1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,NFE2 like bZIP transcription factor 1,aging,Homo sapiens,Aging
300,IFNB1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,interferon beta 1,aging,Homo sapiens,Aging
301,GDF11,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,growth differentiation factor 11,aging,Homo sapiens,Aging

## 4 DRKG

In [6]:
drkg_path = PROC_DIR + 'DRKG/DRKG_Gene_Biological_Process.csv'
if os.path.exists(drkg_path):
    DRKG = pd.read_csv(drkg_path)
    DRKG.columns = DRKG.columns.str.lower()
    if 'head_name' in DRKG.columns:
        DRKG = DRKG.rename(columns={'head_name': 'head_detail_name'})
    if 'tail_name' in DRKG.columns:
        DRKG = DRKG.rename(columns={'tail_name': 'tail_detail_name'})
    DRKG['head_id_is'] = 'NCBI_ID'
    DRKG['tail_id_is'] = 'Quick_GO'
    DRKG['relation'] = 'Gene_BiologicalProcess'
    DRKG['head_type'] = 'Gene'
    DRKG['tail_type'] = 'BiologicalProcess'
    DRKG['kg_source'] = 'DRKG'
    DRKG['kg_type'] = 'Generalised'
    DRKG['tail_detail_name'] = DRKG['tail'].map(GO_dict)
    print(f"DRKG: {len(DRKG):,} rows")
else:
    print("Warning: DRKG path not found")
    DRKG = pd.DataFrame(columns=REQUIRED_COLS)
DRKG['species'] = 'Homo sapiens'
DRKG['kg_type'] = 'Generalised'
DRKG

DRKG: 559,453 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_detail_name,head_detail_name,head_ens,tail_detail_name,head_id_is,tail_id_is,head_orignal,tail_orignal,kg_type,species
0,SOCS3,Gene_BiologicalProcess,GO:0071357,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,9021,suppressor of cytokine signaling 3,ENSG00000184557,cellular response to type I interferon,NCBI_ID,Quick_GO,Gene::9021,Biological Process::GO:0071357,Generalised,Homo sapiens
1,ASB2,Gene_BiologicalProcess,GO:0098780,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,51676,ankyrin repeat and SOCS box containing 2,ENSG00000100628,response to mitochondrial depolarisation,NCBI_ID,Quick_GO,Gene::51676,Biological Process::GO:0098780,Generalised,Homo sapiens
2,ABCA1,Gene_BiologicalProcess,GO:0055088,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,19,ATP binding cassette subfamily A member 1,ENSG00000165029,lipid homeostasis,NCBI_ID,Quick_GO,Gene::19,Biological Process::GO:0055088,Generalised,Homo sapiens
3,HNMT,Gene_BiologicalProcess,GO:0010243,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,3176,histamine N-methyltransferase,ENSG00000150540,obsolete response to organonitrogen compound,NCBI_ID,Quick_GO,Gene::3176,Biological Process::GO:0010243,Generalised,Homo sapiens
4,HBA1,Gene_BiologicalProcess,GO:0006898,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,3039,hemoglobin subunit alpha 1,ENSG00000206172,receptor-mediated endocytosis,NCBI_ID,Quick_GO,Gene::3039,Biological Process::GO:0006898,Generalised,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559448,SLC35B2,Gene_BiologicalProcess,GO:0042451,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,347734,solute carrier family 35 member B2,ENSG00000157593,purine nucleoside biosynthetic process,NCBI_ID,Quick_GO,Gene::347734,Biological Process::GO:0042451,Generalised,Homo sapiens
559449,SCFD2,Gene_BiologicalProcess,GO:0048278,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,152579,sec1 family domain containing 2,ENSG00000184178,vesicle docking,NCBI_ID,Quick_GO,Gene::152579,Biological Process::GO:0048278,Generalised,Homo sapiens
559450,APOM,Gene_BiologicalProcess,GO:0097006,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,55937,apolipoprotein M,ENSG00000204444,regulation of plasma lipoprotein particle levels,NCBI_ID,Quick_GO,Gene::55937,Biological Process::GO:0097006,Generalised,Homo sapiens
559451,CYP2R1,Gene_BiologicalProcess,GO:0044107,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,120227,cytochrome P450 family 2 subfamily R member 1,ENSG00000186104,obsolete cellular alcohol metabolic process,NCBI_ID,Quick_GO,Gene::120227,Biological Process::GO:0044107,Generalised,Homo sapiens
559452,EDAR,Gene_BiologicalProcess,GO:1902533,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,10913,ectodysplasin A receptor,ENSG00000135960,positive regulation of intracellular signal tr...,NCBI_ID,Quick_GO,Gene::10913,Biological Process::GO:1902533,Generalised,Homo sapiens


# 5. GPKG

In [7]:

gpkg_path = PROC_DIR + 'GPKG/Gene_BiologicalProcess_GPKG.csv'
if os.path.exists(gpkg_path):
    GPKG = pd.read_csv(gpkg_path)
    GPKG.columns = GPKG.columns.str.lower()
    if 'head_name' in GPKG.columns:
        GPKG = GPKG.rename(columns={'head_name': 'head_detail_name'})
    if 'tail_name' in GPKG.columns:
        GPKG = GPKG.rename(columns={'tail_name': 'tail_detail_name'})
    GPKG['head_id_is'] = 'NCBI_ID'
    GPKG['tail_id_is'] = 'Quick_GO'
    GPKG['relation'] = 'Gene_BiologicalProcess'
    GPKG['head_type'] = 'Gene'
    GPKG['tail_type'] = 'BiologicalProcess'
    GPKG['kg_source'] = 'GPKG'
    GPKG['kg_type'] = 'Generalised'
    if 'tail_detail_name' not in GPKG.columns:
        GPKG['tail_detail_name'] = GPKG['tail'].map(GO_dict)
    else:
        GPKG['tail_detail_name'] = GPKG['tail_detail_name'].fillna(GPKG['tail'].map(GO_dict))
    print(f"GPKG: {len(GPKG):,} rows")
else:
    print("Warning: GPKG path not found")
    GPKG = pd.DataFrame(columns=REQUIRED_COLS)
GPKG['species'] = 'Homo sapiens'
GPKG['kg_type'] = 'Generalised'
GPKG

GPKG: 93,395 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_orignal,head_alias_mapped,head_detail_name,head_id_is,tail_detail_name,tail_id_is,kg_type,species
0,TRAV27,Gene_BiologicalProcess,GO:0050830,Gene,associated,BiologicalProcess,GPKG,ENSG00000211809,TRAV27,T cell receptor alpha variable 27,NCBI_ID,defense response to Gram-positive bacterium,Quick_GO,Generalised,Homo sapiens
1,TRAV27,Gene_BiologicalProcess,GO:0009617,Gene,associated,BiologicalProcess,GPKG,ENSG00000211809,TRAV27,T cell receptor alpha variable 27,NCBI_ID,response to bacterium,Quick_GO,Generalised,Homo sapiens
2,TRAV27,Gene_BiologicalProcess,GO:0006955,Gene,associated,BiologicalProcess,GPKG,ENSG00000211809,TRAV27,T cell receptor alpha variable 27,NCBI_ID,immune response,Quick_GO,Generalised,Homo sapiens
3,MEIKIN,Gene_BiologicalProcess,GO:0051754,Gene,associated,BiologicalProcess,GPKG,ENSG00000239642,MEIKIN,meiotic kinetochore factor,NCBI_ID,"meiotic sister chromatid cohesion, centromeric",Quick_GO,Generalised,Homo sapiens
4,MEIKIN,Gene_BiologicalProcess,GO:0007060,Gene,associated,BiologicalProcess,GPKG,ENSG00000239642,MEIKIN,meiotic kinetochore factor,NCBI_ID,male meiosis chromosome segregation,Quick_GO,Generalised,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93390,CAPN12,Gene_BiologicalProcess,GO:0006508,Gene,associated,BiologicalProcess,GPKG,ENSG00000182472,CAPN12,calpain 12,NCBI_ID,proteolysis,Quick_GO,Generalised,Homo sapiens
93391,RNF121,Gene_BiologicalProcess,GO:0030433,Gene,associated,BiologicalProcess,GPKG,ENSG00000137522,RNF121,ring finger protein 121,NCBI_ID,obsolete ubiquitin-dependent ERAD pathway,Quick_GO,Generalised,Homo sapiens
93392,DHDH,Gene_BiologicalProcess,GO:0042843,Gene,associated,BiologicalProcess,GPKG,ENSG00000104808,DHDH,dihydrodiol dehydrogenase,NCBI_ID,D-xylose catabolic process,Quick_GO,Generalised,Homo sapiens
93393,GPRIN2,Gene_BiologicalProcess,GO:0031175,Gene,associated,BiologicalProcess,GPKG,ENSG00000204175,GPRIN2,G protein regulated inducer of neurite outgrow...,NCBI_ID,neuron projection development,Quick_GO,Generalised,Homo sapiens
93394,ZNF625,Gene_BiologicalProcess,GO:0006357,Gene,associated,BiologicalProcess,GPKG,ENSG00000257591,ZNF625,zinc finger protein 625,NCBI_ID,regulation of transcription by RNA polymerase II,Quick_GO,Generalised,Homo sapiens

## 6. Hetionet

In [8]:
hetionet_path = PROC_DIR + 'Hetionet/Gene_BiologicalProcess_Hetionet.csv'
if os.path.exists(hetionet_path):
    Hetionet = pd.read_csv(hetionet_path)
    Hetionet.columns = Hetionet.columns.str.lower()
    if 'tail_name' in Hetionet.columns:
        Hetionet = Hetionet.rename(columns={'tail_name': 'tail_detail_name'})
    Hetionet['head_id_is'] = 'NCBI_ID'
    Hetionet['tail_id_is'] = 'Quick_GO'
    Hetionet['relation'] = 'Gene_BiologicalProcess'
    Hetionet['head_type'] = 'Gene'
    Hetionet['tail_type'] = 'BiologicalProcess'
    Hetionet['kg_source'] = 'Hetionet'
    Hetionet['kg_type'] = 'Generalised'
    if 'tail_detail_name' not in Hetionet.columns:
        Hetionet['tail_detail_name'] = Hetionet['tail'].map(GO_dict)
    else:
        Hetionet['tail_detail_name'] = Hetionet['tail_detail_name'].fillna(Hetionet['tail'].map(GO_dict))
    print(f"Hetionet: {len(Hetionet):,} rows")
else:
    print("Warning: Hetionet path not found")
    Hetionet = pd.DataFrame(columns=REQUIRED_COLS)

Hetionet['species'] = 'Homo sapiens'
Hetionet['kg_type'] = 'Generalised'
Hetionet

Hetionet: 559,453 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_name,head_detail_name,tail_detail_name,kg_type,species
0,SOCS3,Gene_BiologicalProcess,GO:0071357,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,9021,suppressor of cytokine signaling 3,cellular response to type I interferon,Generalised,Homo sapiens
1,ASB2,Gene_BiologicalProcess,GO:0098780,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,51676,ankyrin repeat and SOCS box containing 2,response to mitochondrial depolarisation,Generalised,Homo sapiens
2,ABCA1,Gene_BiologicalProcess,GO:0055088,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,19,ATP binding cassette subfamily A member 1,lipid homeostasis,Generalised,Homo sapiens
3,HNMT,Gene_BiologicalProcess,GO:0010243,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,3176,histamine N-methyltransferase,obsolete response to organonitrogen compound,Generalised,Homo sapiens
4,HBA1,Gene_BiologicalProcess,GO:0006898,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,3039,hemoglobin subunit alpha 1,receptor-mediated endocytosis,Generalised,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559448,SLC35B2,Gene_BiologicalProcess,GO:0042451,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,347734,solute carrier family 35 member B2,purine nucleoside biosynthetic process,Generalised,Homo sapiens
559449,SCFD2,Gene_BiologicalProcess,GO:0048278,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,152579,sec1 family domain containing 2,vesicle docking,Generalised,Homo sapiens
559450,APOM,Gene_BiologicalProcess,GO:0097006,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,55937,apolipoprotein M,regulation of plasma lipoprotein particle levels,Generalised,Homo sapiens
559451,CYP2R1,Gene_BiologicalProcess,GO:0044107,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,120227,cytochrome P450 family 2 subfamily R member 1,obsolete cellular alcohol metabolic process,Generalised,Homo sapiens
559452,EDAR,Gene_BiologicalProcess,GO:1902533,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,10913,ectodysplasin A receptor,positive regulation of intracellular signal tr...,Generalised,Homo sapiens

# 7. Monarch

In [9]:
monarch_path = PROC_DIR + 'Monarch/Human/Gene_Human_BiologicalProcess_MONARCH.csv'
if os.path.exists(monarch_path):
    Monarch = pd.read_csv(monarch_path)
    Monarch.columns = Monarch.columns.str.lower()
    if 'kgsource' in Monarch.columns:
        Monarch = Monarch.rename(columns={'kgsource': 'kg_source'})
    if 'head_name' in Monarch.columns:
        Monarch = Monarch.rename(columns={'head_name': 'head_detail_name'})
    if 'tail_name' in Monarch.columns:
        Monarch = Monarch.rename(columns={'tail_name': 'tail_detail_name'})
    Monarch['head_id_is'] = 'NCBI_ID'
    Monarch['tail_id_is'] = 'Quick_GO'
    Monarch['relation'] = 'Gene_BiologicalProcess'
    Monarch['head_type'] = 'Gene'
    Monarch['tail_type'] = 'BiologicalProcess'
    Monarch['kg_source'] = 'Monarch_KG'
    Monarch['kg_type'] = 'Generalised'
    if 'tail_detail_name' not in Monarch.columns:
        Monarch['tail_detail_name'] = Monarch['tail'].map(GO_dict)
    else:
        Monarch['tail_detail_name'] = Monarch['tail_detail_name'].fillna(Monarch['tail'].map(GO_dict))
    print(f"Monarch: {len(Monarch):,} rows")
else:
    print("Warning: Monarch path not found")
    Monarch = pd.DataFrame(columns=REQUIRED_COLS)
Monarch['species'] = 'Homo sapiens'
Monarch['kg_type'] = 'Generalised'
Monarch

Monarch: 166,291 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,kg_source,head_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_detail_name,tail_detail_name,head_orignal,species_species,kg_type,species
0,ADRA1B,Gene_BiologicalProcess,GO:0007200,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,adrenoceptor alpha 1B,Homo sapiens,NaN,NCBI_ID,Quick_GO,ADRA1B,phospholipase C-activating G protein-coupled r...,HGNC:278,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
1,ATP13A4,Gene_BiologicalProcess,GO:0006874,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,ATPase 13A4,Homo sapiens,NaN,NCBI_ID,Quick_GO,ATP13A4,intracellular calcium ion homeostasis,HGNC:25422,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
2,TGIF2,Gene_BiologicalProcess,GO:0000122,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,TGFB induced factor homeobox 2,Homo sapiens,NaN,NCBI_ID,Quick_GO,TGIF2,negative regulation of transcription by RNA po...,HGNC:15764,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
3,CACNG7,Gene_BiologicalProcess,GO:0051968,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,calcium voltage-gated channel auxiliary subuni...,Homo sapiens,NaN,NCBI_ID,Quick_GO,CACNG7,"positive regulation of synaptic transmission, ...",HGNC:13626,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
4,IGKV2D-28,Gene_BiologicalProcess,GO:0006955,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,immunoglobulin kappa variable 2D-28,Homo sapiens,NaN,NCBI_ID,Quick_GO,IGKV2D-28,immune response,HGNC:5799,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166286,HIKESHI,Gene_BiologicalProcess,GO:0006606,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,heat shock protein nuclear import factor hikeshi,Homo sapiens,NaN,NCBI_ID,Quick_GO,HIKESHI,protein import into nucleus,HGNC:26938,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
166287,TOP3A,Gene_BiologicalProcess,GO:0006310,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,DNA topoisomerase III alpha,Homo sapiens,NaN,NCBI_ID,Quick_GO,TOP3A,DNA recombination,HGNC:11992,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
166288,CCDC93,Gene_BiologicalProcess,GO:0006893,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,coiled-coil domain containing 93,Homo sapiens,NaN,NCBI_ID,Quick_GO,CCDC93,Golgi to plasma membrane transport,HGNC:25611,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
166289,SPTSSB,Gene_BiologicalProcess,GO:0007029,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,serine palmitoyltransferase small subunit B,Homo sapiens,NaN,NCBI_ID,Quick_GO,SPTSSB,endoplasmic reticulum organization,HGNC:24045,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
166290,B3GNT9,Gene_BiologicalProcess,GO:0006493,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,"UDP-GlcNAc:betaGal beta-1,3-N-acetylglucosamin...",Homo sapiens,NaN,NCBI_ID,Quick_GO,B3GNT9,protein O-linked glycosylation,HGNC:28714,Homo sapiens_Homo sapiens,Generalised,Homo sapiens

## 8. TARKG

In [10]:
tarkg_path = PROC_DIR + 'TARKG/Gene_BiologicalProcess_TARKG.csv'
if os.path.exists(tarkg_path):
    TARKG = pd.read_csv(tarkg_path)
    TARKG.columns = TARKG.columns.str.lower()
    if 'head_name' in TARKG.columns:
        TARKG = TARKG.rename(columns={'head_name': 'head_detail_name'})
    if 'tail_name' in TARKG.columns:
        TARKG = TARKG.rename(columns={'tail_name': 'tail_detail_name'})
    TARKG['head_id_is'] = 'NCBI_ID'
    TARKG['tail_id_is'] = 'Quick_GO'
    TARKG['relation'] = 'Gene_BiologicalProcess'
    TARKG['head_type'] = 'Gene'
    TARKG['tail_type'] = 'BiologicalProcess'
    TARKG['kg_source'] = 'TARKG'
    TARKG['kg_type'] = 'Generalised'
    if 'tail_detail_name' not in TARKG.columns:
        TARKG['tail_detail_name'] = TARKG['tail'].map(GO_dict)
    else:
        TARKG['tail_detail_name'] = TARKG['tail_detail_name'].fillna(TARKG['tail'].map(GO_dict))
    print(f"TARKG: {len(TARKG):,} rows")
else:
    print("Warning: TARKG path not found")
    TARKG = pd.DataFrame(columns=REQUIRED_COLS)
TARKG['species'] = 'Homo sapiens'
TARKG

TARKG: 1,045,588 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_index,kg,change,kg_type,species
0,AHCTF1,Gene_BiologicalProcess,GO:0071705,Gene,GpBP,BiologicalProcess,TARKG,AT-hook containing transcription factor 1,nitrogen compound transport,NCBI_ID,Quick_GO,Hetionet-183676,Hetionet,0,Generalised,Homo sapiens
1,AHCTF1,Gene_BiologicalProcess,GO:0071705,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,AT-hook containing transcription factor 1,nitrogen compound transport,NCBI_ID,Quick_GO,DRKG-2054878,DRKG,0,Generalised,Homo sapiens
2,NUP62,Gene_BiologicalProcess,GO:0071705,Gene,GpBP,BiologicalProcess,TARKG,nucleoporin 62,nitrogen compound transport,NCBI_ID,Quick_GO,Hetionet-532807,Hetionet,0,Generalised,Homo sapiens
3,NUP62,Gene_BiologicalProcess,GO:0071705,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,nucleoporin 62,nitrogen compound transport,NCBI_ID,Quick_GO,DRKG-2404009,DRKG,0,Generalised,Homo sapiens
4,NUP37,Gene_BiologicalProcess,GO:0071705,Gene,GpBP,BiologicalProcess,TARKG,nucleoporin 37,nitrogen compound transport,NCBI_ID,Quick_GO,Hetionet-149653,Hetionet,0,Generalised,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1045583,SLC35B4,Gene_BiologicalProcess,GO:1990569,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,solute carrier family 35 member B4,UDP-N-acetylglucosamine transmembrane transport,NCBI_ID,Quick_GO,DRKG-2332823,DRKG,0,Generalised,Homo sapiens
1045584,PCYOX1,Gene_BiologicalProcess,GO:0030328,Gene,GpBP,BiologicalProcess,TARKG,prenylcysteine oxidase 1,prenylcysteine catabolic process,NCBI_ID,Quick_GO,Hetionet-295606,Hetionet,0,Generalised,Homo sapiens
1045585,PCYOX1,Gene_BiologicalProcess,GO:0030328,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,prenylcysteine oxidase 1,prenylcysteine catabolic process,NCBI_ID,Quick_GO,DRKG-2166808,DRKG,0,Generalised,Homo sapiens
1045586,PCYOX1L,Gene_BiologicalProcess,GO:0030328,Gene,GpBP,BiologicalProcess,TARKG,prenylcysteine oxidase 1 like,prenylcysteine catabolic process,NCBI_ID,Quick_GO,Hetionet-177161,Hetionet,0,Generalised,Homo sapiens
1045587,PCYOX1L,Gene_BiologicalProcess,GO:0030328,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,prenylcysteine oxidase 1 like,prenylcysteine catabolic process,NCBI_ID,Quick_GO,DRKG-2048363,DRKG,0,Generalised,Homo sapiens

In [11]:
source_dfs = {
    "AgeAnno": AgeAnno,
    "AgingAtlas": AgingAtlas,
    "DRKG": DRKG,
    "genage": genage,
    "GPKG": GPKG,
    "Hetionet": Hetionet,
    "Monarch": Monarch,
    "TARKG": TARKG
}

for name, df in source_dfs.items():
    print(f"name: {name}")
    display(df)   # or just print(df)

name: AgeAnno

,head,relation,tail,head_type,tail_type,relation_source,species,tail_detail_name,head_detail_name,head_id_is,tail_id_is,kg_source,kg_type
0,EIF1,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,eukaryotic translation initiation factor 1,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
1,SELPLG,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,selectin P ligand,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
2,LINC01592,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,long intergenic non-protein coding RNA 1592,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
3,PDE3A,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,phosphodiesterase 3A,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
4,OSBPL3,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,oxysterol binding protein like 3,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1551,DUSP5,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,dual specificity phosphatase 5,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
1552,SMIM21,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,small integral membrane protein 21,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
1553,SLC35A1,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,solute carrier family 35 member A1,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
1554,CLGN,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,calmegin,NCBI_ID,Quick_GO,AgeAnnoMO,Aging
1555,MIR4523,Gene_BiologicalProcess,GO:1111113,Gene,BiologicalProcess,AgeAnnoMO,Homo sapiens,Epigenetic Alterations,microRNA 4523,NCBI_ID,Quick_GO,AgeAnnoMO,Aging

name: AgingAtlas

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_source,species,symbol,gene_set,kegg_id,kegg_name,literature_name,literature_link,data_type,kg_type
0,IL2RB,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Interleukin 2 Receptor Subunit Beta,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,IL2RB,others,hsa04060,Cytokine-cytokine receptor interaction,Defective CD8 Signaling Pathways Delay Rejecti...,10.1097/TP.0000000000000886,Associative,Aging
1,PSAT1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Phosphoserine Aminotransferase 1,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,PSAT1,others,hsa00260 hsa00260,"Glycine, serine and threonine metabolism",Serine Metabolism Controls Dental Pulp Stem Ce...,10.1177/0022034520958374,Associative,Aging
2,A2M,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,alpha-2-macroglobulin,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,A2M,others,unknown,Unknown,Alpha-2 Macroglobulin Is Genetically Associate...,10.1038/1243,Associative,Aging
3,AARS1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Alanyl-TRNA Synthetase 1,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,AARS1,loss of proteostasis,hsa00970,Aminoacyl-tRNA biosynthesis,Altered Sensory Neuron Development in CMT2D Mi...,10.3389/fncel.2020.00232,Associative,Aging
4,ABL1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"ABL proto-oncogene 1, non-receptor tyrosine ki...",aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,ABL1,genomic instability,hsa04110,Cell cycle,p73 Is Regulated by Tyrosine Kinase c-Abl in t...,10.1038/21704,Associative,Aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,XRCC5,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,X-ray repair complementing defective repair in...,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,XRCC5,telomere attrition,unknown,Unknown,Human Ku70/80 Associates Physically With Telom...,10.1074/jbc.M208542200,Associative,Aging
499,XRCC6,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,X-ray repair complementing defective repair in...,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,XRCC6,others,unknown,Unknown,Human Ku70/80 associates physically with telom...,10.1074/jbc.M208542200,Associative,Aging
500,YWHAZ,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,tyrosine 3-monooxygenase/tryptophan 5-monooxyg...,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,YWHAZ,stem cell exhaustion,hsa04110,Cell cycle,Proteomic Analysis Identifies That 14-3-3zeta ...,10.1073/pnas.0406499101,Associative,Aging
501,ZAP70,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Zeta Chain Of T Cell Receptor Associated Prote...,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,ZAP70,NF-?B related gene,hsa04064,NF-kappa B signaling pathway,Otud7b facilitates T cell activation and infla...,10.1084/jem.20151426,Associative,Aging
502,ZMPSTE24,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc metallopeptidase STE24,aging,NCBI_ID,Quick_GO,AgingAtlas,Homo sapiens,ZMPSTE24,genomic instability,unknown,Unknown,Loss of ZMPSTE24 (FACE-1) Causes Autosomal Rec...,10.1093/hmg/ddi159,Associative,Aging

name: DRKG

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_detail_name,head_detail_name,head_ens,tail_detail_name,head_id_is,tail_id_is,head_orignal,tail_orignal,kg_type,species
0,SOCS3,Gene_BiologicalProcess,GO:0071357,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,9021,suppressor of cytokine signaling 3,ENSG00000184557,cellular response to type I interferon,NCBI_ID,Quick_GO,Gene::9021,Biological Process::GO:0071357,Generalised,Homo sapiens
1,ASB2,Gene_BiologicalProcess,GO:0098780,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,51676,ankyrin repeat and SOCS box containing 2,ENSG00000100628,response to mitochondrial depolarisation,NCBI_ID,Quick_GO,Gene::51676,Biological Process::GO:0098780,Generalised,Homo sapiens
2,ABCA1,Gene_BiologicalProcess,GO:0055088,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,19,ATP binding cassette subfamily A member 1,ENSG00000165029,lipid homeostasis,NCBI_ID,Quick_GO,Gene::19,Biological Process::GO:0055088,Generalised,Homo sapiens
3,HNMT,Gene_BiologicalProcess,GO:0010243,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,3176,histamine N-methyltransferase,ENSG00000150540,obsolete response to organonitrogen compound,NCBI_ID,Quick_GO,Gene::3176,Biological Process::GO:0010243,Generalised,Homo sapiens
4,HBA1,Gene_BiologicalProcess,GO:0006898,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,3039,hemoglobin subunit alpha 1,ENSG00000206172,receptor-mediated endocytosis,NCBI_ID,Quick_GO,Gene::3039,Biological Process::GO:0006898,Generalised,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559448,SLC35B2,Gene_BiologicalProcess,GO:0042451,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,347734,solute carrier family 35 member B2,ENSG00000157593,purine nucleoside biosynthetic process,NCBI_ID,Quick_GO,Gene::347734,Biological Process::GO:0042451,Generalised,Homo sapiens
559449,SCFD2,Gene_BiologicalProcess,GO:0048278,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,152579,sec1 family domain containing 2,ENSG00000184178,vesicle docking,NCBI_ID,Quick_GO,Gene::152579,Biological Process::GO:0048278,Generalised,Homo sapiens
559450,APOM,Gene_BiologicalProcess,GO:0097006,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,55937,apolipoprotein M,ENSG00000204444,regulation of plasma lipoprotein particle levels,NCBI_ID,Quick_GO,Gene::55937,Biological Process::GO:0097006,Generalised,Homo sapiens
559451,CYP2R1,Gene_BiologicalProcess,GO:0044107,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,120227,cytochrome P450 family 2 subfamily R member 1,ENSG00000186104,obsolete cellular alcohol metabolic process,NCBI_ID,Quick_GO,Gene::120227,Biological Process::GO:0044107,Generalised,Homo sapiens
559452,EDAR,Gene_BiologicalProcess,GO:1902533,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,10913,ectodysplasin A receptor,ENSG00000135960,positive regulation of intracellular signal tr...,NCBI_ID,Quick_GO,Gene::10913,Biological Process::GO:1902533,Generalised,Homo sapiens

name: genage

,head,relation,tail,head_type,tail_type,kg_source,head_id_is,tail_id_is,relation_type,head_detail_name,tail_detail_name,species,kg_type
0,GHR,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,growth hormone receptor,aging,Homo sapiens,Aging
1,GHRH,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,growth hormone releasing hormone,aging,Homo sapiens,Aging
2,SHC1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,SHC adaptor protein 1,aging,Homo sapiens,Aging
3,POU1F1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,POU class 1 homeobox 1,aging,Homo sapiens,Aging
4,PROP1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,PROP paired-like homeobox 1,aging,Homo sapiens,Aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,TRAP1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,TNF receptor associated protein 1,aging,Homo sapiens,Aging
298,TRPV1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,transient receptor potential cation channel su...,aging,Homo sapiens,Aging
299,NFE2L1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,NFE2 like bZIP transcription factor 1,aging,Homo sapiens,Aging
300,IFNB1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,interferon beta 1,aging,Homo sapiens,Aging
301,GDF11,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,GenAge,NCBI_ID,Quick_GO,Causative,growth differentiation factor 11,aging,Homo sapiens,Aging

name: GPKG

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_orignal,head_alias_mapped,head_detail_name,head_id_is,tail_detail_name,tail_id_is,kg_type,species
0,TRAV27,Gene_BiologicalProcess,GO:0050830,Gene,associated,BiologicalProcess,GPKG,ENSG00000211809,TRAV27,T cell receptor alpha variable 27,NCBI_ID,defense response to Gram-positive bacterium,Quick_GO,Generalised,Homo sapiens
1,TRAV27,Gene_BiologicalProcess,GO:0009617,Gene,associated,BiologicalProcess,GPKG,ENSG00000211809,TRAV27,T cell receptor alpha variable 27,NCBI_ID,response to bacterium,Quick_GO,Generalised,Homo sapiens
2,TRAV27,Gene_BiologicalProcess,GO:0006955,Gene,associated,BiologicalProcess,GPKG,ENSG00000211809,TRAV27,T cell receptor alpha variable 27,NCBI_ID,immune response,Quick_GO,Generalised,Homo sapiens
3,MEIKIN,Gene_BiologicalProcess,GO:0051754,Gene,associated,BiologicalProcess,GPKG,ENSG00000239642,MEIKIN,meiotic kinetochore factor,NCBI_ID,"meiotic sister chromatid cohesion, centromeric",Quick_GO,Generalised,Homo sapiens
4,MEIKIN,Gene_BiologicalProcess,GO:0007060,Gene,associated,BiologicalProcess,GPKG,ENSG00000239642,MEIKIN,meiotic kinetochore factor,NCBI_ID,male meiosis chromosome segregation,Quick_GO,Generalised,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93390,CAPN12,Gene_BiologicalProcess,GO:0006508,Gene,associated,BiologicalProcess,GPKG,ENSG00000182472,CAPN12,calpain 12,NCBI_ID,proteolysis,Quick_GO,Generalised,Homo sapiens
93391,RNF121,Gene_BiologicalProcess,GO:0030433,Gene,associated,BiologicalProcess,GPKG,ENSG00000137522,RNF121,ring finger protein 121,NCBI_ID,obsolete ubiquitin-dependent ERAD pathway,Quick_GO,Generalised,Homo sapiens
93392,DHDH,Gene_BiologicalProcess,GO:0042843,Gene,associated,BiologicalProcess,GPKG,ENSG00000104808,DHDH,dihydrodiol dehydrogenase,NCBI_ID,D-xylose catabolic process,Quick_GO,Generalised,Homo sapiens
93393,GPRIN2,Gene_BiologicalProcess,GO:0031175,Gene,associated,BiologicalProcess,GPKG,ENSG00000204175,GPRIN2,G protein regulated inducer of neurite outgrow...,NCBI_ID,neuron projection development,Quick_GO,Generalised,Homo sapiens
93394,ZNF625,Gene_BiologicalProcess,GO:0006357,Gene,associated,BiologicalProcess,GPKG,ENSG00000257591,ZNF625,zinc finger protein 625,NCBI_ID,regulation of transcription by RNA polymerase II,Quick_GO,Generalised,Homo sapiens

name: Hetionet

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_name,head_detail_name,tail_detail_name,kg_type,species
0,SOCS3,Gene_BiologicalProcess,GO:0071357,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,9021,suppressor of cytokine signaling 3,cellular response to type I interferon,Generalised,Homo sapiens
1,ASB2,Gene_BiologicalProcess,GO:0098780,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,51676,ankyrin repeat and SOCS box containing 2,response to mitochondrial depolarisation,Generalised,Homo sapiens
2,ABCA1,Gene_BiologicalProcess,GO:0055088,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,19,ATP binding cassette subfamily A member 1,lipid homeostasis,Generalised,Homo sapiens
3,HNMT,Gene_BiologicalProcess,GO:0010243,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,3176,histamine N-methyltransferase,obsolete response to organonitrogen compound,Generalised,Homo sapiens
4,HBA1,Gene_BiologicalProcess,GO:0006898,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,3039,hemoglobin subunit alpha 1,receptor-mediated endocytosis,Generalised,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559448,SLC35B2,Gene_BiologicalProcess,GO:0042451,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,347734,solute carrier family 35 member B2,purine nucleoside biosynthetic process,Generalised,Homo sapiens
559449,SCFD2,Gene_BiologicalProcess,GO:0048278,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,152579,sec1 family domain containing 2,vesicle docking,Generalised,Homo sapiens
559450,APOM,Gene_BiologicalProcess,GO:0097006,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,55937,apolipoprotein M,regulation of plasma lipoprotein particle levels,Generalised,Homo sapiens
559451,CYP2R1,Gene_BiologicalProcess,GO:0044107,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,120227,cytochrome P450 family 2 subfamily R member 1,obsolete cellular alcohol metabolic process,Generalised,Homo sapiens
559452,EDAR,Gene_BiologicalProcess,GO:1902533,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,NCBI_ID,Quick_GO,10913,ectodysplasin A receptor,positive regulation of intracellular signal tr...,Generalised,Homo sapiens

name: Monarch

,head,relation,tail,head_type,relation_type,tail_type,relation_source,kg_source,head_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_detail_name,tail_detail_name,head_orignal,species_species,kg_type,species
0,ADRA1B,Gene_BiologicalProcess,GO:0007200,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,adrenoceptor alpha 1B,Homo sapiens,NaN,NCBI_ID,Quick_GO,ADRA1B,phospholipase C-activating G protein-coupled r...,HGNC:278,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
1,ATP13A4,Gene_BiologicalProcess,GO:0006874,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,ATPase 13A4,Homo sapiens,NaN,NCBI_ID,Quick_GO,ATP13A4,intracellular calcium ion homeostasis,HGNC:25422,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
2,TGIF2,Gene_BiologicalProcess,GO:0000122,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,TGFB induced factor homeobox 2,Homo sapiens,NaN,NCBI_ID,Quick_GO,TGIF2,negative regulation of transcription by RNA po...,HGNC:15764,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
3,CACNG7,Gene_BiologicalProcess,GO:0051968,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,calcium voltage-gated channel auxiliary subuni...,Homo sapiens,NaN,NCBI_ID,Quick_GO,CACNG7,"positive regulation of synaptic transmission, ...",HGNC:13626,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
4,IGKV2D-28,Gene_BiologicalProcess,GO:0006955,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,immunoglobulin kappa variable 2D-28,Homo sapiens,NaN,NCBI_ID,Quick_GO,IGKV2D-28,immune response,HGNC:5799,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166286,HIKESHI,Gene_BiologicalProcess,GO:0006606,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,heat shock protein nuclear import factor hikeshi,Homo sapiens,NaN,NCBI_ID,Quick_GO,HIKESHI,protein import into nucleus,HGNC:26938,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
166287,TOP3A,Gene_BiologicalProcess,GO:0006310,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,DNA topoisomerase III alpha,Homo sapiens,NaN,NCBI_ID,Quick_GO,TOP3A,DNA recombination,HGNC:11992,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
166288,CCDC93,Gene_BiologicalProcess,GO:0006893,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,coiled-coil domain containing 93,Homo sapiens,NaN,NCBI_ID,Quick_GO,CCDC93,Golgi to plasma membrane transport,HGNC:25611,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
166289,SPTSSB,Gene_BiologicalProcess,GO:0007029,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,serine palmitoyltransferase small subunit B,Homo sapiens,NaN,NCBI_ID,Quick_GO,SPTSSB,endoplasmic reticulum organization,HGNC:24045,Homo sapiens_Homo sapiens,Generalised,Homo sapiens
166290,B3GNT9,Gene_BiologicalProcess,GO:0006493,Gene,actively_involved_in,BiologicalProcess,infores:go-central,Monarch_KG,"UDP-GlcNAc:betaGal beta-1,3-N-acetylglucosamin...",Homo sapiens,NaN,NCBI_ID,Quick_GO,B3GNT9,protein O-linked glycosylation,HGNC:28714,Homo sapiens_Homo sapiens,Generalised,Homo sapiens

name: TARKG

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_index,kg,change,kg_type,species
0,AHCTF1,Gene_BiologicalProcess,GO:0071705,Gene,GpBP,BiologicalProcess,TARKG,AT-hook containing transcription factor 1,nitrogen compound transport,NCBI_ID,Quick_GO,Hetionet-183676,Hetionet,0,Generalised,Homo sapiens
1,AHCTF1,Gene_BiologicalProcess,GO:0071705,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,AT-hook containing transcription factor 1,nitrogen compound transport,NCBI_ID,Quick_GO,DRKG-2054878,DRKG,0,Generalised,Homo sapiens
2,NUP62,Gene_BiologicalProcess,GO:0071705,Gene,GpBP,BiologicalProcess,TARKG,nucleoporin 62,nitrogen compound transport,NCBI_ID,Quick_GO,Hetionet-532807,Hetionet,0,Generalised,Homo sapiens
3,NUP62,Gene_BiologicalProcess,GO:0071705,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,nucleoporin 62,nitrogen compound transport,NCBI_ID,Quick_GO,DRKG-2404009,DRKG,0,Generalised,Homo sapiens
4,NUP37,Gene_BiologicalProcess,GO:0071705,Gene,GpBP,BiologicalProcess,TARKG,nucleoporin 37,nitrogen compound transport,NCBI_ID,Quick_GO,Hetionet-149653,Hetionet,0,Generalised,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1045583,SLC35B4,Gene_BiologicalProcess,GO:1990569,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,solute carrier family 35 member B4,UDP-N-acetylglucosamine transmembrane transport,NCBI_ID,Quick_GO,DRKG-2332823,DRKG,0,Generalised,Homo sapiens
1045584,PCYOX1,Gene_BiologicalProcess,GO:0030328,Gene,GpBP,BiologicalProcess,TARKG,prenylcysteine oxidase 1,prenylcysteine catabolic process,NCBI_ID,Quick_GO,Hetionet-295606,Hetionet,0,Generalised,Homo sapiens
1045585,PCYOX1,Gene_BiologicalProcess,GO:0030328,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,prenylcysteine oxidase 1,prenylcysteine catabolic process,NCBI_ID,Quick_GO,DRKG-2166808,DRKG,0,Generalised,Homo sapiens
1045586,PCYOX1L,Gene_BiologicalProcess,GO:0030328,Gene,GpBP,BiologicalProcess,TARKG,prenylcysteine oxidase 1 like,prenylcysteine catabolic process,NCBI_ID,Quick_GO,Hetionet-177161,Hetionet,0,Generalised,Homo sapiens
1045587,PCYOX1L,Gene_BiologicalProcess,GO:0030328,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,prenylcysteine oxidase 1 like,prenylcysteine catabolic process,NCBI_ID,Quick_GO,DRKG-2048363,DRKG,0,Generalised,Homo sapiens

## 3 · Consolidate

In [26]:
source_dfs = [
    AgeAnno, AgingAtlas,
    DRKG, genage, GPKG, Hetionet, Monarch, TARKG
]
aligned = []
for df in source_dfs:
    df = df.copy()
    df = df.loc[:, ~df.columns.duplicated()]
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])
final_df = pd.concat(aligned, ignore_index=True)
final_df = final_df[final_df['head'].astype(str).str.upper() != 'NAN']

In [27]:
final_df[final_df['head'] == 'NAT2']

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
202794,NAT2,Gene_BiologicalProcess,GO:0006805,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,Generalised,NCBI_ID,Quick_GO,10,xenobiotic metabolic process,Homo sapiens
330138,NAT2,Gene_BiologicalProcess,GO:0009410,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,Generalised,NCBI_ID,Quick_GO,10,response to xenobiotic stimulus,Homo sapiens
385334,NAT2,Gene_BiologicalProcess,GO:0071466,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,Generalised,NCBI_ID,Quick_GO,10,cellular response to xenobiotic stimulus,Homo sapiens
855944,NAT2,Gene_BiologicalProcess,GO:0006805,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,Generalised,NCBI_ID,Quick_GO,N-acetyltransferase 2,xenobiotic metabolic process,Homo sapiens
983288,NAT2,Gene_BiologicalProcess,GO:0009410,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,Generalised,NCBI_ID,Quick_GO,N-acetyltransferase 2,response to xenobiotic stimulus,Homo sapiens
1038484,NAT2,Gene_BiologicalProcess,GO:0071466,Gene,Gene–participates–BiologicalProcess,BiologicalProcess,Hetionet,Generalised,NCBI_ID,Quick_GO,N-acetyltransferase 2,cellular response to xenobiotic stimulus,Homo sapiens
1257533,NAT2,Gene_BiologicalProcess,GO:0006805,Gene,actively_involved_in,BiologicalProcess,Monarch_KG,Generalised,NCBI_ID,Quick_GO,solute carrier family 38 member 1,xenobiotic metabolic process,Homo sapiens
1257534,NAT2,Gene_BiologicalProcess,GO:0006805,Gene,actively_involved_in,BiologicalProcess,Monarch_KG,Generalised,NCBI_ID,Quick_GO,solute carrier family 38 member 1,xenobiotic metabolic process,Homo sapiens
1747205,NAT2,Gene_BiologicalProcess,GO:0009410,Gene,GpBP,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,N-acetyltransferase 2,response to xenobiotic stimulus,Homo sapiens
1747206,NAT2,Gene_BiologicalProcess,GO:0009410,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,N-acetyltransferase 2,response to xenobiotic stimulus,Homo sapiens
2064345,NAT2,Gene_BiologicalProcess,GO:0071466,Gene,GpBP,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,N-acetyltransferase 2,cellular response to xenobiotic stimulus,Homo sapiens
2064346,NAT2,Gene_BiologicalProcess,GO:0071466,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,N-acetyltransferase 2,cellular response to xenobiotic stimulus,Homo sapiens
2064719,NAT2,Gene_BiologicalProcess,GO:0006805,Gene,GpBP,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,N-acetyltransferase 2,xenobiotic metabolic process,Homo sapiens
2064720,NAT2,Gene_BiologicalProcess,GO:0006805,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,N-acetyltransferase 2,xenobiotic metabolic process,Homo sapiens

In [28]:
final_df['head_detail_name'] = final_df['head'].map(NCBI_sym2desc_dict)
final_df

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,EIF1,Gene_BiologicalProcess,GO:1111113,Gene,None,BiologicalProcess,AgeAnnoMO,Aging,NCBI_ID,Quick_GO,eukaryotic translation initiation factor 1,Epigenetic Alterations,Homo sapiens
1,SELPLG,Gene_BiologicalProcess,GO:1111113,Gene,None,BiologicalProcess,AgeAnnoMO,Aging,NCBI_ID,Quick_GO,selectin P ligand,Epigenetic Alterations,Homo sapiens
2,LINC01592,Gene_BiologicalProcess,GO:1111113,Gene,None,BiologicalProcess,AgeAnnoMO,Aging,NCBI_ID,Quick_GO,long intergenic non-protein coding RNA 1592,Epigenetic Alterations,Homo sapiens
3,PDE3A,Gene_BiologicalProcess,GO:1111113,Gene,None,BiologicalProcess,AgeAnnoMO,Aging,NCBI_ID,Quick_GO,phosphodiesterase 3A,Epigenetic Alterations,Homo sapiens
4,OSBPL3,Gene_BiologicalProcess,GO:1111113,Gene,None,BiologicalProcess,AgeAnnoMO,Aging,NCBI_ID,Quick_GO,oxysterol binding protein like 3,Epigenetic Alterations,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2426536,SLC35B4,Gene_BiologicalProcess,GO:1990569,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,solute carrier family 35 member B4,UDP-N-acetylglucosamine transmembrane transport,Homo sapiens
2426537,PCYOX1,Gene_BiologicalProcess,GO:0030328,Gene,GpBP,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,prenylcysteine oxidase 1,prenylcysteine catabolic process,Homo sapiens
2426538,PCYOX1,Gene_BiologicalProcess,GO:0030328,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,prenylcysteine oxidase 1,prenylcysteine catabolic process,Homo sapiens
2426539,PCYOX1L,Gene_BiologicalProcess,GO:0030328,Gene,GpBP,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,prenylcysteine oxidase 1 like,prenylcysteine catabolic process,Homo sapiens
2426540,PCYOX1L,Gene_BiologicalProcess,GO:0030328,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,prenylcysteine oxidase 1 like,prenylcysteine catabolic process,Homo sapiens

In [29]:
final_df[final_df['head'] == 'ADA']

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
2115,ADA,Gene_BiologicalProcess,GO:0009394,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,Generalised,NCBI_ID,Quick_GO,adenosine deaminase,2'-deoxyribonucleotide metabolic process,Homo sapiens
5295,ADA,Gene_BiologicalProcess,GO:0009167,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,Generalised,NCBI_ID,Quick_GO,adenosine deaminase,purine ribonucleoside monophosphate metabolic ...,Homo sapiens
8592,ADA,Gene_BiologicalProcess,GO:0042113,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,Generalised,NCBI_ID,Quick_GO,adenosine deaminase,B cell activation,Homo sapiens
11480,ADA,Gene_BiologicalProcess,GO:0019439,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,Generalised,NCBI_ID,Quick_GO,adenosine deaminase,obsolete aromatic compound catabolic process,Homo sapiens
11750,ADA,Gene_BiologicalProcess,GO:0033628,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG,Generalised,NCBI_ID,Quick_GO,adenosine deaminase,regulation of cell adhesion mediated by integrin,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2417960,ADA,Gene_BiologicalProcess,GO:0046061,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,adenosine deaminase,dATP catabolic process,Homo sapiens
2417965,ADA,Gene_BiologicalProcess,GO:0042323,Gene,GpBP,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,adenosine deaminase,negative regulation of circadian sleep/wake cy...,Homo sapiens
2417966,ADA,Gene_BiologicalProcess,GO:0042323,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,adenosine deaminase,negative regulation of circadian sleep/wake cy...,Homo sapiens
2417969,ADA,Gene_BiologicalProcess,GO:0070256,Gene,GpBP,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,adenosine deaminase,negative regulation of mucus secretion,Homo sapiens
2417970,ADA,Gene_BiologicalProcess,GO:0070256,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,TARKG,Generalised,NCBI_ID,Quick_GO,adenosine deaminase,negative regulation of mucus secretion,Homo sapiens

## 4 · Gene Symbol Normalisation & Pre-dedup NA audit

In [30]:


final_df = final_df.dropna(subset=['head_detail_name', 'tail_detail_name']).reset_index(drop=True)

print(f"Consolidated rows (before deduplication): {len(final_df):,}")
print("\nNaN audit before deduplication:")
print(final_df.isna().sum())

Consolidated rows (before deduplication): 2,426,310

NaN audit before deduplication:
head                   0
relation               0
tail                   0
head_type              0
relation_type       2052
tail_type              0
kg_source              0
kg_type                0
head_id_is             0
tail_id_is             0
head_detail_name       0
tail_detail_name       0
species                0
dtype: int64

## 5 · Deduplication & Post-dedup NA audit

In [31]:
def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']
final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type': 'first',
    'relation_type': 'first',
    'tail_type': 'first',
    'kg_source': merge_sources,
    'kg_type': merge_sources,
    'head_id_is': 'first',
    'tail_id_is': 'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
print("\nNaN audit after deduplication:")
print(final_df_dedup.isna().sum())

Before dedup: 2,426,310  |  After dedup: 620,622

NaN audit after deduplication:
head                   0
relation               0
tail                   0
head_type              0
relation_type       1739
tail_type              0
kg_source              0
kg_type                0
head_id_is             0
tail_id_is             0
head_detail_name       0
tail_detail_name       0
species                0
dtype: int64

In [32]:
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,A1BG,Gene_BiologicalProcess,GO:0002764,Gene,actively_involved_in,BiologicalProcess,Monarch_KG,Generalised,NCBI_ID,Quick_GO,alpha-1-B glycoprotein,immune response-regulating signaling pathway,Homo sapiens
1,A1CF,Gene_BiologicalProcess,GO:0006396,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG::Hetionet::TARKG,Generalised,NCBI_ID,Quick_GO,APOBEC1 complementation factor,RNA processing,Homo sapiens
2,A1CF,Gene_BiologicalProcess,GO:0006397,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG::Hetionet::Monarch_KG::TARKG,Generalised,NCBI_ID,Quick_GO,APOBEC1 complementation factor,mRNA processing,Homo sapiens
3,A1CF,Gene_BiologicalProcess,GO:0007566,Gene,actively_involved_in,BiologicalProcess,Monarch_KG,Generalised,NCBI_ID,Quick_GO,APOBEC1 complementation factor,embryo implantation,Homo sapiens
4,A1CF,Gene_BiologicalProcess,GO:0009451,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG::Hetionet::TARKG,Generalised,NCBI_ID,Quick_GO,APOBEC1 complementation factor,RNA modification,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
620617,ZZZ3,Gene_BiologicalProcess,GO:0045995,Gene,associated,BiologicalProcess,GPKG::Monarch_KG,Generalised,NCBI_ID,Quick_GO,zinc finger ZZ-type containing 3,regulation of embryonic development,Homo sapiens
620618,ZZZ3,Gene_BiologicalProcess,GO:0051276,Gene,Hetionet::GpBP::Gene:Biological Process,BiologicalProcess,DRKG::Hetionet::TARKG,Generalised,NCBI_ID,Quick_GO,zinc finger ZZ-type containing 3,chromosome organization,Homo sapiens
620619,ZZZ3,Gene_BiologicalProcess,GO:0051302,Gene,associated,BiologicalProcess,GPKG::Monarch_KG,Generalised,NCBI_ID,Quick_GO,zinc finger ZZ-type containing 3,regulation of cell division,Homo sapiens
620620,ZZZ3,Gene_BiologicalProcess,GO:0051726,Gene,associated,BiologicalProcess,GPKG::Monarch_KG,Generalised,NCBI_ID,Quick_GO,zinc finger ZZ-type containing 3,regulation of cell cycle,Homo sapiens
620621,ZZZ3,Gene_BiologicalProcess,GO:0090043,Gene,associated,BiologicalProcess,GPKG::Monarch_KG,Generalised,NCBI_ID,Quick_GO,zinc finger ZZ-type containing 3,regulation of tubulin deacetylation,Homo sapiens

In [33]:
set(final_df_dedup['kg_source']),set(final_df_dedup['kg_type'])

({'AgeAnnoMO',
  'AgingAtlas',
  'AgingAtlas::DRKG::GPKG::GenAge::Hetionet',
  'AgingAtlas::DRKG::GenAge::Hetionet',
  'AgingAtlas::DRKG::Hetionet',
  'AgingAtlas::GPKG',
  'AgingAtlas::GPKG::GenAge',
  'AgingAtlas::GenAge',
  'DRKG::GPKG::Hetionet',
  'DRKG::GPKG::Hetionet::Monarch_KG',
  'DRKG::GPKG::Hetionet::Monarch_KG::TARKG',
  'DRKG::GPKG::Hetionet::TARKG',
  'DRKG::Hetionet',
  'DRKG::Hetionet::Monarch_KG',
  'DRKG::Hetionet::Monarch_KG::TARKG',
  'DRKG::Hetionet::TARKG',
  'GPKG',
  'GPKG::Monarch_KG',
  'Monarch_KG'},
 {'Aging', 'Aging::Generalised', 'Generalised'})

## 6 · Save Output

In [34]:
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 620,622 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/GENE_BIOLOGICALPROCESS/ALL_GENE_BIOLOGICALPROCESS.csv