# ANATOMY ↔ GENE Relation-Wise Merge

Merges ANATOMY–GENE triples from multiple KG sources (DRKG, PrimeKG, Hetionet, TARKG),
aligns to a common schema, deduplicates by `(head, relation, tail)`, and saves the result.

## 0. Configuration

In [14]:
import os
import pandas as pd
import numpy as np

# ── Base directories ──────────────────────────────────────────────────────────
BASE_DIR  = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR  = BASE_DIR + 'processed_data/'
PROC_DIR  = BASE_DIR + 'processed_data/'


# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH  = BASE_DIR + 'processed_data_relation_wise_merge/generalised/ANATOMY_CELLCOMP/ALL_ANATOMY_CELLCOMP.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

## 1. Build Lookup Dictionaries

In [15]:
UBERON = pd.read_csv(f'{BASE_DIR}data_collection/databases_for_mapping/uberon/Uberon_ID_Name_non_dup.csv')
UBERON_dict = dict(zip(UBERON['UBERON ID'], UBERON['Name']))
# UBERON_dict

In [16]:
# MESH mapping to map tail (GO_ID) to name
go_db = pd.read_csv(f'{BASE_DIR}data_collection/databases_for_mapping/MESH/MESH_GO_ID_NAME.csv')
GO_dict = dict(zip(go_db['id'], go_db['name']))
del go_db

## 2. Load Individual KG Sources

### 2a. Monarch

In [17]:
Monarch_Anatomy_cellularComp = pd.read_csv(f'{BASE_DIR}processed_data/Monarch/Human/Human_AnatomicalEntity_CellularComponent_Monarch.csv')
Monarch_Anatomy_cellularComp.columns = Monarch_Anatomy_cellularComp.columns.str.lower()
Monarch_Anatomy_cellularComp['head_detail_name'] = Monarch_Anatomy_cellularComp['head'].map(UBERON_dict)
Monarch_Anatomy_cellularComp['tail_detail_name'] = Monarch_Anatomy_cellularComp['tail'].map(GO_dict)

print(f"DRKG:     {len(Monarch_Anatomy_cellularComp):,} rows | columns: {list(Monarch_Anatomy_cellularComp.columns)}")
Monarch_Anatomy_cellularComp['kg_type'] = 'Generalised'
Monarch_Anatomy_cellularComp['species'] = 'Homo sapiens'
Monarch_Anatomy_cellularComp['kg_source'] = 'Monarch_KG'

Monarch_Anatomy_cellularComp

DRKG:     71 rows | columns: ['head', 'tail', 'relation_type', 'relation_source', 'kgsource', 'head_name', 'head_type', 'head_id_is', 'head_taxon', 'head_taxon_label', 'tail_name', 'tail_type', 'tail_id_is', 'tail_taxon', 'tail_taxon_label', 'head_taxon_name', 'tail_taxon_name', 'head_type_clean', 'tail_type_clean', 'relation', 'species_species', 'head_detail_name', 'tail_detail_name']

,head,tail,relation_type,relation_source,kgsource,head_name,head_type,head_id_is,head_taxon,head_taxon_label,...,tail_taxon_name,head_type_clean,tail_type_clean,relation,species_species,head_detail_name,tail_detail_name,kg_type,species,kg_source
0,UBERON:0000022,GO:0045095,related_to,infores:uberon,MonarchKG,feather,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,CellularComponent,AnatomicalEntity_CellularComponent,NaN,feather,keratin filament,Generalised,Homo sapiens,Monarch_KG
1,UBERON:0000054,GO:0070451,related_to,infores:uberon,MonarchKG,macula,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,CellularComponent,AnatomicalEntity_CellularComponent,NaN,macula,cell hair,Generalised,Homo sapiens,Monarch_KG
2,UBERON:0000121,GO:0005581,related_to,infores:uberon,MonarchKG,perineurium,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,CellularComponent,AnatomicalEntity_CellularComponent,NaN,perineurium,collagen trimer,Generalised,Homo sapiens,Monarch_KG
3,UBERON:0000122,GO:0043005,related_to,infores:uberon,MonarchKG,neuron projection bundle,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,CellularComponent,AnatomicalEntity_CellularComponent,NaN,neuron projection bundle,neuron projection,Generalised,Homo sapiens,Monarch_KG
4,UBERON:0000123,GO:0043209,related_to,infores:uberon,MonarchKG,endoneurium,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,CellularComponent,AnatomicalEntity_CellularComponent,NaN,endoneurium,myelin sheath,Generalised,Homo sapiens,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,UBERON:0018687,GO:0005604,related_to,infores:uberon,MonarchKG,glial limiting membrane,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,CellularComponent,AnatomicalEntity_CellularComponent,NaN,glial limiting membrane,basement membrane,Generalised,Homo sapiens,Monarch_KG
67,UBERON:0022317,GO:0030425,related_to,infores:uberon,MonarchKG,olfactory cortex layer 1,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,CellularComponent,AnatomicalEntity_CellularComponent,NaN,olfactory cortex layer 1,dendrite,Generalised,Homo sapiens,Monarch_KG
68,UBERON:0022318,GO:0043025,related_to,infores:uberon,MonarchKG,olfactory cortex layer 2,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,CellularComponent,AnatomicalEntity_CellularComponent,NaN,olfactory cortex layer 2,neuronal cell body,Generalised,Homo sapiens,Monarch_KG
69,UBERON:4000020,GO:0031012,subclass_of,infores:uberon,MonarchKG,mineralized extracellular matrix,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,CellularComponent,AnatomicalEntity_CellularComponent,NaN,mineralized extracellular matrix,extracellular matrix,Generalised,Homo sapiens,Monarch_KG
70,UBERON:4000059,GO:0031012,subclass_of,infores:uberon,MonarchKG,avascular GAG-rich matrix,AnatomicalEntity,UBERON,NaN,NaN,...,NaN,AnatomicalEntity,CellularComponent,AnatomicalEntity_CellularComponent,NaN,avascular GAG-rich matrix,extracellular matrix,Generalised,Homo sapiens,Monarch_KG

In [18]:
Monarch_Anatomy_cellularComp[Monarch_Anatomy_cellularComp['head_detail_name'].isna()]

Empty DataFrame
Columns: [head, tail, relation_type, relation_source, kgsource, head_name, head_type, head_id_is, head_taxon, head_taxon_label, tail_name, tail_type, tail_id_is, tail_taxon, tail_taxon_label, head_taxon_name, tail_taxon_name, head_type_clean, tail_type_clean, relation, species_species, head_detail_name, tail_detail_name, kg_type, species, kg_source]
Index: []

[0 rows x 26 columns]

In [19]:
Monarch_Anatomy_cellularComp[Monarch_Anatomy_cellularComp['tail_detail_name'].isna()]

Empty DataFrame
Columns: [head, tail, relation_type, relation_source, kgsource, head_name, head_type, head_id_is, head_taxon, head_taxon_label, tail_name, tail_type, tail_id_is, tail_taxon, tail_taxon_label, head_taxon_name, tail_taxon_name, head_type_clean, tail_type_clean, relation, species_species, head_detail_name, tail_detail_name, kg_type, species, kg_source]
Index: []

[0 rows x 26 columns]

## 3. Align Schemas and Concatenate

In [20]:
source_dfs = [
    Monarch_Anatomy_cellularComp,
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df['species'] = 'Homo sapiens'
final_df

Consolidated rows: 71

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,UBERON:0000022,AnatomicalEntity_CellularComponent,GO:0045095,AnatomicalEntity,related_to,CellularComponent,Monarch_KG,UBERON,GO,feather,keratin filament,Generalised,Homo sapiens
1,UBERON:0000054,AnatomicalEntity_CellularComponent,GO:0070451,AnatomicalEntity,related_to,CellularComponent,Monarch_KG,UBERON,GO,macula,cell hair,Generalised,Homo sapiens
2,UBERON:0000121,AnatomicalEntity_CellularComponent,GO:0005581,AnatomicalEntity,related_to,CellularComponent,Monarch_KG,UBERON,GO,perineurium,collagen trimer,Generalised,Homo sapiens
3,UBERON:0000122,AnatomicalEntity_CellularComponent,GO:0043005,AnatomicalEntity,related_to,CellularComponent,Monarch_KG,UBERON,GO,neuron projection bundle,neuron projection,Generalised,Homo sapiens
4,UBERON:0000123,AnatomicalEntity_CellularComponent,GO:0043209,AnatomicalEntity,related_to,CellularComponent,Monarch_KG,UBERON,GO,endoneurium,myelin sheath,Generalised,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,UBERON:0018687,AnatomicalEntity_CellularComponent,GO:0005604,AnatomicalEntity,related_to,CellularComponent,Monarch_KG,UBERON,GO,glial limiting membrane,basement membrane,Generalised,Homo sapiens
67,UBERON:0022317,AnatomicalEntity_CellularComponent,GO:0030425,AnatomicalEntity,related_to,CellularComponent,Monarch_KG,UBERON,GO,olfactory cortex layer 1,dendrite,Generalised,Homo sapiens
68,UBERON:0022318,AnatomicalEntity_CellularComponent,GO:0043025,AnatomicalEntity,related_to,CellularComponent,Monarch_KG,UBERON,GO,olfactory cortex layer 2,neuronal cell body,Generalised,Homo sapiens
69,UBERON:4000020,AnatomicalEntity_CellularComponent,GO:0031012,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,UBERON,GO,mineralized extracellular matrix,extracellular matrix,Generalised,Homo sapiens
70,UBERON:4000059,AnatomicalEntity_CellularComponent,GO:0031012,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,UBERON,GO,avascular GAG-rich matrix,extracellular matrix,Generalised,Homo sapiens

## 4. QC — NaN Check Before Name Repair

In [21]:
def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(final_df)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

## 6. Deduplicate and Add Schema Columns

Group by `(head, relation, tail)` and collapse duplicate `kg_source` values with `::` separator.

In [22]:
GROUP_COLS = ['head', 'relation', 'tail']

def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

final_df_dedup = final_df.groupby(GROUP_COLS, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'kg_type': merge_sources,
    'species': 'first',
})

# Enforce final column order
final_df_dedup = final_df_dedup[REQUIRED_COLS]

print(f"After deduplication: {len(final_df_dedup):,} rows")
final_df_dedup.head()

After deduplication: 71 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,UBERON:0000022,AnatomicalEntity_CellularComponent,GO:0045095,AnatomicalEntity,related_to,CellularComponent,Monarch_KG,UBERON,GO,feather,keratin filament,Generalised,Homo sapiens
1,UBERON:0000054,AnatomicalEntity_CellularComponent,GO:0070451,AnatomicalEntity,related_to,CellularComponent,Monarch_KG,UBERON,GO,macula,cell hair,Generalised,Homo sapiens
2,UBERON:0000121,AnatomicalEntity_CellularComponent,GO:0005581,AnatomicalEntity,related_to,CellularComponent,Monarch_KG,UBERON,GO,perineurium,collagen trimer,Generalised,Homo sapiens
3,UBERON:0000122,AnatomicalEntity_CellularComponent,GO:0043005,AnatomicalEntity,related_to,CellularComponent,Monarch_KG,UBERON,GO,neuron projection bundle,neuron projection,Generalised,Homo sapiens
4,UBERON:0000123,AnatomicalEntity_CellularComponent,GO:0043209,AnatomicalEntity,related_to,CellularComponent,Monarch_KG,UBERON,GO,endoneurium,myelin sheath,Generalised,Homo sapiens

In [23]:
print("\nkg_source values present:", set(final_df_dedup['kg_source']))

kg_source values present: {'Monarch_KG'}

In [24]:
print("\nkg_type values present:", set(final_df_dedup['kg_type']))

kg_type values present: {'Generalised'}

## 7. QC — NaN Check After Deduplication

In [25]:
nan_summary(final_df_dedup)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

In [26]:
final_df_dedup['head_species'] = 'Homo sapiens'
final_df_dedup['tail_species'] = 'Homo sapiens'

## 8. Save Output

In [27]:
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 71 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/ANATOMY_CELLCOMP/ALL_ANATOMY_CELLCOMP.csv

In [28]:
#