In [15]:
import os
import pandas as pd
import numpy as np

In [16]:
# ── Base directories ──────────────────────────────────────────────────────────
BASE_DIR   = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR   = BASE_DIR + 'processed_data/'
DB_DIR     = BASE_DIR + 'data_collection/databases_for_mapping/'


# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

In [17]:
# MESH mapping to map tail (GO_ID) to name
go_db = pd.read_csv(DB_DIR + 'MESH/MESH_GO_ID_NAME.csv')
GO_dict = dict(zip(go_db['id'], go_db['name']))
del go_db

# POSITIVE ASSOCIATION

In [18]:
# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/GENE_Positively_BIOLOGICALPROCESS/GENE_Positively_BIOLOGICALPROCESS_Human.parquet'

# DAA
DAA_Human_Gene_Pos_BioPro_1 = pd.read_csv(PROC_DIR + 'digitalagingatlas/Human/DAA_Gene_PositivelyAssociatedWith_BiologicalProcess_Human.csv')
DAA_Human_Gene_Pos_BioPro_1.columns = DAA_Human_Gene_Pos_BioPro_1.columns.str.lower()
DAA_Human_Gene_Pos_BioPro_1['tail_detail_name'] = 'aging'
DAA_Human_Gene_Pos_BioPro_1.rename(columns={'relation_source': 'kg_source'}, inplace=True)
DAA_Human_Gene_Pos_BioPro_1['kg_type'] = 'Aging'
DAA_Human_Gene_Pos_BioPro_1['kg_source'] = 'DAA'
DAA_Human_Gene_Pos_BioPro_1['relation'] = 'Gene_PositivelyAssociatedWith_BiologicalProcess'

DAA_Human_Gene_Pos_BioPro_1['species'] = 'Homo sapiens'
DAA_Human_Gene_Pos_BioPro_1['head_id_is'] = 'NCBI_ID'
DAA_Human_Gene_Pos_BioPro_1['tail_id_is'] = 'Quick_GO'
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
DAA_Human_Gene_Pos_BioPro_1.to_parquet(OUT_PATH, index=False)
print(f'Saved {len(DAA_Human_Gene_Pos_BioPro_1):,} rows → {OUT_PATH}')

DAA_Human_Gene_Pos_BioPro_1

Saved 215 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/GENE_Positively_BIOLOGICALPROCESS/GENE_Positively_BIOLOGICALPROCESS_Human.parquet

,head,relation,tail,head_type,tail_type,head_detail_name,kg_source,species,data_type,tail_detail_name,kg_type,head_id_is,tail_id_is
0,ERI1,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,exoribonuclease 1,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
1,NT5C2,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"5'-nucleotidase, cytosolic II",DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
2,ANP32B,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,acidic nuclear phosphoprotein 32 family member B,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
3,ACTC1,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,actin alpha cardiac muscle 1,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
4,ABLIM1,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,actin binding LIM protein 1,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,ZBTB4,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc finger and BTB domain containing 4,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
211,ZCCHC24,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc finger CCHC-type containing 24,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
212,ZFP36L1,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ZFP36 ring finger protein like 1,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
213,ZNF507,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc finger protein 507,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
214,ZHX2,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc fingers and homeoboxes 2,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO

In [19]:
def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(DAA_Human_Gene_Pos_BioPro_1)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
tail_type                 0                   0               0
head_detail_name          0                   0               0
kg_source                 0                   0               0
species                   0                   0               0
data_type                 0                   0               0
tail_detail_name          0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0

# NEGATIVE ASSOCIATION

In [20]:
OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/GENE_Negatively_BIOLOGICALPROCESS/GENE_Negatively_BIOLOGICALPROCESS_Human.parquet'

# DAA
DAA_Human_Gene_Neg_BioPro_1 = pd.read_csv(PROC_DIR + 'digitalagingatlas/Human/DAA_Gene_NegativelyAssociatedWith_BiologicalProcess_Human.csv')
DAA_Human_Gene_Neg_BioPro_1.columns = DAA_Human_Gene_Neg_BioPro_1.columns.str.lower()
DAA_Human_Gene_Neg_BioPro_1['tail_detail_name'] = 'aging'
DAA_Human_Gene_Neg_BioPro_1.rename(columns={'relation_source': 'kg_source'}, inplace=True)
DAA_Human_Gene_Neg_BioPro_1['kg_type'] = 'Aging'
DAA_Human_Gene_Neg_BioPro_1['kg_source'] = 'DAA'
DAA_Human_Gene_Neg_BioPro_1['species'] = 'Homo sapiens'
DAA_Human_Gene_Neg_BioPro_1['relation'] = 'Gene_NegativelyAssociatedWith_BiologicalProcess'
DAA_Human_Gene_Neg_BioPro_1['head_id_is'] = 'NCBI_ID'
DAA_Human_Gene_Neg_BioPro_1['tail_id_is'] = 'Quick_GO'
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
DAA_Human_Gene_Neg_BioPro_1.to_parquet(OUT_PATH, index=False)
print(f'Saved {len(DAA_Human_Gene_Neg_BioPro_1):,} rows → {OUT_PATH}')

DAA_Human_Gene_Neg_BioPro_1

Saved 310 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/GENE_Negatively_BIOLOGICALPROCESS/GENE_Negatively_BIOLOGICALPROCESS_Human.parquet

,head,relation,tail,head_type,tail_type,head_detail_name,kg_source,species,data_type,tail_detail_name,kg_type,head_id_is,tail_id_is
0,PTS,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,6-pyruvoyltetrahydropterin synthase,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
1,ABHD14A,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,abhydrolase domain containing 14A,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
2,ABI2,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,abl interactor 2,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
3,ACTA1,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"actin alpha 1, skeletal muscle",DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
4,ACTB,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,actin beta,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,WSB2,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,WD repeat and SOCS box containing 2,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
306,WDR12,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,WD repeat domain 12,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
307,ZER1,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zyg-11 related cell cycle regulator,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
308,ZMIZ2,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc finger MIZ-type containing 2,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO
309,ZNF280A,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc finger protein 280A,DAA,Homo sapiens,Associative,aging,Aging,NCBI_ID,Quick_GO

In [21]:
def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(DAA_Human_Gene_Neg_BioPro_1)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
tail_type                 0                   0               0
head_detail_name          0                   0               0
kg_source                 0                   0               0
species                   0                   0               0
data_type                 0                   0               0
tail_detail_name          0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0

# NOT ASSOCIATED

In [22]:
OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/GENE_NotAssociated_BIOLOGICALPROCESS/GENE_NotAssociated_BIOLOGICALPROCESS_Human.parquet'

# DAA
DAA_Human_Gene_Not_BioPro_1 = pd.read_csv(PROC_DIR + 'digitalagingatlas/Human/DAA_Gene_NotAssociatedWith_BiologicalProcess_Human.csv')
DAA_Human_Gene_Not_BioPro_1.columns = DAA_Human_Gene_Not_BioPro_1.columns.str.lower()
DAA_Human_Gene_Neg_BioPro_1['tail_detail_name'] = 'aging'

DAA_Human_Gene_Not_BioPro_1.rename(columns={'relation_source': 'kg_source'}, inplace=True)
DAA_Human_Gene_Not_BioPro_1['kg_type'] = 'Aging'
DAA_Human_Gene_Not_BioPro_1['kg_source'] = 'DAA'
DAA_Human_Gene_Not_BioPro_1['species'] = 'Homo sapiens'
DAA_Human_Gene_Not_BioPro_1['relation'] = 'Gene_NotAssociatedWith_BiologicalProcess'
DAA_Human_Gene_Not_BioPro_1['head_id_is'] = 'NCBI_ID'
DAA_Human_Gene_Not_BioPro_1['tail_id_is'] = 'Quick_GO'

os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
DAA_Human_Gene_Not_BioPro_1.to_parquet(OUT_PATH, index=False)
print(f'Saved {len(DAA_Human_Gene_Not_BioPro_1):,} rows → {OUT_PATH}')

DAA_Human_Gene_Not_BioPro_1

Saved 1 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/GENE_NotAssociated_BIOLOGICALPROCESS/GENE_NotAssociated_BIOLOGICALPROCESS_Human.parquet

,head,relation,tail,head_type,tail_type,head_detail_name,kg_source,species,data_type,kg_type,head_id_is,tail_id_is
0,MRPS22,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,mitochondrial ribosomal protein S22,DAA,Homo sapiens,Associative,Aging,NCBI_ID,Quick_GO

In [23]:
def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(DAA_Human_Gene_Not_BioPro_1)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
tail_type                 0                   0               0
head_detail_name          0                   0               0
kg_source                 0                   0               0
species                   0                   0               0
data_type                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0

In [24]:
DAA_Human_Gene_Not_BioPro_1 = pd.read_parquet('/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/GENE_NotAssociated_BIOLOGICALPROCESS/GENE_NotAssociated_BIOLOGICALPROCESS_Human.parquet')
DAA_Human_Gene_Not_BioPro_1

,head,relation,tail,head_type,tail_type,head_detail_name,kg_source,species,data_type,kg_type,head_id_is,tail_id_is
0,MRPS22,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,mitochondrial ribosomal protein S22,DAA,Homo sapiens,Associative,Aging,NCBI_ID,Quick_GO