# ChemicalEntity ↔ Mutation Relation-Wise Merge

Merges Chemical–Mutation triples from CKG and EvoAGE; resolves chemical names via
PubChem, DrugBank (standard + extended); falls back to raw head value for any
remaining unresolved IDs; deduplicates by `(head, relation, tail)`; and saves the result.

## 0. Configuration

In [1]:
import pandas as pd
import numpy as np
import re

# ── Base directories ──────────────────────────────────────────────────────────
BASE_DIR   = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR   = BASE_DIR + 'processed_data/'
DB_DIR     = BASE_DIR + 'data_collection/databases_for_mapping/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/CHEMICALENTITY_MUTATION/ALL_CHEMICALENTITY_MUTATION.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

## 1. Build Lookup Dictionaries

- **PubChem** — CID → IUPAC name and SMILES
- **DrugBank standard** — `drugbank_id` → name
- **DrugBank extended** — full `drugbank_all.csv` as fallback

In [2]:
Pubchem = pd.read_pickle(DB_DIR + 'pubchem/combined_df.pkl')
Pubchem_IUPAC_CID_Dict = dict(zip(Pubchem['PUBCHEM_COMPOUND_CID'], Pubchem['PUBCHEM_IUPAC_NAME']))
Pubchem_CID_Smile_Dict = dict(zip(Pubchem['PUBCHEM_COMPOUND_CID'], Pubchem['PUBCHEM_SMILES']))
del Pubchem
print(f"PubChem IUPAC dict: {len(Pubchem_IUPAC_CID_Dict):,} entries")

PubChem IUPAC dict: 119,177,440 entries

In [17]:
Drugbank = pd.read_csv(DB_DIR + 'drugbank/ALL_DRUGBANK_WITH_SMILE_PUBCHEM.csv')
Drugbank_dict = dict(zip(Drugbank['drugbank_id'], Drugbank['name']))

DB_All = pd.read_csv(DB_DIR + 'drugbank/drugbank_all.csv')
DB_All_dict = dict(zip(DB_All['drugbank_id'], DB_All['name']))

print(f"DrugBank dict:     {len(Drugbank_dict):,} entries")
print(f"DrugBank all dict: {len(DB_All_dict):,} entries")

DrugBank dict:     16,575 entries
DrugBank all dict: 16,575 entries

In [18]:
Drugbank_dict

{'DB00001': 'Lepirudin',
 'DB00002': 'Cetuximab',
 'DB00003': 'Dornase alfa',
 'DB00004': 'Denileukin diftitox',
 'DB00005': 'Etanercept',
 'DB00006': 'Bivalirudin',
 'DB00007': 'Leuprolide',
 'DB00008': 'Peginterferon alfa-2a',
 'DB00009': 'Alteplase',
 'DB00010': 'Sermorelin',
 'DB00011': 'Interferon alfa-n1',
 'DB00012': 'Darbepoetin alfa',
 'DB00013': 'Urokinase',
 'DB00014': 'Goserelin',
 'DB00015': 'Reteplase',
 'DB00016': 'Erythropoietin',
 'DB00017': 'Salmon calcitonin',
 'DB00018': 'Interferon alfa-n3',
 'DB00019': 'Pegfilgrastim',
 'DB00020': 'Sargramostim',
 'DB00022': 'Peginterferon alfa-2b',
 'DB00023': 'Asparaginase Escherichia coli',
 'DB00024': 'Thyrotropin alfa',
 'DB00025': 'Antihemophilic factor, human recombinant',
 'DB00026': 'Anakinra',
 'DB00027': 'Gramicidin D',
 'DB00028': 'Human immunoglobulin G',
 'DB00029': 'Anistreplase',
 'DB00030': 'Insulin human',
 'DB00031': 'Tenecteplase',
 'DB00032': 'Menotropins',
 'DB00033': 'Interferon gamma-1b',
 'DB00034': 'Interferon alfa-2a',
 'DB00035': 'Desmopressin',
 'DB00036': 'Coagulation factor VIIa Recombinant Human',
 'DB00038': 'Oprelvekin',
 'DB00039': 'Palifermin',
 'DB00040': 'Glucagon',
 'DB00041': 'Aldesleukin',
 'DB00042': 'Botulinum toxin type B',
 'DB00043': 'Omalizumab',
 'DB00044': 'Lutropin alfa',
 'DB00045': 'Lyme disease vaccine (recombinant OspA)',
 'DB00046': 'Insulin lispro',
 'DB00047': 'Insulin glargine',
 'DB00048': 'Collagenase clostridium histolyticum',
 'DB00049': 'Rasburicase',
 'DB00050': 'Cetrorelix',
 'DB00051': 'Adalimumab',
 'DB00052': 'Somatotropin',
 'DB00053': 'Imiglucerase',
 'DB00054': 'Abciximab',
 'DB00055': 'Drotrecogin alfa',
 'DB00056': 'Gemtuzumab ozogamicin',
 'DB00057': 'Indium In-111 satumomab pendetide',
 'DB00058': 'Alpha-1-proteinase inhibitor',
 'DB00059': 'Pegaspargase',
 'DB00060': 'Interferon beta-1a',
 'DB00061': 'Pegademase',
 'DB00062': 'Albumin human',
 'DB00063': 'Eptifibatide',
 'DB00065': 'Infliximab',
 'DB00066': 'Follitropin',
 'DB00067': 'Vasopressin',
 'DB00068': 'Interferon beta-1b',
 'DB00069': 'Interferon alfacon-1',
 'DB00070': 'Hyaluronidase (ovine)',
 'DB00071': 'Insulin pork',
 'DB00072': 'Trastuzumab',
 'DB00073': 'Rituximab',
 'DB00074': 'Basiliximab',
 'DB00075': 'Muromonab',
 'DB00076': 'Digoxin Immune Fab (Ovine)',
 'DB00078': 'Ibritumomab tiuxetan',
 'DB00080': 'Daptomycin',
 'DB00081': 'Tositumomab',
 'DB00082': 'Pegvisomant',
 'DB00083': 'Botulinum toxin type A',
 'DB00085': 'Pancrelipase',
 'DB00086': 'Streptokinase',
 'DB00087': 'Alemtuzumab',
 'DB00088': 'Alglucerase',
 'DB00089': 'Capromab pendetide',
 'DB00090': 'Laronidase',
 'DB00091': 'Cyclosporine',
 'DB00092': 'Alefacept',
 'DB00093': 'Felypressin',
 'DB00094': 'Urofollitropin',
 'DB00095': 'Efalizumab',
 'DB00097': 'Choriogonadotropin alfa',
 'DB00098': 'Antithymocyte immunoglobulin (rabbit)',
 'DB00099': 'Filgrastim',
 'DB00100': 'Coagulation Factor IX (Recombinant)',
 'DB00102': 'Becaplermin',
 'DB00103': 'Agalsidase beta',
 'DB00104': 'Octreotide',
 'DB00105': 'Interferon alfa-2b',
 'DB00106': 'Abarelix',
 'DB00107': 'Oxytocin',
 'DB00108': 'Natalizumab',
 'DB00109': 'Enfuvirtide',
 'DB00110': 'Palivizumab',
 'DB00111': 'Daclizumab',
 'DB00112': 'Bevacizumab',
 'DB00113': 'Technetium Tc-99m arcitumomab',
 'DB00114': 'Pyridoxal phosphate',
 'DB00115': 'Cyanocobalamin',
 'DB00116': 'Tetrahydrofolic acid',
 'DB00117': 'Histidine',
 'DB00118': 'Ademetionine',
 'DB00119': 'Pyruvic acid',
 'DB00120': 'Phenylalanine',
 'DB00121': 'Biotin',
 'DB00122': 'Choline',
 'DB00123': 'Lysine',
 'DB00125': 'Arginine',
 'DB00126': 'Ascorbic acid',
 'DB00127': 'Spermine',
 'DB00128': 'Aspartic acid',
 'DB00129': 'Ornithine',
 'DB00130': 'L-Glutamine',
 'DB00131': 'Adenosine phosphate',
 'DB00132': 'alpha-Linolenic acid',
 'DB00133': 'Serine',
 'DB00134': 'Methionine',
 'DB00135': 'Tyrosine',
 'DB00136': 'Calcitriol',
 'DB00137': 'Lutein',
 'DB00138': 'Cystine',
 'DB00139': 'Succinic acid',
 'DB00140': 'Riboflavin',
 'DB00141': 'N-Acetylglucosamine',
 'DB00142': 'Glutamic acid',
 'DB00143': 'Glutathione',
 'DB00144': 'Phosphatidyl serine',
 'DB00145': 'Glycine',
 'DB00146': 'Calcifediol',
 'DB00147': 'Pyridoxal',
 'DB00148': 'Creatine',
 'DB00149': 'Leucine',
 'DB00150': 'Tryptophan',
 'DB00151': 'Cysteine',
 'DB00152': 'Thiamine',
 'DB00153': 'Ergocalciferol',
 'DB00154': 'Dihomo-gamma-linolenic acid',
 'DB00155': 'Citrulline',
 'DB00156': 'Threonine',
 'DB00157': 'NADH',
 'DB00158': 'Folic acid',
 'DB00159': 'Icosapent',
 'DB00160': 'Alanine',
 'DB00161': 'Valine',
 'DB00162': 'Vitamin A',
 'DB00163': 'Vitamin E',
 'DB00165': 'Pyridoxine',
 'DB00166': 'Lipoic acid',
 'DB00167': 'Isoleucine',
 'DB00168': 'Aspartame',
 'DB00169': 'Cholecalciferol',
 'DB00170': 'Menadione',
 'DB00171': 'ATP',
 'DB00172': 'Proline',
 'DB00173': 'Adenine',
 'DB00174': 'Asparagine',
 'DB00175': 'Pravastatin',
 'DB00176': 'Fluvoxamine',
 'DB00177': 'Valsartan',
 'DB00178': 'Ramipril',
 'DB00179': 'Masoprocol',
 'DB00180': 'Flunisolide',
 'DB00181': 'Baclofen',
 'DB00182': 'Amphetamine',
 'DB00183': 'Pentagastrin',
 'DB00184': 'Nicotine',
 'DB00185': 'Cevimeline',
 'DB00186': 'Lorazepam',
 'DB00187': 'Esmolol',
 'DB00188': 'Bortezomib',
 'DB00189': 'Ethchlorvynol',
 'DB00190': 'Carbidopa',
 'DB00191': 'Phentermine',
 'DB00192': 'Indecainide',
 'DB00193': 'Tramadol',
 'DB00194': 'Vidarabine',
 'DB00195': 'Betaxolol',
 'DB00196': 'Fluconazole',
 'DB00197': 'Troglitazone',
 'DB00198': 'Oseltamivir',
 'DB00199': 'Erythromycin',
 'DB00200': 'Hydroxocobalamin',
 'DB00201': 'Caffeine',
 'DB00202': 'Succinylcholine',
 'DB00203': 'Sildenafil',
 'DB00204': 'Dofetilide',
 'DB00205': 'Pyrimethamine',
 'DB00206': 'Reserpine',
 'DB00207': 'Azithromycin',
 'DB00208': 'Ticlopidine',
 'DB00209': 'Trospium',
 'DB00210': 'Adapalene',
 'DB00211': 'Midodrine',
 'DB00212': 'Remikiren',
 'DB00213': 'Pantoprazole',
 'DB00214': 'Torasemide',
 'DB00215': 'Citalopram',
 'DB00216': 'Eletriptan',
 'DB00217': 'Bethanidine',
 'DB00218': 'Moxifloxacin',
 'DB00219': 'Oxyphenonium',
 'DB00220': 'Nelfinavir',
 'DB00221': 'Isoetharine',
 'DB00222': 'Glimepiride',
 'DB00223': 'Diflorasone',
 'DB00224': 'Indinavir',
 'DB00225': 'Gadodiamide',
 'DB00226': 'Guanadrel',
 'DB00227': 'Lovastatin',
 'DB00228': 'Enflurane',
 'DB00229': 'Cefotiam',
 'DB00230': 'Pregabalin',
 'DB00231': 'Temazepam',
 'DB00232': 'Methyclothiazide',
 'DB00233': 'Aminosalicylic acid',
 'DB00234': 'Reboxetine',
 'DB00235': 'Milrinone',
 'DB00236': 'Pipobroman',
 'DB00237': 'Butabarbital',
 'DB00238': 'Nevirapine',
 'DB00239': 'Oxiconazole',
 'DB00240': 'Alclometasone',
 'DB00241': 'Butalbital',
 'DB00242': 'Cladribine',
 'DB00243': 'Ranolazine',
 'DB00244': 'Mesalazine',
 'DB00245': 'Benzatropine',
 'DB00246': 'Ziprasidone',
 'DB00247': 'Methysergide',
 'DB00248': 'Cabergoline',
 'DB00249': 'Idoxuridine',
 'DB00250': 'Dapsone',
 'DB00251': 'Terconazole',
 'DB00252': 'Phenytoin',
 'DB00253': 'Medrysone',
 'DB00254': 'Doxycycline',
 'DB00255': 'Diethylstilbestrol',
 'DB00256': 'Lymecycline',
 'DB00257': 'Clotrimazole',
 'DB00258': 'Calcium acetate',
 'DB00259': 'Sulfanilamide',
 'DB00260': 'Cycloserine',
 'DB00261': 'Anagrelide',
 'DB00262': 'Carmustine',
 'DB00263': 'Sulfisoxazole',
 'DB00264': 'Metoprolol',
 'DB00265': 'Crotamiton',
 'DB00266': 'Dicoumarol',
 'DB00267': 'Cefmenoxime',
 'DB00268': 'Ropinirole',
 'DB00269': 'Chlorotrianisene',
 'DB00270': 'Isradipine',
 'DB00271': 'Diatrizoate',
 'DB00272': 'Betazole',
 'DB00273': 'Topiramate',
 'DB00274': 'Cefmetazole',
 'DB00275': 'Olmesartan',
 'DB00276': 'Amsacrine',
 'DB00277': 'Theophylline',
 'DB00278': 'Argatroban',
 'DB00279': 'Liothyronine',
 'DB00280': 'Disopyramide',
 'DB00281': 'Lidocaine',
 'DB00282': 'Pamidronic acid',
 'DB00283': 'Clemastine',
 'DB00284': 'Acarbose',
 'DB00285': 'Venlafaxine',
 'DB00286': 'Conjugated estrogens',
 'DB00287': 'Travoprost',
 'DB00288': 'Amcinonide',
 'DB00289': 'Atomoxetine',
 'DB00290': 'Bleomycin',
 'DB00291': 'Chlorambucil',
 'DB00292': 'Etomidate',
 'DB00293': 'Raltitrexed',
 'DB00294': 'Etonogestrel',
 'DB00295': 'Morphine',
 'DB00296': 'Ropivacaine',
 'DB00297': 'Bupivacaine',
 'DB00298': 'Dapiprazole',
 'DB00299': 'Penciclovir',
 'DB00300': 'Tenofovir disoproxil',
 'DB00301': 'Flucloxacillin',
 'DB00302': 'Tranexamic acid',
 'DB00303': 'Ertapenem',
 'DB00304': 'Desogestrel',
 'DB00305': 'Mitomycin',
 'DB00306': 'Talbutal',
 'DB00307': 'Bexarotene',
 'DB00308': 'Ibutilide',
 'DB00309': 'Vindesine',
 'DB00310': 'Chlorthalidone',
 'DB00311': 'Ethoxzolamide',
 'DB00312': 'Pentobarbital',
 'DB00313': 'Valproic acid',
 'DB00314': 'Capreomycin',
 'DB00315': 'Zolmitriptan',
 'DB00316': 'Acetaminophen',
 'DB00317': 'Gefitinib',
 'DB00318': 'Codeine',
 'DB00319': 'Piperacillin',
 'DB00320': 'Dihydroergotamine',
 'DB00321': 'Amitriptyline',
 'DB00322': 'Floxuridine',
 'DB00323': 'Tolcapone',
 'DB00324': 'Fluorometholone',
 'DB00325': 'Nitroprusside',
 'DB00326': 'Calcium glucoheptonate',
 'DB00327': 'Hydromorphone',
 'DB00328': 'Indomethacin',
 'DB00330': 'Ethambutol',
 'DB00331': 'Metformin',
 'DB00332': 'Ipratropium',
 'DB00333': 'Methadone',
 'DB00334': 'Olanzapine',
 'DB00335': 'Atenolol',
 'DB00336': 'Nitrofural',
 'DB00337': 'Pimecrolimus',
 'DB00338': 'Omeprazole',
 'DB00339': 'Pyrazinamide',
 'DB00340': 'Metixene',
 'DB00341': 'Cetirizine',
 'DB00342': 'Terfenadine',
 'DB00343': 'Diltiazem',
 'DB00344': 'Protriptyline',
 'DB00345': 'Aminohippuric acid',
 'DB00346': 'Alfuzosin',
 'DB00347': 'Trimethadione',
 'DB00348': 'Nitisinone',
 'DB00349': 'Clobazam',
 'DB00350': 'Minoxidil',
 'DB00351': 'Megestrol acetate',
 'DB00352': 'Tioguanine',
 'DB00353': 'Methylergometrine',
 'DB00354': 'Buclizine',
 'DB00355': 'Aztreonam',
 'DB00356': 'Chlorzoxazone',
 'DB00357': 'Aminoglutethimide',
 'DB00358': 'Mefloquine',
 'DB00359': 'Sulfadiazine',
 'DB00360': 'Sapropterin',
 'DB00361': 'Vinorelbine',
 'DB00362': 'Anidulafungin',
 'DB00363': 'Clozapine',
 'DB00364': 'Sucralfate',
 'DB00365': 'Grepafloxacin',
 'DB00366': 'Doxylamine',
 'DB00367': 'Levonorgestrel',
 'DB00368': 'Norepinephrine',
 'DB00369': 'Cidofovir',
 'DB00370': 'Mirtazapine',
 'DB00371': 'Meprobamate',
 'DB00372': 'Thiethylperazine',
 'DB00373': 'Timolol',
 'DB00374': 'Treprostinil',
 'DB00375': 'Colestipol',
 'DB00376': 'Trihexyphenidyl',
 'DB00377': 'Palonosetron',
 'DB00378': 'Dydrogesterone',
 'DB00379': 'Mexiletine',
 'DB00380': 'Dexrazoxane',
 'DB00381': 'Amlodipine',
 'DB00382': 'Tacrine',
 'DB00383': 'Oxyphencyclimine',
 'DB00384': 'Triamterene',
 'DB00385': 'Valrubicin',
 'DB00387': 'Procyclidine',
 'DB00388': 'Phenylephrine',
 'DB00389': 'Carbimazole',
 'DB00390': 'Digoxin',
 'DB00391': 'Sulpiride',
 'DB00392': 'Profenamine',
 'DB00393': 'Nimodipine',
 'DB00394': 'Beclomethasone dipropionate',
 'DB00395': 'Carisoprodol',
 'DB00396': 'Progesterone',
 'DB00397': 'Phenylpropanolamine',
 'DB00398': 'Sorafenib',
 'DB00399': 'Zoledronic acid',
 'DB00400': 'Griseofulvin',
 'DB00401': 'Nisoldipine',
 'DB00402': 'Eszopiclone',
 'DB00403': 'Ceruletide',
 'DB00404': 'Alprazolam',
 'DB00405': 'Dexbrompheniramine',
 'DB00406': 'Gentian violet cation',
 'DB00407': 'Ardeparin',
 'DB00408': 'Loxapine',
 'DB00409': 'Remoxipride',
 'DB00410': 'Mupirocin',
 'DB00411': 'Carbamoylcholine',
 'DB00412': 'Rosiglitazone',
 'DB00413': 'Pramipexole',
 'DB00414': 'Acetohexamide',
 'DB00415': 'Ampicillin',
 'DB00416': 'Metocurine iodide',
 'DB00417': 'Phenoxymethylpenicillin',
 'DB00418': 'Secobarbital',
 'DB00419': 'Miglustat',
 'DB00420': 'Promazine',
 'DB00421': 'Spironolactone',
 'DB00422': 'Methylphenidate',
 'DB00423': 'Methocarbamol',
 'DB00424': 'Hyoscyamine',
 'DB00425': 'Zolpidem',
 'DB00426': 'Famciclovir',
 'DB00427': 'Triprolidine',
 'DB00428': 'Streptozocin',
 'DB00429': 'Carboprost tromethamine',
 'DB00430': 'Cefpiramide',
 'DB00431': 'Lindane',
 'DB00432': 'Trifluridine',
 'DB00433': 'Prochlorperazine',
 'DB00434': 'Cyproheptadine',
 'DB00435': 'Nitric Oxide',
 'DB00436': 'Bendroflumethiazide',
 'DB00437': 'Allopurinol',
 'DB00438': 'Ceftazidime',
 'DB00439': 'Cerivastatin',
 'DB00440': 'Trimethoprim',
 'DB00441': 'Gemcitabine',
 'DB00442': 'Entecavir',
 'DB00443': 'Betamethasone',
 'DB00444': 'Teniposide',
 'DB00445': 'Epirubicin',
 'DB00446': 'Chloramphenicol',
 'DB00447': 'Loracarbef',
 'DB00448': 'Lansoprazole',
 'DB00449': 'Dipivefrin',
 'DB00450': 'Droperidol',
 'DB00451': 'Levothyroxine',
 'DB00452': 'Framycetin',
 'DB00453': 'Clomocycline',
 'DB00454': 'Meperidine',
 'DB00455': 'Loratadine',
 'DB00456': 'Cefalotin',
 'DB00457': 'Prazosin',
 'DB00458': 'Imipramine',
 'DB00459': 'Acitretin',
 'DB00460': 'Verteporfin',
 'DB00461': 'Nabumetone',
 'DB00462': 'Methscopolamine bromide',
 'DB00463': 'Metharbital',
 'DB00464': 'Sodium tetradecyl sulfate',
 'DB00465': 'Ketorolac',
 'DB00466': 'Picrotoxin',
 'DB00467': 'Enoxacin',
 'DB00468': 'Quinine',
 'DB00469': 'Tenoxicam',
 'DB00470': 'Dronabinol',
 'DB00471': 'Montelukast',
 'DB00472': 'Fluoxetine',
 'DB00473': 'Hexylcaine',
 'DB00474': 'Methohexital',
 'DB00475': 'Chlordiazepoxide',
 'DB00476': 'Duloxetine',
 'DB00477': 'Chlorpromazine',
 'DB00478': 'Rimantadine',
 'DB00479': 'Amikacin',
 'DB00480': 'Lenalidomide',
 'DB00481': 'Raloxifene',
 'DB00482': 'Celecoxib',
 'DB00483': 'Gallamine triethiodide',
 'DB00484': 'Brimonidine',
 'DB00485': 'Dicloxacillin',
 'DB00486': 'Nabilone',
 'DB00487': 'Pefloxacin',
 'DB00488': 'Altretamine',
 'DB00489': 'Sotalol',
 'DB00490': 'Buspirone',
 'DB00491': 'Miglitol',
 'DB00492': 'Fosinopril',
 'DB00493': 'Cefotaxime',
 'DB00494': 'Entacapone',
 'DB00495': 'Zidovudine',
 'DB00496': 'Darifenacin',
 'DB00497': 'Oxycodone',
 'DB00498': 'Phenindione',
 'DB00499': 'Flutamide',
 'DB00500': 'Tolmetin',
 'DB00501': 'Cimetidine',
 'DB00502': 'Haloperidol',
 'DB00503': 'Ritonavir',
 'DB00504': 'Levallorphan',
 'DB00505': 'Tridihexethyl',
 'DB00507': 'Nitazoxanide',
 'DB00508': 'Triflupromazine',
 'DB00509': 'Dextrothyroxine',
 'DB00511': 'Acetyldigitoxin',
 'DB00512': 'Vancomycin',
 'DB00513': 'Aminocaproic acid',
 'DB00514': 'Dextromethorphan',
 'DB00515': 'Cisplatin',
 'DB00516': 'Bentoquatam',
 'DB00517': 'Anisotropine methylbromide',
 'DB00518': 'Albendazole',
 'DB00519': 'Trandolapril',
 'DB00520': 'Caspofungin',
 'DB00521': 'Carteolol',
 'DB00522': 'Bentiromide',
 'DB00523': 'Alitretinoin',
 'DB00524': 'Metolazone',
 'DB00525': 'Tolnaftate',
 'DB00526': 'Oxaliplatin',
 'DB00527': 'Cinchocaine',
 'DB00528': 'Lercanidipine',
 'DB00529': 'Foscarnet',
 'DB00530': 'Erlotinib',
 'DB00531': 'Cyclophosphamide',
 'DB00532': 'Mephenytoin',
 'DB00533': 'Rofecoxib',
 'DB00534': 'Chlormerodrin',
 'DB00535': 'Cefdinir',
 'DB00536': 'Guanidine',
 'DB00537': 'Ciprofloxacin',
 'DB00538': 'Gadoversetamide',
 'DB00539': 'Toremifene',
 'DB00540': 'Nortriptyline',
 'DB00541': 'Vincristine',
 'DB00542': 'Benazepril',
 'DB00543': 'Amoxapine',
 'DB00544': 'Fluorouracil',
 'DB00545': 'Pyridostigmine',
 'DB00546': 'Adinazolam',
 'DB00547': 'Desoximetasone',
 'DB00548': 'Azelaic acid',
 'DB00549': 'Zafirlukast',
 'DB00550': 'Propylthiouracil',
 'DB00551': 'Acetohydroxamic acid',
 'DB00552': 'Pentostatin',
 'DB00553': 'Methoxsalen',
 'DB00554': 'Piroxicam',
 'DB00555': 'Lamotrigine',
 'DB00556': 'Perflutren',
 'DB00557': 'Hydroxyzine',
 'DB00558': 'Zanamivir',
 'DB00559': 'Bosentan',
 'DB00560': 'Tigecycline',
 'DB00561': 'Doxapram',
 'DB00562': 'Benzthiazide',
 'DB00563': 'Methotrexate',
 'DB00564': 'Carbamazepine',
 'DB00565': 'Cisatracurium',
 'DB00566': 'Succimer',
 'DB00567': 'Cephalexin',
 'DB00568': 'Cinnarizine',
 'DB00569': 'Fondaparinux',
 'DB00570': 'Vinblastine',
 'DB00571': 'Propranolol',
 'DB00572': 'Atropine',
 'DB00573': 'Fenoprofen',
 'DB00574': 'Fenfluramine',
 'DB00575': 'Clonidine',
 'DB00576': 'Sulfamethizole',
 'DB00577': 'Valaciclovir',
 'DB00578': 'Carbenicillin',
 'DB00579': 'Mazindol',
 'DB00580': 'Valdecoxib',
 'DB00581': 'Lactulose',
 'DB00582': 'Voriconazole',
 'DB00583': 'Levocarnitine',
 'DB00584': 'Enalapril',
 'DB00585': 'Nizatidine',
 'DB00586': 'Diclofenac',
 'DB00587': 'Cinalukast',
 'DB00588': 'Fluticasone propionate',
 'DB00589': 'Lisuride',
 'DB00590': 'Doxazosin',
 'DB00591': 'Fluocinolone acetonide',
 'DB00592': 'Piperazine',
 'DB00593': 'Ethosuximide',
 'DB00594': 'Amiloride',
 'DB00595': 'Oxytetracycline',
 'DB00596': 'Ulobetasol',
 'DB00597': 'Gadoteridol',
 'DB00598': 'Labetalol',
 'DB00599': 'Thiopental',
 'DB00600': 'Monobenzone',
 'DB00601': 'Linezolid',
 'DB00602': 'Ivermectin',
 'DB00603': 'Medroxyprogesterone acetate',
 'DB00604': 'Cisapride',
 'DB00605': 'Sulindac',
 'DB00606': 'Cyclothiazide',
 'DB00607': 'Nafcillin',
 'DB00608': 'Chloroquine',
 'DB00609': 'Ethionamide',
 'DB00610': 'Metaraminol',
 'DB00611': 'Butorphanol',
 'DB00612': 'Bisoprolol',
 'DB00613': 'Amodiaquine',
 'DB00614': 'Furazolidone',
 'DB00615': 'Rifabutin',
 'DB00616': 'Candoxatril',
 'DB00617': 'Paramethadione',
 'DB00618': 'Demeclocycline',
 'DB00619': 'Imatinib',
 'DB00620': 'Triamcinolone',
 'DB00621': 'Oxandrolone',
 'DB00622': 'Nicardipine',
 'DB00623': 'Fluphenazine',
 'DB00624': 'Testosterone',
 'DB00625': 'Efavirenz',
 'DB00626': 'Bacitracin',
 'DB00627': 'Niacin',
 'DB00628': 'Clorazepic acid',
 'DB00629': 'Guanabenz',
 'DB00630': 'Alendronic acid',
 'DB00631': 'Clofarabine',
 'DB00632': 'Docosanol',
 'DB00633': 'Dexmedetomidine',
 'DB00634': 'Sulfacetamide',
 'DB00635': 'Prednisone',
 'DB00636': 'Clofibrate',
 'DB00637': 'Astemizole',
 'DB00638': 'Inulin',
 'DB00639': 'Butoconazole',
 'DB00640': 'Adenosine',
 'DB00641': 'Simvastatin',
 'DB00642': 'Pemetrexed',
 'DB00643': 'Mebendazole',
 'DB00644': 'Gonadorelin',
 'DB00645': 'Dyclonine',
 'DB00646': 'Nystatin',
 'DB00647': 'Dextropropoxyphene',
 'DB00648': 'Mitotane',
 'DB00649': 'Stavudine',
 'DB00650': 'Leucovorin',
 'DB00651': 'Dyphylline',
 'DB00652': 'Pentazocine',
 'DB00653': 'Magnesium sulfate',
 'DB00654': 'Latanoprost',
 'DB00655': 'Estrone',
 'DB00656': 'Trazodone',
 'DB00657': 'Mecamylamine',
 'DB00658': 'Sevelamer',
 'DB00659': 'Acamprosate',
 'DB00660': 'Metaxalone',
 'DB00661': 'Verapamil',
 'DB00662': 'Trimethobenzamide',
 'DB00663': 'Flumethasone',
 'DB00664': 'Sulfametopyrazine',
 'DB00665': 'Nilutamide',
 'DB00666': 'Nafarelin',
 'DB00668': 'Epinephrine',
 'DB00669': 'Sumatriptan',
 'DB00670': 'Pirenzepine',
 'DB00671': 'Cefixime',
 'DB00672': 'Chlorpropamide',
 'DB00673': 'Aprepitant',
 'DB00674': 'Galantamine',
 'DB00675': 'Tamoxifen',
 'DB00676': 'Benzyl benzoate',
 'DB00677': 'Isoflurophate',
 'DB00678': 'Losartan',
 'DB00679': 'Thioridazine',
 'DB00680': 'Moricizine',
 'DB00681': 'Amphotericin B',
 'DB00682': 'Warfarin',
 'DB00683': 'Midazolam',
 'DB00684': 'Tobramycin',
 'DB00685': 'Trovafloxacin',
 'DB00686': 'Pentosan polysulfate',
 'DB00687': 'Fludrocortisone',
 'DB00688': 'Mycophenolate mofetil',
 'DB00689': 'Cephaloglycin',
 'DB00690': 'Flurazepam',
 'DB00691': 'Moexipril',
 'DB00692': 'Phentolamine',
 'DB00693': 'Fluorescein',
 'DB00694': 'Daunorubicin',
 'DB00695': 'Furosemide',
 'DB00696': 'Ergotamine',
 'DB00697': 'Tizanidine',
 'DB00698': 'Nitrofurantoin',
 'DB00699': 'Nicergoline',
 'DB00700': 'Eplerenone',
 'DB00701': 'Amprenavir',
 'DB00702': 'Icodextrin',
 'DB00703': 'Methazolamide',
 'DB00704': 'Naltrexone',
 'DB00705': 'Delavirdine',
 'DB00706': 'Tamsulosin',
 'DB00707': 'Porfimer sodium',
 'DB00708': 'Sufentanil',
 'DB00709': 'Lamivudine',
 'DB00710': 'Ibandronate',
 'DB00711': 'Diethylcarbamazine',
 'DB00712': 'Flurbiprofen',
 'DB00713': 'Oxacillin',
 'DB00714': 'Apomorphine',
 'DB00715': 'Paroxetine',
 'DB00716': 'Nedocromil',
 'DB00717': 'Norethisterone',
 'DB00718': 'Adefovir dipivoxil',
 'DB00719': 'Azatadine',
 'DB00720': 'Clodronic acid',
 'DB00721': 'Procaine',
 'DB00722': 'Lisinopril',
 'DB00723': 'Methoxamine',
 'DB00724': 'Imiquimod',
 'DB00725': 'Homatropine methylbromide',
 'DB00726': 'Trimipramine',
 'DB00727': 'Nitroglycerin',
 'DB00728': 'Rocuronium',
 'DB00730': 'Thiabendazole',
 'DB00731': 'Nateglinide',
 'DB00732': 'Atracurium besylate',
 'DB00733': 'Pralidoxime',

## 2. Load KG Sources

### 2a. CKG

In [4]:
CKG_Chemical_Mutation = pd.read_csv(PROC_DIR + 'CKG/File_2_Drug_MutationVariant_CKG.csv')
CKG_Chemical_Mutation.columns = CKG_Chemical_Mutation.columns.str.lower()
print(f"CKG:    {len(CKG_Chemical_Mutation):,} rows | columns: {list(CKG_Chemical_Mutation.columns)}")
CKG_Chemical_Mutation.rename(columns={'head_smiles': 'head_detail_name'}, inplace=True)

CKG_Chemical_Mutation['kg_type'] = 'Generalised'
CKG_Chemical_Mutation['species'] = 'Homo sapiens'
CKG_Chemical_Mutation['relation'] = 'ChemicalEntity_Mutation'
CKG_Chemical_Mutation['head_type'] = 'ChemicalEntity'
CKG_Chemical_Mutation['tail_type'] = 'Mutation'
CKG_Chemical_Mutation.head(2)

CKG:    13,661 rows | columns: ['head', 'relation', 'tail', 'head_type', 'relation_type', 'tail_type', 'source', 'kg_source', "head_alt_id's", 'head_iupac', 'head_smiles', 'head_id_is', 'tail_id_is', 'evidence', 'response', 'disease']

,head,relation,tail,head_type,relation_type,tail_type,source,kg_source,head_alt_id's,head_iupac,head_detail_name,head_id_is,tail_id_is,evidence,response,disease,kg_type,species
0,10184653,ChemicalEntity_Mutation,Q504U8_p.Gly719Ser,ChemicalEntity,curated,Mutation,CGI,CKG,DB08916,CN(C)C/C=C/C(=O)NC1=C(C=C2C(=C1)C(=NC=N2)NC3=C...,(E)-N-[4-(3-chloro-4-fluoroanilino)-7-[(3S)-ox...,Pubchem,protein_mutation_name,Early trials,Responsive,Lung,Generalised,Homo sapiens
1,DB00002,ChemicalEntity_Mutation,B6RC66_p.Gly465Arg,ChemicalEntity,curated,Mutation,CGI,CKG,DB00002,Cetuximab,NaN,Drugbank,protein_mutation_name,Pre-clinical,Resistant,Colorectal adenocarcinoma,Generalised,Homo sapiens

In [5]:
CKG_Chemical_Mutation_2 = pd.read_csv(PROC_DIR + 'CKG/File_3_Drug_MutationVariant_OncoKB_CKG.csv')
CKG_Chemical_Mutation_2.columns = CKG_Chemical_Mutation_2.columns.str.lower()
print(f"CKG:    {len(CKG_Chemical_Mutation_2):,} rows | columns: {list(CKG_Chemical_Mutation_2.columns)}")
CKG_Chemical_Mutation_2.rename(columns={'head_smiles': 'head_detail_name'}, inplace=True)

CKG_Chemical_Mutation_2['kg_type'] = 'Generalised'
CKG_Chemical_Mutation_2['species'] = 'Homo sapiens'

CKG_Chemical_Mutation_2['relation'] = 'ChemicalEntity_Mutation'
CKG_Chemical_Mutation_2['head_type'] = 'ChemicalEntity'
CKG_Chemical_Mutation_2['tail_type'] = 'Mutation'
CKG_Chemical_Mutation_2['species'] = 'Homo sapiens'

CKG_Chemical_Mutation_2.head(2)

CKG:    3,439 rows | columns: ['head', 'relation', 'tail', 'head_type', 'relation_type', 'tail_type', 'source', 'kg_source', "head_alt_id's", 'head_iupac', 'head_smiles', 'head_id_is', 'tail_id_is', 'evidence', 'response', 'disease']

,head,relation,tail,head_type,relation_type,tail_type,source,kg_source,head_alt_id's,head_iupac,head_detail_name,head_id_is,tail_id_is,evidence,response,disease,kg_type,species
0,10184653,ChemicalEntity_Mutation,F1JTL6_p.Thr790Met,ChemicalEntity,curated,Mutation,OncoKB,CKG,DB08916,CN(C)C/C=C/C(=O)NC1=C(C=C2C(=C1)C(=NC=N2)NC3=C...,(E)-N-[4-(3-chloro-4-fluoroanilino)-7-[(3S)-ox...,Pubchem,protein_mutation_name,R,1,Non-Small Cell Lung Cancer,Generalised,Homo sapiens
1,11167602,ChemicalEntity_Mutation,P10721-2_p.Thr670Ile,ChemicalEntity,curated,Mutation,OncoKB,CKG,DB08896,CNC(=O)C1=NC=CC(=C1)OC2=CC(=C(C=C2)NC(=O)NC3=C...,4-[4-[[4-chloro-3-(trifluoromethyl)phenyl]carb...,Pubchem,protein_mutation_name,approved,Responsive,Gastrointestinal Stromal Tumor,Generalised,Homo sapiens

### 2b. Hald

In [6]:
hald = pd.read_csv(PROC_DIR + 'hald/Chemical_Mutation_HALD.csv')
hald.rename(columns={'relation_source': 'kg_source', 'tail_name': 'head_detail_name'}, inplace=True)
hald.columns = hald.columns.str.lower()
print(f"EvoAGE: {len(hald):,} rows | columns: {list(hald.columns)}")

hald['kg_type'] = 'Aging'
hald['species'] = 'Homo sapiens'
hald.head(2)

EvoAGE: 29 rows | columns: ['head', 'relation', 'tail', 'head_type', 'relation_type', 'tail_type', 'kg_source', 'head_detail_name', 'head_smiles_name', 'head_id_is']

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_detail_name,head_smiles_name,head_id_is,kg_type,species
0,Triglycerides,ChemicalEntity_Mutation,rs2805533,ChemicalEntity,associated,Mutation,HALD_KG,Triglycerides,Triglycerides,NaN,Aging,Homo sapiens
1,5793,ChemicalEntity_Mutation,rs1260326,ChemicalEntity,associated,Mutation,HALD_KG,"(3R,4S,5S,6R)-6-(hydroxymethyl)oxane-2,3,4,5-t...",C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)O,Pubchem,Aging,Homo sapiens

## 3. Check and Fix Duplicate Columns

In [7]:
SOURCE_DFS = [
    ('CKG_Chemical_Mutation', CKG_Chemical_Mutation),
    ('CKG_Chemical_Mutation_2', CKG_Chemical_Mutation_2),
    ('hald',                hald),
]

for name, df in SOURCE_DFS:
    dupes = df.columns[df.columns.duplicated(keep=False)].unique().tolist()
    if dupes:
        print(f"\n[{name}] duplicate columns: {dupes}")
        for col in dupes:
            for i, (_, s) in enumerate(df.loc[:, df.columns == col].items()):
                print(f"  '{col}' occurrence {i} → sample: {s.dropna().head(3).tolist()}")
    else:
        print(f"[{name}] ✓ no duplicates")

[CKG_Chemical_Mutation] ✓ no duplicates
[CKG_Chemical_Mutation_2] ✓ no duplicates
[hald] ✓ no duplicates

In [54]:
# # Edit keep='first'/'last' per DataFrame based on inspection above
# CKG_Chemical_Mutation = CKG_Chemical_Mutation.loc[:, ~CKG_Chemical_Mutation.columns.duplicated(keep='first')]
# EvoAGE                = hald.loc[:,                ~hald.columns.duplicated(keep='first')]

# for name, df in SOURCE_DFS:
#     remaining = df.columns[df.columns.duplicated()].tolist()
#     print(f"[{name}] {'✓ clean' if not remaining else '✗ still has dupes: ' + str(remaining)}")

## 4. Align Schemas and Concatenate

In [8]:
CONCAT_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

df_list = []
for name, df in SOURCE_DFS:
    tmp = df.copy()
    for col in CONCAT_COLS:
        if col not in tmp.columns:
            tmp[col] = pd.NA
    df_list.append(tmp[CONCAT_COLS])

final_df = pd.concat(df_list, ignore_index=True)
print(f"Combined: {len(final_df):,} rows")
final_df.head(2)

Combined: 17,129 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,10184653,ChemicalEntity_Mutation,Q504U8_p.Gly719Ser,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,(E)-N-[4-(3-chloro-4-fluoroanilino)-7-[(3S)-ox...,NaN,Generalised,Homo sapiens
1,DB00002,ChemicalEntity_Mutation,B6RC66_p.Gly465Arg,ChemicalEntity,curated,Mutation,CKG,Drugbank,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens

In [9]:
def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(final_df)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is               14                  14              28
tail_id_is               29                  29              58
head_detail_name       5334                5334           10668
tail_detail_name      17129               17129           34258
kg_type                   0                   0               0
species                   0                   0               0

In [10]:
final_df[final_df['head_detail_name'].isna()]

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
1,DB00002,ChemicalEntity_Mutation,B6RC66_p.Gly465Arg,ChemicalEntity,curated,Mutation,CKG,Drugbank,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens
2,allosteric AKT inhibitors,ChemicalEntity_Mutation,G3V4I6_p.Glu17Lys,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens
5,HSP90 inhibitors,ChemicalEntity_Mutation,S5LJ61_p.Arg175His,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens
10,EGFR inhibitor 1st gens,ChemicalEntity_Mutation,G9MC81_p.Asp761Tyr,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens
12,HSP90 inhibitors,ChemicalEntity_Mutation,L0EQY4_p.Arg175His,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16794,DB00002,ChemicalEntity_Mutation,F1CC75_p.Val600Glu,ChemicalEntity,curated,Mutation,CKG,Drugbank,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens
16802,DB01269,ChemicalEntity_Mutation,A0A2U3TZI2_p.Val600Glu,ChemicalEntity,curated,Mutation,CKG,Drugbank,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens
16820,DB00002,ChemicalEntity_Mutation,A0A0C4LC38_p.Val600Glu,ChemicalEntity,curated,Mutation,CKG,Drugbank,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens
16982,DB01269,ChemicalEntity_Mutation,A0A2R8Y679_p.Val600Glu,ChemicalEntity,curated,Mutation,CKG,Drugbank,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens
17072,DB00002,ChemicalEntity_Mutation,E2I6F4_p.Val600Glu,ChemicalEntity,curated,Mutation,CKG,Drugbank,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens

## 5. Resolve Head (Chemical) Names

1. PubChem IUPAC lookup (numeric CIDs).
2. Normalise DrugBank IDs to zero-padded 5-digit format.
3. DrugBank standard dict fallback for `DB`-prefixed IDs.
4. DrugBank extended dict (`drugbank_all`) second fallback.
5. Final fallback: use raw head value as name (covers compound names stored directly as IDs).
6. Drop any rows still missing `head_detail_name`.

In [11]:
# Step 1 – PubChem lookup
final_df['head_detail_name'] = final_df['head'].astype(str).map(Pubchem_IUPAC_CID_Dict)
final_df['head_smiles_name'] = final_df['head'].astype(str).map(Pubchem_CID_Smile_Dict)
final_df

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species,head_smiles_name
0,10184653,ChemicalEntity_Mutation,Q504U8_p.Gly719Ser,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,(E)-N-[4-(3-chloro-4-fluoroanilino)-7-[(3S)-ox...,NaN,Generalised,Homo sapiens,CN(C)C/C=C/C(=O)NC1=C(C=C2C(=C1)C(=NC=N2)NC3=C...
1,DB00002,ChemicalEntity_Mutation,B6RC66_p.Gly465Arg,ChemicalEntity,curated,Mutation,CKG,Drugbank,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens,NaN
2,allosteric AKT inhibitors,ChemicalEntity_Mutation,G3V4I6_p.Glu17Lys,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens,NaN
3,3062316,ChemicalEntity_Mutation,H7C4S5_p.Gly466Val,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,N-(2-chloro-6-methylphenyl)-2-[[6-[4-(2-hydrox...,NaN,Generalised,Homo sapiens,CC1=C(C(=CC=C1)Cl)NC(=O)C2=CN=C(S2)NC3=CC(=NC(...
4,9915743,ChemicalEntity_Mutation,A0A0R9RWK2_p.Thr798Ile,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,(E)-N-[4-[3-chloro-4-(pyridin-2-ylmethoxy)anil...,NaN,Generalised,Homo sapiens,CCOC1=C(C=C2C(=C1)N=CC(=C2NC3=CC(=C(C=C3)OCC4=...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17124,Ceramides,ChemicalEntity_Mutation,rs183444295,ChemicalEntity,decreased,Mutation,HALD_KG,NaN,NaN,NaN,NaN,Aging,Homo sapiens,NaN
17125,Ceramides,ChemicalEntity_Mutation,rs183444295,ChemicalEntity,tend,Mutation,HALD_KG,NaN,NaN,NaN,NaN,Aging,Homo sapiens,NaN
17126,Linoleic Acids,ChemicalEntity_Mutation,rs174537,ChemicalEntity,associated,Mutation,HALD_KG,NaN,NaN,NaN,NaN,Aging,Homo sapiens,NaN
17127,Linoleic Acids,ChemicalEntity_Mutation,rs953413,ChemicalEntity,associated,Mutation,HALD_KG,NaN,NaN,NaN,NaN,Aging,Homo sapiens,NaN
17128,5997,ChemicalEntity_Mutation,rs3020449,ChemicalEntity,associated,Mutation,HALD_KG,Pubchem,NaN,"(3S,8S,9S,10R,13R,14S,17R)-10,13-dimethyl-17-[...",NaN,Aging,Homo sapiens,C[C@H](CCCC(C)C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3...

In [19]:
# Step 2 – Normalise DrugBank IDs
def standardize_drugbank_id(val):
    if isinstance(val, str):
        m = re.match(r'^DB(\d+)$', val)
        if m:
            return 'DB' + m.group(1).zfill(5)
    return val

final_df['head'] = final_df['head'].apply(standardize_drugbank_id).astype(str)
final_df

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species,head_smiles_name
0,10184653,ChemicalEntity_Mutation,Q504U8_p.Gly719Ser,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,(E)-N-[4-(3-chloro-4-fluoroanilino)-7-[(3S)-ox...,NaN,Generalised,Homo sapiens,CN(C)C/C=C/C(=O)NC1=C(C=C2C(=C1)C(=NC=N2)NC3=C...
1,DB00002,ChemicalEntity_Mutation,B6RC66_p.Gly465Arg,ChemicalEntity,curated,Mutation,CKG,Drugbank,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens,NaN
2,allosteric AKT inhibitors,ChemicalEntity_Mutation,G3V4I6_p.Glu17Lys,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens,NaN
3,3062316,ChemicalEntity_Mutation,H7C4S5_p.Gly466Val,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,N-(2-chloro-6-methylphenyl)-2-[[6-[4-(2-hydrox...,NaN,Generalised,Homo sapiens,CC1=C(C(=CC=C1)Cl)NC(=O)C2=CN=C(S2)NC3=CC(=NC(...
4,9915743,ChemicalEntity_Mutation,A0A0R9RWK2_p.Thr798Ile,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,(E)-N-[4-[3-chloro-4-(pyridin-2-ylmethoxy)anil...,NaN,Generalised,Homo sapiens,CCOC1=C(C=C2C(=C1)N=CC(=C2NC3=CC(=C(C=C3)OCC4=...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17124,Ceramides,ChemicalEntity_Mutation,rs183444295,ChemicalEntity,decreased,Mutation,HALD_KG,NaN,NaN,NaN,NaN,Aging,Homo sapiens,NaN
17125,Ceramides,ChemicalEntity_Mutation,rs183444295,ChemicalEntity,tend,Mutation,HALD_KG,NaN,NaN,NaN,NaN,Aging,Homo sapiens,NaN
17126,Linoleic Acids,ChemicalEntity_Mutation,rs174537,ChemicalEntity,associated,Mutation,HALD_KG,NaN,NaN,NaN,NaN,Aging,Homo sapiens,NaN
17127,Linoleic Acids,ChemicalEntity_Mutation,rs953413,ChemicalEntity,associated,Mutation,HALD_KG,NaN,NaN,NaN,NaN,Aging,Homo sapiens,NaN
17128,5997,ChemicalEntity_Mutation,rs3020449,ChemicalEntity,associated,Mutation,HALD_KG,Pubchem,NaN,"(3S,8S,9S,10R,13R,14S,17R)-10,13-dimethyl-17-[...",NaN,Aging,Homo sapiens,C[C@H](CCCC(C)C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3...

In [20]:
# Step 3 – DrugBank fallback
mask = final_df['head_detail_name'].isna() & final_df['head'].str.startswith('DB')
final_df.loc[mask, 'head_detail_name'] = final_df.loc[mask, 'head'].map(Drugbank_dict)
final_df

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species,head_smiles_name
0,10184653,ChemicalEntity_Mutation,Q504U8_p.Gly719Ser,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,(E)-N-[4-(3-chloro-4-fluoroanilino)-7-[(3S)-ox...,NaN,Generalised,Homo sapiens,CN(C)C/C=C/C(=O)NC1=C(C=C2C(=C1)C(=NC=N2)NC3=C...
1,DB00002,ChemicalEntity_Mutation,B6RC66_p.Gly465Arg,ChemicalEntity,curated,Mutation,CKG,Drugbank,protein_mutation_name,Cetuximab,NaN,Generalised,Homo sapiens,NaN
2,allosteric AKT inhibitors,ChemicalEntity_Mutation,G3V4I6_p.Glu17Lys,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,NaN,NaN,Generalised,Homo sapiens,NaN
3,3062316,ChemicalEntity_Mutation,H7C4S5_p.Gly466Val,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,N-(2-chloro-6-methylphenyl)-2-[[6-[4-(2-hydrox...,NaN,Generalised,Homo sapiens,CC1=C(C(=CC=C1)Cl)NC(=O)C2=CN=C(S2)NC3=CC(=NC(...
4,9915743,ChemicalEntity_Mutation,A0A0R9RWK2_p.Thr798Ile,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,(E)-N-[4-[3-chloro-4-(pyridin-2-ylmethoxy)anil...,NaN,Generalised,Homo sapiens,CCOC1=C(C=C2C(=C1)N=CC(=C2NC3=CC(=C(C=C3)OCC4=...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17124,Ceramides,ChemicalEntity_Mutation,rs183444295,ChemicalEntity,decreased,Mutation,HALD_KG,NaN,NaN,NaN,NaN,Aging,Homo sapiens,NaN
17125,Ceramides,ChemicalEntity_Mutation,rs183444295,ChemicalEntity,tend,Mutation,HALD_KG,NaN,NaN,NaN,NaN,Aging,Homo sapiens,NaN
17126,Linoleic Acids,ChemicalEntity_Mutation,rs174537,ChemicalEntity,associated,Mutation,HALD_KG,NaN,NaN,NaN,NaN,Aging,Homo sapiens,NaN
17127,Linoleic Acids,ChemicalEntity_Mutation,rs953413,ChemicalEntity,associated,Mutation,HALD_KG,NaN,NaN,NaN,NaN,Aging,Homo sapiens,NaN
17128,5997,ChemicalEntity_Mutation,rs3020449,ChemicalEntity,associated,Mutation,HALD_KG,Pubchem,NaN,"(3S,8S,9S,10R,13R,14S,17R)-10,13-dimethyl-17-[...",NaN,Aging,Homo sapiens,C[C@H](CCCC(C)C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3...

In [22]:

import numpy as np

final_df['head_detail_name'] = (
    final_df['head_detail_name']
    .replace(['NaN', 'nan', '', ' '], np.nan)
    .fillna(final_df['head'])
)


final_df

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species,head_smiles_name
0,10184653,ChemicalEntity_Mutation,Q504U8_p.Gly719Ser,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,(E)-N-[4-(3-chloro-4-fluoroanilino)-7-[(3S)-ox...,NaN,Generalised,Homo sapiens,CN(C)C/C=C/C(=O)NC1=C(C=C2C(=C1)C(=NC=N2)NC3=C...
1,DB00002,ChemicalEntity_Mutation,B6RC66_p.Gly465Arg,ChemicalEntity,curated,Mutation,CKG,Drugbank,protein_mutation_name,Cetuximab,NaN,Generalised,Homo sapiens,NaN
2,allosteric AKT inhibitors,ChemicalEntity_Mutation,G3V4I6_p.Glu17Lys,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,Triglycerides,NaN,Generalised,Homo sapiens,NaN
3,3062316,ChemicalEntity_Mutation,H7C4S5_p.Gly466Val,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,N-(2-chloro-6-methylphenyl)-2-[[6-[4-(2-hydrox...,NaN,Generalised,Homo sapiens,CC1=C(C(=CC=C1)Cl)NC(=O)C2=CN=C(S2)NC3=CC(=NC(...
4,9915743,ChemicalEntity_Mutation,A0A0R9RWK2_p.Thr798Ile,ChemicalEntity,curated,Mutation,CKG,Pubchem,protein_mutation_name,(E)-N-[4-[3-chloro-4-(pyridin-2-ylmethoxy)anil...,NaN,Generalised,Homo sapiens,CCOC1=C(C=C2C(=C1)N=CC(=C2NC3=CC(=C(C=C3)OCC4=...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17124,Ceramides,ChemicalEntity_Mutation,rs183444295,ChemicalEntity,decreased,Mutation,HALD_KG,NaN,NaN,Ceramides,NaN,Aging,Homo sapiens,NaN
17125,Ceramides,ChemicalEntity_Mutation,rs183444295,ChemicalEntity,tend,Mutation,HALD_KG,NaN,NaN,Ceramides,NaN,Aging,Homo sapiens,NaN
17126,Linoleic Acids,ChemicalEntity_Mutation,rs174537,ChemicalEntity,associated,Mutation,HALD_KG,NaN,NaN,Linoleic Acids,NaN,Aging,Homo sapiens,NaN
17127,Linoleic Acids,ChemicalEntity_Mutation,rs953413,ChemicalEntity,associated,Mutation,HALD_KG,NaN,NaN,Linoleic Acids,NaN,Aging,Homo sapiens,NaN
17128,5997,ChemicalEntity_Mutation,rs3020449,ChemicalEntity,associated,Mutation,HALD_KG,Pubchem,NaN,"(3S,8S,9S,10R,13R,14S,17R)-10,13-dimethyl-17-[...",NaN,Aging,Homo sapiens,C[C@H](CCCC(C)C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3...

In [23]:
# Step 4 – Assign head_id_is
final_df['head_id_is'] = np.where(
    final_df['head'].isna(), None,
    np.where(final_df['head'].str.startswith('DB'), 'Drugbank', 'Pubchem')
)
final_df
# Step 5 – Drop unresolvable rows
before = len(final_df)
final_df = final_df[
    ~final_df['head_detail_name'].isna()
].reset_index(drop=True)
final_df
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 17,129 remaining

## 6. Standardise Fixed-Value Columns

In [26]:
final_df['head_type'] = 'ChemicalEntity'
final_df['tail_type'] = 'Mutation'
final_df['relation']  = 'ChemicalEntity_Mutation'
final_df['tail_id_is'] = 'Mutation'

# head_id_is: DB-prefix → Drugbank, numeric → Pubchem, else NaN
final_df['head'] = final_df['head'].astype(str)
final_df['head_id_is'] = np.where(
    final_df['head'].isna(), np.nan,
    np.where(final_df['head'].str.startswith('DB'), 'Drugbank',
    np.where(final_df['head'].str.match(r'^\d+$'), 'Pubchem', None)) # intentional None becauce some are just names like Cermides etc
)

print("Unique relation:",   set(final_df['relation']))
print("Unique head_type:",  set(final_df['head_type']))
print("Unique tail_type:",  set(final_df['tail_type']))
print("Unique head_id_is:", set(final_df['head_id_is']))
print("Unique kg_source:",  set(final_df['kg_source']))

Unique relation: {'ChemicalEntity_Mutation'}
Unique head_type: {'ChemicalEntity'}
Unique tail_type: {'Mutation'}
Unique head_id_is: {'Pubchem', None, 'Drugbank'}
Unique kg_source: {'CKG', 'HALD_KG'}

In [27]:
# final_df[final_df['head_id_is'].isna()]

## 7. Deduplicate

In [28]:
GROUP_COLS = ['head', 'relation', 'tail']

def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

final_df_dedup = final_df.groupby(GROUP_COLS, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':         merge_sources,
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'kg_type': merge_sources,
    'species': 'first',
})
print(f"After deduplication: {len(final_df_dedup):,} rows")

After deduplication: 13,808 rows

## 8. Add Schema Columns and Enforce Column Order

In [29]:
# EXTRA_COLS = ['head_smiles_name']
# final_df_dedup = final_df_dedup[REQUIRED_COLS + EXTRA_COLS]

# print(f"Final shape: {final_df_dedup.shape}")
# final_df_dedup.head()

In [30]:
# final_df_dedup[final_df_dedup['head_id_is'].isna()]

<!-- ## 9. QC — NaN Check -->

In [31]:

nan_summary(final_df_dedup)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is             4320                   0            4320
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name      13808                   0           13808
kg_type                   0                   0               0
species                   0                   0               0

## 10. Save Output

In [32]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 13,808 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/CHEMICALENTITY_MUTATION/ALL_CHEMICALENTITY_MUTATION.csv

In [12]:
#