In [3]:
import os
import pandas as pd
import numpy as np

BASE_DIR   = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR   = BASE_DIR + 'processed_data/'
DB_DIR     = BASE_DIR + 'data_collection/databases_for_mapping/'

OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/PMID_DISEASE/ALL_PMID_DISEASE.parquet'

REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

## 2. Load KG Sources

#### CKG

In [3]:
CKG = pd.read_csv(PROC_DIR + 'CKG/File_16_PMID_Disease_CKG.csv')
CKG

/tmp/ipykernel_3058171/756830279.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  CKG = pd.read_csv(PROC_DIR + 'CKG/File_16_PMID_Disease_CKG.csv')

,Head,Relation,Tail,Head_type,Tail_type,KG_Source,Tail_DO_name,Tail_DO_Alt_ids,Head_ID_IS,Tail_ID_IS
0,PMID:20300260,MENTIONED_IN_PUBLICATION,DOID:0001816,PMID,Disease,CKG,angiosarcoma,ICDO:9120/3|MESH:D006394|NCI:C3088|NCI:C9275|S...,PubmedID,DiseaseOntology
1,PMID:19675708,MENTIONED_IN_PUBLICATION,DOID:0001816,PMID,Disease,CKG,angiosarcoma,ICDO:9120/3|MESH:D006394|NCI:C3088|NCI:C9275|S...,PubmedID,DiseaseOntology
2,PMID:19139624,MENTIONED_IN_PUBLICATION,DOID:0001816,PMID,Disease,CKG,angiosarcoma,ICDO:9120/3|MESH:D006394|NCI:C3088|NCI:C9275|S...,PubmedID,DiseaseOntology
3,PMID:19935795,MENTIONED_IN_PUBLICATION,DOID:0001816,PMID,Disease,CKG,angiosarcoma,ICDO:9120/3|MESH:D006394|NCI:C3088|NCI:C9275|S...,PubmedID,DiseaseOntology
4,PMID:20339539,MENTIONED_IN_PUBLICATION,DOID:0001816,PMID,Disease,CKG,angiosarcoma,ICDO:9120/3|MESH:D006394|NCI:C3088|NCI:C9275|S...,PubmedID,DiseaseOntology
...,...,...,...,...,...,...,...,...,...,...
192843418,PMID:33960521,MENTIONED_IN_PUBLICATION,DOID:9997,PMID,Disease,CKG,peripartum cardiomyopathy,GARD:220|ICD10CM:O90.3|ICD9CM:674.5|NCI:C17160...,PubmedID,DiseaseOntology
192843419,PMID:33893006,MENTIONED_IN_PUBLICATION,DOID:9997,PMID,Disease,CKG,peripartum cardiomyopathy,GARD:220|ICD10CM:O90.3|ICD9CM:674.5|NCI:C17160...,PubmedID,DiseaseOntology
192843420,PMID:8969606,MENTIONED_IN_PUBLICATION,DOID:9997,PMID,Disease,CKG,peripartum cardiomyopathy,GARD:220|ICD10CM:O90.3|ICD9CM:674.5|NCI:C17160...,PubmedID,DiseaseOntology
192843421,PMID:8502901,MENTIONED_IN_PUBLICATION,DOID:9997,PMID,Disease,CKG,peripartum cardiomyopathy,GARD:220|ICD10CM:O90.3|ICD9CM:674.5|NCI:C17160...,PubmedID,DiseaseOntology
192843422,PMID:139328,MENTIONED_IN_PUBLICATION,DOID:9997,PMID,Disease,CKG,peripartum cardiomyopathy,GARD:220|ICD10CM:O90.3|ICD9CM:674.5|NCI:C17160...,PubmedID,DiseaseOntology

In [9]:
CKG.columns = CKG.columns.str.lower()
CKG.rename(columns={'tail_do_name': 'tail_detail_name'}, inplace=True)
CKG['relation'] = 'PMID_Disease'
CKG['tail_type'] = 'Disease'
CKG['kg_type'] = 'Generalised'
CKG['kg_source'] = 'CKG'
CKG['species'] = 'Homo species'
CKG

,head,relation,tail,head_type,tail_type,kg_source,tail_detail_name,tail_do_alt_ids,head_id_is,tail_id_is,kg_type,species
0,PMID:20300260,PMID_Disease,DOID:0001816,PMID,Disease,CKG,angiosarcoma,ICDO:9120/3|MESH:D006394|NCI:C3088|NCI:C9275|S...,PubmedID,DiseaseOntology,Generalised,Homo species
1,PMID:19675708,PMID_Disease,DOID:0001816,PMID,Disease,CKG,angiosarcoma,ICDO:9120/3|MESH:D006394|NCI:C3088|NCI:C9275|S...,PubmedID,DiseaseOntology,Generalised,Homo species
2,PMID:19139624,PMID_Disease,DOID:0001816,PMID,Disease,CKG,angiosarcoma,ICDO:9120/3|MESH:D006394|NCI:C3088|NCI:C9275|S...,PubmedID,DiseaseOntology,Generalised,Homo species
3,PMID:19935795,PMID_Disease,DOID:0001816,PMID,Disease,CKG,angiosarcoma,ICDO:9120/3|MESH:D006394|NCI:C3088|NCI:C9275|S...,PubmedID,DiseaseOntology,Generalised,Homo species
4,PMID:20339539,PMID_Disease,DOID:0001816,PMID,Disease,CKG,angiosarcoma,ICDO:9120/3|MESH:D006394|NCI:C3088|NCI:C9275|S...,PubmedID,DiseaseOntology,Generalised,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...
192843418,PMID:33960521,PMID_Disease,DOID:9997,PMID,Disease,CKG,peripartum cardiomyopathy,GARD:220|ICD10CM:O90.3|ICD9CM:674.5|NCI:C17160...,PubmedID,DiseaseOntology,Generalised,Homo species
192843419,PMID:33893006,PMID_Disease,DOID:9997,PMID,Disease,CKG,peripartum cardiomyopathy,GARD:220|ICD10CM:O90.3|ICD9CM:674.5|NCI:C17160...,PubmedID,DiseaseOntology,Generalised,Homo species
192843420,PMID:8969606,PMID_Disease,DOID:9997,PMID,Disease,CKG,peripartum cardiomyopathy,GARD:220|ICD10CM:O90.3|ICD9CM:674.5|NCI:C17160...,PubmedID,DiseaseOntology,Generalised,Homo species
192843421,PMID:8502901,PMID_Disease,DOID:9997,PMID,Disease,CKG,peripartum cardiomyopathy,GARD:220|ICD10CM:O90.3|ICD9CM:674.5|NCI:C17160...,PubmedID,DiseaseOntology,Generalised,Homo species
192843422,PMID:139328,PMID_Disease,DOID:9997,PMID,Disease,CKG,peripartum cardiomyopathy,GARD:220|ICD10CM:O90.3|ICD9CM:674.5|NCI:C17160...,PubmedID,DiseaseOntology,Generalised,Homo species

In [10]:
SOURCE_DFS = [
              ('CKG', CKG)
             ]
for name, df in SOURCE_DFS:
    dupes = df.columns[df.columns.duplicated(keep=False)].unique().tolist()
    print(f"[{name}] {'duplicate columns: ' + str(dupes) if dupes else '✓ no duplicates'}")

[CKG] ✓ no duplicates

In [11]:
CONCAT_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name','kg_type', 'species'
]

df_list = []
for name, df in SOURCE_DFS:
    tmp = df.loc[:, ~df.columns.duplicated()].copy()
    for col in CONCAT_COLS:
        if col not in tmp.columns:
            tmp[col] = pd.NA
    df_list.append(tmp[CONCAT_COLS])

final_df = pd.concat(df_list, ignore_index=True)
print(f"Combined: {len(final_df):,} rows")
final_df

Combined: 192,843,423 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,PMID:20300260,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DiseaseOntology,<NA>,angiosarcoma,Generalised,Homo species
1,PMID:19675708,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DiseaseOntology,<NA>,angiosarcoma,Generalised,Homo species
2,PMID:19139624,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DiseaseOntology,<NA>,angiosarcoma,Generalised,Homo species
3,PMID:19935795,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DiseaseOntology,<NA>,angiosarcoma,Generalised,Homo species
4,PMID:20339539,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DiseaseOntology,<NA>,angiosarcoma,Generalised,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
192843418,PMID:33960521,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DiseaseOntology,<NA>,peripartum cardiomyopathy,Generalised,Homo species
192843419,PMID:33893006,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DiseaseOntology,<NA>,peripartum cardiomyopathy,Generalised,Homo species
192843420,PMID:8969606,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DiseaseOntology,<NA>,peripartum cardiomyopathy,Generalised,Homo species
192843421,PMID:8502901,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DiseaseOntology,<NA>,peripartum cardiomyopathy,Generalised,Homo species
192843422,PMID:139328,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DiseaseOntology,<NA>,peripartum cardiomyopathy,Generalised,Homo species

In [12]:
final_df['tail_id_is'] = 'DOID'
final_df = final_df[~final_df['tail_detail_name'].isna()]
final_df

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,PMID:20300260,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,angiosarcoma,Generalised,Homo species
1,PMID:19675708,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,angiosarcoma,Generalised,Homo species
2,PMID:19139624,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,angiosarcoma,Generalised,Homo species
3,PMID:19935795,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,angiosarcoma,Generalised,Homo species
4,PMID:20339539,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,angiosarcoma,Generalised,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
192843418,PMID:33960521,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,peripartum cardiomyopathy,Generalised,Homo species
192843419,PMID:33893006,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,peripartum cardiomyopathy,Generalised,Homo species
192843420,PMID:8969606,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,peripartum cardiomyopathy,Generalised,Homo species
192843421,PMID:8502901,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,peripartum cardiomyopathy,Generalised,Homo species
192843422,PMID:139328,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,peripartum cardiomyopathy,Generalised,Homo species

In [13]:
import pandas as pd
import numpy as np

# Vectorized hash using numpy — avoids Python string ops entirely
keys = (
    pd.util.hash_array(final_df['head'].to_numpy()) ^
    pd.util.hash_array(final_df['relation'].to_numpy()) * 2654435761 ^
    pd.util.hash_array(final_df['tail'].to_numpy()) * 40503
)

# Keep first occurrence of each hash
mask = ~pd.Series(keys).duplicated(keep='first').to_numpy()
final_df = final_df.iloc[mask].reset_index(drop=True)

print(f"After dedup: {len(final_df):,} rows")
final_df

After dedup: 192,843,423 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,PMID:20300260,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,angiosarcoma,Generalised,Homo species
1,PMID:19675708,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,angiosarcoma,Generalised,Homo species
2,PMID:19139624,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,angiosarcoma,Generalised,Homo species
3,PMID:19935795,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,angiosarcoma,Generalised,Homo species
4,PMID:20339539,PMID_Disease,DOID:0001816,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,angiosarcoma,Generalised,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
192843418,PMID:33960521,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,peripartum cardiomyopathy,Generalised,Homo species
192843419,PMID:33893006,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,peripartum cardiomyopathy,Generalised,Homo species
192843420,PMID:8969606,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,peripartum cardiomyopathy,Generalised,Homo species
192843421,PMID:8502901,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,peripartum cardiomyopathy,Generalised,Homo species
192843422,PMID:139328,PMID_Disease,DOID:9997,PMID,<NA>,Disease,CKG,PubmedID,DOID,<NA>,peripartum cardiomyopathy,Generalised,Homo species

In [16]:
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
final_df.to_parquet(OUT_PATH, index=False)
print(f"Saved {len(final_df):,} rows → {OUT_PATH}")

Saved 192,843,423 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/PMID_CELLULARCOMPONENT/ALL_PMID_CELLULARCOMPONENT.parquet

In [4]:
#