# Protein ↔ Tissue Relation-Wise Merge

## 0. Configuration

In [40]:
import os
import pandas as pd

BASE_DIR   = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR   = BASE_DIR + 'processed_data/'
DB_DIR     = BASE_DIR + 'data_collection/databases_for_mapping/'

OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/PROTEIN_TISSUE/ALL_PROTEIN_TISSUE.parquet'

REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

In [41]:
# RecName dict (AC → RecName)
Uniprot_Recname = pd.read_csv(DB_DIR + 'uniprot/Uniprot_ID_Recname.csv')
Uniprot_Recname_dict = dict(zip(Uniprot_Recname['AC'], Uniprot_Recname['RecName']))

# Parsed TrEMBL dict (AC → NAME) for head/tail name fallback
uniprot = pd.read_csv(DB_DIR + 'uniprot/uniprot_parsed_results.csv')
uniprot_trembl_AC_Name_dict = dict(zip(uniprot['AC'], uniprot['NAME']))
del uniprot

print(f"UniProt RecName dict: {len(Uniprot_Recname_dict):,} | TrEMBL dict: {len(uniprot_trembl_AC_Name_dict):,}")

UniProt RecName dict: 794,151 | TrEMBL dict: 252,635,149

## 1. Load KG Sources

### 1a. ageanno_mo

In [6]:
ageanno_mo = pd.read_csv(PROC_DIR + 'ageanno_processed_mo/AgeAnnoMO_Human_Protein_Tissue.csv')
ageanno_mo.rename(columns={'relation_source': 'kg_source', 'tail_name': 'head_detail_name'}, inplace=True)
ageanno_mo.columns = ageanno_mo.columns.str.lower()
print(f"ageanno_mo: {len(ageanno_mo):,} rows | columns: {list(ageanno_mo.columns)}")

ageanno_mo['kg_type'] = 'Aging'
ageanno_mo['kg_source'] = 'AgeAnnoMO'
ageanno_mo['species'] = 'Homo species'
ageanno_mo.head(2)

ageanno_mo: 1,133 rows | columns: ['head', 'relation', 'tail', 'head_type', 'tail_type', 'head_id_is', 'tail_id_is', 'relation_source', 'species', 'tail_detail_name', 'head_detail_name']

,head,relation,tail,head_type,tail_type,head_id_is,tail_id_is,relation_source,species,tail_detail_name,head_detail_name,kg_type,kg_source
0,P01023,Gene_Tissue,BTO:0000131,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Homo species,blood plasma,Alpha-2-macroglobulin,Aging,AgeAnnoMO
1,P42684,Gene_Tissue,BTO:0000131,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Homo species,blood plasma,Tyrosine-protein kinase ABL2,Aging,AgeAnnoMO

### 1b. ckg

In [9]:
ckg = pd.read_csv(PROC_DIR + 'CKG/File_7_ProtQC_bioM_Tissue_CKG.csv')
ckg.rename(columns={'relation_source': 'kg_source', 'tail_name': 'head_detail_name'}, inplace=True)
ckg.columns = ckg.columns.str.lower()
print(f"ckg: {len(ckg):,} rows | columns: {list(ckg.columns)}")
ckg['kg_type'] = 'Generalised'
ckg['kg_source'] = 'CKG'
ckg['species'] = 'Homo species'
ckg.head(2)

ckg: 255 rows | columns: ['head', 'relation', 'tail', 'head_type', 'tail_type', 'kg_source', 'head_alt_name', 'tail_bto_name', 'head_id_is', 'tail_id_is']

,head,relation,tail,head_type,tail_type,kg_source,head_alt_name,tail_bto_name,head_id_is,tail_id_is,kg_type,species
0,P69905,IS_QCMARKER_IN,BTO:0000131,Protein_QC_BioM,Tissue_Ontology,CKG,Hemopressin {ECO:0000303|PubMed:18077343},blood plasma,Uniprot,BrendaTO,Generalised,Homo species
1,P68871,IS_QCMARKER_IN,BTO:0000131,Protein_QC_BioM,Tissue_Ontology,CKG,Spinorphin,blood plasma,Uniprot,BrendaTO,Generalised,Homo species

In [25]:
ckg

,head,relation,tail,head_type,tail_type,kg_source,head_alt_name,tail_bto_name,head_id_is,tail_id_is,kg_type,species
0,P69905,IS_QCMARKER_IN,BTO:0000131,Protein_QC_BioM,Tissue_Ontology,CKG,Hemopressin {ECO:0000303|PubMed:18077343},blood plasma,Uniprot,BrendaTO,Generalised,Homo species
1,P68871,IS_QCMARKER_IN,BTO:0000131,Protein_QC_BioM,Tissue_Ontology,CKG,Spinorphin,blood plasma,Uniprot,BrendaTO,Generalised,Homo species
2,P00915,IS_QCMARKER_IN,BTO:0000131,Protein_QC_BioM,Tissue_Ontology,CKG,Carbonic anhydrase 1,blood plasma,Uniprot,BrendaTO,Generalised,Homo species
3,E5RHP7,IS_QCMARKER_IN,BTO:0000131,Protein_QC_BioM,Tissue_Ontology,CKG,E5RHP7,blood plasma,Uniprot,BrendaTO,Generalised,Homo species
4,E5RH81,IS_QCMARKER_IN,BTO:0000131,Protein_QC_BioM,Tissue_Ontology,CKG,E5RH81,blood plasma,Uniprot,BrendaTO,Generalised,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...
250,P04070,IS_QCMARKER_IN,BTO:0000131,Protein_QC_BioM,Tissue_Ontology,CKG,Activation peptide,blood plasma,Uniprot,BrendaTO,Generalised,Homo species
251,E7END6,IS_QCMARKER_IN,BTO:0000131,Protein_QC_BioM,Tissue_Ontology,CKG,E7END6,blood plasma,Uniprot,BrendaTO,Generalised,Homo species
252,P04070-2,IS_QCMARKER_IN,BTO:0000131,Protein_QC_BioM,Tissue_Ontology,CKG,P04070-2,blood plasma,Uniprot,BrendaTO,Generalised,Homo species
253,P02776,IS_QCMARKER_IN,BTO:0000131,Protein_QC_BioM,Tissue_Ontology,CKG,"Platelet factor 4, short form",blood plasma,Uniprot,BrendaTO,Generalised,Homo species
254,P10720,IS_QCMARKER_IN,BTO:0000131,Protein_QC_BioM,Tissue_Ontology,CKG,Platelet factor 4 variant(6-74),blood plasma,Uniprot,BrendaTO,Generalised,Homo species

In [27]:
ckg_2 = pd.read_csv(PROC_DIR + 'CKG/File_23_protein_tissue_CKG.csv')
ckg_2.rename(columns={'relation_source': 'kg_source', 'tail_name': 'head_detail_name'}, inplace=True)
ckg_2.columns = ckg_2.columns.str.lower()
print(f"ckg_2: {len(ckg_2):,} rows | columns: {list(ckg_2.columns)}")
ckg_2.rename(columns={'head_alt_name':'head_detail_name','tail_bto_name':'tail_detail_name'}, inplace=True, errors='ignore')
ckg_2['kg_type'] = 'Generalised'
ckg_2['kg_source'] = 'CKG'
ckg_2['species'] = 'Homo species'
ckg_2

ckg_2: 40,474,167 rows | columns: ['head', 'relation', 'tail', 'head_type', 'tail_type', 'source', 'kg_source', 'head_alt_name', 'tail_bto_name', 'head_id_is', 'tail_id_is', 'evidence_type', 'score']

,head,relation,tail,head_type,tail_type,source,kg_source,head_detail_name,tail_detail_name,head_id_is,tail_id_is,evidence_type,score,kg_type,species
0,Q96PA4,ASSOCIATED_WITH_INTEGRATED,BTO:0000138,Protein,Tissue,TISSUES,CKG,C-type lectin domain family 7 member A,midbrain,Uniprot_ID,brendaTissueid,compiled,1.145,Generalised,Homo species
1,O15267,ASSOCIATED_WITH_INTEGRATED,BTO:0001764,Protein,Tissue,TISSUES,CKG,Short stature homeobox protein,neural crest,Uniprot_ID,brendaTissueid,compiled,1.065,Generalised,Homo species
2,D3DNW1,ASSOCIATED_WITH_INTEGRATED,BTO:0005601,Protein,Tissue,TISSUES,CKG,Urotensin-2B,paracentral lobule,Uniprot_ID,brendaTissueid,compiled,0.517,Generalised,Homo species
3,Q5T4H6,ASSOCIATED_WITH_INTEGRATED,BTO:0001233,Protein,Tissue,TISSUES,CKG,Mucolipin-3 {ECO:0000303|PubMed:19497048},plant embryo,Uniprot_ID,brendaTissueid,compiled,0.821,Generalised,Homo species
4,Q96HE1,ASSOCIATED_WITH_INTEGRATED,BTO:0005198,Protein,Tissue,TISSUES,CKG,Neurogenin-1,adipose-derived stem cell,Uniprot_ID,brendaTissueid,compiled,0.973,Generalised,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40474162,Q53SJ1,ASSOCIATED_WITH_INTEGRATED,BTO:0005453,Protein,Tissue,TISSUES,CKG,Rho-related GTP-binding protein RhoQ,culture condition:CD4+ cell,Uniprot_ID,brendaTissueid,compiled,0.533,Generalised,Homo species
40474163,A8KAJ4,ASSOCIATED_WITH_INTEGRATED,BTO:0000956,Protein,Tissue,TISSUES,CKG,Interferon alpha/beta receptor 2,gut epithelium,Uniprot_ID,brendaTissueid,compiled,1.139,Generalised,Homo species
40474164,Q9HBU3,ASSOCIATED_WITH_INTEGRATED,BTO:0001491,Protein,Tissue,TISSUES,CKG,Myoferlin,viscus,Uniprot_ID,brendaTissueid,compiled,4.706,Generalised,Homo species
40474165,Q7L8L3,ASSOCIATED_WITH_INTEGRATED,BTO:0000675,Protein,Tissue,TISSUES,CKG,Ammonium transporter Rh type A {ECO:0000305},SW-620 cell,Uniprot_ID,brendaTissueid,compiled,1.158,Generalised,Homo species
40474166,Q9H9M8,ASSOCIATED_WITH_INTEGRATED,BTO:0000088,Protein,Tissue,TISSUES,CKG,MAP7 domain-containing protein 3,cardiovascular system,Uniprot_ID,brendaTissueid,compiled,2.025,Generalised,Homo species

## 2. Check and Fix Duplicate Columns

In [28]:
SOURCE_DFS = [('ageanno_mo', ageanno_mo), # aging
              ('ckg', ckg),
              ('ckg_2', ckg_2)
             ]

for name, df in SOURCE_DFS:
    dupes = df.columns[df.columns.duplicated(keep=False)].unique().tolist()
    print(f"[{name}] {'duplicate columns: ' + str(dupes) if dupes else '✓ no duplicates'}")

[ageanno_mo] ✓ no duplicates
[ckg] ✓ no duplicates
[ckg_2] ✓ no duplicates

## 3. Align Schemas and Concatenate

In [29]:
CONCAT_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name','kg_type', 'species'
]

df_list = []
for name, df in SOURCE_DFS:
    tmp = df.loc[:, ~df.columns.duplicated()].copy()
    for col in CONCAT_COLS:
        if col not in tmp.columns:
            tmp[col] = pd.NA
    df_list.append(tmp[CONCAT_COLS])

final_df = pd.concat(df_list, ignore_index=True)
print(f"Combined: {len(final_df):,} rows")
final_df.head(2)

Combined: 40,475,555 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,P01023,Gene_Tissue,BTO:0000131,Protein,NaN,Tissue,AgeAnnoMO,Uniprot,BTO_ID,Alpha-2-macroglobulin,blood plasma,Aging,Homo species
1,P42684,Gene_Tissue,BTO:0000131,Protein,NaN,Tissue,AgeAnnoMO,Uniprot,BTO_ID,Tyrosine-protein kinase ABL2,blood plasma,Aging,Homo species

In [30]:
final_df

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,P01023,Gene_Tissue,BTO:0000131,Protein,NaN,Tissue,AgeAnnoMO,Uniprot,BTO_ID,Alpha-2-macroglobulin,blood plasma,Aging,Homo species
1,P42684,Gene_Tissue,BTO:0000131,Protein,NaN,Tissue,AgeAnnoMO,Uniprot,BTO_ID,Tyrosine-protein kinase ABL2,blood plasma,Aging,Homo species
2,Q9BYF1,Gene_Tissue,BTO:0000131,Protein,NaN,Tissue,AgeAnnoMO,Uniprot,BTO_ID,Processed angiotensin-converting enzyme 2 {ECO...,blood plasma,Aging,Homo species
3,Q76LX8,Gene_Tissue,BTO:0000131,Protein,NaN,Tissue,AgeAnnoMO,Uniprot,BTO_ID,A disintegrin and metalloproteinase with throm...,blood plasma,Aging,Homo species
4,Q8TE58,Gene_Tissue,BTO:0000131,Protein,NaN,Tissue,AgeAnnoMO,Uniprot,BTO_ID,A disintegrin and metalloproteinase with throm...,blood plasma,Aging,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40475550,Q53SJ1,ASSOCIATED_WITH_INTEGRATED,BTO:0005453,Protein,NaN,Tissue,CKG,Uniprot_ID,brendaTissueid,Rho-related GTP-binding protein RhoQ,culture condition:CD4+ cell,Generalised,Homo species
40475551,A8KAJ4,ASSOCIATED_WITH_INTEGRATED,BTO:0000956,Protein,NaN,Tissue,CKG,Uniprot_ID,brendaTissueid,Interferon alpha/beta receptor 2,gut epithelium,Generalised,Homo species
40475552,Q9HBU3,ASSOCIATED_WITH_INTEGRATED,BTO:0001491,Protein,NaN,Tissue,CKG,Uniprot_ID,brendaTissueid,Myoferlin,viscus,Generalised,Homo species
40475553,Q7L8L3,ASSOCIATED_WITH_INTEGRATED,BTO:0000675,Protein,NaN,Tissue,CKG,Uniprot_ID,brendaTissueid,Ammonium transporter Rh type A {ECO:0000305},SW-620 cell,Generalised,Homo species
40475554,Q9H9M8,ASSOCIATED_WITH_INTEGRATED,BTO:0000088,Protein,NaN,Tissue,CKG,Uniprot_ID,brendaTissueid,MAP7 domain-containing protein 3,cardiovascular system,Generalised,Homo species

## 4. Standardise Fixed-Value Columns

In [31]:
final_df['head_type'] = 'Protein'
final_df['tail_type'] = 'Tissue'
final_df['relation']  = 'Protein_Tissue'
final_df['head_id_is']  = 'Uniprot_ID'
final_df['tail_id_is']  = 'BTO_ID'

print("Unique relation:",   set(final_df['relation']))
print("Unique head_id_is:", set(final_df['head_id_is']))
print("Unique tail_id_is:", set(final_df['tail_id_is']))
print("Unique kg_source:",  set(final_df['kg_source']))
print("Unique kg_source:",  set(final_df['kg_type']))

Unique relation: {'Protein_Tissue'}
Unique head_id_is: {'Uniprot_ID'}
Unique tail_id_is: {'BTO_ID'}
Unique kg_source: {'AgeAnnoMO', 'CKG'}
Unique kg_source: {'Generalised', 'Aging'}

In [32]:
final_df[final_df['head_detail_name'].isna()]

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
1133,P69905,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
1134,P68871,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
1135,P00915,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
1136,E5RHP7,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
1137,E5RH81,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40472910,H0Y6T8,Protein_Tissue,BTO:0000445,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,cerebral lobe,Generalised,Homo species
40473315,A0A0J9YYA3,Protein_Tissue,BTO:0000493,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,gall bladder,Generalised,Homo species
40473455,H0YCD9,Protein_Tissue,BTO:0001056,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,myeloid leukemia cell,Generalised,Homo species
40473463,M0QYT0,Protein_Tissue,BTO:0002502,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,kinetoplastid,Generalised,Homo species
40474899,Q5T8Z4,Protein_Tissue,BTO:0005655,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,Th17 cell,Generalised,Homo species

In [33]:
final_df[final_df['tail_detail_name'].isna()]

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
1133,P69905,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
1134,P68871,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
1135,P00915,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
1136,E5RHP7,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
1137,E5RH81,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1383,P04070,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
1384,E7END6,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
1385,P04070-2,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
1386,P02776,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species
1387,P10720,Protein_Tissue,BTO:0000131,Protein,NaN,Tissue,CKG,Uniprot_ID,BTO_ID,NaN,NaN,Generalised,Homo species

## 5. Deduplicate and Add Schema Columns

In [34]:
GROUP_COLS = ['head', 'relation', 'tail']

def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

final_df_dedup = final_df.groupby(GROUP_COLS, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':         merge_sources,
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'kg_type': merge_sources,
    'species': 'first',
})
print(f"After deduplication: {len(final_df_dedup):,} rows")
final_df_dedup = final_df_dedup[REQUIRED_COLS]
final_df_dedup.head()

After deduplication: 40,404,920 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,A0A024R072,Protein_Tissue,BTO:0000000,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,Cyclin-L2,"tissues, cell types and enzyme sources",Generalised,Homo species
1,A0A024R072,Protein_Tissue,BTO:0000003,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,Cyclin-L2,intestinal cell line,Generalised,Homo species
2,A0A024R072,Protein_Tissue,BTO:0000007,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,Cyclin-L2,HEK-293 cell,Generalised,Homo species
3,A0A024R072,Protein_Tissue,BTO:0000011,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,Cyclin-L2,3T3-L1 cell,Generalised,Homo species
4,A0A024R072,Protein_Tissue,BTO:0000016,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,Cyclin-L2,A-172 cell,Generalised,Homo species

## 6. QC — NaN Check

In [36]:
def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(final_df_dedup)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type      40404920                   0        40404920
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name      73907                   0           73907
tail_detail_name        170                   0             170
kg_type                   0                   0               0
species                   0                   0               0

In [42]:
final_df_dedup['head_detail_name'] = (
    final_df_dedup['head_detail_name']
    .fillna(
        final_df_dedup['head'].map(uniprot_trembl_AC_Name_dict)
        .fillna(
            final_df_dedup['head'].map(Uniprot_Recname_dict)
        )
    )
)

In [49]:
nan_summary(final_df_dedup)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type      40397385                   0        40397385
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

In [50]:
final_df_dedup = final_df_dedup[~final_df_dedup['tail_detail_name'].isna()]
final_df_dedup = final_df_dedup[~final_df_dedup['head_detail_name'].isna()]
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,A0A024R072,Protein_Tissue,BTO:0000000,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,Cyclin-L2,"tissues, cell types and enzyme sources",Generalised,Homo species
1,A0A024R072,Protein_Tissue,BTO:0000003,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,Cyclin-L2,intestinal cell line,Generalised,Homo species
2,A0A024R072,Protein_Tissue,BTO:0000007,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,Cyclin-L2,HEK-293 cell,Generalised,Homo species
3,A0A024R072,Protein_Tissue,BTO:0000011,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,Cyclin-L2,3T3-L1 cell,Generalised,Homo species
4,A0A024R072,Protein_Tissue,BTO:0000016,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,Cyclin-L2,A-172 cell,Generalised,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40404633,X6RBU3,Protein_Tissue,BTO:0005810,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,NELL2-interacting cell ontogeny regulator 1 {E...,immune system,Generalised,Homo species
40404634,X6RBU3,Protein_Tissue,BTO:0005813,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,NELL2-interacting cell ontogeny regulator 1 {E...,pancreatic islet cell,Generalised,Homo species
40404635,X6RBU3,Protein_Tissue,BTO:0006072,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,NELL2-interacting cell ontogeny regulator 1 {E...,tongue epithelial cell line,Generalised,Homo species
40404636,X6RBU3,Protein_Tissue,BTO:0006092,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,NELL2-interacting cell ontogeny regulator 1 {E...,hTERT-HPNE cell,Generalised,Homo species
40404637,X6RBU3,Protein_Tissue,BTO:0006191,Protein,None,Tissue,CKG,Uniprot_ID,BTO_ID,NELL2-interacting cell ontogeny regulator 1 {E...,cumulus-oocyte complex,Generalised,Homo species

## 7. Save Output

In [51]:
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
final_df_dedup.to_parquet(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 40,397,385 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/PROTEIN_TISSUE/ALL_PROTEIN_TISSUE.parquet

In [52]:
#