In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
# ── Base directories ──────────────────────────────────────────────────────────
BASE_DIR   = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR   = BASE_DIR + 'processed_data/'
DB_DIR     = BASE_DIR + 'data_collection/databases_for_mapping/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/CHEMICAL_NOEFFECT_BIOLOGICALPROCESS/ALL_CHEMICAL_NOEFFECT_BIOLOGICALPROCESS_Human.parquet'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

In [3]:
# AgeXtend
AgeXtend_Human_Chem_noeffect_BioPro_1 = pd.read_csv(PROC_DIR + 'agextend_processed/CHEM_BioP_Hallmarks/All_Chemical_Noeffect_BioPro(Hallmarks).csv')
AgeXtend_Human_Chem_noeffect_BioPro_1.columns = AgeXtend_Human_Chem_noeffect_BioPro_1.columns.str.lower()
AgeXtend_Human_Chem_noeffect_BioPro_1.rename(columns={'relation_source': 'kg_source'}, inplace=True)
AgeXtend_Human_Chem_noeffect_BioPro_1['kg_type'] = 'Aging'
AgeXtend_Human_Chem_noeffect_BioPro_1['kg_source'] = 'AgeXtend'
AgeXtend_Human_Chem_noeffect_BioPro_1['species'] = 'Homo sapiens'
AgeXtend_Human_Chem_noeffect_BioPro_1

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,tail_detail_name,kg_source,species,head_id_is,tail_id_is,source,kg_type
0,49778107,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,BiologicalProcess,3-[(4-acetamidophenyl)methyl-methylamino]-N-(3...,CC1=C(N2C=C(C=CC2=N1)C(=O)NCCCN3C=CN=C3)N(C)CC...,mitochondrial dysfunction,AgeXtend,Homo sapiens,Pubchem,Quick_GO,AID_624263_datatable_inactive,Aging
1,2530863,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,BiologicalProcess,2-(4-cyanophenoxy)-N-[3-(2-oxopyrrolidin-1-yl)...,C1CC(=O)N(C1)CCCNC(=O)COC2=CC=C(C=C2)C#N,mitochondrial dysfunction,AgeXtend,Homo sapiens,Pubchem,Quick_GO,AID_624263_datatable_inactive,Aging
2,4203055,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,BiologicalProcess,N-cyclohexyl-2-[[4-methyl-5-(trifluoromethyl)-...,CN1C(=NN=C1SCC(=O)NC2CCCCC2)C(F)(F)F,mitochondrial dysfunction,AgeXtend,Homo sapiens,Pubchem,Quick_GO,AID_624263_datatable_inactive,Aging
3,49778108,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,BiologicalProcess,5-[1-(4-phenylbutanoyl)piperidin-2-yl]-N-(pyri...,C1CCN(C(C1)C2=CC(=NO2)C(=O)NCC3=CN=CC=C3)C(=O)...,mitochondrial dysfunction,AgeXtend,Homo sapiens,Pubchem,Quick_GO,AID_624263_datatable_inactive,Aging
4,49778109,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,BiologicalProcess,"[(2S,6R)-4-benzyl-6-(6-pyrrolidin-1-ylpurin-9-...",CC(=O)OC[C@@H]1CN(C[C@@H](O1)N2C=NC3=C2N=CN=C3...,mitochondrial dysfunction,AgeXtend,Homo sapiens,Pubchem,Quick_GO,AID_624263_datatable_inactive,Aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
642373,71717698,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111118,ChemicalEntity,BiologicalProcess,"methyl (4R,5R)-5-[(1S,9R,10R)-3-hydroxy-4,12-d...",CN1CC[C@]23CC(=O)C(=C[C@H]2[C@H]1CC4=C3C(=C(C=...,altered intercellular communication,AgeXtend,Homo sapiens,Pubchem,Quick_GO,AID_736485_datatable_inactive,Aging
642374,71719512,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111118,ChemicalEntity,BiologicalProcess,"methyl (4R,5R)-3-(4-bromophenyl)-5-[(1S,9R,10R...",CN1CC[C@]23CC(=O)C(=C[C@H]2[C@H]1CC4=C3C(=C(C=...,altered intercellular communication,AgeXtend,Homo sapiens,Pubchem,Quick_GO,AID_736485_datatable_inactive,Aging
642375,71720111,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111118,ChemicalEntity,BiologicalProcess,"methyl (4R,5R)-3-(3-chlorophenyl)-5-[(1S,9R,10...",CN1CC[C@]23CC(=O)C(=C[C@H]2[C@H]1CC4=C3C(=C(C=...,altered intercellular communication,AgeXtend,Homo sapiens,Pubchem,Quick_GO,AID_736485_datatable_inactive,Aging
642376,71720112,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111118,ChemicalEntity,BiologicalProcess,"methyl (4R,5R)-5-[(1S,9R,10R)-3-hydroxy-4,12-d...",CN1CC[C@]23CC(=O)C(=C[C@H]2[C@H]1CC4=C3C(=C(C=...,altered intercellular communication,AgeXtend,Homo sapiens,Pubchem,Quick_GO,AID_736485_datatable_inactive,Aging
642377,71720769,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111118,ChemicalEntity,BiologicalProcess,"methyl (4R,5R)-3-(4-chlorophenyl)-5-[(1S,9R,10...",CN1CC[C@]23CC(=O)C(=C[C@H]2[C@H]1CC4=C3C(=C(C=...,altered intercellular communication,AgeXtend,Homo sapiens,Pubchem,Quick_GO,AID_736485_datatable_inactive,Aging

In [4]:
SOURCE_DFS = [
    ('AgeXtend_Human_Chem_noeffect_BioPro_1', AgeXtend_Human_Chem_noeffect_BioPro_1),
]

for name, df in SOURCE_DFS:
    dupes = df.columns[df.columns.duplicated(keep=False)].unique().tolist()
    if dupes:
        print(f'\n[{name}] duplicate columns: {dupes}')
        for col in dupes:
            for i, (_, s) in enumerate(df.loc[:, df.columns == col].items()):
                print(f"  '{col}' occurrence {i} → sample: {s.dropna().head(3).tolist()}")
    else:
        print(f'[{name}] ✓ no duplicates')

[AgeXtend_Human_Chem_noeffect_BioPro_1] ✓ no duplicates

In [5]:
CONCAT_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

df_list = []
for name, df in SOURCE_DFS:
    tmp = df.loc[:, ~df.columns.duplicated()].copy()
    for col in CONCAT_COLS:
        if col not in tmp.columns:
            tmp[col] = pd.NA
    df_list.append(tmp[CONCAT_COLS])

final_df = pd.concat(df_list, ignore_index=True)
print(f'Combined: {len(final_df):,} rows')
final_df

Combined: 642,378 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,49778107,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,3-[(4-acetamidophenyl)methyl-methylamino]-N-(3...,mitochondrial dysfunction,Aging,Homo sapiens
1,2530863,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,2-(4-cyanophenoxy)-N-[3-(2-oxopyrrolidin-1-yl)...,mitochondrial dysfunction,Aging,Homo sapiens
2,4203055,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,N-cyclohexyl-2-[[4-methyl-5-(trifluoromethyl)-...,mitochondrial dysfunction,Aging,Homo sapiens
3,49778108,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,5-[1-(4-phenylbutanoyl)piperidin-2-yl]-N-(pyri...,mitochondrial dysfunction,Aging,Homo sapiens
4,49778109,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"[(2S,6R)-4-benzyl-6-(6-pyrrolidin-1-ylpurin-9-...",mitochondrial dysfunction,Aging,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
642373,71717698,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111118,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"methyl (4R,5R)-5-[(1S,9R,10R)-3-hydroxy-4,12-d...",altered intercellular communication,Aging,Homo sapiens
642374,71719512,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111118,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"methyl (4R,5R)-3-(4-bromophenyl)-5-[(1S,9R,10R...",altered intercellular communication,Aging,Homo sapiens
642375,71720111,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111118,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"methyl (4R,5R)-3-(3-chlorophenyl)-5-[(1S,9R,10...",altered intercellular communication,Aging,Homo sapiens
642376,71720112,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111118,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"methyl (4R,5R)-5-[(1S,9R,10R)-3-hydroxy-4,12-d...",altered intercellular communication,Aging,Homo sapiens
642377,71720769,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111118,ChemicalEntity,<NA>,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"methyl (4R,5R)-3-(4-chlorophenyl)-5-[(1S,9R,10...",altered intercellular communication,Aging,Homo sapiens

In [6]:
GROUP_COLS = ['head', 'relation', 'tail']

def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

final_df_dedup = final_df.groupby(GROUP_COLS, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':         merge_sources,
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'kg_type': merge_sources,
    'species': 'first',
})
print(f'After deduplication: {len(final_df_dedup):,} rows')
final_df_dedup = final_df_dedup[REQUIRED_COLS]
final_df_dedup.head()

After deduplication: 642,378 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,4,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111114,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,1-aminopropan-2-ol,loss of proteostasis,Aging,Homo sapiens
1,6,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"1-chloro-2,4-dinitrobenzene",mitochondrial dysfunction,Aging,Homo sapiens
2,11,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111114,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"1,2-dichloroethane",loss of proteostasis,Aging,Homo sapiens
3,13,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"1,2,4-trichlorobenzene",genomic instability,Aging,Homo sapiens
4,13,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111114,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"1,2,4-trichlorobenzene",loss of proteostasis,Aging,Homo sapiens

In [7]:
def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(final_df_dedup)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type        642378                   0          642378
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name        132                   0             132
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

In [9]:
final_df_dedup['head_species'] = 'Homo sapiens'
final_df_dedup['head_species'] = 'Homo sapiens'
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species,head_species
0,4,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111114,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,1-aminopropan-2-ol,loss of proteostasis,Aging,Homo sapiens,Homo sapiens
1,6,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"1-chloro-2,4-dinitrobenzene",mitochondrial dysfunction,Aging,Homo sapiens,Homo sapiens
2,11,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111114,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"1,2-dichloroethane",loss of proteostasis,Aging,Homo sapiens,Homo sapiens
3,13,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"1,2,4-trichlorobenzene",genomic instability,Aging,Homo sapiens,Homo sapiens
4,13,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111114,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"1,2,4-trichlorobenzene",loss of proteostasis,Aging,Homo sapiens,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
642373,136153828,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"3-[1-(2,6-dimethylphenyl)tetrazol-5-yl]-1H-ben...",mitochondrial dysfunction,Aging,Homo sapiens,Homo sapiens
642374,136181841,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111116,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"6,6-dimethyl-3-[4-(trifluoromethyl)phenyl]-4H-...",mitochondrial dysfunction,Aging,Homo sapiens,Homo sapiens
642375,136185788,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111112,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"N-(1,3-benzodioxol-5-yl)-2-[4-hydroxy-5-[(E)-i...",telomere attrition,Aging,Homo sapiens,Homo sapiens
642376,136187687,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111112,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,2-[4-hydroxy-5-[(Z)-(2-oxoquinolin-3-ylidene)m...,telomere attrition,Aging,Homo sapiens,Homo sapiens
642377,139971569,ChemicalEntity_NoEffect_BiologicalProcess,GO:1111111,ChemicalEntity,None,BiologicalProcess,AgeXtend,Pubchem,Quick_GO,"1-hydroxy-2-methyl-N,2-diphenylindol-3-imine",genomic instability,Aging,Homo sapiens,Homo sapiens

In [10]:
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
final_df_dedup.to_parquet(OUT_PATH, index=False)
print(f'Saved {len(final_df_dedup):,} rows → {OUT_PATH}')

Saved 642,378 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/CHEMICAL_NOEFFECT_BIOLOGICALPROCESS/ALL_CHEMICAL_NOEFFECT_BIOLOGICALPROCESS_Human.parquet