In [1]:
import pandas as pd
import os

In [2]:
# ── Base directories ──────────────────────────────────────────────────────────
BASE_DIR   = '/storage/Arushi/090526_EvoAge/kg_formation/'
PROC_DIR   = BASE_DIR + 'processed_data/'
DB_DIR     = BASE_DIR + 'data_collection/databases_for_mapping/'

# ── Output path ───────────────────────────────────────────────────────────────
OUT_PATH   = BASE_DIR + 'processed_data_relation_wise_merge/generalised/GENE_PROMOTES_BIOLOGICALPROCESS/ALL_GENE_PROMOTES_BIOLOGICALPROCESS.parquet'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'kg_type', 'species'
]

# cellage

In [3]:
# CellAge
CellAge_Human_Gene_Promotes_BioPro_1 = pd.read_csv(PROC_DIR + 'cellage/CellAge_Gene_Promotes_BioPro_human.csv')
CellAge_Human_Gene_Promotes_BioPro_1.columns = CellAge_Human_Gene_Promotes_BioPro_1.columns.str.lower()
CellAge_Human_Gene_Promotes_BioPro_1.rename(columns={'Relation_Source': 'kg_source'}, inplace=True)
CellAge_Human_Gene_Promotes_BioPro_1['kg_type'] = 'Aging'
CellAge_Human_Gene_Promotes_BioPro_1['kg_source'] = 'CellAge'
CellAge_Human_Gene_Promotes_BioPro_1['species'] = 'Homo species'
CellAge_Human_Gene_Promotes_BioPro_1

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,relation_source,species,head_id_is,tail_id_is,data_type,cancer cell,kg_type,kg_source
0,AAK1,Gene_Promotes_BiologicalProcess,GO:0090398,Gene,BiologicalProcess,AP2 associated kinase 1,cellular senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,No,Aging,CellAge
1,ABCB1,Gene_Promotes_BiologicalProcess,GO:0090400,Gene,BiologicalProcess,ATP binding cassette subfamily B member 1,stress-induced premature senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,Yes,Aging,CellAge
2,ABI3,Gene_Promotes_BiologicalProcess,GO:0090402,Gene,BiologicalProcess,ABI family member 3,oncogene-induced cell senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,Yes,Aging,CellAge
3,ABI3BP,Gene_Promotes_BiologicalProcess,GO:0090398,Gene,BiologicalProcess,ABI family member 3 binding protein,cellular senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,Yes,Aging,CellAge
4,ACKR1,Gene_Promotes_BiologicalProcess,GO:0090400,Gene,BiologicalProcess,atypical chemokine receptor 1 (Duffy blood group),stress-induced premature senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,No,Aging,CellAge
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,XAF1,Gene_Promotes_BiologicalProcess,GO:0090400,Gene,BiologicalProcess,XIAP associated factor 1,stress-induced premature senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,No,Aging,CellAge
412,XPO1,Gene_Promotes_BiologicalProcess,GO:0090398,Gene,BiologicalProcess,exportin 1,cellular senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,No,Aging,CellAge
413,YPEL3,Gene_Promotes_BiologicalProcess,GO:0090400,Gene,BiologicalProcess,yippee like 3,stress-induced premature senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,Yes,Aging,CellAge
414,ZCCHC10,Gene_Promotes_BiologicalProcess,GO:0090399,Gene,BiologicalProcess,zinc finger CCHC-type containing 10,replicative senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,Yes,Aging,CellAge
415,ZFP36,Gene_Promotes_BiologicalProcess,GO:0090398,Gene,BiologicalProcess,ZFP36 ring finger protein,cellular senescence,CellAge,Homo species,NCBI_ID,Quick_GO,Causitive,Yes,Aging,CellAge

### Agingbank

In [4]:

agingbank_gene_promotes_BiologicalProcess = pd.read_csv(PROC_DIR + 'agingbank/Human_AgingbankGene_promotes_BioPro.csv')
agingbank_gene_promotes_BiologicalProcess.columns = agingbank_gene_promotes_BiologicalProcess.columns.str.lower()
agingbank_gene_promotes_BiologicalProcess.rename(columns={'Relation_Source': 'kg_source'}, inplace=True)
agingbank_gene_promotes_BiologicalProcess['kg_type'] = 'Aging'
agingbank_gene_promotes_BiologicalProcess['kg_source'] = 'AgingBank'
agingbank_gene_promotes_BiologicalProcess['relation'] = 'Gene_Promotes_BiologicalProcess'

agingbank_gene_promotes_BiologicalProcess['species'] = 'Homo species'
agingbank_gene_promotes_BiologicalProcess

,head,relation,tail,head_type,tail_type,kg_source,kg_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_type.1,species
0,SRSF3,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,serine and arginine rich splicing factor 3,aging,NCBI_ID,Quick_GO,Aging,Homo species
1,GH1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,growth hormone 1,aging,NCBI_ID,Quick_GO,Aging,Homo species
2,WRN,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,WRN RecQ like helicase,aging,NCBI_ID,Quick_GO,Aging,Homo species
3,MEF2A,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,myocyte enhancer factor 2A,aging,NCBI_ID,Quick_GO,Aging,Homo species
4,p16,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,H3 histone pseudogene 10,aging,NCBI_ID,Quick_GO,Aging,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,SRSF3,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,serine and arginine rich splicing factor 3,aging,NCBI_ID,Quick_GO,Aging,Homo species
318,STAT,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,sterol O-acyltransferase 1,aging,NCBI_ID,Quick_GO,Aging,Homo species
319,STAT1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,signal transducer and activator of transcripti...,aging,NCBI_ID,Quick_GO,Aging,Homo species
320,TBX2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,T-box transcription factor 2,aging,NCBI_ID,Quick_GO,Aging,Homo species
321,WT1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,WT1 transcription factor,aging,NCBI_ID,Quick_GO,Aging,Homo species

In [5]:

agingbank_2_gene_promotes_BiologicalProcess = pd.read_csv(PROC_DIR + 'agingbank/Human_AgingbankGene_promotes_BioPro_file2.csv')
agingbank_2_gene_promotes_BiologicalProcess.columns = agingbank_2_gene_promotes_BiologicalProcess.columns.str.lower()
agingbank_2_gene_promotes_BiologicalProcess.rename(columns={'Relation_Source': 'kg_source'}, inplace=True)
agingbank_2_gene_promotes_BiologicalProcess['kg_type'] = 'Aging'
agingbank_2_gene_promotes_BiologicalProcess['kg_source'] = 'AgingBank'
agingbank_2_gene_promotes_BiologicalProcess['relation'] = 'Gene_Promotes_BiologicalProcess'

agingbank_2_gene_promotes_BiologicalProcess['species'] = 'Homo species'
agingbank_2_gene_promotes_BiologicalProcess

,head,relation,tail,head_type,tail_type,kg_source,kg_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_type.1,species
0,SRSF3,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,serine and arginine rich splicing factor 3,aging,NCBI_ID,Quick_GO,Aging,Homo species
1,MEF2A,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,myocyte enhancer factor 2A,aging,NCBI_ID,Quick_GO,Aging,Homo species
2,p21,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,H3 histone pseudogene 16,aging,NCBI_ID,Quick_GO,Aging,Homo species
3,SOD2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,superoxide dismutase 2,aging,NCBI_ID,Quick_GO,Aging,Homo species
4,DEC1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,deleted in esophageal cancer 1,aging,NCBI_ID,Quick_GO,Aging,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,LMNA,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,lamin A/C,aging,NCBI_ID,Quick_GO,Aging,Homo species
181,OCTN2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,solute carrier family 22 member 5,aging,NCBI_ID,Quick_GO,Aging,Homo species
182,ELOVL2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,ELOVL fatty acid elongase 2,aging,NCBI_ID,Quick_GO,Aging,Homo species
183,p65,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,WNK lysine deficient protein kinase 1,aging,NCBI_ID,Quick_GO,Aging,Homo species
184,LMNA,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,lamin A/C,aging,NCBI_ID,Quick_GO,Aging,Homo species

In [6]:
SOURCE_DFS = [
    ('CellAge_Human_Gene_Promotes_BioPro_1',    CellAge_Human_Gene_Promotes_BioPro_1),
    ('agingbank_gene_promotes_BiologicalProcess',    agingbank_gene_promotes_BiologicalProcess),
    ('agingbank_2_gene_promotes_BiologicalProcess',    agingbank_2_gene_promotes_BiologicalProcess),
    
]

for name, df in SOURCE_DFS:
    dupes = df.columns[df.columns.duplicated(keep=False)].unique().tolist()
    if dupes:
        print(f"\n[{name}] duplicate columns: {dupes}")
        for col in dupes:
            for i, (_, s) in enumerate(df.loc[:, df.columns == col].items()):
                print(f"  '{col}' occurrence {i} → sample: {s.dropna().head(3).tolist()}")
    else:
        print(f"[{name}] ✓ no duplicates")

[CellAge_Human_Gene_Promotes_BioPro_1] ✓ no duplicates
[agingbank_gene_promotes_BiologicalProcess] ✓ no duplicates
[agingbank_2_gene_promotes_BiologicalProcess] ✓ no duplicates

In [7]:
CONCAT_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name','kg_type', 'species'
]

df_list = []
for name, df in SOURCE_DFS:
    tmp = df.loc[:, ~df.columns.duplicated()].copy()
    for col in CONCAT_COLS:
        if col not in tmp.columns:
            tmp[col] = pd.NA
    df_list.append(tmp[CONCAT_COLS])

final_df = pd.concat(df_list, ignore_index=True)
print(f"Combined: {len(final_df):,} rows")
final_df

Combined: 923 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,AAK1,Gene_Promotes_BiologicalProcess,GO:0090398,Gene,NaN,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,AP2 associated kinase 1,cellular senescence,Aging,Homo species
1,ABCB1,Gene_Promotes_BiologicalProcess,GO:0090400,Gene,NaN,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,ATP binding cassette subfamily B member 1,stress-induced premature senescence,Aging,Homo species
2,ABI3,Gene_Promotes_BiologicalProcess,GO:0090402,Gene,NaN,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,ABI family member 3,oncogene-induced cell senescence,Aging,Homo species
3,ABI3BP,Gene_Promotes_BiologicalProcess,GO:0090398,Gene,NaN,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,ABI family member 3 binding protein,cellular senescence,Aging,Homo species
4,ACKR1,Gene_Promotes_BiologicalProcess,GO:0090400,Gene,NaN,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,atypical chemokine receptor 1 (Duffy blood group),stress-induced premature senescence,Aging,Homo species
...,...,...,...,...,...,...,...,...,...,...,...,...,...
918,LMNA,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,NaN,BiologicalProcess,AgingBank,NCBI_ID,Quick_GO,lamin A/C,aging,Aging,Homo species
919,OCTN2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,NaN,BiologicalProcess,AgingBank,NCBI_ID,Quick_GO,solute carrier family 22 member 5,aging,Aging,Homo species
920,ELOVL2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,NaN,BiologicalProcess,AgingBank,NCBI_ID,Quick_GO,ELOVL fatty acid elongase 2,aging,Aging,Homo species
921,p65,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,NaN,BiologicalProcess,AgingBank,NCBI_ID,Quick_GO,WNK lysine deficient protein kinase 1,aging,Aging,Homo species
922,LMNA,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,NaN,BiologicalProcess,AgingBank,NCBI_ID,Quick_GO,lamin A/C,aging,Aging,Homo species

In [8]:
GROUP_COLS = ['head', 'relation', 'tail']

def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

final_df_dedup = final_df.groupby(GROUP_COLS, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':         merge_sources,
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'kg_type': merge_sources,
    'species': 'first',
})
print(f"After deduplication: {len(final_df_dedup):,} rows")
final_df_dedup = final_df_dedup[REQUIRED_COLS]
final_df_dedup.head()

After deduplication: 636 rows

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,kg_type,species
0,AAK1,Gene_Promotes_BiologicalProcess,GO:0090398,Gene,None,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,AP2 associated kinase 1,cellular senescence,Aging,Homo species
1,ABCB1,Gene_Promotes_BiologicalProcess,GO:0090400,Gene,None,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,ATP binding cassette subfamily B member 1,stress-induced premature senescence,Aging,Homo species
2,ABI3,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,NCBI_ID,Quick_GO,ABI family member 3,aging,Aging,Homo species
3,ABI3,Gene_Promotes_BiologicalProcess,GO:0090402,Gene,None,BiologicalProcess,CellAge,NCBI_ID,Quick_GO,ABI family member 3,oncogene-induced cell senescence,Aging,Homo species
4,ABI3BP,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,NCBI_ID,Quick_GO,ABI family member 3 binding protein,aging,Aging,Homo species

In [9]:
def nan_summary(df):
    true_nan   = df.isna().sum()
    string_nan = df.apply(lambda c: c.astype(str).str.upper().eq('NAN').sum())
    return pd.DataFrame({
        'NaN_count':          true_nan,
        "'NAN'_string_count": string_nan,
        'Total_NaN_like':     true_nan + string_nan
    })

nan_summary(final_df_dedup)

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           636                   0             636
tail_type                 0                   0               0
kg_source                 0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
kg_type                   0                   0               0
species                   0                   0               0

In [10]:
os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
final_df_dedup.to_parquet(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 636 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/GENE_PROMOTES_BIOLOGICALPROCESS/ALL_GENE_PROMOTES_BIOLOGICALPROCESS.parquet