# C. elegans Gene–Gene — Relation-Wise KG Triple Construction

## Purpose

This notebook processes Gene–Gene interaction data for *C. elegans* from **two sources** and combines them into standardized relation-wise Knowledge Graph (KG) triples:
1. **STRING** — Protein–protein interactions (mapped to genes via LocusTag)

## Pipeline Overview

| Step | Section | Description |
|------|---------|-------------|
| 1 | NCBI Gene Info | Load NCBI annotations, build LocusTag → Description dictionary |
| 2 | STRING Source | Load raw STRING file, clean protein IDs, map descriptions |
| 3 | WID/FICE Source | Load pre-processed pickle, add metadata, map descriptions |
| 4 | Combine Sources | Merge both into unified DataFrame with required columns |
| 5 | Validate, Deduplicate & Export | Quality check, deduplicate, export |

## Final Output Schema

| Column | Description |
|--------|-------------|
| `head` | Gene LocusTag |
| `relation` | `Gene_Gene` |
| `tail` | Gene LocusTag |
| `head_type` | `Gene` |
| `relation_type` | (NaN) |
| `tail_type` | `Gene` |
| `kg_source` | `STRING`, `FICE`, or `Worm_Interactome_Database` (merged with `::` on dedup) |
| `head_id_is` | `NCBI_ID` |
| `tail_id_is` | `NCBI_ID` |
| `head_detail_name` | Gene description from NCBI |
| `tail_detail_name` | Gene description from NCBI |
| `species` | `C.elegans` |

## Data Download Instructions

All databases used in this notebook must be downloaded prior to execution.
Please refer to the **central download instructions document** for detailed steps:

📄 **[Download Instructions — Link to be added]**

### Required Files

| File | Source | Description |
|------|--------|-------------|
| `6239.protein.links.detailed.v12.0.txt` | STRING | Raw protein–protein interaction file for C. elegans (tax_id: 6239) |
| `C_ELE_GENE_GENE_WithSEQ.pkl` | WID + FICE (pre-processed) | Gene–gene functional associations with sequences |
| `Caenorhabditis_elegans.gene_info` | NCBI Gene | Gene annotations for C. elegans |

---
## Setup

Import required libraries and define all base paths.

In [12]:
import pandas as pd
import numpy as np

In [13]:
# =============================================================================
# BASE PATHS — Update these to match your local directory structure
# =============================================================================
your_path_here = '/storage/Arushi/090526_EvoAge/kg_formation/data_collection/'

# NCBI gene info for C. elegans
NCBI_GENE_INFO_PATH = f'{your_path_here}databases_for_mapping/ncbi/Caenorhabditis_elegans.gene_info'

# Raw STRING protein-protein interaction file for C. elegans
STRING_RAW_PATH = f'{your_path_here}string/celegans/6239.protein.links.detailed.v12.0.txt'

# Pre-processed WID/FICE gene-gene pickle
# WID_FICE_PICKLE_PATH = '{your_path_here}/string/GENE_GENE/C_ELE_GENE_GENE_WithSEQ.pkl'

# Final output path
OUTPUT_PATH = '/storage/Arushi/090526_EvoAge/kg_formation/processed_data/string/celegans/string_CELE_GENE_GENE.csv'

---
## 1. NCBI Gene Info — Build LocusTag → Description Dictionary

Load NCBI gene annotations for *C. elegans*. Strip the `CELE_` prefix from LocusTags. In C. elegans, both STRING protein IDs and WID/FICE gene IDs correspond to LocusTags after cleaning.

In [14]:
# =============================================================================
# Load NCBI gene info and build dictionaries
# =============================================================================

ncbi_cele_gene = pd.read_csv(NCBI_GENE_INFO_PATH, sep='\t')

# Strip 'CELE_' prefix from LocusTag
ncbi_cele_gene['LocusTag'] = ncbi_cele_gene['LocusTag'].str.replace('CELE_', '', regex=False)

# Dictionary: LocusTag → Description (used for head/tail_detail_name)
ncbi_locustag_to_description = dict(zip(ncbi_cele_gene['LocusTag'], ncbi_cele_gene['description']))

print(f"NCBI genes loaded: {len(ncbi_cele_gene):,}")
print(f"LocusTag → Description dictionary size: {len(ncbi_locustag_to_description):,}")

NCBI genes loaded: 46,927
LocusTag → Description dictionary size: 46,927

In [15]:
ncbi_locustag_to_description

{'Y74C9A.3': 'Alpha N-terminal protein methyltransferase 1',
 'Y74C9A.2': 'Peptide P4',
 'Y74C9A.4': 'REST corepressor rcor-1',
 'Y74C9A.5': 'Sestrin homolog',
 'Y48G1C.4': 'CDP-diacylglycerol--glycerol-3-phosphate 3-phosphatidyltransferase',
 'Y48G1C.5': 'Tyrosine-protein phosphatase domain-containing protein',
 'Y48G1C.6': 'HTH CENPB-type domain-containing protein',
 'Y48G1C.1': 'Protein pid-2',
 'F53G12.1': 'Ras-related protein rab-11.1',
 'F53G12.10': 'Large ribosomal subunit protein uL30',
 'F53G12.9': 'GST_C_6 domain-containing protein;Metaxin glutathione S-transferase domain-containing protein',
 'F53G12.8': 'Uncharacterized protein',
 'F53G12.7': 'Collagen triple helix repeat protein;Nematode cuticle collagen N-terminal domain-containing protein',
 'F53G12.6': 'Spermatocyte protein spe-8',
 'F53G12.5': 'Growth-regulating factor;K Homology domain-containing protein',
 'F56C11.1': 'Dual oxidase 1',
 'F56C11.2': 'SSD domain-containing protein',
 'F56C11.6': 'Carboxylic ester hydrolase',
 'F56C11.3': 'Sulfhydryl oxidase',
 'Y48G1BL.3': 'pseudo',
 'Y48G1BM.1': 'snRNA-activating protein complex subunit 3',
 'C53D5.2': 'RING-CH-type domain-containing protein',
 'C53D5.4': 'C2H2-type domain-containing protein',
 'C53D5.1': 'FAM69 protein-kinase domain-containing protein',
 'C53D5.5': 'Gamma-glutamyltranspeptidase 1',
 'Y48G1A.5': 'Exportin-2;Exportin-2 C-terminal domain-containing protein',
 'Y48G1A.4': 'Nucleolar protein 14',
 'Y48G1A.3': 'Dauer abnormal formation protein 25',
 'Y48G1A.6': 'Malignant brain tumor repeat protein 1',
 'Y48G1A.2': 'Transposase',
 'R119.1': 'pseudo',
 'R119.7': 'RRM domain-containing protein',
 'R119.3': 'DeHydrogenases, Short chain',
 'R119.6': 'Transcription initiation factor TFIID subunit 4',
 'R119.5': 'Protein-L-isoaspartate O-methyltransferase domain-containing protein 1',
 'Y50C1A.1': 'ubiquitinyl hydrolase 1',
 'C07F11.2': 'BTB domain-containing protein',
 'C07F11.1': 'TIR domain-containing protein',
 'W04C9.4': 'Uncharacterized protein',
 'W04C9.3': 'ZP domain-containing protein',
 'W04C9.2': 'MICOS complex subunit MIC13',
 'W04C9.1': 'ABC-type antigen peptide transporter',
 'Y65B4BL.3': 'Transmembrane protein',
 'Y65B4BL.4': 'Dolichyl-phosphate-mannose--protein mannosyltransferase',
 'Y65B4BL.2': 'P-granule-associated protein deps-1',
 'Y65B4BL.5': 'Long-chain-fatty-acid--CoA ligase',
 'Y65B4BL.1': 'Uncharacterized protein',
 'Y65B4BR.8': 'DNA replication complex GINS protein PSF3',
 'Y65B4BR.5': 'Nascent polypeptide-associated complex subunit alpha',
 'Y65B4BR.4': 'E3 ubiquitin-protein ligase wwp-1',
 'Y65B4BR.2': 'LiPocalin-Related protein;Lipocln_cytosolic_FA-bd_dom domain-containing protein',
 'Y65B4BR.6': 'Ground-like domain-containing protein',
 'F56A6.2': 'Unconventional myosin-IXa-like',
 'F56A6.4': 'Crossover junction endonuclease MUS81;ERCC4 domain-containing protein',
 'F56A6.1': 'Piwi domain-containing protein',
 'Y65B4A.3': 'Charged multivesicular body protein 6',
 'Y65B4A.2': 'Peptidase C1A papain C-terminal domain-containing protein',
 'Y65B4A.1': 'RRM domain-containing protein',
 'Y65B4A.8': 'Cytidyltransferase-like domain-containing protein',
 'Y65B4A.9': 'Protein kinase domain-containing protein',
 'Y18H1A.10': 'non-specific serine/threonine protein kinase',
 'Y18H1A.1': 'Tyrosine-protein phosphatase domain-containing protein',
 'Y18H1A.4': 'Histidine phosphatase family protein',
 'Y18H1A.2': 'CBF1-interacting co-repressor CIR N-terminal domain-containing protein;Cir_N domain-containing protein',
 'Y18H1A.3': 'Rap-GAP domain-containing protein',
 'Y18H1A.7': 'Uncharacterized protein',
 'Y18H1A.6': 'ATP-dependent DNA helicase;ATP-dependent DNA helicase PIF1',
 'Y18H1A.9': 'ShKT domain-containing protein',
 'Y18H1A.8': 'Apyrase;TransThyretin-Related family domain',
 'T06A4.3': 'Peptidase M14 carboxypeptidase A domain-containing protein;ShKT domain-containing protein',
 'T06A4.1': 'Peptidase M14 carboxypeptidase A domain-containing protein',
 'ZC123.3': 'Zinc Finger and Homeobox;Zinc finger homeobox protein 4;Zinc finger protein',
 'ZC123.1': 'Sperm mitochondrial-associated cysteine-rich protein-like',
 'ZC123.4': 'Protein kinase domain-containing protein',
 'Y95B8A.6': 'Bursicon;Bursicon subunit alpha;Secreted protein',
 'Y95B8A.5': 'Guanine nucleotide-binding protein alpha-16 subunit',
 'Y34D9B.1': 'Frizzled-4',
 'F54A5.2': 'ZP domain-containing protein',
 'F54A5.1': 'Homeobox-containing protein 1',
 'C54G6.1': 'MADF domain-containing protein',
 'C54G6.5': 'Saposin B-type domain-containing protein',
 'Y34D9A.1': 'Large ribosomal subunit protein mL38',
 'Y34D9A.4': 'Protein regulator of cytokinesis 1',
 'Y34D9A.3': 'MIF4G domain-containing protein;THO complex subunit 2;TPR_REGION domain-containing protein;Uncharacterized protein',
 'Y34D9A.6': 'Glutaredoxin-1',
 'R06A10.2': 'Guanine nucleotide-binding protein G(s) subunit alpha',
 'R06A10.4': 'Protein kinase domain-containing protein',
 'ZK993.1': 'Homeobox domain-containing protein',
 'Y48G8AL.14': 'AP complex mu/sigma subunit domain-containing protein',
 'Y48G8AL.8': 'Large ribosomal subunit protein uL22',
 'Y48G8AL.7': 'Origin recognition complex subunit 6',
 'Y48G8AL.11': 'ABC transporter ATP-binding protein;ATP-binding cassette sub-family B member 8, mitochondrial',
 'Y48G8AL.6': 'Regulator of nonsense transcripts 1',
 'Y48G8AL.5': 'Doublecortin domain-containing protein;SAM-dependent MTase RsmB/NOP-type domain-containing protein;tRNA (cytosine(34)-C(5))-methyltransferase',
 'Y48G8AL.12': 'Uncharacterized protein',
 'Y48G8AL.13': 'TLC domain-containing protein',
 'Y48G8AL.1': 'HECT domain-containing protein',
 'Y48G8AR.2': 'FYVE-type domain-containing protein',
 'K12C11.1': 'Peptidase M24 domain-containing protein;Xaa-Pro dipeptidase',
 'Y92H12BR.6': 'SET domain-containing protein',
 'Y92H12BR.2': 'Chromatin target of PRMT1 protein C-terminal domain-containing protein',
 'Y92H12BR.3': 'Uncharacterized protein',
 'Y92H12BR.4': 'pseudo',
 'Y92H12BR.8': 'Large ribosomal subunit protein uL15m',
 'F37F2.2': 'putative signal recognition particle 19 kDa protein',
 'F47G6.4': 'Myosin VI cargo binding domain-containing protein;Myosin motor domain-containing protein',
 'F47G6.3': 'LEM domain-containing protein',
 'F47G6.2': 'AMP-dependent synthetase/ligase domain-containing protein',
 'F47G6.1': 'Dystrobrevin-1',
 'Y92H12A.5': "tRNA (32-2'-O)-methyltransferase regulator THADA",
 'Y92H12A.2': 'E3 ubiquitin-protein ligase;HECT-type E3 ubiquitin transferase',
 'Y92H12A.T1': 'tRNA-Arg',
 'Y92H12A.1': 'Tyrosine protein-kinase src-1',
 'Y73E7A.2': 'Protein BFR2',
 'Y73E7A.6': 'Bladder cancer-associated protein',
 'Y73E7A.1': 'Coiled-coil domain-containing protein',
 'Y73E7A.8': 'Mucin-5AC',
 'Y71G12B.20': 'Semaphorin-2A',
 'Y71G12B.21': 'Prion-like-(Q/N-rich)-domain-bearing protein',
 'Y71G12B.18': 'Methyltransferase FkbM domain-containing protein',
 'Y71G12B.17': 'Phosphatidylinositol transfer protein',
 'Y71G12B.23': 'Hemolysin-III related-domain-containing protein;Monocyte to macrophage differentiation factor',
 'Y71G12B.15': 'UBC core domain-containing protein;UBIQUITIN_CONJUGAT_2 domain-containing protein',
 'Y71G12B.12': 'Autophagy-related protein 5',
 'Y71G12B.11': 'FERM domain-containing protein;I/LWEQ domain-containing protein;Talin central domain-containing protein',
 'Y71G12B.24': 'Mitochondrial-processing peptidase subunit alpha',
 'Y71G12B.10': 'hydroxymethylglutaryl-CoA lyase',
 'Y71G12B.9': 'ML domain-containing protein;RING-type domain-containing protein;Uncharacterized protein',
 'Y71G12B.25': 'MFS domain-containing protein;Major facilitator superfamily (MFS) profile domain-containing protein',
 'Y71G12B.26': 'MFS domain-containing protein',
 'Y71G12B.8': 'RNA helicase',
 'Y71G12B.6': 'NAD(P)-bd_dom domain-containing protein;NAD(P)-binding domain-containing protein',
 'Y71G12B.27': 'Cyclin-dependent kinases regulatory subunit',
 'Y71G12B.4': 'putative peptidylglycine alpha-hydroxylating monooxygenase 1',
 'Y71G12B.1': 'WD_REPEATS_REGION domain-containing protein',
 'Y71G12B.28': 'pseudo',
 'C53H9.2': 'Large subunit GTPase 1 homolog',
 'C53H9.1': 'Large ribosomal subunit protein eL27',
 'M01D7.7': 'Guanine nucleotide-binding protein subunit alpha',
 'M01D7.6': 'Emerin homolog 1',
 'M01D7.5': 'Neuropeptide-Like Protein',
 'M01D7.4': 'GHMP kinase C-terminal domain-containing protein;Galactokinase',
 'M01D7.2': 'Secretory carrier-associated membrane protein',
 'Y71G12A.3': 'Tubby C-terminal domain-containing protein',
 'Y71G12A.4': 'AB hydrolase-1 domain-containing protein',
 'Y51F10.7': 'MD-2-related lipid-recognition domain-containing protein',
 'Y37E3.1': 'Tetratricopeptide repeat protein 5 OB fold domain-containing protein',
 'Y37E3.3': 'DNA-directed RNA polymerases I, II, and III subunit RPABC5',
 'Y37E3.4': 'Modifier of protein aggregation 4',
 'Y37E3.5': 'ADP-ribosylation factor-like protein 13B',
 'Y37E3.7': 'Large ribosomal subunit protein P1',
 'Y37E3.8': 'Large ribosomal subunit protein uL15',
 'Y37E3.9': 'Mitochondrial prohibitin complex protein 1',
 'Y37E3.10': 'Eukaryotic translation initiation factor 2 subunit 1',
 'Y37E3.11': 'IstB_IS21 domain-containing protein;Secreted protein;ethanolamine-phosphate cytidylyltransferase',
 'Y37E3.13': 'Ig-like domain-containing protein',
 'Y37E3.16': 'Solute carrier family 40 member',
 'Y37E3.15': 'Nuclear pore protein',
 'Y37E3.17': 'Dimethylglycine dehydrogenase, mitochondrial',
 'W03F11.6': 'Afadin;FHA domain-containing protein;PDZ domain-containing protein',
 'W03F11.5': 'Uncharacterized protein',
 'W03F11.1': 'Chitin-binding type-2 domain-containing protein',
 'W03F11.3': 'Major sperm protein',
 'W03F11.4': 'WSN domain-containing protein',
 'F12B6.2': 'MFS domain-containing protein;Major facilitator superfamily (MFS) profile domain-containing protein',
 'F12B6.1': 'ABC transporter domain-containing protein',
 'Y39G10AL.1': 'Tropomyosin;Tubulin-specific chaperone A',
 'Y39G10AL.3': 'Cyclin-dependent kinase 7',
 'Y39G10AR.11': 'TPR_MLP1_2 domain-containing protein',
 'Y39G10AR.12': 'TPX2 domain-containing protein',
 'Y39G10AR.10': 'Ectopic P granules protein 2',
 'Y39G10AR.13': 'Inner centromere protein ARK-binding domain-containing protein',
 'Y39G10AR.9': 'WD_REPEATS_REGION domain-containing protein',
 'Y39G10AR.21': '5-methylcytosine rRNA methyltransferase nsun-4',
 'Y39G10AR.20': 'Tubulin-specific chaperone A',
 'Y39G10AR.8': 'protein-synthesizing GTPase',
 'Y39G10AR.14': 'DNA replication licensing factor mcm-4',
 'Y39G10AR.15': 'DUF5523 domain-containing protein',
 'Y39G10AR.16': 'Uncharacterized protein',
 'Y39G10AR.18': 'Histone-lysine N-methyltransferase, H3 lysine-79 specific',
 'Y39G10AR.2': 'Protein zwilch homolog',
 'F23C8.13': 'PDZ domain-containing protein',
 'F23C8.5': 'Electron transfer flavoprotein subunit beta',
 'F23C8.6': 'Charged multivesicular body protein 1b',
 'F23C8.8': 'non-specific serine/threonine protein kinase',
 'F23C8.9': 'Protein TIPIN homolog',
 'F23C8.4': 'UBX domain-containing protein 1',
 'T16H5.1': 'Innexin-19',
 'Y74C10AL.2': 'Transmembrane protein 50A',
 'Y74C10AR.3': 'ABC transmembrane type-1 domain-containing protein;Iron-sulfur clusters transporter ABCB7, mitochondrial',
 'Y74C10AR.2': 'Conserved secreted protein',
 'Y74C10AR.1': 'Eukaryotic translation initiation factor 3 subunit I;Serine-threonine kinase receptor-associated protein',
 'Y23H5B.6': 'ATP-dependent RNA helicase;ATP-dependent rRNA helicase SPB4-like C-terminal extension domain-containing protein',
 'Y23H5B.5': 'U3 small nucleolar RNA-associated protein 15 homolog',
 'Y23H5B.7': 'pseudo',
 'C55C2.2': 'Sperm-specific class P protein 19',
 'C55C2.5': 'Amino Acid Transporter',
 'K07A3.2': 'SSD domain-containing protein',
 'K07A3.3': 'ATP-dependent Clp protease ATP-binding subunit clpX-like, mitochondrial',
 'Y23H5A.5': 'Alpha-catulin',
 'Y23H5A.3': 'Protein pid-3',
 'Y23H5A.2': 'Cnn_1N domain-containing protein;t-SNARE coiled-coil homology domain-containing protein',
 'Y23H5A.7': 'Cysteine--tRNA ligase, cytoplasmic',
 'Y23H5A.1': 'pseudo',
 'F40E3.5': 'Serine/threonine specific protein phosphatases domain-containing protein',
 'F32B5.6': 'BTB domain-containing protein;MIF4G domain-containing protein',
 'F32B5.7': 'Glycine-rich domain-containing protein 1;VWFD domain-containing protein',
 'F32B5.8': 'Cathepsin Z-1',
 'F32B5.4': 'Anther-specific protein BCP1-like',
 'F32B5.1': 'arginine kinase',
 'Y71F9B.5': 'Frizzled-4',
 'Y71F9B.16': 'J domain-containing protein',
 'Y71F9B.4': 'putative small nuclear ribonucleoprotein G',
 'Y71F9B.3': 'Receptor expression-enhancing protein',
 'Y71F9B.2': 'Phosphatidate cytidylyltransferase, mitochondrial',
 'Y71F9B.8': 'eLRR (extracellular Leucine-Rich Repeat) ONly',
 'Y71F9B.7': 'Serine/threonine-protein kinase plk-2',
 'Y71F9B.9': 'L-gulonate 3-dehydrogenase',
 'Y71F9B.10': 'Mediator complex subunit 1;Mediator of RNA polymerase II transcription subunit 1.1',
 'Y71F9B.13': 'NADH dehydrogenase [ubiquinone] 1 beta subcomplex subunit 7',
 'W03D8.9': 'Membrane transporter protein',
 'W03D8.10': 'pseudo',
 'W03D8.2': 'Serine/threonine-protein phosphatase',
 'W03D8.6': 'InTestinal NeureXin-like',
 'W03D8.5': 'Major sperm protein',
 'W03D8.3': 'Uncharacterized protein',
 'W10C8.2': 'Protein pop-1',
 'W10C8.5': 'arginine kinase',
 'Y71F9AL.10': 'RING-type E3 ubiquitin transferase',
 'Y71F9AL.13': 'Large ribosomal subunit protein uL1',
 'Y71F9AL.9': 'CUE domain-containing protein',
 'Y71F9AL.8': 'Myb_DNA-bind_3 domain-containing protein',
 'Y71F9AL.14': 'Dynactin subunit 5',
 'Y71F9AL.16': 'Actin-related protein 3',
 'Y71F9AL.25': 'Clathrin light chain',
 'Y71F9AL.6': 'Protein PBN1',
 'Y71F9AL.17': 'Coatomer subunit alpha',
 'Y71F9AL.4': 'Tyrosine-protein phosphatase',
 'Y71F9AL.2': 'Protein kinase domain-containing protein',
 'Y71F9AL.1': 'tRNA (guanine(10)-N2)-methyltransferase homolog',
 'Y71F9AM.6': 'Translocon-associated protein subunit alpha',
 'Y71F9AM.5': 'NTF2-related export protein',
 'Y71F9AM.4': 'Conserved oligomeric Golgi complex subunit 3;Conserved oligomeric Golgi complex subunit 3 C-terminal domain-containing protein',
 'Y71F9AR.1': 'Neurexin-related protein bam-2',
 'Y71F9AR.3': 'SUPpressor of Rpm-1',
 'Y54E10BL.4': 'J domain-containing protein',
 'Y54E10BL.6': 'Dual specificity mitogen-activated protein kinase kinase mek-2',
 'Y54E10BL.2': 'Nematode cuticle collagen N-terminal domain-containing protein',
 'Y54E10BR.4': 'RNA-binding protein NOB1',
 'Y54E10BR.3': 'RING-type E3 ubiquitin transferase',
 'Y54E10BR.5': 'Signal peptidase complex catalytic subunit SEC11',
 'Y54E10BR.6': 'DNA-directed RNA polymerase II subunit RPB7',
 'Y54E10BR.2': 'ADP-ribosylation factor-related protein 1',
 'Y54E10BR.7': 'Transporter',
 'Y54E10BR.8': 'C2H2-type domain-containing protein',
 'Y54E10BR.1': 'GPI ethanolamine phosphate transferase 1',
 'M01B12.3': 'Actin-related protein 2/3 complex subunit 5',
 'M01B12.5': 'Serine/threonine-protein kinase RIO1',
 'C45E1.1': 'Nuclear hormone receptor family member nhr-64',
 'C45E1.4': 'DUF148 domain-containing protein',
 'K09H9.6': 'Brix domain-containing protein',
 'K09H9.2': 'Sister chromatid cohesion protein DCC1',
 'Y54E10A.9': 'RNA helicase',
 'Y54E10A.7': 'Large ribosomal subunit protein bL17m',
 'Y54E10A.6': 'B3/B4 tRNA-binding domain-containing protein',
 'Y54E10A.5': 'Dynactin subunit 6',
 'Y54E10A.10': 'Ribosome production factor 2 homolog',
 'Y54E10A.11': 'E3 ubiquitin-protein ligase listerin',
 'Y54E10A.12': 'ING domain-containing protein;PH domain-containing protein',
 'Y54E10A.4': 'RRM domain-containing protein',
 'Y54E10A.15': 'CDT1 Geminin-binding domain-containing protein',
 'Y54E10A.3': 'Thioredoxin-like protein',
 'Y54E10A.16': 'Male abnormal protein mab-31',
 'Y44E3B.1': 'Transcription factor zip-4',
 'W01B11.3': 'Nop domain-containing protein',
 'W01B11.6': 'Thioredoxin domain-containing protein',
 'W01B11.1': 'Uncharacterized protein',
 'Y44E3A.2': 'Carboxylic ester hydrolase',
 'Y44E3A.4': 'SH3 domain-containing protein',
 'Y44E3A.6': 'FHA domain-containing protein',
 'W05F2.3': 'Transmembrane protein',
 'W05F2.6': 'RRM domain-containing protein',
 'K03E5.3': 'Cyclin-dependent kinase 2;Protein kinase domain-containing protein',
 'Y47G6A.12': 'Separin homolog sep-1',
 'Y47G6A.28': 'Protein kinase domain-containing protein',
 'Y47G6A.11': 'DNA mismatch repair protein',
 'Y47G6A.10': 'AFG3-like protein spg-7',
 'Y47G6A.9': 'DNA-directed RNA polymerase III subunit',
 'Y47G6A.8': 'Flap endonuclease 1',
 'Y47G6A.7': 'Sugar phosphate transporter domain-containing protein',
 'Y47G6A.18': 'Golgi phosphoprotein 3 homolog sauron',
 'Y47G6A.6': 'Histone acetyltransferase GCN5',
 'Y47G6A.19': 'Peptidase M14 carboxypeptidase A domain-containing protein;ShKT domain-containing protein',
 'Y47G6A.20': 'Poly(U)-binding-splicing factor rnp-6',
 'Y47G6A.4': 'RNA interference defective protein 10',
 'Y47G6A.21': 'DeHydrogenases, Short chain',
 'Y47G6A.22': 'DeHydrogenases, Short chain',
 'Y47G6A.23': 'Bridge-like lipid transfer protein family member 1 C-terminal domain-containing protein',
 'Y47G6A.24': 'uncharacterized protein',
 'Y47G6A.25': 'Uncharacterized protein',
 'Y47G6A.2': 'Innexin',
 'Y47G6A.1': 'Innexin',
 'Y47G6A.26': 'Uncharacterized protein',
 'T28F2.4': 'Bifunctional lysine-specific demethylase and histidyl-hydroxylase NO66',
 'T28F2.5': 'Guanylate kinase/L-type calcium channel beta subunit domain-containing protein',
 'D1037.3': 'Ferritin',
 'D1037.4': 'Ras-related protein Rab-8A',
 'D1037.1': 'Protein SON',
 'D1037.5': 'phospholipase A2',
 'H26D21.2': 'DNA mismatch repair proteins mutS family domain-containing protein',
 'H26D21.1': 'Checkpoint protein',
 'T12F5.3': 'ATP-dependent RNA helicase glh-4',
 'T12F5.5': 'HTH La-type RNA-binding domain-containing protein',
 'Y8G1A.2': 'Innexin',
 'ZK770.3': 'Innexin-12',
 'C32E8.6': 'AMP-binding domain-containing protein;AMP-dependent synthetase/ligase domain-containing protein',
 'C32E8.5': 'FHA domain-containing protein',
 'C32E8.4': 'Uncharacterized protein',
 'C32E8.3': 'Tubulin polymerization-promoting protein homolog',
 'C32E8.2': 'Large ribosomal subunit protein eL13',
 'C32E8.8': 'SSD domain-containing protein',
 'C32E8.9': 'Ethylmalonyl-CoA decarboxylase',
 'C32E8.10': 'Phosphatidylinositol-binding clathrin assembly protein unc-11',
 'C32E8.11': 'E3 ubiquitin-protein ligase ubr-1',
 'F53F10.5': 'Nsp1_C domain-containing protein',
 'F53F10.7': 'ncRNA',
 'F53F10.4': 'Ras-related protein Rab-2',
 'F53F10.3': 'putative mitochondrial pyruvate carrier 2',
 'F53F10.2': 'AntiZyme INhibitor;Antizyme inhibitor 1;BRCA1',
 'F53F10.1': 'Coiled-coil domain-containing protein 102A',
 'T03F1.5': 'Serine/threonine-protein phosphatase PP1-delta',
 'T03F1.6': 'F-box domain-containing protein',
 'T03F1.11': 'EF-hand domain-containing protein',
 'T03F1.8': 'guanylate kinase',
 'T03F1.9': 'HoloCentric chromosome binding Protein',
 'T03F1.3': 'putative phosphoglycerate kinase',
 'T03F1.2': 'Ubiquinone biosynthesis protein coq-4, mitochondrial',
 'T03F1.10': 'C-type lectin domain-containing protein',
 'T03F1.1': 'Ubiquitin-like modifier-activating enzyme 5',
 'T03F1.12': 'Protein SYS1 homolog',
 'C50F2.3': 'Pre-mRNA-splicing factor SYF1',
 'C50F2.2': 'CCHC-type domain-containing protein',
 'C50F2.5': 'Tyrosine-protein phosphatase domain-containing protein',
 'C50F2.6': 'peptidylprolyl isomerase',
 'T20F5.2': 'Proteasome subunit beta type-2',
 'T20F5.3': 'Ribosome-recycling factor, mitochondrial',
 'T20F5.4': 'Uncharacterized protein',
 'T20F5.6': 'RING-type domain-containing protein',
 'T20F5.7': 'RING-type domain-containing protein',
 'T21E3.1': 'Inactive protein-tyrosine phosphatase egg-4',
 'T21E3.3': 'EGF-like domain-containing protein',
 'F47B3.6': 'Protein-tyrosine phosphatase',
 'F47B3.7': 'Protein-tyrosine phosphatase',
 'F47B3.1': 'Protein-tyrosine phosphatase',
 'F28H1.3': 'Alanine--tRNA ligase, cytoplasmic',
 'F28H1.2': 'Calponin-homology (CH) domain-containing protein',
 'F28H1.1': 'Uncharacterized protein',

---
## 2. STRING Source — Protein–Protein Interactions

Load the raw STRING file, strip species prefix, clean protein IDs (handle version numbers with exactly 2 dots), uppercase, and add KG metadata.

**ID cleaning logic:** C. elegans protein IDs can have version suffixes like `Y110A7A.10.1`. When there are exactly 2 dots, the middle segment is removed (e.g., `Y110A7A.10.1` → `Y110A7A.1`). IDs are then uppercased to match NCBI LocusTags.

In [16]:
# =============================================================================
# Load raw STRING protein-protein interaction file
# =============================================================================

string_ppi_df = pd.read_csv(STRING_RAW_PATH, sep='\\s')
string_ppi_df = string_ppi_df.rename(columns={'protein1': 'head', 'protein2': 'tail'})

# Strip species prefix '6239.' from both columns
string_ppi_df['tail'] = string_ppi_df['tail'].str.replace('6239.', '', regex=False)
string_ppi_df['head'] = string_ppi_df['head'].str.replace('6239.', '', regex=False)

print(f"Raw STRING interactions loaded: {len(string_ppi_df):,}")
string_ppi_df

# =============================================================================
# Clean protein IDs: handle version numbers and uppercase
# =============================================================================
# For IDs with exactly 2 dots (e.g., Y110A7A.10.1), remove the middle segment
# Then uppercase all IDs to match NCBI LocusTag format

for col in ['head', 'tail']:
    mask = string_ppi_df[col].str.count(r'\.') == 2
    string_ppi_df.loc[mask, col] = string_ppi_df.loc[mask, col].str.replace(r'\.[^.]+\.', '.', regex=True)

# Uppercase to match NCBI LocusTag format
string_ppi_df['head'] = string_ppi_df['head'].str.upper()
string_ppi_df['tail'] = string_ppi_df['tail'].str.upper()

print(f"Protein IDs cleaned and uppercased")
string_ppi_df

/tmp/ipykernel_2171772/803880184.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  string_ppi_df = pd.read_csv(STRING_RAW_PATH, sep='\\s')

Raw STRING interactions loaded: 9,271,876
Protein IDs cleaned and uppercased

,head,tail,neighborhood,fusion,cooccurence,coexpression,experimental,database,textmining,combined_score
0,2L52.1,B0205.1,0,0,0,0,148,0,56,161
1,2L52.1,C24D10.1,0,0,0,0,220,0,0,220
2,2L52.1,C43E11.1,0,0,0,89,129,0,55,185
3,2L52.1,R13F6.1,0,0,0,0,167,0,0,167
4,2L52.1,C13D9.1,0,0,0,81,129,0,0,164
...,...,...,...,...,...,...,...,...,...,...
9271871,CTEL55X.1,F32A5.1,0,0,0,173,0,0,0,173
9271872,CTEL55X.1,F36A4.1,0,0,0,174,0,0,0,173
9271873,CTEL55X.1,Y73C8B.1,0,0,0,154,0,0,0,153
9271874,CTEL55X.1,C37C3.1,0,0,0,164,0,0,0,163
9271875,CTEL55X.1,C03B1.1,0,0,0,385,0,0,0,384

In [17]:
# =============================================================================
# Add KG metadata and map descriptions for STRING source
# =============================================================================
string_ppi_df['relation'] = 'Gene_Gene'
string_ppi_df['head_type'] = 'Gene'
string_ppi_df['tail_type'] = 'Gene'
string_ppi_df['relation_type'] = np.nan
string_ppi_df['kg_source'] = 'STRING'
string_ppi_df
string_ppi_df['head_detail_name'] = string_ppi_df['head'].map(ncbi_locustag_to_description)
string_ppi_df['tail_detail_name'] = string_ppi_df['tail'].map(ncbi_locustag_to_description)

In [18]:
string_ppi_df

,head,tail,neighborhood,fusion,cooccurence,coexpression,experimental,database,textmining,combined_score,relation,head_type,tail_type,relation_type,kg_source,head_detail_name,tail_detail_name
0,2L52.1,B0205.1,0,0,0,0,148,0,56,161,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,SPK domain-containing protein
1,2L52.1,C24D10.1,0,0,0,0,220,0,0,220,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,Tyrosine-protein phosphatase domain-containing...
2,2L52.1,C43E11.1,0,0,0,89,129,0,55,185,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,SAP domain-containing protein
3,2L52.1,R13F6.1,0,0,0,0,167,0,0,167,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,KNL (kinetochore null) Binding Protein
4,2L52.1,C13D9.1,0,0,0,81,129,0,0,164,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,ABC transmembrane type-1 domain-containing pro...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9271871,CTEL55X.1,F32A5.1,0,0,0,173,0,0,0,173,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,SANT domain-containing protein
9271872,CTEL55X.1,F36A4.1,0,0,0,174,0,0,0,173,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,Uncharacterized protein
9271873,CTEL55X.1,Y73C8B.1,0,0,0,154,0,0,0,153,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,AB hydrolase-1 domain-containing protein
9271874,CTEL55X.1,C37C3.1,0,0,0,164,0,0,0,163,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,DUF1768 domain-containing protein;NADAR domain...
9271875,CTEL55X.1,C03B1.1,0,0,0,385,0,0,0,384,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,Uncharacterized protein

In [19]:

string_ppi_df['head_id_is'] = 'NCBI_ID'
string_ppi_df['tail_id_is'] = 'NCBI_ID'
string_ppi_df['species'] = 'C.elegans'
string_ppi_df

,head,tail,neighborhood,fusion,cooccurence,coexpression,experimental,database,textmining,combined_score,relation,head_type,tail_type,relation_type,kg_source,head_detail_name,tail_detail_name,head_id_is,tail_id_is,species
0,2L52.1,B0205.1,0,0,0,0,148,0,56,161,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,SPK domain-containing protein,NCBI_ID,NCBI_ID,C.elegans
1,2L52.1,C24D10.1,0,0,0,0,220,0,0,220,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,Tyrosine-protein phosphatase domain-containing...,NCBI_ID,NCBI_ID,C.elegans
2,2L52.1,C43E11.1,0,0,0,89,129,0,55,185,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,SAP domain-containing protein,NCBI_ID,NCBI_ID,C.elegans
3,2L52.1,R13F6.1,0,0,0,0,167,0,0,167,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,KNL (kinetochore null) Binding Protein,NCBI_ID,NCBI_ID,C.elegans
4,2L52.1,C13D9.1,0,0,0,81,129,0,0,164,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,ABC transmembrane type-1 domain-containing pro...,NCBI_ID,NCBI_ID,C.elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9271871,CTEL55X.1,F32A5.1,0,0,0,173,0,0,0,173,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,SANT domain-containing protein,NCBI_ID,NCBI_ID,C.elegans
9271872,CTEL55X.1,F36A4.1,0,0,0,174,0,0,0,173,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,Uncharacterized protein,NCBI_ID,NCBI_ID,C.elegans
9271873,CTEL55X.1,Y73C8B.1,0,0,0,154,0,0,0,153,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,AB hydrolase-1 domain-containing protein,NCBI_ID,NCBI_ID,C.elegans
9271874,CTEL55X.1,C37C3.1,0,0,0,164,0,0,0,163,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,DUF1768 domain-containing protein;NADAR domain...,NCBI_ID,NCBI_ID,C.elegans
9271875,CTEL55X.1,C03B1.1,0,0,0,385,0,0,0,384,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,Uncharacterized protein,NCBI_ID,NCBI_ID,C.elegans

In [20]:

# Filter out unmapped entries
string_ppi_df = string_ppi_df[~string_ppi_df['head_detail_name'].isna()]
string_ppi_df = string_ppi_df[~string_ppi_df['tail_detail_name'].isna()]

print(f"STRING Gene-Gene triples after filtering: {len(string_ppi_df):,}")
string_ppi_df
string_ppi_df

STRING Gene-Gene triples after filtering: 7,867,356

,head,tail,neighborhood,fusion,cooccurence,coexpression,experimental,database,textmining,combined_score,relation,head_type,tail_type,relation_type,kg_source,head_detail_name,tail_detail_name,head_id_is,tail_id_is,species
0,2L52.1,B0205.1,0,0,0,0,148,0,56,161,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,SPK domain-containing protein,NCBI_ID,NCBI_ID,C.elegans
1,2L52.1,C24D10.1,0,0,0,0,220,0,0,220,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,Tyrosine-protein phosphatase domain-containing...,NCBI_ID,NCBI_ID,C.elegans
2,2L52.1,C43E11.1,0,0,0,89,129,0,55,185,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,SAP domain-containing protein,NCBI_ID,NCBI_ID,C.elegans
3,2L52.1,R13F6.1,0,0,0,0,167,0,0,167,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,KNL (kinetochore null) Binding Protein,NCBI_ID,NCBI_ID,C.elegans
4,2L52.1,C13D9.1,0,0,0,81,129,0,0,164,Gene_Gene,Gene,Gene,NaN,STRING,C2H2-type domain-containing protein,ABC transmembrane type-1 domain-containing pro...,NCBI_ID,NCBI_ID,C.elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9271871,CTEL55X.1,F32A5.1,0,0,0,173,0,0,0,173,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,SANT domain-containing protein,NCBI_ID,NCBI_ID,C.elegans
9271872,CTEL55X.1,F36A4.1,0,0,0,174,0,0,0,173,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,Uncharacterized protein,NCBI_ID,NCBI_ID,C.elegans
9271873,CTEL55X.1,Y73C8B.1,0,0,0,154,0,0,0,153,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,AB hydrolase-1 domain-containing protein,NCBI_ID,NCBI_ID,C.elegans
9271874,CTEL55X.1,C37C3.1,0,0,0,164,0,0,0,163,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,DUF1768 domain-containing protein;NADAR domain...,NCBI_ID,NCBI_ID,C.elegans
9271875,CTEL55X.1,C03B1.1,0,0,0,385,0,0,0,384,Gene_Gene,Gene,Gene,NaN,STRING,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,Uncharacterized protein,NCBI_ID,NCBI_ID,C.elegans

In [21]:

# Keep + reorder columns
string_ppi_df = string_ppi_df[
    [
        "head",
        "relation",
        "tail",
        "head_type",
        "relation_type",
        "tail_type",
        "kg_source",
        "head_id_is",
        "tail_id_is",
        "head_detail_name",
        "tail_detail_name",
        "species"
    ]
]

# Add kg_type column
string_ppi_df["kg_type"] = string_ppi_df["species"]

# Final column order
string_ppi_df = string_ppi_df[
    [
        "head",
        "relation",
        "tail",
        "head_type",
        "relation_type",
        "tail_type",
        "kg_source",
        "kg_type",
        "head_id_is",
        "tail_id_is",
        "head_detail_name",
        "tail_detail_name",
        "species"
    ]
]

# Save
string_ppi_df

/tmp/ipykernel_2171772/3154585268.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  string_ppi_df["kg_type"] = string_ppi_df["species"]

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,2L52.1,Gene_Gene,B0205.1,Gene,NaN,Gene,STRING,C.elegans,NCBI_ID,NCBI_ID,C2H2-type domain-containing protein,SPK domain-containing protein,C.elegans
1,2L52.1,Gene_Gene,C24D10.1,Gene,NaN,Gene,STRING,C.elegans,NCBI_ID,NCBI_ID,C2H2-type domain-containing protein,Tyrosine-protein phosphatase domain-containing...,C.elegans
2,2L52.1,Gene_Gene,C43E11.1,Gene,NaN,Gene,STRING,C.elegans,NCBI_ID,NCBI_ID,C2H2-type domain-containing protein,SAP domain-containing protein,C.elegans
3,2L52.1,Gene_Gene,R13F6.1,Gene,NaN,Gene,STRING,C.elegans,NCBI_ID,NCBI_ID,C2H2-type domain-containing protein,KNL (kinetochore null) Binding Protein,C.elegans
4,2L52.1,Gene_Gene,C13D9.1,Gene,NaN,Gene,STRING,C.elegans,NCBI_ID,NCBI_ID,C2H2-type domain-containing protein,ABC transmembrane type-1 domain-containing pro...,C.elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9271871,CTEL55X.1,Gene_Gene,F32A5.1,Gene,NaN,Gene,STRING,C.elegans,NCBI_ID,NCBI_ID,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,SANT domain-containing protein,C.elegans
9271872,CTEL55X.1,Gene_Gene,F36A4.1,Gene,NaN,Gene,STRING,C.elegans,NCBI_ID,NCBI_ID,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,Uncharacterized protein,C.elegans
9271873,CTEL55X.1,Gene_Gene,Y73C8B.1,Gene,NaN,Gene,STRING,C.elegans,NCBI_ID,NCBI_ID,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,AB hydrolase-1 domain-containing protein,C.elegans
9271874,CTEL55X.1,Gene_Gene,C37C3.1,Gene,NaN,Gene,STRING,C.elegans,NCBI_ID,NCBI_ID,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,DUF1768 domain-containing protein;NADAR domain...,C.elegans
9271875,CTEL55X.1,Gene_Gene,C03B1.1,Gene,NaN,Gene,STRING,C.elegans,NCBI_ID,NCBI_ID,Androgen-induced gene 1 protein;FAR-17a/AIG1-l...,Uncharacterized protein,C.elegans

In [ ]:
# =============================================================================
# Export final deduplicated Chemical-Gene KG triples
# =============================================================================

string_ppi_df.to_csv(OUTPUT_PATH, index=None)
print(f"Final output saved to: {OUTPUT_PATH}")

In [ ]:
OUTPUT_PATH