In [2]:
import pandas as pd
import numpy as np

In [4]:
# =============================================================================
# BASE PATHS — Update these to match your local directory structure
# =============================================================================
your_path_here = '/storage/Arushi/090526_EvoAge/kg_formation/data_collection/'

# NCBI gene info for C. elegans
NCBI_GENE_INFO_PATH = f'{your_path_here}databases_for_mapping/ncbi/Caenorhabditis_elegans.gene_info'


# Pre-processed WID/FICE gene-gene pickle
WID_PATH = f'{your_path_here}widb/WIDB_integrated_functional_network.txt'

# Final output path
OUTPUT_PATH = '/storage/Arushi/090526_EvoAge/kg_formation/processed_data/wid/wid_CELE_GENE_GENE.csv'

In [10]:
# =============================================================================
# Load NCBI gene info and build dictionaries
# =============================================================================

ncbi_cele_gene = pd.read_csv(NCBI_GENE_INFO_PATH, sep='\t')

# Strip 'CELE_' prefix from LocusTag
ncbi_cele_gene['LocusTag'] = ncbi_cele_gene['LocusTag'].str.replace('CELE_', '', regex=False)

# Dictionary: LocusTag → Description (used for head/tail_detail_name)
ncbi_locustag_to_description = dict(zip(ncbi_cele_gene['LocusTag'], ncbi_cele_gene['description']))

print(f"NCBI genes loaded: {len(ncbi_cele_gene):,}")
print(f"LocusTag → Description dictionary size: {len(ncbi_locustag_to_description):,}")

NCBI genes loaded: 46,927
LocusTag → Description dictionary size: 46,927

In [11]:
C_Ele_G_G_WID = pd.read_csv(f'{your_path_here}/widb/WIDB_integrated_functional_network.txt',sep = '\t')
C_Ele_G_G_WID

C_Ele_G_G_WID = C_Ele_G_G_WID.rename( columns = {'IDA' : 'Head', 'IDB': 'Tail'})

# Drop the specified columns
columns_to_drop = ['WI8','LCI','interologs','genetic','phenotypes','coexpression']
C_Ele_G_G_WID.drop(columns=columns_to_drop, inplace=True)

C_Ele_G_G_WID['Relation'] = 'Gene_Gene'
C_Ele_G_G_WID['Relation_Source'] = 'Worm_Interactome_Database'
C_Ele_G_G_WID['head_type'] = 'Gene'
C_Ele_G_G_WID['tail_type'] = 'Gene'

# Reorder the columns in the DataFrame
desired_columns = ['Head', 'Relation', 'Tail', 'head_type', 'tail_type', 'Relation_Source']
C_Ele_G_G_WID = C_Ele_G_G_WID[desired_columns]
C_Ele_G_G_WID
C_Ele_G_G_WID

,Head,Relation,Tail,head_type,tail_type,Relation_Source
0,4R79.1,Gene_Gene,4R79.1,Gene,Gene,Worm_Interactome_Database
1,4R79.1,Gene_Gene,C34D4.9,Gene,Gene,Worm_Interactome_Database
2,4R79.1,Gene_Gene,F39D8.4,Gene,Gene,Worm_Interactome_Database
3,6R55.1,Gene_Gene,C02F5.3,Gene,Gene,Worm_Interactome_Database
4,6R55.1,Gene_Gene,C03B1.12,Gene,Gene,Worm_Interactome_Database
...,...,...,...,...,...,...
178146,ZK970.3,Gene_Gene,ZK973.10,Gene,Gene,Worm_Interactome_Database
178147,ZK970.3,Gene_Gene,ZK973.11,Gene,Gene,Worm_Interactome_Database
178148,ZK970.3,Gene_Gene,ZK973.9,Gene,Gene,Worm_Interactome_Database
178149,ZK970.4,Gene_Gene,ZK973.10,Gene,Gene,Worm_Interactome_Database
178150,ZK973.11,Gene_Gene,ZK973.9,Gene,Gene,Worm_Interactome_Database

In [15]:
C_Ele_G_G_WID['relation'] = 'Gene_Gene'
C_Ele_G_G_WID['head_type'] = 'Gene'
C_Ele_G_G_WID['tail_type'] = 'Gene'
C_Ele_G_G_WID['relation_type'] = np.nan
C_Ele_G_G_WID['kg_source'] = C_Ele_G_G_WID['Relation_Source']
C_Ele_G_G_WID['head_detail_name'] = C_Ele_G_G_WID['Head'].map(ncbi_locustag_to_description)
C_Ele_G_G_WID['tail_detail_name'] = C_Ele_G_G_WID['Tail'].map(ncbi_locustag_to_description)
C_Ele_G_G_WID['head_id_is'] = 'NCBI_ID'
C_Ele_G_G_WID['tail_id_is'] = 'NCBI_ID'
C_Ele_G_G_WID['species'] = 'C.elegans'
C_Ele_G_G_WID
C_Ele_G_G_WID
C_Ele_G_G_WID = C_Ele_G_G_WID[~C_Ele_G_G_WID['head_detail_name'].isna()]
C_Ele_G_G_WID = C_Ele_G_G_WID[~C_Ele_G_G_WID['tail_detail_name'].isna()]
C_Ele_G_G_WID

,Head,Relation,Tail,head_type,tail_type,Relation_Source,relation,relation_type,kg_source,head_detail_name,tail_detail_name,head_id_is,tail_id_is,species
0,4R79.1,Gene_Gene,4R79.1,Gene,Gene,Worm_Interactome_Database,Gene_Gene,NaN,Worm_Interactome_Database,Metalloendopeptidase;Zinc metalloproteinase nas-6,Metalloendopeptidase;Zinc metalloproteinase nas-6,NCBI_ID,NCBI_ID,C.elegans
1,4R79.1,Gene_Gene,C34D4.9,Gene,Gene,Worm_Interactome_Database,Gene_Gene,NaN,Worm_Interactome_Database,Metalloendopeptidase;Zinc metalloproteinase nas-6,Zinc metalloproteinase nas-8,NCBI_ID,NCBI_ID,C.elegans
2,4R79.1,Gene_Gene,F39D8.4,Gene,Gene,Worm_Interactome_Database,Gene_Gene,NaN,Worm_Interactome_Database,Metalloendopeptidase;Zinc metalloproteinase nas-6,Zinc metalloproteinase nas-13,NCBI_ID,NCBI_ID,C.elegans
22,AC3.10,Gene_Gene,AC3.3,Gene,Gene,Worm_Interactome_Database,Gene_Gene,NaN,Worm_Interactome_Database,Palmitoyltransferase spe-10,Activated in Blocked Unfolded protein response,NCBI_ID,NCBI_ID,C.elegans
23,AC3.3,Gene_Gene,C03A7.14,Gene,Gene,Worm_Interactome_Database,Gene_Gene,NaN,Worm_Interactome_Database,Activated in Blocked Unfolded protein response,Activated in Blocked Unfolded protein response,NCBI_ID,NCBI_ID,C.elegans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178146,ZK970.3,Gene_Gene,ZK973.10,Gene,Gene,Worm_Interactome_Database,Gene_Gene,NaN,Worm_Interactome_Database,Mediator of RNA polymerase II transcription su...,NADH dehydrogenase [ubiquinone] iron-sulfur pr...,NCBI_ID,NCBI_ID,C.elegans
178147,ZK970.3,Gene_Gene,ZK973.11,Gene,Gene,Worm_Interactome_Database,Gene_Gene,NaN,Worm_Interactome_Database,Mediator of RNA polymerase II transcription su...,Thioredoxin domain-containing protein,NCBI_ID,NCBI_ID,C.elegans
178148,ZK970.3,Gene_Gene,ZK973.9,Gene,Gene,Worm_Interactome_Database,Gene_Gene,NaN,Worm_Interactome_Database,Mediator of RNA polymerase II transcription su...,SS18 N-terminal domain-containing protein,NCBI_ID,NCBI_ID,C.elegans
178149,ZK970.4,Gene_Gene,ZK973.10,Gene,Gene,Worm_Interactome_Database,Gene_Gene,NaN,Worm_Interactome_Database,putative V-type proton ATPase subunit F,NADH dehydrogenase [ubiquinone] iron-sulfur pr...,NCBI_ID,NCBI_ID,C.elegans
178150,ZK973.11,Gene_Gene,ZK973.9,Gene,Gene,Worm_Interactome_Database,Gene_Gene,NaN,Worm_Interactome_Database,Thioredoxin domain-containing protein,SS18 N-terminal domain-containing protein,NCBI_ID,NCBI_ID,C.elegans

In [18]:
C_Ele_G_G_WID.to_csv(f'{OUTPUT_PATH}',index = None)