In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
BASE_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/data_collection/"
OUT_PATH  = "/storage/Arushi/090526_EvoAge/kg_formation/processed_data/agingatlas"

# ── derived sub-paths (do not edit below this line) ──────────────
# Inputs
PUBCHEM_SYN_PATH    = os.path.join(BASE_PATH, "databases_for_mapping/pubchem/CID-Synonym-filtered")
PUBCHEM_PKL_PATH    = os.path.join(BASE_PATH, "databases_for_mapping/pubchem/combined_df.pkl")
GERO_COMP_PATH      = os.path.join(BASE_PATH, "agingatlas/Geroprotective_compounds.csv")
METABOLITES_PATH    = os.path.join(BASE_PATH, "agingatlas/metabolites_aging_atlas.csv")

# Output directories
OUT_HUMAN  = os.path.join(OUT_PATH, "Human/")
OUT_YEAST  = os.path.join(OUT_PATH, "Yeast/")
OUT_CELE   = os.path.join(OUT_PATH, "Cele/")
OUT_DROSO  = os.path.join(OUT_PATH, "Droso/")
OUT_MOUSE  = os.path.join(OUT_PATH, "Mouse/")

for d in [OUT_HUMAN, OUT_YEAST, OUT_CELE, OUT_DROSO, OUT_MOUSE]:
    os.makedirs(d, exist_ok=True)

print("Paths configured.")
print(f"  Input  : {BASE_PATH}")
print(f"  Output : {OUT_PATH}")

Paths configured.
  Input  : /storage/Arushi/090526_EvoAge/kg_formation/data_collection/
  Output : /storage/Arushi/090526_EvoAge/kg_formation/processed_data/agingatlas

# Mappings

In [3]:
## PubChem Synonym (unfiltered) → CID lookup

Pubchem_Syn_fil = pd.read_csv(PUBCHEM_SYN_PATH, sep='\t', header=None)
Pubchem_Syn_fil_dict = dict(zip(Pubchem_Syn_fil[1], Pubchem_Syn_fil[0]))
print(f"Loaded {len(Pubchem_Syn_fil_dict):,} PubChem synonyms")

Loaded 102,877,691 PubChem synonyms

In [4]:
#

In [5]:
## PubChem CID → IUPAC name & SMILES

Pubchem = pd.read_pickle(PUBCHEM_PKL_PATH)
Pubchem.head()

,PUBCHEM_COMPOUND_CID,PUBCHEM_IUPAC_NAME,PUBCHEM_SMILES
0,56500001,"2-[1-(4,6-dimethylpyrimidin-2-yl)-3,5-dimethyl...",CC1=CC(=NC(=N1)N2C(=C(C(=N2)C)CC(=O)NC3=C(N=CC...
1,56500002,N-[2-(2-methoxyethoxy)pyridin-3-yl]-2-[[4-(4-m...,COCCOC1=C(C=CC=N1)NC(=O)CSC2=NN=CN2C3=CC=C(C=C...
2,56500003,N-[2-(2-methoxyethoxy)pyridin-3-yl]-1-phenyl-5...,COCCOC1=C(C=CC=N1)NC(=O)C2=NN(C(=N2)C3=CC=CS3)...
3,56500004,4-methoxy-N-[2-(2-methoxyethoxy)pyridin-3-yl]-...,CC(C)NS(=O)(=O)C1=C(C=CC(=C1)C(=O)NC2=C(N=CC=C...
4,56500005,2-chloro-N-[2-(2-methoxyethoxy)pyridin-3-yl]-5...,CC(C)NS(=O)(=O)C1=CC(=C(C=C1)Cl)C(=O)NC2=C(N=C...

In [6]:
Pubchem_CID_Smile_Dict = dict(zip(Pubchem['PUBCHEM_COMPOUND_CID'], Pubchem['PUBCHEM_SMILES']))
Pubchem_IUPAC_CID_Dict = dict(zip(Pubchem['PUBCHEM_COMPOUND_CID'], Pubchem['PUBCHEM_IUPAC_NAME']))
print(f"Loaded {len(Pubchem_CID_Smile_Dict):,} CID→SMILES and {len(Pubchem_IUPAC_CID_Dict):,} CID→IUPAC mappings")

Loaded 119,177,440 CID→SMILES and 119,177,440 CID→IUPAC mappings

---
# Part 1 — Geroprotective Compounds

Source: `AgeingAtlas/Geroprotective_compounds.csv`  
Relation: `ChemicalEntity_Inhibits/Promotes_BiologicalProcess` → `GO:0007568`

In [7]:
file_gero_comp = pd.read_csv(GERO_COMP_PATH)
print(f"Loaded {len(file_gero_comp):,} rows")
print("Organisms:", set(file_gero_comp['organism']))
file_gero_comp

Loaded 447 rows
Organisms: {'Mytilina brevispina', 'Aeolosoma viride', 'Drosophila bipectinata', 'Acheta domesticus', 'Mytilina brevispina var redunca', 'Saccharomyces cerevisiae', 'Asplanchna brightwelli', 'Homo sapiens (cell culture)', 'Caenorhabditis elegans', 'Nothobranchius furzeri', 'Rattus norvegicus(cell culture)', 'Paramecium tetraurelia', 'Zaprionus paravittiger', 'Musca domestica', 'Mus musculus', 'Saccharomyces cerevisiae ', 'Anastrepha ludens', 'Rattus norvegicus', 'Drosophila melanogaster', 'Podospora anserina', 'Philodina acuticornis', 'Brachionus manjavacas', 'Aedes aegyptimosquito', 'Bombyx mori', 'Apis mellifera', 'Ceriodaphnia affinis', 'Mesocricetus auratus'}

,compounds,organism,phenotype,pmid,rnaseq
0,2-mercaptoethanol,Mus musculus,Extended Lifespan,6334792,Not Available
1,2-deoxy-D-glucose,Homo sapiens (cell culture),Senescence Retardated,21604001,Not Available
2,17-DMAG,Mus musculus,Extended Lifespan,28871086,Not Available
3,17a-oestradiol,Mus musculus,Extended Lifespan,27312236,Not Available
4,Alpha-phenyl-N-t-butyl-nitrone,Homo sapiens (cell culture),Senescence Retardated,10702229,Not Available
...,...,...,...,...,...
442,Vitamin E,Caenorhabditis elegans,Extended Lifespan,3374177,Not Available
443,Vitexin,Caenorhabditis elegans,Extended Lifespan,26535084,Not Available
444,Wortmannin,Drosophila melanogaster,Extended Lifespan,24096697,Not Available
445,Wortmannin,Caenorhabditis elegans,Shortened Lifespan,23543623,Not Available
446,Xylose,Caenorhabditis elegans,Extended Lifespan,25643626,Not Available

In [8]:
# Standardise organism names and filter to the 5 target species
file_gero_comp.loc[file_gero_comp['organism'] == 'Homo sapiens (cell culture)', 'organism'] = 'Homo sapiens'

Sp_list = ['Caenorhabditis elegans', 'Drosophila melanogaster',
           'Saccharomyces cerevisiae', 'Homo sapiens', 'Mus musculus']
file_gero_comp = file_gero_comp[file_gero_comp['organism'].isin(Sp_list)]

# Normalise phenotype labels → AntiAging / ProAging
anti_aging_terms = ['Extended Healthspan', 'Extended Lifespan ', 'Extended Lifespan /Healthspan',
                    'Senescence  Retardated', 'Senescence  Retardated ']
pro_aging_terms  = ['Shortened Lifespan', 'Shortened lifespan']

file_gero_comp['phenotype'] = file_gero_comp['phenotype'].apply(
    lambda x: 'AntiAging' if x in anti_aging_terms else ('ProAging' if x in pro_aging_terms else x)
)
file_gero_comp['compounds'] = file_gero_comp['compounds'].str.rstrip()

print("Phenotype counts after normalisation:")
print(file_gero_comp['phenotype'].value_counts())
print(f"\nRows remaining: {len(file_gero_comp):,}")

Phenotype counts after normalisation:
phenotype
AntiAging    396
ProAging       6
Name: count, dtype: int64

Rows remaining: 402

/tmp/ipykernel_2545539/111829890.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file_gero_comp['phenotype'] = file_gero_comp['phenotype'].apply(
/tmp/ipykernel_2545539/111829890.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file_gero_comp['compounds'] = file_gero_comp['compounds'].str.rstrip()

In [9]:
# Resolve compound name → PubChem CID (case-insensitive)
Pubchem_Syn_fil_dict_lower = {str(k).lower(): v for k, v in Pubchem_Syn_fil_dict.items()}

file_gero_comp['Head'] = file_gero_comp['compounds'].str.lower().map(Pubchem_Syn_fil_dict_lower)
file_gero_comp['Head'] = file_gero_comp['Head'].astype(str).str.replace(r'\.0$', '', regex=True)

before = len(file_gero_comp)
file_gero_comp = file_gero_comp[file_gero_comp['Head'] != 'nan']
print(f"PubChem CID resolved: {len(file_gero_comp):,} / {before:,} rows kept")

PubChem CID resolved: 343 / 402 rows kept

/tmp/ipykernel_2545539/169155311.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file_gero_comp['Head'] = file_gero_comp['compounds'].str.lower().map(Pubchem_Syn_fil_dict_lower)
/tmp/ipykernel_2545539/169155311.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file_gero_comp['Head'] = file_gero_comp['Head'].astype(str).str.replace(r'\.0$', '', regex=True)

In [10]:
# Annotate IUPAC name and SMILES
file_gero_comp['Head_detail_name'] = file_gero_comp['Head'].map(Pubchem_IUPAC_CID_Dict)
file_gero_comp['Head_SMILE_name']  = file_gero_comp['Head'].map(Pubchem_CID_Smile_Dict)

In [11]:
# Rename columns, add type/relation/source columns
file_gero_comp = file_gero_comp.rename(columns={
    'compounds': 'Head_Alt_name',
    'phenotype': 'Tail',
    'organism':  'Species'
})

file_gero_comp['Head_type']       = 'ChemicalEntity'
file_gero_comp['Tail_type']       = 'Phenotype'
file_gero_comp['Relation']        = file_gero_comp['Head_type'] + '_' + file_gero_comp['Tail_type']
file_gero_comp['Relation_Source'] = 'Aging_Atlas_gerprotector'
file_gero_comp['Data_type']       = 'Associative'

desired_order = [
    'Head', 'Relation', 'Tail', 'Head_type', 'Tail_type',
    'Head_detail_name', 'Head_SMILE_name',
    'Relation_Source', 'Species', 'Head_Alt_name', 'pmid', 'rnaseq', 'Data_type'
]
existing_cols = [c for c in desired_order if c in file_gero_comp.columns]
file_gero_comp = file_gero_comp[existing_cols]
file_gero_comp

,Head,Relation,Tail,Head_type,Tail_type,Head_detail_name,Head_SMILE_name,Relation_Source,Species,Head_Alt_name,pmid,rnaseq,Data_type
0,1567,ChemicalEntity_Phenotype,AntiAging,ChemicalEntity,Phenotype,2-sulfanylethanol,C(CS)O,Aging_Atlas_gerprotector,Mus musculus,2-mercaptoethanol,6334792,Not Available,Associative
1,17751002,ChemicalEntity_Phenotype,AntiAging,ChemicalEntity,Phenotype,"(3S,4R,5S)-3,4,5,6-tetrahydroxyhexanal",C(C=O)[C@@H]([C@H]([C@H](CO)O)O)O,Aging_Atlas_gerprotector,Homo sapiens,2-deoxy-D-glucose,21604001,Not Available,Associative
2,139254081,ChemicalEntity_Phenotype,AntiAging,ChemicalEntity,Phenotype,"[(4E,6E,8R,9R,10E,12S,13R,14S,16R)-19-[2-(dime...",C[C@H]1C[C@@H]([C@@H]([C@H](/C=C(/[C@H]([C@@H]...,Aging_Atlas_gerprotector,Mus musculus,17-DMAG,28871086,Not Available,Associative
3,68570,ChemicalEntity_Phenotype,AntiAging,ChemicalEntity,Phenotype,"(8R,9S,13S,14S,17R)-13-methyl-6,7,8,9,11,12,14...",C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@H]2O)CCC4=C3C...,Aging_Atlas_gerprotector,Mus musculus,17a-oestradiol,27312236,Not Available,Associative
6,163284948,ChemicalEntity_Phenotype,AntiAging,ChemicalEntity,Phenotype,"(2S,5S)-5-[(2R,5S)-5-[(2R,5S,6R)-3,4-dihydroxy...",C[C@@H]1[C@H](C(C([C@H](O1)O[C@@H]2C(O[C@@H](C...,Aging_Atlas_gerprotector,Mus musculus,Acarbose,24245565,Not Available,Associative
...,...,...,...,...,...,...,...,...,...,...,...,...,...
442,14985,ChemicalEntity_Phenotype,AntiAging,ChemicalEntity,Phenotype,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",CC1=C(C2=C(CC[C@@](O2)(C)CCC[C@H](C)CCC[C@H](C...,Aging_Atlas_gerprotector,Caenorhabditis elegans,Vitamin E,3374177,Not Available,Associative
443,5280441,ChemicalEntity_Phenotype,AntiAging,ChemicalEntity,Phenotype,"5,7-dihydroxy-2-(4-hydroxyphenyl)-8-[(2S,3R,4R...",C1=CC(=CC=C1C2=CC(=O)C3=C(O2)C(=C(C=C3O)O)[C@H...,Aging_Atlas_gerprotector,Caenorhabditis elegans,Vitexin,26535084,Not Available,Associative
444,312145,ChemicalEntity_Phenotype,AntiAging,ChemicalEntity,Phenotype,"[(1R,3R,5S,9R,18S)-18-(methoxymethyl)-1,5-dime...",CC(=O)O[C@@H]1C[C@]2([C@@H](CCC2=O)C3=C1[C@]4(...,Aging_Atlas_gerprotector,Drosophila melanogaster,Wortmannin,24096697,Not Available,Associative
445,312145,ChemicalEntity_Phenotype,ProAging,ChemicalEntity,Phenotype,"[(1R,3R,5S,9R,18S)-18-(methoxymethyl)-1,5-dime...",CC(=O)O[C@@H]1C[C@]2([C@@H](CCC2=O)C3=C1[C@]4(...,Aging_Atlas_gerprotector,Caenorhabditis elegans,Wortmannin,23543623,Not Available,Associative
446,135191,ChemicalEntity_Phenotype,AntiAging,ChemicalEntity,Phenotype,"(3R,4S,5R)-oxane-2,3,4,5-tetrol",C1[C@H]([C@@H]([C@H](C(O1)O)O)O)O,Aging_Atlas_gerprotector,Caenorhabditis elegans,Xylose,25643626,Not Available,Associative

In [12]:
# Map phenotype → canonical Relation, set Tail to aging GO term
file_gero_comp['Tail'] = file_gero_comp['Tail'].replace({
    'ProAging':  'ChemicalEntity_Promotes_BiologicalProcess',
    'AntiAging': 'ChemicalEntity_Inhibits_BiologicalProcess',
    'Not Clear': 'ChemicalEntity_NoEffect_BiologicalProcess'
})

# Swap Relation ↔ Tail so Relation column holds the edge type
file_gero_comp[['Relation', 'Tail']] = file_gero_comp[['Tail', 'Relation']]

file_gero_comp['Tail']             = 'GO:0007568'
file_gero_comp['Tail_detail_name'] = 'aging'
file_gero_comp['Tail_type']        = 'BiologicalProcess'
file_gero_comp['Data_type']        = 'Causative'

print("Relation counts:")
print(file_gero_comp['Relation'].value_counts())
print("\nSpecies counts:")
print(file_gero_comp['Species'].value_counts())

Relation counts:
Relation
ChemicalEntity_Inhibits_BiologicalProcess    338
ChemicalEntity_Promotes_BiologicalProcess      5
Name: count, dtype: int64

Species counts:
Species
Caenorhabditis elegans      224
Drosophila melanogaster      66
Mus musculus                 33
Homo sapiens                 10
Saccharomyces cerevisiae     10
Name: count, dtype: int64

## Export — Geroprotectors by Species

In [13]:
# ── Human ──────────────────────────────────────────────────────────
Human_Chemical_BioPro = file_gero_comp[file_gero_comp['Species'] == 'Homo sapiens']
print(Human_Chemical_BioPro['Relation'].value_counts())

out_file = os.path.join(OUT_HUMAN, 'AgingAtlas_Human_Chemical_Inhibit_BiologicalProcess_Geroprotectors.csv')
Human_Chemical_BioPro.to_csv(out_file, index=False)
print(f"Saved → {out_file}")

Relation
ChemicalEntity_Inhibits_BiologicalProcess    10
Name: count, dtype: int64
Saved → /storage/Arushi/090526_EvoAge/kg_formation/processed_data/agingatlas/Human/AgingAtlas_Human_Chemical_Inhibit_BiologicalProcess_Geroprotectors.csv

In [14]:
# ── Yeast ──────────────────────────────────────────────────────────
Yeast_Chemical_BioPro = file_gero_comp[file_gero_comp['Species'] == 'Saccharomyces cerevisiae']
print(Yeast_Chemical_BioPro['Relation'].value_counts())

out_file = os.path.join(OUT_YEAST, 'Yeast_AgingAtlas_Chemical_Inhibit_BiologicalProcess_Geroprotectors.csv')
Yeast_Chemical_BioPro.to_csv(out_file, index=False)
print(f"Saved → {out_file}")

Relation
ChemicalEntity_Inhibits_BiologicalProcess    10
Name: count, dtype: int64
Saved → /storage/Arushi/090526_EvoAge/kg_formation/processed_data/agingatlas/Yeast/Yeast_AgingAtlas_Chemical_Inhibit_BiologicalProcess_Geroprotectors.csv

In [15]:
# ── C. elegans ─────────────────────────────────────────────────────
Cele_Chemical_BioPro = file_gero_comp[file_gero_comp['Species'] == 'Caenorhabditis elegans']
print(Cele_Chemical_BioPro['Relation'].value_counts())

Cele_Inhibits  = Cele_Chemical_BioPro[Cele_Chemical_BioPro['Relation'] == 'ChemicalEntity_Inhibits_BiologicalProcess']
Cele_Promotes  = Cele_Chemical_BioPro[Cele_Chemical_BioPro['Relation'] == 'ChemicalEntity_Promotes_BiologicalProcess']

Cele_Inhibits.to_csv(os.path.join(OUT_CELE, 'Cele_AgingAtlas_Chemical_Inhibit_BiologicalProcess_Geroprotectors.csv'),  index=False)
Cele_Promotes.to_csv(os.path.join(OUT_CELE, 'Cele_AgingAtlas_Chemical_Promotes_BiologicalProcess_Geroprotectors.csv'), index=False)
print(f"Saved → {OUT_CELE}")

Relation
ChemicalEntity_Inhibits_BiologicalProcess    221
ChemicalEntity_Promotes_BiologicalProcess      3
Name: count, dtype: int64
Saved → /storage/Arushi/090526_EvoAge/kg_formation/processed_data/agingatlas/Cele/

In [16]:
# ── Drosophila ─────────────────────────────────────────────────────
Droso_Chemical_BioPro = file_gero_comp[file_gero_comp['Species'] == 'Drosophila melanogaster']
print(Droso_Chemical_BioPro['Relation'].value_counts())

Droso_Inhibits = Droso_Chemical_BioPro[Droso_Chemical_BioPro['Relation'] == 'ChemicalEntity_Inhibits_BiologicalProcess']
Droso_Promotes = Droso_Chemical_BioPro[Droso_Chemical_BioPro['Relation'] == 'ChemicalEntity_Promotes_BiologicalProcess']

Droso_Inhibits.to_csv(os.path.join(OUT_DROSO, 'Droso_AgingAtlas_Chemical_Inhibit_BiologicalProcess_Geroprotectors.csv'),  index=False)
Droso_Promotes.to_csv(os.path.join(OUT_DROSO, 'Droso_AgingAtlas_Chemical_Promotes_BiologicalProcess_Geroprotectors.csv'), index=False)
print(f"Saved → {OUT_DROSO}")

Relation
ChemicalEntity_Inhibits_BiologicalProcess    64
ChemicalEntity_Promotes_BiologicalProcess     2
Name: count, dtype: int64
Saved → /storage/Arushi/090526_EvoAge/kg_formation/processed_data/agingatlas/Droso/

In [17]:
# ── Mouse ──────────────────────────────────────────────────────────
Mouse_Chemical_BioPro = file_gero_comp[file_gero_comp['Species'] == 'Mus musculus']
print(Mouse_Chemical_BioPro['Relation'].value_counts())

Mouse_Inhibits = Mouse_Chemical_BioPro[Mouse_Chemical_BioPro['Relation'] == 'ChemicalEntity_Inhibits_BiologicalProcess']

Mouse_Inhibits.to_csv(os.path.join(OUT_MOUSE, 'Mouse_AgingAtlas_Chemical_Inhibit_BiologicalProcess_Geroprotectors.csv'), index=False)
print(f"Saved → {OUT_MOUSE}")

Relation
ChemicalEntity_Inhibits_BiologicalProcess    33
Name: count, dtype: int64
Saved → /storage/Arushi/090526_EvoAge/kg_formation/processed_data/agingatlas/Mouse/

In [18]:
Mouse_Chemical_BioPro[Mouse_Chemical_BioPro['Relation'] == 'ChemicalEntity_Promotes_BiologicalProcess']

Empty DataFrame
Columns: [Head, Relation, Tail, Head_type, Tail_type, Head_detail_name, Head_SMILE_name, Relation_Source, Species, Head_Alt_name, pmid, rnaseq, Data_type, Tail_detail_name]
Index: []

---
# Part 2 — Age-related Metabolites

Source: `AgeingAtlas/metabolites_aging_atlas.csv`  
Relation: `ChemicalEntity_Inhibits/Promotes_BiologicalProcess` → `GO:0007568`  
Direction derived from Log2 FC: positive → Pro-Aging, negative → Anti-Aging

In [19]:
file_metabolites = pd.read_csv(METABOLITES_PATH)
file_metabolites

,Biochemical,Species,Cell/Tissue,Treatment,Log2 FC,P,P adjust,Super Pathway,Sub Pathway,COMP ID,CHEMICAL ID,PUBCHEM,KEGG,HMDB
0,"N,N,N-trimethyl-5-aminovalerate",Macaca fascicularis,Skin,Young VS Old,1.360340,4.994000e-02,NaN,Amino Acid,Lysine Metabolism,57687,100015962,NaN,NaN,NaN
1,erucate (22:1n9),Macaca fascicularis,Plasma,Young VS Old,0.661547,4.972900e-02,NaN,Lipid,Long Chain Monounsaturated Fatty Acid,1552,1087,5281116.0,C08316,HMDB02068
2,1-carboxyethylphenylalanine,Macaca fascicularis,Brain,Young VS Old,-0.496104,4.966200e-02,NaN,Amino Acid,Phenylalanine Metabolism,62566,100020419,NaN,NaN,NaN
3,4-ethylphenyl sulfate,Macaca fascicularis,Kidney,Young VS Old,-2.860170,4.963000e-02,NaN,Xenobiotics,Benzoate Metabolism,36099,100001756,20822574.0,C13637,HMDB62551
4,1-palmitoyl-2-oleoyl-GPI (16:0/18:1)*,Homo sapiens,hMSCs,WT-hMSCs VS WS-hMSCs,0.769150,4.961100e-02,NaN,Lipid,Phosphatidylinositol (PI),52669,100009066,NaN,NaN,HMDB09783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,alpha-hydroxyisovalerate,Homo sapiens,hMSCs,WT-hMSCs VS WS-hMSCs,0.683700,3.710000e-07,NaN,Amino Acid,"Leucine, Isoleucine and Valine Metabolism",46537,100001300,99823.0,NaN,HMDB00407
989,phenol sulfate,Homo sapiens,hMSCs,WT-hMSCs VS WS-hMSCs,-0.944040,2.940000e-07,NaN,Amino Acid,Tyrosine Metabolism,32553,100001510,74426.0,C02180,HMDB60015
990,isovalerylcarnitine (C5),Homo sapiens,hMSCs,WT-hMSCs VS WS-hMSCs,-1.247100,8.150000e-08,NaN,Amino Acid,"Leucine, Isoleucine and Valine Metabolism",34407,100001393,6426851.0,NaN,HMDB00688
991,gamma-glutamyl-epsilon-lysine,Homo sapiens,hMSCs,WT-hMSCs VS WS-hMSCs,-2.022400,5.400000e-09,NaN,Peptide,Gamma-glutamyl Amino Acid,33934,100001262,7015685.0,NaN,HMDB03869
992,N-acetylputrescine,Homo sapiens,hMSCs,WT-hMSCs VS WS-hMSCs,2.228500,5.130000e-11,NaN,Amino Acid,Polyamine Metabolism,37496,192,122356.0,C02714,HMDB02064

In [20]:
file_metabolites = pd.read_csv(METABOLITES_PATH)
print(f"Loaded {len(file_metabolites):,} rows")
print("Species:", file_metabolites['Species'].value_counts().to_dict())
print(f"Log2 FC range: {file_metabolites['Log2 FC'].min():.3f} → {file_metabolites['Log2 FC'].max():.3f}")
file_metabolites = file_metabolites[file_metabolites['Treatment']== 'Young VS Old']
file_metabolites

Loaded 993 rows
Species: {'Macaca fascicularis': 738, 'Homo sapiens': 255}
Log2 FC range: -3.543 → 3.626

,Biochemical,Species,Cell/Tissue,Treatment,Log2 FC,P,P adjust,Super Pathway,Sub Pathway,COMP ID,CHEMICAL ID,PUBCHEM,KEGG,HMDB
0,"N,N,N-trimethyl-5-aminovalerate",Macaca fascicularis,Skin,Young VS Old,1.360340,0.049940,NaN,Amino Acid,Lysine Metabolism,57687,100015962,NaN,NaN,NaN
1,erucate (22:1n9),Macaca fascicularis,Plasma,Young VS Old,0.661547,0.049729,NaN,Lipid,Long Chain Monounsaturated Fatty Acid,1552,1087,5281116.0,C08316,HMDB02068
2,1-carboxyethylphenylalanine,Macaca fascicularis,Brain,Young VS Old,-0.496104,0.049662,NaN,Amino Acid,Phenylalanine Metabolism,62566,100020419,NaN,NaN,NaN
3,4-ethylphenyl sulfate,Macaca fascicularis,Kidney,Young VS Old,-2.860170,0.049630,NaN,Xenobiotics,Benzoate Metabolism,36099,100001756,20822574.0,C13637,HMDB62551
5,arachidoylcarnitine (C20)*,Macaca fascicularis,Skin,Young VS Old,0.614602,0.049287,NaN,Lipid,"Fatty Acid Metabolism (Acyl Carnitine, Long Ch...",57513,100015833,NaN,NaN,HMDB06460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,"N6,N6-dimethyllysine",Macaca fascicularis,Kidney,Young VS Old,1.606340,0.000124,NaN,Amino Acid,Lysine Metabolism,62862,100020417,193344.0,C05545,HMDB13287
945,phenylalanine,Macaca fascicularis,Liver,Young VS Old,0.634935,0.000110,NaN,Amino Acid,Phenylalanine Metabolism,64,460,6140.0,C00079,HMDB00159
951,tyrosylglycine,Macaca fascicularis,Liver,Young VS Old,1.604100,0.000086,NaN,Peptide,Dipeptide,41375,100003598,259323.0,NaN,HMDB29105
954,indole-3-carboxylate,Macaca fascicularis,Plasma,Young VS Old,1.424300,0.000067,NaN,Amino Acid,Tryptophan Metabolism,38116,100002185,69867.0,C19837,HMDB03320
966,anthranilate,Macaca fascicularis,Liver,Young VS Old,0.939261,0.000035,NaN,Amino Acid,Tryptophan Metabolism,4970,1258,227.0,C00108,HMDB01123

In [21]:
file_metabolites['Treatment'].value_counts()

Treatment
Young VS Old    738
Name: count, dtype: int64

In [22]:
# Resolve metabolite name → PubChem CID
# Fallback to PUBCHEM column if synonym lookup misses
Pubchem_Syn_fil_dict_lower = {str(k).lower(): v for k, v in Pubchem_Syn_fil_dict.items()}

file_metabolites['Head'] = (
    file_metabolites['Biochemical'].str.lower()
    .map(Pubchem_Syn_fil_dict_lower)
    .fillna(file_metabolites['PUBCHEM'])
)
file_metabolites['Head'] = file_metabolites['Head'].astype(str).str.replace(r'\.0$', '', regex=True)

before = len(file_metabolites)
file_metabolites = file_metabolites[file_metabolites['Head'] != 'nan']
print(f"PubChem CID resolved: {len(file_metabolites):,} / {before:,} rows kept")
print("Species after filter:", file_metabolites['Species'].value_counts().to_dict())

PubChem CID resolved: 590 / 738 rows kept
Species after filter: {'Macaca fascicularis': 590}

In [23]:
# Annotate IUPAC name and SMILES
file_metabolites['Head_detail_name'] = file_metabolites['Head'].map(Pubchem_IUPAC_CID_Dict)
file_metabolites['Head_SMILE_name']  = file_metabolites['Head'].map(Pubchem_CID_Smile_Dict)

/tmp/ipykernel_2545539/2188189837.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file_metabolites['Head_detail_name'] = file_metabolites['Head'].map(Pubchem_IUPAC_CID_Dict)
/tmp/ipykernel_2545539/2188189837.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file_metabolites['Head_SMILE_name']  = file_metabolites['Head'].map(Pubchem_CID_Smile_Dict)

In [24]:
file_metabolites['relation'] = file_metabolites['Log2 FC'].apply(
    lambda x: 'PositivelyAssociatedWithAging' if x < -1   # higher in Old
    else ('NegativelyAssociatedWithAging'     if x > 1   # higher in Young  
    else  'NotAssociatedWithAging')
)
file_metabolites

/tmp/ipykernel_2545539/3039339915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file_metabolites['relation'] = file_metabolites['Log2 FC'].apply(

,Biochemical,Species,Cell/Tissue,Treatment,Log2 FC,P,P adjust,Super Pathway,Sub Pathway,COMP ID,CHEMICAL ID,PUBCHEM,KEGG,HMDB,Head,Head_detail_name,Head_SMILE_name,relation
1,erucate (22:1n9),Macaca fascicularis,Plasma,Young VS Old,0.661547,0.049729,NaN,Lipid,Long Chain Monounsaturated Fatty Acid,1552,1087,5281116.0,C08316,HMDB02068,5281116,(Z)-docos-13-enoic acid,CCCCCCCC/C=C\CCCCCCCCCCCC(=O)O,NotAssociatedWithAging
2,1-carboxyethylphenylalanine,Macaca fascicularis,Brain,Young VS Old,-0.496104,0.049662,NaN,Amino Acid,Phenylalanine Metabolism,62566,100020419,NaN,NaN,NaN,127261991,(2S)-2-[[(1R)-1-carboxyethyl]amino]-3-phenylpr...,C[C@H](C(=O)O)N[C@@H](CC1=CC=CC=C1)C(=O)O,NotAssociatedWithAging
3,4-ethylphenyl sulfate,Macaca fascicularis,Kidney,Young VS Old,-2.860170,0.049630,NaN,Xenobiotics,Benzoate Metabolism,36099,100001756,20822574.0,C13637,HMDB62551,20822574,(4-ethylphenyl) hydrogen sulfate,CCC1=CC=C(C=C1)OS(=O)(=O)O,PositivelyAssociatedWithAging
6,glucose 6-phosphate,Macaca fascicularis,White adipose tissue,Young VS Old,2.860500,0.049167,NaN,Carbohydrate,"Glycolysis, Gluconeogenesis, and Pyruvate Meta...",31260,291,5958.0,C00668,HMDB01401,5958,"[(2R,3S,4S,5R)-3,4,5,6-tetrahydroxyoxan-2-yl]m...",C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)OP(=O...,NegativelyAssociatedWithAging
7,glycerate,Macaca fascicularis,White adipose tissue,Young VS Old,2.111790,0.048887,NaN,Carbohydrate,"Glycolysis, Gluconeogenesis, and Pyruvate Meta...",1572,1052,752.0,C00258,HMDB00139,5460358,"(2R)-2,3-dihydroxypropanoate",C([C@H](C(=O)[O-])O)O,NegativelyAssociatedWithAging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,"N6,N6-dimethyllysine",Macaca fascicularis,Kidney,Young VS Old,1.606340,0.000124,NaN,Amino Acid,Lysine Metabolism,62862,100020417,193344.0,C05545,HMDB13287,193344,(2S)-2-amino-6-(dimethylamino)hexanoic acid,CN(C)CCCC[C@@H](C(=O)O)N,NegativelyAssociatedWithAging
945,phenylalanine,Macaca fascicularis,Liver,Young VS Old,0.634935,0.000110,NaN,Amino Acid,Phenylalanine Metabolism,64,460,6140.0,C00079,HMDB00159,6140,(2S)-2-amino-3-phenylpropanoic acid,C1=CC=C(C=C1)C[C@@H](C(=O)O)N,NotAssociatedWithAging
951,tyrosylglycine,Macaca fascicularis,Liver,Young VS Old,1.604100,0.000086,NaN,Peptide,Dipeptide,41375,100003598,259323.0,NaN,HMDB29105,7021854,2-[[(2S)-2-amino-3-(4-hydroxyphenyl)propanoyl]...,C1=CC(=CC=C1C[C@@H](C(=O)NCC(=O)O)N)O,NegativelyAssociatedWithAging
954,indole-3-carboxylate,Macaca fascicularis,Plasma,Young VS Old,1.424300,0.000067,NaN,Amino Acid,Tryptophan Metabolism,38116,100002185,69867.0,C19837,HMDB03320,6932058,1H-indole-3-carboxylate,C1=CC=C2C(=C1)C(=CN2)C(=O)[O-],NegativelyAssociatedWithAging
966,anthranilate,Macaca fascicularis,Liver,Young VS Old,0.939261,0.000035,NaN,Amino Acid,Tryptophan Metabolism,4970,1258,227.0,C00108,HMDB01123,5459842,2-aminobenzoate,C1=CC=C(C(=C1)C(=O)[O-])N,NotAssociatedWithAging

In [25]:
file_metabolites['relation'].value_counts()

relation
NotAssociatedWithAging           317
NegativelyAssociatedWithAging    228
PositivelyAssociatedWithAging     45
Name: count, dtype: int64

In [26]:
# Fix GO term
file_metabolites['Tail']             = 'GO:0007568'
file_metabolites['Tail_detail_name'] = 'aging'
file_metabolites['Tail_type']        = 'BiologicalProcess'
file_metabolites['Data_type']        = 'Associative'
file_metabolites

/tmp/ipykernel_2545539/671448937.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file_metabolites['Tail']             = 'GO:0007568'
/tmp/ipykernel_2545539/671448937.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file_metabolites['Tail_detail_name'] = 'aging'
/tmp/ipykernel_2545539/671448937.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file_metabolites['Tail_type']        = 'BiologicalProcess'
/tmp/ipykernel_2545539/671448937.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file_metabolites['Data_type']        = 'Associative'

,Biochemical,Species,Cell/Tissue,Treatment,Log2 FC,P,P adjust,Super Pathway,Sub Pathway,COMP ID,...,KEGG,HMDB,Head,Head_detail_name,Head_SMILE_name,relation,Tail,Tail_detail_name,Tail_type,Data_type
1,erucate (22:1n9),Macaca fascicularis,Plasma,Young VS Old,0.661547,0.049729,NaN,Lipid,Long Chain Monounsaturated Fatty Acid,1552,...,C08316,HMDB02068,5281116,(Z)-docos-13-enoic acid,CCCCCCCC/C=C\CCCCCCCCCCCC(=O)O,NotAssociatedWithAging,GO:0007568,aging,BiologicalProcess,Associative
2,1-carboxyethylphenylalanine,Macaca fascicularis,Brain,Young VS Old,-0.496104,0.049662,NaN,Amino Acid,Phenylalanine Metabolism,62566,...,NaN,NaN,127261991,(2S)-2-[[(1R)-1-carboxyethyl]amino]-3-phenylpr...,C[C@H](C(=O)O)N[C@@H](CC1=CC=CC=C1)C(=O)O,NotAssociatedWithAging,GO:0007568,aging,BiologicalProcess,Associative
3,4-ethylphenyl sulfate,Macaca fascicularis,Kidney,Young VS Old,-2.860170,0.049630,NaN,Xenobiotics,Benzoate Metabolism,36099,...,C13637,HMDB62551,20822574,(4-ethylphenyl) hydrogen sulfate,CCC1=CC=C(C=C1)OS(=O)(=O)O,PositivelyAssociatedWithAging,GO:0007568,aging,BiologicalProcess,Associative
6,glucose 6-phosphate,Macaca fascicularis,White adipose tissue,Young VS Old,2.860500,0.049167,NaN,Carbohydrate,"Glycolysis, Gluconeogenesis, and Pyruvate Meta...",31260,...,C00668,HMDB01401,5958,"[(2R,3S,4S,5R)-3,4,5,6-tetrahydroxyoxan-2-yl]m...",C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)OP(=O...,NegativelyAssociatedWithAging,GO:0007568,aging,BiologicalProcess,Associative
7,glycerate,Macaca fascicularis,White adipose tissue,Young VS Old,2.111790,0.048887,NaN,Carbohydrate,"Glycolysis, Gluconeogenesis, and Pyruvate Meta...",1572,...,C00258,HMDB00139,5460358,"(2R)-2,3-dihydroxypropanoate",C([C@H](C(=O)[O-])O)O,NegativelyAssociatedWithAging,GO:0007568,aging,BiologicalProcess,Associative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,"N6,N6-dimethyllysine",Macaca fascicularis,Kidney,Young VS Old,1.606340,0.000124,NaN,Amino Acid,Lysine Metabolism,62862,...,C05545,HMDB13287,193344,(2S)-2-amino-6-(dimethylamino)hexanoic acid,CN(C)CCCC[C@@H](C(=O)O)N,NegativelyAssociatedWithAging,GO:0007568,aging,BiologicalProcess,Associative
945,phenylalanine,Macaca fascicularis,Liver,Young VS Old,0.634935,0.000110,NaN,Amino Acid,Phenylalanine Metabolism,64,...,C00079,HMDB00159,6140,(2S)-2-amino-3-phenylpropanoic acid,C1=CC=C(C=C1)C[C@@H](C(=O)O)N,NotAssociatedWithAging,GO:0007568,aging,BiologicalProcess,Associative
951,tyrosylglycine,Macaca fascicularis,Liver,Young VS Old,1.604100,0.000086,NaN,Peptide,Dipeptide,41375,...,NaN,HMDB29105,7021854,2-[[(2S)-2-amino-3-(4-hydroxyphenyl)propanoyl]...,C1=CC(=CC=C1C[C@@H](C(=O)NCC(=O)O)N)O,NegativelyAssociatedWithAging,GO:0007568,aging,BiologicalProcess,Associative
954,indole-3-carboxylate,Macaca fascicularis,Plasma,Young VS Old,1.424300,0.000067,NaN,Amino Acid,Tryptophan Metabolism,38116,...,C19837,HMDB03320,6932058,1H-indole-3-carboxylate,C1=CC=C2C(=C1)C(=CN2)C(=O)[O-],NegativelyAssociatedWithAging,GO:0007568,aging,BiologicalProcess,Associative
966,anthranilate,Macaca fascicularis,Liver,Young VS Old,0.939261,0.000035,NaN,Amino Acid,Tryptophan Metabolism,4970,...,C00108,HMDB01123,5459842,2-aminobenzoate,C1=CC=C(C(=C1)C(=O)[O-])N,NotAssociatedWithAging,GO:0007568,aging,BiologicalProcess,Associative

In [27]:
# Rename, add type/relation/source columns
file_metabolites = file_metabolites.rename(columns={'Biochemical': 'Head_Alt_name'})

file_metabolites['Head_type']       = 'ChemicalEntity'
file_metabolites['Tail_type']       = 'BiologicalProcess'
file_metabolites['Relation']        = file_metabolites['relation']
file_metabolites['Relation_Source'] = 'Aging_Atlas_Metabolites'
file_metabolites['Data_type']       = 'Associative'

desired_order = [
    'Head', 'Relation', 'Tail', 'Head_type', 'Tail_type',
    'Head_detail_name', 'Head_SMILE_name',
    'Relation_Source', 'Species', 'Head_Alt_name',
    'Cell/Tissue', 'Treatment', 'Log2 FC', 'P'
]
existing_cols = [c for c in desired_order if c in file_metabolites.columns]
file_metabolites = file_metabolites[existing_cols]
file_metabolites

,Head,Relation,Tail,Head_type,Tail_type,Head_detail_name,Head_SMILE_name,Relation_Source,Species,Head_Alt_name,Cell/Tissue,Treatment,Log2 FC,P
1,5281116,NotAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,(Z)-docos-13-enoic acid,CCCCCCCC/C=C\CCCCCCCCCCCC(=O)O,Aging_Atlas_Metabolites,Macaca fascicularis,erucate (22:1n9),Plasma,Young VS Old,0.661547,0.049729
2,127261991,NotAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-[[(1R)-1-carboxyethyl]amino]-3-phenylpr...,C[C@H](C(=O)O)N[C@@H](CC1=CC=CC=C1)C(=O)O,Aging_Atlas_Metabolites,Macaca fascicularis,1-carboxyethylphenylalanine,Brain,Young VS Old,-0.496104,0.049662
3,20822574,PositivelyAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,(4-ethylphenyl) hydrogen sulfate,CCC1=CC=C(C=C1)OS(=O)(=O)O,Aging_Atlas_Metabolites,Macaca fascicularis,4-ethylphenyl sulfate,Kidney,Young VS Old,-2.860170,0.049630
6,5958,NegativelyAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,"[(2R,3S,4S,5R)-3,4,5,6-tetrahydroxyoxan-2-yl]m...",C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)OP(=O...,Aging_Atlas_Metabolites,Macaca fascicularis,glucose 6-phosphate,White adipose tissue,Young VS Old,2.860500,0.049167
7,5460358,NegativelyAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2,3-dihydroxypropanoate",C([C@H](C(=O)[O-])O)O,Aging_Atlas_Metabolites,Macaca fascicularis,glycerate,White adipose tissue,Young VS Old,2.111790,0.048887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,193344,NegativelyAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-amino-6-(dimethylamino)hexanoic acid,CN(C)CCCC[C@@H](C(=O)O)N,Aging_Atlas_Metabolites,Macaca fascicularis,"N6,N6-dimethyllysine",Kidney,Young VS Old,1.606340,0.000124
945,6140,NotAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-amino-3-phenylpropanoic acid,C1=CC=C(C=C1)C[C@@H](C(=O)O)N,Aging_Atlas_Metabolites,Macaca fascicularis,phenylalanine,Liver,Young VS Old,0.634935,0.000110
951,7021854,NegativelyAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,2-[[(2S)-2-amino-3-(4-hydroxyphenyl)propanoyl]...,C1=CC(=CC=C1C[C@@H](C(=O)NCC(=O)O)N)O,Aging_Atlas_Metabolites,Macaca fascicularis,tyrosylglycine,Liver,Young VS Old,1.604100,0.000086
954,6932058,NegativelyAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,1H-indole-3-carboxylate,C1=CC=C2C(=C1)C(=CN2)C(=O)[O-],Aging_Atlas_Metabolites,Macaca fascicularis,indole-3-carboxylate,Plasma,Young VS Old,1.424300,0.000067
966,5459842,NotAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,2-aminobenzoate,C1=CC=C(C(=C1)C(=O)[O-])N,Aging_Atlas_Metabolites,Macaca fascicularis,anthranilate,Liver,Young VS Old,0.939261,0.000035

In [28]:
print("Relation counts:")
print(file_metabolites['Relation'].value_counts())

Relation counts:
Relation
NotAssociatedWithAging           317
NegativelyAssociatedWithAging    228
PositivelyAssociatedWithAging     45
Name: count, dtype: int64

In [29]:
file_metabolites_save = file_metabolites
file_metabolites_save

,Head,Relation,Tail,Head_type,Tail_type,Head_detail_name,Head_SMILE_name,Relation_Source,Species,Head_Alt_name,Cell/Tissue,Treatment,Log2 FC,P
1,5281116,NotAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,(Z)-docos-13-enoic acid,CCCCCCCC/C=C\CCCCCCCCCCCC(=O)O,Aging_Atlas_Metabolites,Macaca fascicularis,erucate (22:1n9),Plasma,Young VS Old,0.661547,0.049729
2,127261991,NotAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-[[(1R)-1-carboxyethyl]amino]-3-phenylpr...,C[C@H](C(=O)O)N[C@@H](CC1=CC=CC=C1)C(=O)O,Aging_Atlas_Metabolites,Macaca fascicularis,1-carboxyethylphenylalanine,Brain,Young VS Old,-0.496104,0.049662
3,20822574,PositivelyAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,(4-ethylphenyl) hydrogen sulfate,CCC1=CC=C(C=C1)OS(=O)(=O)O,Aging_Atlas_Metabolites,Macaca fascicularis,4-ethylphenyl sulfate,Kidney,Young VS Old,-2.860170,0.049630
6,5958,NegativelyAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,"[(2R,3S,4S,5R)-3,4,5,6-tetrahydroxyoxan-2-yl]m...",C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)OP(=O...,Aging_Atlas_Metabolites,Macaca fascicularis,glucose 6-phosphate,White adipose tissue,Young VS Old,2.860500,0.049167
7,5460358,NegativelyAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2,3-dihydroxypropanoate",C([C@H](C(=O)[O-])O)O,Aging_Atlas_Metabolites,Macaca fascicularis,glycerate,White adipose tissue,Young VS Old,2.111790,0.048887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,193344,NegativelyAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-amino-6-(dimethylamino)hexanoic acid,CN(C)CCCC[C@@H](C(=O)O)N,Aging_Atlas_Metabolites,Macaca fascicularis,"N6,N6-dimethyllysine",Kidney,Young VS Old,1.606340,0.000124
945,6140,NotAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-amino-3-phenylpropanoic acid,C1=CC=C(C=C1)C[C@@H](C(=O)O)N,Aging_Atlas_Metabolites,Macaca fascicularis,phenylalanine,Liver,Young VS Old,0.634935,0.000110
951,7021854,NegativelyAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,2-[[(2S)-2-amino-3-(4-hydroxyphenyl)propanoyl]...,C1=CC(=CC=C1C[C@@H](C(=O)NCC(=O)O)N)O,Aging_Atlas_Metabolites,Macaca fascicularis,tyrosylglycine,Liver,Young VS Old,1.604100,0.000086
954,6932058,NegativelyAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,1H-indole-3-carboxylate,C1=CC=C2C(=C1)C(=CN2)C(=O)[O-],Aging_Atlas_Metabolites,Macaca fascicularis,indole-3-carboxylate,Plasma,Young VS Old,1.424300,0.000067
966,5459842,NotAssociatedWithAging,GO:0007568,ChemicalEntity,BiologicalProcess,2-aminobenzoate,C1=CC=C(C(=C1)C(=O)[O-])N,Aging_Atlas_Metabolites,Macaca fascicularis,anthranilate,Liver,Young VS Old,0.939261,0.000035

## Export — Metabolites (Human only)

In [30]:

print(file_metabolites['Relation'].value_counts())

Human_Positiveassociation  = file_metabolites[file_metabolites['Relation'] == 'PositivelyAssociatedWithAging']
Human_Negativeassociation  = file_metabolites[file_metabolites['Relation'] == 'NegativelyAssociatedWithAging']

Human_Positiveassociation.to_csv( os.path.join(OUT_HUMAN, 'ChemicalEntity_PositivelyAssociatedWithAging_BiologicalProcess_Metabolites.csv'),  index=False)
Human_Negativeassociation.to_csv( os.path.join(OUT_HUMAN, 'ChemicalEntity_NegativelyAssociatedWithAging_BiologicalProcess_Metabolites.csv'), index=False)
print(f"Saved → {OUT_HUMAN}")

Relation
NotAssociatedWithAging           317
NegativelyAssociatedWithAging    228
PositivelyAssociatedWithAging     45
Name: count, dtype: int64
Saved → /storage/Arushi/090526_EvoAge/kg_formation/processed_data/agingatlas/Human/

In [31]:
# # Final summary of all output files
# print("\n=== Output files written ===")
# for root, dirs, files in os.walk(OUT_PATH):
#     for f in sorted(files):
#         full = os.path.join(root, f)
#         size = os.path.getsize(full)
#         print(f"  {full}  ({size:,} bytes)")

In [32]:
# !wc -l /storage/Arushi/090526_EvoAge/kg_formation/processed_data/agingatlas/*/*.csv

In [33]:
# !ls /storage/Arushi/090526_EvoAge/kg_formation/processed_data/agingatlas/*/*.csv

# Part 3 — Age-related Genes

In [34]:
human_aging_atlas_genes = pd.read_csv(
    f'{BASE_PATH}agingatlas/Aging_atlas_human_agingrelated_genes.csv',
    encoding='latin1'
)

human_aging_atlas_genes
print(f"Raw: {len(human_aging_atlas_genes):,} rows")
print("Species:", set(human_aging_atlas_genes['Species']))

human_aging_atlas_genes

# ── Build KG triples from Aging Atlas Gene-Set data ───────────────────────────

# Filter to Human only
human_aging_atlas_genes = human_aging_atlas_genes[human_aging_atlas_genes['Species'] == 'Homo sapiens'].copy()

# ── Assign columns ────────────────────────────────────────────────────────────
human_aging_atlas_genes['Head']             = human_aging_atlas_genes['Symbol']
human_aging_atlas_genes['Head_detail_name'] = human_aging_atlas_genes['Description']
human_aging_atlas_genes['Head_type']        = 'Gene'
human_aging_atlas_genes['Head_ID_IS']       = 'NCBI_ID'

human_aging_atlas_genes['Relation']         = 'Gene_BiologicalProcess'
human_aging_atlas_genes['Relation_Source']  = 'aging_atlas'

human_aging_atlas_genes['Tail']             = 'GO:0007568'
human_aging_atlas_genes['Tail_detail_name'] = 'aging'
human_aging_atlas_genes['Tail_type']        = 'BiologicalProcess'
human_aging_atlas_genes['Tail_ID_IS']       = 'QuickGO_ID'

human_aging_atlas_genes['Species']          = 'H.sapiens'
human_aging_atlas_genes['Data_type']        = 'Associative'


# ── Select final columns ──────────────────────────────────────────────────────
desired_cols = [
    'Head', 'Relation', 'Tail',
    'Head_type', 'Tail_type',
    'Head_detail_name', 'Tail_detail_name',
    'Head_ID_IS', 'Tail_ID_IS',
    'Relation_Source', 'Species',
    'Symbol', 'Gene_Set', 'KEGG_ID', 'KEGG_Name',
    'Literature_Name', 'Literature_Link',
    'Data_type'
]

human_aging_atlas_genes = human_aging_atlas_genes[[c for c in desired_cols if c in human_aging_atlas_genes.columns]]

print(f"Shape: {human_aging_atlas_genes.shape}")
print(human_aging_atlas_genes['Relation'].value_counts())
human_aging_atlas_genes

Raw: 503 rows
Species: {'Homo sapiens'}
Shape: (503, 18)
Relation
Gene_BiologicalProcess    503
Name: count, dtype: int64

,Head,Relation,Tail,Head_type,Tail_type,Head_detail_name,Tail_detail_name,Head_ID_IS,Tail_ID_IS,Relation_Source,Species,Symbol,Gene_Set,KEGG_ID,KEGG_Name,Literature_Name,Literature_Link,Data_type
0,IL2RB,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Interleukin 2 Receptor Subunit Beta,aging,NCBI_ID,QuickGO_ID,aging_atlas,H.sapiens,IL2RB,others,hsa04060,Cytokine-cytokine receptor interaction,Defective CD8 Signaling Pathways Delay Rejecti...,10.1097/TP.0000000000000886,Associative
1,PSAT1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Phosphoserine Aminotransferase 1,aging,NCBI_ID,QuickGO_ID,aging_atlas,H.sapiens,PSAT1,others,hsa00260 hsa00260,"Glycine, serine and threonine metabolism",Serine Metabolism Controls Dental Pulp Stem Ce...,10.1177/0022034520958374,Associative
2,A2M,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,alpha-2-macroglobulin,aging,NCBI_ID,QuickGO_ID,aging_atlas,H.sapiens,A2M,others,unknown,Unknown,Alpha-2 Macroglobulin Is Genetically Associate...,10.1038/1243,Associative
3,AARS1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Alanyl-TRNA Synthetase 1,aging,NCBI_ID,QuickGO_ID,aging_atlas,H.sapiens,AARS1,loss of proteostasis,hsa00970,Aminoacyl-tRNA biosynthesis,Altered Sensory Neuron Development in CMT2D Mi...,10.3389/fncel.2020.00232,Associative
4,ABL1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"ABL proto-oncogene 1, non-receptor tyrosine ki...",aging,NCBI_ID,QuickGO_ID,aging_atlas,H.sapiens,ABL1,genomic instability,hsa04110,Cell cycle,p73 Is Regulated by Tyrosine Kinase c-Abl in t...,10.1038/21704,Associative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,XRCC5,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,X-ray repair complementing defective repair in...,aging,NCBI_ID,QuickGO_ID,aging_atlas,H.sapiens,XRCC5,telomere attrition,unknown,Unknown,Human Ku70/80 Associates Physically With Telom...,10.1074/jbc.M208542200,Associative
499,XRCC6,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,X-ray repair complementing defective repair in...,aging,NCBI_ID,QuickGO_ID,aging_atlas,H.sapiens,XRCC6,others,unknown,Unknown,Human Ku70/80 associates physically with telom...,10.1074/jbc.M208542200,Associative
500,YWHAZ,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,tyrosine 3-monooxygenase/tryptophan 5-monooxyg...,aging,NCBI_ID,QuickGO_ID,aging_atlas,H.sapiens,YWHAZ,stem cell exhaustion,hsa04110,Cell cycle,Proteomic Analysis Identifies That 14-3-3zeta ...,10.1073/pnas.0406499101,Associative
501,ZAP70,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Zeta Chain Of T Cell Receptor Associated Prote...,aging,NCBI_ID,QuickGO_ID,aging_atlas,H.sapiens,ZAP70,NF-?B related gene,hsa04064,NF-kappa B signaling pathway,Otud7b facilitates T cell activation and infla...,10.1084/jem.20151426,Associative
502,ZMPSTE24,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc metallopeptidase STE24,aging,NCBI_ID,QuickGO_ID,aging_atlas,H.sapiens,ZMPSTE24,genomic instability,unknown,Unknown,Loss of ZMPSTE24 (FACE-1) Causes Autosomal Rec...,10.1093/hmg/ddi159,Associative

In [35]:
OUT_HUMAN

'/storage/Arushi/090526_EvoAge/kg_formation/processed_data/agingatlas/Human/'

In [36]:
human_aging_atlas_genes.to_csv( os.path.join(OUT_HUMAN, 'Human_Gene_BiologicalProcess.csv'),  index=False)

In [37]:
mouse_aging_atlas_genes = pd.read_csv(
    f'{BASE_PATH}agingatlas/Aging_atlas_mouse_agingrelated_genes.csv',
    encoding='latin1'
)

mouse_aging_atlas_genes
print(f"Raw: {len(mouse_aging_atlas_genes):,} rows")
print("Species:", set(mouse_aging_atlas_genes['Species']))

mouse_aging_atlas_genes

# ── Build KG triples from Aging Atlas Gene-Set data ───────────────────────────

# Filter to Human only
mouse_aging_atlas_genes = mouse_aging_atlas_genes[mouse_aging_atlas_genes['Species'] == 'Mus musculus'].copy()

# ── Assign columns ────────────────────────────────────────────────────────────
mouse_aging_atlas_genes['Head']             = mouse_aging_atlas_genes['Symbol']
mouse_aging_atlas_genes['Head_detail_name'] = mouse_aging_atlas_genes['Description']
mouse_aging_atlas_genes['Head_type']        = 'Gene'
mouse_aging_atlas_genes['Head_ID_IS']       = 'NCBI_ID'

mouse_aging_atlas_genes['Relation']         = 'Gene_BiologicalProcess'
mouse_aging_atlas_genes['Relation_Source']  = 'aging_atlas'

mouse_aging_atlas_genes['Tail']             = 'GO:0007568'
mouse_aging_atlas_genes['Tail_detail_name'] = 'aging'
mouse_aging_atlas_genes['Tail_type']        = 'BiologicalProcess'
mouse_aging_atlas_genes['Tail_ID_IS']       = 'QuickGO_ID'

mouse_aging_atlas_genes['Species']          = 'M.musculus'
mouse_aging_atlas_genes['Data_type']        = 'Associative'


# ── Select final columns ──────────────────────────────────────────────────────
desired_cols = [
    'Head', 'Relation', 'Tail',
    'Head_type', 'Tail_type',
    'Head_detail_name', 'Tail_detail_name',
    'Head_ID_IS', 'Tail_ID_IS',
    'Relation_Source', 'Species',
    'Symbol', 'Gene_Set', 'KEGG_ID', 'KEGG_Name',
    'Literature_Name', 'Literature_Link',
    'Data_type'
]

mouse_aging_atlas_genes = mouse_aging_atlas_genes[[c for c in desired_cols if c in mouse_aging_atlas_genes.columns]]

print(f"Shape: {mouse_aging_atlas_genes.shape}")
print(mouse_aging_atlas_genes['Relation'].value_counts())
mouse_aging_atlas_genes

Raw: 400 rows
Species: {'Mus musculus'}
Shape: (400, 18)
Relation
Gene_BiologicalProcess    400
Name: count, dtype: int64

,Head,Relation,Tail,Head_type,Tail_type,Head_detail_name,Tail_detail_name,Head_ID_IS,Tail_ID_IS,Relation_Source,Species,Symbol,Gene_Set,KEGG_ID,KEGG_Name,Literature_Name,Literature_Link,Data_type
0,A2m,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,alpha-2-macroglobulin,aging,NCBI_ID,QuickGO_ID,aging_atlas,M.musculus,A2m,others,unknown,Unknown,The primary sequence and the subunit structure...,10.1111/j.1432-1033.1992.tb17424.x,Associative
1,Abl1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"c-abl oncogene 1, non-receptor tyrosine kinase",aging,NCBI_ID,QuickGO_ID,aging_atlas,M.musculus,Abl1,genomic instability,mmu04110,Cell cycle,Functional interaction between DNA-PK and c-Ab...,10.1038/386732a0,Associative
2,Adcy1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,adenylate cyclase 1,aging,NCBI_ID,QuickGO_ID,aging_atlas,M.musculus,Adcy1,altered intercellular communication,mmu04211,Longevity regulating pathway,Loss of adenylyl cyclase I activity disrupts p...,10.1038/980,Associative
3,Adcy2,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,adenylate cyclase 2,aging,NCBI_ID,QuickGO_ID,aging_atlas,M.musculus,Adcy2,altered intercellular communication,mmu04211,Longevity regulating pathway,BGEM: an in situ hybridization database of gen...,10.1371/journal.pbio.0040086,Associative
4,Adcy3,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,adenylate cyclase 3,aging,NCBI_ID,QuickGO_ID,aging_atlas,M.musculus,Adcy3,altered intercellular communication,mmu04211,Longevity regulating pathway,Disruption of the type III adenylyl cyclase ge...,10.1016/s0896-6273(00)00060-x,Associative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Stub1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Stip1 homology and U-Box containing protein 1,aging,NCBI_ID,QuickGO_ID,aging_atlas,M.musculus,Stub1,loss of proteostasis,unknown,Unknown,Age-related expression of STUB1 in senescence-...,10.1126/science.1102895,Associative
396,Sumf1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Sulfatase Modifying Factor 1,aging,NCBI_ID,QuickGO_ID,aging_atlas,M.musculus,Sumf1,others,mmu04142,Lysosome,High-throughput screening of mouse gene knocko...,0.1038/boneres.2014.34,Associative
397,Sumo1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,small ubiquitin-like modifier 1,aging,NCBI_ID,QuickGO_ID,aging_atlas,M.musculus,Sumo1,genomic instability,unknown,Unknown,SUMO-1 Conjugation to Topoisomerase I: A Possi...,10.1126/science.1102896,Associative
398,Sun1,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Sad1 and UNC84 domain containing 1,aging,NCBI_ID,QuickGO_ID,aging_atlas,M.musculus,Sun1,others,unknown,Unknown,Reversal of laminopathies: the curious case of...,10.1126/science.1102897,Associative
399,Syk,Gene_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,spleen tyrosine kinase,aging,NCBI_ID,QuickGO_ID,aging_atlas,M.musculus,Syk,NF-ÎºB related gene,mmu04064,NF-kappa B signaling pathway,miR-25-3p promotes endothelial cell angiogenes...,10.18632/aging.103834,Associative

In [38]:
mouse_aging_atlas_genes.to_csv( os.path.join(OUT_MOUSE, 'Mouse_Gene_BiologicalProcess.csv'),  index=False)

In [67]:
#