In [1]:
import pandas as pd
import numpy as np

In [3]:
BASE_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/data_collection/"
OUT_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/processed_data/stitch"

In [5]:
# BTO 
BTO = pd.read_csv(f'{BASE_PATH}databases_for_mapping/bto/Tissue.tsv', sep = '\t')
BTO
BTO_Dict  = dict(zip(BTO['name'], BTO['ID']))
BTO_Dict

{'tissues, cell types and enzyme sources': 'BTO:0000000',
 'culture condition:-induced cell': 'BTO:0000001',
 'culture condition:1,4-dichlorobenzene-grown cell': 'BTO:0000002',
 'intestinal cell line': 'BTO:0000003',
 'culture condition:2,5-dihydroxybenzoate-grown cell': 'BTO:0000004',
 'culture condition:2-aminobenzenesulfonate-grown cell': 'BTO:0000005',
 'osteoblastoma cell': 'BTO:0000006',
 'HEK-293 cell': 'BTO:0000007',
 'culture condition:3-chlorobenzoate-grown cell': 'BTO:0000008',
 'culture condition:3-hydroxybenzoate-grown cell': 'BTO:0000009',
 'culture condition:3-methylcrotonoyl-CoA-grown cell': 'BTO:0000010',
 '3T3-L1 cell': 'BTO:0000011',
 'culture condition:4-(methoxymethyl)phenol-grown cell': 'BTO:0000012',
 'culture condition:4-chlorophenol-grown cell': 'BTO:0000013',
 'culture condition:4-hydroxybenzoate-grown cell': 'BTO:0000014',
 'culture condition:4-methylmuconolactone-grown cell': 'BTO:0000015',
 'A-172 cell': 'BTO:0000016',
 'A-431 cell': 'BTO:0000017',
 'A-549 cell': 'BTO:0000018',
 'A7r5 cell': 'BTO:0000019',
 'abdomen': 'BTO:0000020',
 'head muscle': 'BTO:0000021',
 'abdominal ganglion': 'BTO:0000022',
 'pectoral muscle': 'BTO:0000023',
 'abomasum': 'BTO:0000024',
 'amniotic cavity': 'BTO:0000025',
 'culture condition:galactose-grown cell': 'BTO:0000026',
 'achene': 'BTO:0000027',
 'pancreatic acinar cell': 'BTO:0000028',
 'adductor longus': 'BTO:0000029',
 'adductor': 'BTO:0000030',
 'fruit peduncle': 'BTO:0000031',
 'colonic adenocarcinoma cell': 'BTO:0000032',
 'SW-403 cell': 'BTO:0000033',
 'apical meristem': 'BTO:0000034',
 'colorectal adenocarcinoma cell': 'BTO:0000035',
 'gastric adenocarcinoma cell': 'BTO:0000036',
 'renal cell carcinoma cell': 'BTO:0000037',
 'SW-480 cell': 'BTO:0000038',
 'root cap': 'BTO:0000039',
 'adenohypophysis': 'BTO:0000040',
 'medulla oblongata': 'BTO:0000041',
 'animal': 'BTO:0000042',
 'cerebellar cortex': 'BTO:0000043',
 'tear gland': 'BTO:0000044',
 'adrenal cortex': 'BTO:0000045',
 'Y-1 cell': 'BTO:0000046',
 'adrenal gland': 'BTO:0000047',
 'zona glomerulosa': 'BTO:0000048',
 'adrenal medulla': 'BTO:0000049',
 'zona fasciculata': 'BTO:0000050',
 'tendon sheath': 'BTO:0000051',
 'stoma': 'BTO:0000052',
 'albedo': 'BTO:0000053',
 'albumen gland': 'BTO:0000054',
 'pars recta': 'BTO:0000055',
 'zona reticulata': 'BTO:0000056',
 'aleurone layer': 'BTO:0000057',
 'alimentary canal': 'BTO:0000058',
 'renal epithelium': 'BTO:0000059',
 'alveolus': 'BTO:0000060',
 'alveolar sac': 'BTO:0000061',
 'amastigote': 'BTO:0000062',
 'culture condition:ammonium malate-grown cell': 'BTO:0000063',
 'amniochorion': 'BTO:0000064',
 'amnion': 'BTO:0000065',
 'amniocyte': 'BTO:0000066',
 'kidney cell line': 'BTO:0000067',
 'amniotic fluid': 'BTO:0000068',
 'WISH cell': 'BTO:0000069',
 'fungal cell line': 'BTO:0000070',
 'amoebocyte': 'BTO:0000071',
 'carpel': 'BTO:0000072',
 'culture condition:aniline-grown cell': 'BTO:0000073',
 'antenna': 'BTO:0000074',
 'antennal gland': 'BTO:0000075',
 'anterior midgut': 'BTO:0000076',
 'posterior midgut': 'BTO:0000077',
 'microglia': 'BTO:0000078',
 'anther': 'BTO:0000079',
 'male reproductive gland': 'BTO:0000080',
 'reproductive system': 'BTO:0000081',
 'male reproductive system': 'BTO:0000082',
 'female reproductive system': 'BTO:0000083',
 'vermiform appendix': 'BTO:0000084',
 'appressorium': 'BTO:0000085',
 'culture condition:arabinose-grown cell': 'BTO:0000086',
 'arterial smooth muscle': 'BTO:0000087',
 'cardiovascular system': 'BTO:0000088',
 'blood': 'BTO:0000089',
 'ascidian': 'BTO:0000090',
 'ascites': 'BTO:0000091',
 'trypanosomoid form': 'BTO:0000092',
 'MCF-7 cell': 'BTO:0000093',
 'ascites tumor cell': 'BTO:0000094',
 'F-9 cell': 'BTO:0000095',
 'urinary bladder cell line': 'BTO:0000096',
 'ascospore': 'BTO:0000097',
 'astroblast': 'BTO:0000098',
 'astrocyte': 'BTO:0000099',
 'astrocytoma cell': 'BTO:0000100',
 'astrocytoma cell line': 'BTO:0000101',
 'blood clot': 'BTO:0000102',
 'Colon 26-L5 cell': 'BTO:0000103',
 'lymphoma cell line': 'BTO:0000104',
 'upper epidermis': 'BTO:0000105',
 'cranial ganglion': 'BTO:0000106',
 'B95-8 cell': 'BTO:0000107',
 'olfactory epithelium': 'BTO:0000108',
 'bacteroid': 'BTO:0000109',
 'amniotic cell line': 'BTO:0000110',
 'BALB/3T12-3 cell': 'BTO:0000111',
 'sieve cell': 'BTO:0000112',
 'cervical ganglion': 'BTO:0000113',
 'basidiocarp': 'BTO:0000114',
 'BC3H1 cell': 'BTO:0000115',
 'plant epidermis': 'BTO:0000116',
 'culture condition:benzoate-grown cell': 'BTO:0000117',
 'culture condition:benzoylformate-grown cell': 'BTO:0000118',
 'berry': 'BTO:0000119',
 'BHK-21 cell': 'BTO:0000120',
 'bile': 'BTO:0000121',
 'bile duct': 'BTO:0000122',
 'bladder': 'BTO:0000123',
 'microspore': 'BTO:0000124',
 'blast cell': 'BTO:0000125',
 'blastoderm': 'BTO:0000126',
 'blastospore': 'BTO:0000127',
 'blastula': 'BTO:0000128',
 'basophil': 'BTO:0000129',
 'neutrophil': 'BTO:0000130',
 'blood plasma': 'BTO:0000131',
 'blood platelet': 'BTO:0000132',
 'blood serum': 'BTO:0000133',
 'bloodstream form': 'BTO:0000134',
 'aorta': 'BTO:0000135',
 'bronchoalveolar system': 'BTO:0000136',
 'pulmonary artery endothelium': 'BTO:0000137',
 'midbrain': 'BTO:0000138',
 'body wall': 'BTO:0000139',
 'bone': 'BTO:0000140',
 'bone marrow': 'BTO:0000141',
 'brain': 'BTO:0000142',
 'substantia nigra': 'BTO:0000143',
 'meninx': 'BTO:0000144',
 'brain myelin': 'BTO:0000145',
 'brain stem': 'BTO:0000146',
 'microgametophyte': 'BTO:0000147',
 'branch': 'BTO:0000148',
 'breast': 'BTO:0000149',
 'breast cancer cell': 'BTO:0000150',
 'extensor': 'BTO:0000151',
 'infected cell': 'BTO:0000152',
 'Walker carcinoma 256 cell': 'BTO:0000153',
 'BRL-3A cell': 'BTO:0000154',
 'bronchoalveolar lavage': 'BTO:0000155',
 'brown adipose tissue': 'BTO:0000156',
 'aorta thoracica': 'BTO:0000157',
 'plant bud': 'BTO:0000158',
 'bulb': 'BTO:0000159',
 'bundle sheath': 'BTO:0000160',
 'lung fibroblast cell line': 'BTO:0000161',
 'culture condition:butyrate-grown cell': 'BTO:0000162',
 'corolla': 'BTO:0000163',
 'Burkitt lymphoma cell': 'BTO:0000164',
 'C2C12 cell': 'BTO:0000165',
 'cecum': 'BTO:0000166',
 'adenocarcinoma cell line': 'BTO:0000167',
 'carotid artery': 'BTO:0000168',
 'calyx': 'BTO:0000169',
 'cambium': 'BTO:0000170',
 'NCI-H226Br cell': 'BTO:0000171',
 'pileus': 'BTO:0000172',
 'fruit capsule': 'BTO:0000173',
 'embryonic structure': 'BTO:0000174',
 'epithalamus': 'BTO:0000175',
 'carcinoma cell': 'BTO:0000176',
 'BG-1 cell': 'BTO:0000177',
 'adenoma cell': 'BTO:0000178',
 'Colo-205 cell': 'BTO:0000179',
 'cervical carcinoma cell': 'BTO:0000180',
 'Lewis lung carcinoma cell line': 'BTO:0000181',
 'HT-29 cell': 'BTO:0000182',
 'pancreatic cell line': 'BTO:0000183',
 'medullary thyroid carcinoma cell': 'BTO:0000184',
 'medullary breast carcinoma cell': 'BTO:0000185',
 'lobular carcinoma cell': 'BTO:0000186',
 'myeloblast': 'BTO:0000187',
 'colonic cell line': 'BTO:0000188',
 'small cell lung cancer cell': 'BTO:0000189',
 'Ehrlich tumor carcinoma cell': 'BTO:0000190',
 'medullary carcinoma cell': 'BTO:0000191',
 'nasopharyngeal carcinoma cell': 'BTO:0000192',
 'rectal cancer cell': 'BTO:0000193',
 'endometrioid carcinoma cell': 'BTO:0000194',
 'CACO-2 cell': 'BTO:0000195',
 'thyroid cancer cell': 'BTO:0000196',
 'carcinosarcoma cell': 'BTO:0000197',
 'cardia': 'BTO:0000198',
 'cardiac muscle': 'BTO:0000199',
 'culture condition:2-chloropropionate-grown cell': 'BTO:0000200',
 'pheochromocytoma cell line': 'BTO:0000201',
 'sense organ': 'BTO:0000202',
 'respiratory system': 'BTO:0000203',
 'carotid body': 'BTO:0000204',
 'nerve plexus': 'BTO:0000205',
 'cartilage': 'BTO:0000206',
 'tibial cartilage': 'BTO:0000207',
 'caryopsis': 'BTO:0000208',
 'corpus epididymis': 'BTO:0000209',
 'cauda epididymis': 'BTO:0000210',
 'caudate nucleus': 'BTO:0000211',
 'caudate putamen': 'BTO:0000212',
 'cecum mucosa': 'BTO:0000213',
 'cell culture': 'BTO:0000214',
 'culture condition:galactonate-grown cell': 'BTO:0000215',
 'culture condition': 'BTO:0000216',
 'MH-7777A cell': 'BTO:0000217',
 'BALB/3T3 cell': 'BTO:0000218',
 'plastron': 'BTO:0000219',
 'MH1C1 cell': 'BTO:0000220',
 'cell suspension culture': 'BTO:0000221',
 'myoblast': 'BTO:0000222',
 'teratocarcinoma cell': 'BTO:0000223',
 'liver cell line': 'BTO:0000224',
 'CEM cell': 'BTO:0000225',
 'gitter cell': 'BTO:0000226',
 'central nervous system': 'BTO:0000227',
 'C-1300 cell': 'BTO:0000228',
 'centrum semiovale': 'BTO:0000229',
 'subarachnoid space': 'BTO:0000230',
 'cerebral hemisphere': 'BTO:0000231',
 'cerebellum': 'BTO:0000232',
 'cerebral cortex': 'BTO:0000233',
 'vein': 'BTO:0000234',
 'basal ganglion': 'BTO:0000235',
 'cerebral white matter': 'BTO:0000236',
 'cerebrospinal fluid': 'BTO:0000237',
 'cerebrovascular endothelial cell': 'BTO:0000238',
 'telencephalon': 'BTO:0000239',
 'inferior cervical ganglion': 'BTO:0000240',
 'cervical epithelium': 'BTO:0000241',
 'cervical mucus': 'BTO:0000242',
 'vagina': 'BTO:0000243',
 'culture condition:chlorobenzene-induced cell': 'BTO:0000244',
 'culture condition:chlorobenzoate-grown cell': 'BTO:0000245',
 'CHO cell': 'BTO:0000246',
 'shoot tip': 'BTO:0000247',
 'chondroclast': 'BTO:0000248',
 'chondrocyte': 'BTO:0000249',
 'chondrosarcoma cell': 'BTO:0000250',
 'chorioallantois': 'BTO:0000251',
 'chorion': 'BTO:0000252',
 'BEN cell': 'BTO:0000253',
 'female reproductive gland': 'BTO:0000254',
 'brain cell line': 'BTO:0000255',
 'myoblast cell line': 'BTO:0000256',
 'uterine cancer cell': 'BTO:0000257',
 'choroid plexus': 'BTO:0000258',
 'chromaffin cell': 'BTO:0000259',
 'ciliary body': 'BTO:0000260',
 'culture condition:mannitol-grown cell': 'BTO:0000261',
 'clove': 'BTO:0000262',
 'P-388D1(IL-1) cell': 'BTO:0000263',
 'bone marrow cell line': 'BTO:0000264',
 'coagulating gland': 'BTO:0000265',
 'cob': 'BTO:0000266',
 'cochlea': 'BTO:0000267',
 'coleoptile': 'BTO:0000268',
 'colon': 'BTO:0000269',
 'colon ascendens': 'BTO:0000270',
 'colonic mucosa': 'BTO:0000271',
 'colon transversum': 'BTO:0000272',
 'ink gland': 'BTO:0000273',
 'apical bud': 'BTO:0000274',
 'colonocyte': 'BTO:0000275',
 'colostrum': 'BTO:0000276',
 'columnella muscle': 'BTO:0000277',
 'commercial preparation': 'BTO:0000278',
 'testicular cancer cell': 'BTO:0000279',
 'cone': 'BTO:0000280',
 'conidiophore': 'BTO:0000281',
 'head': 'BTO:0000282',
 'conidium': 'BTO:0000283',
 'organism form': 'BTO:0000284',
 'corm': 'BTO:0000285',
 'cornea': 'BTO:0000286',
 'corneal epithelium': 'BTO:0000287',
 'corona': 'BTO:0000288',
 'cytotoxic T-lymphocyte': 'BTO:0000289',
 'coronary artery': 'BTO:0000290',
 'corpus allatum': 'BTO:0000291',
 'corpus luteum': 'BTO:0000292',
 'occipital lobe': 'BTO:0000293',
 'dermis': 'BTO:0000294',
 'WEHI-3 cell': 'BTO:0000295',
 'SW-1088 cell': 'BTO:0000296',
 'carcinoma cell line': 'BTO:0000297',
 'COS-7 cell': 'BTO:0000298',
 'cotton fibre': 'BTO:0000299',
 'cotyledon': 'BTO:0000300',
 'crop': 'BTO:0000301',
 'ring gland': 'BTO:0000302',
 'crown gall': 'BTO:0000303',
 'PANC-1 cell': 'BTO:0000304',
 'crypt': 'BTO:0000305',
 'teratocarcinoma cell line': 'BTO:0000306',
 'crystalline style': 'BTO:0000307',
 'cytotoxic T-lymphocyte cell line': 'BTO:0000308',
 'bundle sheath cell': 'BTO:0000309',
 'protophloem': 'BTO:0000310',
 'culture filtrate': 'BTO:0000311',
 'motoneuron': 'BTO:0000312',
 'hypodermis': 'BTO:0000313',
 'neuroepithelium': 'BTO:0000314',
 'ectoderm': 'BTO:0000315',
 'culture medium': 'BTO:0000316',
 'caulonema': 'BTO:0000317',
 'CV-1 cell': 'BTO:0000318',
 'culture condition:cyclohexanol-grown cell': 'BTO:0000319',
 'cyst': 'BTO:0000320',
 'plant cuticle': 'BTO:0000321',
 'cytotrophoblast': 'BTO:0000322',
 'culture condition:D-mandelate-grown cell': 'BTO:0000323',
 'culture condition:D-arabinose-induced cell': 'BTO:0000324',
 'culture condition:D-galactose-grown cell': 'BTO:0000325',
 'culture condition:D-lyxose-grown cell': 'BTO:0000326',
 'culture condition:D-mannose-grown cell': 'BTO:0000327',
 'culture condition:D-phenylglycine-grown cell': 'BTO:0000328',
 'culture condition:D-ribose-grown cell': 'BTO:0000329',
 'culture condition:D-ribose-induced cell': 'BTO:0000330',
 'L-929 cell': 'BTO:0000331',
 'culture condition:dark-grown cell': 'BTO:0000332',
 'renal corpuscle': 'BTO:0000333',
 'decidua parietalis': 'BTO:0000334',
 'deciduoma cell': 'BTO:0000335',
 'caput epididymis': 'BTO:0000336',
 'dental follicle': 'BTO:0000337',
 'dental plaque': 'BTO:0000338',
 'dental pulp': 'BTO:0000339',
 'culture condition:deoxyribonucleoside-induced cell': 'BTO:0000340',
 'diaphragm': 'BTO:0000341',
 'diencephalon': 'BTO:0000342',
 'renal tubule': 'BTO:0000343',
 'stratum corneum': 'BTO:0000344',
 'digestive gland': 'BTO:0000345',
 'digestive juice': 'BTO:0000346',
 'reticulum': 'BTO:0000347',
 'omasum': 'BTO:0000348',
 'gut cavity': 'BTO:0000349',
 'culture condition:dimethylamine-grown cell': 'BTO:0000350',
 'disc': 'BTO:0000351',
 'culture condition:DL-mandelate-grown cell': 'BTO:0000352',
 'lung cell line': 'BTO:0000353',
 'DON cell': 'BTO:0000354',
 'dormant eye': 'BTO:0000355',
 'breast cancer cell line': 'BTO:0000356',
 'nectary': 'BTO:0000357',
 'McA-RH7777 cell': 'BTO:0000358',
 'middle cervical ganglion': 'BTO:0000359',
 'posterior spinal root': 'BTO:0000360',
 'stratum granulosum': 'BTO:0000361',
 'urinary bladder cancer cell': 'BTO:0000362',
 'culture condition:dulcitol-grown cell': 'BTO:0000363',
 'stratum lucidum': 'BTO:0000364',
 'duodenum': 'BTO:0000365',
 'duodenal juice': 'BTO:0000366',
 'duodenal mucosa': 'BTO:0000367',
 'ear': 'BTO:0000368',
 'egg': 'BTO:0000369',
 'egg white': 'BTO:0000370',
 'egg yolk': 'BTO:0000371',
 'bone cancer cell': 'BTO:0000372',
 'Ehrlich ascites carcinoma cell': 'BTO:0000373',
 'bone cell line': 'BTO:0000374',
 'keratinocyte cell line': 'BTO:0000375',
 'electric organ': 'BTO:0000376',
 'elementary body': 'BTO:0000377',
 'elytron': 'BTO:0000378',
 'embryo': 'BTO:0000379',
 'embryonic axis': 'BTO:0000380',
 'embryonic blood': 'BTO:0000381',
 'Kc cell': 'BTO:0000382',
 'renal cell carcinoma cell line': 'BTO:0000383',
 'emulsin': 'BTO:0000384',
 'bone cancer cell line': 'BTO:0000385',
 'culture condition:(NH4)2SO4-grown cell': 'BTO:0000386',
 'endocardium': 'BTO:0000387',
 'endodermis': 'BTO:0000388',
 'mature ovarian follicle': 'BTO:0000389',
 'endosperm': 'BTO:0000390',
 'DLD-1 cell': 'BTO:0000391',
 'plasma cell': 'BTO:0000392',
 'endothelium': 'BTO:0000393',
 'aorta endothelium': 'BTO:0000394',
 'alveolar cell': 'BTO:0000395',
 'EAhy 926 cell': 'BTO:0000396',
 'tooth': 'BTO:0000397',
 'enterocyte': 'BTO:0000398',
 'eosinophil': 'BTO:0000399',
 'sarcoma cell line': 'BTO:0000400',
 'ependymal epithelium': 'BTO:0000401',
 'epicotyl': 'BTO:0000402',
 'mastocytoma cell line': 'BTO:0000403',
 'epidermis': 'BTO:0000404',
 'penis': 'BTO:0000405',
 'L-428 cell': 'BTO:0000406',
 'osteosarcoma cell line': 'BTO:0000407',
 'epididymis': 'BTO:0000408',
 'epimastigote': 'BTO:0000409',
 'immature ovarian follicle': 'BTO:0000410',
 'cervical mucosa': 'BTO:0000411',
 'epiphyseal growth plate': 'BTO:0000412',
 'epiphysis': 'BTO:0000413',
 'epithelial cell': 'BTO:0000414',
 'epithelioma cell': 'BTO:0000415',
 'epithelium': 'BTO:0000416',
 'bile duct epithelium': 'BTO:0000417',
 'neostriatum': 'BTO:0000418',
 'respiratory epithelium': 'BTO:0000419',
 'neck': 'BTO:0000420',
 'connective tissue': 'BTO:0000421',
 'vaginal epithelium': 'BTO:0000422',
 'epitrochlearis': 'BTO:0000423',
 'erythrocyte': 'BTO:0000424',
 'erythrocytic stage': 'BTO:0000425',
 'erythroleukemia cell': 'BTO:0000426',
 'pituitary gland cell line': 'BTO:0000427',
 'culture condition:ethanol-grown cell': 'BTO:0000428',
 'H69AR cell': 'BTO:0000429',
 'EUE cell': 'BTO:0000430',
 'excretory gland': 'BTO:0000431',
 'corpus cardiacum': 'BTO:0000432',
 'exocrine acinar cell': 'BTO:0000433',
 'exocrine pancreas': 'BTO:0000434',
 'stratum spinosum': 'BTO:0000435',
 'extensor digitorum longus': 'BTO:0000436',
 'culture condition:glycerol-grown cell': 'BTO:0000437',
 'stratum germinativum': 'BTO:0000438',
 'eye': 'BTO:0000439',
 'feces': 'BTO:0000440',
 'fat body': 'BTO:0000442',
 'adipocyte': 'BTO:0000443',
 'fat pad': 'BTO:0000444',
 'cerebral lobe': 'BTO:0000445',
 'FDCP-Mix cl.A4 cell': 'BTO:0000446',
 'feather': 'BTO:0000447',
 'fetal serum': 'BTO:0000448',
 'fetus': 'BTO:0000449',
 'fiber': 'BTO:0000450',
 'fibrillar flight muscle': 'BTO:0000451',
 'fibroblast': 'BTO:0000452',
 'fibroblast cell line': 'BTO:0000453',
 '3T6-Swiss albino cell': 'BTO:0000454',
 'JTC-15 cell': 'BTO:0000455',
 'plasmacytoma cell line': 'BTO:0000456',
 'CHO-K1 cell': 'BTO:0000457',
 'WI-38 cell': 'BTO:0000458',
 'fibrosarcoma cell': 'BTO:0000459',
 'fibrosarcoma cell line': 'BTO:0000460',
 'HSDM1C1 cell': 'BTO:0000461',
 'fiddlehead': 'BTO:0000462',
 'filament': 'BTO:0000463',
 'flagellate': 'BTO:0000464',
 'flavedo': 'BTO:0000465',
 'flexor digitorum longus': 'BTO:0000466',
 'flight muscle': 'BTO:0000467',
 'floret': 'BTO:0000468',
 'flower': 'BTO:0000469',
 'flower bud': 'BTO:0000470',
 'culture condition:fluorene-grown cell': 'BTO:0000471',
 'FM3A cell': 'BTO:0000472',
 'fetal membrane': 'BTO:0000473',
 'allantois': 'BTO:0000474',
 'ovarian follicle': 'BTO:0000475',
 'foot': 'BTO:0000476',
 'foot muscle': 'BTO:0000477',
 'forebrain': 'BTO:0000478',
 'forelimb muscle': 'BTO:0000479',
 'forestomach': 'BTO:0000480',
 'culture condition:formate-grown cell': 'BTO:0000481',
 'renal distal tubule': 'BTO:0000482',
 'frond': 'BTO:0000483',
 'frontal lobe': 'BTO:0000484',
 'culture condition:fructose-grown cell': 'BTO:0000485',
 'fruit': 'BTO:0000486',
 'fruit body': 'BTO:0000487',
 'lower epidermis': 'BTO:0000488',
 'intestinal cancer cell': 'BTO:0000489',
 'prostate gland ventral lobe': 'BTO:0000490',
 'excretion': 'BTO:0000491',
 'MST cell': 'BTO:0000492',
 'gall bladder': 'BTO:0000493',
 'germinal disc': 'BTO:0000494',
 'gametophyte': 'BTO:0000495',
 'anterior lobe': 'BTO:0000496',
 'ganglion': 'BTO:0000497',
 'gastric cancer cell': 'BTO:0000498',
 'gastric corpus mucosa': 'BTO:0000499',
 'gastric epithelium': 'BTO:0000500',
 'gastric juice': 'BTO:0000501',
 'gastric fundus': 'BTO:0000502',
 'gastric gland': 'BTO:0000503',
 'pancreatic juice': 'BTO:0000504',
 'gastric corpus': 'BTO:0000505',
 'gastrocnemius': 'BTO:0000506',
 'foregut': 'BTO:0000507',
 'thorax muscle': 'BTO:0000508',
 'gastrodermis': 'BTO:0000509',
 'hindgut': 'BTO:0000510',
 'gastrointestinal tract': 'BTO:0000511',
 'primary oocyte': 'BTO:0000512',
 'culture condition:geranoic acid-induced cell': 'BTO:0000513',
 'germ': 'BTO:0000514',
 'haustorium': 'BTO:0000515',
 'ghost': 'BTO:0000516',
 'culture condition:5-methylcytosine-grown cell': 'BTO:0000517',
 'gill': 'BTO:0000518',
 'gingiva': 'BTO:0000519',
 'gizzard': 'BTO:0000520',
 'gizzard smooth muscle': 'BTO:0000521',
 'gland': 'BTO:0000522',
 'gleba': 'BTO:0000523',
 'glia': 'BTO:0000524',
 'A-875 cell': 'BTO:0000525',
 'glioma cell': 'BTO:0000526',
 'glioblastoma cell': 'BTO:0000527',
 'JTC-27 cell': 'BTO:0000528',
 'C6 glioma cell': 'BTO:0000529',
 'renal glomerulus': 'BTO:0000530',
 'gluteal muscle': 'BTO:0000531',
 'culture condition:glycine-grown cell': 'BTO:0000532',
 'culture condition:dihydroxyacetone-grown cell': 'BTO:0000533',
 'gonad': 'BTO:0000534',
 'germ cell': 'BTO:0000535',
 'gracilis muscle': 'BTO:0000536',
 'nectar': 'BTO:0000537',
 'alveolar cell type II': 'BTO:0000538',
 'granulocyte': 'BTO:0000539',
 'pollen mother cell': 'BTO:0000540',
 'prostate gland dorsolateral lobe': 'BTO:0000541',
 'granulosa cell': 'BTO:0000542',
 'ground meristem': 'BTO:0000543',
 'guard cell': 'BTO:0000544',
 'gut': 'BTO:0000545',
 'gut mucosa': 'BTO:0000546',
 'gut wall': 'BTO:0000547',
 'prostate gland lobe': 'BTO:0000548',
 'culture condition:H2/CO2-grown cell': 'BTO:0000549',
 'anal plate': 'BTO:0000550',
 'lung cancer cell': 'BTO:0000551',
 'HaCaT cell': 'BTO:0000552',
 'peripheral blood': 'BTO:0000553',
 'hair follicle': 'BTO:0000554',
 'hair root': 'BTO:0000555',
 'germ layer': 'BTO:0000556',
 'harderian gland': 'BTO:0000557',
 'hatching gland': 'BTO:0000558',

In [6]:
# BTO 

Anatomy = pd.read_csv(f'{BASE_PATH}databases_for_mapping/uberon/Uberon_ID_Name_non_dup.csv')
Anatomy = Anatomy[~Anatomy['Name'].isna()]
Anatomy_dict  = dict(zip(Anatomy['Name'], Anatomy['UBERON ID']))
Anatomy_dict

{'thoracic mammary gland': 'UBERON:0005200',
 'nail bed of finger': 'UBERON:0005278',
 'nasalis muscle': 'UBERON:0010953',
 'medial entorhinal cortex': 'UBERON:0007224',
 'head of pancreas': 'UBERON:0001069',
 'median arcuate ligament': 'UBERON:0015215',
 'suprarostral cartilage': 'UBERON:3000998',
 'scapula': 'UBERON:0006849',
 'obsolete proneural cluster': 'UBERON:0000937',
 'urinary bladder vasculature': 'UBERON:0012239',
 'olfactory tubercle': 'UBERON:0001883',
 'stomatodeum gland': 'UBERON:0005250',
 'parasphenoid': 'UBERON:0004745',
 'manual minor digit (Aves)': 'UBERON:0012262',
 'oviduct albumen gland': 'UBERON:0034735',
 'pupa': 'UBERON:0003143',
 'transverse process of lumbar vertebra': 'UBERON:0018146',
 'periventricular nucleus of hypothalamus': 'UBERON:0014667',
 'facial motor nucleus': 'UBERON:0003011',
 'preorbitalis muscle': 'UBERON:0011685',
 'hemopoietic organ': 'UBERON:0004177',
 'ciliated pit': 'UBERON:0009957',
 'limb': 'UBERON:0002101',
 'lower jaw molar': 'UBERON:0003667',
 'major calyx': 'UBERON:0001226',
 'forelimb muscle': 'UBERON:0003662',
 'tunica vaginalis testis': 'UBERON:0006650',
 'obsolete epipharynx': 'UBERON:0003204',
 'intermetacarpal joint': 'UBERON:0011131',
 'second phalanx': 'UBERON:4100005',
 'epithelium of tongue': 'UBERON:0003357',
 'larynx epithelium': 'UBERON:0004816',
 'insect antennal disc': 'UBERON:6001767',
 'Brodmann (1909) area 13': 'UBERON:0013544',
 'oral epithelium': 'UBERON:0002424',
 'plantar nerve': 'UBERON:0035109',
 'anal fin ray 3': 'UBERON:2001771',
 'ethmoid cartilage': 'UBERON:0011242',
 'labyrinthine artery': 'UBERON:0018231',
 'sex cord': 'UBERON:0005295',
 'castor sac': 'UBERON:0036019',
 'rib 7': 'UBERON:0004607',
 'venous system': 'UBERON:0004582',
 'vena cava': 'UBERON:0004087',
 'skeletal muscle tissue of trunk': 'UBERON:0003898',
 'posterior nuchal plate': 'UBERON:2001820',
 'reticular layer of dermis': 'UBERON:0001993',
 'crus of clitoris': 'UBERON:0006640',
 'subclavius': 'UBERON:0008779',
 'bony part of hard palate': 'UBERON:0012074',
 'renal tubule': 'UBERON:0009773',
 'autopodial skeleton': 'UBERON:0006717',
 'peristaltic circulatory vessel': 'UBERON:0015227',
 'intervertebral cartilage': 'UBERON:0011135',
 'central caudal thalamic nucleus': 'UBERON:2000182',
 'palatine uvula': 'UBERON:0001734',
 'cerebellum hemispheric lobule V': 'UBERON:0024001',
 'rectus femoris': 'UBERON:0001378',
 'zonal area': 'UBERON:3000757',
 'intertragic incisure': 'UBERON:0036212',
 'corpus albicans': 'UBERON:0000450',
 'rhombomere 6': 'UBERON:0005519',
 'pronephros': 'UBERON:0002120',
 'tooth root': 'UBERON:0003677',
 'mural trophectoderm': 'UBERON:0006265',
 'mating plug': 'UBERON:0010148',
 'laterodorsal tegmental nucleus': 'UBERON:0002267',
 'pseudodentary': 'UBERON:3000518',
 'central amygdaloid nucleus': 'UBERON:0002883',
 'craniopharyngeal canal': 'UBERON:0016881',
 'membranous labyrinth': 'UBERON:0001849',
 'wrist connective tissue': 'UBERON:0003575',
 'dilatator pupillae': 'UBERON:0001608',
 'dorsal fin distal radial bone 1': 'UBERON:2005372',
 'cranial ganglion': 'UBERON:0001714',
 'auditory ossicle endochondral element': 'UBERON:0035130',
 'nephron epithelium': 'UBERON:0004211',
 'anterior sector of right lobe of liver': 'UBERON:8600016',
 'secretory circumventricular organ': 'UBERON:0010134',
 'cerebellar layer': 'UBERON:0004130',
 'fibrous ring of heart': 'UBERON:0006008',
 'anterior nucleus of hypothalamus central part': 'UBERON:0014590',
 'mesentery of heart': 'UBERON:0003282',
 'vestibulocochlear nerve': 'UBERON:0001648',
 'olfactory gland': 'UBERON:0002232',
 'cortex of manus bone': 'UBERON:0005809',
 'flexor digitorum superficialis': 'UBERON:0003222',
 'thoracic spinal cord ventral horn': 'UBERON:0014610',
 'abdominal aorta': 'UBERON:0001516',
 'tympanic plate': 'UBERON:0010066',
 'right lung accessory lobe endothelium': 'UBERON:0005676',
 'mucosa of soft palate': 'UBERON:0005024',
 'pronephric duct': 'UBERON:0003060',
 'ceratobranchial 5 bone distal cartilage': 'UBERON:2001961',
 'mushroom body': 'UBERON:0001058',
 'obsolete pharyngeal nerve': 'UBERON:0000960',
 'tunnel of Corti': 'UBERON:0005972',
 'posterior fascicle of palatopharyngeus': 'UBERON:0018103',
 'Ongur, Price, and Ferry (2003) area 47s': 'UBERON:0028417',
 'great vein of heart': 'UBERON:0006958',
 'secondary palate': 'UBERON:0001716',
 'nucleus of medulla oblongata': 'UBERON:0007635',
 'optic cup': 'UBERON:0003072',
 'midbrain dura mater': 'UBERON:0003562',
 'prepupa': 'UBERON:0003142',
 'orbital cartilages': 'UBERON:3010131',
 'arthropod neurohemal organ': 'UBERON:0001053',
 'cingulate gyrus': 'UBERON:0002967',
 'lobe of thyroid gland': 'UBERON:0001118',
 'brain blood vessel': 'UBERON:0003499',
 'uterine fat pad': 'UBERON:0014394',
 'elastic cartilage tissue': 'UBERON:0001996',
 'principal part of ventral posteromedial nucleus': 'UBERON:0003024',
 'maxillary process of inferior nasal concha': 'UBERON:0005869',
 'magnocellular nucleus of medial geniculate body': 'UBERON:0002759',
 'obsolete fast muscle cell somite 2': 'UBERON:2000879',
 'supraorbital foramen': 'UBERON:8500002',
 'sacral vertebra pre-cartilage condensation': 'UBERON:0010744',
 'respiratory system lamina propria': 'UBERON:0004779',
 'nephron': 'UBERON:0001285',
 'palpebral conjunctiva': 'UBERON:0001812',
 'lateral medullary lamina of globus pallidus': 'UBERON:0002765',
 'pelvic fin distal radial element': 'UBERON:1600008',
 'hepatobiliary system': 'UBERON:0002423',
 'adrenal cortex': 'UBERON:0001235',
 'bone of pectoral complex': 'UBERON:0010741',
 'trachea': 'UBERON:0003126',
 'arcuate fasciculus': 'UBERON:0035937',
 'cerebellopontine angle': 'UBERON:0014908',
 'central nervous system cell part cluster': 'UBERON:0011215',
 'obsolete vagal root': 'UBERON:2007011',
 'extrinsic ocular pre-muscle mass': 'UBERON:0006230',
 'dorsal pallium': 'UBERON:0014740',
 'fourth ventricle': 'UBERON:0002422',
 'nucleus isthmi': 'UBERON:2000398',
 'spleen secondary B follicle': 'UBERON:0004042',
 'mammillary princeps fasciculus': 'UBERON:0002723',
 'pedal digit 1 phalanx': 'UBERON:0003640',
 'fibroelastic membrane of larynx': 'UBERON:0014372',
 'ceratohyal-dorsal hypohyal joint': 'UBERON:2001843',
 'neurula embryo': 'UBERON:0004455',
 'dermal pulp of feather shaft': 'UBERON:0011800',
 'sesamoid element': 'UBERON:0013631',
 'hepatic portal system': 'UBERON:0010194',
 'septal nuclear complex': 'UBERON:0002663',
 'pedal digit 3': 'UBERON:0003633',
 'obsolete secondary oogonium': 'UBERON:3010299',
 'secondary follicle corona': 'UBERON:0010755',
 'left auditory cortex': 'UBERON:0009898',
 'cingulum of canine tooth': 'UBERON:0017297',
 'insect larval abdominal segment': 'UBERON:6001747',
 'blastula': 'UBERON:0000307',
 'common iliac artery': 'UBERON:0001191',
 'hyomandibular cartilage': 'UBERON:0011607',
 'posterior cerebral artery': 'UBERON:0001636',
 'cerebrospinal fluid': 'UBERON:0001359',
 'rhombomere 3 lateral wall': 'UBERON:0005574',
 'rotator muscle of the vertebral column': 'UBERON:0000951',
 'ventral thalamus': 'UBERON:0001900',
 'dorsolateral prefrontal cortex layer 6': 'UBERON:0035158',
 'spiral prominence of cochlear duct': 'UBERON:0028194',
 'pseudoangular': 'UBERON:3000515',
 'scleral endothelium': 'UBERON:0010294',
 'posterior nuclear complex of thalamus': 'UBERON:0002709',
 'intervertebral disk of fourth cervical vertebra': 'UBERON:0007261',
 'epiglottis': 'UBERON:0000388',
 'renal pelvis': 'UBERON:0001224',
 'dorsal part of pharyngeal pouch 5': 'UBERON:0010029',
 'pelvic appendage bud mesenchyme': 'UBERON:0003412',
 'granular cell layer of dorsal cochlear nucleus': 'UBERON:0029009',
 'mucus': 'UBERON:0000912',
 'second preethmoid bone': 'UBERON:2002023',
 'interarcual cartilage': 'UBERON:2002269',
 'posterior paraventricular nucleus of thalamus': 'UBERON:0000433',
 'pedal digit 5 epithelium': 'UBERON:0005652',
 'decussation of medial lemniscus': 'UBERON:0002643',
 'skin of chest': 'UBERON:0001868',
 'thyroid follicle': 'UBERON:0005305',
 'rostrum': 'UBERON:7500071',
 'pharyngeal arch mesenchyme from neural crest': 'UBERON:0010359',
 'neck of tooth': 'UBERON:0015181',
 'resorption pit': 'UBERON:0018297',
 'articular/anguloarticular': 'UBERON:0004744',
 'inner renal medulla interstitium': 'UBERON:0005214',
 'sesamoid bone of gastrocnemius': 'UBERON:0003467',
 'snake venom': 'UBERON:0013076',
 'medial condyle of tibia': 'UBERON:0009990',
 'fully formed stage': 'UBERON:0000066',
 'left atrioventricular canal': 'UBERON:0003907',
 'musculature of hip': 'UBERON:0004475',
 'ultimobranchial body': 'UBERON:0003092',
 'telencephalon arachnoid mater': 'UBERON:0005400',
 'hindlimb': 'UBERON:0002103',
 'future central tendon': 'UBERON:0006239',
 'hypoglossal nerve': 'UBERON:0001650',
 'vasculature of musculoskeletal system': 'UBERON:0004522',
 'nasal turbinal': 'UBERON:0035612',
 'proximal convoluted tubule brush border': 'UBERON:0012428',
 'esophageal nerve (sensu Cancer borealis)': 'UBERON:8910019',
 'meningeal vein': 'UBERON:0018251',
 'uncinate process of ribs': 'UBERON:0007843',
 'tendon sheath': 'UBERON:0000304',
 'extensor digitorum longus': 'UBERON:0001386',
 'external anal sphincter': 'UBERON:0001367',
 'organ cavity': 'UBERON:0002558',
 'acrocoracoid process': 'UBERON:4200040',
 'lateral occipital sulcus': 'UBERON:0002904',
 'skin nerve field': 'UBERON:0007121',
 'pectoral appendage bud mesenchyme': 'UBERON:0003413',
 'interventricular septum membranous part': 'UBERON:0004666',
 'parietal mesothelium': 'UBERON:0007140',
 'anal fin radial bone': 'UBERON:2001671',
 'jejunum lamina propria': 'UBERON:8600034',
 'lamina V of gray matter of spinal cord': 'UBERON:0016576',
 'cerebellum interpositus nucleus': 'UBERON:0004073',
 'anterior cranial fontanel': 'UBERON:2001739',
 'triangular process': 'UBERON:3010557',
 'skeleton of pedal digitopodium': 'UBERON:0012152',
 'meso-epithelium': 'UBERON:0012275',
 'white matter of forebrain': 'UBERON:0019261',
 'mammillary peduncle': 'UBERON:0002720',
 'retropyloric lymph node': 'UBERON:0038953',
 'cephalic vein': 'UBERON:0001106',
 'distal carpal bone 3': 'UBERON:0001432',
 'pupillary membrane': 'UBERON:0002269',
 'piriform cortex layer 1a': 'UBERON:0023900',
 'iliac cartilage element': 'UBERON:0010714',
 'posterior humeral circumflex artery': 'UBERON:8600107',
 'junction of superior esophageal nerve and stomatogastric nerve (sensu Cancer borealis)': 'UBERON:8910022',
 'metencephalon': 'UBERON:0001895',
 'respiratory system connective tissue': 'UBERON:0003570',
 'interneural spine cartilage': 'UBERON:4300271',
 'middle suprarenal artery': 'UBERON:0012173',
 'amphid sensory organ': 'UBERON:0005067',
 'glomerular tuft': 'UBERON:0005749',
 'tooth placode': 'UBERON:0005087',
 'multicellular organism': 'UBERON:0000468',
 'secondary dentition': 'UBERON:0007774',
 'nucleus of spinal cord': 'UBERON:0011777',
 'dorsolateral placode': 'UBERON:0003067',
 'liver lobule': 'UBERON:0004647',
 'metanephros cortex': 'UBERON:0010533',
 'white matter of myelencephalon': 'UBERON:0019262',
 'compound organ component': 'UBERON:0000471',
 'postcommissural fornix of brain': 'UBERON:0003016',
 'airway submucosal gland': 'UBERON:8410077',
 'lamina propria of esophagus': 'UBERON:0001974',
 'basipterygium bone': 'UBERON:2000623',
 'articular capsule of hip joint': 'UBERON:0011961',
 'calcaneocuboid joint': 'UBERON:0011964',
 'posterior lateral line nerve (PLLN)': 'UBERON:3010115',
 'pancreatic tributary of splenic vein': 'UBERON:0001214',
 'cranium': 'UBERON:0003128',
 'infraorbital series': 'UBERON:2001709',
 'musculature of thorax': 'UBERON:0004464',
 'calcareous tooth': 'UBERON:0001091',
 'obsolete cytoarchitectural part of the cerebellum': 'UBERON:0023827',
 'lumbar vertebra': 'UBERON:0002414',
 'pharyngobranchial element': 'UBERON:2001909',
 'placental labyrinth blood vessel': 'UBERON:0004183',
 'mucosa of male urethra': 'UBERON:0005013',
 'umbilical blood vessel': 'UBERON:0010260',
 'nuchal groove': 'UBERON:3010235',
 'left lower secondary canine tooth': 'UBERON:8490039',
 'insect adult brain': 'UBERON:6003624',
 'condyle of tibia': 'UBERON:0009989',
 'lymphatic vessel': 'UBERON:0001473',
 'epibranchial 2 bone': 'UBERON:2001246',
 'blood microvessel': 'UBERON:8410081',
 'mucosa of rumen': 'UBERON:8480046',
 'nasal air sac': 'UBERON:0013175',
 'third ventricle': 'UBERON:0002286',
 'sphenethmoid': 'UBERON:3000572',
 'submucosa of left hepatic duct': 'UBERON:0004942',
 'subsegmental bronchus': 'UBERON:8600009',
 'lower jaw cingulum': 'UBERON:0013612',
 'lepidotrichium': 'UBERON:4000172',
 'metanephric mesenchyme': 'UBERON:0003220',
 'lateral sulcus': 'UBERON:0002721',
 'subclavian artery': 'UBERON:0001533',
 'm. sternoepicoracoideus': 'UBERON:3010713',
 'lateral amygdaloid nucleus': 'UBERON:0002886',
 'os basale': 'UBERON:3000348',
 'posterior cranial fossa': 'UBERON:0008788',
 'sublaminar layers S1 or S2 or S3 or S4': 'UBERON:0009737',
 'cortical layer III': 'UBERON:0005392',
 'anterior ascending limb of lateral sulcus': 'UBERON:0002670',
 'cardiogenic splanchnic mesoderm': 'UBERON:0007005',
 'inner nuclear layer of retina': 'UBERON:0001791',
 'epithelium': 'UBERON:0000483',
 'obsolete regional part of cerebellar white matter': 'UBERON:0025444',
 'longitudinal muscle layer of muscular coat': 'UBERON:0012369',
 'pharyngobranchial 4 tooth plate': 'UBERON:2002016',
 'frenulum of lower lip': 'UBERON:0016913',
 'digital vein': 'UBERON:0004562',
 'fauces': 'UBERON:0035120',
 'cerebral hemisphere': 'UBERON:0001869',
 'transcapular ligament': 'UBERON:2001683',
 'lamina propria of mucosa of colon': 'UBERON:0007177',
 'angular sulcus': 'UBERON:0026725',
 'paravermic lobule III': 'UBERON:0028919',
 'somite 23': 'UBERON:2000730',
 'thoracic cavity connective tissue': 'UBERON:0003593',
 'forelimb nerve': 'UBERON:0003441',
 'presumptive rhombomere 8': 'UBERON:0007295',
 'nucleus of optic tract': 'UBERON:0002996',
 'cerebellar vermis': 'UBERON:0004720',
 'musculature of pectoral complex': 'UBERON:0014793',
 'hypobranchial artery': 'UBERON:2000673',
 'mucosa of cardia of stomach': 'UBERON:0004996',
 'hepatic duct': 'UBERON:0005171',
 'hypobranchial 1 bone distal cartilage': 'UBERON:2001962',
 "ventral patch of Leydig's organ": 'UBERON:0010015',
 'tapetum': 'UBERON:0015169',
 'telencephalic ventricle': 'UBERON:0002285',
 'anterior swim bladder bud': 'UBERON:2002145',
 'primitive superior sagittal sinus': 'UBERON:0009968',
 'ascending process of the parasphenoid': 'UBERON:2002021',
 'quadrate lobe hepatic sinusoid': 'UBERON:0011738',
 'anal tooth': 'UBERON:0012468',
 'central canal of spinal cord': 'UBERON:0002291',
 'myenteric nerve plexus of appendix': 'UBERON:8410011',
 'pyloric canal': 'UBERON:0008858',
 'tooth 5V': 'UBERON:2001142',
 'fast muscle tissue': 'UBERON:0006908',
 'blood vessel internal elastic membrane': 'UBERON:0011392',
 'parotid gland intralobular duct': 'UBERON:0035045',
 'habenulo-interpeduncular tract': 'UBERON:0002138',
 'maxillary prominence': 'UBERON:0005868',
 "lumen of Rathke's pouch": 'UBERON:0009974',
 'pedal digit 4 phalanx': 'UBERON:0003862',
 'left lateral wall of urinary bladder': 'UBERON:8600044',
 'blood sinus of vibrissa': 'UBERON:0034941',
 'nasal muscle': 'UBERON:0008522',
 'lateral globus pallidus': 'UBERON:0002476',
 'metaphysis of femur': 'UBERON:0006865',
 'pedicle of vertebra': 'UBERON:0001078',
 'nasolacrimal groove': 'UBERON:0006266',
 'masticatory muscle': 'UBERON:0003681',
 'substantia propria of cornea': 'UBERON:0001777',
 'arterial system endothelium': 'UBERON:0004700',
 'lumen of esophagus': 'UBERON:0011566',
 'dorsal nucleus of medial geniculate body': 'UBERON:0002758',
 'olfactory sulcus': 'UBERON:0002772',
 'periventricular hypothalamic nucleus, anterior part': 'UBERON:8440007',
 'secondary fissure of cerebellum': 'UBERON:0002817',
 'skin appendage placode': 'UBERON:0011817',
 'frontal gyrus': 'UBERON:0015593',
 'stomach fundus epithelium': 'UBERON:0005477',
 'stratum spinosum of epidermis': 'UBERON:0002026',
 'ulna': 'UBERON:0001424',
 'right atrium valve': 'UBERON:0005208',
 '1st arch mandibular ectoderm': 'UBERON:0013155',
 'central figure of scute': 'UBERON:0018309',
 'haemolymphatic fluid': 'UBERON:0000179',
 'efferent lamellar arteriole': 'UBERON:2005019',
 'manual digit 7': 'UBERON:0011982',
 'saphenous nerve': 'UBERON:0002475',
 'clavicle bone primordium': 'UBERON:0010905',
 'obsolete regional part of anterior hypothalamic region': 'UBERON:0023628',
 'testicular artery': 'UBERON:0001187',
 'tendon': 'UBERON:0000043',
 'palatoethmoidal suture': 'UBERON:0035124',
 'plantar metatarsal artery': 'UBERON:0035195',
 'facial suture': 'UBERON:0009199',
 'median eminence of neurohypophysis': 'UBERON:0002197',
 'notochordal plate': 'UBERON:0006267',
 'pedal digit 4 metatarsal endochondral element': 'UBERON:0015040',
 'irregular bone': 'UBERON:0008001',
 'bursal follicle': 'UBERON:0003905',
 'inferior phrenic artery': 'UBERON:0012255',
 'ceratohyal foramen': 'UBERON:2001795',
 'cerebral cortex neuropil': 'UBERON:0013693',
 'thoracic duct': 'UBERON:0001631',
 'ureteral orifice': 'UBERON:0012303',
 'ventral sulcus': 'UBERON:2000305',
 'sulcus longitudinalis': 'UBERON:3000844',
 'tooth 4V': 'UBERON:2001143',
 'deep facial vein': 'UBERON:0035659',
 'anal fin spine': 'UBERON:2002262',
 'stria medullaris': 'UBERON:0006086',
 'pedal digit connective tissue': 'UBERON:0003578',
 'lateral process of basipterygium': 'UBERON:2002076',
 'postganglionic sympathetic fiber': 'UBERON:0011926',
 'postrhinal area, layer 4': 'UBERON:0035911',
 'flocculus': 'UBERON:0001063',
 'superior mesenteric ganglion': 'UBERON:0005479',
 'strand of hair': 'UBERON:0001037',
 'olfactory trigone': 'UBERON:0002922',
 'obsolete regional part of fovea': 'UBERON:0028200',
 'promontory lymph node': 'UBERON:0037536',
 'pons': 'UBERON:0000988',
 'hyoid apparatus': 'UBERON:0010272',
 'ramus nasalis internus': 'UBERON:3010661',
 'atrioventricular nodal artery': 'UBERON:8600055',
 'pyramidal layer of CA2': 'UBERON:0014549',
 'epithelium of esophagus': 'UBERON:0001976',
 'decussation of superior cerebellar peduncle': 'UBERON:0002588',
 'heart endothelium': 'UBERON:0008307',
 'parieto-occipital sulcus': 'UBERON:0002695',
 'olivocerebellar tract': 'UBERON:0002752',
 'hair follicle isthmus': 'UBERON:0006005',
 'pharyngeal arch 1': 'UBERON:0004362',
 'crypt of Lieberkuhn': 'UBERON:0001983',
 'spinal cord ependyma': 'UBERON:0005359',
 'manual digit 2, 3 or 4': 'UBERON:0019232',
 'immature posterior otolith': 'UBERON:2001103',
 'caudal vertebra endochondral element': 'UBERON:0018142',
 'segmental pulmonary vein': 'UBERON:8600051',
 'sternum': 'UBERON:0000975',
 'brachial nerve plexus': 'UBERON:0001814',
 'intercarpal joint': 'UBERON:0011132',
 'body wall': 'UBERON:0000309',
 'plantar part of pes': 'UBERON:0008338',
 'T10 segment of thoracic spinal cord': 'UBERON:0006466',
 'skin of manus': 'UBERON:0001519',
 'tibial artery': 'UBERON:0007610',
 'actinopterygian pyloric caecum': 'UBERON:4300174',
 'endocardial ring': 'UBERON:2005072',
 'mesenchyme of hip': 'UBERON:0003320',
 'mesenchyme of interdigital region of pes': 'UBERON:0009601',
 'dorsal lateral geniculate nucleus': 'UBERON:0002479',
 'mesenchyme derived from trunk neural crest': 'UBERON:0007214',
 'gastrocnemius medialis': 'UBERON:0011907',
 'extrinsic auricular muscle': 'UBERON:0001583',
 'obsolete gravid stage': 'UBERON:0009096',
 'cardiac septum': 'UBERON:0002099',
 'collecting duct of renal tubule': 'UBERON:0001232',
 'ulnar protuberances': 'UBERON:3010189',
 'eponychium': 'UBERON:0004882',
 'surface of bone': 'UBERON:4200230',
 'anatomical line between outer ears': 'UBERON:0010231',
 'osseus labyrinth vestibule': 'UBERON:0005236',
 'tarsal gland': 'UBERON:0001818',
 'mucosa of pyloric antrum': 'UBERON:0004997',
 'thoracic vertebra 7': 'UBERON:0004632',
 'interdigital region': 'UBERON:0006012',
 'pronephric glomerular capillary': 'UBERON:0007306',
 'right lower second secondary premolar tooth': 'UBERON:8490011',
 'skeleton of lower jaw': 'UBERON:0003278',

In [7]:
Anatomy[Anatomy['Name'].str.contains('golgi')]

,UBERON ID,Name,Other IDs
1133,UBERON:0004012,golgi tendon organ,EMAPA:37873; FMA:83608; NCIT:C13826; UMLS:C002...

In [9]:
GO = pd.read_csv(f'{BASE_PATH}databases_for_mapping/MESH/MESH_GO_ID_NAME.csv')
GO_dict = dict(zip(GO['name'], GO['id']))
GO_dict
GO_id_namespace_dict = dict(zip(GO['id'], GO['namespace']))
GO_id_namespace_dict

{'GO:0000001': 'biological_process',
 'GO:0000002': 'biological_process',
 'GO:0000003': 'biological_process',
 'GO:0000005': 'molecular_function',
 'GO:0000006': 'molecular_function',
 'GO:0000007': 'molecular_function',
 'GO:0000008': 'molecular_function',
 'GO:0000009': 'molecular_function',
 'GO:0000010': 'molecular_function',
 'GO:0000011': 'biological_process',
 'GO:0000012': 'biological_process',
 'GO:0000014': 'molecular_function',
 'GO:0000015': 'cellular_component',
 'GO:0000016': 'molecular_function',
 'GO:0000017': 'biological_process',
 'GO:0000018': 'biological_process',
 'GO:0000019': 'biological_process',
 'GO:0000020': 'biological_process',
 'GO:0000022': 'biological_process',
 'GO:0000023': 'biological_process',
 'GO:0000024': 'biological_process',
 'GO:0000025': 'biological_process',
 'GO:0000026': 'molecular_function',
 'GO:0000027': 'biological_process',
 'GO:0000028': 'biological_process',
 'GO:0000030': 'molecular_function',
 'GO:0000031': 'molecular_function',
 'GO:0000032': 'biological_process',
 'GO:0000033': 'molecular_function',
 'GO:0000034': 'molecular_function',
 'GO:0000035': 'molecular_function',
 'GO:0000036': 'molecular_function',
 'GO:0000038': 'biological_process',
 'GO:0000039': 'molecular_function',
 'GO:0000041': 'biological_process',
 'GO:0000044': 'biological_process',
 'GO:0000045': 'biological_process',
 'GO:0000047': 'molecular_function',
 'GO:0000048': 'molecular_function',
 'GO:0000049': 'molecular_function',
 'GO:0000050': 'biological_process',
 'GO:0000051': 'biological_process',
 'GO:0000052': 'biological_process',
 'GO:0000053': 'biological_process',
 'GO:0000054': 'biological_process',
 'GO:0000055': 'biological_process',
 'GO:0000056': 'biological_process',
 'GO:0000059': 'biological_process',
 'GO:0000060': 'biological_process',
 'GO:0000061': 'biological_process',
 'GO:0000062': 'molecular_function',
 'GO:0000064': 'molecular_function',
 'GO:0000067': 'biological_process',
 'GO:0000070': 'biological_process',
 'GO:0000072': 'biological_process',
 'GO:0000073': 'biological_process',
 'GO:0000075': 'biological_process',
 'GO:0000076': 'biological_process',
 'GO:0000077': 'biological_process',
 'GO:0000078': 'biological_process',
 'GO:0000079': 'biological_process',
 'GO:0000080': 'biological_process',
 'GO:0000082': 'biological_process',
 'GO:0000083': 'biological_process',
 'GO:0000084': 'biological_process',
 'GO:0000085': 'biological_process',
 'GO:0000086': 'biological_process',
 'GO:0000087': 'biological_process',
 'GO:0000088': 'biological_process',
 'GO:0000089': 'biological_process',
 'GO:0000090': 'biological_process',
 'GO:0000091': 'biological_process',
 'GO:0000092': 'biological_process',
 'GO:0000093': 'biological_process',
 'GO:0000094': 'biological_process',
 'GO:0000095': 'molecular_function',
 'GO:0000096': 'biological_process',
 'GO:0000097': 'biological_process',
 'GO:0000098': 'biological_process',
 'GO:0000099': 'molecular_function',
 'GO:0000100': 'molecular_function',
 'GO:0000101': 'biological_process',
 'GO:0000102': 'molecular_function',
 'GO:0000103': 'biological_process',
 'GO:0000104': 'molecular_function',
 'GO:0000105': 'biological_process',
 'GO:0000107': 'molecular_function',
 'GO:0000108': 'cellular_component',
 'GO:0000109': 'cellular_component',
 'GO:0000110': 'cellular_component',
 'GO:0000111': 'cellular_component',
 'GO:0000112': 'cellular_component',
 'GO:0000113': 'cellular_component',
 'GO:0000114': 'biological_process',
 'GO:0000115': 'biological_process',
 'GO:0000116': 'biological_process',
 'GO:0000117': 'biological_process',
 'GO:0000118': 'cellular_component',
 'GO:0000120': 'cellular_component',
 'GO:0000121': 'molecular_function',
 'GO:0000122': 'biological_process',
 'GO:0000123': 'cellular_component',
 'GO:0000124': 'cellular_component',
 'GO:0000126': 'cellular_component',
 'GO:0000127': 'cellular_component',
 'GO:0000128': 'biological_process',
 'GO:0000131': 'cellular_component',
 'GO:0000132': 'biological_process',
 'GO:0000133': 'cellular_component',
 'GO:0000136': 'cellular_component',
 'GO:0000137': 'cellular_component',
 'GO:0000138': 'cellular_component',
 'GO:0000139': 'cellular_component',
 'GO:0000140': 'molecular_function',
 'GO:0000142': 'cellular_component',
 'GO:0000144': 'cellular_component',
 'GO:0000145': 'cellular_component',
 'GO:0000146': 'molecular_function',
 'GO:0000147': 'biological_process',
 'GO:0000148': 'cellular_component',
 'GO:0000149': 'molecular_function',
 'GO:0000150': 'molecular_function',
 'GO:0000151': 'cellular_component',
 'GO:0000152': 'cellular_component',
 'GO:0000153': 'cellular_component',
 'GO:0000154': 'biological_process',
 'GO:0000155': 'molecular_function',
 'GO:0000156': 'molecular_function',
 'GO:0000159': 'cellular_component',
 'GO:0000160': 'biological_process',
 'GO:0000161': 'biological_process',
 'GO:0000162': 'biological_process',
 'GO:0000164': 'cellular_component',
 'GO:0000165': 'biological_process',
 'GO:0000166': 'molecular_function',
 'GO:0000170': 'molecular_function',
 'GO:0000171': 'molecular_function',
 'GO:0000172': 'cellular_component',
 'GO:0000174': 'biological_process',
 'GO:0000175': 'molecular_function',
 'GO:0000176': 'cellular_component',
 'GO:0000177': 'cellular_component',
 'GO:0000178': 'cellular_component',
 'GO:0000179': 'molecular_function',
 'GO:0000180': 'cellular_component',
 'GO:0000181': 'cellular_component',
 'GO:0000182': 'molecular_function',
 'GO:0000183': 'biological_process',
 'GO:0000184': 'biological_process',
 'GO:0000185': 'biological_process',
 'GO:0000186': 'biological_process',
 'GO:0000187': 'biological_process',
 'GO:0000188': 'biological_process',
 'GO:0000189': 'biological_process',
 'GO:0000190': 'biological_process',
 'GO:0000191': 'biological_process',
 'GO:0000192': 'biological_process',
 'GO:0000193': 'biological_process',
 'GO:0000194': 'biological_process',
 'GO:0000195': 'biological_process',
 'GO:0000196': 'biological_process',
 'GO:0000197': 'biological_process',
 'GO:0000198': 'biological_process',
 'GO:0000199': 'biological_process',
 'GO:0000200': 'biological_process',
 'GO:0000201': 'biological_process',
 'GO:0000202': 'biological_process',
 'GO:0000203': 'biological_process',
 'GO:0000204': 'biological_process',
 'GO:0000205': 'biological_process',
 'GO:0000206': 'biological_process',
 'GO:0000207': 'biological_process',
 'GO:0000208': 'biological_process',
 'GO:0000209': 'biological_process',
 'GO:0000210': 'molecular_function',
 'GO:0000211': 'molecular_function',
 'GO:0000212': 'biological_process',
 'GO:0000213': 'molecular_function',
 'GO:0000214': 'cellular_component',
 'GO:0000215': 'molecular_function',
 'GO:0000216': 'biological_process',
 'GO:0000217': 'molecular_function',
 'GO:0000219': 'cellular_component',
 'GO:0000220': 'cellular_component',
 'GO:0000221': 'cellular_component',
 'GO:0000222': 'cellular_component',
 'GO:0000223': 'cellular_component',
 'GO:0000224': 'molecular_function',
 'GO:0000225': 'molecular_function',
 'GO:0000226': 'biological_process',
 'GO:0000227': 'molecular_function',
 'GO:0000228': 'cellular_component',
 'GO:0000229': 'cellular_component',
 'GO:0000230': 'cellular_component',
 'GO:0000231': 'cellular_component',
 'GO:0000232': 'cellular_component',
 'GO:0000233': 'cellular_component',
 'GO:0000234': 'molecular_function',
 'GO:0000235': 'cellular_component',
 'GO:0000236': 'biological_process',
 'GO:0000237': 'biological_process',
 'GO:0000238': 'biological_process',
 'GO:0000239': 'biological_process',
 'GO:0000240': 'biological_process',
 'GO:0000241': 'biological_process',
 'GO:0000242': 'cellular_component',
 'GO:0000243': 'cellular_component',
 'GO:0000244': 'biological_process',
 'GO:0000245': 'biological_process',
 'GO:0000246': 'molecular_function',
 'GO:0000247': 'molecular_function',
 'GO:0000248': 'molecular_function',
 'GO:0000249': 'molecular_function',
 'GO:0000250': 'molecular_function',
 'GO:0000252': 'molecular_function',
 'GO:0000253': 'molecular_function',
 'GO:0000254': 'molecular_function',
 'GO:0000255': 'biological_process',
 'GO:0000256': 'biological_process',
 'GO:0000257': 'molecular_function',
 'GO:0000258': 'molecular_function',
 'GO:0000259': 'molecular_function',
 'GO:0000260': 'molecular_function',
 'GO:0000261': 'molecular_function',
 'GO:0000262': 'cellular_component',
 'GO:0000263': 'molecular_function',
 'GO:0000264': 'molecular_function',
 'GO:0000265': 'molecular_function',
 'GO:0000266': 'biological_process',
 'GO:0000267': 'cellular_component',
 'GO:0000268': 'molecular_function',
 'GO:0000269': 'molecular_function',
 'GO:0000270': 'biological_process',
 'GO:0000271': 'biological_process',
 'GO:0000272': 'biological_process',
 'GO:0000274': 'cellular_component',
 'GO:0000275': 'cellular_component',
 'GO:0000276': 'cellular_component',
 'GO:0000277': 'molecular_function',
 'GO:0000278': 'biological_process',
 'GO:0000279': 'biological_process',
 'GO:0000280': 'biological_process',
 'GO:0000281': 'biological_process',
 'GO:0000282': 'biological_process',
 'GO:0000284': 'biological_process',
 'GO:0000285': 'molecular_function',
 'GO:0000286': 'molecular_function',
 'GO:0000287': 'molecular_function',
 'GO:0000288': 'biological_process',
 'GO:0000289': 'biological_process',
 'GO:0000290': 'biological_process',
 'GO:0000291': 'biological_process',
 'GO:0000292': 'biological_process',
 'GO:0000293': 'molecular_function',
 'GO:0000294': 'biological_process',
 'GO:0000295': 'molecular_function',
 'GO:0000296': 'biological_process',
 'GO:0000297': 'molecular_function',
 'GO:0000298': 'molecular_function',
 'GO:0000299': 'cellular_component',
 'GO:0000300': 'cellular_component',
 'GO:0000301': 'biological_process',
 'GO:0000302': 'biological_process',
 'GO:0000303': 'biological_process',
 'GO:0000304': 'biological_process',
 'GO:0000305': 'biological_process',
 'GO:0000306': 'cellular_component',
 'GO:0000307': 'cellular_component',
 'GO:0000308': 'cellular_component',
 'GO:0000309': 'molecular_function',
 'GO:0000310': 'molecular_function',
 'GO:0000311': 'cellular_component',
 'GO:0000312': 'cellular_component',
 'GO:0000313': 'cellular_component',
 'GO:0000314': 'cellular_component',
 'GO:0000315': 'cellular_component',
 'GO:0000316': 'biological_process',
 'GO:0000319': 'molecular_function',
 'GO:0000320': 'biological_process',
 'GO:0000321': 'biological_process',
 'GO:0000322': 'cellular_component',
 'GO:0000323': 'cellular_component',
 'GO:0000324': 'cellular_component',
 'GO:0000325': 'cellular_component',
 'GO:0000326': 'cellular_component',
 'GO:0000327': 'cellular_component',
 'GO:0000328': 'cellular_component',
 'GO:0000329': 'cellular_component',
 'GO:0000330': 'cellular_component',
 'GO:0000331': 'cellular_component',
 'GO:0000332': 'molecular_function',
 'GO:0000333': 'cellular_component',
 'GO:0000334': 'molecular_function',
 'GO:0000335': 'biological_process',
 'GO:0000336': 'biological_process',
 'GO:0000337': 'biological_process',
 'GO:0000338': 'biological_process',
 'GO:0000339': 'molecular_function',
 'GO:0000340': 'molecular_function',
 'GO:0000341': 'molecular_function',
 'GO:0000342': 'molecular_function',
 'GO:0000343': 'cellular_component',
 'GO:0000344': 'cellular_component',
 'GO:0000345': 'cellular_component',
 'GO:0000346': 'cellular_component',
 'GO:0000347': 'cellular_component',
 'GO:0000348': 'biological_process',
 'GO:0000349': 'biological_process',
 'GO:0000350': 'biological_process',
 'GO:0000352': 'biological_process',
 'GO:0000353': 'biological_process',
 'GO:0000354': 'biological_process',
 'GO:0000362': 'molecular_function',
 'GO:0000363': 'molecular_function',
 'GO:0000364': 'molecular_function',
 'GO:0000365': 'biological_process',
 'GO:0000366': 'biological_process',
 'GO:0000367': 'molecular_function',
 'GO:0000372': 'biological_process',
 'GO:0000373': 'biological_process',
 'GO:0000374': 'biological_process',
 'GO:0000375': 'biological_process',
 'GO:0000376': 'biological_process',
 'GO:0000377': 'biological_process',
 'GO:0000378': 'biological_process',
 'GO:0000379': 'biological_process',
 'GO:0000380': 'biological_process',
 'GO:0000381': 'biological_process',
 'GO:0000384': 'molecular_function',
 'GO:0000386': 'molecular_function',
 'GO:0000387': 'biological_process',
 'GO:0000388': 'biological_process',
 'GO:0000389': 'biological_process',
 'GO:0000390': 'biological_process',
 'GO:0000393': 'biological_process',
 'GO:0000394': 'biological_process',
 'GO:0000395': 'biological_process',
 'GO:0000398': 'biological_process',
 'GO:0000399': 'cellular_component',
 'GO:0000400': 'molecular_function',
 'GO:0000401': 'molecular_function',
 'GO:0000402': 'molecular_function',
 'GO:0000403': 'molecular_function',
 'GO:0000404': 'molecular_function',
 'GO:0000405': 'molecular_function',
 'GO:0000406': 'molecular_function',
 'GO:0000407': 'cellular_component',
 'GO:0000408': 'cellular_component',
 'GO:0000409': 'biological_process',
 'GO:0000410': 'biological_process',
 'GO:0000411': 'biological_process',
 'GO:0000412': 'biological_process',
 'GO:0000413': 'biological_process',
 'GO:0000414': 'biological_process',
 'GO:0000415': 'biological_process',
 'GO:0000416': 'biological_process',
 'GO:0000417': 'cellular_component',
 'GO:0000418': 'cellular_component',
 'GO:0000419': 'cellular_component',
 'GO:0000421': 'cellular_component',
 'GO:0000422': 'biological_process',
 'GO:0000423': 'biological_process',
 'GO:0000424': 'biological_process',
 'GO:0000425': 'biological_process',
 'GO:0000426': 'biological_process',
 'GO:0000427': 'cellular_component',
 'GO:0000428': 'cellular_component',
 'GO:0000429': 'biological_process',
 'GO:0000430': 'biological_process',
 'GO:0000431': 'biological_process',
 'GO:0000432': 'biological_process',
 'GO:0000433': 'biological_process',
 'GO:0000434': 'biological_process',
 'GO:0000435': 'biological_process',
 'GO:0000436': 'biological_process',
 'GO:0000437': 'biological_process',
 'GO:0000438': 'cellular_component',
 'GO:0000439': 'cellular_component',
 'GO:0000440': 'cellular_component',
 'GO:0000444': 'cellular_component',
 'GO:0000445': 'cellular_component',
 'GO:0000446': 'cellular_component',
 'GO:0000447': 'biological_process',
 'GO:0000448': 'biological_process',
 'GO:0000449': 'biological_process',
 'GO:0000450': 'biological_process',
 'GO:0000451': 'biological_process',
 'GO:0000452': 'biological_process',
 'GO:0000453': 'biological_process',
 'GO:0000454': 'biological_process',
 'GO:0000455': 'biological_process',
 'GO:0000456': 'biological_process',
 'GO:0000457': 'biological_process',
 'GO:0000458': 'biological_process',
 'GO:0000459': 'biological_process',
 'GO:0000460': 'biological_process',
 'GO:0000461': 'biological_process',
 'GO:0000462': 'biological_process',
 'GO:0000463': 'biological_process',
 'GO:0000464': 'biological_process',
 'GO:0000465': 'biological_process',
 'GO:0000466': 'biological_process',
 'GO:0000467': 'biological_process',
 'GO:0000468': 'biological_process',
 'GO:0000469': 'biological_process',
 'GO:0000470': 'biological_process',
 'GO:0000471': 'biological_process',
 'GO:0000472': 'biological_process',
 'GO:0000473': 'biological_process',
 'GO:0000474': 'biological_process',
 'GO:0000475': 'biological_process',
 'GO:0000476': 'biological_process',
 'GO:0000477': 'biological_process',
 'GO:0000478': 'biological_process',
 'GO:0000479': 'biological_process',
 'GO:0000480': 'biological_process',
 'GO:0000481': 'biological_process',
 'GO:0000482': 'biological_process',
 'GO:0000483': 'biological_process',
 'GO:0000484': 'biological_process',
 'GO:0000485': 'biological_process',
 'GO:0000486': 'biological_process',
 'GO:0000487': 'biological_process',
 'GO:0000488': 'biological_process',
 'GO:0000489': 'biological_process',
 'GO:0000491': 'biological_process',
 'GO:0000492': 'biological_process',
 'GO:0000493': 'biological_process',
 'GO:0000494': 'biological_process',
 'GO:0000495': 'biological_process',
 'GO:0000497': 'molecular_function',
 'GO:0000500': 'cellular_component',
 'GO:0000502': 'cellular_component',
 'GO:0000504': 'cellular_component',
 'GO:0000506': 'cellular_component',
 'GO:0000510': 'molecular_function',
 'GO:0000511': 'molecular_function',
 'GO:0000512': 'biological_process',
 'GO:0000513': 'molecular_function',
 'GO:0000514': 'molecular_function',
 'GO:0000515': 'molecular_function',
 'GO:0000578': 'biological_process',
 'GO:0000700': 'molecular_function',
 'GO:0000701': 'molecular_function',
 'GO:0000702': 'molecular_function',
 'GO:0000703': 'molecular_function',
 'GO:0000704': 'molecular_function',
 'GO:0000705': 'biological_process',
 'GO:0000706': 'biological_process',
 'GO:0000707': 'biological_process',
 'GO:0000708': 'biological_process',
 'GO:0000709': 'biological_process',
 'GO:0000710': 'biological_process',
 'GO:0000711': 'biological_process',
 'GO:0000712': 'biological_process',
 'GO:0000713': 'biological_process',
 'GO:0000714': 'biological_process',
 'GO:0000715': 'biological_process',
 'GO:0000716': 'biological_process',
 'GO:0000717': 'biological_process',
 'GO:0000718': 'biological_process',
 'GO:0000719': 'biological_process',
 'GO:0000720': 'biological_process',
 'GO:0000721': 'molecular_function',
 'GO:0000722': 'biological_process',
 'GO:0000723': 'biological_process',
 'GO:0000724': 'biological_process',
 'GO:0000725': 'biological_process',
 'GO:0000726': 'biological_process',
 'GO:0000727': 'biological_process',
 'GO:0000729': 'biological_process',
 'GO:0000730': 'biological_process',
 'GO:0000731': 'biological_process',
 'GO:0000732': 'biological_process',
 'GO:0000733': 'biological_process',
 'GO:0000735': 'biological_process',
 'GO:0000736': 'biological_process',
 'GO:0000737': 'biological_process',
 'GO:0000738': 'biological_process',
 'GO:0000739': 'molecular_function',
 'GO:0000740': 'biological_process',
 'GO:0000741': 'biological_process',
 'GO:0000742': 'biological_process',
 'GO:0000743': 'biological_process',
 'GO:0000744': 'biological_process',
 'GO:0000745': 'biological_process',
 'GO:0000746': 'biological_process',
 'GO:0000747': 'biological_process',
 'GO:0000748': 'biological_process',
 'GO:0000749': 'biological_process',
 'GO:0000750': 'biological_process',
 'GO:0000751': 'biological_process',
 'GO:0000752': 'biological_process',
 'GO:0000753': 'biological_process',
 'GO:0000754': 'biological_process',
 'GO:0000755': 'biological_process',
 'GO:0000756': 'biological_process',
 'GO:0000757': 'biological_process',
 'GO:0000758': 'biological_process',
 'GO:0000759': 'biological_process',
 'GO:0000760': 'biological_process',
 'GO:0000761': 'biological_process',
 'GO:0000762': 'biological_process',
 'GO:0000763': 'biological_process',
 'GO:0000764': 'biological_process',
 'GO:0000765': 'biological_process',
 'GO:0000766': 'biological_process',
 'GO:0000767': 'biological_process',
 'GO:0000768': 'biological_process',
 'GO:0000769': 'biological_process',
 'GO:0000770': 'biological_process',
 'GO:0000771': 'biological_process',
 'GO:0000772': 'molecular_function',
 'GO:0000773': 'molecular_function',
 'GO:0000774': 'molecular_function',
 'GO:0000775': 'cellular_component',
 'GO:0000776': 'cellular_component',
 'GO:0000779': 'cellular_component',
 'GO:0000781': 'cellular_component',
 'GO:0000782': 'cellular_component',
 'GO:0000783': 'cellular_component',
 'GO:0000785': 'cellular_component',
 'GO:0000786': 'cellular_component',
 'GO:0000791': 'cellular_component',
 'GO:0000792': 'cellular_component',
 'GO:0000793': 'cellular_component',
 'GO:0000794': 'cellular_component',
 'GO:0000795': 'cellular_component',
 'GO:0000796': 'cellular_component',
 'GO:0000800': 'cellular_component',
 'GO:0000801': 'cellular_component',
 'GO:0000802': 'cellular_component',
 'GO:0000803': 'cellular_component',
 'GO:0000804': 'cellular_component',
 'GO:0000805': 'cellular_component',
 'GO:0000806': 'cellular_component',
 'GO:0000807': 'cellular_component',
 'GO:0000808': 'cellular_component',
 'GO:0000809': 'cellular_component',
 'GO:0000810': 'molecular_function',

In [11]:
GO_dict

{'mitochondrion inheritance': 'GO:0000001',
 'mitochondrial genome maintenance': 'GO:0000002',
 'obsolete reproduction': 'GO:0000003',
 'obsolete ribosomal chaperone activity': 'GO:0000005',
 'high-affinity zinc transmembrane transporter activity': 'GO:0000006',
 'low-affinity zinc ion transmembrane transporter activity': 'GO:0000007',
 'obsolete thioredoxin': 'GO:0000008',
 'alpha-1,6-mannosyltransferase activity': 'GO:0000009',
 'heptaprenyl diphosphate synthase activity': 'GO:0000010',
 'vacuole inheritance': 'GO:0000011',
 'single strand break repair': 'GO:0000012',
 'single-stranded DNA endodeoxyribonuclease activity': 'GO:0000014',
 'phosphopyruvate hydratase complex': 'GO:0000015',
 'lactase activity': 'GO:0000016',
 'alpha-glucoside transport': 'GO:0000017',
 'regulation of DNA recombination': 'GO:0000018',
 'regulation of mitotic recombination': 'GO:0000019',
 'obsolete negative regulation of recombination within rDNA repeats': 'GO:0000020',
 'mitotic spindle elongation': 'GO:0000022',
 'maltose metabolic process': 'GO:0000023',
 'maltose biosynthetic process': 'GO:0000024',
 'maltose catabolic process': 'GO:0000025',
 'alpha-1,2-mannosyltransferase activity': 'GO:0000026',
 'ribosomal large subunit assembly': 'GO:0000027',
 'ribosomal small subunit assembly': 'GO:0000028',
 'mannosyltransferase activity': 'GO:0000030',
 'mannosylphosphate transferase activity': 'GO:0000031',
 'cell wall mannoprotein biosynthetic process': 'GO:0000032',
 'alpha-1,3-mannosyltransferase activity': 'GO:0000033',
 'adenine deaminase activity': 'GO:0000034',
 'acyl binding': 'GO:0000035',
 'acyl carrier activity': 'GO:0000036',
 'very long-chain fatty acid metabolic process': 'GO:0000038',
 'obsolete plasma membrane long-chain fatty acid transporter': 'GO:0000039',
 'transition metal ion transport': 'GO:0000041',
 'obsolete ascorbate stabilization': 'GO:0000044',
 'autophagosome assembly': 'GO:0000045',
 'obsolete Rieske iron-sulfur protein': 'GO:0000047',
 'peptidyltransferase activity': 'GO:0000048',
 'tRNA binding': 'GO:0000049',
 'urea cycle': 'GO:0000050',
 'obsolete urea cycle intermediate metabolic process': 'GO:0000051',
 'citrulline metabolic process': 'GO:0000052',
 'argininosuccinate metabolic process': 'GO:0000053',
 'ribosomal subunit export from nucleus': 'GO:0000054',
 'ribosomal large subunit export from nucleus': 'GO:0000055',
 'ribosomal small subunit export from nucleus': 'GO:0000056',
 'obsolete protein import into nucleus, docking': 'GO:0000059',
 'obsolete protein import into nucleus, translocation': 'GO:0000060',
 'obsolete protein import into nucleus, substrate release': 'GO:0000061',
 'fatty-acyl-CoA binding': 'GO:0000062',
 'L-ornithine transmembrane transporter activity': 'GO:0000064',
 'obsolete DNA replication and chromosome cycle': 'GO:0000067',
 'mitotic sister chromatid segregation': 'GO:0000070',
 'obsolete M phase specific microtubule process': 'GO:0000072',
 'initial mitotic spindle pole body separation': 'GO:0000073',
 'cell cycle checkpoint signaling': 'GO:0000075',
 'DNA replication checkpoint signaling': 'GO:0000076',
 'DNA damage checkpoint signaling': 'GO:0000077',
 'obsolete cytokinesis after mitosis checkpoint': 'GO:0000078',
 'regulation of cyclin-dependent protein serine/threonine kinase activity': 'GO:0000079',
 'mitotic G1 phase': 'GO:0000080',
 'G1/S transition of mitotic cell cycle': 'GO:0000082',
 'obsolete regulation of transcription involved in G1/S transition of mitotic cell cycle': 'GO:0000083',
 'mitotic S phase': 'GO:0000084',
 'mitotic G2 phase': 'GO:0000085',
 'G2/M transition of mitotic cell cycle': 'GO:0000086',
 'mitotic M phase': 'GO:0000087',
 'mitotic prophase': 'GO:0000088',
 'mitotic metaphase': 'GO:0000089',
 'mitotic anaphase': 'GO:0000090',
 'mitotic anaphase A': 'GO:0000091',
 'mitotic anaphase B': 'GO:0000092',
 'mitotic telophase': 'GO:0000093',
 'obsolete septin assembly and septum formation': 'GO:0000094',
 'S-adenosyl-L-methionine transmembrane transporter activity': 'GO:0000095',
 'sulfur amino acid metabolic process': 'GO:0000096',
 'sulfur amino acid biosynthetic process': 'GO:0000097',
 'sulfur amino acid catabolic process': 'GO:0000098',
 'sulfur amino acid transmembrane transporter activity': 'GO:0000099',
 'S-methylmethionine transmembrane transporter activity': 'GO:0000100',
 'sulfur amino acid transport': 'GO:0000101',
 'L-methionine secondary active transmembrane transporter activity': 'GO:0000102',
 'sulfate assimilation': 'GO:0000103',
 'succinate dehydrogenase activity': 'GO:0000104',
 'L-histidine biosynthetic process': 'GO:0000105',
 'imidazoleglycerol-phosphate synthase activity': 'GO:0000107',
 'obsolete repairosome': 'GO:0000108',
 'nucleotide-excision repair complex': 'GO:0000109',
 'nucleotide-excision repair factor 1 complex': 'GO:0000110',
 'nucleotide-excision repair factor 2 complex': 'GO:0000111',
 'nucleotide-excision repair factor 3 complex': 'GO:0000112',
 'nucleotide-excision repair factor 4 complex': 'GO:0000113',
 'obsolete regulation of transcription involved in G1 phase of mitotic cell cycle': 'GO:0000114',
 'obsolete regulation of transcription involved in S phase of mitotic cell cycle': 'GO:0000115',
 'obsolete regulation of transcription involved in G2-phase of mitotic cell cycle': 'GO:0000116',
 'obsolete regulation of transcription involved in G2/M transition of mitotic cell cycle': 'GO:0000117',
 'histone deacetylase complex': 'GO:0000118',
 'RNA polymerase I transcription regulator complex': 'GO:0000120',
 'glycerol-1-phosphatase activity': 'GO:0000121',
 'negative regulation of transcription by RNA polymerase II': 'GO:0000122',
 'histone acetyltransferase complex': 'GO:0000123',
 'SAGA complex': 'GO:0000124',
 'transcription factor TFIIIB complex': 'GO:0000126',
 'transcription factor TFIIIC complex': 'GO:0000127',
 'flocculation': 'GO:0000128',
 'incipient cellular bud site': 'GO:0000131',
 'establishment of mitotic spindle orientation': 'GO:0000132',
 'polarisome': 'GO:0000133',
 'mannan polymerase complex': 'GO:0000136',
 'Golgi cis cisterna': 'GO:0000137',
 'Golgi trans cisterna': 'GO:0000138',
 'Golgi membrane': 'GO:0000139',
 'acylglycerone-phosphate reductase (NADP+) activity': 'GO:0000140',
 'cellular bud neck contractile ring': 'GO:0000142',
 'cellular bud neck septin ring': 'GO:0000144',
 'exocyst': 'GO:0000145',
 'microfilament motor activity': 'GO:0000146',
 'actin cortical patch assembly': 'GO:0000147',
 '1,3-beta-D-glucan synthase complex': 'GO:0000148',
 'SNARE binding': 'GO:0000149',
 'DNA strand exchange activity': 'GO:0000150',
 'ubiquitin ligase complex': 'GO:0000151',
 'nuclear ubiquitin ligase complex': 'GO:0000152',
 'cytoplasmic ubiquitin ligase complex': 'GO:0000153',
 'rRNA modification': 'GO:0000154',
 'phosphorelay sensor kinase activity': 'GO:0000155',
 'phosphorelay response regulator activity': 'GO:0000156',
 'protein phosphatase type 2A complex': 'GO:0000159',
 'phosphorelay signal transduction system': 'GO:0000160',
 'obsolete osmosensory signaling MAPK cascade': 'GO:0000161',
 'L-tryptophan biosynthetic process': 'GO:0000162',
 'protein phosphatase type 1 complex': 'GO:0000164',
 'MAPK cascade': 'GO:0000165',
 'nucleotide binding': 'GO:0000166',
 'sphingosine hydroxylase activity': 'GO:0000170',
 'ribonuclease MRP activity': 'GO:0000171',
 'ribonuclease MRP complex': 'GO:0000172',
 'obsolete inactivation of MAPK (mating sensu Saccharomyces)': 'GO:0000174',
 "3'-5'-RNA exonuclease activity": 'GO:0000175',
 'nuclear exosome (RNase complex)': 'GO:0000176',
 'cytoplasmic exosome (RNase complex)': 'GO:0000177',
 'exosome (RNase complex)': 'GO:0000178',
 'rRNA (adenine-N6,N6-)-dimethyltransferase activity': 'GO:0000179',
 'obsolete cytosolic large ribosomal subunit': 'GO:0000180',
 'obsolete cytosolic small ribosomal subunit': 'GO:0000181',
 'rDNA binding': 'GO:0000182',
 'rDNA heterochromatin formation': 'GO:0000183',
 'nuclear-transcribed mRNA catabolic process, nonsense-mediated decay': 'GO:0000184',
 'obsolete activation of MAPKKK activity': 'GO:0000185',
 'obsolete activation of MAPKK activity': 'GO:0000186',
 'obsolete activation of MAPK activity': 'GO:0000187',
 'obsolete inactivation of MAPK activity': 'GO:0000188',
 'obsolete MAPK import into nucleus': 'GO:0000189',
 'obsolete MAPKKK cascade (pseudohyphal growth)': 'GO:0000190',
 'obsolete activation of MAPKKK (pseudohyphal growth)': 'GO:0000191',
 'obsolete activation of MAPKK (pseudohyphal growth)': 'GO:0000192',
 'obsolete activation of MAPK (pseudohyphal growth)': 'GO:0000193',
 'obsolete inactivation of MAPK (pseudohyphal growth)': 'GO:0000194',
 'obsolete nuclear translocation of MAPK (pseudohyphal growth)': 'GO:0000195',
 'cell integrity MAPK cascade': 'GO:0000196',
 'obsolete activation of MAPKKK activity involved in cell wall organization or biogenesis': 'GO:0000197',
 'obsolete activation of MAPKK activity involved in cell wall organization or biogenesis': 'GO:0000198',
 'obsolete activation of MAPK activity involved in cell wall organization or biogenesis': 'GO:0000199',
 'obsolete inactivation of MAPK activity involved in cell wall organization or biogenesis': 'GO:0000200',
 'obsolete MAPK import into nucleus involved in cell wall organization or biogenesis': 'GO:0000201',
 'obsolete MAPKKK cascade during sporulation (sensu Saccharomyces)': 'GO:0000202',
 'obsolete activation of MAPKKK during sporulation (sensu Saccharomyces)': 'GO:0000203',
 'obsolete activation of MAPKK during sporulation (sensu Saccharomyces)': 'GO:0000204',
 'obsolete activation of MAPK during sporulation (sensu Saccharomyces)': 'GO:0000205',
 'obsolete inactivation of MAPK during sporulation (sensu Saccharomyces)': 'GO:0000206',
 'obsolete nuclear translocation of MAPK during sporulation (sensu Saccharomyces)': 'GO:0000207',
 'obsolete MAPK import into nucleus involved in osmosensory signaling pathway': 'GO:0000208',
 'protein polyubiquitination': 'GO:0000209',
 'NAD+ diphosphatase activity': 'GO:0000210',
 'obsolete protein degradation tagging activity': 'GO:0000211',
 'meiotic spindle organization': 'GO:0000212',
 'tRNA-intron endonuclease activity': 'GO:0000213',
 'tRNA-intron endonuclease complex': 'GO:0000214',
 "tRNA 2'-phosphotransferase activity": 'GO:0000215',
 'obsolete M/G1 transition of mitotic cell cycle': 'GO:0000216',
 'DNA secondary structure binding': 'GO:0000217',
 'obsolete vacuolar hydrogen-transporting ATPase': 'GO:0000219',
 'vacuolar proton-transporting V-type ATPase, V0 domain': 'GO:0000220',
 'vacuolar proton-transporting V-type ATPase, V1 domain': 'GO:0000221',
 'plasma membrane proton-transporting V-type ATPase, V0 domain': 'GO:0000222',
 'plasma membrane proton-transporting V-type ATPase, V1 domain': 'GO:0000223',
 'peptide-N4-(N-acetyl-beta-glucosaminyl)asparagine amidase activity': 'GO:0000224',
 'N-acetylglucosaminylphosphatidylinositol deacetylase activity': 'GO:0000225',
 'microtubule cytoskeleton organization': 'GO:0000226',
 'obsolete oxaloacetate secondary active transmembrane transporter activity': 'GO:0000227',
 'nuclear chromosome': 'GO:0000228',
 'obsolete cytoplasmic chromosome': 'GO:0000229',
 'obsolete nuclear mitotic chromosome': 'GO:0000230',
 'obsolete cytoplasmic mitotic chromosome': 'GO:0000231',
 'obsolete nuclear interphase chromosome': 'GO:0000232',
 'obsolete cytoplasmic interphase chromosome': 'GO:0000233',
 'phosphoethanolamine N-methyltransferase activity': 'GO:0000234',
 'astral microtubule': 'GO:0000235',
 'mitotic prometaphase': 'GO:0000236',
 'leptotene': 'GO:0000237',
 'zygotene': 'GO:0000238',
 'pachytene': 'GO:0000239',
 'diplotene': 'GO:0000240',
 'diakinesis': 'GO:0000241',
 'pericentriolar material': 'GO:0000242',
 'commitment complex': 'GO:0000243',
 'spliceosomal tri-snRNP complex assembly': 'GO:0000244',
 'spliceosomal complex assembly': 'GO:0000245',
 'Delta24(24-1) sterol reductase activity': 'GO:0000246',
 'C-8 sterol isomerase activity': 'GO:0000247',
 'C-5 sterol desaturase activity': 'GO:0000248',
 'C-22 sterol desaturase (NADPH) activity': 'GO:0000249',
 'lanosterol synthase activity': 'GO:0000250',
 '3-beta-hydroxysteroid dehydrogenase [NAD(P)+]/C4-decarboxylase activity': 'GO:0000252',
 '3-beta-hydroxysteroid 3-dehydrogenase (NADP+) activity': 'GO:0000253',
 'C-4 methylsterol oxidase activity': 'GO:0000254',
 'allantoin metabolic process': 'GO:0000255',
 'allantoin catabolic process': 'GO:0000256',
 'nitrilase activity': 'GO:0000257',
 'obsolete isoleucine/valine:sodium symporter activity': 'GO:0000258',
 'obsolete intracellular nucleoside transmembrane transporter activity': 'GO:0000259',
 'obsolete hydrogen-translocating V-type ATPase activity': 'GO:0000260',
 'obsolete sodium-translocating V-type ATPase activity': 'GO:0000261',
 'mitochondrial chromosome': 'GO:0000262',
 'obsolete heterotrimeric G-protein GTPase, alpha-subunit': 'GO:0000263',
 'obsolete heterotrimeric G-protein GTPase, beta-subunit': 'GO:0000264',
 'obsolete heterotrimeric G-protein GTPase, gamma-subunit': 'GO:0000265',
 'mitochondrial fission': 'GO:0000266',
 'obsolete cell fraction': 'GO:0000267',
 'peroxisome targeting sequence binding': 'GO:0000268',
 'toxin export channel activity': 'GO:0000269',
 'peptidoglycan metabolic process': 'GO:0000270',
 'polysaccharide biosynthetic process': 'GO:0000271',
 'polysaccharide catabolic process': 'GO:0000272',
 'obsolete mitochondrial proton-transporting ATP synthase, stator stalk': 'GO:0000274',
 'obsolete mitochondrial proton-transporting ATP synthase complex, catalytic sector F(1)': 'GO:0000275',
 'obsolete mitochondrial proton-transporting ATP synthase complex, coupling factor F(o)': 'GO:0000276',
 '[cytochrome c]-lysine N-methyltransferase activity': 'GO:0000277',
 'mitotic cell cycle': 'GO:0000278',
 'M phase': 'GO:0000279',
 'nuclear division': 'GO:0000280',
 'mitotic cytokinesis': 'GO:0000281',
 'cellular bud site selection': 'GO:0000282',
 'obsolete shmoo orientation': 'GO:0000284',
 '1-phosphatidylinositol-3-phosphate 5-kinase activity': 'GO:0000285',
 'alanine dehydrogenase activity': 'GO:0000286',
 'magnesium ion binding': 'GO:0000287',
 'nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay': 'GO:0000288',
 'nuclear-transcribed mRNA poly(A) tail shortening': 'GO:0000289',
 'deadenylation-dependent decapping of nuclear-transcribed mRNA': 'GO:0000290',
 'obsolete nuclear-transcribed mRNA catabolic process, exonucleolytic': 'GO:0000291',
 'RNA fragment catabolic process': 'GO:0000292',
 'ferric-chelate reductase activity': 'GO:0000293',
 'nuclear-transcribed mRNA catabolic process, RNase MRP-dependent': 'GO:0000294',
 'adenine nucleotide transmembrane transporter activity': 'GO:0000295',
 'spermine transport': 'GO:0000296',
 'spermine transmembrane transporter activity': 'GO:0000297',
 'endopolyphosphatase activity': 'GO:0000298',
 'obsolete integral to membrane of membrane fraction': 'GO:0000299',
 'obsolete peripheral to membrane of membrane fraction': 'GO:0000300',
 'retrograde transport, vesicle recycling within Golgi': 'GO:0000301',
 'response to reactive oxygen species': 'GO:0000302',
 'response to superoxide': 'GO:0000303',
 'response to singlet oxygen': 'GO:0000304',
 'response to oxygen radical': 'GO:0000305',
 'obsolete extrinsic component of vacuolar membrane': 'GO:0000306',
 'cyclin-dependent protein kinase holoenzyme complex': 'GO:0000307',
 'cytoplasmic cyclin-dependent protein kinase holoenzyme complex': 'GO:0000308',
 'nicotinamide-nucleotide adenylyltransferase activity': 'GO:0000309',
 'xanthine phosphoribosyltransferase activity': 'GO:0000310',
 'plastid large ribosomal subunit': 'GO:0000311',
 'plastid small ribosomal subunit': 'GO:0000312',
 'organellar ribosome': 'GO:0000313',
 'organellar small ribosomal subunit': 'GO:0000314',
 'organellar large ribosomal subunit': 'GO:0000315',
 'sulfite transmembrane transport': 'GO:0000316',
 'sulfite transmembrane transporter activity': 'GO:0000319',
 're-entry into mitotic cell cycle': 'GO:0000320',
 're-entry into mitotic cell cycle after pheromone arrest': 'GO:0000321',
 'storage vacuole': 'GO:0000322',
 'lytic vacuole': 'GO:0000323',
 'fungal-type vacuole': 'GO:0000324',
 'plant-type vacuole': 'GO:0000325',
 'protein storage vacuole': 'GO:0000326',
 'lytic vacuole within protein storage vacuole': 'GO:0000327',
 'fungal-type vacuole lumen': 'GO:0000328',
 'fungal-type vacuole membrane': 'GO:0000329',
 'plant-type vacuole lumen': 'GO:0000330',
 'contractile vacuole': 'GO:0000331',
 'template for synthesis of G-rich strand of telomere DNA activity': 'GO:0000332',
 'telomerase catalytic core complex': 'GO:0000333',
 '3-hydroxyanthranilate 3,4-dioxygenase activity': 'GO:0000334',
 'obsolete negative regulation of transposition, DNA-mediated': 'GO:0000335',
 'obsolete positive regulation of transposition, DNA-mediated': 'GO:0000336',
 'obsolete regulation of transposition, DNA-mediated': 'GO:0000337',
 'protein deneddylation': 'GO:0000338',
 'RNA cap binding': 'GO:0000339',
 'RNA 7-methylguanosine cap binding': 'GO:0000340',
 'RNA trimethylguanosine cap binding': 'GO:0000341',
 'RNA cap 4 binding': 'GO:0000342',
 'plastid-encoded plastid RNA polymerase complex A': 'GO:0000343',
 'plastid-encoded plastid RNA polymerase complex B': 'GO:0000344',
 'cytosolic DNA-directed RNA polymerase complex': 'GO:0000345',
 'transcription export complex': 'GO:0000346',
 'THO complex': 'GO:0000347',
 'mRNA branch site recognition': 'GO:0000348',
 'generation of catalytic spliceosome for first transesterification step': 'GO:0000349',
 'generation of catalytic spliceosome for second transesterification step': 'GO:0000350',
 'trans assembly of SL-containing precatalytic spliceosome': 'GO:0000352',
 'formation of quadruple SL/U4/U5/U6 snRNP': 'GO:0000353',
 'cis assembly of pre-catalytic spliceosome': 'GO:0000354',
 'obsolete first U2-type spliceosomal transesterification activity': 'GO:0000362',
 'obsolete first U12-type spliceosomal transesterification activity': 'GO:0000363',
 'obsolete second U2-type spliceosomal transesterification activity': 'GO:0000364',
 'mRNA trans splicing, via spliceosome': 'GO:0000365',
 'mRNA alternative trans-splicing': 'GO:0000366',
 'obsolete second U12-type spliceosomal transesterification activity': 'GO:0000367',
 'Group I intron splicing': 'GO:0000372',
 'Group II intron splicing': 'GO:0000373',
 'Group III intron splicing': 'GO:0000374',
 'RNA splicing, via transesterification reactions': 'GO:0000375',
 'RNA splicing, via transesterification reactions with guanosine as nucleophile': 'GO:0000376',
 'RNA splicing, via transesterification reactions with bulged adenosine as nucleophile': 'GO:0000377',
 'RNA exon ligation': 'GO:0000378',
 'tRNA-type intron splice site recognition and cleavage': 'GO:0000379',
 'alternative mRNA splicing, via spliceosome': 'GO:0000380',
 'regulation of alternative mRNA splicing, via spliceosome': 'GO:0000381',
 'first spliceosomal transesterification activity': 'GO:0000384',
 'second spliceosomal transesterification activity': 'GO:0000386',
 'spliceosomal snRNP assembly': 'GO:0000387',
 'spliceosome conformational change to release U4 (or U4atac) and U1 (or U11)': 'GO:0000388',
 "mRNA 3'-splice site recognition": 'GO:0000389',
 'spliceosomal complex disassembly': 'GO:0000390',
 'spliceosomal conformational changes to generate catalytic conformation': 'GO:0000393',
 'RNA splicing, via endonucleolytic cleavage and ligation': 'GO:0000394',
 "mRNA 5'-splice site recognition": 'GO:0000395',
 'mRNA splicing, via spliceosome': 'GO:0000398',
 'cellular bud neck septin structure': 'GO:0000399',
 'four-way junction DNA binding': 'GO:0000400',
 'open form four-way junction DNA binding': 'GO:0000401',
 'crossed form four-way junction DNA binding': 'GO:0000402',
 'Y-form DNA binding': 'GO:0000403',
 'heteroduplex DNA loop binding': 'GO:0000404',
 'bubble DNA binding': 'GO:0000405',
 'double-strand/single-strand DNA junction binding': 'GO:0000406',
 'phagophore assembly site': 'GO:0000407',
 'EKC/KEOPS complex': 'GO:0000408',

In [10]:
NCBI_Yeast_gene = pd.read_csv(f'{BASE_PATH}databases_for_mapping/ncbi/Saccharomyces_cerevisiae.gene_info',sep = '\t')
NCBI_Yeast_gene

NCBI_Yeast_gene_Locus_2_GeneSymd_ict = dict(zip(NCBI_Yeast_gene['LocusTag'], NCBI_Yeast_gene['Symbol']))
NCBI_Yeast_gene_Locus_2_GeneSymd_ict
NCBI_Yeast_Locustag_Descrip_dict = dict(zip(NCBI_Yeast_gene['LocusTag'], NCBI_Yeast_gene['description']))
NCBI_Yeast_Locustag_Descrip_dict

{'-': 'Record to support submission of GeneRIFs for a gene not in Gene.',
 'ACI60_gp06': 'Atp6',
 'ACI60_gt03': 'tRNA-Glu',
 'ACI60_gt04': 'tRNA-Ser',
 'ACI60_gr01': 'large subunit ribosomal RNA',
 'ACI60_gt21': 'tRNA-Phe',
 'ACI60_gt24': 'tRNA-Met',
 'ACI60_gp04': 'Atp9',
 'ACI60_gp07': 'Atp8',
 'ACI60_gr02': 'small subunit ribosomal RNA',
 'ACI60_gt02': 'tRNA-Trp',
 'ACI60_gp08': 'cytochrome c oxidase subunit 1',
 'ACI60_gp05': 'cytochrome b',
 'ACI60_gp03': 'ribosomal protein S3',
 'ACI60_gt05': 'tRNA-Thr',
 'ACI60_gt06': 'tRNA-Cys',
 'ACI60_gt07': 'tRNA-His',
 'ACI60_gt08': 'tRNA-Leu',
 'ACI60_gt09': 'tRNA-Gln',
 'ACI60_gt10': 'tRNA-Lys',
 'ACI60_gt11': 'tRNA-Arg',
 'ACI60_gt12': 'tRNA-Gly',
 'ACI60_gt13': 'tRNA-Asp',
 'ACI60_gt14': 'tRNA-Ser',
 'ACI60_gt15': 'tRNA-Arg',
 'ACI60_gt16': 'tRNA-Ala',
 'ACI60_gt17': 'tRNA-Ile',
 'ACI60_gt18': 'tRNA-Tyr',
 'ACI60_gt19': 'tRNA-Asn',
 'ACI60_gt20': 'tRNA-Met',
 'ACI60_gp02': 'cytchrome c oxidase sububnit 2',
 'ACI60_gt22': 'tRNA-Thr',
 'ACI60_gt23': 'tRNA-Val',
 'ACI60_gp01': 'cytchrome c oxidase sububnit 3',
 'ACI60_gs01': 'ncRNA',
 'ACI60_gt01': 'tRNA-Pro',
 'YCL075W': 'pseudo',
 'YCL074W': 'pseudo',
 'YCL073C': 'glutathione exchanger',
 'YCL069W': 'basic amino acid transporter',
 'YCL068C': 'uncharacterized protein',
 'YCL067C': 'homeodomain mating type protein alpha2',
 'YCL066W': 'transcriptional co-activator mating type protein alpha',
 'YCL064C': 'L-serine/L-threonine ammonia-lyase CHA1',
 'YCL063W': 'Vac17p',
 'YCL061C': 'chromatin-modulating protein MRC1',
 'YCL059C': 'ribosome biosynthesis protein KRR1',
 'YCL058C': 'Fyv5p',
 'YCL057C-A': 'Mic10p',
 'YCL057W': 'metalloendopeptidase',
 'YCL056C': 'Pex34p',
 'YCL055W': 'Kar4p',
 'YCL054W': "27S pre-rRNA (guanosine2922-2'-O)-methyltransferase",
 'YCL052C': 'Pbn1p',
 'YCL051W': 'Lre1p',
 'YCL050C': 'bifunctional AP-4-A phosphorylase/ADP sulfurylase',
 'YCL049C': 'uncharacterized protein',
 'YCL048W': 'Sps22p',
 'YCL047C': 'nicotinamide-nucleotide adenylyltransferase',
 'YCL045C': 'Emc1p',
 'YCL044C': 'Mgr1p',
 'YCL043C': 'protein disulfide isomerase PDI1',
 'YCL042W': 'uncharacterized protein',
 'YCL040W': 'glucokinase',
 'YCL039W': 'glucose-induced degradation complex subunit GID7',
 'YCL038C': 'Atg22p',
 'YCL037C': 'Sro9p',
 'YCL036W': 'Gfd2p',
 'YCL035C': 'dithiol glutaredoxin GRX1',
 'YCL034W': 'Lsb5p',
 'YCL033C': 'peptide-methionine (R)-S-oxide reductase',
 'YCL032W': 'Ste50p',
 'YCL031C': 'Rrp7p',
 'YCL030C': 'trifunctional histidinol dehydrogenase/phosphoribosyl-AMP cyclohydrolase/phosphoribosyl-ATP diphosphatase',
 'YCL029C': 'Bik1p',
 'YCL028W': 'prion domain-containing protein RNQ1',
 'YCL027W': 'Fus1p',
 'YCL026C-B': 'putative nitroreductase',
 'YCL026C-A': 'type II nitroreductase',
 'YCL025C': 'amino acid transporter AGP1',
 'YCL024W': 'serine/threonine protein kinase',
 'YNCC0001C': 'tRNA-Glu',
 'YCL021W-A': 'uncharacterized protein',
 'YCL020W': 'gag protein',
 'YCL019W': 'gag-pol fusion protein',
 'YNCC0002W': 'tRNA-Leu',
 'YCL018W': '3-isopropylmalate dehydrogenase',
 'YCL017C': 'cysteine desulfurase',
 'YCL016C': 'Dcc1p',
 'YCL014W': 'Bud3p',
 'YCL011C': 'single-stranded telomeric DNA-binding/mRNA-binding protein',
 'YCL010C': 'Sgf29p',
 'YCL009C': 'acetolactate synthase regulatory subunit',
 'YCL008C': 'ubiquitin-binding ESCRT-I subunit protein STP22',
 'YCL005W': 'Ldb16p',
 'YCL004W': 'CDP-diacylglycerol--glycerol-3-phosphate 3-phosphatidyltransferase',
 'YCL002C': 'uncharacterized protein',
 'YCL001W': 'protein retrieval receptor',
 'YCL001W-A': 'uncharacterized protein',
 'YCL001W-B': 'uncharacterized protein',
 'YCR001W': 'uncharacterized protein',
 'YCR002C': 'septin CDC10',
 'YCR003W': 'mitochondrial 54S ribosomal protein YmL32',
 'YCR004C': 'flavodoxin-like fold family protein',
 'YCR005C': 'citrate (Si)-synthase CIT2',
 'YCR006C': 'uncharacterized protein',
 'YNCC0004C': 'tRNA-Pro',
 'YCR007C': 'DUP240 family protein',
 'YNCC0005W': 'tRNA-Asn',
 'YCR008W': 'serine/threonine protein kinase SAT4',
 'YCR009C': 'amphiphysin-like protein RVS161',
 'YCR010C': 'Ady2p',
 'YCR011C': 'putative ATP-dependent permease ADP1',
 'YCR012W': 'phosphoglycerate kinase',
 'YCR014C': 'DNA-directed DNA polymerase IV',
 'YCR015C': 'Cto1p',
 'YNCC0007C': 'tRNA-Gly',
 'YCR016W': 'RNA-binding ribosome assembly factor RBP95',
 'YCR017C': 'Cwh43p',
 'YCR018C': 'Srd1p',
 'YNCC0008W': 'tRNA-Met',
 'YNCC0009C': 'tRNA-Lys',
 'YCR019W': 'Mak32p',
 'YCR020C': 'Pet18p',
 'YCR020C-A': 'Mak31p',
 'YCR020W-B': 'Htl1p',
 'YCR021C': 'Hsp30p',
 'YCR022C': 'uncharacterized protein',
 'YCR023C': 'uncharacterized protein',
 'YCR024C': 'asparagine--tRNA ligase SLM5',
 'YCR024C-A': 'proteolipid ATPase',
 'YCR025C': 'uncharacterized protein',
 'YCR026C': 'nucleotide diphosphatase/phosphodiesterase NPP1',
 'YCR027C': 'putative GTPase RHB1',
 'YNCC0010C': 'tRNA-Gln',
 'YCR028C': 'Fen2p',
 'YCR028C-A': 'Rim1p',
 'YCR030C': 'Syp1p',
 'YCR031C': 'ribosomal 40S subunit protein S14A',
 'YCR032W': 'Bph1p',
 'YCR033W': 'Snt1p',
 'YCR034W': 'fatty acid elongase ELO2',
 'YCR035C': 'exosome non-catalytic core subunit RRP43',
 'YCR036W': 'putative ribokinase',
 'YCR037C': 'SPX domain-containing inorganic phosphate transporter',
 'YCR038C': 'Ras family guanine nucleotide exchange factor BUD5',
 'YCR039C': 'homeodomain mating type protein alpha2',
 'YCR040W': 'transcriptional co-activator mating type protein alpha',
 'YCR041W': 'uncharacterized protein',
 'YCR042C': 'transcription initiation factor TFIID subunit TAF2',
 'YCR043C': 'uncharacterized protein',
 'YCR044C': 'Per1p',
 'YCR045C': 'Rrt12p',
 'YCR046C': 'mitochondrial 54S ribosomal protein IMG1',
 'YCR047C': '18S rRNA (guanine1575-N7)-methyltransferase',
 'YCR048W': 'sterol acyltransferase',
 'YCR050C': 'uncharacterized protein',
 'YCR051W': 'uncharacterized protein',
 'YCR052W': 'Rsc6p',
 'YCR053W': 'threonine synthase THR4',
 'YCR054C': 'Ctr86p',
 'YCR057C': 'snoRNA-binding rRNA-processing protein PWP2',
 'YCR059C': 'Yih1p',
 'YCR060W': 'Tah1p',
 'YCR061W': 'Tvs1p',
 'YNCC0013W': 'tRNA-Ser',
 'YCR063W': 'U2 snRNP complex subunit BUD31',
 'YCR065W': 'Hcm1p',
 'YCR066W': 'E3 ubiquitin-protein ligase RAD18',
 'YCR067C': 'GTPase-activating protein SED4',
 'YCR068W': 'triglyceride lipase ATG15',
 'YCR069W': 'peptidylprolyl isomerase family protein CPR4',
 'YCR071C': 'mitochondrial 54S ribosomal protein IMG2',
 'YCR072C': 'Rsa4p',
 'YCR073C': 'mitogen-activated protein kinase kinase kinase SSK22',
 'YCR073W-A': 'Sol2p',
 'YCR075C': 'cystinosin-like protein ERS1',
 'YCR076C': 'Fub1p',
 'YCR077C': 'deadenylation-dependent mRNA-decapping factor PAT1',
 'YCR079W': 'type 2C protein phosphatase PTC6',
 'YCR081W': 'Srb8p',
 'YCR082W': 'Ahc2p',
 'YCR083W': 'Trx3p',
 'YCR084C': 'chromatin-silencing transcriptional regulator TUP1',
 'YCR085W': 'uncharacterized protein',
 'YCR086W': 'Csm1p',
 'YCR087C-A': 'uncharacterized protein',
 'YCR088W': 'Abp1p',
 'YCR089W': 'Fig2p',
 'YCR090C': 'uncharacterized protein',
 'YCR091W': 'putative serine/threonine protein kinase KIN82',
 'YCR092C': 'mismatch repair protein MSH3',
 'YCR093W': 'CCR4-NOT core subunit CDC39',
 'YCR094W': 'aminophospholipid translocase regulatory protein CDC50',
 'YCR095C': 'Oca4p',
 'YCR096C': 'homeodomain mating type protein a2',
 'YCR097W': 'Hmra1p',
 'YNCC0014W': 'tRNA-Thr',
 'YCR098C': 'Git1p',
 'YCR099C': 'uncharacterized protein',
 'YCR100C': 'Ema35p',
 'YCR101C': 'uncharacterized protein',
 'YCR102C': 'uncharacterized protein',
 'YCR104W': 'seripauperin PAU3',
 'YCR105W': 'NADP-dependent alcohol dehydrogenase',
 'YCR106W': 'Rds1p',
 'YCR107W': 'putative aryl-alcohol dehydrogenase',
 'YFL068W': 'uncharacterized protein',
 'YFL067W': 'uncharacterized protein',
 'YFL066C': "Y' element ATP-dependent helicase",
 'YFL065C': 'uncharacterized protein',
 'YFL064C': 'uncharacterized protein',
 'YFL062W': 'Cos4p',
 'YFL061W': 'cyanamide hydratase',
 'YFL060C': "putative pyridoxal 5'-phosphate synthase",
 'YFL059W': 'pyridoxine biosynthesis protein SNZ3',
 'YFL058W': '4-amino-5-hydroxymethyl-2-methylpyrimidine phosphate synthase',
 'YFL056C': 'pseudo',
 'YFL055W': 'Agp3p',
 'YFL054C': 'Aqy3p',
 'YFL053W': 'dihydroxyacetone kinase',
 'YFL052W': 'DNA-binding domain containing protein',
 'YFL051C': 'uncharacterized protein',
 'YFL050C': 'putative Mg(2+) transporter ALR2',
 'YFL049W': 'Swp82p',
 'YFL048C': 'Emp47p',
 'YFL047W': 'GTPase-activating protein RGD2',
 'YFL046W': 'Fmp32p',
 'YFL045C': 'phosphomannomutase SEC53',
 'YFL044C': 'ubiquitin-specific protease OTU1',
 'YFL042C': 'Lam5p',
 'YFL041W': 'ferroxidase FET5',
 'YFL040W': 'uncharacterized protein',
 'YFL039C': 'actin',
 'YFL038C': 'Rab family GTPase YPT1',
 'YFL037W': 'beta-tubulin',
 'YFL036W': 'DNA-directed RNA polymerase',
 'YFL034C-B': 'Mob2p',
 'YFL034C-A': 'ribosomal 60S subunit protein L22B',
 'YFL034W': 'Mil1p',
 'YFL033C': 'protein kinase RIM15',
 'YFL031W': 'transcription factor HAC1',
 'YFL030W': 'alanine--glyoxylate transaminase',
 'YFL029C': 'cyclin-dependent protein kinase-activating kinase CAK1',
 'YFL028C': 'putative ATP-binding cassette family ATPase CAF16',
 'YFL027C': 'GTPase-activating protein GYP8',
 'YFL026W': 'alpha-factor pheromone receptor STE2',
 'YFL025C': 'Bst1p',
 'YFL024C': 'Epl1p',
 'YFL023W': 'prefoldin-like protein',
 'YFL022C': 'phenylalanine--tRNA ligase subunit alpha',
 'YFL021W': 'Gat1p',
 'YFL020C': 'seripauperin PAU5',
 'YFL019C': 'uncharacterized protein',
 'YNCF0002W': 'tRNA-Pro',
 'YFL018C': 'dihydrolipoyl dehydrogenase',
 'YFL017W-A': 'mRNA splicing protein SMX2',
 'YFL017C': 'glucosamine 6-phosphate N-acetyltransferase',
 'YFL016C': 'Mdj1p',
 'YFL015C': 'uncharacterized protein',
 'YFL014W': 'lipid-binding protein HSP12',
 'YFL013C': 'Ies1p',
 'YFL012W': 'uncharacterized protein',
 'YFL011W': 'hexose transporter HXT10',
 'YFL010W-A': 'Aua1p',
 'YFL010C': 'Wwm1p',
 'YFL009W': 'SCF ubiquitin ligase complex subunit CDC4',
 'YFL008W': 'cohesin subunit SMC1',
 'YFL007W': 'proteasome activator BLM10',
 'YFL005W': 'Rab family GTPase SEC4',
 'YFL004W': 'vacuolar transporter chaperone',
 'YFL003C': 'MutS family protein MSH4',
 'YNCF0004C': 'tRNA-Asn',
 'YFL002W-B': 'gag protein',
 'YFL002W-A': 'gag-pol fusion protein',
 'YFL002C': 'ATP-dependent RNA helicase SPB4',
 'YFL001W': 'pseudouridine synthase DEG1',
 'YFR001W': 'Loc1p',
 'YFR002W': 'linker nucleoporin NIC96',
 'YFR003C': 'type 1 protein phosphatase-activating protein YPI1',
 'YFR004W': 'proteasome regulatory particle lid subunit RPN11',
 'YFR005C': 'mRNA splicing protein SAD1',
 'YFR006W': 'putative Xaa-Pro dipeptidase',
 'YNCF0005C': 'tRNA-Phe',
 'YFR007W': 'Yfh7p',
 'YFR008W': 'Far7p',
 'YNCF0006W': 'tRNA-Gly',
 'YFR009W': 'putative AAA family ATPase GCN20',
 'YFR010W': 'ubiquitin-specific protease UBP6',
 'YFR011C': 'Mic19p',
 'YNCF0007W': 'tRNA-Tyr',
 'YFR012W': 'Dcv1p',
 'YFR012W-A': 'uncharacterized protein',
 'YFR013W': 'Ioc3p',
 'YFR014C': 'calmodulin-dependent protein kinase CMK1',
 'YFR015C': 'glycogen (starch) synthase GSY1',
 'YFR016C': 'Aip5p',
 'YNCF0008C': 'tRNA-Gly',
 'YFR017C': 'Igd1p',
 'YFR018C': 'uncharacterized protein',
 'YFR019W': '1-phosphatidylinositol-3-phosphate 5-kinase',
 'YNCF0009C': 'tRNA-Ser',
 'YFR020W': 'Css2p',
 'YFR021W': 'phosphoinositide binding protein ATG18',
 'YFR022W': 'Rog3p',
 'YFR023W': 'Pes4p',
 'YFR024C-A': 'Lsb3p',
 'YFR025C': 'histidinol-phosphatase',
 'YNCF0011C': 'tRNA-Ala',
 'YFR026C': 'Uli1p',
 'YFR027W': 'Eco1p',
 'YFR028C': 'phosphoprotein phosphatase CDC14',
 'YNCF0012C': 'tRNA-Tyr',
 'YFR029W': 'Ptr3p',
 'YFR030W': 'sulfite reductase subunit alpha',
 'YFR031C': 'condensin subunit SMC2',
 'YFR031C-A': 'ribosomal 60S subunit protein L2A',
 'YFR032C': 'Rrt5p',
 'YFR032C-A': 'ribosomal 60S subunit protein L29',
 'YFR033C': 'ubiquinol--cytochrome-c reductase subunit 6',
 'YFR034C': 'phosphate-sensing transcription factor PHO4',
 'YFR035C': 'uncharacterized protein',
 'YNCF0014C': 'tRNA-Lys',
 'YFR036W': 'anaphase promoting complex subunit CDC26',
 'YFR037C': 'Rsc8p',
 'YFR038W': 'putative ATPase',
 'YFR039C': 'Osw7p',
 'YFR040W': 'Sap155p',
 'YFR041C': 'Erj5p',
 'YFR042W': 'Keg1p',
 'YFR043C': 'Irc6p',
 'YFR044C': 'metallodipeptidase',
 'YFR045W': 'Mrx20p',
 'YFR046C': 'centromere-binding protein CNN1',
 'YFR047C': 'nicotinate-nucleotide diphosphorylase (carboxylating)',
 'YFR048W': 'Rmd8p',
 'YFR049W': 'alpha-ketoglutarate dehydrogenase subunit KGD4',
 'YFR050C': 'proteasome core particle subunit beta 7',
 'YFR051C': 'coatomer subunit delta',
 'YFR052W': 'proteasome regulatory particle lid subunit RPN12',
 'YFR053C': 'hexokinase 1',
 'YFR054C': 'uncharacterized protein',
 'YFR055W': 'cysteine-S-conjugate beta-lyase IRC7',
 'YFR057W': 'uncharacterized protein',
 'YLL040C': 'membrane morphogenesis protein VPS13',
 'YLL039C': 'ubiquitin',
 'YLL038C': 'Ent4p',
 'YLL036C': 'E3 ubiquitin-protein ligase PRP19',
 'YLL035W': "polynucleotide 5'-hydroxyl-kinase",
 'YLL034C': 'putative AAA family ATPase RIX7',
 'YLL033W': 'Irc19p',
 'YLL032C': 'uncharacterized protein',
 'YLL031C': 'mannose-ethanolamine phosphotransferase GPI13',
 'YLL030C': 'Rrt7p',
 'YLL029W': 'aminopeptidase P',
 'YLL028W': 'polyamine transporter TPO1',
 'YLL027W': 'Fe-binding Fe/S cluster assembly protein ISA1',
 'YLL026W': 'chaperone ATPase HSP104',
 'YNCL0001W': 'tRNA-Pro',
 'YLL025W': 'seripauperin PAU17',
 'YLL024C': 'Hsp70 family chaperone SSA2',
 'YLL023C': 'nucleoporin POM33',
 'YLL022C': 'Hif1p',
 'YLL021W': 'Spa2p',
 'YLL019C': 'serine/threonine protein kinase KNS1',
 'YLL018C-A': 'Cox19p',
 'YLL018C': 'aspartate--tRNA ligase DPS1',
 'YLL016W': 'pseudo',
 'YLL015W': 'ATP-binding cassette bilirubin transporter BPT1',
 'YLL014W': 'Emc6p',
 'YLL013C': 'mRNA-binding protein PUF3',
 'YLL012W': 'sterol esterase',
 'YLL011W': 'rRNA-processing protein SOF1',
 'YLL010C': 'phosphatase',
 'YLL009C': 'copper metallochaperone COX17',
 'YLL008W': 'putative ATP-dependent RNA helicase',
 'YLL007C': 'Lmo1p',
 'YLL006W': 'ERMES complex subunit MMM1',
 'YLL005C': 'Spo75p',
 'YLL004W': 'origin recognition complex subunit 3',
 'YLL003W': 'Sfi1p',
 'YLL002W': 'H3 histone acetyltransferase RTT109',
 'YLL067C': "Y' element ATP-dependent helicase",
 'YLL066C': "Y' element ATP-dependent helicase",
 'YLL064C': 'seripauperin PAU18',
 'YLL063C': 'acetyltransferase',
 'YLL062C': 'S-adenosylmethionine-homocysteine S-methyltransferase MHT1',
 'YLL061W': 'S-methylmethionine permease MMP1',
 'YLL060C': 'glutathione transferase GTT2',
 'YLL058W': 'cystathionine gamma-synthase',
 'YLL057C': 'sulfonate dioxygenase',
 'YLL056C': 'uncharacterized protein',
 'YLL055W': 'Yct1p',
 'YLL054C': 'uncharacterized protein',
 'YLL053C': 'uncharacterized protein',
 'YLL052C': 'Aqy2p',
 'YLL051C': 'putative ferric-chelate reductase',
 'YLL050C': 'cofilin',
 'YLL049W': 'Ldb18p',
 'YLL048C': 'bile acid-transporting ATPase YBT1',
 'YLL046C': 'Rnp1p',
 'YLL045C': 'ribosomal 60S subunit protein L8B',
 'YLL043W': 'Fps1p',
 'YLL042C': 'E2-like conjugating enzyme',
 'YLL041C': 'succinate dehydrogenase iron-sulfur protein subunit SDH2',
 'YLL001W': 'dynamin-related GTPase DNM1',
 'YLR001C': 'uncharacterized protein',
 'YLR002C': 'Noc3p',
 'YLR003C': 'Cms1p',
 'YLR004C': 'Thi73p',
 'YLR005W': 'TFIIH/NER complex subunit SSL1',
 'YLR006C': 'mitogen-activated protein kinase kinase kinase SSK1',
 'YLR007W': 'Smc5-Smc6 complex subunit NSE1',
 'YLR008C': 'Pam18p',
 'YLR009W': 'ATPase-activating ribosome biosynthesis protein',
 'YLR010C': 'Ten1p',
 'YNCL0002C': 'tRNA-Ser',
 'YLR011W': 'flavin-dependent quinone reductase',
 'YLR012C': 'uncharacterized protein',
 'YLR013W': 'Gat3p',
 'YLR014C': 'Ppr1p',
 'YLR015W': 'Bre2p',
 'YLR016C': 'Pml1p',
 'YLR017W': 'S-methyl-5-thioadenosine phosphorylase',
 'YLR018C': 'Pom34p',
 'YLR019W': 'putative phosphatase',
 'YLR020C': 'sterol esterase',
 'YLR021W': 'Irc25p',
 'YLR022C': 'guanine nucleotide exchange factor SDO1',
 'YLR023C': 'Izh3p',
 'YLR024C': 'putative ubiquitin-protein ligase UBR2',
 'YLR025W': 'ESCRT-III subunit protein SNF7',
 'YLR026C': 't-SNARE syntaxin',
 'YLR027C': 'aspartate transaminase AAT2',
 'YLR028C': 'bifunctional phosphoribosylaminoimidazolecarboxamide formyltransferase/IMP cyclohydrolase ADE16',
 'YLR029C': 'ribosomal 60S subunit protein L15A',
 'YLR030W': 'uncharacterized protein',
 'YLR031W': 'uncharacterized protein',
 'YLR032W': 'DNA helicase RAD5',
 'YLR033W': 'Rsc58p',
 'YLR034C': 'putative divalent metal ion transporter SMF3',
 'YLR035C': 'mismatch repair protein MLH2',
 'YNCL0004C': 'tRNA-Ala',
 'YLR035C-A': 'gag-pol fusion protein',
 'YLR036C': 'uncharacterized protein',
 'YLR037C': 'seripauperin PAU23',
 'YLR038C': 'cytochrome c oxidase subunit VIb',
 'YLR039C': 'Ric1p',
 'YLR040C': 'Afb1p',
 'YLR042C': 'Nfg1p',
 'YLR043C': 'thioredoxin TRX1',
 'YLR044C': 'indolepyruvate decarboxylase 1',
 'YLR045C': 'Stu2p',
 'YLR046C': 'uncharacterized protein',
 'YLR047C': 'putative ferric-chelate reductase',
 'YLR048W': 'ribosomal 40S subunit protein S0B',
 'YLR049C': 'Mlo50p',
 'YLR050C': 'Ema19p',
 'YLR051C': 'Fcf2p',
 'YLR052W': 'Ies3p',
 'YLR053C': 'Nrs1p',
 'YLR054C': 'Osw2p',
 'YLR055C': 'SAGA complex subunit SPT8',
 'YLR056W': 'C-5 sterol desaturase',
 'YLR057W': 'putative mannosidase MNL2',
 'YLR058C': 'glycine hydroxymethyltransferase SHM2',
 'YLR059C': 'Rex2p',
 'YLR060W': 'phenylalanine--tRNA ligase subunit beta',
 'YLR061W': 'ribosomal 60S subunit protein L22A',
 'YLR063W': '25S rRNA (uracil2843-N3)-methyltransferase',
 'YLR064W': 'Per33p',
 'YLR065C': 'Snd2p',
 'YLR066W': 'signal peptidase complex subunit SPC3',
 'YLR067C': 'Pet309p',
 'YLR068W': 'Fyv7p',
 'YLR069C': 'Mef1p',
 'YLR070C': 'D-xylulose reductase XYL2',
 'YLR071C': 'Rgr1p',
 'YLR072W': 'Lam6p',
 'YLR073C': 'Rfu1p',
 'YLR074C': 'Bud20p',
 'YLR075W': 'ribosomal 60S subunit protein L10',
 'YLR077W': 'Fmp25p',
 'YLR078C': 'Bos1p',
 'YLR079W': 'cyclin-dependent protein serine/threonine kinase inhibiting protein SIC1',
 'YLR080W': 'Emp46p',
 'YLR081W': 'galactose permease GAL2',
 'YLR082C': 'Srl2p',
 'YLR083C': 'Emp70p',
 'YLR084C': 'Rax2p',
 'YLR085C': 'Arp6p',
 'YLR086W': 'condensin subunit SMC4',
 'YLR087C': 'Csf1p',
 'YLR088W': 'GPI-anchor transamidase subunit GAA1',
 'YLR089C': 'alanine transaminase ALT1',
 'YLR090W': 'Xdj1p',
 'YLR091W': 'Gep5p',
 'YLR092W': 'sulfate permease',
 'YLR093C': 'Nyv1p',
 'YLR094C': 'Gis3p',
 'YLR095C': 'Ioc2p',
 'YLR096W': 'serine/threonine protein kinase KIN2',
 'YLR097C': 'SCF ubiquitin ligase complex subunit HRT3',
 'YLR098C': 'Cha4p',
 'YLR099C': 'lysophosphatidic acid acyltransferase ICT1',
 'YLR099W-A': 'Mim2p',
 'YLR100W': '3-keto-steroid reductase',
 'YLR102C': 'anaphase promoting complex subunit 9',
 'YLR103C': 'DNA replication initiation factor CDC45',
 'YLR104W': 'Lcl2p',
 'YLR105C': 'tRNA splicing endonuclease subunit SEN2',
 'YLR106C': 'AAA family ATPase midasin',
 'YLR107W': 'RNA exonuclease',
 'YLR108C': 'uncharacterized protein',
 'YLR109W': 'thioredoxin peroxidase AHP1',
 'YLR110C': 'Ccw12p',
 'YLR111W': 'uncharacterized protein',
 'YLR112W': 'uncharacterized protein',
 'YLR113W': 'mitogen-activated protein kinase HOG1',
 'YNCL0007W': 'tRNA-Arg',
 'YLR114C': 'Avl9p',
 'YLR115W': 'cleavage polyadenylation factor subunit CFT2',
 'YLR116W': 'mRNA splicing protein MSL5',
 'YLR117C': 'Clf1p',
 'YLR118C': 'palmitoyl-(protein) hydrolase',
 'YLR119W': 'ESCRT-I subunit protein SRN2',
 'YLR120C': 'aspartyl protease',
 'YLR121C': 'aspartyl protease',
 'YLR122C': 'uncharacterized protein',
 'YLR125W': 'uncharacterized protein',
 'YLR126C': 'putative amidotransferase',
 'YLR127C': 'anaphase promoting complex subunit 2',
 'YLR128W': 'NEDD8 ligase DCN1',
 'YLR129W': 'snoRNA-binding rRNA-processing protein DIP2',
 'YLR130C': 'low-affinity Zn(2+) transporter ZRT2',
 'YLR131C': 'DNA-binding transcription factor ACE2',
 'YLR132C': 'phosphoric diester hydrolase',
 'YLR133W': 'bifunctional choline kinase/ethanolamine kinase CKI1',
 'YLR134W': 'indolepyruvate decarboxylase 5',
 'YLR135W': 'Slx4p',
 'YLR136C': 'Tis11p',

# Gene_Tissue

In [12]:
yeast_gene_SL = f'{BASE_PATH}eSLDB/YEAST_GENE_SL_withSEQ.pkl'
Y_G_SL = pd.read_pickle(yeast_gene_SL)
Y_G_SL['tail'] = Y_G_SL['tail'].str.lower()
# Y_G_SL['BTO'] = Y_G_SL['tail'].map(BTO_Dict)
# Y_G_SL['Uber'] = Y_G_SL['tail'].map(Anatomy_dict

Y_G_SL['tail_type'] = 'CellularComponent'
Y_G_SL['head_type'] = 'Gene'
Y_G_SL['relation'] = 'Gene_CellularComponent'
Y_G_SL['relation_type'] = np.nan
Y_G_SL['kg_source'] = 'GenePatri'
Y_G_SL['head_detail_name'] = Y_G_SL['head'].astype(str).map(NCBI_Yeast_Locustag_Descrip_dict)
Y_G_SL['tail_detail_name'] = Y_G_SL['tail'].map(GO_dict).fillna(Y_G_SL['tail'])
Y_G_SL[['tail_detail_name', 'tail']] = Y_G_SL[['tail', 'tail_detail_name']]
Y_G_SL['head_id_is'] = 'SGD_SysematicName'
Y_G_SL['tail_id_is'] = ''

Y_G_SL['species'] = 'S.cerevisae'
Y_G_SL
Y_G_SL = Y_G_SL[~Y_G_SL['head_detail_name'].isna()]
Y_G_SL = Y_G_SL[~Y_G_SL['tail_detail_name'].isna()]

Y_G_SL['head_id_is'] = 'NCBI_ID'
# Y_G_SL['tail_id_is'] = 
Y_G_SL['tail_id_is'] = np.where(
    Y_G_SL['tail'].isna(),
    None,                          # ← None instead of np.nan
    np.where(
        Y_G_SL['tail'].str.startswith('GO'),
        'Quick_GO',
        ''
    )

)
Y_G_SL

,head,relation,tail,weight,head_type,tail_type,normalized_weight,Head_SEQ,relation_type,kg_source,head_detail_name,tail_detail_name,head_id_is,tail_id_is,species
57936271,YJL062W,Gene_CellularComponent,transmembrane,10.0,Gene,CellularComponent,1.649216,ATGAACTTGAAGCAGTTCACGTGCCTATCATGCGCTCAATTACTCG...,NaN,GenePatri,mannose-ethanolamine phosphotransferase LAS21,transmembrane,NCBI_ID,,S.cerevisae
57936272,YJL062W,Gene_CellularComponent,GO:0005783,10.0,Gene,CellularComponent,1.649216,ATGAACTTGAAGCAGTTCACGTGCCTATCATGCGCTCAATTACTCG...,NaN,GenePatri,mannose-ethanolamine phosphotransferase LAS21,endoplasmic reticulum,NCBI_ID,Quick_GO,S.cerevisae
57936273,YPL032C,Gene_CellularComponent,GO:0005737,10.0,Gene,CellularComponent,1.649216,TTATTTCTTTGATTTATTTTTTTTTTTGAATAGGCCAAATCTCTTC...,NaN,GenePatri,Svl3p,cytoplasm,NCBI_ID,Quick_GO,S.cerevisae
57936274,YDR100W,Gene_CellularComponent,transmembrane,10.0,Gene,CellularComponent,1.649216,ATGTCAGTTATTCCTCCAAAATTCTTCAAGATTGCAAATATATCAA...,NaN,GenePatri,Tvp15p,transmembrane,NCBI_ID,,S.cerevisae
57936275,YDR100W,Gene_CellularComponent,golgi,10.0,Gene,CellularComponent,1.649216,ATGTCAGTTATTCCTCCAAAATTCTTCAAGATTGCAAATATATCAA...,NaN,GenePatri,Tvp15p,golgi,NCBI_ID,,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57940493,YEL044W,Gene_CellularComponent,GO:0005634,10.0,Gene,CellularComponent,1.649216,ATGAGCGGTAGTAGGGGCAATAGCAGCAATAGTAGCGTCAGTAATA...,NaN,GenePatri,Ies6p,nucleus,NCBI_ID,Quick_GO,S.cerevisae
57940494,YGR222W,Gene_CellularComponent,GO:0016020,10.0,Gene,CellularComponent,1.649216,ATGAAGGCTTCTAGTAAAGCTATTAAATTAGTACTGGACCATCTGA...,NaN,GenePatri,Pet54p,membrane,NCBI_ID,Quick_GO,S.cerevisae
57940495,YGR222W,Gene_CellularComponent,GO:0005739,10.0,Gene,CellularComponent,1.649216,ATGAAGGCTTCTAGTAAAGCTATTAAATTAGTACTGGACCATCTGA...,NaN,GenePatri,Pet54p,mitochondrion,NCBI_ID,Quick_GO,S.cerevisae
57940496,YNL059C,Gene_CellularComponent,GO:0005634,10.0,Gene,CellularComponent,1.649216,TTAGTCTTCAAAATACTTCGTATTCCCTAACTTATGCTCTTTGATG...,NaN,GenePatri,actin-related protein ARP5,nucleus,NCBI_ID,Quick_GO,S.cerevisae
57940497,YLR414C,Gene_CellularComponent,transmembrane,10.0,Gene,CellularComponent,1.649216,TCAAATCAATGGTTTTTCCTCAATTGGAGCGTTCGCATAGATGACG...,NaN,GenePatri,Pun1p,transmembrane,NCBI_ID,,S.cerevisae

In [13]:
final_df = Y_G_SL

In [14]:
set(final_df['species']), set(final_df['relation']),set(final_df['head_type']),set(final_df['tail_type']),set(final_df['kg_source']),set(final_df['head_id_is']),set(final_df['tail_id_is'])

({'S.cerevisae'},
 {'Gene_CellularComponent'},
 {'Gene'},
 {'CellularComponent'},
 {'GenePatri'},
 {'NCBI_ID'},
 {'', 'Quick_GO'})

In [15]:
# set(final_df['relation_type'])

In [16]:
# Count true NaN values
true_nan_count = final_df.isna().sum()

# Count string 'NAN' values (case-insensitive)
string_nan_count = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

# Combine both counts
nan_summary = pd.DataFrame({
    'NaN_count': true_nan_count,
    "'NAN'_string_count": string_nan_count,
    'Total_NaN_like': true_nan_count + string_nan_count
})
nan_summary

                   NaN_count  'NAN'_string_count  Total_NaN_like
head                       0                   0               0
relation                   0                   0               0
tail                       0                   0               0
weight                     0                   0               0
head_type                  0                   0               0
tail_type                  0                   0               0
normalized_weight          0                   0               0
Head_SEQ                   0                   0               0
relation_type           4183                4183            8366
kg_source                  0                   0               0
head_detail_name           0                   0               0
tail_detail_name           0                   0               0
head_id_is                 0                   0               0
tail_id_is                 0                   0               0
species                    0                   0               0

In [17]:
# First, concatenate all dataframes as before (assuming `final_df` already exists from earlier step)

# Group by the 3 key columns
group_cols = ['head', 'relation', 'tail']

# For kg_source, combine with '::'
def merge_sources(x):
    return '::'.join(sorted(set(x.dropna())))

# Merge duplicates
final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type': 'first',
    'relation_type': 'first',
    'tail_type': 'first',
    'kg_source': merge_sources,
    'head_id_is': 'first',
    'tail_id_is': 'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})
final_df_dedup

,head,relation,tail,head_type,relation_type,tail_type,kg_source,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Q0045,Gene_CellularComponent,GO:0005739,Gene,NaN,CellularComponent,GenePatri,NCBI_ID,Quick_GO,cytochrome c oxidase subunit 1,mitochondrion,S.cerevisae
1,Q0045,Gene_CellularComponent,transmembrane,Gene,NaN,CellularComponent,GenePatri,NCBI_ID,,cytochrome c oxidase subunit 1,transmembrane,S.cerevisae
2,Q0060,Gene_CellularComponent,GO:0005739,Gene,NaN,CellularComponent,GenePatri,NCBI_ID,Quick_GO,intron-encoded DNA endonuclease aI3,mitochondrion,S.cerevisae
3,Q0080,Gene_CellularComponent,GO:0005739,Gene,NaN,CellularComponent,GenePatri,NCBI_ID,Quick_GO,F1F0 ATP synthase subunit 8,mitochondrion,S.cerevisae
4,Q0080,Gene_CellularComponent,transmembrane,Gene,NaN,CellularComponent,GenePatri,NCBI_ID,,F1F0 ATP synthase subunit 8,transmembrane,S.cerevisae
...,...,...,...,...,...,...,...,...,...,...,...,...
4178,YPR191W,Gene_CellularComponent,GO:0005739,Gene,NaN,CellularComponent,GenePatri,NCBI_ID,Quick_GO,ubiquinol--cytochrome-c reductase subunit 2,mitochondrion,S.cerevisae
4179,YPR191W,Gene_CellularComponent,GO:0016020,Gene,NaN,CellularComponent,GenePatri,NCBI_ID,Quick_GO,ubiquinol--cytochrome-c reductase subunit 2,membrane,S.cerevisae
4180,YPR198W,Gene_CellularComponent,transmembrane,Gene,NaN,CellularComponent,GenePatri,NCBI_ID,,Sge1p,transmembrane,S.cerevisae
4181,YPR199C,Gene_CellularComponent,GO:0005634,Gene,NaN,CellularComponent,GenePatri,NCBI_ID,Quick_GO,Arr1p,nucleus,S.cerevisae
4182,YPR201W,Gene_CellularComponent,transmembrane,Gene,NaN,CellularComponent,GenePatri,NCBI_ID,,Arr3p,transmembrane,S.cerevisae

In [19]:

OUT_PATH = "/storage/Arushi/090526_EvoAge/kg_formation/processed_data/eSLDB/"

final_df_dedup.to_csv(f'{OUT_PATH}esld_YEAST_GENE_cellularComponent.csv',index = None)