In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_gene_cellularcomponent
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_cellularcomponent/Mouse_gene_cellularcomponent.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

In [5]:
# Mouse = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Mus_musculus.gene_info',
#     sep='\t',
    
# )
# # Mouse["LocusTag"] = Mouse["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Mouse_symbol2Locus_dict = dict(zip(Mouse['Symbol'], Mouse['LocusTag']))
# # Mouse
# # Mouse_symbol2Locus_dict
# Mouse

# Monarch

In [6]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Mouse/Gene_Mouse_CellularComponent.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head_detail_name'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'
monarch['species'] = 'M.musculus'
monarch['head_id_is'] = 'NCBI_ID'
monarch['tail_id_is'] = 'Quick_GO'
print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 173,545 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,Ptk2b,Gene_CellularComponent,GO:0017146,Gene,part_of,CellularComponent,infores:alzheimers-university-of-toronto,PTK2 protein tyrosine kinase 2 beta,NMDA selective glutamate receptor complex,Mus musculus,NaN,NCBI_ID,Quick_GO,Ptk2b,M.musculus,Generalised,Monarch_KG
1,Ptk2b,Gene_CellularComponent,GO:0098793,Gene,is_active_in,CellularComponent,infores:syngo,PTK2 protein tyrosine kinase 2 beta,presynapse,Mus musculus,NaN,NCBI_ID,Quick_GO,Ptk2b,M.musculus,Generalised,Monarch_KG
2,Ptk2b,Gene_CellularComponent,GO:0098978,Gene,is_active_in,CellularComponent,infores:syngo,PTK2 protein tyrosine kinase 2 beta,glutamatergic synapse,Mus musculus,NaN,NCBI_ID,Quick_GO,Ptk2b,M.musculus,Generalised,Monarch_KG
3,Ptk2b,Gene_CellularComponent,GO:0098978,Gene,is_active_in,CellularComponent,infores:syngo,PTK2 protein tyrosine kinase 2 beta,glutamatergic synapse,Mus musculus,NaN,NCBI_ID,Quick_GO,Ptk2b,M.musculus,Generalised,Monarch_KG
4,Ptk2b,Gene_CellularComponent,GO:0099092,Gene,is_active_in,CellularComponent,infores:syngo,PTK2 protein tyrosine kinase 2 beta,"postsynaptic density, intracellular component",Mus musculus,NaN,NCBI_ID,Quick_GO,Ptk2b,M.musculus,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174583,4930554N03Rik,Gene_CellularComponent,GO:0005575,Gene,is_active_in,CellularComponent,infores:mgi,RIKEN cDNA 4930554N03 gene,cellular_component,Mus musculus,NaN,NCBI_ID,Quick_GO,4930554N03Rik,M.musculus,Generalised,Monarch_KG
174584,4930547M16Rik,Gene_CellularComponent,GO:0005575,Gene,is_active_in,CellularComponent,infores:mgi,RIKEN cDNA 4930547M16 gene,cellular_component,Mus musculus,NaN,NCBI_ID,Quick_GO,4930547M16Rik,M.musculus,Generalised,Monarch_KG
174585,4930548F15Rik,Gene_CellularComponent,GO:0005575,Gene,is_active_in,CellularComponent,infores:mgi,RIKEN cDNA 4930548F15 gene,cellular_component,Mus musculus,NaN,NCBI_ID,Quick_GO,4930548F15Rik,M.musculus,Generalised,Monarch_KG
174586,4930556N09Rik,Gene_CellularComponent,GO:0005575,Gene,is_active_in,CellularComponent,infores:mgi,RIKEN cDNA 4930556N09 gene,cellular_component,Mus musculus,NaN,NCBI_ID,Quick_GO,4930556N09Rik,M.musculus,Generalised,Monarch_KG
174587,Asxl2,Gene_CellularComponent,GO:0005634,Gene,located_in,CellularComponent,infores:mgi,ASXL transcriptional regulator 2,nucleus,Mus musculus,NaN,NCBI_ID,Quick_GO,Asxl2,M.musculus,Generalised,Monarch_KG

In [7]:
# monarch[monarch['head_detail_name'].isna()]

# Consolidate into Unified Schem

In [8]:
# List all source DataFrames to include
source_dfs = [
    monarch,
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 173,545

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Ptk2b,Gene_CellularComponent,GO:0017146,Gene,part_of,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,PTK2 protein tyrosine kinase 2 beta,NMDA selective glutamate receptor complex,M.musculus
1,Ptk2b,Gene_CellularComponent,GO:0098793,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,PTK2 protein tyrosine kinase 2 beta,presynapse,M.musculus
2,Ptk2b,Gene_CellularComponent,GO:0098978,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,PTK2 protein tyrosine kinase 2 beta,glutamatergic synapse,M.musculus
3,Ptk2b,Gene_CellularComponent,GO:0098978,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,PTK2 protein tyrosine kinase 2 beta,glutamatergic synapse,M.musculus
4,Ptk2b,Gene_CellularComponent,GO:0099092,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,PTK2 protein tyrosine kinase 2 beta,"postsynaptic density, intracellular component",M.musculus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173540,4930554N03Rik,Gene_CellularComponent,GO:0005575,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,RIKEN cDNA 4930554N03 gene,cellular_component,M.musculus
173541,4930547M16Rik,Gene_CellularComponent,GO:0005575,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,RIKEN cDNA 4930547M16 gene,cellular_component,M.musculus
173542,4930548F15Rik,Gene_CellularComponent,GO:0005575,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,RIKEN cDNA 4930548F15 gene,cellular_component,M.musculus
173543,4930556N09Rik,Gene_CellularComponent,GO:0005575,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,RIKEN cDNA 4930556N09 gene,cellular_component,M.musculus
173544,Asxl2,Gene_CellularComponent,GO:0005634,Gene,located_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,ASXL transcriptional regulator 2,nucleus,M.musculus

# Sanity Check — Distinct Values

In [9]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_CellularComponent'}
head_type           : {'Gene'}
tail_type           : {'CellularComponent'}
relation_type       : {'colocalizes_with', 'part_of', 'located_in', 'is_active_in'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [10]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 173,545 remaining

# NaN Audit (pre-dedup)

In [11]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [12]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 173,545  |  After dedup: 94,395

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,0610005C13Rik,Gene_CellularComponent,GO:0005575,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,RIKEN cDNA 0610005C13 gene,cellular_component,M.musculus
1,0610006L08Rik,Gene_CellularComponent,GO:0005575,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,RIKEN cDNA 0610006L08 gene,cellular_component,M.musculus
2,0610008J02Rik,Gene_CellularComponent,GO:0005575,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,RIKEN cDNA 0610008J02 gene,cellular_component,M.musculus

In [13]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    94395
Name: count, dtype: int64

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    94395
Name: count, dtype: int64

In [16]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 94,395 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_cellularcomponent/Mouse_gene_cellularcomponent.csv

In [17]:
OUT_PATH

'/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_cellularcomponent/Mouse_gene_cellularcomponent.csv'