In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_gene_inhibits_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_inhibits_biologicalprocess/Mouse_gene_inhibits_biologicalprocess.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Mouse_gene_inhibits_biologicalprocess’: File exists

In [4]:
#

In [5]:
# Mouse = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Mus_musculus.gene_info',
#     sep='\t',
    
# )
# # Mouse["LocusTag"] = Mouse["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Mouse_symbol2Locus_dict = dict(zip(Mouse['Symbol'], Mouse['LocusTag']))
# # Mouse
# # Mouse_symbol2Locus_dict
# Mouse

# Genage

In [6]:
Genage = pd.read_csv(PROC_DIR + 'genage/Mouse/Mouse_Gene_Inhibits_BiologicalProcess.csv')
Genage.columns = Genage.columns.str.lower()
Genage = Genage[~Genage['head_detail_name'].isna()]

Genage['kg_type'] = 'Aging'

print(f"Genage: {len(Genage):,} rows")
Genage['head_id_is'] = 'NCBI_ID'
Genage['tail_id_is'] = 'Quick_GO'
Genage['species'] = 'Mus musculus'
Genage['kg_source'] = 'Genage'

Genage

Genage: 83 rows

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,relation_source,species,data_type,kg_type,head_id_is,tail_id_is,kg_source
0,Arhgap1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Rho GTPase activating protein 1,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
1,Atm,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ataxia telangiectasia mutated,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
2,Atr,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ataxia telangiectasia and Rad3 related,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
3,Brca1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"breast cancer 1, early onset",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
4,Bub1b,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"BUB1B, mitotic checkpoint serine/threonine kinase",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,Rbm38,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,RNA binding motif protein 38,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
79,Col1a1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"collagen, type I, alpha 1",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
80,Siglece,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,sialic acid binding Ig-like lectin E,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
81,Sod3,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"superoxide dismutase 3, extracellular",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
82,Mir17,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,microRNA 17,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage

# AgingBank

In [7]:
AgingBank = pd.read_csv(PROC_DIR + 'agingbank/Mouse_AgingbankGene_inhibits_BioPro.csv')
AgingBank.columns = AgingBank.columns.str.lower()
AgingBank = AgingBank[~AgingBank['head_detail_name'].isna()]

AgingBank['kg_type'] = 'Aging'
AgingBank['tail_type'] = 'BiologicalProcess'
print(f"AgingBank: {len(AgingBank):,} rows")
AgingBank['head_id_is'] = 'NCBI_ID'
AgingBank['relation'] = 'Gene_Inhibits_BiologicalProcess'
AgingBank['tail_id_is'] = 'Quick_GO'
AgingBank['species'] = 'Mus musculus'
AgingBank['kg_source'] = 'AgingBank'
AgingBank

AgingBank: 17 rows

,head,relation,tail,head_type,tail_type,kg_source,kg_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_type.1,species
0,Aldh2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"aldehyde dehydrogenase 2, mitochondrial",aging,NCBI_ID,Quick_GO,Aging,Mus musculus
1,Bcl2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,B cell leukemia/lymphoma 2,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
2,Bmi1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,Bmi1 polycomb ring finger oncogene,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
3,Hmox1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,heme oxygenase 1,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
4,Ankrd22,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,ankyrin repeat domain 22,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
5,C4b,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,complement C4B (Chido blood group),aging,NCBI_ID,Quick_GO,Aging,Mus musculus
6,Lag3,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,lymphocyte-activation gene 3,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
7,Nqo1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"NAD(P)H dehydrogenase, quinone 1",aging,NCBI_ID,Quick_GO,Aging,Mus musculus
8,Pcdhb9,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,protocadherin beta 9,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
9,Prdx4,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,peroxiredoxin 4,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
10,H19,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"H19, imprinted maternally expressed transcript",aging,NCBI_ID,Quick_GO,Aging,Mus musculus
11,Norad,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,non-coding RNA activated by DNA damage,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
12,COX1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,cytochrome c oxidase subunit I,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
13,Kl,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,klotho,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
14,Isl1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"ISL1 transcription factor, LIM/homeodomain",aging,NCBI_ID,Quick_GO,Aging,Mus musculus
15,Mfn2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,mitofusin 2,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
16,Mtbp,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"Mdm2, transformed 3T3 cell double minute p53 b...",aging,NCBI_ID,Quick_GO,Aging,Mus musculus

In [8]:
AgingBank_2 = pd.read_csv(PROC_DIR + 'agingbank/Mouse_AgingbankGene_inhibits_BioPro_2.csv')
AgingBank_2.columns = AgingBank_2.columns.str.lower()
AgingBank_2 = AgingBank_2[~AgingBank_2['head_detail_name'].isna()]

AgingBank_2['kg_type'] = 'Aging'
AgingBank_2['relation'] = 'Gene_Inhibits_BiologicalProcess'

AgingBank_2['tail_type'] = 'BiologicalProcess'
print(f"AgingBank_2: {len(AgingBank_2):,} rows")
AgingBank_2['head_id_is'] = 'NCBI_ID'
AgingBank_2['tail_id_is'] = 'Quick_GO'
AgingBank_2['species'] = 'Mus musculus'
AgingBank_2['kg_source'] = 'AgingBank'
AgingBank_2

AgingBank_2: 1 rows

,head,relation,tail,head_type,tail_type,kg_source,kg_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_type.1,species
0,COX1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,cytochrome c oxidase subunit I,aging,NCBI_ID,Quick_GO,Aging,Mus musculus

# Consolidate into Unified Schem

In [9]:
# List all source DataFrames to include
source_dfs = [
    Genage, AgingBank, AgingBank_2
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 101

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Arhgap1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Rho GTPase activating protein 1,obsolete aging,Mus musculus
1,Atm,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,ataxia telangiectasia mutated,obsolete aging,Mus musculus
2,Atr,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,ataxia telangiectasia and Rad3 related,obsolete aging,Mus musculus
3,Brca1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,"breast cancer 1, early onset",obsolete aging,Mus musculus
4,Bub1b,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,"BUB1B, mitotic checkpoint serine/threonine kinase",obsolete aging,Mus musculus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Kl,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,klotho,aging,Mus musculus
97,Isl1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,"ISL1 transcription factor, LIM/homeodomain",aging,Mus musculus
98,Mfn2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,mitofusin 2,aging,Mus musculus
99,Mtbp,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,"Mdm2, transformed 3T3 cell double minute p53 b...",aging,Mus musculus
100,COX1,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,cytochrome c oxidase subunit I,aging,Mus musculus

# Sanity Check — Distinct Values

In [10]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_Inhibits_BiologicalProcess'}
head_type           : {'Gene'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'Genage', 'AgingBank'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [11]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 101 remaining

# NaN Audit (pre-dedup)

In [12]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           101                   0             101
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [13]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 101  |  After dedup: 99

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Adra1a,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,"adrenergic receptor, alpha 1a",obsolete aging,Mus musculus
1,Aldh2,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,"aldehyde dehydrogenase 2, mitochondrial",aging,Mus musculus
2,Ankrd22,Gene_Inhibits_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,ankyrin repeat domain 22,aging,Mus musculus

In [14]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            99                   0              99
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'AgingBank::Genage', 'Genage', 'AgingBank'} kg_source
Genage               82
AgingBank            16
AgingBank::Genage     1
Name: count, dtype: int64

In [16]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    99
Name: count, dtype: int64

In [17]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 99 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_inhibits_biologicalprocess/Mouse_gene_inhibits_biologicalprocess.csv

In [18]:
# OUT_PATH