In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_gene_promotes_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_promotes_biologicalprocess/Mouse_gene_promotes_biologicalprocess.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Mouse_gene_promotes_biologicalprocess’: File exists

In [4]:
#

In [5]:
# Mouse = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Mus_musculus.gene_info',
#     sep='\t',
    
# )
# # Mouse["LocusTag"] = Mouse["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Mouse_symbol2Locus_dict = dict(zip(Mouse['Symbol'], Mouse['LocusTag']))
# # Mouse
# # Mouse_symbol2Locus_dict
# Mouse

# Genage

In [6]:
Genage = pd.read_csv(PROC_DIR + 'genage/Mouse/Mouse_Gene_Promotes_BiologicalProcess.csv')
Genage.columns = Genage.columns.str.lower()
Genage = Genage[~Genage['head_detail_name'].isna()]

Genage['kg_type'] = 'Aging'

print(f"Genage: {len(Genage):,} rows")
Genage['head_id_is'] = 'NCBI_ID'
Genage['tail_id_is'] = 'Quick_GO'
Genage['species'] = 'Mus musculus'
Genage['kg_source'] = 'Genage'

Genage

Genage: 45 rows

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,relation_source,species,data_type,kg_type,head_id_is,tail_id_is,kg_source
0,Adcy5,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,adenylate cyclase 5,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
1,Cdkn1a,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,cyclin dependent kinase inhibitor 1A,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
2,Coq7,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,demethyl-Q 7,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
3,Gh,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,growth hormone,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
4,Ghr,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,growth hormone receptor,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
5,Ghrhr,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,growth hormone releasing hormone receptor,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
6,Gpx4,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,glutathione peroxidase 4,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
7,Igf1r,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,insulin-like growth factor I receptor,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
8,Insr,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,insulin receptor,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
9,Irs1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,insulin receptor substrate 1,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
10,Irs2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,insulin receptor substrate 2,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
11,Pappa,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,pregnancy-associated plasma protein A,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
12,Pou1f1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"POU domain, class 1, transcription factor 1",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
13,Prop1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,paired like homeodomain factor 1,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
14,Shc1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,src homology 2 domain-containing transforming ...,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
15,Surf1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,surfeit gene 1,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
16,Terf2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,telomeric repeat binding factor 2,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
17,Agtr1a,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"angiotensin II receptor, type 1a",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
18,Eef1e1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,eukaryotic translation elongation factor 1 eps...,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
19,Eps8,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,epidermal growth factor receptor pathway subst...,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
20,Htt,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,huntingtin,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
21,Kcna3,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"potassium voltage-gated channel, shaker-relate...",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
22,Slc13a1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,solute carrier family 13 (sodium/sulfate sympo...,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
23,Trp53bp1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,transformation related protein 53 binding prot...,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
24,Rps6kb1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"ribosomal protein S6 kinase, polypeptide 1",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
25,Prkar2b,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"protein kinase, cAMP dependent regulatory, typ...",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
26,Eif5a2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,eukaryotic translation initiation factor 5A2,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
27,Mif,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,macrophage migration inhibitory factor (glycos...,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
28,Dgat1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,diacylglycerol O-acyltransferase 1,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
29,Gsta4,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"glutathione S-transferase, alpha 4",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
30,Mtor,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,mechanistic target of rapamycin kinase,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
31,Akt1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,thymoma viral proto-oncogene 1,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
32,Ikbkb,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,inhibitor of kappaB kinase beta,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
33,Ghrh,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,growth hormone releasing hormone,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
34,Serpine1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"serine (or cysteine) peptidase inhibitor, clad...",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
35,Myc,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,myelocytomatosis oncogene,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
36,Ctf1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,cardiotrophin 1,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
37,Trpv1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"transient receptor potential cation channel, s...",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
38,Adra1b,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"adrenergic receptor, alpha 1b",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
39,Ubd,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ubiquitin D,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
40,Mstn,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,myostatin,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
41,Mtbp,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"Mdm2, transformed 3T3 cell double minute p53 b...",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
42,Gmfb,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"glia maturation factor, beta",obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
43,Per2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,period circadian clock 2,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage
44,Akt2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,thymoma viral proto-oncogene 2,obsolete aging,GeneAge,Mus musculus,Causative,Aging,NCBI_ID,Quick_GO,Genage

# AgingBank

In [7]:
AgingBank = pd.read_csv(PROC_DIR + 'agingbank/Mouse_AgingbankGene_promotes_BioPro.csv')
AgingBank.columns = AgingBank.columns.str.lower()
AgingBank = AgingBank[~AgingBank['head_detail_name'].isna()]

AgingBank['kg_type'] = 'Aging'
AgingBank['relation'] = 'Gene_Promotes_BiologicalProcess'
AgingBank['tail_type'] = 'BiologicalProcess'
print(f"AgingBank: {len(AgingBank):,} rows")
AgingBank['head_id_is'] = 'NCBI_ID'
AgingBank['tail_id_is'] = 'Quick_GO'
AgingBank['species'] = 'Mus musculus'
AgingBank['kg_source'] = 'AgingBank'
AgingBank

AgingBank: 20 rows

,head,relation,tail,head_type,tail_type,kg_source,kg_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_type.1,species
0,Alpl,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"alkaline phosphatase, liver/bone/kidney",aging,NCBI_ID,Quick_GO,Aging,Mus musculus
1,Dctn1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,dynactin 1,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
2,Nrip1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,nuclear receptor interacting protein 1,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
3,Rras2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,related RAS viral (r-ras) oncogene 2,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
4,Thy1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"thymus cell antigen 1, theta",aging,NCBI_ID,Quick_GO,Aging,Mus musculus
5,Drd2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,dopamine receptor D2,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
6,H19,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"H19, imprinted maternally expressed transcript",aging,NCBI_ID,Quick_GO,Aging,Mus musculus
7,Homer1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,homer scaffolding protein 1,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
8,Gm14230,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,predicted gene 14230,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
9,C1ql3,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,C1q-like 3,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
10,Gpr37,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,G protein-coupled receptor 37,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
11,Igf2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,insulin-like growth factor 2,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
12,Mest,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,mesoderm specific transcript,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
13,Ptk7,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,PTK7 protein tyrosine kinase 7,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
14,Srd5a2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,steroid 5 alpha-reductase 2,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
15,Cln5,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"ceroid-lipofuscinosis, neuronal 5",aging,NCBI_ID,Quick_GO,Aging,Mus musculus
16,Dkc1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"dyskeratosis congenita 1, dyskerin",aging,NCBI_ID,Quick_GO,Aging,Mus musculus
17,Ptpn11,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"protein tyrosine phosphatase, non-receptor typ...",aging,NCBI_ID,Quick_GO,Aging,Mus musculus
18,Tmem135,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,transmembrane protein 135,aging,NCBI_ID,Quick_GO,Aging,Mus musculus
19,Bach1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"BTB and CNC homology 1, basic leucine zipper t...",aging,NCBI_ID,Quick_GO,Aging,Mus musculus

In [8]:
AgingBank_2 = pd.read_csv(PROC_DIR + 'agingbank/Mouse_AgingbankGene_promotes_BioPro_2.csv')
AgingBank_2.columns = AgingBank_2.columns.str.lower()
AgingBank_2 = AgingBank_2[~AgingBank_2['head_detail_name'].isna()]

AgingBank_2['kg_type'] = 'Aging'
AgingBank_2['relation'] = 'Gene_Promotes_BiologicalProcess'

AgingBank_2['tail_type'] = 'BiologicalProcess'
print(f"AgingBank_2: {len(AgingBank_2):,} rows")
AgingBank_2['head_id_is'] = 'NCBI_ID'
AgingBank_2['tail_id_is'] = 'Quick_GO'
AgingBank_2['species'] = 'Mus musculus'
AgingBank_2['kg_source'] = 'AgingBank'
AgingBank_2

AgingBank_2: 0 rows

Empty DataFrame
Columns: [head, relation, tail, head_type, tail_type, kg_source, kg_type, head_detail_name, tail_detail_name, head_id_is, tail_id_is, kg_type.1, species]
Index: []

# Consolidate into Unified Schem

In [9]:
# List all source DataFrames to include
source_dfs = [
    Genage, AgingBank, AgingBank_2
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 65

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Adcy5,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,adenylate cyclase 5,obsolete aging,Mus musculus
1,Cdkn1a,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,cyclin dependent kinase inhibitor 1A,obsolete aging,Mus musculus
2,Coq7,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,demethyl-Q 7,obsolete aging,Mus musculus
3,Gh,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,growth hormone,obsolete aging,Mus musculus
4,Ghr,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,growth hormone receptor,obsolete aging,Mus musculus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Cln5,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,"ceroid-lipofuscinosis, neuronal 5",aging,Mus musculus
61,Dkc1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,"dyskeratosis congenita 1, dyskerin",aging,Mus musculus
62,Ptpn11,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,"protein tyrosine phosphatase, non-receptor typ...",aging,Mus musculus
63,Tmem135,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,transmembrane protein 135,aging,Mus musculus
64,Bach1,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,"BTB and CNC homology 1, basic leucine zipper t...",aging,Mus musculus

# Sanity Check — Distinct Values

In [10]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_Promotes_BiologicalProcess'}
head_type           : {'Gene'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'AgingBank', 'Genage'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [11]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 65 remaining

# NaN Audit (pre-dedup)

In [12]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            65                   0              65
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [13]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 65  |  After dedup: 65

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Adcy5,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,adenylate cyclase 5,obsolete aging,Mus musculus
1,Adra1b,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,"adrenergic receptor, alpha 1b",obsolete aging,Mus musculus
2,Agtr1a,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,"angiotensin II receptor, type 1a",obsolete aging,Mus musculus

In [14]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            65                   0              65
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'AgingBank', 'Genage'} kg_source
Genage       45
AgingBank    20
Name: count, dtype: int64

In [16]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    65
Name: count, dtype: int64

In [17]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 65 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_promotes_biologicalprocess/Mouse_gene_promotes_biologicalprocess.csv

In [18]:
# OUT_PATH