In [33]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [34]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse

In [35]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_phenotype_chemical
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_phenotype_chemical/Mouse_phenotype_chemical.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Mouse_phenotype_chemical’: File exists

In [36]:
#

In [37]:
! ls /storage/Arushi/090526_EvoAge/kg_formation/processed_data/ageanno_processed_mo/ageanno_processed_mo/

ls: cannot access '/storage/Arushi/090526_EvoAge/kg_formation/processed_data/ageanno_processed_mo/ageanno_processed_mo/': No such file or directory

# monarch

In [38]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Mouse/Mouse_Phenotype_ChemicalEntity.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch.rename(columns={
    'headtype': 'head_type',
    'tailtype': 'tail_type',
})
# monarch = monarch[~monarch['head_detail_name'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'
monarch['species'] = 'M.musculus'
monarch['head_id_is'] = 'MP_ID'

print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 451 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,tail_iupac_name,species,kg_type,kg_source
0,MP:0000180,Phenotype_ChemicalEntity,5997,Phenotype,related_to,ChemicalEntity,infores:upheno,abnormal circulating cholesterol level,cholesterol,Mus musculus,NaN,MP_ID,PubChem,"(3S,8S,9S,10R,13R,14S,17R)-10,13-dimethyl-17-[...",M.musculus,Generalised,Monarch_KG
1,MP:0000194,Phenotype_ChemicalEntity,5460341,Phenotype,related_to,ChemicalEntity,infores:upheno,increased circulating calcium level,calcium atom,Mus musculus,NaN,MP_ID,PubChem,calcium,M.musculus,Generalised,Monarch_KG
2,MP:0000195,Phenotype_ChemicalEntity,5460341,Phenotype,related_to,ChemicalEntity,infores:upheno,decreased circulating calcium level,calcium atom,Mus musculus,NaN,MP_ID,PubChem,calcium,M.musculus,Generalised,Monarch_KG
3,MP:0000362,Phenotype_ChemicalEntity,774,Phenotype,related_to,ChemicalEntity,infores:upheno,decreased mast cell histamine storage,histamine,Mus musculus,NaN,MP_ID,PubChem,2-(1H-imidazol-5-yl)ethanamine,M.musculus,Generalised,Monarch_KG
4,MP:0000676,Phenotype_ChemicalEntity,962,Phenotype,related_to,ChemicalEntity,infores:upheno,abnormal body water content,water,Mus musculus,NaN,MP_ID,PubChem,oxidane,M.musculus,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,MP:0031655,Phenotype_ChemicalEntity,5462224,Phenotype,related_to,ChemicalEntity,infores:upheno,abnormal brain magnesium level,magnesium atom,Mus musculus,NaN,MP_ID,PubChem,magnesium,M.musculus,Generalised,Monarch_KG
447,MP:0031656,Phenotype_ChemicalEntity,5462224,Phenotype,related_to,ChemicalEntity,infores:upheno,decreased brain magnesium level,magnesium atom,Mus musculus,NaN,MP_ID,PubChem,magnesium,M.musculus,Generalised,Monarch_KG
448,MP:0031657,Phenotype_ChemicalEntity,5462224,Phenotype,related_to,ChemicalEntity,infores:upheno,increased brain magnesium level,magnesium atom,Mus musculus,NaN,MP_ID,PubChem,magnesium,M.musculus,Generalised,Monarch_KG
449,MP:0031658,Phenotype_ChemicalEntity,5462224,Phenotype,related_to,ChemicalEntity,infores:upheno,decreased magnesium level,magnesium atom,Mus musculus,NaN,MP_ID,PubChem,magnesium,M.musculus,Generalised,Monarch_KG
450,MP:0031659,Phenotype_ChemicalEntity,5462224,Phenotype,related_to,ChemicalEntity,infores:upheno,increased magnesium level,magnesium atom,Mus musculus,NaN,MP_ID,PubChem,magnesium,M.musculus,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [39]:
# List all source DataFrames to include
source_dfs = [
    monarch,
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 451

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,MP:0000180,Phenotype_ChemicalEntity,5997,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,MP_ID,PubChem,abnormal circulating cholesterol level,cholesterol,M.musculus
1,MP:0000194,Phenotype_ChemicalEntity,5460341,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,MP_ID,PubChem,increased circulating calcium level,calcium atom,M.musculus
2,MP:0000195,Phenotype_ChemicalEntity,5460341,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,MP_ID,PubChem,decreased circulating calcium level,calcium atom,M.musculus
3,MP:0000362,Phenotype_ChemicalEntity,774,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,MP_ID,PubChem,decreased mast cell histamine storage,histamine,M.musculus
4,MP:0000676,Phenotype_ChemicalEntity,962,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,MP_ID,PubChem,abnormal body water content,water,M.musculus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,MP:0031655,Phenotype_ChemicalEntity,5462224,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,MP_ID,PubChem,abnormal brain magnesium level,magnesium atom,M.musculus
447,MP:0031656,Phenotype_ChemicalEntity,5462224,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,MP_ID,PubChem,decreased brain magnesium level,magnesium atom,M.musculus
448,MP:0031657,Phenotype_ChemicalEntity,5462224,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,MP_ID,PubChem,increased brain magnesium level,magnesium atom,M.musculus
449,MP:0031658,Phenotype_ChemicalEntity,5462224,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,MP_ID,PubChem,decreased magnesium level,magnesium atom,M.musculus
450,MP:0031659,Phenotype_ChemicalEntity,5462224,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,MP_ID,PubChem,increased magnesium level,magnesium atom,M.musculus

# Sanity Check — Distinct Values

In [40]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Phenotype_ChemicalEntity'}
head_type           : {'Phenotype'}
tail_type           : {'ChemicalEntity'}
relation_type       : {'related_to'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'MP_ID'}
tail_id_is          : {'PubChem'}

In [41]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 451 remaining

# NaN Audit (pre-dedup)

In [42]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [43]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 451  |  After dedup: 451

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,MP:0000180,Phenotype_ChemicalEntity,5997,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,MP_ID,PubChem,abnormal circulating cholesterol level,cholesterol,M.musculus
1,MP:0000194,Phenotype_ChemicalEntity,5460341,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,MP_ID,PubChem,increased circulating calcium level,calcium atom,M.musculus
2,MP:0000195,Phenotype_ChemicalEntity,5460341,Phenotype,related_to,ChemicalEntity,Monarch_KG,Generalised,MP_ID,PubChem,decreased circulating calcium level,calcium atom,M.musculus

In [44]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [45]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    451
Name: count, dtype: int64

In [46]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    451
Name: count, dtype: int64

In [47]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 451 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_phenotype_chemical/Mouse_phenotype_chemical.csv

In [48]:
# OUT_PATH