In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_chemical_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_chemical_biologicalprocess/Mouse_chemical_biologicalprocess.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

# AgeAnnoMO

In [5]:
AgeAnnoMO = pd.read_csv(PROC_DIR + 'ageanno_processed_mo/AgeAnnoMO_Mouse_Chemical_BiologicalProcess_1.csv')
AgeAnnoMO.columns = AgeAnnoMO.columns.str.lower()
AgeAnnoMO = AgeAnnoMO[~AgeAnnoMO['head_detail_name'].isna()]

AgeAnnoMO['kg_type'] = 'Aging'
AgeAnnoMO['tail_type'] = 'BiologicalProcess'
print(f"AgeAnnoMO: {len(AgeAnnoMO):,} rows")
AgeAnnoMO['head_id_is'] = 'Pubchem'
AgeAnnoMO['tail_id_is'] = 'Quick_GO'
AgeAnnoMO['species'] = 'Mus musculus'
AgeAnnoMO['kg_source'] = 'AgeAnnoMO'
AgeAnnoMO

AgeAnnoMO: 10 rows

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,relation_source,their_source_pmid,species,kg_type,kg_source
0,445154,ChemicalEntity_BiologicalProcess,GO:1111113,ChemicalEntity,BiologicalProcess,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",Epigenetic Alterations,Pubchem,Quick_GO,AgeAnnoMO,19207472.0,Mus musculus,Aging,AgeAnnoMO
1,4091,ChemicalEntity_BiologicalProcess,GO:1111113,ChemicalEntity,BiologicalProcess,"3-(diaminomethylidene)-1,1-dimethylguanidine",Epigenetic Alterations,Pubchem,Quick_GO,AgeAnnoMO,28143904.0,Mus musculus,Aging,AgeAnnoMO
2,1123,ChemicalEntity_BiologicalProcess,GO:1111114,ChemicalEntity,BiologicalProcess,2-aminoethanesulfonic acid,Loss of Proteostasis,Pubchem,Quick_GO,AgeAnnoMO,25833520.0,Mus musculus,Aging,AgeAnnoMO
3,22053264,ChemicalEntity_BiologicalProcess,GO:1111114,ChemicalEntity,BiologicalProcess,4-phenylbutanoate,Loss of Proteostasis,Pubchem,Quick_GO,AgeAnnoMO,35488730.0,Mus musculus,Aging,AgeAnnoMO
4,4534,ChemicalEntity_BiologicalProcess,GO:1111114,ChemicalEntity,BiologicalProcess,"4-[4-(3,4-dihydroxyphenyl)-2,3-dimethylbutyl]b...",Loss of Proteostasis,Pubchem,Quick_GO,AgeAnnoMO,31602311.0,Mus musculus,Aging,AgeAnnoMO
5,170907453,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,BiologicalProcess,"(2S)-2-[[(1R,4S,7S,13S,16R,21R,24R,27S,30S,33R...",Deregulated Nutrient Sensing,Pubchem,Quick_GO,AgeAnnoMO,15489035.0,Mus musculus,Aging,AgeAnnoMO
6,896,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,BiologicalProcess,N-[2-(5-methoxy-1H-indol-3-yl)ethyl]acetamide,Deregulated Nutrient Sensing,Pubchem,Quick_GO,AgeAnnoMO,29907977.0,Mus musculus,Aging,AgeAnnoMO
7,445154,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,BiologicalProcess,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",Deregulated Nutrient Sensing,Pubchem,Quick_GO,AgeAnnoMO,25315298.0,Mus musculus,Aging,AgeAnnoMO
8,3062316,ChemicalEntity_BiologicalProcess,GO:0090398,ChemicalEntity,BiologicalProcess,N-(2-chloro-6-methylphenyl)-2-[[6-[4-(2-hydrox...,Cellular Senescence,Pubchem,Quick_GO,AgeAnnoMO,25754370.0,Mus musculus,Aging,AgeAnnoMO
9,5284616,ChemicalEntity_BiologicalProcess,GO:0090398,ChemicalEntity,BiologicalProcess,"(1R,9S,12S,15R,16E,18R,19R,21R,23S,24E,26E,28E...",Cellular Senescence,Pubchem,Quick_GO,AgeAnnoMO,19471117.0,Mus musculus,Aging,AgeAnnoMO

In [6]:
AgeAnnoMO_2 = pd.read_csv(PROC_DIR + 'ageanno_processed_mo/AgeAnnoMO_Mouse_Chemical_BiologicalProcess_2.csv')
AgeAnnoMO_2.columns = AgeAnnoMO_2.columns.str.lower()
AgeAnnoMO_2 = AgeAnnoMO_2[~AgeAnnoMO_2['head_detail_name'].isna()]

AgeAnnoMO_2['kg_type'] = 'Aging'
AgeAnnoMO_2['tail_type'] = 'BiologicalProcess'
print(f"AgeAnnoMO_2: {len(AgeAnnoMO_2):,} rows")
AgeAnnoMO_2['head_id_is'] = 'Pubchem'
AgeAnnoMO_2['tail_id_is'] = 'Quick_GO'
AgeAnnoMO_2['species'] = 'Mus musculus'
AgeAnnoMO_2['kg_source'] = 'AgeAnnoMO'
AgeAnnoMO_2

AgeAnnoMO_2: 9 rows

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,relation_source,species,head_id,kg_type,kg_source
0,10917,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,BiologicalProcess,(3R)-3-hydroxy-4-(trimethylazaniumyl)butanoate,Deregulated Nutrient Sensing,Pubchem,Quick_GO,AgeAnnoMO,Mus musculus,Levocarnitine,Aging,AgeAnnoMO
1,657272,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,BiologicalProcess,"[(2R)-2,3-dihydroxypropyl] 2-(trimethylazanium...",Deregulated Nutrient Sensing,Pubchem,Quick_GO,AgeAnnoMO,Mus musculus,Choline Alfoscerate,Aging,AgeAnnoMO
2,288,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,BiologicalProcess,3-hydroxy-4-(trimethylazaniumyl)butanoate,Deregulated Nutrient Sensing,Pubchem,Quick_GO,AgeAnnoMO,Mus musculus,DL-Carnitine,Aging,AgeAnnoMO
3,107738,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,BiologicalProcess,3-propanoyloxy-4-(trimethylazaniumyl)butanoate,Deregulated Nutrient Sensing,Pubchem,Quick_GO,AgeAnnoMO,Mus musculus,Propionylcarnitine,Aging,AgeAnnoMO
4,5283469,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,BiologicalProcess,"2,3-dihydroxypropyl (9Z,12Z)-octadeca-9,12-die...",Deregulated Nutrient Sensing,Pubchem,Quick_GO,AgeAnnoMO,Mus musculus,Glyceryl monolinoleate,Aging,AgeAnnoMO
5,5460358,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,BiologicalProcess,"(2R)-2,3-dihydroxypropanoate",Deregulated Nutrient Sensing,Pubchem,Quick_GO,AgeAnnoMO,Mus musculus,D-glycerate,Aging,AgeAnnoMO
6,40489139,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,BiologicalProcess,"[(2R)-2,3-dihydroxypropyl] (9Z,12Z)-octadeca-9...",Deregulated Nutrient Sensing,Pubchem,Quick_GO,AgeAnnoMO,Mus musculus,1-Monolinolein,Aging,AgeAnnoMO
7,6436630,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,BiologicalProcess,"[(2S)-2,3-dihydroxypropyl] (9Z,12Z)-octadeca-9...",Deregulated Nutrient Sensing,Pubchem,Quick_GO,AgeAnnoMO,Mus musculus,alpha-Glyceryl linoleate,Aging,AgeAnnoMO
8,7045767,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,BiologicalProcess,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Deregulated Nutrient Sensing,Pubchem,Quick_GO,AgeAnnoMO,Mus musculus,Acetyl-L-carnitine,Aging,AgeAnnoMO

# Consolidate into Unified Schem

In [7]:
# List all source DataFrames to include
source_dfs = [
    AgeAnnoMO, AgeAnnoMO_2
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 19

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,445154,ChemicalEntity_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",Epigenetic Alterations,Mus musculus
1,4091,ChemicalEntity_BiologicalProcess,GO:1111113,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,"3-(diaminomethylidene)-1,1-dimethylguanidine",Epigenetic Alterations,Mus musculus
2,1123,ChemicalEntity_BiologicalProcess,GO:1111114,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,2-aminoethanesulfonic acid,Loss of Proteostasis,Mus musculus
3,22053264,ChemicalEntity_BiologicalProcess,GO:1111114,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,4-phenylbutanoate,Loss of Proteostasis,Mus musculus
4,4534,ChemicalEntity_BiologicalProcess,GO:1111114,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,"4-[4-(3,4-dihydroxyphenyl)-2,3-dimethylbutyl]b...",Loss of Proteostasis,Mus musculus
5,170907453,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,"(2S)-2-[[(1R,4S,7S,13S,16R,21R,24R,27S,30S,33R...",Deregulated Nutrient Sensing,Mus musculus
6,896,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,N-[2-(5-methoxy-1H-indol-3-yl)ethyl]acetamide,Deregulated Nutrient Sensing,Mus musculus
7,445154,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",Deregulated Nutrient Sensing,Mus musculus
8,3062316,ChemicalEntity_BiologicalProcess,GO:0090398,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,N-(2-chloro-6-methylphenyl)-2-[[6-[4-(2-hydrox...,Cellular Senescence,Mus musculus
9,5284616,ChemicalEntity_BiologicalProcess,GO:0090398,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,"(1R,9S,12S,15R,16E,18R,19R,21R,23S,24E,26E,28E...",Cellular Senescence,Mus musculus
10,10917,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,(3R)-3-hydroxy-4-(trimethylazaniumyl)butanoate,Deregulated Nutrient Sensing,Mus musculus
11,657272,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,"[(2R)-2,3-dihydroxypropyl] 2-(trimethylazanium...",Deregulated Nutrient Sensing,Mus musculus
12,288,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,3-hydroxy-4-(trimethylazaniumyl)butanoate,Deregulated Nutrient Sensing,Mus musculus
13,107738,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,3-propanoyloxy-4-(trimethylazaniumyl)butanoate,Deregulated Nutrient Sensing,Mus musculus
14,5283469,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,"2,3-dihydroxypropyl (9Z,12Z)-octadeca-9,12-die...",Deregulated Nutrient Sensing,Mus musculus
15,5460358,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,"(2R)-2,3-dihydroxypropanoate",Deregulated Nutrient Sensing,Mus musculus
16,40489139,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,"[(2R)-2,3-dihydroxypropyl] (9Z,12Z)-octadeca-9...",Deregulated Nutrient Sensing,Mus musculus
17,6436630,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,"[(2S)-2,3-dihydroxypropyl] (9Z,12Z)-octadeca-9...",Deregulated Nutrient Sensing,Mus musculus
18,7045767,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,(3R)-3-acetyloxy-4-(trimethylazaniumyl)butanoate,Deregulated Nutrient Sensing,Mus musculus

# Sanity Check — Distinct Values

In [8]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'ChemicalEntity_BiologicalProcess'}
head_type           : {'ChemicalEntity'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'AgeAnnoMO'}
head_id_is          : {'Pubchem'}
tail_id_is          : {'Quick_GO'}

In [9]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 19 remaining

# NaN Audit (pre-dedup)

In [10]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            19                   0              19
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [11]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 19  |  After dedup: 19

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,288,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,3-hydroxy-4-(trimethylazaniumyl)butanoate,Deregulated Nutrient Sensing,Mus musculus
1,896,ChemicalEntity_BiologicalProcess,GO:1111115,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,N-[2-(5-methoxy-1H-indol-3-yl)ethyl]acetamide,Deregulated Nutrient Sensing,Mus musculus
2,1123,ChemicalEntity_BiologicalProcess,GO:1111114,ChemicalEntity,None,BiologicalProcess,AgeAnnoMO,Aging,Pubchem,Quick_GO,2-aminoethanesulfonic acid,Loss of Proteostasis,Mus musculus

In [12]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            19                   0              19
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'AgeAnnoMO'} kg_source
AgeAnnoMO    19
Name: count, dtype: int64

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    19
Name: count, dtype: int64

In [15]:
# ! mkdir Mouse_chemical_biologicalprocess

In [16]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 19 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_chemical_biologicalprocess/Mouse_chemical_biologicalprocess.csv

In [17]:
# OUT_PATH