In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_gene_tissue
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_tissue/Mouse_gene_tissue.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

In [5]:
# Mouse = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Mus_musculus.gene_info',
#     sep='\t',
    
# )
# # Mouse["LocusTag"] = Mouse["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Mouse_symbol2Locus_dict = dict(zip(Mouse['Symbol'], Mouse['LocusTag']))
# # Mouse
# # Mouse_symbol2Locus_dict
# Mouse

# DAA

In [6]:
DAA = pd.read_csv(PROC_DIR + 'digitalagingatlas/Mouse/DAA_Gene_Tissue_Mouse.csv')

DAA.columns = DAA.columns.str.lower()
DAA = DAA[~DAA['head_detail_name'].isna()]
DAA['kg_type'] = 'Aging'
DAA['kg_source'] = 'DigitalAgingAtlas'
DAA['species'] = 'Mus musculus'
DAA['head_id_is'] = 'NCBI_ID'
DAA['tail_id_is'] = 'BTO_ID'
print(f"DAA: {len(DAA):,} rows")
DAA

DAA: 576 rows

,head,relation,tail,head_type,tail_type,relation_source,species,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_type,kg_source
0,Abat,Gene_Tissue,BTO:0000570,Gene,Tissue,DigitalAgingAtlas,Mus musculus,4-aminobutyrate aminotransferase,hematopoietic system,NCBI_ID,BTO_ID,Aging,DigitalAgingAtlas
1,Dhcr7,Gene_Tissue,BTO:0000759,Gene,Tissue,DigitalAgingAtlas,Mus musculus,7-dehydrocholesterol reductase,liver,NCBI_ID,BTO_ID,Aging,DigitalAgingAtlas
2,Abhd14a,Gene_Tissue,BTO:0000887,Gene,Tissue,DigitalAgingAtlas,Mus musculus,abhydrolase domain containing 14A,muscle,NCBI_ID,BTO_ID,Aging,DigitalAgingAtlas
3,Acta1,Gene_Tissue,BTO:0001103,Gene,Tissue,DigitalAgingAtlas,Mus musculus,"actin alpha 1, skeletal muscle",skeletal muscle,NCBI_ID,BTO_ID,Aging,DigitalAgingAtlas
4,Actc1,Gene_Tissue,BTO:0000887,Gene,Tissue,DigitalAgingAtlas,Mus musculus,"actin, alpha, cardiac muscle 1",muscle,NCBI_ID,BTO_ID,Aging,DigitalAgingAtlas
...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,Zbtb47,Gene_Tissue,BTO:0001103,Gene,Tissue,DigitalAgingAtlas,Mus musculus,zinc finger and BTB domain containing 47,skeletal muscle,NCBI_ID,BTO_ID,Aging,DigitalAgingAtlas
572,Zfp68,Gene_Tissue,BTO:0000142,Gene,Tissue,DigitalAgingAtlas,Mus musculus,zinc finger protein 68,brain,NCBI_ID,BTO_ID,Aging,DigitalAgingAtlas
573,Zfp84,Gene_Tissue,BTO:0000763,Gene,Tissue,DigitalAgingAtlas,Mus musculus,zinc finger protein 84,lung,NCBI_ID,BTO_ID,Aging,DigitalAgingAtlas
574,Zzz3,Gene_Tissue,BTO:0001103,Gene,Tissue,DigitalAgingAtlas,Mus musculus,"zinc finger, ZZ domain containing 3",skeletal muscle,NCBI_ID,BTO_ID,Aging,DigitalAgingAtlas
575,Polr1h,Gene_Tissue,BTO:0000763,Gene,Tissue,DigitalAgingAtlas,Mus musculus,RNA polymerase I subunit H,lung,NCBI_ID,BTO_ID,Aging,DigitalAgingAtlas

In [7]:
# DAA[DAA['head_detail_name'].isna()]

# Consolidate into Unified Schem

In [8]:
# List all source DataFrames to include
source_dfs = [
    DAA,
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 576

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Abat,Gene_Tissue,BTO:0000570,Gene,None,Tissue,DigitalAgingAtlas,Aging,NCBI_ID,BTO_ID,4-aminobutyrate aminotransferase,hematopoietic system,Mus musculus
1,Dhcr7,Gene_Tissue,BTO:0000759,Gene,None,Tissue,DigitalAgingAtlas,Aging,NCBI_ID,BTO_ID,7-dehydrocholesterol reductase,liver,Mus musculus
2,Abhd14a,Gene_Tissue,BTO:0000887,Gene,None,Tissue,DigitalAgingAtlas,Aging,NCBI_ID,BTO_ID,abhydrolase domain containing 14A,muscle,Mus musculus
3,Acta1,Gene_Tissue,BTO:0001103,Gene,None,Tissue,DigitalAgingAtlas,Aging,NCBI_ID,BTO_ID,"actin alpha 1, skeletal muscle",skeletal muscle,Mus musculus
4,Actc1,Gene_Tissue,BTO:0000887,Gene,None,Tissue,DigitalAgingAtlas,Aging,NCBI_ID,BTO_ID,"actin, alpha, cardiac muscle 1",muscle,Mus musculus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,Zbtb47,Gene_Tissue,BTO:0001103,Gene,None,Tissue,DigitalAgingAtlas,Aging,NCBI_ID,BTO_ID,zinc finger and BTB domain containing 47,skeletal muscle,Mus musculus
572,Zfp68,Gene_Tissue,BTO:0000142,Gene,None,Tissue,DigitalAgingAtlas,Aging,NCBI_ID,BTO_ID,zinc finger protein 68,brain,Mus musculus
573,Zfp84,Gene_Tissue,BTO:0000763,Gene,None,Tissue,DigitalAgingAtlas,Aging,NCBI_ID,BTO_ID,zinc finger protein 84,lung,Mus musculus
574,Zzz3,Gene_Tissue,BTO:0001103,Gene,None,Tissue,DigitalAgingAtlas,Aging,NCBI_ID,BTO_ID,"zinc finger, ZZ domain containing 3",skeletal muscle,Mus musculus
575,Polr1h,Gene_Tissue,BTO:0000763,Gene,None,Tissue,DigitalAgingAtlas,Aging,NCBI_ID,BTO_ID,RNA polymerase I subunit H,lung,Mus musculus

# Sanity Check — Distinct Values

In [9]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_Tissue'}
head_type           : {'Gene'}
tail_type           : {'Tissue'}
relation_type       : {None}
kg_source           : {'DigitalAgingAtlas'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'BTO_ID'}

In [10]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 576 remaining

# NaN Audit (pre-dedup)

In [11]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           576                   0             576
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [12]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 576  |  After dedup: 574

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,1600029I14Rik,Gene_Tissue,BTO:0000570,Gene,None,Tissue,DigitalAgingAtlas,Aging,NCBI_ID,BTO_ID,RIKEN cDNA 1600029I14 gene,hematopoietic system,Mus musculus
1,1700056E22Rik,Gene_Tissue,BTO:0000763,Gene,None,Tissue,DigitalAgingAtlas,Aging,NCBI_ID,BTO_ID,RIKEN cDNA 1700056E22 gene,lung,Mus musculus
2,1810044D09Rik,Gene_Tissue,BTO:0000570,Gene,None,Tissue,DigitalAgingAtlas,Aging,NCBI_ID,BTO_ID,RIKEN cDNA 1810044D09 gene,hematopoietic system,Mus musculus

In [13]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           574                   0             574
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'DigitalAgingAtlas'} kg_source
DigitalAgingAtlas    574
Name: count, dtype: int64

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    574
Name: count, dtype: int64

In [16]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 574 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_tissue/Mouse_gene_tissue.csv