In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_mirna_gene
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_mirna_gene/Mouse_mirna_gene.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Mouse_mirna_gene’: File exists

In [4]:
#

In [5]:
# Mouse = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Mus_musculus.gene_info',
#     sep='\t',
    
# )
# # Mouse["LocusTag"] = Mouse["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Mouse_symbol2Locus_dict = dict(zip(Mouse['Symbol'], Mouse['LocusTag']))
# # Mouse
# # Mouse_symbol2Locus_dict
# Mouse

# mirna

In [6]:
mirna = pd.read_csv(PROC_DIR + 'mirTARbase/mmus/miRTarBase_Mirna_Gene.csv')

mirna.columns = mirna.columns.str.lower()
mirna = mirna.rename(columns={
    'headtype': 'head_type',
    'tailtype': 'tail_type',
})
mirna = mirna[~mirna['head_detail_name'].isna()]
mirna['kg_type'] = 'Generalised'
mirna['kg_source'] = 'miRTarBase'
mirna['species'] = 'M.musculus'
mirna['tail_id_is'] = 'NCBI_ID'
mirna['head_id_is'] = 'miRTarBase_ID'

print(f"mirna: {len(mirna):,} rows")
mirna

mirna: 654,247 rows

,head,relation,tail,head_type,tail_type,kg_source,head_detail_name,tail_detail_name,species,kg_type,tail_id_is,head_id_is
0,mmu-miR-122-5p,Mirna_Gene,Cd320,Mirna,Gene,miRTarBase,mmu-miR-122-5p,CD320 antigen,M.musculus,Generalised,NCBI_ID,miRTarBase_ID
1,mmu-miR-122-5p,Mirna_Gene,Cd320,Mirna,Gene,miRTarBase,mmu-miR-122-5p,CD320 antigen,M.musculus,Generalised,NCBI_ID,miRTarBase_ID
2,mmu-miR-122-5p,Mirna_Gene,Ndrg3,Mirna,Gene,miRTarBase,mmu-miR-122-5p,N-myc downstream regulated gene 3,M.musculus,Generalised,NCBI_ID,miRTarBase_ID
3,mmu-miR-122-5p,Mirna_Gene,Ndrg3,Mirna,Gene,miRTarBase,mmu-miR-122-5p,N-myc downstream regulated gene 3,M.musculus,Generalised,NCBI_ID,miRTarBase_ID
4,mmu-miR-122-5p,Mirna_Gene,Ndrg3,Mirna,Gene,miRTarBase,mmu-miR-122-5p,N-myc downstream regulated gene 3,M.musculus,Generalised,NCBI_ID,miRTarBase_ID
...,...,...,...,...,...,...,...,...,...,...,...,...
654242,mmu-miR-125b-5p,Mirna_Gene,Tnfrsf1b,Mirna,Gene,miRTarBase,mmu-miR-125b-5p,"tumor necrosis factor receptor superfamily, me...",M.musculus,Generalised,NCBI_ID,miRTarBase_ID
654243,mmu-miR-351,Mirna_Gene,Tnfrsf1b,Mirna,Gene,miRTarBase,mmu-miR-351,"tumor necrosis factor receptor superfamily, me...",M.musculus,Generalised,NCBI_ID,miRTarBase_ID
654244,mmu-miR-670,Mirna_Gene,Tnfrsf1b,Mirna,Gene,miRTarBase,mmu-miR-670,"tumor necrosis factor receptor superfamily, me...",M.musculus,Generalised,NCBI_ID,miRTarBase_ID
654245,mmu-miR-3473c,Mirna_Gene,Tnrc6b,Mirna,Gene,miRTarBase,mmu-miR-3473c,trinucleotide repeat containing 6b,M.musculus,Generalised,NCBI_ID,miRTarBase_ID
654246,mmu-miR-3473c,Mirna_Gene,Zfp738,Mirna,Gene,miRTarBase,mmu-miR-3473c,zinc finger protein 738,M.musculus,Generalised,NCBI_ID,miRTarBase_ID

# Consolidate into Unified Schem

In [7]:
# List all source DataFrames to include
source_dfs = [
    mirna,
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 654,247

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,mmu-miR-122-5p,Mirna_Gene,Cd320,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,mmu-miR-122-5p,CD320 antigen,M.musculus
1,mmu-miR-122-5p,Mirna_Gene,Cd320,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,mmu-miR-122-5p,CD320 antigen,M.musculus
2,mmu-miR-122-5p,Mirna_Gene,Ndrg3,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,mmu-miR-122-5p,N-myc downstream regulated gene 3,M.musculus
3,mmu-miR-122-5p,Mirna_Gene,Ndrg3,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,mmu-miR-122-5p,N-myc downstream regulated gene 3,M.musculus
4,mmu-miR-122-5p,Mirna_Gene,Ndrg3,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,mmu-miR-122-5p,N-myc downstream regulated gene 3,M.musculus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
654242,mmu-miR-125b-5p,Mirna_Gene,Tnfrsf1b,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,mmu-miR-125b-5p,"tumor necrosis factor receptor superfamily, me...",M.musculus
654243,mmu-miR-351,Mirna_Gene,Tnfrsf1b,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,mmu-miR-351,"tumor necrosis factor receptor superfamily, me...",M.musculus
654244,mmu-miR-670,Mirna_Gene,Tnfrsf1b,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,mmu-miR-670,"tumor necrosis factor receptor superfamily, me...",M.musculus
654245,mmu-miR-3473c,Mirna_Gene,Tnrc6b,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,mmu-miR-3473c,trinucleotide repeat containing 6b,M.musculus
654246,mmu-miR-3473c,Mirna_Gene,Zfp738,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,mmu-miR-3473c,zinc finger protein 738,M.musculus

# Sanity Check — Distinct Values

In [8]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Mirna_Gene'}
head_type           : {'Mirna'}
tail_type           : {'Gene'}
relation_type       : {None}
kg_source           : {'miRTarBase'}
head_id_is          : {'miRTarBase_ID'}
tail_id_is          : {'NCBI_ID'}

In [9]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 654,247 remaining

# NaN Audit (pre-dedup)

In [10]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type        654247                   0          654247
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [11]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 654,247  |  After dedup: 394,133

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,mmu-let-7a,Mirna_Gene,1600014C10Rik,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,mmu-let-7a,RIKEN cDNA 1600014C10 gene,M.musculus
1,mmu-let-7a,Mirna_Gene,5031439G07Rik,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,mmu-let-7a,RIKEN cDNA 5031439G07 gene,M.musculus
2,mmu-let-7a,Mirna_Gene,6030458C11Rik,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,mmu-let-7a,RIKEN cDNA 6030458C11 gene,M.musculus

In [12]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type        394133                   0          394133
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'miRTarBase'} kg_source
miRTarBase    394133
Name: count, dtype: int64

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    394133
Name: count, dtype: int64

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 394,133 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_mirna_gene/Mouse_mirna_gene.csv

In [16]:
OUT_PATH

'/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_mirna_gene/Mouse_mirna_gene.csv'