In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_anatomy_anatomy
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_anatomy_anatomy/Mouse_anatomy_anatomy.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

In [5]:
# Mouse = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Mus_musculus.gene_info',
#     sep='\t',
    
# )
# # Mouse["LocusTag"] = Mouse["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Mouse_symbol2Locus_dict = dict(zip(Mouse['Symbol'], Mouse['LocusTag']))
# # Mouse
# # Mouse_symbol2Locus_dict
# Mouse

# monarch

In [6]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Mouse/Mouse_AnatomicalEntity_AnatomicalEntity.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch.rename(columns={
    'headtype': 'head_type',
    'tailtype': 'tail_type',
})
# monarch = monarch[~monarch['head_detail_name'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'
monarch['species'] = 'M.musculus'
monarch['relation'] = 'AnatomicalEntity_AnatomicalEntity'
monarch['head_type'] = 'AnatomicalEntity'
monarch['tail_type'] = 'AnatomicalEntity'

print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 4,579 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,species,kg_type,kg_source
0,EMAPA:16032,AnatomicalEntity_AnatomicalEntity,EMAPA:31859,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:emapa,first polar body,polar body,Mus musculus,Mus musculus,EMAPA,EMAPA,M.musculus,Generalised,Monarch_KG
1,EMAPA:16033,AnatomicalEntity_AnatomicalEntity,EMAPA:36032,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:emapa,1-cell stage embryo,early embryo,Mus musculus,Mus musculus,EMAPA,EMAPA,M.musculus,Generalised,Monarch_KG
2,EMAPA:16034,AnatomicalEntity_AnatomicalEntity,EMAPA:31859,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:emapa,second polar body,polar body,Mus musculus,Mus musculus,EMAPA,EMAPA,M.musculus,Generalised,Monarch_KG
3,EMAPA:16036,AnatomicalEntity_AnatomicalEntity,EMAPA:36032,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:emapa,2-cell stage embryo,early embryo,Mus musculus,Mus musculus,EMAPA,EMAPA,M.musculus,Generalised,Monarch_KG
4,EMAPA:16037,AnatomicalEntity_AnatomicalEntity,EMAPA:36032,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:emapa,4-8 cell stage embryo,early embryo,Mus musculus,Mus musculus,EMAPA,EMAPA,M.musculus,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4574,EMAPA:38234,AnatomicalEntity_AnatomicalEntity,EMAPA:35263,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:emapa,cranial suture mesenchyme,cranial suture,Mus musculus,Mus musculus,EMAPA,EMAPA,M.musculus,Generalised,Monarch_KG
4575,EMAPA:38235,AnatomicalEntity_AnatomicalEntity,EMAPA:35263,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:emapa,cranial suture osteogenic front,cranial suture,Mus musculus,Mus musculus,EMAPA,EMAPA,M.musculus,Generalised,Monarch_KG
4576,EMAPA:38236,AnatomicalEntity_AnatomicalEntity,EMAPA:38235,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:emapa,coronal suture osteogenic front,cranial suture osteogenic front,Mus musculus,Mus musculus,EMAPA,EMAPA,M.musculus,Generalised,Monarch_KG
4577,EMAPA:38237,AnatomicalEntity_AnatomicalEntity,EMAPA:38235,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:emapa,lambdoid suture osteogenic front,cranial suture osteogenic front,Mus musculus,Mus musculus,EMAPA,EMAPA,M.musculus,Generalised,Monarch_KG
4578,EMAPA:38238,AnatomicalEntity_AnatomicalEntity,EMAPA:35178,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:emapa,exocoelomic cavity fluid,body fluid or substance,Mus musculus,Mus musculus,EMAPA,EMAPA,M.musculus,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [7]:
# List all source DataFrames to include
source_dfs = [
    monarch,
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 4,579

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,EMAPA:16032,AnatomicalEntity_AnatomicalEntity,EMAPA:31859,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,EMAPA,EMAPA,first polar body,polar body,M.musculus
1,EMAPA:16033,AnatomicalEntity_AnatomicalEntity,EMAPA:36032,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,EMAPA,EMAPA,1-cell stage embryo,early embryo,M.musculus
2,EMAPA:16034,AnatomicalEntity_AnatomicalEntity,EMAPA:31859,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,EMAPA,EMAPA,second polar body,polar body,M.musculus
3,EMAPA:16036,AnatomicalEntity_AnatomicalEntity,EMAPA:36032,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,EMAPA,EMAPA,2-cell stage embryo,early embryo,M.musculus
4,EMAPA:16037,AnatomicalEntity_AnatomicalEntity,EMAPA:36032,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,EMAPA,EMAPA,4-8 cell stage embryo,early embryo,M.musculus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4574,EMAPA:38234,AnatomicalEntity_AnatomicalEntity,EMAPA:35263,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,EMAPA,EMAPA,cranial suture mesenchyme,cranial suture,M.musculus
4575,EMAPA:38235,AnatomicalEntity_AnatomicalEntity,EMAPA:35263,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,EMAPA,EMAPA,cranial suture osteogenic front,cranial suture,M.musculus
4576,EMAPA:38236,AnatomicalEntity_AnatomicalEntity,EMAPA:38235,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,EMAPA,EMAPA,coronal suture osteogenic front,cranial suture osteogenic front,M.musculus
4577,EMAPA:38237,AnatomicalEntity_AnatomicalEntity,EMAPA:38235,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,EMAPA,EMAPA,lambdoid suture osteogenic front,cranial suture osteogenic front,M.musculus
4578,EMAPA:38238,AnatomicalEntity_AnatomicalEntity,EMAPA:35178,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,EMAPA,EMAPA,exocoelomic cavity fluid,body fluid or substance,M.musculus

# Sanity Check — Distinct Values

In [8]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'AnatomicalEntity_AnatomicalEntity'}
head_type           : {'AnatomicalEntity'}
tail_type           : {'AnatomicalEntity'}
relation_type       : {'subclass_of'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'EMAPA'}
tail_id_is          : {'EMAPA'}

In [9]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 4,579 remaining

# NaN Audit (pre-dedup)

In [10]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [11]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 4,579  |  After dedup: 4,579

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,EMAPA:16032,AnatomicalEntity_AnatomicalEntity,EMAPA:31859,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,EMAPA,EMAPA,first polar body,polar body,M.musculus
1,EMAPA:16033,AnatomicalEntity_AnatomicalEntity,EMAPA:36032,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,EMAPA,EMAPA,1-cell stage embryo,early embryo,M.musculus
2,EMAPA:16034,AnatomicalEntity_AnatomicalEntity,EMAPA:31859,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,EMAPA,EMAPA,second polar body,polar body,M.musculus

In [12]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    4579
Name: count, dtype: int64

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    4579
Name: count, dtype: int64

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 4,579 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_anatomy_anatomy/Mouse_anatomy_anatomy.csv

In [16]:
# OUT_PATH