In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'


# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

# POSITIVE ASSOCIATION

In [4]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_chemical_positiveassociated_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_chemical_positiveassociated_biologicalprocess/Mouse_chemical_positiveassociated_biologicalprocess.csv'

### Drugage

In [5]:
Drugage = pd.read_csv(PROC_DIR + 'drugage/drugage_final/Mouse_CE_Pos_BioPro_merged.csv')
Drugage.columns = Drugage.columns.str.lower()
Drugage = Drugage[~Drugage['head_detail_name'].isna()]

Drugage['kg_type'] = 'Aging'

print(f"Drugage: {len(Drugage):,} rows")
Drugage['head_id_is'] = 'Pubchem'
Drugage['tail_id_is'] = 'Quick_GO'
Drugage['relation'] = 'ChemicalEntity_PositivelyAssociatedWith_BiologicalProcess'
Drugage['kg_source'] = 'Drugage'
Drugage['tail_detail_name'] = 'aging'
Drugage

Drugage: 41 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,...,age_at_initiation,treatment_duration,avg_lifespan_change_percent,dosage,pubmed_id,kg_type,head_id_is,tail_id_is,kg_source,tail_detail_name
0,6433176,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,3-aminopropanenitrile;(E)-but-2-enedioic acid,C(CN)C#N.C(=C/C(=O)O)\C(=O)O,DrugAge,Mus musculus,Beta-aminopropionitrile fumarate,...,2 months,18 months,5.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
1,6047,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2S)-2-amino-3-(3,4-dihydroxyphenyl)propanoic ...",C1=CC(=C(C=C1C[C@@H](C(=O)O)N)O)O,DrugAge,Mus musculus,Levodopa,...,1 month,until death,28.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
2,3293,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"6-ethoxy-2,2,4-trimethyl-1H-quinoline",CCOC1=CC2=C(C=C1)NC(C=C2C)(C)C,DrugAge,Mus musculus,Ethoxyquin,...,3 months,until death,20.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
3,638877,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,N-tert-butyl-1-phenylmethanimine oxide,CC(C)(C)/[N+](=C/C1=CC=CC=C1)/[O-],DrugAge,Mus musculus,N-tert-butyl-alpha-phenylnitrone,...,24.5 months,until death,4.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
4,219042,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,(4S)-4-[[(2S)-2-aminopropanoyl]amino]-5-[[(2S)...,C[C@@H](C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CC(...,DrugAge,Mus musculus,Epithalamin,...,NaN,NaN,11.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
5,443753,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"calcium;3-[[(2R)-2,4-dihydroxy-3,3-dimethylbut...",CC(C)(CO)[C@H](C(=O)NCCC(=O)[O-])O.CC(C)(CO)[C...,DrugAge,Mus musculus,Calcium pantothenate,...,1 month,until death,20.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
6,443297,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,hydroxylamine;hydrochloride,NO.Cl,DrugAge,Mus musculus,Hydroxylamine hydrochloride,...,after weaning,until death,7.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
7,9082,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-aminoethanethiol;hydrochloride,C(CS)N.Cl,DrugAge,Mus musculus,2-mercaptoethylamine hydrochloride,...,after weaning,until death,26.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
8,8249,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,1-(diaminomethylidene)-2-(2-phenylethyl)guanidine,C1=CC=C(C=C1)CCN=C(N)N=C(N)N,DrugAge,Mus musculus,Phenformin,...,3.5 months,until death,21.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
9,586,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-[carbamimidoyl(methyl)amino]acetic acid,CN(CC(=O)O)C(=N)N,DrugAge,Mus musculus,Creatine,...,12 months,until death,9.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
10,124072,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"1,7-bis(4-hydroxy-3-methoxyphenyl)heptane-3,5-...",COC1=C(C=CC(=C1)CCC(=O)CC(=O)CCC2=CC(=C(C=C2)O...,DrugAge,Mus musculus,Tetrahydrocurcumin,...,13 months,until death,11.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
11,4091,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"3-(diaminomethylidene)-1,1-dimethylguanidine",CN(C)C(=N)N=C(N)N,DrugAge,Mus musculus,Metformin,...,3 months,until death,38.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
12,5284616,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(1R,9S,12S,15R,16E,18R,19R,21R,23S,24E,26E,28E...",C[C@@H]1CC[C@H]2C[C@@H](/C(=C/C=C/C=C/[C@H](C[...,DrugAge,Mus musculus,Rapamycin,...,20 months,until death,13.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
13,134378124,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"1-[(2R)-6-fluoro-3,4-dihydro-2H-chromen-2-yl]-...",C1CC2=C(C=CC(=C2)F)O[C@@H]1[C@@H](CNCC([C@H]3C...,DrugAge,Mus musculus,Nebivolol,...,12 months,until death,6.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
14,4171,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,1-[4-(2-methoxyethyl)phenoxy]-3-(propan-2-ylam...,CC(C)NCC(COC1=CC=C(C=C1)CCOC)O,DrugAge,Mus musculus,Metoprolol,...,12 months,until death,10.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
15,163284948,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2S,5S)-5-[(2R,5S)-5-[(2R,5S,6R)-3,4-dihydroxy...",C[C@@H]1[C@H](C(C([C@H](O1)O[C@@H]2C(O[C@@H](C...,DrugAge,Mus musculus,Acarbose,...,4 months,until death,5.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
16,132999,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"3-[3-[[(7S)-3,4-dimethoxy-7-bicyclo[4.2.0]octa...",CN(CCCN1CCC2=CC(=C(C=C2CC1=O)OC)OC)C[C@H]3CC4=...,DrugAge,Mus musculus,Ivabradine,...,3 months,until death,6.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
17,1103,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"N,N'-bis(3-aminopropyl)butane-1,4-diamine",C(CCNCCCN)CNCCCN,DrugAge,Mus musculus,Spermine,...,4 months,until death,14.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
18,2353,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"16,17-dimethoxy-5,7-dioxa-13-azoniapentacyclo[...",COC1=C(C2=C[N+]3=C(C=C2C=C1)C4=CC5=C(C=C4CC3)O...,DrugAge,Mus musculus,Berberine,...,18 months,4 months,16.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
19,2882155,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"2-[(6-phenyl-2,3,4,9-tetrahydro-1H-carbazol-1-...",C1CC(C2=C(C1)C3=C(N2)C=CC(=C3)C4=CC=CC=C4)NCCO,DrugAge,Mus musculus,CASIN,...,18 months,4 days,10.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
20,169853,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R,3R,4S)-2-(3,4-dihydroxyphenyl)-4-[(2R,3R)-...",C1[C@H]([C@H](OC2=C1C(=CC(=C2[C@@H]3[C@H]([C@H...,DrugAge,Mus musculus,Procyanidin C1,...,24-27 months,until death,9.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
21,72281,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2S)-5,7-dihydroxy-2-(3-hydroxy-4-methoxypheny...",COC1=C(C=C(C=C1)[C@@H]2CC(=O)C3=C(C=C(C=C3O2)O...,DrugAge,Mus musculus,Hesperetin,...,19.5-23.5 months,3-6 months,9.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
22,56649450,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2S)-1-N-[4-methyl-5-[2-(1,1,1-trifluoro-2-met...",CC1=C(SC(=N1)NC(=O)N2CCC[C@H]2C(=O)N)C3=CC(=NC...,DrugAge,Mus musculus,Alpelisib,...,12 months,until death,11.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
23,4034,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,1-[(4-chlorophenyl)-phenylmethyl]-4-[(3-methyl...,CC1=CC(=CC=C1)CN2CCN(CC2)C(C3=CC=CC=C3)C4=CC=C...,DrugAge,Mus musculus,Meclizine,...,12 months,until death,3.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
24,2244,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-acetyloxybenzoic acid,CC(=O)OC1=CC=CC=C1C(=O)O,DrugAge,Mus musculus,Aspirin,...,NaN,NaN,8.00,21 mg/kg food,18631321.0,Aging,Pubchem,Quick_GO,Drugage,aging
25,12035,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,(2R)-2-acetamido-3-sulfanylpropanoic acid,CC(=O)N[C@@H](CS)C(=O)O,DrugAge,Mus musculus,N-acetyl-L-cysteine,...,NaN,NaN,24.00,10 g/L of water,20819793.0,Aging,Pubchem,Quick_GO,Drugage,aging
26,34007,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,oxovanadium(2+);sulfate,[O-]S(=O)(=O)[O-].O=[V+2],DrugAge,Mus musculus,Vanadyl sulfate,...,NaN,NaN,0.17,5 ppm,1113210.0,Aging,Pubchem,Quick_GO,Drugage,aging
27,896,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,N-[2-(5-methoxy-1H-indol-3-yl)ethyl]acetamide,CC(=O)NCCC1=CNC2=C1C=C(C=C2)OC,DrugAge,Mus musculus,Melatonin,...,NaN,NaN,5.40,20 mg/l,11445596.0,Aging,Pubchem,Quick_GO,Drugage,aging
28,164533,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-oxopentanedioate,C(CC(=O)[O-])C(=O)C(=O)[O-],DrugAge,Mus musculus,Alpha-ketoglutarate,...,NaN,NaN,4.80,2% (w/w),32877690.0,Aging,Pubchem,Quick_GO,Drugage,aging
29,6099,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,[7-(dimethylamino)phenothiazin-3-ylidene]-dime...,CN(C)C1=CC2=C(C=C1)N=C3C=CC(=[N+](C)C)C=C3S2.[...,DrugAge,Mus musculus,Methylene blue,...,NaN,NaN,0.70,27 mg/kg diet,24245565.0,Aging,Pubchem,Quick_GO,Drugage,aging
30,439213,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(3R,4R,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)N)O)O)O,DrugAge,Mus musculus,D-glucosamine,...,NaN,NaN,5.60,10 g/kg,24714520.0,Aging,Pubchem,Quick_GO,Drugage,aging
31,9756,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,nickel(2+);diacetate,CC(=O)[O-].CC(=O)[O-].[Ni+2],DrugAge,Mus musculus,Nickelous acetate,...,NaN,NaN,5.48,5 ppm,1113210.0,Aging,Pubchem,Quick_GO,Drugage,aging
32,54670067,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2-[(1S)-1,2-dihydroxyethyl]-3,4-dihydroxy...",C([C@@H]([C@@H]1C(=C(C(=O)O1)O)O)O)O,DrugAge,Mus musculus,Ascorbic acid,...,NaN,NaN,8.60,1 %,6519438.0,Aging,Pubchem,Quick_GO,Drugage,aging
33,26052,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,disodium;dioxido(dioxo)tungsten,[O-][W](=O)(=O)[O-].[Na+].[Na+],DrugAge,Mus musculus,Sodium tungstate,...,NaN,NaN,40.75,5 ppm,1113210.0,Aging,Pubchem,Quick_GO,Drugage,aging
34,14985,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",CC1=C(C2=C(CC[C@@](O2)(C)CCC[C@H](C)CCC[C@H](C...,DrugAge,Mus musculus,Vitamin E,...,NaN,NaN,15.00,550 mg/kg,18257658.0,Aging,Pubchem,Quick_GO,Drugage,aging
35,4534,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"4-[4-(3,4-dihydroxyphenyl)-2,3-dimethylbutyl]b...",CC(CC1=CC(=C(C=C1)O)O)C(C)CC2=CC(=C(C=C2)O)O,DrugAge,Mus musculus,Nordihydroguaiaretic acid,...,NaN,NaN,12.00,2.5 g/kg food,18631321.0,Aging,Pubchem,Quick_GO,Drugage,aging
36,1493,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"2,4-dinitrophenol",C1=CC(=C(C=C1[N+](=O)[O-])[N+](=O)[O-])O,DrugAge,Mus musculus,"2,4-dinitrophenol",...,NaN,NaN,7.10,1 mg/L,18505478.0,Aging,Pubchem,Quick_GO,Drugage,aging
37,1102,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"N'-(3-aminopropyl)butane-1,4-diamine",C(CCNCCCN)CN,DrugAge,Mus musculus,Spermidine,...,NaN,NaN,23.79,Drinking water supplemented with 3mM,28386016.0,Aging,Pubchem,Quick_GO,Drugage,aging
38,439924,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"1-[(2R,3R,4S,5R)-3,4-dihydroxy-5-(hydroxymethy...",C1=CC(=C[N+](=C1)[C@H]2[C@@H]([C@@H]([C@H](O2)...,DrugAge,Mus musculus,Nicotinamide riboside,...,NaN,NaN,4.70,400 mg/kg/day,27127236.0,Aging,Pubchem,Quick_GO,Drugage,aging
39,750,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-aminoacetic acid,C(C(=O)O)N,DrugAge,Mus musculus,Glycine,...,NaN,NaN,6.20,8%,30916479.0,Aging,Pubchem,Quick_GO,Drugage,aging
40,24812758,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2S,3R,4R,5S,6R)-2-[3-[[5-(4-fluorophenyl)thio...",CC1=C(C=C(C=C1)[C@H]2[C@@H]([C@H]([C@@H]([C@H]...,DrugAge,Mus musculus,Canagliflozin,...,NaN,NaN,14.00,30 mg/kg BW,32990681.0,Aging,Pubchem,Quick_GO,Drugage,aging

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
    Drugage
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 41

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,6433176,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,3-aminopropanenitrile;(E)-but-2-enedioic acid,aging,Mus musculus
1,6047,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2S)-2-amino-3-(3,4-dihydroxyphenyl)propanoic ...",aging,Mus musculus
2,3293,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"6-ethoxy-2,2,4-trimethyl-1H-quinoline",aging,Mus musculus
3,638877,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,N-tert-butyl-1-phenylmethanimine oxide,aging,Mus musculus
4,219042,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,(4S)-4-[[(2S)-2-aminopropanoyl]amino]-5-[[(2S)...,aging,Mus musculus
5,443753,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"calcium;3-[[(2R)-2,4-dihydroxy-3,3-dimethylbut...",aging,Mus musculus
6,443297,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,hydroxylamine;hydrochloride,aging,Mus musculus
7,9082,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-aminoethanethiol;hydrochloride,aging,Mus musculus
8,8249,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,1-(diaminomethylidene)-2-(2-phenylethyl)guanidine,aging,Mus musculus
9,586,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-[carbamimidoyl(methyl)amino]acetic acid,aging,Mus musculus
10,124072,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"1,7-bis(4-hydroxy-3-methoxyphenyl)heptane-3,5-...",aging,Mus musculus
11,4091,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"3-(diaminomethylidene)-1,1-dimethylguanidine",aging,Mus musculus
12,5284616,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(1R,9S,12S,15R,16E,18R,19R,21R,23S,24E,26E,28E...",aging,Mus musculus
13,134378124,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"1-[(2R)-6-fluoro-3,4-dihydro-2H-chromen-2-yl]-...",aging,Mus musculus
14,4171,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,1-[4-(2-methoxyethyl)phenoxy]-3-(propan-2-ylam...,aging,Mus musculus
15,163284948,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2S,5S)-5-[(2R,5S)-5-[(2R,5S,6R)-3,4-dihydroxy...",aging,Mus musculus
16,132999,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"3-[3-[[(7S)-3,4-dimethoxy-7-bicyclo[4.2.0]octa...",aging,Mus musculus
17,1103,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"N,N'-bis(3-aminopropyl)butane-1,4-diamine",aging,Mus musculus
18,2353,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"16,17-dimethoxy-5,7-dioxa-13-azoniapentacyclo[...",aging,Mus musculus
19,2882155,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"2-[(6-phenyl-2,3,4,9-tetrahydro-1H-carbazol-1-...",aging,Mus musculus
20,169853,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2R,3R,4S)-2-(3,4-dihydroxyphenyl)-4-[(2R,3R)-...",aging,Mus musculus
21,72281,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2S)-5,7-dihydroxy-2-(3-hydroxy-4-methoxypheny...",aging,Mus musculus
22,56649450,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2S)-1-N-[4-methyl-5-[2-(1,1,1-trifluoro-2-met...",aging,Mus musculus
23,4034,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,1-[(4-chlorophenyl)-phenylmethyl]-4-[(3-methyl...,aging,Mus musculus
24,2244,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-acetyloxybenzoic acid,aging,Mus musculus
25,12035,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,(2R)-2-acetamido-3-sulfanylpropanoic acid,aging,Mus musculus
26,34007,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,oxovanadium(2+);sulfate,aging,Mus musculus
27,896,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,N-[2-(5-methoxy-1H-indol-3-yl)ethyl]acetamide,aging,Mus musculus
28,164533,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-oxopentanedioate,aging,Mus musculus
29,6099,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,[7-(dimethylamino)phenothiazin-3-ylidene]-dime...,aging,Mus musculus
30,439213,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(3R,4R,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",aging,Mus musculus
31,9756,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,nickel(2+);diacetate,aging,Mus musculus
32,54670067,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2R)-2-[(1S)-1,2-dihydroxyethyl]-3,4-dihydroxy...",aging,Mus musculus
33,26052,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,disodium;dioxido(dioxo)tungsten,aging,Mus musculus
34,14985,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",aging,Mus musculus
35,4534,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"4-[4-(3,4-dihydroxyphenyl)-2,3-dimethylbutyl]b...",aging,Mus musculus
36,1493,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"2,4-dinitrophenol",aging,Mus musculus
37,1102,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"N'-(3-aminopropyl)butane-1,4-diamine",aging,Mus musculus
38,439924,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"1-[(2R,3R,4S,5R)-3,4-dihydroxy-5-(hydroxymethy...",aging,Mus musculus
39,750,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-aminoacetic acid,aging,Mus musculus
40,24812758,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2S,3R,4R,5S,6R)-2-[3-[[5-(4-fluorophenyl)thio...",aging,Mus musculus

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'ChemicalEntity_PositivelyAssociatedWith_BiologicalProcess'}
head_type           : {'ChemicalEntity'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'Drugage'}
head_id_is          : {'Pubchem'}
tail_id_is          : {'Quick_GO'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 41 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            41                   0              41
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 41  |  After dedup: 41

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,586,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-[carbamimidoyl(methyl)amino]acetic acid,aging,Mus musculus
1,750,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-aminoacetic acid,aging,Mus musculus
2,896,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,N-[2-(5-methoxy-1H-indol-3-yl)ethyl]acetamide,aging,Mus musculus

In [11]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            41                   0              41
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Drugage'} kg_source
Drugage    41
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    41
Name: count, dtype: int64

In [14]:
! mkdir Mouse_chemical_positiveassociated_biologicalprocess

mkdir: cannot create directory ‘Mouse_chemical_positiveassociated_biologicalprocess’: File exists

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 41 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_chemical_positiveassociated_biologicalprocess/Mouse_chemical_positiveassociated_biologicalprocess.csv

In [16]:
# OUT_PATH

# NEGATIVE ASSOCIATION

In [17]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_chemical_negativeassociated_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_chemical_negativeassociated_biologicalprocess/Mouse_chemical_negativeassociated_biologicalprocess.csv'

In [18]:
Drugage = pd.read_csv(PROC_DIR + 'drugage/drugage_final/Mouse_CE_Neg_BioPro_merged.csv')
Drugage.columns = Drugage.columns.str.lower()
Drugage = Drugage[~Drugage['head_detail_name'].isna()]

Drugage['kg_type'] = 'Aging'

print(f"Drugage: {len(Drugage):,} rows")
Drugage['head_id_is'] = 'Pubchem'
Drugage['tail_id_is'] = 'Quick_GO'
Drugage['relation'] = 'ChemicalEntity_NegativelyAssociatedWith_BiologicalProcess'
Drugage['kg_source'] = 'Drugage'
Drugage['tail_detail_name'] = 'aging'
Drugage

Drugage: 9 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,...,age_at_initiation,treatment_duration,avg_lifespan_change_percent,dosage,pubmed_id,kg_type,head_id_is,tail_id_is,kg_source,tail_detail_name
0,24012,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,trichloroalumane,[Al](Cl)(Cl)Cl,DrugAge,Mus musculus,Aluminium chloride,...,20 months,until death,-7.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
1,22053264,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,4-phenylbutanoate,C1=CC=C(C=C1)CCCC(=O)[O-],DrugAge,Mus musculus,4-phenylbutyrate,...,9 months,until death,-2.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
2,5756,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(8R,9S,13S,14S,16R,17R)-13-methyl-6,7,8,9,11,1...",C[C@]12CC[C@H]3[C@H]([C@@H]1C[C@H]([C@@H]2O)O)...,DrugAge,Mus musculus,16-alpha-hydroxyestradiol,...,12 months,until death,-7.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
3,2719,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"4-N-(7-chloroquinolin-4-yl)-1-N,1-N-diethylpen...",CCN(CC)CCCC(C)NC1=C2C=CC(=CC2=NC=C1)Cl,DrugAge,Mus musculus,Chloroquine,...,NaN,NaN,-16.80,13.2 µg/mL,4788962.0,Aging,Pubchem,Quick_GO,Drugage,aging
4,10980,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,barium(2+);diacetate,CC(=O)[O-].CC(=O)[O-].[Ba+2],DrugAge,Mus musculus,Barium acetate,...,NaN,NaN,-8.80,5 ppm,1113210.0,Aging,Pubchem,Quick_GO,Drugage,aging
5,5280343,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"2-(3,4-dihydroxyphenyl)-3,5,7-trihydroxychrome...",C1=CC(=C(C=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O)O)O,DrugAge,Mus musculus,Quercetin,...,NaN,NaN,-14.20,10 mg/day,7140862.0,Aging,Pubchem,Quick_GO,Drugage,aging
6,4654,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-amino-3-(4-fluorophenyl)propanoic acid,C1=CC(=CC=C1CC(C(=O)O)N)F,DrugAge,Mus musculus,p-fluorophenylalanine,...,NaN,NaN,-15.43,0.4 mM,689376.0,Aging,Pubchem,Quick_GO,Drugage,aging
7,84815,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,(2R)-2-amino-4-methylsulfanylbutanoic acid,CSCC[C@H](C(=O)O)N,DrugAge,Mus musculus,Methionine,...,NaN,NaN,-16.90,0.05 M,6519211.0,Aging,Pubchem,Quick_GO,Drugage,aging
8,4091,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"3-(diaminomethylidene)-1,1-dimethylguanidine",CN(C)C(=N)N=C(N)N,DrugAge,Mus musculus,Metformin,...,NaN,NaN,-1.53,100 mg/kg/day,33585467.0,Aging,Pubchem,Quick_GO,Drugage,aging

In [19]:
# List all source DataFrames to include
source_dfs = [
    Drugage
    
]
aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 9

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,24012,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,trichloroalumane,aging,Mus musculus
1,22053264,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,4-phenylbutanoate,aging,Mus musculus
2,5756,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(8R,9S,13S,14S,16R,17R)-13-methyl-6,7,8,9,11,1...",aging,Mus musculus
3,2719,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"4-N-(7-chloroquinolin-4-yl)-1-N,1-N-diethylpen...",aging,Mus musculus
4,10980,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,barium(2+);diacetate,aging,Mus musculus
5,5280343,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"2-(3,4-dihydroxyphenyl)-3,5,7-trihydroxychrome...",aging,Mus musculus
6,4654,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-amino-3-(4-fluorophenyl)propanoic acid,aging,Mus musculus
7,84815,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,(2R)-2-amino-4-methylsulfanylbutanoic acid,aging,Mus musculus
8,4091,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"3-(diaminomethylidene)-1,1-dimethylguanidine",aging,Mus musculus

In [20]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             9                   0               9
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [21]:
! mkdir Mouse_chemical_negativeassociated_biologicalprocess

mkdir: cannot create directory ‘Mouse_chemical_negativeassociated_biologicalprocess’: File exists

In [22]:
final_df.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df):,} rows → {OUT_PATH}")

Saved 9 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_chemical_negativeassociated_biologicalprocess/Mouse_chemical_negativeassociated_biologicalprocess.csv

# NOT ASSOCIATION

In [23]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_chemical_notassociated_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_chemical_notassociated_biologicalprocess/Mouse_chemical_notassociated_biologicalprocess.csv'

In [24]:
Drugage = pd.read_csv(PROC_DIR + 'drugage/drugage_final/Mouse_CE_Not_BioPro_merged.csv')
Drugage.columns = Drugage.columns.str.lower()
Drugage = Drugage[~Drugage['head_detail_name'].isna()]

Drugage['kg_type'] = 'Aging'

print(f"Drugage: {len(Drugage):,} rows")
Drugage['head_id_is'] = 'Pubchem'
Drugage['tail_id_is'] = 'Quick_GO'
Drugage['relation'] = 'ChemicalEntity_NotAssociatedWith_BiologicalProcess'
Drugage['kg_source'] = 'Drugage'
Drugage['tail_detail_name'] = 'aging'
Drugage

Drugage: 61 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,...,age_at_initiation,treatment_duration,avg_lifespan_change_percent,dosage,pubmed_id,kg_type,head_id_is,tail_id_is,kg_source,tail_detail_name
0,4654,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,2-amino-3-(4-fluorophenyl)propanoic acid,C1=CC(=CC=C1CC(C(=O)O)N)F,DrugAge,Mus musculus,p-fluorophenylalanine,...,12 months,4 weeks,-5.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
1,3598,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"3,4,6-trichloro-2-[(2,3,5-trichloro-6-hydroxyp...",C1=C(C(=C(C(=C1Cl)Cl)CC2=C(C(=CC(=C2Cl)Cl)Cl)O...,DrugAge,Mus musculus,Hexachlorophene,...,1 month,until death,-7.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
2,40473195,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"[2-[(8S,9S,10R,11S,13S,14S,17R)-11,17-dihydrox...",C[C@]12C[C@@H]([C@H]3[C@H]([C@@H]1CC[C@@]2(C(=...,DrugAge,Mus musculus,Prednisolone sodium phosphate,...,7.7 months,until death,0.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
3,5280489,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"1,3,3-trimethyl-2-[(1E,3E,5E,7E,9E,11E,13E,15E...",CC1=C(C(CCC1)(C)C)/C=C/C(=C/C=C/C(=C/C=C/C=C(/...,DrugAge,Mus musculus,Beta-carotene,...,20 months,until death,-10.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
4,2726,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"3-(2-chlorophenothiazin-10-yl)-N,N-dimethylpro...",CN(C)CCCN1C2=CC=CC=C2SC3=C1C=C(C=C3)Cl,DrugAge,Mus musculus,Chlorpromazine,...,9.7 or 10.7 months,until death,0.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,5881,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"(3S,8R,9S,10R,13S,14S)-3-hydroxy-10,13-dimethy...",C[C@]12CC[C@H]3[C@H]([C@@H]1CCC2=O)CC=C4[C@@]3...,DrugAge,Mus musculus,Dehydroepiandrosterone,...,NaN,NaN,2.35,25 μg/mL,10197641.0,Aging,Pubchem,Quick_GO,Drugage,aging
57,439924,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"1-[(2R,3R,4S,5R)-3,4-dihydroxy-5-(hydroxymethy...",C1=CC(=C[N+](=C1)[C@H]2[C@@H]([C@@H]([C@H](O2)...,DrugAge,Mus musculus,Nicotinamide riboside,...,NaN,NaN,0.00,1000 ppm,33788371.0,Aging,Pubchem,Quick_GO,Drugage,aging
58,44631884,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"3-[(3-hydroxyphenyl)methyl]-5-methyl-1,3-benzo...",CC1=CC2=C(C=C1)OC(=O)N2CC3=CC(=CC=C3)O,DrugAge,Mus musculus,MIF098,...,NaN,NaN,-1.00,240 ppm,33788371.0,Aging,Pubchem,Quick_GO,Drugage,aging
59,2244,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,2-acetyloxybenzoic acid,CC(=O)OC1=CC=CC=C1C(=O)O,DrugAge,Mus musculus,Aspirin,...,NaN,NaN,-1.00,60 ppm,30916479.0,Aging,Pubchem,Quick_GO,Drugage,aging
60,44250349,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,5-chloro-2-[[2-[2-[3-(furan-3-yl)anilino]-2-ox...,C1=CC(=CC(=C1)NC(=O)COCC(=O)NC2=C(C=C(C=C2)Cl)...,DrugAge,Mus musculus,TM5441,...,NaN,NaN,-4.00,60 ppm,30916479.0,Aging,Pubchem,Quick_GO,Drugage,aging

In [25]:
# List all source DataFrames to include
source_dfs = [
    Drugage
    
]
aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 61

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,4654,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-amino-3-(4-fluorophenyl)propanoic acid,aging,Mus musculus
1,3598,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"3,4,6-trichloro-2-[(2,3,5-trichloro-6-hydroxyp...",aging,Mus musculus
2,40473195,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"[2-[(8S,9S,10R,11S,13S,14S,17R)-11,17-dihydrox...",aging,Mus musculus
3,5280489,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"1,3,3-trimethyl-2-[(1E,3E,5E,7E,9E,11E,13E,15E...",aging,Mus musculus
4,2726,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"3-(2-chlorophenothiazin-10-yl)-N,N-dimethylpro...",aging,Mus musculus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,5881,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(3S,8R,9S,10R,13S,14S)-3-hydroxy-10,13-dimethy...",aging,Mus musculus
57,439924,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"1-[(2R,3R,4S,5R)-3,4-dihydroxy-5-(hydroxymethy...",aging,Mus musculus
58,44631884,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"3-[(3-hydroxyphenyl)methyl]-5-methyl-1,3-benzo...",aging,Mus musculus
59,2244,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-acetyloxybenzoic acid,aging,Mus musculus
60,44250349,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,5-chloro-2-[[2-[2-[3-(furan-3-yl)anilino]-2-ox...,aging,Mus musculus

In [26]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            61                   0              61
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [27]:
! mkdir Mouse_chemical_notassociated_biologicalprocess

mkdir: cannot create directory ‘Mouse_chemical_notassociated_biologicalprocess’: File exists

In [28]:
final_df.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df):,} rows → {OUT_PATH}")

Saved 61 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_chemical_notassociated_biologicalprocess/Mouse_chemical_notassociated_biologicalprocess.csv