In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'


# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

In [5]:
# Mouse = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Mus_musculus.gene_info',
#     sep='\t',
    
# )
# # Mouse["LocusTag"] = Mouse["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Mouse_symbol2Locus_dict = dict(zip(Mouse['Symbol'], Mouse['LocusTag']))
# # Mouse
# # Mouse_symbol2Locus_dict
# Mouse

# DAA POSITIVE Association

In [6]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_gene_POS_ASS_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_POS_ASS_biologicalprocess/Mouse_gene_POS_ASS_biologicalprocess.csv'

In [7]:
DAA = pd.read_csv(PROC_DIR + 'digitalagingatlas/Mouse/DAA_Mouse_Gene_Pos_BiologicalProcess.csv')
DAA.columns = DAA.columns.str.lower()
DAA = DAA[~DAA['head_detail_name'].isna()]

DAA['kg_type'] = 'Aging'

print(f"DAA: {len(DAA):,} rows")
DAA['head_id_is'] = 'NCBI_ID'
DAA['tail_id_is'] = 'Quick_GO'
DAA['species'] = 'Mus musculus'
DAA['tail_detail_name'] = 'aging'
DAA['kg_source'] = 'DAA'
DAA['relation'] = 'Gene_PositivelyAssociatedWith_BiologicalProcess'
DAA

DAA: 307 rows

,head,relation,tail,head_type,tail_type,head_detail_name,relation_source,species,data_type,kg_type,head_id_is,tail_id_is,tail_detail_name,kg_source
0,Abat,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,4-aminobutyrate aminotransferase,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
1,Dhcr7,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,7-dehydrocholesterol reductase,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
2,Acta1,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"actin alpha 1, skeletal muscle",DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
3,Alcam,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,activated leukocyte cell adhesion molecule,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
4,Adam25,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,ADAM metallopeptidase domain 25,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,Zbtb16,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc finger and BTB domain containing 16,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
303,Zcchc18,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"zinc finger, CCHC domain containing 18",DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
304,Zfp62,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc finger protein 62,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
305,Zfp64,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc finger protein 64,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
306,Zfp68,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc finger protein 68,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA

# Consolidate into Unified Schem

In [8]:
# List all source DataFrames to include
source_dfs = [
    DAA, 
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 307

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Abat,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,DAA,Aging,NCBI_ID,Quick_GO,4-aminobutyrate aminotransferase,aging,Mus musculus
1,Dhcr7,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,DAA,Aging,NCBI_ID,Quick_GO,7-dehydrocholesterol reductase,aging,Mus musculus
2,Acta1,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,DAA,Aging,NCBI_ID,Quick_GO,"actin alpha 1, skeletal muscle",aging,Mus musculus
3,Alcam,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,DAA,Aging,NCBI_ID,Quick_GO,activated leukocyte cell adhesion molecule,aging,Mus musculus
4,Adam25,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,DAA,Aging,NCBI_ID,Quick_GO,ADAM metallopeptidase domain 25,aging,Mus musculus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,Zbtb16,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,DAA,Aging,NCBI_ID,Quick_GO,zinc finger and BTB domain containing 16,aging,Mus musculus
303,Zcchc18,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,DAA,Aging,NCBI_ID,Quick_GO,"zinc finger, CCHC domain containing 18",aging,Mus musculus
304,Zfp62,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,DAA,Aging,NCBI_ID,Quick_GO,zinc finger protein 62,aging,Mus musculus
305,Zfp64,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,DAA,Aging,NCBI_ID,Quick_GO,zinc finger protein 64,aging,Mus musculus
306,Zfp68,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,DAA,Aging,NCBI_ID,Quick_GO,zinc finger protein 68,aging,Mus musculus

# Sanity Check — Distinct Values

In [9]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_PositivelyAssociatedWith_BiologicalProcess'}
head_type           : {'Gene'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'DAA'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [10]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 307 remaining

# NaN Audit (pre-dedup)

In [11]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           307                   0             307
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [12]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 307  |  After dedup: 297

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,1600029I14Rik,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,DAA,Aging,NCBI_ID,Quick_GO,RIKEN cDNA 1600029I14 gene,aging,Mus musculus
1,1700056E22Rik,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,DAA,Aging,NCBI_ID,Quick_GO,RIKEN cDNA 1700056E22 gene,aging,Mus musculus
2,1810044D09Rik,Gene_PositivelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,DAA,Aging,NCBI_ID,Quick_GO,RIKEN cDNA 1810044D09 gene,aging,Mus musculus

In [13]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           297                   0             297
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'DAA'} kg_source
DAA    297
Name: count, dtype: int64

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    297
Name: count, dtype: int64

In [16]:
# ! mkdir Mouse_gene_POS_ASS_biologicalprocess

In [17]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 297 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_POS_ASS_biologicalprocess/Mouse_gene_POS_ASS_biologicalprocess.csv

In [18]:
# OUT_PATH

# DAA NEGATIVE Association

In [19]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_gene_NEG_ASS_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_NEG_ASS_biologicalprocess/Mouse_gene_NEG_ASS_biologicalprocess.csv'

In [20]:
DAA = pd.read_csv(PROC_DIR + 'digitalagingatlas/Mouse/DAA_Mouse_Gene_Neg_BiologicalProcess.csv')
DAA.columns = DAA.columns.str.lower()
DAA = DAA[~DAA['head_detail_name'].isna()]

DAA['kg_type'] = 'Aging'

print(f"DAA: {len(DAA):,} rows")
DAA['head_id_is'] = 'NCBI_ID'
DAA['tail_id_is'] = 'Quick_GO'
DAA['species'] = 'Mus musculus'
DAA['tail_detail_name'] = 'aging'
DAA['kg_source'] = 'DAA'
DAA['relation'] = 'Gene_NegativelyAssociatedWith_BiologicalProcess'
DAA

DAA: 217 rows

,head,relation,tail,head_type,tail_type,head_detail_name,relation_source,species,data_type,kg_type,head_id_is,tail_id_is,tail_detail_name,kg_source
0,Abhd14a,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,abhydrolase domain containing 14A,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
1,Actc1,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"actin, alpha, cardiac muscle 1",DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
2,Acsm2,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,acyl-CoA synthetase medium-chain family member 2,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
3,Acss1,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,acyl-CoA synthetase short-chain family member 1,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
4,Acot7,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,acyl-CoA thioesterase 7,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,Zfhx3,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc finger homeobox 3,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
213,Zmym1,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"zinc finger, MYM domain containing 1",DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
214,Zfp251,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc finger protein 251,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
215,Zfp84,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,zinc finger protein 84,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
216,Zzz3,Gene_NegativelyAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"zinc finger, ZZ domain containing 3",DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA

In [21]:
for col in ['relation', 'head_type', 'tail_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(DAA[col])}")

relation            : {'Gene_NegativelyAssociatedWith_BiologicalProcess'}
head_type           : {'Gene'}
tail_type           : {'BiologicalProcess'}
kg_source           : {'DAA'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [22]:
! mkdir Mouse_gene_NEG_ASS_biologicalprocess

mkdir: cannot create directory ‘Mouse_gene_NEG_ASS_biologicalprocess’: File exists

In [23]:
DAA.to_csv(OUT_PATH, index=False)
print(f"Saved {len(DAA):,} rows → {OUT_PATH}")

Saved 217 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_NEG_ASS_biologicalprocess/Mouse_gene_NEG_ASS_biologicalprocess.csv

# DAA NOT Association

In [24]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_gene_NOT_ASS_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_NOT_ASS_biologicalprocess/Mouse_gene_NOT_ASS_biologicalprocess.csv'

In [25]:
DAA = pd.read_csv(PROC_DIR + 'digitalagingatlas/Mouse/DAA_Mouse_Gene_Not_BiologicalProcess.csv')
DAA.columns = DAA.columns.str.lower()
DAA = DAA[~DAA['head_detail_name'].isna()]

DAA['kg_type'] = 'Aging'

print(f"DAA: {len(DAA):,} rows")
DAA['head_id_is'] = 'NCBI_ID'
DAA['tail_id_is'] = 'Quick_GO'
DAA['species'] = 'Mus musculus'
DAA['tail_detail_name'] = 'aging'
DAA['kg_source'] = 'DAA'
DAA['relation'] = 'Gene_NotAssociatedWith_BiologicalProcess'
DAA

DAA: 24 rows

,head,relation,tail,head_type,tail_type,head_detail_name,relation_source,species,data_type,kg_type,head_id_is,tail_id_is,tail_detail_name,kg_source
0,Ap2m1,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"adaptor-related protein complex 2, mu 1 subunit",DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
1,Brms1l,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,breast cancer metastasis-suppressor 1-like,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
2,Commd4,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,COMM domain containing 4,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
3,Cox6a1,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,cytochrome c oxidase subunit 6A1,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
4,Dmbt1,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,deleted in malignant brain tumors 1,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
5,Dip2b,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,disco interacting protein 2 homolog B,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
6,AI596487,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,expressed sequence AI596487,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
7,Foxl1,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,forkhead box L1,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
8,Fmc1,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,formation of mitochondrial complex V assembly ...,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
9,Gtf2i,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,general transcription factor II I,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
10,Gad1,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,glutamate decarboxylase 1,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
11,Grhpr,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,glyoxylate reductase/hydroxypyruvate reductase,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
12,Hsp90aa1,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"heat shock protein 90, alpha (cytosolic), clas...",DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
13,Mcfd2,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,multiple coagulation factor deficiency 2,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
14,Myoz1,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,myozenin 1,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
15,Ndufb4,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,NADH:ubiquinone oxidoreductase subunit B4,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
16,Ndufb5,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,NADH:ubiquinone oxidoreductase subunit B5,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
17,Ank,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,progressive ankylosis,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
18,Prpf6,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,pre-mRNA splicing factor 6,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
19,Rad23b,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,"RAD23 homolog B, nucleotide excision repair pr...",DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
20,2310033P09Rik,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,RIKEN cDNA 2310033P09 gene,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
21,Ahcyl1,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,S-adenosylhomocysteine hydrolase-like 1,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
22,Sec61a1,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,SEC61 translocon subunit alpha 1,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA
23,Slc25a11,Gene_NotAssociatedWith_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,solute carrier family 25 (mitochondrial carrie...,DigitalAgingAtlas,Mus musculus,Associative,Aging,NCBI_ID,Quick_GO,aging,DAA

In [26]:
! mkdir Mouse_gene_NOT_ASS_biologicalprocess

mkdir: cannot create directory ‘Mouse_gene_NOT_ASS_biologicalprocess’: File exists

In [27]:
DAA.to_csv(OUT_PATH, index=False)
print(f"Saved {len(DAA):,} rows → {OUT_PATH}")

Saved 24 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_gene_NOT_ASS_biologicalprocess/Mouse_gene_NOT_ASS_biologicalprocess.csv