In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_chemical_inhibits_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_chemical_inhibits_biologicalprocess/Mouse_chemical_inhibits_biologicalprocess.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

# AgeXtend

In [4]:
AgeXtend = pd.read_csv(PROC_DIR + 'agextend_processed/AgeXtend_Mouse_ChemicalEntity_Inhibits_BiologicalProcess.csv')
AgeXtend.columns = AgeXtend.columns.str.lower()
AgeXtend = AgeXtend[~AgeXtend['head_detail_name'].isna()]

AgeXtend['kg_type'] = 'Aging'

print(f"AgeXtend: {len(AgeXtend):,} rows")
AgeXtend['head_id_is'] = 'Pubchem'
AgeXtend['tail_id_is'] = 'Quick_GO'
AgeXtend['species'] = 'Mus musculus'
AgeXtend['kg_source'] = 'AgeXtend'

AgeXtend

AgeXtend: 7 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,tail_detail_name,relation_source,species,data_source,anti_aging_status,anti_aging_prob,kg_type,head_id_is,tail_id_is,kg_source
0,5319022,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(3Z)-3-butylidene-4,5-dihydro-2-benzofuran-1-one",CCC/C=C\1/C2=C(C=CCC2)C(=O)O1,aging,AgeXtend,Mus musculus,https://doi.org/10.1016/j.phymed.2023.155216,1,0.914950,Aging,Pubchem,Quick_GO,AgeXtend
1,5280443,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"5,7-dihydroxy-2-(4-hydroxyphenyl)chromen-4-one",C1=CC(=CC=C1C2=CC(=O)C3=C(C=C(C=C3O2)O)O)O,aging,AgeXtend,Mus musculus,https://doi.org/10.1016/j.mad.2023.111889,1,0.920326,Aging,Pubchem,Quick_GO,AgeXtend
2,6072,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"1-[2,4-dihydroxy-6-[(2S,3R,4S,5S,6R)-3,4,5-tri...",C1=CC(=CC=C1CCC(=O)C2=C(C=C(C=C2O[C@H]3[C@@H](...,aging,AgeXtend,Mus musculus,https://doi.org/10.1016/j.exger.2022.111769,1,0.904648,Aging,Pubchem,Quick_GO,AgeXtend
3,73554535,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R,6R)-6-[(7S,10S,13R,14R,15S,17R)-7,15-dihyd...",C[C@H](CC(=O)C[C@@H](C)C(=O)O)[C@H]1C[C@@H]([C...,aging,AgeXtend,Mus musculus,https://doi.org/10.1111/acel.13686,1,0.824924,Aging,Pubchem,Quick_GO,AgeXtend
4,4034,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,1-[(4-chlorophenyl)-phenylmethyl]-4-[(3-methyl...,CC1=CC(=CC=C1)CN2CCN(CC2)C(C3=CC=CC=C3)C4=CC=C...,aging,AgeXtend,Mus musculus,https://doi.org/10.1007/s11357-023-01011-0,1,0.928011,Aging,Pubchem,Quick_GO,AgeXtend
5,5991,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(8R,9S,13S,14S,17R)-17-ethynyl-13-methyl-7,8,9...",C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC4...,aging,AgeXtend,Mus musculus,https://doi.org/10.1111/acel.13328,1,0.752881,Aging,Pubchem,Quick_GO,AgeXtend
6,5281233,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"bis[(2S,3R,4S,5S,6R)-3,4,5-trihydroxy-6-[[(2R,...",C/C(=C\C=C\C=C(\C=C\C=C(\C(=O)O[C@@H]1O[C@@H](...,aging,AgeXtend,Mus musculus,https://doi.org/10.22038/ajp.2017.21198.1801,1,0.913811,Aging,Pubchem,Quick_GO,AgeXtend

# AgingAtlas

In [5]:
AgingAtlas = pd.read_csv(PROC_DIR + 'agingatlas/Mouse/Mouse_AgingAtlas_Chemical_Inhibit_BiologicalProcess_Geroprotectors.csv')
AgingAtlas.columns = AgingAtlas.columns.str.lower()
AgingAtlas = AgingAtlas[~AgingAtlas['head_detail_name'].isna()]

AgingAtlas['kg_type'] = 'Aging'
AgingAtlas['tail_type'] = 'BiologicalProcess'
print(f"AgingAtlas: {len(AgingAtlas):,} rows")
AgingAtlas['head_id_is'] = 'Pubchem'
AgingAtlas['tail_id_is'] = 'Quick_GO'
AgingAtlas['species'] = 'Mus musculus'
AgingAtlas['kg_source'] = 'AgingAtlas'
AgingAtlas

AgingAtlas: 33 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,pmid,rnaseq,data_type,tail_detail_name,kg_type,head_id_is,tail_id_is,kg_source
0,1567,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,2-sulfanylethanol,C(CS)O,Aging_Atlas_gerprotector,Mus musculus,2-mercaptoethanol,6334792,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
1,139254081,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"[(4E,6E,8R,9R,10E,12S,13R,14S,16R)-19-[2-(dime...",C[C@H]1C[C@@H]([C@@H]([C@H](/C=C(/[C@H]([C@@H]...,Aging_Atlas_gerprotector,Mus musculus,17-DMAG,28871086,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
2,68570,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(8R,9S,13S,14S,17R)-13-methyl-6,7,8,9,11,12,14...",C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@H]2O)CCC4=C3C...,Aging_Atlas_gerprotector,Mus musculus,17a-oestradiol,27312236,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
3,163284948,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2S,5S)-5-[(2R,5S)-5-[(2R,5S,6R)-3,4-dihydroxy...",C[C@@H]1[C@H](C(C([C@H](O1)O[C@@H]2C(O[C@@H](C...,Aging_Atlas_gerprotector,Mus musculus,Acarbose,24245565,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
4,1983,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,N-(4-hydroxyphenyl)acetamide,CC(=O)NC1=CC=C(C=C1)O,Aging_Atlas_gerprotector,Mus musculus,Acetaminophen,\t4788962,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
5,2244,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,2-acetyloxybenzoic acid,CC(=O)OC1=CC=CC=C1C(=O)O,Aging_Atlas_gerprotector,Mus musculus,Aspirin,4788962,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
6,586,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,2-[carbamimidoyl(methyl)amino]acetic acid,CN(CC(=O)O)C(=N)N,Aging_Atlas_gerprotector,Mus musculus,Creatine,17416441,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
7,439213,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(3R,4R,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)N)O)O)O,Aging_Atlas_gerprotector,Mus musculus,D-glucosamine,24714520,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
8,219042,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,(4S)-4-[[(2S)-2-aminopropanoyl]amino]-5-[[(2S)...,C[C@@H](C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CC(...,Aging_Atlas_gerprotector,Mus musculus,Epithalamin,9701766,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
9,3293,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"6-ethoxy-2,2,4-trimethyl-1H-quinoline",CCOC1=CC2=C(C=C1)NC(C=C2C)(C)C,Aging_Atlas_gerprotector,Mus musculus,Ethoxyquin,15653505,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
10,439213,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(3R,4R,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)N)O)O)O,Aging_Atlas_gerprotector,Mus musculus,Glucosamine,24714520,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
11,132999,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"3-[3-[[(7S)-3,4-dimethoxy-7-bicyclo[4.2.0]octa...",CN(CCCN1CCC2=CC(=C(C=C2CC1=O)OC)OC)C[C@H]3CC4=...,Aging_Atlas_gerprotector,Mus musculus,Ivabradine,25589054,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
12,265776,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,N-methylpyrimidin-2-amine,CNC1=NC=CC=N1,Aging_Atlas_gerprotector,Mus musculus,JH4,27617860,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
13,896,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,N-[2-(5-methoxy-1H-indol-3-yl)ethyl]acetamide,CC(=O)NCCC1=CNC2=C1C=C(C=C2)OC,Aging_Atlas_gerprotector,Mus musculus,Melatonin,11445596,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
14,4091,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"3-(diaminomethylidene)-1,1-dimethylguanidine",CN(C)C(=N)N=C(N)N,Aging_Atlas_gerprotector,Mus musculus,Metformin,23900241,view,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
15,84815,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,(2R)-2-amino-4-methylsulfanylbutanoic acid,CSCC[C@H](C(=O)O)N,Aging_Atlas_gerprotector,Mus musculus,Methionine,30157432,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
16,4171,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,1-[4-(2-methoxyethyl)phenoxy]-3-(propan-2-ylam...,CC(C)NCC(COC1=CC=C(C=C1)CCOC)O,Aging_Atlas_gerprotector,Mus musculus,Metoprolol,23314750,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
17,462382,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,benzyl N-[(2S)-4-methyl-1-[[(2S)-4-methyl-1-[[...,CC(C)C[C@@H](C=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,Aging_Atlas_gerprotector,Mus musculus,MG132,21084425,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
18,12035,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,(2R)-2-acetamido-3-sulfanylpropanoic acid,CC(=O)N[C@@H](CS)C(=O)O,Aging_Atlas_gerprotector,Mus musculus,N-acetyl-L-cysteine,20819793,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
19,134378124,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"1-[(2R)-6-fluoro-3,4-dihydro-2H-chromen-2-yl]-...",C1CC2=C(C=CC(=C2)F)O[C@@H]1[C@@H](CNCC([C@H]3C...,Aging_Atlas_gerprotector,Mus musculus,Nebivolol,23314750,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
20,14181,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"[(2R,3S,4R,5R)-5-(3-carbamoylpyridin-1-ium-1-y...",C1=CC(=C[N+](=C1)[C@H]2[C@@H]([C@@H]([C@H](O2)...,Aging_Atlas_gerprotector,Mus musculus,Nicotinamide mononucleotide,28068222,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
21,4534,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"4-[4-(3,4-dihydroxyphenyl)-2,3-dimethylbutyl]b...",CC(CC1=CC(=C(C=C1)O)O)C(C)CC2=CC(=C(C=C2)O)O,Aging_Atlas_gerprotector,Mus musculus,Nordihydroguaiaretic acid,18631321,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
22,8249,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,1-(diaminomethylidene)-2-(2-phenylethyl)guanidine,C1=CC=C(C=C1)CCN=C(N)N=C(N)N,Aging_Atlas_gerprotector,Mus musculus,Phenformin,14618027,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
23,5280343,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"2-(3,4-dihydroxyphenyl)-3,5,7-trihydroxychrome...",C1=CC(=C(C=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O)O)O,Aging_Atlas_gerprotector,Mus musculus,Quercetin,31325157,view,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
24,5284616,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(1R,9S,12S,15R,16E,18R,19R,21R,23S,24E,26E,28E...",C[C@@H]1CC[C@H]2C[C@@H](/C(=C/C=C/C=C/[C@H](C[...,Aging_Atlas_gerprotector,Mus musculus,Rapamycin,27091134,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
25,5280805,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"2-(3,4-dihydroxyphenyl)-5,7-dihydroxy-3-[(2S,3...",C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC[C@@H]2[...,Aging_Atlas_gerprotector,Mus musculus,Rutin,27865831,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
26,24934,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,disodium;selenite,[O-][Se](=O)[O-].[Na+].[Na+],Aging_Atlas_gerprotector,Mus musculus,Sodium selenite,7214335,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
27,1103,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"N,N'-bis(3-aminopropyl)butane-1,4-diamine",C(CCNCCCN)CNCCCN,Aging_Atlas_gerprotector,Mus musculus,Spermine,21858192,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
28,25232708,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"N-[2-[3-(piperazin-1-ylmethyl)imidazo[2,1-b][1...",C1CN(CCN1)CC2=CSC3=NC(=CN23)C4=CC=CC=C4NC(=O)C...,Aging_Atlas_gerprotector,Mus musculus,SRT1720,24582957,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
29,5311,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,N'-hydroxy-N-phenyloctanediamide,C1=CC=C(C=C1)NC(=O)CCCCCCC(=O)NO,Aging_Atlas_gerprotector,Mus musculus,Suberoylanilide hydroxamic acid,26441515,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
30,124072,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"1,7-bis(4-hydroxy-3-methoxyphenyl)heptane-3,5-...",COC1=C(C=CC(=C1)CCC(=O)CC(=O)CCC2=CC(=C(C=C2)O...,Aging_Atlas_gerprotector,Mus musculus,Tetrahydrocurcumin,17516143,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
31,54670067,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2-[(1S)-1,2-dihydroxyethyl]-3,4-dihydroxy...",C([C@@H]([C@@H]1C(=C(C(=O)O1)O)O)O)O,Aging_Atlas_gerprotector,Mus musculus,Vitamin C,19741171,view,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
32,14985,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",CC1=C(C2=C(CC[C@@](O2)(C)CCC[C@H](C)CCC[C@H](C...,Aging_Atlas_gerprotector,Mus musculus,Vitamin E,18257658,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
    AgeXtend, AgingAtlas
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 40

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,5319022,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"(3Z)-3-butylidene-4,5-dihydro-2-benzofuran-1-one",aging,Mus musculus
1,5280443,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"5,7-dihydroxy-2-(4-hydroxyphenyl)chromen-4-one",aging,Mus musculus
2,6072,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"1-[2,4-dihydroxy-6-[(2S,3R,4S,5S,6R)-3,4,5-tri...",aging,Mus musculus
3,73554535,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"(2R,6R)-6-[(7S,10S,13R,14R,15S,17R)-7,15-dihyd...",aging,Mus musculus
4,4034,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,1-[(4-chlorophenyl)-phenylmethyl]-4-[(3-methyl...,aging,Mus musculus
5,5991,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"(8R,9S,13S,14S,17R)-17-ethynyl-13-methyl-7,8,9...",aging,Mus musculus
6,5281233,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"bis[(2S,3R,4S,5S,6R)-3,4,5-trihydroxy-6-[[(2R,...",aging,Mus musculus
7,1567,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,2-sulfanylethanol,aging,Mus musculus
8,139254081,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"[(4E,6E,8R,9R,10E,12S,13R,14S,16R)-19-[2-(dime...",aging,Mus musculus
9,68570,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(8R,9S,13S,14S,17R)-13-methyl-6,7,8,9,11,12,14...",aging,Mus musculus
10,163284948,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(2S,5S)-5-[(2R,5S)-5-[(2R,5S,6R)-3,4-dihydroxy...",aging,Mus musculus
11,1983,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,N-(4-hydroxyphenyl)acetamide,aging,Mus musculus
12,2244,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,2-acetyloxybenzoic acid,aging,Mus musculus
13,586,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,2-[carbamimidoyl(methyl)amino]acetic acid,aging,Mus musculus
14,439213,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(3R,4R,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",aging,Mus musculus
15,219042,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,(4S)-4-[[(2S)-2-aminopropanoyl]amino]-5-[[(2S)...,aging,Mus musculus
16,3293,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"6-ethoxy-2,2,4-trimethyl-1H-quinoline",aging,Mus musculus
17,439213,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(3R,4R,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",aging,Mus musculus
18,132999,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"3-[3-[[(7S)-3,4-dimethoxy-7-bicyclo[4.2.0]octa...",aging,Mus musculus
19,265776,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,N-methylpyrimidin-2-amine,aging,Mus musculus
20,896,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,N-[2-(5-methoxy-1H-indol-3-yl)ethyl]acetamide,aging,Mus musculus
21,4091,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"3-(diaminomethylidene)-1,1-dimethylguanidine",aging,Mus musculus
22,84815,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,(2R)-2-amino-4-methylsulfanylbutanoic acid,aging,Mus musculus
23,4171,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,1-[4-(2-methoxyethyl)phenoxy]-3-(propan-2-ylam...,aging,Mus musculus
24,462382,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,benzyl N-[(2S)-4-methyl-1-[[(2S)-4-methyl-1-[[...,aging,Mus musculus
25,12035,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,(2R)-2-acetamido-3-sulfanylpropanoic acid,aging,Mus musculus
26,134378124,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"1-[(2R)-6-fluoro-3,4-dihydro-2H-chromen-2-yl]-...",aging,Mus musculus
27,14181,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"[(2R,3S,4R,5R)-5-(3-carbamoylpyridin-1-ium-1-y...",aging,Mus musculus
28,4534,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"4-[4-(3,4-dihydroxyphenyl)-2,3-dimethylbutyl]b...",aging,Mus musculus
29,8249,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,1-(diaminomethylidene)-2-(2-phenylethyl)guanidine,aging,Mus musculus
30,5280343,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"2-(3,4-dihydroxyphenyl)-3,5,7-trihydroxychrome...",aging,Mus musculus
31,5284616,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(1R,9S,12S,15R,16E,18R,19R,21R,23S,24E,26E,28E...",aging,Mus musculus
32,5280805,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"2-(3,4-dihydroxyphenyl)-5,7-dihydroxy-3-[(2S,3...",aging,Mus musculus
33,24934,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,disodium;selenite,aging,Mus musculus
34,1103,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"N,N'-bis(3-aminopropyl)butane-1,4-diamine",aging,Mus musculus
35,25232708,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"N-[2-[3-(piperazin-1-ylmethyl)imidazo[2,1-b][1...",aging,Mus musculus
36,5311,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,N'-hydroxy-N-phenyloctanediamide,aging,Mus musculus
37,124072,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"1,7-bis(4-hydroxy-3-methoxyphenyl)heptane-3,5-...",aging,Mus musculus
38,54670067,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(2R)-2-[(1S)-1,2-dihydroxyethyl]-3,4-dihydroxy...",aging,Mus musculus
39,14985,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",aging,Mus musculus

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'ChemicalEntity_Inhibits_BiologicalProcess'}
head_type           : {'ChemicalEntity'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'AgeXtend', 'AgingAtlas'}
head_id_is          : {'Pubchem'}
tail_id_is          : {'Quick_GO'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 40 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            40                   0              40
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 40  |  After dedup: 39

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,586,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,2-[carbamimidoyl(methyl)amino]acetic acid,aging,Mus musculus
1,896,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,N-[2-(5-methoxy-1H-indol-3-yl)ethyl]acetamide,aging,Mus musculus
2,1103,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"N,N'-bis(3-aminopropyl)butane-1,4-diamine",aging,Mus musculus

In [11]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            39                   0              39
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'AgeXtend', 'AgingAtlas'} kg_source
AgingAtlas    32
AgeXtend       7
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    39
Name: count, dtype: int64

In [14]:
# ! mkdir Mouse_chemical_inhibits_biologicalprocess

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 39 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_chemical_inhibits_biologicalprocess/Mouse_chemical_inhibits_biologicalprocess.csv

In [16]:
# OUT_PATH