In [35]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [36]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse

In [37]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Mouse_phenotype_cellularcomponent
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_phenotype_cellularcomponent/Mouse_phenotype_cellularcomponent.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Mouse_phenotype_cellularcomponent’: File exists

In [38]:
#

# monarch

In [39]:
monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Mouse/Mouse_Phenotype_CellularComponent.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch.rename(columns={
    'headtype': 'head_type',
    'tailtype': 'tail_type',
})
# monarch = monarch[~monarch['head_detail_name'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'
monarch['species'] = 'M.musculus'
monarch['head_id_is'] = 'MP_ID'

print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 354 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,species,kg_type,kg_source
0,MP:0000731,Phenotype_CellularComponent,GO:0005581,Phenotype,related_to,CellularComponent,infores:upheno,increased collagen deposition in the muscles,collagen trimer,Mus musculus,NaN,MP_ID,Quick_GO,M.musculus,Generalised,Monarch_KG
1,MP:0001053,Phenotype_CellularComponent,GO:0031594,Phenotype,related_to,CellularComponent,infores:upheno,abnormal neuromuscular synapse morphology,neuromuscular junction,Mus musculus,NaN,MP_ID,Quick_GO,M.musculus,Generalised,Monarch_KG
2,MP:0001805,Phenotype_CellularComponent,GO:0071736,Phenotype,related_to,CellularComponent,infores:upheno,decreased IgG level,"IgG immunoglobulin complex, circulating",Mus musculus,NaN,MP_ID,Quick_GO,M.musculus,Generalised,Monarch_KG
3,MP:0001806,Phenotype_CellularComponent,GO:0071754,Phenotype,related_to,CellularComponent,infores:upheno,decreased IgM level,"IgM immunoglobulin complex, circulating",Mus musculus,NaN,MP_ID,Quick_GO,M.musculus,Generalised,Monarch_KG
4,MP:0001807,Phenotype_CellularComponent,GO:0071746,Phenotype,related_to,CellularComponent,infores:upheno,decreased IgA level,"IgA immunoglobulin complex, circulating",Mus musculus,NaN,MP_ID,Quick_GO,M.musculus,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,MP:0031388,Phenotype_CellularComponent,GO:0002177,Phenotype,related_to,CellularComponent,infores:upheno,absent manchette,manchette,Mus musculus,NaN,MP_ID,Quick_GO,M.musculus,Generalised,Monarch_KG
350,MP:0031408,Phenotype_CellularComponent,GO:0061827,Phenotype,related_to,CellularComponent,infores:upheno,multi-headed sperm,sperm head,Mus musculus,NaN,MP_ID,Quick_GO,M.musculus,Generalised,Monarch_KG
351,MP:0031409,Phenotype_CellularComponent,GO:0061827,Phenotype,related_to,CellularComponent,infores:upheno,double-headed sperm,sperm head,Mus musculus,NaN,MP_ID,Quick_GO,M.musculus,Generalised,Monarch_KG
352,MP:0031410,Phenotype_CellularComponent,GO:0036126,Phenotype,related_to,CellularComponent,infores:upheno,biflagellated sperm,sperm flagellum,Mus musculus,NaN,MP_ID,Quick_GO,M.musculus,Generalised,Monarch_KG
353,MP:0031620,Phenotype_CellularComponent,GO:0033391,Phenotype,related_to,CellularComponent,infores:upheno,abnormal chromatoid body morphology,chromatoid body,Mus musculus,NaN,MP_ID,Quick_GO,M.musculus,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [40]:
# List all source DataFrames to include
source_dfs = [
    monarch,
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 354

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,MP:0000731,Phenotype_CellularComponent,GO:0005581,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,MP_ID,Quick_GO,increased collagen deposition in the muscles,collagen trimer,M.musculus
1,MP:0001053,Phenotype_CellularComponent,GO:0031594,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,MP_ID,Quick_GO,abnormal neuromuscular synapse morphology,neuromuscular junction,M.musculus
2,MP:0001805,Phenotype_CellularComponent,GO:0071736,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,MP_ID,Quick_GO,decreased IgG level,"IgG immunoglobulin complex, circulating",M.musculus
3,MP:0001806,Phenotype_CellularComponent,GO:0071754,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,MP_ID,Quick_GO,decreased IgM level,"IgM immunoglobulin complex, circulating",M.musculus
4,MP:0001807,Phenotype_CellularComponent,GO:0071746,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,MP_ID,Quick_GO,decreased IgA level,"IgA immunoglobulin complex, circulating",M.musculus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,MP:0031388,Phenotype_CellularComponent,GO:0002177,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,MP_ID,Quick_GO,absent manchette,manchette,M.musculus
350,MP:0031408,Phenotype_CellularComponent,GO:0061827,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,MP_ID,Quick_GO,multi-headed sperm,sperm head,M.musculus
351,MP:0031409,Phenotype_CellularComponent,GO:0061827,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,MP_ID,Quick_GO,double-headed sperm,sperm head,M.musculus
352,MP:0031410,Phenotype_CellularComponent,GO:0036126,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,MP_ID,Quick_GO,biflagellated sperm,sperm flagellum,M.musculus
353,MP:0031620,Phenotype_CellularComponent,GO:0033391,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,MP_ID,Quick_GO,abnormal chromatoid body morphology,chromatoid body,M.musculus

# Sanity Check — Distinct Values

In [41]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Phenotype_CellularComponent'}
head_type           : {'Phenotype'}
tail_type           : {'CellularComponent'}
relation_type       : {'related_to'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'MP_ID'}
tail_id_is          : {'Quick_GO'}

In [42]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 354 remaining

# NaN Audit (pre-dedup)

In [43]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [44]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 354  |  After dedup: 354

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,MP:0000731,Phenotype_CellularComponent,GO:0005581,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,MP_ID,Quick_GO,increased collagen deposition in the muscles,collagen trimer,M.musculus
1,MP:0001053,Phenotype_CellularComponent,GO:0031594,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,MP_ID,Quick_GO,abnormal neuromuscular synapse morphology,neuromuscular junction,M.musculus
2,MP:0001805,Phenotype_CellularComponent,GO:0071736,Phenotype,related_to,CellularComponent,Monarch_KG,Generalised,MP_ID,Quick_GO,decreased IgG level,"IgG immunoglobulin complex, circulating",M.musculus

In [45]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type             0                   0               0
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [46]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    354
Name: count, dtype: int64

In [47]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    354
Name: count, dtype: int64

In [48]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 354 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Mouse/Mouse_phenotype_cellularcomponent/Mouse_phenotype_cellularcomponent.csv

In [49]:
# OUT_PATH