In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'


# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

# POSITIVE ASSOCIATION

In [4]:
# ── Output path ───────────────────────────────────────────────────────────────
! mkdir Drosophila_chemical_positiveassociated_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_chemical_positiveassociated_biologicalprocess/Drosophila_chemical_positiveassociated_biologicalprocess.csv'

### Drugage

In [5]:
Drugage = pd.read_csv(PROC_DIR + 'drugage/drugage_final/Droso_CE_Pos_BioPro_merged.csv')
Drugage.columns = Drugage.columns.str.lower()
Drugage = Drugage[~Drugage['head_detail_name'].isna()]

Drugage['kg_type'] = 'Aging'

print(f"Drugage: {len(Drugage):,} rows")
Drugage['head_id_is'] = 'Pubchem'
Drugage['tail_id_is'] = 'Quick_GO'
Drugage['relation'] = 'ChemicalEntity_PositivelyAssociatedWith_BiologicalProcess'
Drugage['kg_source'] = 'Drugage'
Drugage['tail_detail_name'] = 'aging'
Drugage

Drugage: 118 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,...,age_at_initiation,treatment_duration,avg_lifespan_change_percent,dosage,pubmed_id,kg_type,head_id_is,tail_id_is,kg_source,tail_detail_name
0,128852,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-ethyl-6-methylpyridin-3-ol;hydrochloride,CCC1=C(C=CC(=N1)C)O.Cl,DrugAge,Drosophila melanogaster,2-Ethyl-6-methylpyridin-3-ol hydrochloride,...,NaN,NaN,22.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
1,6346,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,diiodomethane,C(I)I,DrugAge,Drosophila melanogaster,Diiodomethane,...,NaN,NaN,14.50,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
2,19,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"2,3-dihydroxybenzoic acid",C1=CC(=C(C(=C1)O)O)C(=O)O,DrugAge,Drosophila melanogaster,"2,3-Dihydroxybenzoic acid",...,NaN,NaN,9.33,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
3,5147,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-hydroxybenzamide,C1=CC=C(C(=C1)C(=O)N)O,DrugAge,Drosophila melanogaster,Salicylamide,...,NaN,NaN,44.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
4,4039,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-(dimethylamino)ethyl 2-(4-chlorophenoxy)acetate,CN(C)CCOC(=O)COC1=CC=C(C=C1)Cl,DrugAge,Drosophila melanogaster,Meclofenoxate,...,NaN,NaN,28.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,4184,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"5-methyl-2,5-diazatetracyclo[13.4.0.02,7.08,13...",CN1CCN2C(C1)C3=CC=CC=C3CC4=CC=CC=C42,DrugAge,Drosophila melanogaster,Mianserin,...,NaN,NaN,6.00,20 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
115,6915732,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(3R,4S,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",C([C@@H]1[C@H]([C@H]([C@H](C(O1)O)N)O)O)O,DrugAge,Drosophila melanogaster,Alln,...,NaN,NaN,11.55,200 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
116,5452,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,10-[2-(1-methylpiperidin-2-yl)ethyl]-2-methyls...,CN1CCCCC1CCN2C3=CC=CC=C3SC4=C2C=C(C=C4)SC,DrugAge,Drosophila melanogaster,Thioridazine,...,NaN,NaN,16.16,200 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
117,54704426,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(4S,4aS,5aS,6S,12aR)-4-(dimethylamino)-1,6,10,...",C[C@@]1([C@H]2C[C@H]3[C@@H](C(=O)C(=C([C@]3(C(...,DrugAge,Drosophila melanogaster,Tetracycline HCL,...,NaN,NaN,5.23,20 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
118,64737,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"1-butyl-N-(2,6-dimethylphenyl)piperidine-2-car...",CCCCN1CCCCC1C(=O)NC2=C(C=CC=C2C)C.Cl,DrugAge,Drosophila melanogaster,Bupivacaine HCl,...,NaN,NaN,11.95,20 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
    Drugage
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 118

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,128852,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-ethyl-6-methylpyridin-3-ol;hydrochloride,aging,Drosophila melanogaster
1,6346,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,diiodomethane,aging,Drosophila melanogaster
2,19,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"2,3-dihydroxybenzoic acid",aging,Drosophila melanogaster
3,5147,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-hydroxybenzamide,aging,Drosophila melanogaster
4,4039,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-(dimethylamino)ethyl 2-(4-chlorophenoxy)acetate,aging,Drosophila melanogaster
...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,4184,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"5-methyl-2,5-diazatetracyclo[13.4.0.02,7.08,13...",aging,Drosophila melanogaster
114,6915732,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(3R,4S,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",aging,Drosophila melanogaster
115,5452,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,10-[2-(1-methylpiperidin-2-yl)ethyl]-2-methyls...,aging,Drosophila melanogaster
116,54704426,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(4S,4aS,5aS,6S,12aR)-4-(dimethylamino)-1,6,10,...",aging,Drosophila melanogaster
117,64737,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"1-butyl-N-(2,6-dimethylphenyl)piperidine-2-car...",aging,Drosophila melanogaster

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'ChemicalEntity_PositivelyAssociatedWith_BiologicalProcess'}
head_type           : {'ChemicalEntity'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'Drugage'}
head_id_is          : {'Pubchem'}
tail_id_is          : {'Quick_GO'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 118 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           118                   0             118
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 118  |  After dedup: 118

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,19,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"2,3-dihydroxybenzoic acid",aging,Drosophila melanogaster
1,51,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-oxopentanedioic acid,aging,Drosophila melanogaster
2,199,ChemicalEntity_PositivelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-(4-aminobutyl)guanidine,aging,Drosophila melanogaster

In [11]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           118                   0             118
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Drugage'} kg_source
Drugage    118
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    118
Name: count, dtype: int64

In [14]:
! mkdir Drosophila_chemical_positiveassociated_biologicalprocess

mkdir: cannot create directory ‘Drosophila_chemical_positiveassociated_biologicalprocess’: File exists

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 118 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_chemical_positiveassociated_biologicalprocess/Drosophila_chemical_positiveassociated_biologicalprocess.csv

In [16]:
# OUT_PATH

# NEGATIVE ASSOCIATION

In [17]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Drosophila_chemical_negativeassociated_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_chemical_negativeassociated_biologicalprocess/Drosophila_chemical_negativeassociated_biologicalprocess.csv'

In [18]:
Drugage = pd.read_csv(PROC_DIR + 'drugage/drugage_final/Droso_CE_Neg_BioPro_merged.csv')
Drugage.columns = Drugage.columns.str.lower()
Drugage = Drugage[~Drugage['head_detail_name'].isna()]

Drugage['kg_type'] = 'Aging'

print(f"Drugage: {len(Drugage):,} rows")
Drugage['head_id_is'] = 'Pubchem'
Drugage['tail_id_is'] = 'Quick_GO'
Drugage['relation'] = 'ChemicalEntity_NegativelyAssociatedWith_BiologicalProcess'
Drugage['kg_source'] = 'Drugage'
Drugage['tail_detail_name'] = 'aging'
Drugage

Drugage: 52 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,...,age_at_initiation,treatment_duration,avg_lifespan_change_percent,dosage,pubmed_id,kg_type,head_id_is,tail_id_is,kg_source,tail_detail_name
0,83273,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"1,3-dimethyl-1-nitrosourea",CNC(=O)N(C)N=O,DrugAge,Drosophila melanogaster,Nitrosodimethylurea,...,NaN,NaN,-37.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
1,2244,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-acetyloxybenzoic acid,CC(=O)OC1=CC=CC=C1C(=O)O,DrugAge,Drosophila melanogaster,Aspirin,...,NaN,NaN,-16.06,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
2,24850,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,dialuminum;trisulfate,[O-]S(=O)(=O)[O-].[O-]S(=O)(=O)[O-].[O-]S(=O)(...,DrugAge,Drosophila melanogaster,Aluminum sulfate,...,NaN,NaN,-21.84,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
3,26053,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,aluminum;trinitrate,[N+](=O)([O-])[O-].[N+](=O)([O-])[O-].[N+](=O)...,DrugAge,Drosophila melanogaster,Aluminium nitrate,...,NaN,NaN,-8.93,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
4,11192,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,zinc;diacetate,CC(=O)[O-].CC(=O)[O-].[Zn+2],DrugAge,Drosophila melanogaster,Zinc acetate,...,NaN,NaN,-6.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
5,5280531,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"[(2E,4E,6E,8E)-3,7-dimethyl-9-(2,6,6-trimethyl...",CCCCCCCCCCCCCCCC(=O)OC/C=C(\C)/C=C/C=C(\C)/C=C...,DrugAge,Drosophila melanogaster,Vitamin A palmitate,...,NaN,NaN,-60.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
6,493570,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"7,8-dimethyl-10-[(2S,3S,4R)-2,3,4,5-tetrahydro...",CC1=CC2=C(C=C1C)N(C3=NC(=O)NC(=O)C3=N2)C[C@@H]...,DrugAge,Drosophila melanogaster,Riboflavin,...,NaN,NaN,-9.50,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
7,6036,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(3R,4S,5R,6R)-6-(hydroxymethyl)oxane-2,3,4,5-t...",C([C@@H]1[C@@H]([C@@H]([C@H](C(O1)O)O)O)O)O,DrugAge,Drosophila melanogaster,Galactose,...,NaN,NaN,-15.90,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
8,5280961,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"5,7-dihydroxy-3-(4-hydroxyphenyl)chromen-4-one",C1=CC(=CC=C1C2=COC3=CC(=CC(=C3C2=O)O)O)O,DrugAge,Drosophila melanogaster,Genistein,...,NaN,NaN,-41.75,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
9,4306515,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,5-(4-chlorophenyl)-1-(4-methoxyphenyl)-3-(trif...,COC1=CC=C(C=C1)N2C(=CC(=N2)C(F)(F)F)C3=CC=C(C=...,DrugAge,Drosophila melanogaster,SC-560,...,NaN,NaN,-6.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
10,5280805,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"2-(3,4-dihydroxyphenyl)-5,7-dihydroxy-3-[(2S,3...",C[C@H]1[C@@H]([C@H]([C@H]([C@@H](O1)OC[C@@H]2[...,DrugAge,Drosophila melanogaster,Rutin,...,NaN,NaN,-16.66,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
11,170922317,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,N-[3-[(3-amino-3-oxoprop-1-en-2-yl)amino]-3-ox...,CC[C@H](C)[C@H]1C(=O)N[C@H](C(=O)NC(=C)C(=O)N[...,DrugAge,Drosophila melanogaster,Thiostrepton,...,NaN,NaN,-12.13,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
12,6915732,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(3R,4S,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",C([C@@H]1[C@H]([C@H]([C@H](C(O1)O)N)O)O)O,DrugAge,Drosophila melanogaster,Alln,...,NaN,NaN,-11.11,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
13,219099,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"5-[2-[4-(1,2-benzothiazol-3-yl)piperazin-1-yl]...",C1CN(CCN1CCC2=C(C=C3C(=C2)CC(=O)N3)Cl)C4=NSC5=...,DrugAge,Drosophila melanogaster,Ziprasidone HCl,...,NaN,NaN,-3.65,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
14,5281727,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"4-[(E)-2-(3,5-dimethoxyphenyl)ethenyl]phenol",COC1=CC(=CC(=C1)/C=C/C2=CC=C(C=C2)O)OC,DrugAge,Drosophila melanogaster,Pterostilbene,...,NaN,NaN,-1.83,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
15,969516,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(1E,6E)-1,7-bis(4-hydroxy-3-methoxyphenyl)hept...",COC1=C(C=CC(=C1)/C=C/C(=O)CC(=O)/C=C/C2=CC(=C(...,DrugAge,Drosophila melanogaster,Curcumin,...,NaN,NaN,-8.20,100 mM,23063786.0,Aging,Pubchem,Quick_GO,Drugage,aging
16,72276,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R,3R)-2-(3,4-dihydroxyphenyl)-3,4-dihydro-2H...",C1[C@H]([C@H](OC2=CC(=CC(=C21)O)O)C3=CC(=C(C=C...,DrugAge,Drosophila melanogaster,Epicatechin,...,NaN,NaN,-11.44,1 µM,28066251.0,Aging,Pubchem,Quick_GO,Drugage,aging
17,5280343,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"2-(3,4-dihydroxyphenyl)-3,5,7-trihydroxychrome...",C1=CC(=C(C=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O)O)O,DrugAge,Drosophila melanogaster,Quercetin,...,NaN,NaN,-4.55,0.5 µM,28066251.0,Aging,Pubchem,Quick_GO,Drugage,aging
18,2519,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"1,3,7-trimethylpurine-2,6-dione",CN1C=NC2=C1C(=O)N(C(=O)N2C)C,DrugAge,Drosophila melanogaster,Caffeine,...,NaN,NaN,-22.86,0.03%,29093334.0,Aging,Pubchem,Quick_GO,Drugage,aging
19,1123,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-aminoethanesulfonic acid,C(CS(=O)(=O)O)N,DrugAge,Drosophila melanogaster,Taurine,...,NaN,NaN,-14.29,1.50%,29093334.0,Aging,Pubchem,Quick_GO,Drugage,aging
20,445154,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",C1=CC(=CC=C1/C=C/C2=CC(=CC(=C2)O)O)O,DrugAge,Drosophila melanogaster,Resveratrol,...,NaN,NaN,-3.40,32 µM,17875315.0,Aging,Pubchem,Quick_GO,Drugage,aging
21,5222465,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,sodium;butanoate,CCCC(=O)[O-].[Na+],DrugAge,Drosophila melanogaster,Sodium butyrate,...,NaN,NaN,-10.90,100 mM,23044027.0,Aging,Pubchem,Quick_GO,Drugage,aging
22,4091,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"3-(diaminomethylidene)-1,1-dimethylguanidine",CN(C)C(=N)N=C(N)N,DrugAge,Drosophila melanogaster,Metformin,...,NaN,NaN,-66.00,100 mM,23077661.0,Aging,Pubchem,Quick_GO,Drugage,aging
23,6758,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(1S,6R,13S)-16,17-dimethoxy-6-prop-1-en-2-yl-2...",CC(=C)[C@H]1CC2=C(O1)C=CC3=C2O[C@@H]4COC5=CC(=...,DrugAge,Drosophila melanogaster,Rotenone,...,NaN,NaN,-21.14,100 µM,27076081.0,Aging,Pubchem,Quick_GO,Drugage,aging
24,15939,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,1-methyl-4-(1-methylpyridin-1-ium-4-yl)pyridin...,C[N+]1=CC=C(C=C1)C2=CC=[N+](C=C2)C,DrugAge,Drosophila melanogaster,Paraquat,...,NaN,NaN,-41.40,1 mM,27076081.0,Aging,Pubchem,Quick_GO,Drugage,aging
25,54675810,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2-[(1R)-1,2-dihydroxyethyl]-3,4-dihydroxy...",C([C@H]([C@@H]1C(=C(C(=O)O1)O)O)O)O,DrugAge,Drosophila melanogaster,Erythorbic acid,...,NaN,NaN,-71.57,58.3 mg/mL,16591414.0,Aging,Pubchem,Quick_GO,Drugage,aging
26,24947,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,dichlorocadmium,Cl[Cd]Cl,DrugAge,Drosophila melanogaster,Cadmium chloride,...,NaN,NaN,-17.40,0.1 mM,6409707.0,Aging,Pubchem,Quick_GO,Drugage,aging
27,76034190,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"copper;2-hydroxypropane-1,2,3-tricarboxylic acid",C(C(=O)O)C(CC(=O)O)(C(=O)O)O.[Cu].[Cu],DrugAge,Drosophila melanogaster,Cupric citrate,...,NaN,NaN,-16.30,1 mM,6423450.0,Aging,Pubchem,Quick_GO,Drugage,aging
28,24014,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,dichlorocopper,Cl[Cu]Cl,DrugAge,Drosophila melanogaster,Cupric chloride,...,NaN,NaN,-15.10,1 mM,6423450.0,Aging,Pubchem,Quick_GO,Drugage,aging
29,24462,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,copper;sulfate,[O-]S(=O)(=O)[O-].[Cu+2],DrugAge,Drosophila melanogaster,Cupric sulfate,...,NaN,NaN,-10.00,1 mM,6423450.0,Aging,Pubchem,Quick_GO,Drugage,aging
30,10692,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"copper;(2R,3S,4R,5R)-2,3,4,5,6-pentahydroxyhex...",C([C@H]([C@H]([C@@H]([C@H](C(=O)[O-])O)O)O)O)O...,DrugAge,Drosophila melanogaster,Cupric gluconate,...,NaN,NaN,-79.50,5 mM,6423450.0,Aging,Pubchem,Quick_GO,Drugage,aging
31,3032611,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,copper;2-aminoacetate,C(C(=O)[O-])N.C(C(=O)[O-])N.[Cu+2],DrugAge,Drosophila melanogaster,Cupric glycinate,...,NaN,NaN,-4.40,0.1 mM,6423450.0,Aging,Pubchem,Quick_GO,Drugage,aging
32,24012,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,trichloroalumane,[Al](Cl)(Cl)Cl,DrugAge,Drosophila melanogaster,Aluminium chloride,...,NaN,NaN,-5.82,0.1 mM,3932134.0,Aging,Pubchem,Quick_GO,Drugage,aging
33,679,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,methylsulfinylmethane,CS(=O)C,DrugAge,Drosophila melanogaster,Dimethyl sulfoxide,...,NaN,NaN,-6.36,0.5 %,3921599.0,Aging,Pubchem,Quick_GO,Drugage,aging
34,3715,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-[1-(4-chlorobenzoyl)-5-methoxy-2-methylindol...,CC1=C(C2=C(N1C(=O)C3=CC=C(C=C3)Cl)C=CC(=C2)OC)...,DrugAge,Drosophila melanogaster,Indomethacin,...,NaN,NaN,-41.78,10 mg/mL,3921599.0,Aging,Pubchem,Quick_GO,Drugage,aging
35,996,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,phenol,C1=CC=C(C=C1)O,DrugAge,Drosophila melanogaster,Phenol,...,NaN,NaN,-6.59,0.1 mM,3921599.0,Aging,Pubchem,Quick_GO,Drugage,aging
36,338,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-hydroxybenzoic acid,C1=CC=C(C(=C1)C(=O)O)O,DrugAge,Drosophila melanogaster,Salicylic acid,...,NaN,NaN,-13.20,0.015 M,3921599.0,Aging,Pubchem,Quick_GO,Drugage,aging
37,16760658,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,sodium;2-hydroxybenzoate,C1=CC=C(C(=C1)C(=O)[O-])O.[Na+],DrugAge,Drosophila melanogaster,Sodium salicylate,...,NaN,NaN,-11.94,0.015 M,3921599.0,Aging,Pubchem,Quick_GO,Drugage,aging
38,6240,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"3-(2-chlorophenothiazin-10-yl)-N,N-dimethylpro...",CN(C)CCCN1C2=CC=CC=C2SC3=C1C=C(C=C3)Cl.Cl,DrugAge,Drosophila melanogaster,Chlorpromazine chloride,...,NaN,NaN,-10.00,100 μg/mL,3921599.0,Aging,Pubchem,Quick_GO,Drugage,aging
39,24085,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,dichloromercury,Cl[Hg]Cl,DrugAge,Drosophila melanogaster,Mercuric chloride,...,NaN,NaN,-4.30,0.0001 M,8325352.0,Aging,Pubchem,Quick_GO,Drugage,aging
40,107812,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,2-aminoethanesulfinic acid,C(CS(=O)O)N,DrugAge,Drosophila melanogaster,Hypotaurine,...,NaN,NaN,-39.76,0.1 M,2495975.0,Aging,Pubchem,Quick_GO,Drugage,aging
41,439373,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(3S,4R,5R)-5-[(1S)-1,2-dihydroxyethyl]-3,4-dih...",C([C@@H]([C@@H]1[C@@H]([C@@H](C(=O)O1)O)O)O)O,DrugAge,Drosophila melanogaster,L-Gulonolactone,...,NaN,NaN,-40.30,0.8 M,1756780.0,Aging,Pubchem,Quick_GO,Drugage,aging
42,54670067,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2-[(1S)-1,2-dihydroxyethyl]-3,4-dihydroxy...",C([C@@H]([C@@H]1C(=C(C(=O)O1)O)O)O)O,DrugAge,Drosophila melanogaster,Ascorbic acid,...,NaN,NaN,-3.40,0.1 M,1756780.0,Aging,Pubchem,Quick_GO,Drugage,aging
43,6099,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,[7-(dimethylamino)phenothiazin-3-ylidene]-dime...,CN(C)C1=CC2=C(C=C1)N=C3C=CC(=[N+](C)C)C=C3S2.[...,DrugAge,Drosophila melanogaster,Methylene blue,...,NaN,NaN,-49.00,1 mM,8350657.0,Aging,Pubchem,Quick_GO,Drugage,aging
44,67701,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,3-(diaminomethylideneamino)propanoic acid,C(CN=C(N)N)C(=O)O,DrugAge,Drosophila melanogaster,Beta-Guanidinopropionic acid,...,NaN,NaN,-54.00,900 mM,34141906.0,Aging,Pubchem,Quick_GO,Drugage,aging
45,16218979,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"[(2R,3S,6S,7R)-3-[(3-formamido-2-hydroxybenzoy...",CCCCCCC1[C@H]([C@@H](OC(=O)[C@H]([C@H](OC1=O)C...,DrugAge,Drosophila melanogaster,Antimycin A,...,NaN,NaN,-78.27,200 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
46,107935,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"(1S,14S)-17,18-dimethoxy-7,7-dimethyl-2,8,21-t...",CC1(C=CC2=C(O1)C=CC3=C2O[C@@H]4COC5=CC(=C(C=C5...,DrugAge,Drosophila melanogaster,Deguelin,...,NaN,NaN,-31.58,200 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
47,4477,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,5-chloro-N-(2-chloro-4-nitrophenyl)-2-hydroxyb...,C1=CC(=C(C=C1[N+](=O)[O-])Cl)NC(=O)C2=C(C=CC(=...,DrugAge,Drosophila melanogaster,Nicolsamide,...,NaN,NaN,-7.45,20 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
48,6305,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-amino-3-(1H-indol-3-yl)propanoic acid,C1=CC=C2C(=C1)C(=CN2)C[C@@H](C(=O)O)N,DrugAge,Drosophila melanogaster,Tryptophan,...,NaN,NaN,-3.93,20 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
49,9571016,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,(1E)-2-[6-[[amino-[(E)-[amino-(4-chloroanilino...,C1=CC(=CC=C1N/C(=N/C(=NCCCCCCN=C(/N=C(/NC2=CC=...,DrugAge,Drosophila melanogaster,Chlorhexidine,...,NaN,NaN,-4.25,200 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
50,62978,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,"[4-(4-amino-6,7-dimethoxyquinazolin-2-yl)piper...",COC1=C(C=C2C(=C1)C(=NC(=N2)N3CCN(CC3)C(=O)C4CO...,DrugAge,Drosophila melanogaster,Doxazosin mesylate,...,NaN,NaN,-3.70,200 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
51,3440,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,BiologicalProcess,4-chloro-2-(furan-2-ylmethylamino)-5-sulfamoyl...,C1=COC(=C1)CNC2=CC(=C(C=C2C(=O)O)S(=O)(=O)N)Cl,DrugAge,Drosophila melanogaster,Furosemide,...,NaN,NaN,-5.49,200 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging

In [19]:
# List all source DataFrames to include
source_dfs = [
    Drugage
    
]
aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 52

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,83273,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"1,3-dimethyl-1-nitrosourea",aging,Drosophila melanogaster
1,2244,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-acetyloxybenzoic acid,aging,Drosophila melanogaster
2,24850,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,dialuminum;trisulfate,aging,Drosophila melanogaster
3,26053,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,aluminum;trinitrate,aging,Drosophila melanogaster
4,11192,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,zinc;diacetate,aging,Drosophila melanogaster
5,5280531,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"[(2E,4E,6E,8E)-3,7-dimethyl-9-(2,6,6-trimethyl...",aging,Drosophila melanogaster
6,493570,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"7,8-dimethyl-10-[(2S,3S,4R)-2,3,4,5-tetrahydro...",aging,Drosophila melanogaster
7,6036,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(3R,4S,5R,6R)-6-(hydroxymethyl)oxane-2,3,4,5-t...",aging,Drosophila melanogaster
8,5280961,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"5,7-dihydroxy-3-(4-hydroxyphenyl)chromen-4-one",aging,Drosophila melanogaster
9,4306515,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,5-(4-chlorophenyl)-1-(4-methoxyphenyl)-3-(trif...,aging,Drosophila melanogaster
10,5280805,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"2-(3,4-dihydroxyphenyl)-5,7-dihydroxy-3-[(2S,3...",aging,Drosophila melanogaster
11,170922317,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,N-[3-[(3-amino-3-oxoprop-1-en-2-yl)amino]-3-ox...,aging,Drosophila melanogaster
12,6915732,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(3R,4S,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",aging,Drosophila melanogaster
13,219099,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"5-[2-[4-(1,2-benzothiazol-3-yl)piperazin-1-yl]...",aging,Drosophila melanogaster
14,5281727,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"4-[(E)-2-(3,5-dimethoxyphenyl)ethenyl]phenol",aging,Drosophila melanogaster
15,969516,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(1E,6E)-1,7-bis(4-hydroxy-3-methoxyphenyl)hept...",aging,Drosophila melanogaster
16,72276,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2R,3R)-2-(3,4-dihydroxyphenyl)-3,4-dihydro-2H...",aging,Drosophila melanogaster
17,5280343,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"2-(3,4-dihydroxyphenyl)-3,5,7-trihydroxychrome...",aging,Drosophila melanogaster
18,2519,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"1,3,7-trimethylpurine-2,6-dione",aging,Drosophila melanogaster
19,1123,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-aminoethanesulfonic acid,aging,Drosophila melanogaster
20,445154,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"5-[(E)-2-(4-hydroxyphenyl)ethenyl]benzene-1,3-...",aging,Drosophila melanogaster
21,5222465,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,sodium;butanoate,aging,Drosophila melanogaster
22,4091,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"3-(diaminomethylidene)-1,1-dimethylguanidine",aging,Drosophila melanogaster
23,6758,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(1S,6R,13S)-16,17-dimethoxy-6-prop-1-en-2-yl-2...",aging,Drosophila melanogaster
24,15939,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,1-methyl-4-(1-methylpyridin-1-ium-4-yl)pyridin...,aging,Drosophila melanogaster
25,54675810,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2R)-2-[(1R)-1,2-dihydroxyethyl]-3,4-dihydroxy...",aging,Drosophila melanogaster
26,24947,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,dichlorocadmium,aging,Drosophila melanogaster
27,76034190,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"copper;2-hydroxypropane-1,2,3-tricarboxylic acid",aging,Drosophila melanogaster
28,24014,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,dichlorocopper,aging,Drosophila melanogaster
29,24462,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,copper;sulfate,aging,Drosophila melanogaster
30,10692,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"copper;(2R,3S,4R,5R)-2,3,4,5,6-pentahydroxyhex...",aging,Drosophila melanogaster
31,3032611,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,copper;2-aminoacetate,aging,Drosophila melanogaster
32,24012,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,trichloroalumane,aging,Drosophila melanogaster
33,679,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,methylsulfinylmethane,aging,Drosophila melanogaster
34,3715,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-[1-(4-chlorobenzoyl)-5-methoxy-2-methylindol...,aging,Drosophila melanogaster
35,996,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,phenol,aging,Drosophila melanogaster
36,338,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-hydroxybenzoic acid,aging,Drosophila melanogaster
37,16760658,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,sodium;2-hydroxybenzoate,aging,Drosophila melanogaster
38,6240,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"3-(2-chlorophenothiazin-10-yl)-N,N-dimethylpro...",aging,Drosophila melanogaster
39,24085,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,dichloromercury,aging,Drosophila melanogaster
40,107812,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,2-aminoethanesulfinic acid,aging,Drosophila melanogaster
41,439373,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(3S,4R,5R)-5-[(1S)-1,2-dihydroxyethyl]-3,4-dih...",aging,Drosophila melanogaster
42,54670067,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2R)-2-[(1S)-1,2-dihydroxyethyl]-3,4-dihydroxy...",aging,Drosophila melanogaster
43,6099,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,[7-(dimethylamino)phenothiazin-3-ylidene]-dime...,aging,Drosophila melanogaster
44,67701,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,3-(diaminomethylideneamino)propanoic acid,aging,Drosophila melanogaster
45,16218979,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"[(2R,3S,6S,7R)-3-[(3-formamido-2-hydroxybenzoy...",aging,Drosophila melanogaster
46,107935,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(1S,14S)-17,18-dimethoxy-7,7-dimethyl-2,8,21-t...",aging,Drosophila melanogaster
47,4477,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,5-chloro-N-(2-chloro-4-nitrophenyl)-2-hydroxyb...,aging,Drosophila melanogaster
48,6305,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,(2S)-2-amino-3-(1H-indol-3-yl)propanoic acid,aging,Drosophila melanogaster
49,9571016,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,(1E)-2-[6-[[amino-[(E)-[amino-(4-chloroanilino...,aging,Drosophila melanogaster
50,62978,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"[4-(4-amino-6,7-dimethoxyquinazolin-2-yl)piper...",aging,Drosophila melanogaster
51,3440,ChemicalEntity_NegativelyAssociatedWith_Biolog...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,4-chloro-2-(furan-2-ylmethylamino)-5-sulfamoyl...,aging,Drosophila melanogaster

In [20]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            52                   0              52
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [21]:
! mkdir Drosophila_chemical_negativeassociated_biologicalprocess

mkdir: cannot create directory ‘Drosophila_chemical_negativeassociated_biologicalprocess’: File exists

In [22]:
final_df.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df):,} rows → {OUT_PATH}")

Saved 52 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_chemical_negativeassociated_biologicalprocess/Drosophila_chemical_negativeassociated_biologicalprocess.csv

# NOT ASSOCIATION

In [23]:
# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Drosophila_chemical_notassociated_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_chemical_notassociated_biologicalprocess/Drosophila_chemical_notassociated_biologicalprocess.csv'

In [24]:
Drugage = pd.read_csv(PROC_DIR + 'drugage/drugage_final/Droso_CE_Not_BioPro_merged.csv')
Drugage.columns = Drugage.columns.str.lower()
Drugage = Drugage[~Drugage['head_detail_name'].isna()]

Drugage['kg_type'] = 'Aging'

print(f"Drugage: {len(Drugage):,} rows")
Drugage['head_id_is'] = 'Pubchem'
Drugage['tail_id_is'] = 'Quick_GO'
Drugage['relation'] = 'ChemicalEntity_NotAssociatedWith_BiologicalProcess'
Drugage['kg_source'] = 'Drugage'
Drugage['tail_detail_name'] = 'aging'
Drugage

Drugage: 165 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,...,age_at_initiation,treatment_duration,avg_lifespan_change_percent,dosage,pubmed_id,kg_type,head_id_is,tail_id_is,kg_source,tail_detail_name
0,19463,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"N,N-diethylhydroxylamine",CCN(CC)O,DrugAge,Drosophila melanogaster,Diethylhydroxylamine,...,NaN,NaN,2.30,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
1,440667,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"(5R)-5-[(1S)-1,2-dihydroxyethyl]oxolane-2,3,4-...",C([C@@H]([C@@H]1C(=O)C(=O)C(=O)O1)O)O,DrugAge,Drosophila melanogaster,Dehydroascorbic acid,...,NaN,NaN,0.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
2,54670067,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2-[(1S)-1,2-dihydroxyethyl]-3,4-dihydroxy...",C([C@@H]([C@@H]1C(=C(C(=O)O1)O)O)O)O,DrugAge,Drosophila melanogaster,Ascorbic acid,...,NaN,NaN,0.00,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
3,439373,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"(3S,4R,5R)-5-[(1S)-1,2-dihydroxyethyl]-3,4-dih...",C([C@@H]([C@@H]1[C@@H]([C@@H](C(=O)O1)O)O)O)O,DrugAge,Drosophila melanogaster,L-Gulonolactone,...,NaN,NaN,-4.50,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
4,1188,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"3,7-dihydropurine-2,6-dione",C1=NC2=C(N1)C(=O)NC(=O)N2,DrugAge,Drosophila melanogaster,Xanthine,...,NaN,NaN,1.80,NaN,NaN,Aging,Pubchem,Quick_GO,Drugage,aging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,62978,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"[4-(4-amino-6,7-dimethoxyquinazolin-2-yl)piper...",COC1=C(C=C2C(=C1)C(=NC(=N2)N3CCN(CC3)C(=O)C4CO...,DrugAge,Drosophila melanogaster,Doxazosin mesylate,...,NaN,NaN,-3.12,20 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
161,3878,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"6-(2,3-dichlorophenyl)-1,2,4-triazine-3,5-diamine",C1=CC(=C(C(=C1)Cl)Cl)C2=C(N=C(N=N2)N)N,DrugAge,Drosophila melanogaster,Lamotrigine,...,NaN,NaN,5.41,20 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
162,6915732,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"(3R,4S,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",C([C@@H]1[C@H]([C@H]([C@H](C(O1)O)N)O)O)O,DrugAge,Drosophila melanogaster,Alln,...,NaN,NaN,-4.05,20 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
163,9552079,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,(1E)-2-[6-[[amino-[(E)-[amino-(4-chloroanilino...,C1=CC(=CC=C1N/C(=N/C(=NCCCCCCN=C(/N=C(/NC2=CC=...,DrugAge,Drosophila melanogaster,Chlorohexidine,...,NaN,NaN,-3.95,200 μM,33008901.0,Aging,Pubchem,Quick_GO,Drugage,aging
164,55245,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,BiologicalProcess,"(8S,11R,13S,14S,17S)-11-[4-(dimethylamino)phen...",CC#C[C@@]1(CC[C@@H]2[C@@]1(C[C@@H](C3=C4CCC(=O...,DrugAge,Drosophila melanogaster,Mifepristone,...,NaN,NaN,-3.45,200 μg/mL,32648907.0,Aging,Pubchem,Quick_GO,Drugage,aging

In [25]:
# List all source DataFrames to include
source_dfs = [
    Drugage
    
]
aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 165

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,19463,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"N,N-diethylhydroxylamine",aging,Drosophila melanogaster
1,440667,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(5R)-5-[(1S)-1,2-dihydroxyethyl]oxolane-2,3,4-...",aging,Drosophila melanogaster
2,54670067,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(2R)-2-[(1S)-1,2-dihydroxyethyl]-3,4-dihydroxy...",aging,Drosophila melanogaster
3,439373,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(3S,4R,5R)-5-[(1S)-1,2-dihydroxyethyl]-3,4-dih...",aging,Drosophila melanogaster
4,1188,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"3,7-dihydropurine-2,6-dione",aging,Drosophila melanogaster
...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,62978,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"[4-(4-amino-6,7-dimethoxyquinazolin-2-yl)piper...",aging,Drosophila melanogaster
161,3878,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"6-(2,3-dichlorophenyl)-1,2,4-triazine-3,5-diamine",aging,Drosophila melanogaster
162,6915732,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(3R,4S,5S,6R)-3-amino-6-(hydroxymethyl)oxane-2...",aging,Drosophila melanogaster
163,9552079,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,(1E)-2-[6-[[amino-[(E)-[amino-(4-chloroanilino...,aging,Drosophila melanogaster
164,55245,ChemicalEntity_NotAssociatedWith_BiologicalPro...,GO:0007568,ChemicalEntity,None,BiologicalProcess,Drugage,Aging,Pubchem,Quick_GO,"(8S,11R,13S,14S,17S)-11-[4-(dimethylamino)phen...",aging,Drosophila melanogaster

In [26]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           165                   0             165
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [27]:
! mkdir Drosophila_chemical_notassociated_biologicalprocess

mkdir: cannot create directory ‘Drosophila_chemical_notassociated_biologicalprocess’: File exists

In [28]:
final_df.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df):,} rows → {OUT_PATH}")

Saved 165 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_chemical_notassociated_biologicalprocess/Drosophila_chemical_notassociated_biologicalprocess.csv