In [17]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [18]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila

In [19]:

# flybase/Flybase_Droso_Gene_Phenotype.csv
# Monarch/Drosophila/Gene_Droso_Phenotype_MONARCH.csv

In [20]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Drosophila_gene_anatomy
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_gene_anatomy/Drosophila_gene_anatomy.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Drosophila_gene_anatomy’: File exists

In [21]:
#

# monarch

In [6]:

monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Drosophila/Gene_Droso_Anatomy.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'
monarch['relation'] = 'Gene_AnatomicalEntity'
monarch['tail_type'] = 'AnatomicalEntity'

monarch['species'] = 'D.melanogaster'
monarch['head_id_is'] = 'NCBI_ID'
monarch['tail_id_is'] = 'Quick_GO'
print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 396,331 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,CG8340,Gene_Anatomy,FBbt:00003007,Gene,expressed_in,AnatomicalEntity,infores:flybase,upstream of RpIII128,adult head,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,128up,D.melanogaster,Generalised,Monarch_KG
1,CG31196,Gene_Anatomy,FBbt:00001056,Gene,expressed_in,AnatomicalEntity,infores:flybase,14-3-3epsilon,presumptive embryonic/larval central nervous s...,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,14-3-3ε,D.melanogaster,Generalised,Monarch_KG
2,CG31196,Gene_Anatomy,FBbt:00001134,Gene,expressed_in,AnatomicalEntity,infores:flybase,14-3-3epsilon,presumptive embryonic/larval peripheral nervou...,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,14-3-3ε,D.melanogaster,Generalised,Monarch_KG
3,CG31196,Gene_Anatomy,FBbt:00000092,Gene,expressed_in,AnatomicalEntity,infores:flybase,14-3-3epsilon,primordial germ cell,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,14-3-3ε,D.melanogaster,Generalised,Monarch_KG
4,CG31196,Gene_Anatomy,FBbt:00005409,Gene,expressed_in,AnatomicalEntity,infores:flybase,14-3-3epsilon,ring canal,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,14-3-3ε,D.melanogaster,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397416,CG15304,Gene_Anatomy,FBbt:00003154,Gene,expressed_in,AnatomicalEntity,infores:flybase,Neb-cGP,adult heart,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,Neb-cGP,D.melanogaster,Generalised,Monarch_KG
397417,CG15304,Gene_Anatomy,FBbt:00003154,Gene,expressed_in,AnatomicalEntity,infores:flybase,Neb-cGP,adult heart,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,Neb-cGP,D.melanogaster,Generalised,Monarch_KG
397418,CG15304,Gene_Anatomy,FBbt:00003154,Gene,expressed_in,AnatomicalEntity,infores:flybase,Neb-cGP,adult heart,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,Neb-cGP,D.melanogaster,Generalised,Monarch_KG
397419,CG15304,Gene_Anatomy,FBbt:00003154,Gene,expressed_in,AnatomicalEntity,infores:flybase,Neb-cGP,adult heart,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,Neb-cGP,D.melanogaster,Generalised,Monarch_KG
397420,CG15304,Gene_Anatomy,FBbt:00003154,Gene,expressed_in,AnatomicalEntity,infores:flybase,Neb-cGP,adult heart,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,Neb-cGP,D.melanogaster,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [7]:
# List all source DataFrames to include
source_dfs = [
    monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 396,331

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,CG8340,Gene_Anatomy,FBbt:00003007,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI_ID,Quick_GO,upstream of RpIII128,adult head,D.melanogaster
1,CG31196,Gene_Anatomy,FBbt:00001056,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI_ID,Quick_GO,14-3-3epsilon,presumptive embryonic/larval central nervous s...,D.melanogaster
2,CG31196,Gene_Anatomy,FBbt:00001134,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI_ID,Quick_GO,14-3-3epsilon,presumptive embryonic/larval peripheral nervou...,D.melanogaster
3,CG31196,Gene_Anatomy,FBbt:00000092,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI_ID,Quick_GO,14-3-3epsilon,primordial germ cell,D.melanogaster
4,CG31196,Gene_Anatomy,FBbt:00005409,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI_ID,Quick_GO,14-3-3epsilon,ring canal,D.melanogaster
...,...,...,...,...,...,...,...,...,...,...,...,...,...
396326,CG15304,Gene_Anatomy,FBbt:00003154,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Neb-cGP,adult heart,D.melanogaster
396327,CG15304,Gene_Anatomy,FBbt:00003154,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Neb-cGP,adult heart,D.melanogaster
396328,CG15304,Gene_Anatomy,FBbt:00003154,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Neb-cGP,adult heart,D.melanogaster
396329,CG15304,Gene_Anatomy,FBbt:00003154,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Neb-cGP,adult heart,D.melanogaster
396330,CG15304,Gene_Anatomy,FBbt:00003154,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Neb-cGP,adult heart,D.melanogaster

# Sanity Check — Distinct Values

In [8]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_Anatomy'}
head_type           : {'Gene'}
tail_type           : {'AnatomicalEntity'}
relation_type       : {'expressed_in'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [9]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 396,331 remaining

# NaN Audit (pre-dedup)

In [10]:
true_nan   = final_df.isna().sum()
genDR_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type             0                  0               0
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0
species                   0                  0               0

# Deduplication

In [11]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 396,331  |  After dedup: 88,664

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name
0,-,Gene_Anatomy,FBbt:00000001,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI_ID,Quick_GO,lethal (1) XG10,organism
1,-,Gene_Anatomy,FBbt:00000004,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI_ID,Quick_GO,lethal (1) XG10,head
2,-,Gene_Anatomy,FBbt:00000007,Gene,expressed_in,AnatomicalEntity,Monarch_KG,Generalised,NCBI_ID,Quick_GO,lethal (1) XG10,procephalic segment

In [12]:
true_nan   = final_df_dedup.isna().sum()
genDR_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type             0                  0               0
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    88664
Name: count, dtype: int64

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    88664
Name: count, dtype: int64

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 88,664 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_gene_anatomy/Drosophila_gene_anatomy.csv

In [16]:
#