In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Drosophila_gene_cellularcomponent
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_gene_cellularcomponent/Drosophila_gene_cellularcomponent.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

# monarch

In [5]:

monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Drosophila/Gene_Droso_CellularComponent.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'

monarch['species'] = 'D.melanogaster'
monarch['head_id_is'] = 'NCBI_ID'
monarch['tail_id_is'] = 'Quick_GO'
print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 49,672 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,CG14971,Gene_CellularComponent,GO:0000138,Gene,expressed_in,CellularComponent,infores:flybase,uncharacterized protein,Golgi trans cisterna,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,CG14971,D.melanogaster,Generalised,Monarch_KG
1,CG6875,Gene_CellularComponent,GO:0005813,Gene,expressed_in,CellularComponent,infores:flybase,abnormal spindle,centrosome,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,asp,D.melanogaster,Generalised,Monarch_KG
2,CG2746,Gene_CellularComponent,GO:0022626,Gene,expressed_in,CellularComponent,infores:flybase,Ribosomal protein L19,cytosolic ribosome,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,RpL19,D.melanogaster,Generalised,Monarch_KG
3,CG10837,Gene_CellularComponent,GO:0005829,Gene,expressed_in,CellularComponent,infores:flybase,eukaryotic translation initiation factor 4B,cytosol,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,eIF4B,D.melanogaster,Generalised,Monarch_KG
4,CG7622,Gene_CellularComponent,GO:0022626,Gene,expressed_in,CellularComponent,infores:flybase,Ribosomal protein L36,cytosolic ribosome,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,RpL36,D.melanogaster,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50082,CG7345,Gene_CellularComponent,GO:0005634,Gene,is_active_in,CellularComponent,infores:go-central,Sox21a,nucleus,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,Sox21a,D.melanogaster,Generalised,Monarch_KG
50083,CG12443,Gene_CellularComponent,GO:0005615,Gene,is_active_in,CellularComponent,infores:go-central,thisbe,extracellular space,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,ths,D.melanogaster,Generalised,Monarch_KG
50084,CG30021,Gene_CellularComponent,GO:0005886,Gene,is_active_in,CellularComponent,infores:go-central,menage a trois,plasma membrane,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,metro,D.melanogaster,Generalised,Monarch_KG
50085,CG31913,Gene_CellularComponent,GO:0005743,Gene,is_active_in,CellularComponent,infores:go-central,uncharacterized protein,mitochondrial inner membrane,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,CG31913,D.melanogaster,Generalised,Monarch_KG
50086,CG9308,Gene_CellularComponent,GO:0005793,Gene,is_active_in,CellularComponent,infores:go-central,uncharacterized protein,endoplasmic reticulum-Golgi intermediate compa...,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,CG9308,D.melanogaster,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
    monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 49,672

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,CG14971,Gene_CellularComponent,GO:0000138,Gene,expressed_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,uncharacterized protein,Golgi trans cisterna,D.melanogaster
1,CG6875,Gene_CellularComponent,GO:0005813,Gene,expressed_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,abnormal spindle,centrosome,D.melanogaster
2,CG2746,Gene_CellularComponent,GO:0022626,Gene,expressed_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Ribosomal protein L19,cytosolic ribosome,D.melanogaster
3,CG10837,Gene_CellularComponent,GO:0005829,Gene,expressed_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,eukaryotic translation initiation factor 4B,cytosol,D.melanogaster
4,CG7622,Gene_CellularComponent,GO:0022626,Gene,expressed_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Ribosomal protein L36,cytosolic ribosome,D.melanogaster
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49667,CG7345,Gene_CellularComponent,GO:0005634,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Sox21a,nucleus,D.melanogaster
49668,CG12443,Gene_CellularComponent,GO:0005615,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,thisbe,extracellular space,D.melanogaster
49669,CG30021,Gene_CellularComponent,GO:0005886,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,menage a trois,plasma membrane,D.melanogaster
49670,CG31913,Gene_CellularComponent,GO:0005743,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,uncharacterized protein,mitochondrial inner membrane,D.melanogaster
49671,CG9308,Gene_CellularComponent,GO:0005793,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,uncharacterized protein,endoplasmic reticulum-Golgi intermediate compa...,D.melanogaster

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_CellularComponent'}
head_type           : {'Gene'}
tail_type           : {'CellularComponent'}
relation_type       : {'colocalizes_with', 'expressed_in', 'part_of', 'is_active_in', 'located_in'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 49,672 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
genDR_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type             0                  0               0
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0
species                   0                  0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 49,672  |  After dedup: 26,136

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name
0,-,Gene_CellularComponent,GO:0000785,Gene,located_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,lethal (1) XG10,chromatin
1,-,Gene_CellularComponent,GO:0005575,Gene,is_active_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,lethal (1) XG10,cellular_component
2,-,Gene_CellularComponent,GO:0005576,Gene,expressed_in,CellularComponent,Monarch_KG,Generalised,NCBI_ID,Quick_GO,lethal (1) XG10,extracellular region

In [11]:
true_nan   = final_df_dedup.isna().sum()
genDR_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type             0                  0               0
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    26136
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    26136
Name: count, dtype: int64

In [14]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 26,136 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_gene_cellularcomponent/Drosophila_gene_cellularcomponent.csv

In [15]:
#