In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Droso_chemical_inhibits_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Droso_chemical_inhibits_biologicalprocess/Droso_chemical_inhibits_biologicalprocess.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

# AgeXtend

In [4]:
AgeXtend = pd.read_csv(PROC_DIR + 'agextend_processed/AgeXtend_Droso_ChemicalEntity_Inhibits_BiologicalProcess.csv')
AgeXtend.columns = AgeXtend.columns.str.lower()
AgeXtend = AgeXtend[~AgeXtend['head_detail_name'].isna()]

AgeXtend['kg_type'] = 'Aging'

print(f"AgeXtend: {len(AgeXtend):,} rows")
AgeXtend['head_id_is'] = 'Pubchem'
AgeXtend['tail_id_is'] = 'Quick_GO'
AgeXtend['species'] = 'Drosophila melanogaster'
AgeXtend['kg_source'] = 'AgeXtend'

AgeXtend

AgeXtend: 11 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,tail_detail_name,relation_source,species,data_source,anti_aging_status,anti_aging_prob,kg_type,head_id_is,tail_id_is,kg_source
0,219042,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,(4S)-4-[[(2S)-2-aminopropanoyl]amino]-5-[[(2S)...,C[C@@H](C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CC(...,aging,AgeXtend,Drosophila melanogaster,https://doi.org/10.1016/S0047-6374(00)00217-7,1,0.867517,Aging,Pubchem,Quick_GO,AgeXtend
1,64971,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(1R,3aS,5aR,5bR,7aR,9S,11aR,11bR,13aR,13bR)-9-...",CC(=C)[C@@H]1CC[C@]2([C@H]1[C@H]3CC[C@@H]4[C@]...,aging,AgeXtend,Drosophila melanogaster,https://doi.org/10.3390/nu16030441,1,0.897566,Aging,Pubchem,Quick_GO,AgeXtend
2,156517,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"4-[(2S,3S,4R,5R)-5-(4-hydroxy-3-methoxyphenyl)...",C[C@@H]1[C@@H]([C@H](O[C@H]1C2=CC(=C(C=C2)O)OC...,aging,AgeXtend,Drosophila melanogaster,https://doi.org/10.18632/aging.205234,1,0.872718,Aging,Pubchem,Quick_GO,AgeXtend
3,638024,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2E,4E)-5-(1,3-benzodioxol-5-yl)-1-piperidin-1...",C1CCN(CC1)C(=O)/C=C/C=C/C2=CC3=C(C=C2)OCO3,aging,AgeXtend,Drosophila melanogaster,https://doi.org/10.21203/rs.3.rs-3757264/v1,1,0.738333,Aging,Pubchem,Quick_GO,AgeXtend
4,16725726,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"4-[2-(4-amino-1,2,5-oxadiazol-3-yl)-1-ethyl-7-...",CCN1C2=C(C(=NC=C2OC[C@H]3CCCNC3)C#CC(C)(C)O)N=...,aging,AgeXtend,Drosophila melanogaster,https://doi.org/10.1016/j.mad.2022.111633,1,0.685101,Aging,Pubchem,Quick_GO,AgeXtend
5,115067,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R,3S,4S,5R,6S)-2-(hydroxymethyl)-6-[4-(hydro...",C1=CC(=CC=C1CO)O[C@H]2[C@@H]([C@H]([C@@H]([C@H...,aging,AgeXtend,Drosophila melanogaster,https://doi.org/10.1039/D1FO00847A,1,0.869110,Aging,Pubchem,Quick_GO,AgeXtend
6,5281807,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"7-hydroxy-3-(4-hydroxyphenyl)-8-[(2S,3R,4R,5S,...",C1=CC(=CC=C1C2=COC3=C(C2=O)C=CC(=C3[C@H]4[C@@H...,aging,AgeXtend,Drosophila melanogaster,https://doi.org/10.1039/D2FO02800J,1,0.926578,Aging,Pubchem,Quick_GO,AgeXtend
7,5281727,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"4-[(E)-2-(3,5-dimethoxyphenyl)ethenyl]phenol",COC1=CC(=CC(=C1)/C=C/C2=CC=C(C=C2)O)OC,aging,AgeXtend,Drosophila melanogaster,https://doi.org/10.1155/2022/1744408,1,0.895461,Aging,Pubchem,Quick_GO,AgeXtend
8,2888648,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,N-(3-carbazol-9-yl-2-hydroxypropyl)-N-(furan-2...,CS(=O)(=O)N(CC1=CC=CO1)CC(CN2C3=CC=CC=C3C4=CC=...,aging,AgeXtend,Drosophila melanogaster,https://doi.org/10.3390/clockssleep3030030,1,0.639829,Aging,Pubchem,Quick_GO,AgeXtend
9,168312228,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,3-[3-[N-[(4-bromophenyl)methoxy]-C-methylcarbo...,CCOC(CC1=CC(=CC=C1)C(=NOCC2=CC=C(C=C2)Br)C)C(=O)O,aging,AgeXtend,Drosophila melanogaster,https://doi.org/10.3390/clockssleep3030030,1,0.850064,Aging,Pubchem,Quick_GO,AgeXtend
10,222528,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(4R)-4-[(3R,5R,8R,9S,10S,12S,13R,14S,17R)-3,12...",C[C@H](CCC(=O)O)[C@H]1CC[C@@H]2[C@@]1([C@H](C[...,aging,AgeXtend,Drosophila melanogaster,https://biointerfaceresearch.com/wp-content/up...,1,0.834094,Aging,Pubchem,Quick_GO,AgeXtend

# AgingAtlas

In [5]:
AgingAtlas = pd.read_csv(PROC_DIR + 'agingatlas/Droso/Droso_AgingAtlas_Chemical_Inhibit_BiologicalProcess_Geroprotectors.csv')
AgingAtlas.columns = AgingAtlas.columns.str.lower()
AgingAtlas = AgingAtlas[~AgingAtlas['head_detail_name'].isna()]

AgingAtlas['kg_type'] = 'Aging'
AgingAtlas['tail_type'] = 'BiologicalProcess'
print(f"AgingAtlas: {len(AgingAtlas):,} rows")
AgingAtlas['head_id_is'] = 'Pubchem'
AgingAtlas['tail_id_is'] = 'Quick_GO'
AgingAtlas['species'] =  'Drosophila melanogaster'
AgingAtlas['kg_source'] = 'AgingAtlas'
AgingAtlas

AgingAtlas: 64 rows

,head,relation,tail,head_type,tail_type,head_detail_name,head_smile_name,relation_source,species,head_alt_name,pmid,rnaseq,data_type,tail_detail_name,kg_type,head_id_is,tail_id_is,kg_source
0,5328779,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(E)-N-benzyl-2-cyano-3-(3,4-dihydroxyphenyl)pr...",C1=CC=C(C=C1)CNC(=O)/C(=C/C2=CC(=C(C=C2)O)O)/C#N,Aging_Atlas_gerprotector,Drosophila melanogaster,AG-490,\t22363408,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
1,864,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,5-(dithiolan-3-yl)pentanoic acid,C1CSSC1CCCCC(=O)O,Aging_Atlas_gerprotector,Drosophila melanogaster,Alpha-lipoic acid,15328413,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
2,67701,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,3-(diaminomethylideneamino)propanoic acid,C(CN=C(N)N)C(=O)O,Aging_Atlas_gerprotector,Drosophila melanogaster,Beta-Guanidinopropionic acid,26120775,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
3,13144,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,calcium;2-hydroxypropanoate,CC(C(=O)[O-])O.CC(C(=O)[O-])O.[Ca+2],Aging_Atlas_gerprotector,Drosophila melanogaster,Calcium lactate,110607,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
4,439224,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,(2S)-2-(3-aminopropanoylamino)-3-(1H-imidazol-...,C1=C(NC=N1)C[C@@H](C(=O)O)NC(=O)CCN,Aging_Atlas_gerprotector,Drosophila melanogaster,Carnosine,12447464,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2051,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"N-(3-chlorophenyl)-6,7-dimethoxyquinazolin-4-a...",COC1=C(C=C2C(=C1)C(=NC=N2)NC3=CC(=CC=C3)Cl)OC,Aging_Atlas_gerprotector,Drosophila melanogaster,Tyrphostin AG 1478,22363408,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
60,64945,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(1S,2R,4aS,6aR,6aS,6bR,8aR,10S,12aR,14bS)-10-h...",C[C@@H]1CC[C@@]2(CC[C@@]3(C(=CC[C@H]4[C@]3(CC[...,Aging_Atlas_gerprotector,Drosophila melanogaster,Ursolic acid,30496629,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
61,54670067,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2-[(1S)-1,2-dihydroxyethyl]-3,4-dihydroxy...",C([C@@H]([C@@H]1C(=C(C(=O)O1)O)O)O)O,Aging_Atlas_gerprotector,Drosophila melanogaster,Vitamin C,29093334,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
62,14985,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",CC1=C(C2=C(CC[C@@](O2)(C)CCC[C@H](C)CCC[C@H](C...,Aging_Atlas_gerprotector,Drosophila melanogaster,Vitamin E,17169403,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas
63,312145,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,BiologicalProcess,"[(1R,3R,5S,9R,18S)-18-(methoxymethyl)-1,5-dime...",CC(=O)O[C@@H]1C[C@]2([C@@H](CCC2=O)C3=C1[C@]4(...,Aging_Atlas_gerprotector,Drosophila melanogaster,Wortmannin,24096697,Not Available,Causative,aging,Aging,Pubchem,Quick_GO,AgingAtlas

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
    AgeXtend, AgingAtlas
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 75

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,219042,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,(4S)-4-[[(2S)-2-aminopropanoyl]amino]-5-[[(2S)...,aging,Drosophila melanogaster
1,64971,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"(1R,3aS,5aR,5bR,7aR,9S,11aR,11bR,13aR,13bR)-9-...",aging,Drosophila melanogaster
2,156517,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"4-[(2S,3S,4R,5R)-5-(4-hydroxy-3-methoxyphenyl)...",aging,Drosophila melanogaster
3,638024,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"(2E,4E)-5-(1,3-benzodioxol-5-yl)-1-piperidin-1...",aging,Drosophila melanogaster
4,16725726,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgeXtend,Aging,Pubchem,Quick_GO,"4-[2-(4-amino-1,2,5-oxadiazol-3-yl)-1-ethyl-7-...",aging,Drosophila melanogaster
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2051,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"N-(3-chlorophenyl)-6,7-dimethoxyquinazolin-4-a...",aging,Drosophila melanogaster
71,64945,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(1S,2R,4aS,6aR,6aS,6bR,8aR,10S,12aR,14bS)-10-h...",aging,Drosophila melanogaster
72,54670067,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(2R)-2-[(1S)-1,2-dihydroxyethyl]-3,4-dihydroxy...",aging,Drosophila melanogaster
73,14985,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",aging,Drosophila melanogaster
74,312145,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"[(1R,3R,5S,9R,18S)-18-(methoxymethyl)-1,5-dime...",aging,Drosophila melanogaster

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'ChemicalEntity_Inhibits_BiologicalProcess'}
head_type           : {'ChemicalEntity'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'AgeXtend', 'AgingAtlas'}
head_id_is          : {'Pubchem'}
tail_id_is          : {'Quick_GO'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 75 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            75                   0              75
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 75  |  After dedup: 71

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,612,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,2-hydroxypropanoic acid,aging,Drosophila melanogaster
1,864,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,5-(dithiolan-3-yl)pentanoic acid,aging,Drosophila melanogaster
2,892,ChemicalEntity_Inhibits_BiologicalProcess,GO:0007568,ChemicalEntity,None,BiologicalProcess,AgingAtlas,Aging,Pubchem,Quick_GO,"cyclohexane-1,2,3,4,5,6-hexol",aging,Drosophila melanogaster

In [11]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            71                   0              71
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'AgeXtend', 'AgeXtend::AgingAtlas', 'AgingAtlas'} kg_source
AgingAtlas              60
AgeXtend                10
AgeXtend::AgingAtlas     1
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    71
Name: count, dtype: int64

In [14]:
! mkdir Droso_chemical_inhibits_biologicalprocess

mkdir: cannot create directory ‘Droso_chemical_inhibits_biologicalprocess’: File exists

In [15]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 71 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Droso_chemical_inhibits_biologicalprocess/Droso_chemical_inhibits_biologicalprocess.csv

In [16]:
# OUT_PATH

In [17]:
#