In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila

In [3]:
! pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila

In [4]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Droso_gene_promotes_biologicalprocess
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Droso_gene_promotes_biologicalprocess/Droso_gene_promotes_biologicalprocess.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [5]:
#

In [6]:
# Mouse = pd.read_csv(
#     f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Mus_musculus.gene_info',
#     sep='\t',
    
# )
# # Mouse["LocusTag"] = Mouse["LocusTag"].str.replace("Dmel_", "", regex=False)

# # Mouse_symbol2Locus_dict = dict(zip(Mouse['Symbol'], Mouse['LocusTag']))
# # Mouse
# # Mouse_symbol2Locus_dict
# Mouse

# Genage

In [7]:
Genage = pd.read_csv(PROC_DIR + 'genage/Droso/Droso_Gene_Promotes_BiologicalProcess.csv')
Genage.columns = Genage.columns.str.lower()
Genage = Genage[~Genage['head_detail_name'].isna()]

Genage['kg_type'] = 'Aging'
Genage['relation'] = 'Gene_Promotes_BiologicalProcess'
print(f"Genage: {len(Genage):,} rows")
Genage['head_id_is'] = 'NCBI_ID'
Genage['tail_id_is'] = 'Quick_GO'
Genage['species']    = 'Drosophila melanogaster'
Genage['kg_source'] = 'Genage'

Genage

Genage: 61 rows

,head,relation,tail,head_type,tail_type,head_detail_name,tail_detail_name,relation_source,species,data_type,head_alt_name,kg_type,head_id_is,tail_id_is,kg_source
0,Bmcp,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,bmcp,obsolete aging,GeneAge,Drosophila melanogaster,Causative,Bmcp,Aging,NCBI_ID,Quick_GO,Genage
1,chico,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,chico,obsolete aging,GeneAge,Drosophila melanogaster,Causative,chico,Aging,NCBI_ID,Quick_GO,Genage
2,dnc,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,dunce,obsolete aging,GeneAge,Drosophila melanogaster,Causative,dnc,Aging,NCBI_ID,Quick_GO,Genage
3,EcR,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Ecdysone receptor,obsolete aging,GeneAge,Drosophila melanogaster,Causative,EcR,Aging,NCBI_ID,Quick_GO,Genage
4,Egm,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Enigma,obsolete aging,GeneAge,Drosophila melanogaster,Causative,Egm,Aging,NCBI_ID,Quick_GO,Genage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,chm,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,chameau,obsolete aging,GeneAge,Drosophila melanogaster,Causative,chm,Aging,NCBI_ID,Quick_GO,Genage
57,Hex-A,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Hexokinase A,obsolete aging,GeneAge,Drosophila melanogaster,Causative,Hex-A,Aging,NCBI_ID,Quick_GO,Genage
58,Hex-C,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,Hexokinase C,obsolete aging,GeneAge,Drosophila melanogaster,Causative,Hex-C,Aging,NCBI_ID,Quick_GO,Genage
59,mir-277,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,mir-277 stem loop,obsolete aging,GeneAge,Drosophila melanogaster,Causative,mir-277,Aging,NCBI_ID,Quick_GO,Genage
60,mir-184,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,mir-184 stem loop,obsolete aging,GeneAge,Drosophila melanogaster,Causative,mir-184,Aging,NCBI_ID,Quick_GO,Genage

# AgingBank

In [8]:
AgingBank = pd.read_csv(PROC_DIR + 'agingbank/Droso_AgingbankGene_promotes_BioPro.csv')
AgingBank.columns = AgingBank.columns.str.lower()
AgingBank = AgingBank[~AgingBank['head_detail_name'].isna()]

AgingBank['kg_type'] = 'Aging'
AgingBank['relation'] = 'Gene_Promotes_BiologicalProcess'
AgingBank['tail_type'] = 'BiologicalProcess'
print(f"AgingBank: {len(AgingBank):,} rows")
AgingBank['head_id_is'] = 'NCBI_ID'
AgingBank['tail_id_is'] = 'Quick_GO'
AgingBank['species'] = 'Drosophila melanogaster'
AgingBank['kg_source'] = 'AgingBank'
AgingBank

AgingBank: 4 rows

,head,relation,tail,head_type,tail_type,kg_source,kg_type,head_detail_name,tail_detail_name,head_id_is,tail_id_is,kg_type.1,species
0,CAT,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,catalase,aging,NCBI_ID,Quick_GO,Aging,Drosophila melanogaster
1,EXD2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,exonuclease 3'-5' domain containing 2,aging,NCBI_ID,Quick_GO,Aging,Drosophila melanogaster
2,SOD2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,"superoxide dismutase 2, mitochondrial",aging,NCBI_ID,Quick_GO,Aging,Drosophila melanogaster
3,LMNA,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,BiologicalProcess,AgingBank,Aging,lamin A,aging,NCBI_ID,Quick_GO,Aging,Drosophila melanogaster

# Consolidate into Unified Schem

In [9]:
# List all source DataFrames to include
source_dfs = [
    Genage, AgingBank
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 65

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,Bmcp,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,bmcp,obsolete aging,Drosophila melanogaster
1,chico,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,chico,obsolete aging,Drosophila melanogaster
2,dnc,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,dunce,obsolete aging,Drosophila melanogaster
3,EcR,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Ecdysone receptor,obsolete aging,Drosophila melanogaster
4,Egm,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,Enigma,obsolete aging,Drosophila melanogaster
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,mir-184,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,mir-184 stem loop,obsolete aging,Drosophila melanogaster
61,CAT,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,catalase,aging,Drosophila melanogaster
62,EXD2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,exonuclease 3'-5' domain containing 2,aging,Drosophila melanogaster
63,SOD2,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,"superoxide dismutase 2, mitochondrial",aging,Drosophila melanogaster
64,LMNA,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,AgingBank,Aging,NCBI_ID,Quick_GO,lamin A,aging,Drosophila melanogaster

# Sanity Check — Distinct Values

In [10]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_Promotes_BiologicalProcess'}
head_type           : {'Gene'}
tail_type           : {'BiologicalProcess'}
relation_type       : {None}
kg_source           : {'Genage', 'AgingBank'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [11]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 65 remaining

# NaN Audit (pre-dedup)

In [12]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            65                   0              65
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [13]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 65  |  After dedup: 65

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,14-3-3epsilon,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,14-3-3epsilon,obsolete aging,Drosophila melanogaster
1,5-HT2A,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,5-hydroxytryptamine (serotonin) receptor 2A,obsolete aging,Drosophila melanogaster
2,ATPCL,Gene_Promotes_BiologicalProcess,GO:0007568,Gene,None,BiologicalProcess,Genage,Aging,NCBI_ID,Quick_GO,ATP citrate lyase,obsolete aging,Drosophila melanogaster

In [14]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type            65                   0              65
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Genage', 'AgingBank'} kg_source
Genage       61
AgingBank     4
Name: count, dtype: int64

In [16]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    65
Name: count, dtype: int64

In [17]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 65 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Droso_gene_promotes_biologicalprocess/Droso_gene_promotes_biologicalprocess.csv

In [18]:
# OUT_PATH

In [19]:
# ! mkdir Droso_gene_promotes_biologicalprocess