In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Drosophila_gene_molecularfunction
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_gene_molecularfunction/Drosophila_gene_molecularfunction.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

# monarch

In [5]:

monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Drosophila/Gene_Droso_MolecularFunction.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'

monarch['species'] = 'D.melanogaster'
monarch['head_id_is'] = 'NCBI_ID'
monarch['tail_id_is'] = 'Quick_GO'
print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 38,402 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,CG12725,Gene_MolecularFunction,GO:0003735,Gene,enables,MolecularFunction,infores:go-central,uncharacterized protein,structural constituent of ribosome,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,CG12725,D.melanogaster,Generalised,Monarch_KG
1,CG13623,Gene_MolecularFunction,GO:0051539,Gene,enables,MolecularFunction,infores:go-central,uncharacterized protein,"4 iron, 4 sulfur cluster binding",Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,CG13623,D.melanogaster,Generalised,Monarch_KG
2,CG14250,Gene_MolecularFunction,GO:0008010,Gene,enables,MolecularFunction,infores:go-central,TweedleQ,structural constituent of chitin-based larval ...,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,TwdlQ,D.melanogaster,Generalised,Monarch_KG
3,CG15864,Gene_MolecularFunction,GO:0004656,Gene,enables,MolecularFunction,infores:go-central,uncharacterized protein,procollagen-proline 4-dioxygenase activity,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,CG15864,D.melanogaster,Generalised,Monarch_KG
4,CG4661,Gene_MolecularFunction,GO:0097602,Gene,enables,MolecularFunction,infores:go-central,uncharacterized protein,cullin family protein binding,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,CG4661,D.melanogaster,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38730,CG13225,Gene_MolecularFunction,GO:0004984,Gene,enables,MolecularFunction,infores:go-central,Odorant receptor 47a,olfactory receptor activity,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,Or47a,D.melanogaster,Generalised,Monarch_KG
38731,CG6057,Gene_MolecularFunction,GO:0003677,Gene,enables,MolecularFunction,infores:go-central,Structural maintenance of chromosomes 1,DNA binding,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,SMC1,D.melanogaster,Generalised,Monarch_KG
38732,CG42258,Gene_MolecularFunction,GO:0004402,Gene,enables,MolecularFunction,infores:go-central,uncharacterized protein,histone acetyltransferase activity,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,CG42258,D.melanogaster,Generalised,Monarch_KG
38733,CG5682,Gene_MolecularFunction,GO:0004571,Gene,enables,MolecularFunction,infores:go-central,"ER degradation enhancer, mannosidase alpha-like 2","mannosyl-oligosaccharide 1,2-alpha-mannosidase...",Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,Edem2,D.melanogaster,Generalised,Monarch_KG
38734,CG2331,Gene_MolecularFunction,GO:0031593,Gene,enables,MolecularFunction,infores:go-central,Transitional endoplasmic reticulum 94,polyubiquitin modification-dependent protein b...,Drosophila melanogaster,NaN,NCBI_ID,Quick_GO,TER94,D.melanogaster,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
    monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 38,402

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,CG12725,Gene_MolecularFunction,GO:0003735,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI_ID,Quick_GO,uncharacterized protein,structural constituent of ribosome,D.melanogaster
1,CG13623,Gene_MolecularFunction,GO:0051539,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI_ID,Quick_GO,uncharacterized protein,"4 iron, 4 sulfur cluster binding",D.melanogaster
2,CG14250,Gene_MolecularFunction,GO:0008010,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI_ID,Quick_GO,TweedleQ,structural constituent of chitin-based larval ...,D.melanogaster
3,CG15864,Gene_MolecularFunction,GO:0004656,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI_ID,Quick_GO,uncharacterized protein,procollagen-proline 4-dioxygenase activity,D.melanogaster
4,CG4661,Gene_MolecularFunction,GO:0097602,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI_ID,Quick_GO,uncharacterized protein,cullin family protein binding,D.melanogaster
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38397,CG13225,Gene_MolecularFunction,GO:0004984,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Odorant receptor 47a,olfactory receptor activity,D.melanogaster
38398,CG6057,Gene_MolecularFunction,GO:0003677,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Structural maintenance of chromosomes 1,DNA binding,D.melanogaster
38399,CG42258,Gene_MolecularFunction,GO:0004402,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI_ID,Quick_GO,uncharacterized protein,histone acetyltransferase activity,D.melanogaster
38400,CG5682,Gene_MolecularFunction,GO:0004571,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI_ID,Quick_GO,"ER degradation enhancer, mannosidase alpha-like 2","mannosyl-oligosaccharide 1,2-alpha-mannosidase...",D.melanogaster
38401,CG2331,Gene_MolecularFunction,GO:0031593,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Transitional endoplasmic reticulum 94,polyubiquitin modification-dependent protein b...,D.melanogaster

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_MolecularFunction'}
head_type           : {'Gene'}
tail_type           : {'MolecularFunction'}
relation_type       : {'contributes_to', 'enables'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 38,402 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
genDR_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type             0                  0               0
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0
species                   0                  0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 38,402  |  After dedup: 25,935

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name
0,-,Gene_MolecularFunction,GO:0000981,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI_ID,Quick_GO,lethal (1) XG10,"DNA-binding transcription factor activity, RNA..."
1,-,Gene_MolecularFunction,GO:0003674,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI_ID,Quick_GO,lethal (1) XG10,molecular_function
2,-,Gene_MolecularFunction,GO:0003725,Gene,enables,MolecularFunction,Monarch_KG,Generalised,NCBI_ID,Quick_GO,lethal (1) XG10,double-stranded RNA binding

In [11]:
true_nan   = final_df_dedup.isna().sum()
genDR_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type             0                  0               0
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    25935
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    25935
Name: count, dtype: int64

In [14]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 25,935 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_gene_molecularfunction/Drosophila_gene_molecularfunction.csv

In [15]:
#