In [16]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [17]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila

In [18]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Drosophila_anatomy_anatomy
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_anatomy_anatomy/Drosophila_anatomy_anatomy.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Drosophila_anatomy_anatomy’: File exists

In [19]:
#

# monarch

In [21]:

monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Drosophila/Droso_AnatomicalEntity_AnatomicalEntity.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'
monarch['relation'] = 'AnatomicalEntity_AnatomicalEntity'
monarch['head_type'] = 'AnatomicalEntity'
monarch['tail_type'] = 'AnatomicalEntity'

monarch['species'] = 'D.melanogaster'
monarch['head_id_is'] = 'Flybase_ID'
monarch['tail_id_is'] = 'Flybase_ID'
print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 131,953 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,species,kg_type,kg_source
0,FBbt:00000000,AnatomicalEntity_AnatomicalEntity,FBbt:10000000,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:fbbt,germ layer derivative,anatomical entity,Drosophila melanogaster,Drosophila melanogaster,Flybase_ID,Flybase_ID,D.melanogaster,Generalised,Monarch_KG
1,FBbt:00000000,AnatomicalEntity_AnatomicalEntity,FBbt:00000110,AnatomicalEntity,related_to,AnatomicalEntity,infores:fbbt,germ layer derivative,germ layer,Drosophila melanogaster,Drosophila melanogaster,Flybase_ID,Flybase_ID,D.melanogaster,Generalised,Monarch_KG
2,FBbt:00000001,AnatomicalEntity_AnatomicalEntity,FBbt:00100313,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:fbbt,organism,multicellular structure,Drosophila melanogaster,Drosophila melanogaster,Flybase_ID,Flybase_ID,D.melanogaster,Generalised,Monarch_KG
3,FBbt:00000002,AnatomicalEntity_AnatomicalEntity,FBbt:00057001,AnatomicalEntity,subclass_of,AnatomicalEntity,infores:fbbt,tagma,anterior-posterior subdivision of organism,Drosophila melanogaster,Drosophila melanogaster,Flybase_ID,Flybase_ID,D.melanogaster,Generalised,Monarch_KG
4,FBbt:00000002,AnatomicalEntity_AnatomicalEntity,FBbt:00000001,AnatomicalEntity,related_to,AnatomicalEntity,infores:fbbt,tagma,organism,Drosophila melanogaster,Drosophila melanogaster,Flybase_ID,Flybase_ID,D.melanogaster,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131948,FBbt:20011361,AnatomicalEntity_AnatomicalEntity,FBbt:00003982,AnatomicalEntity,related_to,AnatomicalEntity,infores:fbbt,descending neuron of the posterior brain DNp70,antennal mechanosensory and motor center,Drosophila melanogaster,Drosophila melanogaster,Flybase_ID,Flybase_ID,D.melanogaster,Generalised,Monarch_KG
131949,FBbt:20011361,AnatomicalEntity_AnatomicalEntity,FBbt:00014013,AnatomicalEntity,related_to,AnatomicalEntity,infores:fbbt,descending neuron of the posterior brain DNp70,adult gnathal ganglion,Drosophila melanogaster,Drosophila melanogaster,Flybase_ID,Flybase_ID,D.melanogaster,Generalised,Monarch_KG
131950,FBbt:20011361,AnatomicalEntity_AnatomicalEntity,FBbt:00040042,AnatomicalEntity,related_to,AnatomicalEntity,infores:fbbt,descending neuron of the posterior brain DNp70,posterior ventrolateral protocerebrum,Drosophila melanogaster,Drosophila melanogaster,Flybase_ID,Flybase_ID,D.melanogaster,Generalised,Monarch_KG
131951,FBbt:20011361,AnatomicalEntity_AnatomicalEntity,FBbt:00047139,AnatomicalEntity,related_to,AnatomicalEntity,infores:fbbt,descending neuron of the posterior brain DNp70,adult leg neuropil,Drosophila melanogaster,Drosophila melanogaster,Flybase_ID,Flybase_ID,D.melanogaster,Generalised,Monarch_KG
131952,FBbt:20011361,AnatomicalEntity_AnatomicalEntity,FBbt:00047174,AnatomicalEntity,related_to,AnatomicalEntity,infores:fbbt,descending neuron of the posterior brain DNp70,lower tectulum,Drosophila melanogaster,Drosophila melanogaster,Flybase_ID,Flybase_ID,D.melanogaster,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [22]:
# List all source DataFrames to include
source_dfs = [
    monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 131,953

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,FBbt:00000000,AnatomicalEntity_AnatomicalEntity,FBbt:10000000,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,Flybase_ID,Flybase_ID,germ layer derivative,anatomical entity,D.melanogaster
1,FBbt:00000000,AnatomicalEntity_AnatomicalEntity,FBbt:00000110,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,Flybase_ID,Flybase_ID,germ layer derivative,germ layer,D.melanogaster
2,FBbt:00000001,AnatomicalEntity_AnatomicalEntity,FBbt:00100313,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,Flybase_ID,Flybase_ID,organism,multicellular structure,D.melanogaster
3,FBbt:00000002,AnatomicalEntity_AnatomicalEntity,FBbt:00057001,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,Flybase_ID,Flybase_ID,tagma,anterior-posterior subdivision of organism,D.melanogaster
4,FBbt:00000002,AnatomicalEntity_AnatomicalEntity,FBbt:00000001,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,Flybase_ID,Flybase_ID,tagma,organism,D.melanogaster
...,...,...,...,...,...,...,...,...,...,...,...,...,...
131948,FBbt:20011361,AnatomicalEntity_AnatomicalEntity,FBbt:00003982,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,Flybase_ID,Flybase_ID,descending neuron of the posterior brain DNp70,antennal mechanosensory and motor center,D.melanogaster
131949,FBbt:20011361,AnatomicalEntity_AnatomicalEntity,FBbt:00014013,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,Flybase_ID,Flybase_ID,descending neuron of the posterior brain DNp70,adult gnathal ganglion,D.melanogaster
131950,FBbt:20011361,AnatomicalEntity_AnatomicalEntity,FBbt:00040042,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,Flybase_ID,Flybase_ID,descending neuron of the posterior brain DNp70,posterior ventrolateral protocerebrum,D.melanogaster
131951,FBbt:20011361,AnatomicalEntity_AnatomicalEntity,FBbt:00047139,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,Flybase_ID,Flybase_ID,descending neuron of the posterior brain DNp70,adult leg neuropil,D.melanogaster
131952,FBbt:20011361,AnatomicalEntity_AnatomicalEntity,FBbt:00047174,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,Flybase_ID,Flybase_ID,descending neuron of the posterior brain DNp70,lower tectulum,D.melanogaster

# Sanity Check — Distinct Values

In [23]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'AnatomicalEntity_AnatomicalEntity'}
head_type           : {'AnatomicalEntity'}
tail_type           : {'AnatomicalEntity'}
relation_type       : {'subclass_of', 'related_to'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'Flybase_ID'}
tail_id_is          : {'Flybase_ID'}

In [24]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 131,953 remaining

# NaN Audit (pre-dedup)

In [25]:
true_nan   = final_df.isna().sum()
genDR_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type             0                  0               0
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0
species                   0                  0               0

# Deduplication

In [26]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 131,953  |  After dedup: 131,928

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name
0,FBbt:00000000,AnatomicalEntity_AnatomicalEntity,FBbt:00000110,AnatomicalEntity,related_to,AnatomicalEntity,Monarch_KG,Generalised,Flybase_ID,Flybase_ID,germ layer derivative,germ layer
1,FBbt:00000000,AnatomicalEntity_AnatomicalEntity,FBbt:10000000,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,Flybase_ID,Flybase_ID,germ layer derivative,anatomical entity
2,FBbt:00000001,AnatomicalEntity_AnatomicalEntity,FBbt:00100313,AnatomicalEntity,subclass_of,AnatomicalEntity,Monarch_KG,Generalised,Flybase_ID,Flybase_ID,organism,multicellular structure

In [27]:
true_nan   = final_df_dedup.isna().sum()
genDR_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type             0                  0               0
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0

In [28]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    131928
Name: count, dtype: int64

In [29]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    131928
Name: count, dtype: int64

In [30]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 131,928 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_anatomy_anatomy/Drosophila_anatomy_anatomy.csv

In [15]:
#