In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Drosophila_mirna_gene
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_mirna_gene/Drosophila_mirna_gene.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Drosophila_mirna_gene’: File exists

In [4]:
#

In [5]:
droso = pd.read_csv(
    f'{BASE_DIR}data_collection/databases_for_mapping/ncbi/Drosophila_melanogaster.gene_info',
    sep='\t',)
droso["LocusTag"] = droso["LocusTag"].str.replace("Dmel_", "", regex=False)

droso_symbol2Locus_dict = dict(zip(droso['Symbol'], droso['LocusTag']))
droso
droso_symbol2Locus_dict

{'CG3038': 'CG3038',
 'G9a': 'CG2995',
 'CG13377': 'CG13377',
 'cin': 'CG2945',
 'ewg': 'CG3114',
 'CG13375': 'CG13375',
 'CG12470': 'CG12470',
 'Or1a': 'CG17885',
 'CG3777': 'CG3777',
 'y': 'CG3757',
 'ac': 'CG3796',
 'sc': 'CG3827',
 'l(1)sc': 'CG3839',
 'Pgcl': 'CG13374',
 'ase': 'CG3258',
 'Cyp4g1': 'CG3972',
 'CG13373': 'CG13373',
 'CG3176': 'CG3176',
 'CG18273': 'CG18273',
 'CG3156': 'CG3156',
 'CG17896': 'CG17896',
 'CG17778': 'CG17778',
 'svr': 'CG4122',
 'elav': 'CG4262',
 'CG4293': 'CG4293',
 'Appl': 'CG7727',
 'vnd': 'CG6172',
 'spdi': 'CG13366',
 'CG13365': 'CG13365',
 'Vsp37A': 'CG17828',
 'CG13369': 'CG13369',
 'RpL36': 'CG7622',
 'Mybbp1A': 'CG6189',
 'Dredd': 'CG7486',
 'su(sable)': 'CG6222',
 'CG13367': 'CG13367',
 'Roc1a': 'CG16982',
 'Hmt4-20': 'CG13363',
 'SkpA': 'CG16983',
 'sdk': 'CG5227',
 'CG13362': 'CG13362',
 'CG13361': 'CG13361',
 'CG5254': 'CG5254',
 'CG5273': 'CG5273',
 'RpL22': 'CG7434',
 'fz3': 'CG16785',
 'tw': 'CG12311',
 'CG13360': 'CG13360',
 'CG16989': 'CG16989',
 'Rbf': 'CG7413',
 'CG13359': 'CG13359',
 'CG13358': 'CG13358',
 'Sec22': 'CG7359',
 'CG43867': 'CG43867',
 'CG14635': 'CG14635',
 'CG11664': 'CG11664',
 'CG11663': 'CG11663',
 'Lztr1': 'CG3711',
 'MED22': 'CG3034',
 'CG3708': 'CG3708',
 'TRAM': 'CG11642',
 'CG3704': 'CG3704',
 'mus81': 'CG3026',
 'CG3703': 'CG3703',
 'CG3699': 'CG3699',
 'CG3690': 'CG3690',
 'TfIIA-S-2': 'CG11639',
 'CG14631': 'CG14631',
 'CG11638': 'CG11638',
 'Cdc45': 'CG3658',
 'su(w[a])': 'CG3019',
 'CG14629': 'CG14629',
 'CG3655': 'CG3655',
 'CG14628': 'CG14628',
 'eIF4E7': 'CG32859',
 'CG11378': 'CG11378',
 'CG11384': 'CG11384',
 'CG11379': 'CG11379',
 'CG14627': 'CG14627',
 'CG14626': 'CG14626',
 'CG11380': 'CG11380',
 'CG14625': 'CG14625',
 'CG11381': 'CG11381',
 'CG14624': 'CG14624',
 'CG11382': 'CG11382',
 'CG11398': 'CG11398',
 'CG3638': 'CG3638',
 'CG11403': 'CG11403',
 'CG32812': 'CG32812',
 'DAAM': 'CG14622',
 'CG11409': 'CG11409',
 'Naa30A': 'CG11412',
 'Tsp2A': 'CG11415',
 'MTPAP': 'CG11418',
 'CG12773': 'CG12773',
 'CG11417': 'CG11417',
 'png': 'CG11420',
 'CG14770': 'CG14770',
 'ssx': 'CG3056',
 'CG32813': 'CG32813',
 'Rilpl': 'CG11448',
 'Gr2a': 'CG18531',
 'CG14785': 'CG14785',
 'Lrpprc2': 'CG14786',
 'CG14787': 'CG14787',
 'Ns3': 'CG14788',
 'O-fut2': 'CG14789',
 'CG14777': 'CG14777',
 'CG14778': 'CG14778',
 'pck': 'CG14779',
 'CG14780': 'CG14780',
 'Rab27': 'CG14791',
 'mei-38': 'CG14781',
 'rush': 'CG14782',
 'sta': 'CG14792',
 'Nmdar2': 'CG33513',
 'CG14795': 'CG14795',
 'inc': 'CG32810',
 'Mur2B': 'CG14796',
 'dor': 'CG3093',
 'CG3740': 'CG3740',
 'hfw': 'CG3095',
 'CG32809': 'CG32809',
 'CG14797': 'CG14797',
 'b6': 'CG3100',
 'CR14798': 'CR14798',
 'a6': 'CG3771',
 'CG3795': 'CG3795',
 'Scgdelta': 'CG14808',
 'Adar': 'CG12598',
 'CG14810': 'CG14810',
 'CG14811': 'CG14811',
 'prage': 'CG42666',
 'Lamtor5': 'CG14812',
 'Gcna': 'CG14814',
 'MED18': 'CG14802',
 'Pex5': 'CG14815',
 'CG14803': 'CG14803',
 'Pgam5': 'CG14816',
 'Vps26': 'CG14804',
 'CG14817': 'CG14817',
 'CG14805': 'CG14805',
 'CG14818': 'CG14818',
 'Coa8': 'CG14806',
 'trr': 'CG3848',
 'mRpL16': 'CG3109',
 'arm': 'CG11579',
 'CG32801': 'CG32801',
 'mip130': 'CG3480',
 'Edem1': 'CG3810',
 'Rbcn-3B': 'CG17766',
 'eIF2Bepsilon': 'CG3806',
 'Ocrl': 'CG3573',
 'CG11596': 'CG11596',
 'CG3587': 'CG3587',
 'Hr4': 'CG43934',
 'PIG-K': 'CG4406',
 'usp': 'CG4380',
 'Actn': 'CG4376',
 'CG4325': 'CG4325',
 'moody': 'CG4322',
 'CG4313': 'CG4313',
 'Sik2': 'CG4290',
 'CG4281': 'CG4281',
 'CG14054': 'CG14054',
 'CG4194': 'CG4194',
 'CG4199': 'CG4199',
 'Rtca': 'CG4061',
 'CG4045': 'CG4045',
 'CG4025': 'CG4025',
 'CG16903': 'CG16903',
 'Unc-76': 'CG3981',
 'ph-p': 'CG18412',
 'D2hgdh': 'CG3835',
 'Pgd': 'CG3724',
 'bcn92': 'CG3717',
 'wapl': 'CG3707',
 'Cyp4d1': 'CG3656',
 'CG3630': 'CG3630',
 'ND-B14.5A': 'CG3621',
 'Cyp4d2': 'CG3466',
 'Cyp4ae1': 'CG10755',
 'pn': 'CG3461',
 'Nmd3': 'CG3460',
 'CG3457': 'CG3457',
 'CG14053': 'CG14053',
 'Mct1': 'CG3456',
 'SmydA-8': 'CG33548',
 'Vinc': 'CG3299',
 'CG14052': 'CG14052',
 'pcx': 'CG3443',
 'kz': 'CG3228',
 'Or2a': 'CG3206',
 'crn': 'CG3193',
 'CG3191': 'CG3191',
 'CG3091': 'CG3091',
 'CG3078': 'CG3078',
 'temp': 'CG3073',
 'CG3071': 'CG3071',
 'CG2924': 'CG2924',
 'Grp170': 'CG2918',
 'CG2865': 'CG2865',
 'CG14050': 'CG14050',
 'CG2854': 'CG2854',
 'Ilp6': 'CG14049',
 'Raf': 'CG2845',
 'mRpL14': 'CG14048',
 'PsGEF': 'CG43947',
 'CG12496': 'CG12496',
 'gt': 'CG7952',
 'tko': 'CG7925',
 'boi': 'CG32796',
 'z': 'CG7803',
 'Pdfr': 'CG13758',
 'Vha36-3': 'CG8310',
 'AANATL7': 'CG13759',
 'CG13760': 'CG13760',
 'egh': 'CG9659',
 'Klp3A': 'CG8590',
 'eIF3g1': 'CG8636',
 'Tsp3A': 'CG10742',
 'Seipin': 'CG9904',
 'brv3': 'CG13762',
 'Pi4KIIIalpha': 'CG10260',
 'sgg': 'CG2621',
 'HLH3B': 'CG2655',
 'CG2652': 'CG2652',
 'per': 'CG2647',
 'dyw': 'CG2650',
 'Spg7': 'CG2658',
 'Lint-O': 'CG2662',
 'Ugalt': 'CG2675',
 'eIF2Bbeta': 'CG2677',
 'CG2680': 'CG2680',
 'CG2681': 'CG2681',
 'CG2685': 'CG2685',
 'CG2694': 'CG2694',
 'CG2701': 'CG2701',
 'fs(1)Yb': 'CG2706',
 'fs(1)Ya': 'CG2707',
 'vilya': 'CG2709',
 'dwg': 'CG2711',
 'ttm50': 'CG2713',
 'CG2712': 'CG2712',
 'crm': 'CG2714',
 'Syx4': 'CG2715',
 'CG32795': 'CG32795',
 'w': 'CG2759',
 'CG12498': 'CG12498',
 'CG14416': 'CG14416',
 'CG14417': 'CG14417',
 'CG14418': 'CG14418',
 'CG14419': 'CG14419',
 'CG3526': 'CG3526',
 'CG3588': 'CG3588',
 'CG14424': 'CG14424',
 'CG32793': 'CG32793',
 'CG3592': 'CG3592',
 'CG3598': 'CG3598',
 'CG14420': 'CG14420',
 'CG14421': 'CG14421',
 'CG14422': 'CG14422',
 'CG14423': 'CG14423',
 'CG17959': 'CG17959',
 'CG3603': 'CG3603',
 'rst': 'CG4125',
 'CG4116': 'CG4116',
 'kirre': 'CG3653',
 'N': 'CG3936',
 'Fcp3C': 'CG4015',
 'CG3939': 'CG3939',
 'CG14265': 'CG14265',
 'ng2': 'CG14266',
 'ng3': 'CG10788',
 'ng1': 'CG10781',
 'ng4': 'CG10789',
 'Pig1': 'CG10790',
 'Sgs4': 'CG12181',
 'CG10793': 'CG10793',
 'dnc': 'CG32498',
 'Myc': 'CG10798',
 'CG12535': 'CG12535',
 'CG14269': 'CG14269',
 'CG16782': 'CG16782',
 'CG10801': 'CG10801',
 'CG16781': 'CG16781',
 'CG12206': 'CG12206',
 'CG10804': 'CG10804',
 'CG10802': 'CG10802',
 'CG14270': 'CG14270',
 'CG10803': 'CG10803',
 'Gas8': 'CG14271',
 'DIP-alpha': 'CG32791',
 'CG13021': 'CG13021',
 'CG2875': 'CG2875',
 'Ilp7': 'CG13317',
 'Parg': 'CG2864',
 'Mnt': 'CG13316',
 'Rala': 'CG2849',
 'HIP-R': 'CG2947',
 'fd3F': 'CG44123',
 'CG2901': 'CG2901',
 'ec': 'CG2904',
 'yin': 'CG44402',
 'CG2930': 'CG2930',
 'VhaAC39-1': 'CG2934',
 'CG15239': 'CG15239',
 'CG42541': 'CG42541',
 'CG2938': 'CG2938',
 'Glos': 'CG2941',
 'Vap33': 'CG5014',
 'lva': 'CG6450',
 'CG6428': 'CG6428',
 'CG6414': 'CG6414',
 'CG43689': 'CG43689',
 'Cmtr1': 'CG6379',
 'CG15375': 'CG15375',
 'Xpac': 'CG6358',
 'brn': 'CG4934',
 'cib': 'CG4944',
 'dgt4': 'CG4865',
 'Tip60': 'CG6121',
 'tyf': 'CG4857',
 'Fas2': 'CG3665',
 'CG15571': 'CG15571',
 'CG15570': 'CG15570',
 'Femcoat': 'CG15573',
 'Muc4B': 'CG32774',
 'CG15576': 'CG15576',
 'CG12691': 'CG12691',
 'CG15572': 'CG15572',
 'CG12692': 'CG12692',
 'mei-9': 'CG3697',
 'NO66': 'CG2982',
 'CG12693': 'CG12693',
 'norpA': 'CG3620',
 'CG3626': 'CG3626',
 'bi': 'CG3578',
 'CG3556': 'CG3556',
 'rb': 'CG11427',
 'CHOp24': 'CG3564',
 'CG3568': 'CG3568',
 'Usf': 'CG17592',
 'CG15912': 'CG15912',
 'CG11436': 'CG11436',
 'CG3527': 'CG3527',
 'CG11444': 'CG11444',
 'CG3546': 'CG3546',
 'CG12684': 'CG12684',
 'peb': 'CG12212',
 'Alms1b': 'CG12184',
 'Alms1a': 'CG12179',
 'pon': 'CG3346',
 'CG3081': 'CG3081',
 'CG3062': 'CG3062',
 'HLH4C': 'CG3052',
 'mRpL30': 'CG7038',
 'Torsin': 'CG3024',
 'CG15473': 'CG15473',
 'CG3009': 'CG3009',
 'Pp2C1': 'CG2984',
 'ctp': 'CG6998',
 'Pdha': 'CG7010',
 'CG7024': 'CG7024',
 'Proc-R': 'CG6986',
 'CG15472': 'CG15472',
 'Klf15': 'CG2932',
 'CG2871': 'CG2871',
 'CG15471': 'CG15471',
 'CG6978': 'CG6978',
 'CG2861': 'CG2861',
 'CG12682': 'CG12682',
 'boil': 'CG12681',
 'CG6927': 'CG6927',
 'CG32772': 'CG32772',
 'CG4041': 'CG4041',
 'Hgsnat': 'CG6903',
 'CG44774': 'CG44774',
 'Ptp4E': 'CG6899',
 'CG15468': 'CG15468',
 'CG12680': 'CG12680',
 'ovo': 'CG6824',
 'CG32767': 'CG32767',
 'Rpn13R': 'CG6789',
 'CG15465': 'CG15465',
 'CG5062': 'CG5062',
 'CG42749': 'CG42749',
 'CG3323': 'CG3323',
 'CG17764': 'CG17764',
 'Cdk7': 'CG3319',
 'snf': 'CG4528',
 'TrxT': 'CG3315',
 'dhd': 'CG4193',
 'CG4198': 'CG4198',
 'CG15930': 'CG15930',
 'Sas10': 'CG4202',
 'Rnp4F': 'CG3312',
 'Mcm3': 'CG4206',
 'CG3309': 'CG3309',
 'XRCC1': 'CG4208',
 'SK': 'CG10706',
 'NAAT1': 'CG3252',
 'Usp16-45': 'CG4165',
 'spoon': 'CG3249',
 'CG16756': 'CG16756',
 'CG15784': 'CG15784',
 'SPR': 'CG16752',
 'frma': 'CG3239',
 'CG4151': 'CG4151',
 'CG12730': 'CG12730',
 'Vsx2': 'CG33980',
 'Vsx1': 'CG4136',
 'CG34435': 'CG34435',
 'CG34434': 'CG34434',
 'RhoGAP5A': 'CG3208',
 'Mlc-c': 'CG3201',
 'Pop1': 'CG32763',
 'Sirt4': 'CG3187',
 'CG4119': 'CG4119',
 'RpL35': 'CG4111',
 'CG42449': 'CG42449',
 'PGAP1': 'CG3160',
 'CG3149': 'CG3149',
 'AdamTS-B': 'CG4096',
 'CG33080': 'CG33080',
 'Snx27': 'CG32758',
 'CG15773': 'CG15773',
 'IntS6': 'CG3125',
 'Rtel1': 'CG4078',
 'CG15772': 'CG15772',
 'lin-52': 'CG15929',
 'CG15771': 'CG15771',
 'CG3097': 'CG3097',
 'CG42264': 'CG42264',
 'CG3108': 'CG3108',
 'CG42699': 'CG42699',
 'CG15767': 'CG15767',
 'CG12239': 'CG12239',
 'Cpr5C': 'CG4052',
 'Prosbeta2R1': 'CG18341',
 'AgmNAT': 'CG15766',
 'CG15765': 'CG15765',
 'CG12729': 'CG12729',
 'CG15764': 'CG15764',
 'GAA1': 'CG3033',
 'mof': 'CG3025',
 'Usp30': 'CG3016',
 'CG16721': 'CG16721',
 'Act5C': 'CG4027',
 'CG4020': 'CG4020',
 'CG12236': 'CG12236',
 'Shmt': 'CG3011',
 'CG3726': 'CG3726',
 'CG12728': 'CG12728',
 'CG6041': 'CG6041',
 'CG6048': 'CG6048',
 'CG6067': 'CG6067',
 'CG5966': 'CG5966',
 'CG4766': 'CG4766',
 'rux': 'CG4336',
 'MCTS1': 'CG5941',
 'CG5937': 'CG5937',
 'CG5921': 'CG5921',
 'CG5928': 'CG5928',
 'Tsp5D': 'CG4690',
 'CG4666': 'CG4666',
 'CG4660': 'CG4660',
 'raptor': 'CG4320',
 'Mipp2': 'CG4317',
 'Nep1': 'CG5905',
 'Ca-alpha1T': 'CG15899',
 'vanin-like': 'CG32754',
 'Btnd': 'CG3599',
 'Efr': 'CG3774',
 'sqh': 'CG3595',
 'dtn': 'CG14446',
 'CG14445': 'CG14445',
 'Rbcn-3A': 'CG3585',
 'Spx': 'CG3780',
 'Josd': 'CG3781',
 'CG3566': 'CG3566',
 'CG11700': 'CG11700',
 'Top3beta': 'CG3458',
 'wuho': 'CG15897',
 'Rpt4': 'CG3455',
 'mldr': 'CG15896',
 'CG3815': 'CG3815',
 'CG12219': 'CG12219',
 'CG3823': 'CG3823',
 'CG15894': 'CG15894',
 'CG3842': 'CG3842',
 'CG3847': 'CG3847',
 'ND-B16.6': 'CG3446',
 'kdn': 'CG3861',
 'swa': 'CG3429',
 'Marf': 'CG3869',
 'PpV': 'CG12217',
 'CG3918': 'CG3918',
 'CG3342': 'CG3342',
 'Agxt': 'CG3926',
 'RpL7A': 'CG3314',
 'dx': 'CG3929',
 'CG34417': 'CG34417',
 'CG17717': 'CG17717',
 'Pat1': 'CG10695',
 'APC7': 'CG14444',
 'CG14443': 'CG14443',
 'pigs': 'CG3973',
 'CG3226': 'CG3226',
 'Cdc7': 'CG32742',
 'CG3224': 'CG3224',
 'Ctr1A': 'CG3977',
 'CG3198': 'CG3198',
 'Mcm6': 'CG4039',
 'ND-ASHI': 'CG3192',
 'Fum1': 'CG4094',
 'Fum2': 'CG4095',
 'Pink1': 'CG4523',
 'CG3184': 'CG3184',
 'CG14442': 'CG14442',
 'CG14440': 'CG14440',
 'CG14441': 'CG14441',
 'CG3168': 'CG3168',
 'RpL17': 'CG3203',
 'CG14439': 'CG14439',
 'sov': 'CG14438',
 'shf': 'CG3135',
 'C3G': 'CG42328',
 'pod1': 'CG4532',
 'iav': 'CG4536',
 'Nf-YC': 'CG3075',
 'xit': 'CG4542',
 'Atx-1': 'CG4547',
 'nonC': 'CG32743',
 'mAChR-C': 'CG12796',
 'CG14435': 'CG14435',
 'Tmf': 'CG4557',
 'Cht11': 'CG3044',
 'CG4558': 'CG4558',
 'CG14434': 'CG14434',
 'Setd3': 'CG32732',
 'CG14431': 'CG14431',
 'CG4586': 'CG4586',
 'CG3040': 'CG3040',
 'bou': 'CG14430',
 'Inx6': 'CG17063',
 'Inx2': 'CG4590',
 'cm': 'CG3035',
 'CG3032': 'CG3032',
 'CG4593': 'CG4593',
 'CG12541': 'CG12541',
 'CG14427': 'CG14427',
 'nullo': 'CG14426',
 'CG4607': 'CG4607',
 'CG4615': 'CG4615',
 'CG4617': 'CG4617',
 'CG8300': 'CG8300',
 'fz4': 'CG4626',
 'Cph': 'CG9650',
 'CG1958': 'CG1958',
 'CG1677': 'CG1677',
 'CG2059': 'CG2059',
 'unc-119': 'CG1659',
 'brk': 'CG9653',
 'Atg5': 'CG1643',
 'Dok': 'CG2079',
 'Acsf3': 'CG18155',
 'CBP': 'CG1435',
 'CG15034': 'CG15034',
 'CG1999': 'CG1999',
 'CheA7a': 'CG15033',
 'CG15035': 'CG15035',
 'rumpel': 'CG9657',
 'CG11369': 'CG11369',
 'CG12689': 'CG12689',
 'CHES-1-like': 'CG12690',
 'CG15478': 'CG15478',
 'Hira': 'CG12153',
 'NELF-B': 'CG32721',
 'CG12155': 'CG12155',
 'Pdp': 'CG12151',
 'Rab39': 'CG12156',
 'Ir7a': 'CG12663',
 'CARPA': 'CG1402',
 'CG10920': 'CG10920',
 'CG1409': 'CG1409',
 'Ir7b': 'CG15326',
 'dec': 'CG2175',
 'Ir7c': 'CG15324',
 'Ir7g': 'CG15325',
 'Acat1': 'CG10932',
 'Nek2': 'CG17256',
 'ND-MNLL': 'CG18624',
 'p115': 'CG1422',
 'RpS6': 'CG10944',
 'bys': 'CG1430',
 'dpr14': 'CG10946',
 'spidey': 'CG1444',
 'snz': 'CG1514',
 'hdm': 'CG15329',
 'Ykt6': 'CG1515',
 'mahe': 'CG10777',
 'Dhdds': 'CG10778',
 'orion': 'CG2206',
 'Ubr3': 'CG42593',
 'CG15332': 'CG15332',
 'CG15330': 'CG15330',
 'sws': 'CG2212',
 'sn': 'CG32858',
 'Tbh': 'CG1543',
 'CG15333': 'CG15333',
 'CG2233': 'CG2233',
 'fs(1)h': 'CG2252',
 'Upf2': 'CG2253',
 'CG1571': 'CG1571',
 'Ldsdh1': 'CG2254',
 'CG2256': 'CG2256',
 'UbcE2H': 'CG2257',
 'CG2258': 'CG2258',
 'CG1575': 'CG1575',
 'CG2260': 'CG2260',
 'cyr': 'CG15335',
 'CG2116': 'CG2116',
 'CG10958': 'CG10958',
 'CG2120': 'CG2120',
 'Smox': 'CG2262',
 'CG17982': 'CG17982',
 'alpha-PheRS': 'CG2263',
 'CG2129': 'CG2129',
 'CG15336': 'CG15336',
 'CG10959': 'CG10959',
 'Gbeta5': 'CG10763',
 'CG18262': 'CG18262',
 'Traf6': 'CG10961',
 'GIIIspla2': 'CG1583',
 'CG15337': 'CG15337',
 'CG10761': 'CG10761',
 'Or7a': 'CG10759',
 'CG2278': 'CG2278',
 'CG2147': 'CG2147',
 'Trxr1': 'CG2151',
 'sni': 'CG10964',
 'ND-75': 'CG2286',
 'CG1632': 'CG1632',
 'Corp': 'CG10965',
 'CG15343': 'CG15343',
 'CG1636': 'CG1636',
 'nAChRalpha3': 'CG2302',
 'CG1387': 'CG1387',
 'CG10555': 'CG10555',
 'PIG-T': 'CG11190',
 'Trf2': 'CG18009',
 'Miga': 'CG12125',
 'CG1440': 'CG1440',
 'CG12123': 'CG12123',
 'org-1': 'CG11202',
 'CG15347': 'CG15347',
 'Es2': 'CG1474',
 'Sptr': 'CG12117',
 'CG12116': 'CG12116',
 'Cp7Fb': 'CG15350',
 'Cp7Fc': 'CG15351',
 'Cp36': 'CG1478',
 'Cp38': 'CG11213',
 'otu': 'CG12743',
 'PIP82': 'CG11219',
 'Nrg': 'CG1634',
 'IntS4': 'CG12113',
 'CG12112': 'CG12112',
 'Trf4-1': 'CG11265',
 'CG12111': 'CG12111',
 'spirit': 'CG2056',
 'CG12065': 'CG12065',
 'CG12081': 'CG12081',
 'Crag': 'CG12737',
 'Caf1-180': 'CG12109',
 'oc': 'CG12154',
 'Rubicon': 'CG12772',
 'CAH3': 'CG11284',
 'Ppt1': 'CG12108',
 'Ogg1': 'CG1795',
 'CG11294': 'CG11294',
 'Hexo2': 'CG1787',
 'CG2004': 'CG2004',
 'CG1785': 'CG1785',
 'l(1)G0020': 'CG1994',
 'CG1789': 'CG1789',
 'Lim1': 'CG11354',
 'CG12075': 'CG12075',
 'Moe': 'CG10701',
 'Uros1': 'CG1885',
 'Rbm13': 'CG10648',
 'CG12661': 'CG12661',
 'CG10962': 'CG10962',
 'CG12662': 'CG12662',
 'rdgA': 'CG42667',
 'CG15365': 'CG15365',
 'CG10970': 'CG10970',
 'CG44325': 'CG44325',
 'CG7246': 'CG7246',
 'HP1b': 'CG7041',
 'APC4': 'CG32707',
 'CG6999': 'CG6999',
 'CCT2': 'CG7033',
 'CG7766': 'CG7766',
 'Bx42': 'CG8264',
 'Arfrp1': 'CG7039',
 'AP-1gamma': 'CG9113',
 'fend': 'CG12664',
 'CG7065': 'CG7065',
 'fh': 'CG8971',
 'Bap111': 'CG7055',
 'His3.3B': 'CG8989',
 'Ost48': 'CG9022',
 'Zpr1': 'CG9060',
 'CG12115': 'CG12115',
 'CG12057': 'CG12057',
 'CG12056': 'CG12056',
 'CG12106': 'CG12106',
 'CG12118': 'CG12118',
 'su(r)': 'CG2194',
 'SmydA-9': 'CG12119',
 'Obp8a': 'CG12665',
 'CG15368': 'CG15368',
 'CG15369': 'CG15369',
 't': 'CG12120',
 'CG15370': 'CG15370',
 'Gr8a': 'CG15371',
 'CG12121': 'CG12121',
 'Ir8a': 'CG32704',
 'mxc': 'CG12124',
 'Dsor1': 'CG15793',
 'CG17754': 'CG17754',
 'ric8a': 'CG15797',
 'Erk7': 'CG32703',
 'CG17440': 'CG17440',
 'Cfp1': 'CG17446',
 'Aladin': 'CG16892',
 'lz': 'CG1689',
 'Zdhhc8': 'CG34449',
 'BCL7-like': 'CG17252',
 'CG32700': 'CG32700',
 'RpS28b': 'CG2998',
 'CG15317': 'CG15317',
 'LPCAT': 'CG32699',
 'Gga': 'CG3002',
 'Lst8': 'CG3004',
 'LysRS': 'CG12141',
 'Hecw': 'CG42797',
 'Ptpmeg2': 'CG32697',
 'CG3106': 'CG3106',
 'btd': 'CG12653',
 'Sp1': 'CG1343',
 'CG1354': 'CG1354',
 'CARPB': 'CG32698',
 'Ser7': 'CG2045',
 'CG32695': 'CG32695',
 'CG15247': 'CG15247',
 'CG1468': 'CG1468',
 'CG9686': 'CG9686',
 'CG9689': 'CG9689',
 'CG9691': 'CG9691',
 'CG15249': 'CG15249',
 'CG1986': 'CG1986',
 'Idgf4': 'CG1780',
 'CG1791': 'CG1791',
 'CG1889': 'CG1889',
 'CG43386': 'CG43386',
 'CG15252': 'CG15252',
 'CG32694': 'CG32694',
 'Dna2': 'CG2990',
 'Cht6': 'CG43374',
 'Yp2': 'CG2979',
 'Yp1': 'CG2985',
 'CG15312': 'CG15312',
 'ZAP3': 'CG32685',
 'CG2972': 'CG2972',
 'Naxe': 'CG2974',
 'RhoU': 'CG34104',
 'CG12645': 'CG12645',
 'CG43902': 'CG43902',
 'Ypel': 'CG15309',
 'ATPsyndelta': 'CG2968',
 'CG2962': 'CG2962',
 'CG34408': 'CG34408',
 'CG2961': 'CG2961',
 'Hk': 'CG43388',
 'alpha-Man-Ia': 'CG42275',
 'CG2909': 'CG2909',
 'Gip': 'CG2227',
 'CG15306': 'CG15306',
 'CG43740': 'CG43740',
 'l(1)G0289': 'CG2221',
 'CG17841': 'CG17841',
 'CG2898': 'CG2898',
 'Psf3': 'CG2222',
 'CG32683': 'CG32683',
 'RabX2': 'CG2885',
 'CG12640': 'CG12640',
 'Or9a': 'CG15302',
 'nocte': 'CG17255',
 'CG2889': 'CG2889',
 'CG2887': 'CG2887',
 'PPP4R2r': 'CG2890',
 'CG32687': 'CG32687',
 'CG15296': 'CG15296',
 'spri': 'CG34414',
 'Hmr': 'CG1619',
 'CG2124': 'CG2124',
 'CG1628': 'CG1628',
 'CG43347': 'CG43347',
 'Rab9Db': 'CG9807',
 'CG9806': 'CG9806',
 'CG2111': 'CG2111',
 'CG12637': 'CG12637',
 'X11Lbeta': 'CG32677',
 'BTBD9': 'CG1826',
 'Atg8a': 'CG32672',
 'Rph': 'CG11556',
 'stx': 'CG32676',
 'CG15211': 'CG15211',
 'sesB': 'CG16944',
 'Ant2': 'CG1683',
 'Imp': 'CG1691',
 'CG15209': 'CG15209',
 'Pgls': 'CG17333',
 'CG2202': 'CG2202',
 'feo': 'CG11207',
 'sofe': 'CG1655',
 'CG2186': 'CG2186',
 'CG2157': 'CG2157',
 'CG1637': 'CG1637',
 'Ork1': 'CG1615',
 'CG1582': 'CG1582',
 'CG15208': 'CG15208',
 'CG43901': 'CG43901',
 'v': 'CG2155',
 'CG2145': 'CG2145',
 'Myo10A': 'CG43657',
 'Rab9Fb': 'CG32670',
 'C901': 'CG1567',
 'vex': 'CG42339',
 'SmydA-4': 'CG11160',
 'CG1552': 'CG1552',
 'CG1545': 'CG1545',
 'CG1537': 'CG1537',
 'CG15203': 'CG15203',
 'sev': 'CG18085',
 'Vago': 'CG2081',
 'CG2076': 'CG2076',
 'CG2061': 'CG2061',
 'CG42249': 'CG42249',
 'Hsp60A': 'CG12101',
 'CG11122': 'CG11122',
 'Rpt3': 'CG16916',
 'Klp10A': 'CG1453',
 'CDK2AP1': 'CG18292',
 'CG15199': 'CG15199',
 'CG15202': 'CG15202',
 'CG15201': 'CG15201',
 'Lint-1': 'CG1908',
 'rtv': 'CG1397',
 'Dlic': 'CG1938',
 'Antdh': 'CG1386',
 'CG1394': 'CG1394',
 'CG15200': 'CG15200',
 'CG11106': 'CG11106',
 'CG44422': 'CG44422',
 'CG15198': 'CG15198',
 'Ir10a': 'CG34143',
 'sisA': 'CG1641',
 'l(1)10Bb': 'CG1639',
 'Gapvd1': 'CG1657',
 'Kap3': 'CG11759',
 'CG34348': 'CG34348',
 'GCS1': 'CG1597',
 'CG11756': 'CG11756',
 'CG1738': 'CG1738',
 'NdufV3': 'CG11752',
 'CG1737': 'CG1737',
 'dsh': 'CG18361',
 'Pa1': 'CG11750',
 'hop': 'CG1594',
 'Tim8': 'CG1728',
 'dlg1': 'CG1725',
 'CG15196': 'CG15196',
 'Gr10b': 'CG12622',
 'Or10a': 'CG17867',
 'Gs2': 'CG1743',
 'Evi5': 'CG11727',
 'Sk1': 'CG1747',
 'HP5': 'CG1745',
 'CG43155': 'CG43155',
 'Cyp4g15': 'CG11715',
 'Uba5': 'CG1749',
 'Spase25': 'CG1751',
 'Drak': 'CG32666',
 'CG1572': 'CG1572',
 'PGRP-SA': 'CG11709',
 'Polr2A': 'CG1554',
 'CG11699': 'CG11699',
 'Kmn1': 'CG1558',
 'Reepl1': 'CG11697',
 'CG11696': 'CG11696',
 'CG11695': 'CG11695',
 'nod': 'CG1763',
 'pkm': 'CG1561',
 'rho-4': 'CG1697',
 'CG2533': 'CG2533',
 'CG2247': 'CG2247',
 'CG1703': 'CG1703',
 'RPA3': 'CG15220',
 'Met': 'CG1705',
 'Ptp10D': 'CG1817',
 'Vlet': 'CG2371',
 'bif': 'CG1822',
 'PhKgamma': 'CG1830',
 'CG2444': 'CG2444',
 'FucT6': 'CG2448',
 'Amun': 'CG2446',
 'prtp': 'CG1837',
 'Tango10': 'CG1841',
 'inaF-D': 'CG42563',
 'CG15221': 'CG15221',
 'CG9360': 'CG9360',
 'dy': 'CG9355',
 'Karl': 'CG4139',
 'CkIIbeta': 'CG15224',
 'Hsc70-3': 'CG4147',
 'CG1578': 'CG1578',
 'rudhira': 'CG43154',
 'CG15741': 'CG15741',
 'Cyp28c1': 'CG1895',
 'CG15740': 'CG15740',
 'p24-1': 'CG1967',
 'CG10347': 'CG10347',
 'ATP7': 'CG1886',
 'Nrd1': 'CG2025',
 'CG1847': 'CG1847',
 'BORCS5': 'CG11802',
 'CG15739': 'CG15739',
 'CG10352': 'CG10352',
 'CG10353': 'CG10353',
 'SelG': 'CG1844',
 'CG1840': 'CG1840',
 'sicily': 'CG15738',
 'wisp': 'CG15737',
 'Upf1': 'CG1559',
 'pot': 'CG2467',
 'Sclp': 'CG2471',
 'Pdzd8': 'CG10362',
 'cac': 'CG43368',

# mirna

In [6]:

mirna = pd.read_csv(PROC_DIR + 'mirTARbase/dmel/miRTarBase_Mirna_Gene.csv')

mirna.columns = mirna.columns.str.lower()
mirna['tail'] = mirna['tail'].map(droso_symbol2Locus_dict).fillna(mirna['tail'])
mirna = mirna.rename(columns={'headtype': 'head_type', 'tailtype': 'tail_type'})

mirna['kg_type'] = 'Generalised'
mirna['head_type'] = 'Mirna'
mirna['kg_source'] = 'miRTarBase'
mirna['species'] = 'D.melanogaster'
mirna['tail_id_is'] = 'NCBI_ID'
mirna['head_id_is'] = 'miRTarBase_ID'
print(f"mirna: {len(mirna):,} rows")
mirna

mirna: 276 rows

,head,relation,tail,head_type,tail_type,kg_source,head_detail_name,tail_detail_name,species,kg_type,tail_id_is,head_id_is
0,dme-miR-9a-5p,Mirna_Gene,CG44425,Mirna,Gene,miRTarBase,dme-miR-9a-5p,Beadex,D.melanogaster,Generalised,NCBI_ID,miRTarBase_ID
1,dme-miR-9a-5p,Mirna_Gene,CG44425,Mirna,Gene,miRTarBase,dme-miR-9a-5p,Beadex,D.melanogaster,Generalised,NCBI_ID,miRTarBase_ID
2,dme-miR-8-3p,Mirna_Gene,CG13060,Mirna,Gene,miRTarBase,dme-miR-8-3p,uncharacterized protein,D.melanogaster,Generalised,NCBI_ID,miRTarBase_ID
3,dme-miR-8-3p,Mirna_Gene,CG8420,Mirna,Gene,miRTarBase,dme-miR-8-3p,uncharacterized protein,D.melanogaster,Generalised,NCBI_ID,miRTarBase_ID
4,dme-miR-8-3p,Mirna_Gene,CG9036,Mirna,Gene,miRTarBase,dme-miR-8-3p,Cuticular protein 56F,D.melanogaster,Generalised,NCBI_ID,miRTarBase_ID
...,...,...,...,...,...,...,...,...,...,...,...,...
271,dme-miR-92a-3p,Mirna_Gene,CG8183,Mirna,Gene,miRTarBase,dme-miR-92a-3p,Kinesin heavy chain 73,D.melanogaster,Generalised,NCBI_ID,miRTarBase_ID
272,dme-miR-310-3p,Mirna_Gene,CG5576,Mirna,Gene,miRTarBase,dme-miR-310-3p,immune deficiency,D.melanogaster,Generalised,NCBI_ID,miRTarBase_ID
273,dme-miR-311-3p,Mirna_Gene,CG5576,Mirna,Gene,miRTarBase,dme-miR-311-3p,immune deficiency,D.melanogaster,Generalised,NCBI_ID,miRTarBase_ID
274,dme-miR-312-3p,Mirna_Gene,CG5576,Mirna,Gene,miRTarBase,dme-miR-312-3p,immune deficiency,D.melanogaster,Generalised,NCBI_ID,miRTarBase_ID
275,dme-miR-313-3p,Mirna_Gene,CG5576,Mirna,Gene,miRTarBase,dme-miR-313-3p,immune deficiency,D.melanogaster,Generalised,NCBI_ID,miRTarBase_ID

In [7]:
#

# Consolidate into Unified Schem

In [8]:
# List all source DataFrames to include
source_dfs = [
    mirna
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 276

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,dme-miR-9a-5p,Mirna_Gene,CG44425,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dme-miR-9a-5p,Beadex,D.melanogaster
1,dme-miR-9a-5p,Mirna_Gene,CG44425,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dme-miR-9a-5p,Beadex,D.melanogaster
2,dme-miR-8-3p,Mirna_Gene,CG13060,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dme-miR-8-3p,uncharacterized protein,D.melanogaster
3,dme-miR-8-3p,Mirna_Gene,CG8420,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dme-miR-8-3p,uncharacterized protein,D.melanogaster
4,dme-miR-8-3p,Mirna_Gene,CG9036,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dme-miR-8-3p,Cuticular protein 56F,D.melanogaster
...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,dme-miR-92a-3p,Mirna_Gene,CG8183,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dme-miR-92a-3p,Kinesin heavy chain 73,D.melanogaster
272,dme-miR-310-3p,Mirna_Gene,CG5576,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dme-miR-310-3p,immune deficiency,D.melanogaster
273,dme-miR-311-3p,Mirna_Gene,CG5576,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dme-miR-311-3p,immune deficiency,D.melanogaster
274,dme-miR-312-3p,Mirna_Gene,CG5576,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dme-miR-312-3p,immune deficiency,D.melanogaster
275,dme-miR-313-3p,Mirna_Gene,CG5576,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dme-miR-313-3p,immune deficiency,D.melanogaster

# Sanity Check — Distinct Values

In [9]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Mirna_Gene'}
head_type           : {'Mirna'}
tail_type           : {'Gene'}
relation_type       : {None}
kg_source           : {'miRTarBase'}
head_id_is          : {'miRTarBase_ID'}
tail_id_is          : {'NCBI_ID'}

In [10]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 276 remaining

# NaN Audit (pre-dedup)

In [11]:
true_nan   = final_df.isna().sum()
genDR_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type           276                  0             276
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0
species                   0                  0               0

# Deduplication

In [12]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 276  |  After dedup: 133

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name
0,dme-let-7-5p,Mirna_Gene,CG43860,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dme-let-7-5p,abrupt
1,dme-miR-1-3p,Mirna_Gene,CG10596,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dme-miR-1-3p,Msr-110
2,dme-miR-1-3p,Mirna_Gene,CG10624,Mirna,None,Gene,miRTarBase,Generalised,miRTarBase_ID,NCBI_ID,dme-miR-1-3p,sinuous

In [13]:
true_nan   = final_df_dedup.isna().sum()
genDR_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type           133                  0             133
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0

In [14]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'miRTarBase'} kg_source
miRTarBase    133
Name: count, dtype: int64

In [15]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    133
Name: count, dtype: int64

In [16]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 133 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_mirna_gene/Drosophila_mirna_gene.csv

In [17]:
#