In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila

# Databases Having Gene Phenotype relation of Drosophila

In [17]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Drosophila_protein_tissue
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_protein_tissue/Drosophila_protein_tissue.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Drosophila_protein_tissue’: File exists

# AgeAnnOMO

In [18]:
ageanno = pd.read_csv(PROC_DIR + 'ageanno_processed_mo/AgeAnnoMO_Droso_Protein_Tissue.csv')
ageanno.columns = ageanno.columns.str.lower()
ageanno['relation'] = 'Protein_Tissue'
ageanno['kg_type'] = 'Aging'
ageanno['species'] = 'Drosophila melanogaster'

print(f"ageanno: {len(ageanno):,} rows")
ageanno

ageanno: 170 rows

,head,relation,tail,head_type,tail_type,head_id_is,tail_id_is,relation_source,species,tail_detail_name,head_detail_name,kg_type
0,P41572,Protein_Tissue,BTO:0000142,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Drosophila melanogaster,brain,"6-phosphogluconate dehydrogenase, decarboxylating",Aging
1,Q9VSA3,Protein_Tissue,BTO:0000142,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Drosophila melanogaster,brain,"Medium-chain specific acyl-CoA dehydrogenase, ...",Aging
2,Q9VLJ6,Protein_Tissue,BTO:0000142,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Drosophila melanogaster,brain,Angiotensin-converting enzyme-related protein,Aging
3,Q7KML2,Protein_Tissue,BTO:0000142,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Drosophila melanogaster,brain,Acyl-coenzyme A oxidase 1 {ECO:0000305},Aging
4,P02574,Protein_Tissue,BTO:0000142,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Drosophila melanogaster,brain,"Actin, larval muscle",Aging
...,...,...,...,...,...,...,...,...,...,...,...,...
165,Q9VTF9,Protein_Tissue,BTO:0000142,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Drosophila melanogaster,brain,Ubiquitin fusion degradation protein 1 homolog...,Aging
166,Q9W4P5,Protein_Tissue,BTO:0000142,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Drosophila melanogaster,brain,V-type proton ATPase subunit d 1,Aging
167,Q9V7D2,Protein_Tissue,BTO:0000142,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Drosophila melanogaster,brain,V-type proton ATPase subunit D 1,Aging
168,P54611,Protein_Tissue,BTO:0000142,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Drosophila melanogaster,brain,V-type proton ATPase subunit E,Aging
169,O46037,Protein_Tissue,BTO:0000142,Protein,Tissue,Uniprot,BTO_ID,AgeAnnoMO,Drosophila melanogaster,brain,Vinculin,Aging

In [19]:
#

# Consolidate into Unified Schem

In [20]:
# List all source DataFrames to include
source_dfs = [
    ageanno
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 170

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,P41572,Protein_Tissue,BTO:0000142,Protein,None,Tissue,None,Aging,Uniprot,BTO_ID,"6-phosphogluconate dehydrogenase, decarboxylating",brain,Drosophila melanogaster
1,Q9VSA3,Protein_Tissue,BTO:0000142,Protein,None,Tissue,None,Aging,Uniprot,BTO_ID,"Medium-chain specific acyl-CoA dehydrogenase, ...",brain,Drosophila melanogaster
2,Q9VLJ6,Protein_Tissue,BTO:0000142,Protein,None,Tissue,None,Aging,Uniprot,BTO_ID,Angiotensin-converting enzyme-related protein,brain,Drosophila melanogaster
3,Q7KML2,Protein_Tissue,BTO:0000142,Protein,None,Tissue,None,Aging,Uniprot,BTO_ID,Acyl-coenzyme A oxidase 1 {ECO:0000305},brain,Drosophila melanogaster
4,P02574,Protein_Tissue,BTO:0000142,Protein,None,Tissue,None,Aging,Uniprot,BTO_ID,"Actin, larval muscle",brain,Drosophila melanogaster
...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Q9VTF9,Protein_Tissue,BTO:0000142,Protein,None,Tissue,None,Aging,Uniprot,BTO_ID,Ubiquitin fusion degradation protein 1 homolog...,brain,Drosophila melanogaster
166,Q9W4P5,Protein_Tissue,BTO:0000142,Protein,None,Tissue,None,Aging,Uniprot,BTO_ID,V-type proton ATPase subunit d 1,brain,Drosophila melanogaster
167,Q9V7D2,Protein_Tissue,BTO:0000142,Protein,None,Tissue,None,Aging,Uniprot,BTO_ID,V-type proton ATPase subunit D 1,brain,Drosophila melanogaster
168,P54611,Protein_Tissue,BTO:0000142,Protein,None,Tissue,None,Aging,Uniprot,BTO_ID,V-type proton ATPase subunit E,brain,Drosophila melanogaster
169,O46037,Protein_Tissue,BTO:0000142,Protein,None,Tissue,None,Aging,Uniprot,BTO_ID,Vinculin,brain,Drosophila melanogaster

# Sanity Check — Distinct Values

In [21]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Protein_Tissue'}
head_type           : {'Protein'}
tail_type           : {'Tissue'}
relation_type       : {None}
kg_source           : {None}
head_id_is          : {'Uniprot'}
tail_id_is          : {'BTO_ID'}

In [22]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 170 remaining

# NaN Audit (pre-dedup)

In [23]:
true_nan   = final_df.isna().sum()
string_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           170                   0             170
tail_type                 0                   0               0
kg_source               170                   0             170
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

# Deduplication

In [24]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first',
    
    'species': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 170  |  After dedup: 170

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,A0A1F4,Protein_Tissue,BTO:0000142,Protein,None,Tissue,,Aging,Uniprot,BTO_ID,Protein eyes shut,brain,Drosophila melanogaster
1,H1UUD2,Protein_Tissue,BTO:0000142,Protein,None,Tissue,,Aging,Uniprot,BTO_ID,Ferritin heavy chain {ECO:0000303|PubMed:9266686},brain,Drosophila melanogaster
2,H8F4T6,Protein_Tissue,BTO:0000142,Protein,None,Tissue,,Aging,Uniprot,BTO_ID,"Enoyl-[acyl-carrier-protein] reductase, mitoch...",brain,Drosophila melanogaster

In [25]:
true_nan   = final_df_dedup.isna().sum()
string_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_string_count": string_nan,
    'Total_NaN_like':     true_nan + string_nan
})

                  NaN_count  'NAN'_string_count  Total_NaN_like
head                      0                   0               0
relation                  0                   0               0
tail                      0                   0               0
head_type                 0                   0               0
relation_type           170                   0             170
tail_type                 0                   0               0
kg_source                 0                   0               0
kg_type                   0                   0               0
head_id_is                0                   0               0
tail_id_is                0                   0               0
head_detail_name          0                   0               0
tail_detail_name          0                   0               0
species                   0                   0               0

In [26]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {''} kg_source
    170
Name: count, dtype: int64

In [27]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Aging'} kg_type
Aging    170
Name: count, dtype: int64

In [28]:
# ! mkdir Drosophila_protein_tissue

In [29]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 170 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_protein_tissue/Drosophila_protein_tissue.csv

In [30]:
#