In [19]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [20]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila

In [21]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Drosophila_anatomy_cellcomponent
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_anatomy_cellcomponent/Drosophila_anatomy_cellcomp.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

mkdir: cannot create directory ‘Drosophila_anatomy_cellcomponent’: File exists

In [22]:
#

# monarch

In [23]:

monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Drosophila/Droso_AnatomicalEntity_CellularComponent.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'
monarch['relation'] = 'AnatomicalEntity_CellularComponent'
monarch['head_type'] = 'AnatomicalEntity'

monarch['species'] = 'D.melanogaster'
monarch['head_id_is'] = 'FlyBase'
monarch['tail_id_is'] = 'Quick_GO'
print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 2,766 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,species,kg_type,kg_source
0,WBbt:0001001,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,infores:wbbt,AB nucleus,nucleus,Drosophila melanogaster,NaN,FlyBase,Quick_GO,D.melanogaster,Generalised,Monarch_KG
1,WBbt:0001002,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,infores:wbbt,ABa nucleus,nucleus,Drosophila melanogaster,NaN,FlyBase,Quick_GO,D.melanogaster,Generalised,Monarch_KG
2,WBbt:0001003,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,infores:wbbt,ABal nucleus,nucleus,Drosophila melanogaster,NaN,FlyBase,Quick_GO,D.melanogaster,Generalised,Monarch_KG
3,WBbt:0001004,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,infores:wbbt,ABala nucleus,nucleus,Drosophila melanogaster,NaN,FlyBase,Quick_GO,D.melanogaster,Generalised,Monarch_KG
4,WBbt:0001005,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,infores:wbbt,ABalaa nucleus,nucleus,Drosophila melanogaster,NaN,FlyBase,Quick_GO,D.melanogaster,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,WBbt:0008067,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,infores:wbbt,Z1.a nucleus,nucleus,Drosophila melanogaster,NaN,FlyBase,Quick_GO,D.melanogaster,Generalised,Monarch_KG
2762,WBbt:0008615,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,infores:wbbt,ABplpaapapaa nucleus,nucleus,Drosophila melanogaster,NaN,FlyBase,Quick_GO,D.melanogaster,Generalised,Monarch_KG
2763,WBbt:0008616,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,infores:wbbt,ABplpaapapap nucleus,nucleus,Drosophila melanogaster,NaN,FlyBase,Quick_GO,D.melanogaster,Generalised,Monarch_KG
2764,WBbt:0008617,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,infores:wbbt,ABprpaapapap nucleus,nucleus,Drosophila melanogaster,NaN,FlyBase,Quick_GO,D.melanogaster,Generalised,Monarch_KG
2765,WBbt:0008618,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,infores:wbbt,ABprpaapapaa nucleus,nucleus,Drosophila melanogaster,NaN,FlyBase,Quick_GO,D.melanogaster,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [24]:
# List all source DataFrames to include
source_dfs = [
    monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 2,766

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,WBbt:0001001,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,Generalised,FlyBase,Quick_GO,AB nucleus,nucleus,D.melanogaster
1,WBbt:0001002,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,Generalised,FlyBase,Quick_GO,ABa nucleus,nucleus,D.melanogaster
2,WBbt:0001003,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,Generalised,FlyBase,Quick_GO,ABal nucleus,nucleus,D.melanogaster
3,WBbt:0001004,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,Generalised,FlyBase,Quick_GO,ABala nucleus,nucleus,D.melanogaster
4,WBbt:0001005,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,Generalised,FlyBase,Quick_GO,ABalaa nucleus,nucleus,D.melanogaster
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,WBbt:0008067,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,Generalised,FlyBase,Quick_GO,Z1.a nucleus,nucleus,D.melanogaster
2762,WBbt:0008615,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,Generalised,FlyBase,Quick_GO,ABplpaapapaa nucleus,nucleus,D.melanogaster
2763,WBbt:0008616,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,Generalised,FlyBase,Quick_GO,ABplpaapapap nucleus,nucleus,D.melanogaster
2764,WBbt:0008617,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,Generalised,FlyBase,Quick_GO,ABprpaapapap nucleus,nucleus,D.melanogaster
2765,WBbt:0008618,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,Generalised,FlyBase,Quick_GO,ABprpaapapaa nucleus,nucleus,D.melanogaster

# Sanity Check — Distinct Values

In [25]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'AnatomicalEntity_CellularComponent'}
head_type           : {'AnatomicalEntity'}
tail_type           : {'CellularComponent'}
relation_type       : {'subclass_of'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'FlyBase'}
tail_id_is          : {'Quick_GO'}

In [26]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 2,766 remaining

# NaN Audit (pre-dedup)

In [27]:
true_nan   = final_df.isna().sum()
genDR_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type             0                  0               0
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0
species                   0                  0               0

# Deduplication

In [28]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 2,766  |  After dedup: 2,766

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name
0,WBbt:0001001,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,Generalised,FlyBase,Quick_GO,AB nucleus,nucleus
1,WBbt:0001002,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,Generalised,FlyBase,Quick_GO,ABa nucleus,nucleus
2,WBbt:0001003,AnatomicalEntity_CellularComponent,GO:0005634,AnatomicalEntity,subclass_of,CellularComponent,Monarch_KG,Generalised,FlyBase,Quick_GO,ABal nucleus,nucleus

In [29]:
true_nan   = final_df_dedup.isna().sum()
genDR_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type             0                  0               0
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0

In [30]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    2766
Name: count, dtype: int64

In [31]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    2766
Name: count, dtype: int64

In [32]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 2,766 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_anatomy_cellcomponent/Drosophila_anatomy_cellcomp.csv

In [33]:
#