In [1]:
import pandas as pd
import numpy as np
import glob
import os
from tqdm import tqdm

In [2]:
!pwd

/storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila

In [3]:
BASE_DIR     = '/storage/Arushi/090526_EvoAge/kg_formation/'
MAPPING_DIR  = BASE_DIR + 'data_collection/databases_for_mapping/'
PROC_DIR     = BASE_DIR + 'processed_data/'

# ── Output path ───────────────────────────────────────────────────────────────
!mkdir Drosophila_gene_pathway
OUT_PATH = BASE_DIR + 'processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_gene_pathway/Drosophila_gene_pathway.csv'

# ── Required output schema ────────────────────────────────────────────────────
REQUIRED_COLS = [
    'head', 'relation', 'tail',
    'head_type', 'relation_type', 'tail_type',
    'kg_source', 'kg_type',
    'head_id_is', 'tail_id_is',
    'head_detail_name', 'tail_detail_name', 'species'
]

In [4]:
#

# monarch

In [5]:

monarch = pd.read_csv(PROC_DIR + 'Monarch/Monarch_final/Drosophila/Droso_Gene_Pathway.csv')

monarch.columns = monarch.columns.str.lower()
monarch = monarch[~monarch['head'].isna()]
monarch['kg_type'] = 'Generalised'
monarch['kg_source'] = 'Monarch_KG'

monarch['species'] = 'D.melanogaster'
monarch['head_id_is'] = 'NCBI_ID'
monarch['tail_id_is'] = 'Quick_GO'
print(f"monarch: {len(monarch):,} rows")
monarch

monarch: 18,454 rows

,head,relation,tail,head_type,relation_type,tail_type,relation_source,head_detail_name,tail_detail_name,head_taxon_name,tail_taxon_name,head_id_is,tail_id_is,head_name,species,kg_type,kg_source
0,CG2316,Gene_Pathway,R-HSA-390247,Gene,participates_in,Pathway,infores:reactome,ATP binding cassette subfamily D member 1,Beta-oxidation of very long chain fatty acids,Drosophila melanogaster,Homo sapiens,NCBI_ID,Quick_GO,Abcd1,D.melanogaster,Generalised,Monarch_KG
1,CG2316,Gene_Pathway,R-HSA-9603798,Gene,participates_in,Pathway,infores:reactome,ATP binding cassette subfamily D member 1,Class I peroxisomal membrane protein import,Drosophila melanogaster,Homo sapiens,NCBI_ID,Quick_GO,Abcd1,D.melanogaster,Generalised,Monarch_KG
2,CG1587,Gene_Pathway,R-HSA-186763,Gene,participates_in,Pathway,infores:reactome,Crk oncogene,Downstream signal transduction,Drosophila melanogaster,Homo sapiens,NCBI_ID,Quick_GO,Crk,D.melanogaster,Generalised,Monarch_KG
3,CG1587,Gene_Pathway,R-HSA-4420097,Gene,participates_in,Pathway,infores:reactome,Crk oncogene,VEGFA-VEGFR2 Pathway,Drosophila melanogaster,Homo sapiens,NCBI_ID,Quick_GO,Crk,D.melanogaster,Generalised,Monarch_KG
4,CG1587,Gene_Pathway,R-HSA-8849471,Gene,participates_in,Pathway,infores:reactome,Crk oncogene,"PTK6 Regulates RHO GTPases, RAS GTPase and MAP...",Drosophila melanogaster,Homo sapiens,NCBI_ID,Quick_GO,Crk,D.melanogaster,Generalised,Monarch_KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18464,CG34403,Gene_Pathway,R-HSA-9825892,Gene,participates_in,Pathway,infores:reactome,pangolin,Regulation of MITF-M-dependent genes involved ...,Drosophila melanogaster,Homo sapiens,NCBI_ID,Quick_GO,pan,D.melanogaster,Generalised,Monarch_KG
18465,CG1651,Gene_Pathway,R-HSA-6807878,Gene,participates_in,Pathway,infores:reactome,Ankyrin,COPI-mediated anterograde transport,Drosophila melanogaster,Homo sapiens,NCBI_ID,Quick_GO,Ank,D.melanogaster,Generalised,Monarch_KG
18466,CG2316,Gene_Pathway,R-HSA-1369062,Gene,participates_in,Pathway,infores:reactome,ATP binding cassette subfamily D member 1,ABC transporters in lipid homeostasis,Drosophila melanogaster,Homo sapiens,NCBI_ID,Quick_GO,Abcd1,D.melanogaster,Generalised,Monarch_KG
18467,CG2316,Gene_Pathway,R-HSA-2046105,Gene,participates_in,Pathway,infores:reactome,ATP binding cassette subfamily D member 1,Linoleic acid (LA) metabolism,Drosophila melanogaster,Homo sapiens,NCBI_ID,Quick_GO,Abcd1,D.melanogaster,Generalised,Monarch_KG
18468,CG2316,Gene_Pathway,R-HSA-2046106,Gene,participates_in,Pathway,infores:reactome,ATP binding cassette subfamily D member 1,alpha-linolenic acid (ALA) metabolism,Drosophila melanogaster,Homo sapiens,NCBI_ID,Quick_GO,Abcd1,D.melanogaster,Generalised,Monarch_KG

# Consolidate into Unified Schem

In [6]:
# List all source DataFrames to include
source_dfs = [
    monarch
    
]

aligned = []
for df in source_dfs:
    df = df.copy()
    for col in REQUIRED_COLS:
        if col not in df.columns:
            df[col] = None       
    aligned.append(df[REQUIRED_COLS])

final_df = pd.concat(aligned, ignore_index=True)
print(f"Consolidated rows: {len(final_df):,}")
final_df

Consolidated rows: 18,454

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name,species
0,CG2316,Gene_Pathway,R-HSA-390247,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI_ID,Quick_GO,ATP binding cassette subfamily D member 1,Beta-oxidation of very long chain fatty acids,D.melanogaster
1,CG2316,Gene_Pathway,R-HSA-9603798,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI_ID,Quick_GO,ATP binding cassette subfamily D member 1,Class I peroxisomal membrane protein import,D.melanogaster
2,CG1587,Gene_Pathway,R-HSA-186763,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Crk oncogene,Downstream signal transduction,D.melanogaster
3,CG1587,Gene_Pathway,R-HSA-4420097,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Crk oncogene,VEGFA-VEGFR2 Pathway,D.melanogaster
4,CG1587,Gene_Pathway,R-HSA-8849471,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Crk oncogene,"PTK6 Regulates RHO GTPases, RAS GTPase and MAP...",D.melanogaster
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18449,CG34403,Gene_Pathway,R-HSA-9825892,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI_ID,Quick_GO,pangolin,Regulation of MITF-M-dependent genes involved ...,D.melanogaster
18450,CG1651,Gene_Pathway,R-HSA-6807878,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Ankyrin,COPI-mediated anterograde transport,D.melanogaster
18451,CG2316,Gene_Pathway,R-HSA-1369062,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI_ID,Quick_GO,ATP binding cassette subfamily D member 1,ABC transporters in lipid homeostasis,D.melanogaster
18452,CG2316,Gene_Pathway,R-HSA-2046105,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI_ID,Quick_GO,ATP binding cassette subfamily D member 1,Linoleic acid (LA) metabolism,D.melanogaster
18453,CG2316,Gene_Pathway,R-HSA-2046106,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI_ID,Quick_GO,ATP binding cassette subfamily D member 1,alpha-linolenic acid (ALA) metabolism,D.melanogaster

# Sanity Check — Distinct Values

In [7]:
for col in ['relation', 'head_type', 'tail_type', 'relation_type', 'kg_source', 'head_id_is', 'tail_id_is']:
    print(f"{col:20s}: {set(final_df[col])}")

relation            : {'Gene_Pathway'}
head_type           : {'Gene'}
tail_type           : {'Pathway'}
relation_type       : {'participates_in'}
kg_source           : {'Monarch_KG'}
head_id_is          : {'NCBI_ID'}
tail_id_is          : {'Quick_GO'}

In [8]:
# Step 4: drop unresolvable rows
before = len(final_df)
final_df = final_df[~final_df['tail_detail_name'].isna()].reset_index(drop=True)
print(f"Dropped {before - len(final_df):,} unresolvable rows → {len(final_df):,} remaining")

Dropped 0 unresolvable rows → 18,454 remaining

# NaN Audit (pre-dedup)

In [9]:
true_nan   = final_df.isna().sum()
genDR_nan = final_df.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type             0                  0               0
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0
species                   0                  0               0

# Deduplication

In [10]:
def merge_sources(x):
    """Combine unique, non-null source labels with '::' delimiter."""
    return '::'.join(sorted(set(x.dropna())))

group_cols = ['head', 'relation', 'tail']

final_df_dedup = final_df.groupby(group_cols, as_index=False).agg({
    'head_type':        'first',
    'relation_type':    'first',
    'tail_type':        'first',
    'kg_source':        merge_sources,
    'kg_type':          merge_sources,   # ← changed from 'first'
    'head_id_is':       'first',
    'tail_id_is':       'first',
    'head_detail_name': 'first',
    'tail_detail_name': 'first'
})

print(f"Before dedup: {len(final_df):,}  |  After dedup: {len(final_df_dedup):,}")
final_df_dedup.head(3)

Before dedup: 18,454  |  After dedup: 18,454

,head,relation,tail,head_type,relation_type,tail_type,kg_source,kg_type,head_id_is,tail_id_is,head_detail_name,tail_detail_name
0,CG10000,Gene_Pathway,R-HSA-913709,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI_ID,Quick_GO,uncharacterized protein,O-linked glycosylation of mucins
1,CG10001,Gene_Pathway,R-HSA-391906,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Allatostatin A receptor 2,Leukotriene receptors
2,CG10001,Gene_Pathway,R-HSA-416476,Gene,participates_in,Pathway,Monarch_KG,Generalised,NCBI_ID,Quick_GO,Allatostatin A receptor 2,G alpha (q) signalling events

In [11]:
true_nan   = final_df_dedup.isna().sum()
genDR_nan = final_df_dedup.apply(lambda col: col.astype(str).str.upper().eq('NAN').sum())

pd.DataFrame({
    'NaN_count':          true_nan,
    "'NAN'_genDR_count": genDR_nan,
    'Total_NaN_like':     true_nan + genDR_nan
})

                  NaN_count  'NAN'_genDR_count  Total_NaN_like
head                      0                  0               0
relation                  0                  0               0
tail                      0                  0               0
head_type                 0                  0               0
relation_type             0                  0               0
tail_type                 0                  0               0
kg_source                 0                  0               0
kg_type                   0                  0               0
head_id_is                0                  0               0
tail_id_is                0                  0               0
head_detail_name          0                  0               0
tail_detail_name          0                  0               0

In [12]:
print("kg_source values present:", set(final_df_dedup['kg_source']), final_df_dedup['kg_source'].value_counts())

kg_source values present: {'Monarch_KG'} kg_source
Monarch_KG    18454
Name: count, dtype: int64

In [13]:
print("kg_source values present:", set(final_df_dedup['kg_type']), final_df_dedup['kg_type'].value_counts())

kg_source values present: {'Generalised'} kg_type
Generalised    18454
Name: count, dtype: int64

In [14]:
final_df_dedup.to_csv(OUT_PATH, index=False)
print(f"Saved {len(final_df_dedup):,} rows → {OUT_PATH}")

Saved 18,454 rows → /storage/Arushi/090526_EvoAge/kg_formation/processed_data_relation_wise_merge/generalised/OTHER_SPECIES/Drosophila/Drosophila_gene_pathway/Drosophila_gene_pathway.csv

In [15]:
#